### PR TITLE
Added processing Tilde (~) sign in filename:absname

### PR DESCRIPTION
**Pull request by dieu**
absname(~/foo) -> path_to_current_home/foo
absname(~/../x) -> path_to_current_home/../x
absname(~/) -> path_to_current_home

### CODE REVIEW

**Comment by mikpe** [comment]
Strongly disagree.  This changes absname in an incompatible way.  If you want this functionality, it should be in a convenience layer above the filename module, or as a convenience add-on to that module.

**Comment by dieu** [comment]
@mikpe thank for your feedback. Can you explain where exactly are incompatible this changes?

And how you think it should be implemented?

**Comment by mikpe** [comment]
Tilde is a perfectly valid character in a UNIX file name, and you're changing the behaviour for file names starting with tilde.  That's by definition incompatible.

Just put this new behaviour in a new function, then there's no compatibility issue.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
I agree with @mikpe that the change is incompatible and not acceptable.

**Pull request closed without merging**
