### PR TITLE
epmd: fix local peer detection on inet6 socket

### PR DESCRIPTION
**Pull request by stolen**
epmd compiled on OS X with CFLAGS=-DEPMD6 failed to detect a connection
from 127.0.0.1 (as erl_epmd:register_node/2 does) as local.

This led to disconnects on node registration request and
made nodes unable to start with distribution enabled.

This pull request makes the code responsible for local peer detection
IPv6-aware which fixes node registration issue.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by stolen** [comment]
I've just noticed that PR #602 fixes the IPv6 local peer issue too.
If you accept PR #602, please close this one.

**Comment by IngelaAndin** [comment]
PR 864 is now on its way to be accepted, and then we hopefully can get somewhere with this PR and PR 602.

**Comment by IngelaAndin** [comment]
I have now merged PR 864, should be visible soon at github. When it is please consider the consequences for this PR and maybe rebase it.

Also the following diff that is now being tested and hopefully merged tomorrow as an improvment
to the original PR 864.

```
diff --git a/erts/epmd/src/epmd_srv.c b/erts/epmd/src/epmd_srv.c
index 55ec0f7..e1bac99 100644
--- a/erts/epmd/src/epmd_srv.c
+++ b/erts/epmd/src/epmd_srv.c
@@ -380,7 +380,7 @@ void run(EpmdVars *g)
              epmd_cleanup_exit(g,1);
      }
    }
-      g->listenfd[i] = listensock[i];
+      g->listenfd[bound++] = listensock[i];

 #if HAVE_DECL_IPV6_V6ONLY
       opt = 1;
@@ -439,8 +439,6 @@ void run(EpmdVars *g)
        }
    }

-      bound++;
-
       if(listen(listensock[i], SOMAXCONN) < 0) {
           dbg_perror(g,"failed to listen on socket");
           epmd_cleanup_exit(g,1);
@@ -451,6 +449,7 @@ void run(EpmdVars *g)
       dbg_perror(g,"unable to bind any address");
       epmd_cleanup_exit(g,1);
   }
+  num_sockets = bound;
 #ifdef HAVE_SYSTEMD_DAEMON
     }
     sd_notifyf(0, "READY=1\n"
@@ -495,8 +494,8 @@ void run(EpmdVars *g)
    }

    for (i = 0; i < num_sockets; i++)
-     if (FD_ISSET(listensock[i],&read_mask)) {
-       if (do_accept(g, listensock[i]) && g->active_conn < g->max_conn) {
+     if (FD_ISSET(g->listenfd[i],&read_mask)) {
+       if (do_accept(g, g->listenfd[i]) && g->active_conn < g->max_conn) {
          /*
           * The accept() succeeded, and we have at least one file
           * descriptor still free, which means that another accept()


```

**Comment by IngelaAndin** [comment]
Actually I think PR 864 solves all problems addressed here, so I will close this one.

**Pull request closed without merging**
