### PR TITLE
queue, maps, proplists: add since information to docs for new functions

### PR DESCRIPTION
**Pull request by Maria-12648430**
In past PRs #2791, #2850, #2900 and #2910, I contributed some new functions to the `queue`, `maps` and `proplists` modules, but forgot to add the `since` information in the documentation.

### CODE REVIEW

**Comment by garazdawi** [comment]
thanks! Someone should really write a script that makes sure that we always add `since` information for any new functions...

**Comment by Maria-12648430** [comment]
@garazdawi with that in mind, what should a contributor of new functions put as since when writing the documentation? In the past PRs, I wan't sure in which OTP release they would appear so left them blank, and then forgot ^^;;;

**Comment by garazdawi** [comment]
> @garazdawi with that in mind, what should a contributor of new functions put as since when writing the documentation? In the past PRs, I wan't sure in which OTP release they would appear so left them blank, and then forgot ^^;;;

You need to ask the OTP maintainer responsible for the feature to provide a ticket number to put there. Or rather, the OTP maintainer should remember to ask you to put a ticket number there.

Like this: https://github.com/erlang/otp/blob/master/erts/doc/src/erlang.xml#L319

As a placeholder, I normally put `@OTP-12345@` to distinguish from functions that have no `since` version.

We use an automatic versioning tool that determines how a version should be bumped depending on what the tickets that are part of the release contain. For the major OTP versions it is rather predictable, but for the individual applications you can end up with only a patch dump in an OTP major release.

**Comment by Maria-12648430** [comment]
Ok, thanks :)

**Comment by Maria-12648430** [comment]
@garazdawi an afterthought... sorry to bother you =^^=
The copyright years in the modules that I changed, I didn't "bump" those. Should I have? ^^;;;

**Comment by garazdawi** [comment]
We bump all of those with a script automatically, so no need.

**Comment by Maria-12648430** [comment]
Ok, thanks again :)

**Pull request merged**
