### PR TITLE
WIP - Optimize compile time by changing datastructures

### PR DESCRIPTION
**Pull request by psyeugenic**
Change some of the data structures to Maps to gain some speed.

Preliminary findings using `time erlc $testfile` and best of three:

`$testfile` |  `OTP-18.0-rc2-1-g9a81b28` |  `OTP-18.0-rc2-18-g43a4893`
-----|---|----
NBAP-PDU-Contents.asn |  26146 ms  | 22810 ms
erl_parse.erl | 1591 ms | 1439 ms
lists.erl  | 579 ms  | 518 ms

This is about ~10% improvement.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by josevalim** [comment]
I was literally trying this in some places now. :D You probably know this but in Elixir we also got better performance in some cases by replacing sets by maps where the value is `true`.

**Comment by essen** [comment]
@psyeugenic Here is another file you may find interesting for optimizing the compiler: https://github.com/ninenines/cowlib/blob/master/src/cow_http_hd.erl

It has two include files required: https://github.com/ninenines/cowlib/tree/master/include

In this one's case it's mostly huge guards. It takes a few seconds to compile on my machine currently. Feel free to take a stab at it. :-)

**Comment by kostis** [comment]
A word of caution: gb_sets and gb_trees are data structures that are "optimized for Big-O complexity", i.e., they give guaranteed O(log(n)) times for insertion and lookup at the expense of their operations being heavier.

Asking out of curiosity, are maps in 18.0 efficient enough to guarantee O(log(n)) complexity, or better, for insertion and lookup, or are there still cases where O(n) operations are taking place?

**Comment by psyeugenic** [comment]
@kostis That is a reasonable concern. Maps has a time complexity of O(log(n)) for inserts and lookups and has a very low constant before that O. The Maps tree is probabilistically balanced, i.e. it is a function of the hash-function so for a reasonable large set of data you will, by law of distribution, have reasonable balanced tree. Assuming a good hash-function.

A couple of things to note. Maps has a shallower tree than gb_trees, which means lookups are much faster in Maps. There is only one key compare per lookup in Maps versus one at each level for gb_trees. The other thing is, for few elements in a Map, i.e. fewer than 33, we do linear searches. This is usually pretty fast though due to locality but 32 elements is on the upper limit .. I would like to lower it. That's my concern at least.

There are ofc cases where Maps would be less ideal than say gb_trees but I would say Maps is an overall improvement in this particular case. And of course, if you need an ordered set then gb_trees is what you want in most cases. It depends on the situation.

**Comment by psyeugenic** [comment]
Preliminary findings using `time erlc $testfile` and best of three:

`$testfile` |  `OTP-18.0-rc2-1-g9a81b28` |  `OTP-18.0-rc2-19-g4c9459a`
-----|---|----
NBAP-PDU-Contents.asn |  26146 ms  | 22668 ms
erl_parse.erl | 1591 ms | 1436 ms
lists.erl  | 579 ms  | 513 ms
cow_http_hd.erl | 7530 ms | 6511 ms

There is at least one other bottleneck that irritates me and that's `v3_lifes` Variable lifetime mapping used by `v3_codegen`. However I think we'll save that one for when we remove the `v3_life` pass. What little is done it that pass should be move to `v3_codegen` and/or `v3_kernel`.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by josevalim** [comment]
I can confirm those results too. I merged this with my other patches and compiling Elixir (both erl+elixir sources) is about 15% faster than Erlang 17. I will continue using those patches to see if anything weird pops up.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Merge branch 'hans/ssh/ssh_msg_debug_fun/OTP-12738' into maint-17
Merge branch 'hans/inets/bad_content_length/OTP-12739' into maint-17
ssh: option for handling the SSH_MSG_DEBUG message's printouts


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Moved (merged) `maps:filter/2` to master and rebased this branch to current master.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
