### PR TITLE
Drop old code for handling pre-R15 abstract format

### PR DESCRIPTION
**Pull request by richcarl**
This code seems safe to remove now.

### CODE REVIEW

**Comment by gomoripeti** [comment]
What's the approach for occurrence of such old format in the docs? (does not hurt to keep for historical insight, but keeping all formats that ever existed would clutter the docs) https://github.com/erlang/otp/blob/master/erts/doc/src/absform.xml#L374

**Comment by richcarl** [comment]
@gomoripeti Thanks, removed from doc as well.

**Comment by bjorng** [comment]
The test case `xref_SUITE:fun_mfa_r14/1` in the tools application fails.

**Comment by bjorng** [comment]
@richcarl I have pushed a fixup commit that removes the failing test case. Please squash!

**Pull request merged**
