### PR TITLE
gen_statem Auto Callback Mode (OTP-13752)

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
After the dust settled in the discussion about the new `gen_statem` behaviour (#960) I had time to contemplate and think I will make use of the disclaimer about the new behaviour being somewhat experimental...

#### Selecting Callback Mode

During the discussion I think it was suggested that `gen_statem` could automatically select callback mode depending on which callbacks that were exported, and it was dismissed for some then good reason.  I think one reason was that the `handle_event` and `StateName` callbacks during that time in the discussion had the same arity, and that another reason was efficiency.

As I see it now it is very possible to select callback mode automatically, so that is what this pull request implements: if `Module:handle_event/4` is exported it is called, and if not `Module:StateName/3` is called.  Efficiency is achieved by only testing `erlang:function_exported(Module, handle_event, 4)` once after `Module:init/1` and `Module:code_change/4`, caching the result.

#### Code Downgrade

This solves the annoying problem of code downgrade (which is why I started to think about this solution in the first place).  The new code from which you can make a code change back to an earlier version now does not have to know the callback mode of the old code, since it is defined by the old code.

#### Backwards Incompatibility

It would be possible to make this change backwards compatible by allowing e.g `Module:init/1` to return `{ callback_mode() | ok, ... }` and to only do an automatic callback mode selection only if `ok` is the first element of the returned tuple, but I think there is no benefit in the added complexity.

I think it is better to use the possibility to make a backwards incompatible change for the better (cleaner code and documentation) of an experimental behaviour.

Also see the changes to the SSH and SSL applications in the diff; they are small and simple.  Rewriting for this change is not hard, and more compatible to the older `gen_fsm` and `gen_server` behaviours.

#### Callback Flavour

In the documentation I have stopped talking  about Callback Mode and make a lesser point of it by instead talking briefly about two Callback Flavours: State Name Functions versus One State Function.  Then the important point is whether `Module:handle_event/4` is exported or not.

### CODE REVIEW

**Comment by ferd** [comment]
I'm on vacation and had no time to look at the code change, but the proposal itself sounds good and I'd personally be positive towards backwards incompatible changes given they were advertised as possible

**Comment by antipax** [comment]
Hi everyone! gen_statem is awesome, and thanks for all your hard work! Just to introduce myself a bit, I'm the maintainer of an Elixir wrapper for gen_statem, for what it's worth. :) 

That being said, I'm sort of worried that this behavior is a little too implicit, and could result in a confusing user experience. For instance, if a user defines `handle_event/4`, which is explicitly called by "event functions"-style callbacks for events which should be handled in any state, all of a sudden their `gen_statem` will start ignoring the existing callbacks. If such a `handle_event/4` is defined with a no-op catch-all clause, it could be difficult to determine what has changed. The response to this might be "don't use `handle_event/4` for that," but I'm not sure that is adequate for beginners.

Additionally, if a user accidentally mis-defines `handle_event/4`, with a different name, or different arity, they will not receive a warning, and the error messages could be confusing, since they would presumably complain about an undefined `StateName/3` callback.

I guess the question then, is whether my concerns are valid. If so, a further question is whether they can be addressed in a way that preserves the new behavior, or whether the difficulty (albeit explicit difficulty) around downgrades (which are presumably a fairly rare event), is worth the extra potential confusion in day-to-day use.

If we agree that my concerns are valid, I would propose an alternative: a new callback function which returns the desired callback mode. This way, the downgrade story is simplified (as the code will contain the needed information), and the explicit selection of callback mode is preserved.

Again, thanks for your hard work, and great job on `gen_statem` so far. Looking forward to your thoughts!

**Comment by RaimoNiskanen** [comment]
@antipax

Yes. I have the same concerns, and created this suggestion to see if anyone else thought of it as a problem :-)

My first idea was to havie a mandatory callback `Module:callback_mode/0` that should return `state_functions` or `handle_event_function` but saw the opportunity to make the choice even simpler, and to get less talk in the manual about The Callback Mode.  This concept is not a new one; try one callback first and then a fallback, with the fallback in this case being `Module:StateName/3`. But the question is now whether the choice got to implicit?

That you can not use an exported `handle_event/4` for handling common events in state functions mode, for example through `-compile(export_all).` is tricky, sneaky and a hard to find bug.

**Comment by essen** [comment]
I don't think this is implicit at all, what function you export is explicit. You see this kind of thing already in most Erlang web app with how webmachine/cowboy_rest deals with callbacks (check exports, call if exported, use default instead). A similar thing already exists in gen_server and friends, with the format_error function. Deciding what to do based on exports is common.

Also `-compile(export_all).` is bad practice and uncommon (except in ct test suites perhaps). I wouldn't worry too much about that one. If you do, you can always check for the compile flag before checking the exports and issue a warning when it is detected.

**Comment by okeuday** [comment]
The main problem with relying upon the export may be making sure `handle_event/4` either exists or is removed, if it is necessary to switch between the callback modes with a module update.  That may be abnormally complicated if it is desirable to test either way with a single module.  However, those concerns should appear rarely in practice and the problems are not insurmountable.

**Comment by RaimoNiskanen** [comment]
I have now created a new pull request #1135 that uses `Module:callback_mode/0` to select Callback Mode.

**Comment by antipax** [comment]
@essen While I agree that exporting functions is an explicit action, I would argue that changing behavior based on those exports is indeed implicit, since you will not directly be able to see the effect of your actions as part of the code you have written. 

`format_status` (I assume that's what you meant when you mentioned `format_error`) is quite different from this case to me, because its exportation will not affect the functionality of the rest of your code. If it is exported, it overrides the behavior, and if it is not, it does not. To me, this is simpler to reason about and seems to violate the "principle of least surprise" less than the proposed auto-callback-mode.


In general, I think the smaller size of #1135 is a good signal that it is solving the problem with the least additional complexity, and thus is the better solution.

**Comment by okeuday** [comment]
@RaimoNiskanen I still prefer the way the `gen_statem` is currently due to it being clear and explicit (self-descriptive).  Also, it should be more intuitive for developers due to being an example of normal Inversion of Control.  Adding a new `Module:callback_mode/0` function increases the complexity to pretend the callback mode is a function when it really is data associated with the process.  Using the `Module:handle_event/4` export doesn't necessarily improve the usability, due to causing difficulties for testing and maintenance if the callback mode is switched for upgrade/downgrade.

**Comment by RaimoNiskanen** [comment]
@okeuday

The way `gen_statem` currently selects callback mode i.e with a return value from `Module:init/1` and `Module:code_change/4` does not work well during code downgrade.

This is since `Module:code_change/4` during a downgrade is executed in the new code and hence the new code will have to somehow know the callback mode of all old code versions that it can have had upgraded from.  This is an administrative problem, and an awkward one.  I think it is a problem that ought to be solved.

It would be better if the callback mode could be decided from the executing code after an upgrade or after a downgrade.  One way would be to check if some function e.g `Module:handle_event/4` is exported in the current code version, and another way would be to ask the current code through a callback function e.g `Module:callback_mode/0`.

I think it is the fact that the callback mode currently is data associated with the process that is the problem.  It should be a property of the current callback module to solve the downgrade problem.

**Comment by okeuday** [comment]
@RaimoNiskanen Then the `Module:callback_mode/0` approach in #1135 seems best due to explicitly making it a function that is not only internal process data.  That makes it easier to track which callback mode it is and doesn't create problems if you want source code for both callback modes to coexist during a switch between them.

If `Module:code_change/4` become `Module:code_change/5` with the callback mode added to the input as `OldCallbackMode` by changing the `gen_statem` `system_code_change` function, that can also solve the downgrade in a more direct way, keeping it as process data.  I know that may be odd when compared to other behaviours, but is there a reason to not take that approach?

**Comment by RaimoNiskanen** [comment]
@okeuday The release handler can not know the callback mode of the old code version.  It is only the programmer that wrote the code that can know it.  Or could be found out by calling `Module:code_change/4` on the old code after a downgrade, but that is not done for any other behaviour and would be a new concept for the Design Principles...

Therefore this suggestion about a dedicated callback function.

The alternative: not allow changing callback modes during code change also does not work well since we then could do an upgrade keeping the callback mode, and then when restarting the new code it can actually use the other callback mode returned from `Module:init/1`.  Doing a downgrade from that point would mess it up even further!

So it is not an alternative to disallow changing callback modes during code change.  The only remaining alternative to facilitating callback mode change during code change would be to do a clean split of `gen_statem` into two behaviours since you can not change behaviours in a code change.  A server written for one callback mode = behaviour will forever stay in that mode.

Unless you do a server restart during upgrade/downgrade, that is...

**Comment by okeuday** [comment]
@RaimoNiskanen before `Module:code_change/5` would be called with an argument `OldCallbackMode` it would be at [`gen_statem:system_code_change/4`](https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen_statem.erl#L623) and since the `callback_mode` value is stored in the internal `gen_statem` state map (at https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen_statem.erl#L534), it can be taken before calling `Module:code_change/5`, the same way the `Module`, `State`, and `Data` arguments are taken from the internal state.  So, the release handler doesn't know or care about the callback mode, only the `gen_statem` module.  Right?

**Comment by RaimoNiskanen** [comment]
@okeuday Aah, I see.  You are exploring the track of making this truly a property of the process...

Well, during the upgrade the code is changed, then `Module:code_change/5` in the new code is called with `OldCallbackMode`.  The new code may change callback mode.  The new value is stored in the `gen_statem` engine state map.

Then comes the downgrade and the callback mode of the old code version is lost since now the `gen_statem` engine state map contains the current callback mode.

If we would store the previous callback mode in the `gen_statem` engine state map we could give that as `OldCallbackMode` instead, but I think we can get a server restart wiping that before doing a downgrade, so the previous callback mode of the server is not the same as the callback mode of the code we are downgrading to.

I think this reasoning confirms that the callback mode should be a property of the code, not of the server process...

**Comment by okeuday** [comment]
@RaimoNiskanen Yeah, that makes sense.  Thank you for explaining the issue with that approach.  My view is that https://github.com/erlang/otp/pull/1135 is best due to being explicit, allowing the source code for both callback modes to coexist if necessary, just for testing purposes.

**Comment by RaimoNiskanen** [comment]
@okeuday I agree; #1135 is better since it makes the callback mode more obvious. And it is possible to test both modes as the test cases do in that branch by sneakingly storing the callback mode in an ETS table.

In this branch I had to dynamically compile two text binaries containing module source code with the same module name differing in their export of `handle_event/4` and change code between them...

**Comment by RaimoNiskanen** [comment]
I have added links to documentation to #1135.  Please review!

**Comment by RaimoNiskanen** [comment]
I have now merged #1135 instead; closing this one.

**Pull request closed without merging**
