### PR TITLE
yecc: Avoid compilation errors if atoms become reserved words

### PR DESCRIPTION
**Pull request by bjorng**
In code generated by `yecc`, only atoms known to be reserved words
would be quoted. If a generated module is later compiled with a
version of the compiler that has made one of the used atoms a
reserved word, compilation would fail.

Avoid the problem by having `yecc` code quote all atoms in the
generated code.

### CODE REVIEW

**Comment by lisztspace** [comment]
Reasonable change since the generated code will be precise and consistent rather than trying to be terse when possible.  Making it future safe is a good property as it will not force recompiles just because a used atoms become reserved.

Testing this on a small grammar described pleasant S-expressions.

```
Nonterminals list elements element.
Terminals atom '(' ')'.
Rootsymbol list.
list -> '(' ')' : nil.
list -> '(' elements ')' : '$2'.
elements -> element : {cons, '$1', nil}.
elements -> element elements : {cons, '$1', '$2'}.
element -> atom : '$1'.
element -> list : '$1'.
```

I found, e.g., a function previously generated as `yeccgoto_element` now being generated as `yeccgoto_101108101109101110116`.  While technically not a problem (and at least "readable") that was perhaps not the intent of the change.  This is consistent for all functions related to non terminals.

```
-dialyzer({nowarn_function, yeccgoto_101108101109101110116/7}).
-compile({nowarn_unused_function,  yeccgoto_101108101109101110116/7}).
yeccgoto_101108101109101110116(2, Cat, Ss, Stack, T, Ts, Tzr) ->
 yeccpars2_5(5, Cat, Ss, Stack, T, Ts, Tzr);
yeccgoto_101108101109101110116(5, Cat, Ss, Stack, T, Ts, Tzr) ->
 yeccpars2_5(5, Cat, Ss, Stack, T, Ts, Tzr).
```

I also expected my included atoms, i.e., `cons` and `nil` to be quoted, but I see

```
-compile({inline,yeccpars2_5_/1}).
-dialyzer({nowarn_function, yeccpars2_5_/1}).
-compile({nowarn_unused_function,  yeccpars2_5_/1}).
-file("sexpr.yrl", 2).
yeccpars2_5_(__Stack0) ->
 [___1 | __Stack] = __Stack0,
 [begin
                      {cons, ___1, nil}
  end | __Stack].
```

There are still a large number of unquoted atoms in the generated file and any inlined Erlang code (after `Erlang code.`) seems to be untouched as well.  Have I misunderstood the intent?  Also, to be really paranoid about this, shouldn't even module names and function names be quoted?  If they are not, having a function named `maybe` will cause problems when EEP49 is introduced, although this problem can be circumvented by compiling the file with `--disable-feature=maybe` (thereby showing that it makes sense to have that ability).

**Comment by lisztspace** [comment]
> There are still a large number of unquoted atoms in the generated file and any inlined Erlang code (after `Erlang code.`) seems to be untouched as well.

The inlined code is of course difficult to do anything about since it is just copied verbatim (Syntax errors and all) to the output.  Fixing that can be done, but is a major change in the workings of `yecc` since it would require reading the verbatim code printing it in _quoting atoms mode_.

**Comment by bjorng** [comment]
> I found, e.g., a function previously generated as `yeccgoto_element` now being generated as `yeccgoto_101108101109101110116`.

That was unintentional. Fixed now.

**Comment by bjorng** [comment]
> > There are still a large number of unquoted atoms in the generated file and any inlined Erlang code (after `Erlang code.`) seems to be untouched as well.
> 
> The inlined code is of course difficult to do anything about since it is just copied verbatim (Syntax errors and all) to the output. Fixing that can be done, but is a major change in the workings of `yecc` since it would require reading the verbatim code printing it in _quoting atoms mode_.

Yes, I don't want to change the reading of the code after `Erlang code.`. That could cause unforeseen problems.

However, it is easy to quote atoms in embedded actions, but I don't think that would be appropriate. To show why, consider this example:

```
maybe_expr -> 'maybe' maybe_match_exprs 'end' :
	{maybe,?anno('$1'),'$2'}.
```

If `yecc` were to quote atoms in the generated Erlang code, everything would work **now**. But in some release in the future, `maybe` will probably become a reserved word, and when that happens, `yecc` will read the unquoted `maybe` as a keyword and output it as an unquoted keyword. That will result in a syntax error when trying to compile the generated module. Therefore, it is better to force the implementer of an experimental new feature to quote all atoms that are likely to become reserved words:

```
maybe_expr -> 'maybe' maybe_match_exprs 'end' :
	{'maybe',?anno('$1'),'$2'}.
```

**Comment by bjorng** [comment]
To clarify the intent of this PR: In the code generated by `yecc`, all terminals in the grammar (tokens such `maybe` or `else`) would be used as atoms. Those atoms would be quoted when they were symbols (such as `?=`) or previously known reserved words (such as `case`), but would otherwise be unquoted. This PR quotes all atoms used in that way.

**Comment by lisztspace** [comment]
> To clarify the intent of this PR: In the code generated by `yecc`, all terminals in the grammar (tokens such `maybe` or `else`) would be used as atoms. Those atoms would be quoted when they were symbols (such as `?=`) or previously known reserved words (such as `case`), but would otherwise be unquoted. This PR quotes all atoms used in that way.

Good with this clarification, which then makes the scope appropriate.

**Review by lisztspace — APPROVED** [review]
Approved after fixing the mangling of names and the scope clarification.

**Pull request merged**
