### PR TITLE
Dialyzer to cache results of HiPE compilation

### PR DESCRIPTION
**Pull request by legoscia**
When the `--native_cache` option is specified, cache the results of native
compilation in `~/.dialyze_hipe_cache/ARCH-VERSION`, where ARCH is the
HiPE architecture and VERSION is the HiPE version number.  This can
reduce the startup time significantly.

Also make the compiler obey `outdir` when using the `from_beam` option.

### CODE REVIEW

**Comment by bjorng** [comment]
I like the idea of speeding up Dialyzer, but I don't like having to give an option every time to tell Dialyzer to use its cache. I would want the cache to be default and use the --no_native_cache option to turn it off.

There is also one other thing. To be sure that the system can load the native code, it is not enough to test hipe architecture and hipe version. You'll need to also check HIPE_SYSTEM_CRC. Unfortunately, it seems that you will need to include lib/hipe/rtl/hipe_literals.hrl. With that file included, ?HIPE_SYSTEM_CRC will return an integer that you can include in the directory along with hipe version and architecture.

@mikpe: Is there a better/more portable way to check that the native code is loadable?

**Comment by mikpe** [comment]
@bjorng: Not currently.  The HiPE compiler tags object files with a "system crc" cookie based on (a) the VM running at the time of compilation, and (b) the VM that compiled the HiPE compiler itself.  The HiPE loader checks the system crc of an object file against that of the running VM before attempting to load native code.

In your use case, you need to compute the system crc of the VM when compiling modules and to add that to the paths of the .beam files; I'd suggest to simply put them in a directory where the directory name is the system crc.  When checking for precompiled code, use the then-current system crc to form a path and look there.

A problem is point (b) above: ?HIPE_SYSTEM_CRC expands into a call to a HiPE BIF with a parameter which is a hidden cookie from the VM that generated hipe_literals.hrl.  This means that the .beam code that contains the call is tied to a particular version of the VM.  I don't think that's appropriate (here or in HiPE).  So I'd suggest that you change hipe_bifs:system_crc/1 to /0 (just return the damn thing) and adjust hipe_mkliterals.c to match.  Then you call hipe_bifs:system_crc/0 and use that to name the cache directory -- no need to include hipe_literals.hrl.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Ping @legoscia

**Comment by legoscia** [comment]
Sorry about the delay; I was busy with another project. I changed the system_crc BIF, reversed the sense of the command line option, and rebased everything to the current state of the `maint` branch. Does this look sensible?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
I really like the speed of running dialyzer on a single application when the native code is cached!

We test the branch in our daily builds for the master branch to make sure that it doesn't break anything.

Then I would like to reduce the number of commits. I think that the first commit that changes compile.erl should be removed since it is not needed, the commit "Change hipe_bifs:system_crc/1 to hipe_bifs:system_crc/0" should be retained as separate commit, and all the remaining commits should be  combined into a single commit.

Could you combine the commits like I described and at the same time rebase your branch on master?

**Comment by legoscia** [comment]
There, rebased and squashed. Apparently there is no way to change the target branch of a pull request (isaacs/github#18), so it appears a bit unwieldy now.

**Comment by bjorng** [comment]
Thanks! Looks good.

There is only one thing that we discussed in out group at OTP (and I am personally in a bit of split mind over the matter). That thing is the message when a compiled module is put into the cache. I see the advantage that the user may understand what is happening (especially if something goes wrong), but otherwise the verbose messages are quite annoying.

So our opinion is that the messages should be removed. Any thoughts about that? Any good reason to keep the messages?

If you agree that the message should be removed, I can amend the commit to do that change.

**Comment by legoscia** [comment]
Indeed, the messages are quite verbose. They were helpful while debugging this thing, but I guess they don't serve much of a purpose now.

**Comment by bjorng** [comment]
OK. I will amend the commit.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: code: Reduce overhead of native code checking for loaded modules


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Merged.

**Pull request closed without merging**
