### PR TITLE
High performance atomic mutable counters

### PR DESCRIPTION
**Pull request by sverker**
Closed and replaced by #1961

This is a new module 'counters' that provides functions to do atomic operations towards **mutable word sized counter variables**. The implementation utilizes only atomic hardware instructions without any software level locking, which makes it very efficient for concurrent access. The counters are organized into arrays with the follwing semantics:

- Counters are signed word sized. That is 32-bit (-2147483648 to +2147483647) or 64-bit (-9223372036854775808 to +9223372036854775807) depending on cpu hardware architecture.
- Counters wrap around at overflow and underflow operations.
- All counter operations are atomic. No intermediate results can be seen. Concurrent mutable operations to the same counter are serialized. The result of one mutation can only be the input to one following mutation.
- All counter operations are ordered (using hardware memory barriers). If counter B is updated **after** counter A, then that is how it will appear to any concurrent readers. No one can read the new value of B and then read the old value of A.
- Indexes into counter arrays are zero-based. A counter array of arity N contains N counters with index from 0 to N-1.

Create counter array with
`counters:new(Arity, Opts) -> Ref.`

Atomic read/write operation on one counter:
`counters:put(Ref, Ix, Value) -> ok.`
`counters:get(Ref, Ix) -> Value.`
`counters:add(Ref, Ix, Incr) -> ok.`
`counters:add_get(Ref, Ix, Incr) -> Value.`
`counters:sub(Ref, Ix, Decr) -> ok.`
`counters:sub_get(Ref, Ix, Decr) -> Value.`

And some static info about a counter array:
`counters:size(Ref) -> Arity.`
`counters:max(Ref) -> MaxValue.`
`counters:min(Ref) -> MinValue.`

### CODE REVIEW

**Comment by fenollp** [comment]
* Since this is mostly about atomic semantics (and may be extended to more than just integers some day?) shouldn't the module be named `atomic` instead of `counters`?
* Can a micro benchmark be added to the testing benchmark suite?
* Shouldn't there be a way to delete/remove/erase counters?
* Should there be a variant of the API that returns ok|error tuples instead of throwing an exception?
* If the write operations are serialized, how about reads?
* If operations are serialized, how is this expected to compare with using `erlang:get/1` & `erlang:put/2`, with/without using a process for serialization?
* How is this expected to compare with a counter backed by ETS?
* How is this expected to be used within Ericsson?

Thanks

**Comment by sverker** [comment]
> Shouldn't there be a way to delete/remove/erase counters?

The GC will reclaim counter arrays when last ref is lost. One could imagine a delete/remove/erase/close/kill function to not have to wait for the GC to reclaim the memory, but that would cost one extra pointer indirection at every operation.

> If the write operations are serialized, how about reads?

Maybe I'm using confusing terminology. Serializing writes just means the output of one write op is only input to one next write op. Not sure what serializing reads would mean in this context.

> If operations are serialized, how is this expected to compare with using erlang:get/1 & erlang:put/2, with/without using a process for serialization?

Serializing here is only done with single atomic machine instructions. Serializing via an Erlang process will use software level locking and process scheduling which in the end is done by lots of atomic machine instructions.

So, it's expected to perform better than process serialization and ets:update_counter. That's the main reason for this module.

**Comment by essen** [comment]
This is one of the features added to Ling that provided the biggest speed up if I recall (been a few years). Can already think of many use cases. Exciting!

**Comment by ferd** [comment]
Uh, so... this is kind of a major model change to everything everywhere ever mentioned about the Erlang memory model, where nothing would have been shared except for refc binaries.

On top of the questions asked by @fenollp I would ask:

- Am I going to be able to inspect the memory allocated to these counters? Refc binary leaks is one of the most common and worst ways to leak a crapload of memory. Refc binaries were even introduced to help lower memory by sharing it. Here we're getting a new mechanism that seemingly works the same way, for which I would expect as many leaks, but for which there is no prospective memory savings. How can I debug this stuff?
- What's the rationale in using a signed number instead of unsigned?
- Are there max sizes/lengths to the arrays?
- If there is no way to get slices and work with offsets, why pick a 0-index rather than a 1-index like most other positional data structure in Erlang (ETS index, tuple positions, list `nth` values, etc.)
- max/1 and min/1 sound like they return the maximal element in a counter array. Since the min and max values are based on a word size, why not just have a max/0 and min/0 function that prevents all confusion?
- Is there an expectation that refs from a remote counter should work the way Pids work, or rather should they not be distributable (the way ETS refs work). I assume the latter, but it is unspecified.

**Comment by silviucpp** [comment]
@ferd Same way works any NIF libraries when you are using enif_open_resource_type / enif_alloc_resource. In erlang it returns a reference and that native memory (usually a c struct) is released when last reference gone on the erlang side. Is nothing new in this counters memory model. 

Silviu

**Comment by sverker** [comment]
Maybe a "delete" function is inevitable. But it would mean a pointer indirection from a minimal block (kept alive for the gc) to the actual counter array, deallocated by "delete". This is how ETS tables are organized.

Choosing signed just to be least surprising when decrementing below zero by mistake. A signed/unsigned option to counters:new is easy to add.

At the moment no max size of arrays other than available memory.

Maybe it would be worth a couple of extra cpu cycles to get a nice Erlangish 1-index. But then again, this is not the typical nice Erlang module, with its blasphemous mutable semantics.

I choose min/1 and max/1 as I anticipate options for counters:new (like signed/unsigned) that would make then depend on the array.

The refs work like ETS table refs and NIF resources (from OTP-20). They survive a distribution roundtrip but a remote ref will not keep a counter array alive.

**Comment by vans163** [comment]
This is much needed for some particular use cases. For example a crypto mining pool, where your incrementing a nonce for 1m+ connected miners, (1m+ atomic increments in the span of ideally under 50ms), every millisecond lost here is 1ms a miner spends mining a stale block.

Would it be possible thought instead of having a ref, to have a way to lookup the ref?
```
next_nonce = counters:add({nonce, etn}, 1)
next_nonce = counters:add({nonce, etn}, 1)
..

next_nonce_otherchain = counters:add({nonce, eth}, 1)

#new block
counters:set({nonce, etn}, 0)
```

**Comment by ferd** [comment]
That is a terrible way to handle nonces since every restart would repeat the values sent before and it would provide an easy attack vector.

If you want safe nonce you have to be able to provide some amount of statefulness storing the latest value seen and/or using some form of a safe seed to initiate the counter with, and doing that would likely require the kind of state and boundary checks that would nullify the benefits of being able to use 'named refs for counters' anyway.

**Comment by g-andrade** [comment]
Great feature!

@sverker 
> All counter operations are ordered (using hardware memory barriers). If counter B is updated after counter A, then that is how it will appear to any concurrent readers. No one can read the new value of B and then read the old value of A.

Would it be too much of a hassle to allow for memory order customization (in, say, extended versions of the basic API functions, which allow for options?) 

In my mind, the ideal end result of this PR would approximate C++'s [std::atomic](https://en.cppreference.com/w/cpp/atomic/atomic) API and allow one to atomically manipulate memory words as in [vegrandis](https://github.com/g-andrade/vegrandis), only with full integration with the stdlib (and much more attention payed to performance.)

**Comment by OvermindDL1** [comment]
I don't suppose there is any chance in a CAS (Compare-And-Swap) operation added to this?

**Comment by okeuday** [comment]
@sverker Thank you for adding this!  Is it possible to add 'and', 'or', and 'xor'?  At the very least 'xor' should be useful for hashing data in an efficient way.

**Comment by benoitc** [comment]
@ferd what do you mean by 

> For CAS you at least have it already in ETS counters. So that is still usable for such cases, and faster than any message-based coordination for these.

you mean the threshold?

**Comment by benoitc** [comment]
@sverker would be good to have a way to have a public name for the counter like ETS. IT would remove one roundtrip to get such counter (like keeping it in ETS.

**Comment by ferd** [comment]
@benoitc regarding CAS, the newer releases have `ets:select_replace(Tab, MatchSpec) -> NumReplaced` that allows a compare-and-swap operation:

> Matches the objects in the table Tab using a match specification. For each matched object, the existing object is replaced with the match specification result.
>
> The match-and-replace operation for each individual object is guaranteed to be atomic and isolated. [...]
> 

See for example:

```erlang
1> T = ets:new(t, [set, public]).
#Ref<0.2370317617.3383361537.105874>
2> ets:insert(T, [{key1, 10}, {key2, 0}]).
true
3> Match = ets:fun2ms(fun({key2,3}) -> {key2,0}; ({key2,N}) -> {key2,N+1} end).
[{{key2,3},[],[{{key2,0}}]},
 {{key2,'$1'},[],[{{key2,{'+','$1',1}}}]}]
4> ets:select_replace(T, Match).
1
5> ets:tab2list(T).
[{key2,1},{key1,10}]
6> ets:select_replace(T, Match).
1
7> ets:tab2list(T).
[{key2,2},{key1,10}]
8> ets:select_replace(T, Match).
1
9> ets:tab2list(T).
[{key2,3},{key1,10}]
10> ets:select_replace(T, Match).
1
11> ets:tab2list(T).
[{key2,0},{key1,10}]
```
This gives you compare-and-swap semantics in ETS in terms of isolation.

**Comment by benoitc** [comment]
@ferd ah I thought you were speaking about the counter. But yes indeed latest version has :)

**Comment by sverker** [comment]
Closed and replaced by #1961

**Pull request closed without merging**
