### PR TITLE
Add customization of file opening modes to sasl's error_logger

### PR DESCRIPTION
**Pull request by saleyn**
This includes the ability to open a SASL error log file in append mode
at startup.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Add customization of file opening modes to sasl's error_logger


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Building the documentation failed:

       ^
    sasl_app.xml:178: parser error : Opening and ending tag mismatch: item line 85 and taglist
        </taglist>
                  ^
    sasl_app.xml:179: parser error : Opening and ending tag mismatch: taglist line 83 and section
      </section>
                ^
    sasl_app.xml:191: parser error : Opening and ending tag mismatch: section line 78 and appref
    </appref>
             ^
    sasl_app.xml:193: parser error : Premature end of data in tag appref line 4
    ^
    unable to parse sasl_app.xml
    make[4]: *** [../man6/sasl.6] Error 6
    make[4]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/sasl/doc/src'
    make[3]: *** [release_docs] Error 2
    make[3]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/sasl/doc/src'
    make[2]: *** [release_docs] Error 2
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/sasl'
    make[1]: *** [release_docs] Error 2
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib'
    make: *** [release_docs] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
The sasl_SUITE:log_file test is failing. Can you please rebase this to master and make sure it runs cleanly?

**Comment by saleyn** [comment]
What is the error?  Is it possible that priv_dir (https://github.com/saleyn/otp/commit/d458a43b659a90b67e779c789f3e68557eac761b#diff-391beb94678036eb7d7e6d1a2d734a22R182) is not writable on the test server?

**Comment by saleyn** [comment]
Moved to https://github.com/erlang/otp/pull/713 to rebase on master

**Pull request closed without merging**
