### PR TITLE
HiPE: Optimise algorithmic bottlenecks compiling large functions

### PR DESCRIPTION
**Pull request by margnus1**
This PR speeds up many of HiPEs bottlenecks by improving algorithms and changing data structures. Occurrences of ordsets that grew linearly with program size have been replaced with maps. In a couple of places where it made a measurable improvement, gb_sets and gb_trees have also been replaced with maps, as well as an array:array in one case.
Finally `hipe_sdi` has been massively sped up by substituting an array of intervals with a segment tree.

With this, all the worst bottlenecks to compiling large functions have been addressed, aside from register allocation, which I will be addressing in a future PR.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lpgauth** [comment]
Happy to see some HiPE love :) Could you share what your plans are for the HiPE compiler?

I've love to use it as our default compiler, but unfortunately whenever I tried it in production I've ran into issues (performance, no tracing, etc).

**Comment by margnus1** [comment]
Oh, I'm just hacking HiPE to amuse myself, but I've been looking at giving code loading a bit of a well-needed revamp. As a side effect that should simplify other features, like source code locations in stacktraces.

As far as performance is concerned, probably not all workloads will see a speedup with HiPE due to some increased overheads, but if there's a program that compiles poorly, I'd be curious to have a look. As for tracing, most kinds aside from call and return tracing should work, although I'm not that familiar with their mechanisms.

**Comment by sverker** [comment]
@margnus1 About hipe code loading. I've had a side project for some time now doing improvements to the hipe loading or rather aimed at getting code upgrade and purge to work better:

https://github.com/sverker/otp/tree/sverk/r16/hipe-code-loading

The branch history is a bit messy as I started several major releases ago and merged 'master' into it a number of times. It's working pretty well for x86_64 but the other targets may need some work even though I haven't done much target specific. After some code cleanup and maybe a rebase I hope to get this into master soon.

**Comment by sverker** [comment]
@margnus1 I've put this in the tests for master and OTP-20. Unless you have some good argument about this PR as base really simplifying planned fixes for 19, I like to reduce risk on maint branch.

**Comment by margnus1** [comment]
@sverker Well, I remember wanting to use `hipe_segment_trees` in my LLVM backend refactoring (that was merged before OTP-19), in order to optimise `hipe_llvm_main:combine_ras_and_exns/3`, but the main justification for that is getting rid of a FIXME, rather than really simplifying anything (or any measured performance problem). So it seems fine with me to merge this to master instead.

As for the code loading stuff, we seem to have similar goals but very different approaches, or rather, I have the sligtly loftier goal of making HiPE code loading atomic (whithout ever needing to block multi-scheduling). The two core ideas are to have `hipe_unified_loader` produce a magic binary loader state that is accepted by `erlang:finish_loading/1` and to change the dispatch mechanism for external calls to use a three-element dispatch table, indexed by `code_ix`, like BEAM does. This should remove all need for patching code after it has been loaded, and thus makes away with the unwieldy ref-tables, (hopefully) simplifying the VM side.

I do not have much to show for myself yet, but since you've got code unloading but not code purging yet, feel free to nab my purging commit. It also comes with a test (that fails on your branch):

https://github.com/margnus1/otp/commits/hipe-staged-load

I'm glad you told me about this, since some of the things I was planning to do, you've already done. I think what I'll do now is to proceed to do a prototype of the new dispatch mechanism, so that I can benchmark it for any noticeable performance regressions. Once your improvements have been merged, I will rebase on top of them and proceed from there.

**Comment by sverker** [comment]
Merged to master.

**Comment by sverker** [comment]
@margnus1 By the way, in case you are looking for more amusement. This bug report is complaining about strange stack traces from hipe compiled code: https://bugs.erlang.org/browse/ERL-205.

**Comment by margnus1** [comment]
@sverker Thanks for the pointer. When I get some free time, I'll have a look to see if I can reproduce it.

**Pull request closed without merging**
