### PR TITLE
Property-based tests for the `binary` module

### PR DESCRIPTION
**Pull request by Maria-12648430**
This PR provides property-based tests for the functions in the `binary` module.

### CODE REVIEW

**Comment by bjorng** [comment]
I have made sure that an invalid pattern always raises an exception in #7611.

**Comment by juhlig** [comment]
I have added tests for invalid patterns to the suite in the last commit.

**Comment by juhlig** [comment]
It might also be worth testing that the functions fail if the given subject is not a binary but a bitstring, WDYT?

**Comment by bjorng** [comment]
> It might also be worth testing that the functions fail if the given subject is not a binary but a bitstring, WDYT?

Yes.

**Comment by juhlig** [comment]
@bjorng another finding: `binary:copy/2` accepts a bitstring as subject if `N` is `0`:
```erlang
1> binary:copy(<<1:1>>, 0).
<<>>
2> binary:copy(<<1:1>>, 1).
** exception error: bad argument
     in function  binary:copy/2
        called as binary:copy(<<1:1>>,1)
        *** argument 1: is a bitstring (expected a binary)
```

**Comment by juhlig** [comment]
Similar for `part/2,3`:
```erlang
1> binary:part(<<1:1>>, 0, 0).
<<>>
2> binary:part(<<1:1>>, 0, 1).
** exception error: bad argument
     in function  binary:part/3
        called as binary:part(<<1:1>>,0,1)
        *** argument 1: is a bitstring (expected a binary)
3> binary:part(<<1:1>>, 1, 0).
** exception error: bad argument
     in function  binary:part/3
        called as binary:part(<<1:1>>,1,0)
        *** argument 1: is a bitstring (expected a binary)

4> binary:part(<<1:1>>, {0, 0}).
<<>>
5> binary:part(<<1:1>>, {0, 1}).
** exception error: bad argument
     in function  binary:part/2
        called as binary:part(<<1:1>>,{0,1})
        *** argument 1: is a bitstring (expected a binary)
6> binary:part(<<1:1>>, {1, 0}).
** exception error: bad argument
     in function  binary:part/2
        called as binary:part(<<1:1>>,{1,0})
        *** argument 1: is a bitstring (expected a binary)
```

**Comment by juhlig** [comment]
The last commit adds more tests for invalid subjects. The tests for `copy` and `part` are currently failing because of what I said in the previous comments.

**Comment by bjorng** [comment]
Fixed `binary:copy/2` and `binary:part/{2,3}` in #7628. Added this PR to our daily builds.

**Comment by juhlig** [comment]
> Fixed `binary:copy/2` and `binary:part/{2,3}` in #7628. Added this PR to our daily builds.

When #7628 is merged, I'll rebase this PR on it, after which the two currently failing tests should pass.

**Comment by bjorng** [comment]
I have merged #7628.

**Comment by juhlig** [comment]
> I have merged #7628.

Thanks @bjorng Rebased, and all tests are now passing.

**Comment by juhlig** [comment]
There is a failing test in the CI:
```text
Testing make_test_dir.stdlib_test: *** FAILED test case 1691 ***
=ERROR REPORT==== 7-Sep-2023::16:24:26.246855 ===
beam/beam_load.c(206): Error loading module proper:
  This BEAM file was compiled for an old version of the runtime system.
  To fix this, please re-compile this module with Erlang/OTP 24 or later.
```

**Comment by bjorng** [comment]
The tests ran fine in our daily builds, so I will merge this PR soon.

I will try to address the problem with the CI tests in a separat pull request.

**Comment by bjorng** [comment]
I've tried to fix the `proper` problem in #7638.

**Pull request merged**
