### PR TITLE
Fix infinite loop in shell caused by record with recursive typespec

### PR DESCRIPTION
**Pull request by isvilen**
If record with recursive typespec such as
``` -record(r,{f :: #r{} | undefined}).```
is used in interactive shell it stucks in inifinite loop when trying to find definitions for all records used in expression.

For example following module definition:
```
-module(bug).
-export([t/0]).

-record(r,{f :: #r{} | undefined}).

t() ->
   #r{f=#r{f=undefined}}.
```

leads to this result in interactive shell:
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> c("bug.erl").
{ok,bug}
2> R = bug:t().
{r,{r,undefined}}
3> rr(bug).
[r]
4> R#r.f.
eheap_alloc: Cannot allocate 20310580872 bytes of memory (of type "heap").

Crash dump is being written to: erl_crash.dump...done
```

### CODE REVIEW

**Comment by uabboli** [comment]
Hi,

Thanks for pointing out the bug. 

I don't think this is the best correction, though. I'd rather see:

diff --git a/lib/stdlib/src/shell.erl b/lib/stdlib/src/shell.erl
index 6eafc7b..9b72312 100644
--- a/lib/stdlib/src/shell.erl
+++ b/lib/stdlib/src/shell.erl
@@ -758,6 +758,8 @@ used_records({record,_,R,Name,Ups}) ->
     {name, Name, [R | Ups]};
 used_records({record_field,_,R,F}) -> % illegal
     {expr, [R | F]};
+used_records({typed_record_field,Field,_Type}) ->
+    used_records(Field);
 used_records({call,_,{atom,_,record},[A,{atom,_,Name}]}) ->
     {name, Name, A};
 used_records({call,_,{atom,_,is_record},[A,{atom,_,Name}]}) ->

Another case we missed when changing the representation of typed
record fields some time ago.

Best regards

**Comment by uabboli** [comment]
Hi,

[Sorry for the ugly indentation.]

Thanks for pointing out the bug. 

I don't think this is the best correction, though. I'd rather see:

```erlang
diff --git a/lib/stdlib/src/shell.erl b/lib/stdlib/src/shell.erl
index 6eafc7b..9b72312 100644
--- a/lib/stdlib/src/shell.erl
+++ b/lib/stdlib/src/shell.erl
@@ -758,6 +758,8 @@ used_records({record,_,R,Name,Ups}) ->
     {name, Name, [R | Ups]};
 used_records({record_field,_,R,F}) -> % illegal
     {expr, [R | F]};
+used_records({typed_record_field,Field,_Type}) ->
+    used_records(Field);
 used_records({call,_,{atom,_,record},[A,{atom,_,Name}]}) ->
     {name, Name, A};
 used_records({call,_,{atom,_,is_record},[A,{atom,_,Name}]}) ->
```

Another case we missed when changing the representation of typed
record fields some time ago.

Best regards

**Comment by isvilen** [comment]
@uabboli This certainly looks nicer, but does not work when there are other record fields:

```
-module(bug).
-export([t/0]).

-record(r0,{f0}).
-record(r,{f :: #r{} | undefined, f0 :: #r0{}}).

t() ->
   #r{f=#r{f=undefined, f0 = #r0{f0 = v}}}.
```
results in:
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> c("bug.erl").
{ok,bug}
2> R = bug:t().
{r,{r,undefined,{r0,v}},undefined}
3> rr(bug).
[r,r0]
4> R#r.f.
* 5: record r0 undefined
```
with proposed fix result is as expected:
```
4> R#r.f.
#r{f = undefined,f0 = #r0{f0 = v}}
```

**Comment by uabboli** [comment]
I see. Forget my last suggestion; it's no good.

Your patch tests if record Name has already been seen. Note however
that you also need to take E1 into consideration: only if E1 has already
been processed, can Name be skipped.

Extending your example a bit:

```erlang
-module(bug).
-export([t/0, t2/0]).

-record(r0,{f0}).
-record(r,{f :: #r{} | undefined, f0 :: #r0{}}).

t() ->
   #r{f=#r{f=undefined, f0 = #r0{f0 = v}}}.

-record(r2, {}).

t2() ->
    #r2{}.
```

Now try:

```erlang
> erl
Eshell V9.0  (abort with ^G)
1> c(bug).
{ok,bug}
2> rr(bug).
[r,r0,r2]
3> (#r{f = #r2{}})#r{f = 18}.
* 1: record r2 undefined
4> 
```

**Comment by isvilen** [comment]
@uabboli good point
I've updated the pull request to accordingly.
Now:
```
3> (#r{f = #r2{}})#r{f = 18}.
#r{f = 18,f0 = undefined}
```

**Comment by uabboli** [comment]
Looks good.

A test in shell_SUITE.erl would be nice. It should be possible to
use, for example, otp_6166/1 as a starting point.

The patch cannot make it into Erlang/OTP 20.0 since the code is
frozen. As soon as the release is out (Wednesday is the plan), you
can rebase the patch on maint.

**Comment by isvilen** [comment]
Added `typed_records/1` test in `shell_SUITE.erl `.

It turns out that if already seen records are always skipped  that messes up
the expected order and there are test failures, so I modified the patch to skip
a record only when its own definition is processed.

When Erlang/OTP 20.0 is out I will rebase the patch on maint.

**Comment by isvilen** [comment]
@uabboli rebased  onto `erlang:maint`

**Comment by uabboli** [comment]
Thanks. I'll merge the branch soon.

**Comment by uabboli** [comment]
Merged commit 693691a8e82e892cab23ee66fe3984a3f98e2aa6 into erlang:maint.

**Pull request closed without merging**
