### PR TITLE
Otp 19 erts integer truncation bugs

### PR DESCRIPTION
**Pull request by mikpe**
This fixes several VM malfunction issues we've seen recently at Klarna.  The root cause is that parts of the VM use 32-bit integers to represent counts and byte offsets on 64-bit machines.  Sometimes these small integers overflow causing wraparound, sometimes larger integers are assigned to them causing truncation.  The effects we've observed include segmentation faults and failed attempts to allocate huge amounts of memory (many orders of magnitude more than we have) -- a sign of wraparound or memory corruption.

The patches also include a fix to not crash the VM on attempts to pass large messages between processes.  In OTP 18 there was an explicit check for that in erts_alloc_message_heap_state(), but that check seems to have been removed in OTP 19.  However, the other parts of that patch (primarily fixing struct erl_heap_fragment) still apply.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: erts_new_mso_binary(): do not truncate len to 32 bit signed int


----------------

I am a script, I am not human 

----------------

**Comment by mikpe** [comment]
Had to fix a too long commit message.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
looks good, putting into nightly tests

**Comment by garazdawi** [comment]
Any suggestion on a concise informative release note? :)

**Comment by mikpe** [comment]
I would suggest something like:
Fix bugs caused by the VM sometimes truncating object sizes or offsets to 32 bits on 64-bit hosts.

**Comment by garazdawi** [comment]
I'll use that together with some info about the general areas where the user may expect to run into these truncation bugs. Thanks.

**Pull request merged**
