### PR TITLE
Pre-merge label,jump,label,jump,... instructions

### PR DESCRIPTION
**Pull request by josevalim**
This optimizes the fixpoint calculation which
otherwise would require N*N passes in order to
optimize N labels from patterns.

I have used [this code](https://gist.github.com/josevalim/399302f7de8849b44aa7), extracted from a more complex example,
to pin down the slow down we were seeing during compilation.
The fprof results confirms the N*N behaviour given set operations
are invoked 1_000_000 times for 1_000 clauses.

After applying this optimization, compilation of the slow.erl file in the
gist above went from 0.5s to 0.02s. However, a file with 10_000 clauses
went from 60s to 0.5s.

### CODE REVIEW

**Comment by c-rack** [comment]
+1

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Only looking at the commit message and the code, it is not at all obvious what kind of code would cause the O(N*N) run-time. So I would like a short code example directly in the commit message. An extract from the gist would do.

Also, a few sentences about how much compilation time this optimisation saved directly in the commit message would be good. Basically, the information already present in the pull request.

**Comment by josevalim** [comment]
Commit messages and code updated.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Thanks! We will test it a few days in our daily builds and then merge it to master.

**Comment by nox** [comment]
Can't we just add a clause to opt/2?

**Comment by josevalim** [comment]
@nox I was able to add a clause to opt/3 as follows:

```erlang
%%% Merge label,jump,label,jump instructions to avoid multiple
%%% fixpoint calculations. Otherwise N patterns will require N*N
%%% passes. By pre-merging, we will require N passes.
opt([{label,_}=Lbl,{jump,{f,X}}|[{label,_},{jump,{f,X}}|_]=T], Acc, St) ->
    opt([Lbl|T], Acc, St);
```

I have measured the same performance benefits. My issue with it is that this is happening inside the fixpoint calculation so I am less confident about the correctness of the code.

**Comment by bjorng** [comment]
Your statement about correctness inspired me to look at the code I wrote more than 15 years ago in beam_jump and try to understand how it works.

The result of that deep code dive is the following alternate correction of the performance problem:

https://github.com/bjorng/otp/compare/erlang:master...bjorn/compiler/beam_jump

Please try it and verify that it solves your original performance problem.

**Comment by josevalim** [comment]
Yup, it solves my original performance problem too!

**Comment by bjorng** [comment]
I have merged my beam_jump branch to master.

**Pull request closed without merging**
