### PR TITLE
Add class annotation to HTML from fenced blocks

### PR DESCRIPTION
**Pull request by josevalim**
This can be used, for example, to discard Mermaid diagrams when printing documentation in the shell.

PS: We are considering using this module in Elixir to convert our Markdown to HTML and then render that. I do understand this module is private and we will deal with the consequences of using a private API, but I believe it is better if we can share the rendering stack. During this process, I noticed that there are two features that we needed for now. One is the ability to distinguish the language to discard Mermaid diagrams. To deal with this, I emitting the same HTML as CommonMark. The other part is to properly render tables. Do you folks plan to deal with tables or will you rather keep them as code? Thank you!

### CODE REVIEW

**Comment by garazdawi** [comment]
Looks goot me, just one small nitpick, according to [the common mark spec](https://spec.commonmark.org/0.31.2/#example-143), any text after the first space should be ignored when adding `language-` class. 

> We are considering using this module in Elixir to convert our Markdown to HTML and then render that. I do understand this module is private and we will deal with the consequences of using a private API, but I believe it is better if we can share the rendering stack.

I think it is a good idea for us to standardize on one markdown parser, so I don't mind us eventually making the API public. We may want to polish the API a bit first though before making it public, such as adding metadata to each eHTML element with `anno` information so that it is possible to render nice error messages.

> The other part is to properly render tables. Do you folks plan to deal with tables or will you rather keep them as code? Thank you!

The main reason why we didn't implement parsing of tables is because shell_docs cannot render them. So we would have to implement both table parsing and printing for it to work. It is something we may to eventually, but don't have any plans to do yet. As always PRs are welcome :)

**Comment by josevalim** [comment]
@garazdawi done!

**Comment by Benjamin-Philip** [comment]
> The main reason why we didn't implement parsing of tables is because shell_docs cannot render them. So we would have to implement both table parsing and printing for it to work. It is something we may to eventually, but don't have any plans to do yet. As always PRs are welcome :)

I'll send patches for that in a few weeks.

**Review by kikofernandez — APPROVED** [review]
Thanks for your contribution, greatly appreciated!
Great work!

**Comment by josevalim** [comment]
Changed to maint.

**Comment by kikofernandez** [comment]
> I think we should target this for maint instead so that it will be in the 27.1 release. No need to wait another year for it to be released.

Good catch @garazdawi !

**Pull request merged**
