### PR TITLE
no hardcoded port accept timeout

### PR DESCRIPTION
**Pull request by sstrigler**
fix odbc port timeout for connect

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: allow to change accept timeout for port by env var 'ELR_ODBC_PORT_TIMEOUT'


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by weiss** [comment]
Should this really be an (undocumented?) environment variable rather than a new `odbc:connect/2` option?

If so, note that there's a typo in `ELR_ODBC_PORT_TIMEOUT` (`ELR` vs. `ERL` ).

**Comment by sstrigler** [comment]
D'oh! Fixed the typo. Whether this goes undocumented, documented or as an option to connect surely is open for discussion. First and foremost wanted to point out there is a problem here that might need to be addressed one way or the other.

**Comment by sstrigler** [comment]
Maybe some reasoning behind why I implemented it as an environment variable: The actual problem I'm facing is a client running MongooseIM with MS SQL Server as a DB backend for rosters. They are running their nodes on medium sized EC2 instances with a single core. During boot it suffers from quite some load. As within MongooseIM (and ejabberd likewise probably) there is an odbc connection pool per vhost. I.e. if you want to have three connections in the pool and have like, say 3 vhosts then you end up spawning 9 odbc port processes, all of which then timeout as all of this happens in parallel and not sequentially. 

With this environment variable you can easily bypass and tailor odbc to the needs of the underlying actual system without changing the configuration. Which is a good thing because this value is very system specific. If they'd switch to a machine with more cores, they could still use the same configuration but just set a different value for ERL_ODBC_PORT_TIMEOUT.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I think your reasoning sounds good, it is really not a "connection parameter" but rather something affect the underlaying mechanisms, an "application behaviour" However we do want it to be documented and tested too.

**Comment by jhg** [comment]
@IngelaAndin & @sstrigler is possible use Timeout parameter and not environment variable? Or as say @weiss  a new option? I think a hardcoded value is bad but also I think a parameter or option is better that a environment variable and more easy for use.

**Comment by psyeugenic** [comment]
Using OS environment variables in Erlang applications are generally frowned upon. We do use it, but the policy is not to use environment variables unless all else fails or if we already use similar environments variables in the same application.

**Comment by sstrigler** [comment]
@jhg I don't see how passing the timeout via parameter to the connect call would lead to more flexibility. Then you still rely on the application using odbc to allow you to configure that value. Otherwise you'd still end up having the timeout hardcoded. By using an environment variable you could influence this behaviour without modification to any source code.

**Comment by sstrigler** [comment]
That said, I'm willing to implement it the way you prefer. But someone needs to decide. Also I'll add documentation and a test of course.
If not going for the env var, personally I'd prefer a new option called 'port_timeout'. 
Unfortunately there is an option called 'timeout' already which is not very well documented. From just looking quickly at the code I assume this is the default timeout for subsequent calls to 'commit'. I'd also add a short explanation to this of course then.

**Comment by jhg** [comment]
@sstrigler Why as parameter I can set this option from code where I call it, static or dynamic, and I can call it in other call or in other instance, (other app, other node), in same environment context, with enviroment variable it is so different that only call wit a option, and I think this is easy and flexible. And this is only two examples about it, environment variable is util, etc; but not in all cases. And as say @psyeugenic is better use it only if not exist other way for it or enviorement variable offer something better that other way. Also, as parameter or option is more clean in code the question "why it has a timeout x?" other person read code and then know it so easily.

About 'port_timeout' name for option, sound good. But I can't decide. :smiley:

**Comment by ferd** [comment]
Production experience for us has us define such variables cleanly as an OTP environment variable for an app. If we need that value to be represented by an OS ENV variable, we rather initialize them to that form at application start time. The OTP environment variables are *the* configuration mechanism to be used everywhere in a running program, in my opinion.

**Comment by sstrigler** [comment]
@ferd: Just to make sure, you're talking about application:get_env/2,3?

**Comment by jhg** [comment]
@ferd in an application is that, but in this case odbc is a lib, you can your application, or applications, config with environment variable, but a lib is better that application configure it.

For example, and enviorement variable configure in Django the project settings but settings of other lib and modules that use it is in settings file in code of application, not in a environment variable.

**Comment by ferd** [comment]
@sstrigler yes.
@jhg see things such as [stillir](https://github.com/heroku/stillir) -- the app takes care of converting the OS environment variables into OTP environment variables. 

Here's a sample config we could run with it for example:

```erlang
cache_os_envvars() ->
    ConfigSpecs = config_specs(),
    stillir:set_config(?APP, ConfigSpecs).

reload_os_env_vars_from_file() ->
    stillir:update_env(?APP, os:getenv("HOME") ++ "/env.sh", config_specs()).

config_specs() ->
    [{availability_zone, "AVAILABILITY_ZONE"},
     {instance_name, "INSTANCE_NAME", [required]},
     {local_ip, "LOCAL_IP"},
     {snapshot_fresh_seconds, "SNAPSHOT_FRESH_SECONDS", [{default, 300}, {transform, integer}],
     {metrics_send_rate, "METRICS_SEND_RATE", [{default, 100}, {transform, integer}]},
     {hmac_key, "HMAC_KEY", [{default, <<"uninitialized-key">>}, {transform, binary}]},
     {app_domain, "APP_DOMAIN",  [{default, fun() -> some_call() end}]}
    ]}.
```

We can take that and inject it into all apps we need them for at boot time for the full release.

Another option is to use things like [relx dynamic configuration](https://github.com/erlware/relx/wiki/Dynamic-Configuration) (which uses a script to generate various values), or to use ENV variables directly in `sys.config` (still with relx). For example, I could have a `sys.config` that goes:
```erlang
[{myapp, [{http_listen_port, ${PORT}},
          {cache_dir, "${HOME}"}]},
 {otherapp, [{integer, ${SOME_VAR}},
          {string, "${OTHER_VAR}"}]}
].
```
With the option to use the extended boot script and the ENV variable `RELX_REPLACE_OS_VARS` set to true, it will generate a sys.config file with the variables substituted properly.

The thing is the OS is a good place to set these values in an environment-specific manner decoupled from the repository you save, but Erlang's configuration management is independent of the OS using `application:get_env/2-3` functions. It is better to find a way to translate from the OS to the Erlang standard so that code remains idiomatic.

**Comment by jhg** [comment]
@ferd I didn't know Erlang environment variables for application `application:get_env/2,3` I thing it is better for configure behaviour of a lib that application use. I before say about OS enviorement variable, I see it better for configure application but not library.

And if odbc:connect need has a different behaviour with differents calls I think easy way is a parameter, but if only need one behaviour for all calls in an application then Erlang enviorement variable for application is nice.

Thank you @ferd for show me `application:get_env/2,3`, is so interesting.

**Comment by ferd** [comment]
A library *is* an application.

```
λ /tmp → rebar3 new lib testlib
===> Writing testlib/src/testlib.erl
===> Writing testlib/src/testlib.app.src
===> Writing testlib/rebar.config
===> Writing testlib/.gitignore
===> Writing testlib/LICENSE
===> Writing testlib/README.md
λ /tmp → cd testlib
λ testlib → vim src/testlib.app.src
<add {env,[{testkey, testval}]} entry>
λ testlib → rebar3 shell
===> Verifying dependencies...
===> Compiling testlib
Erlang/OTP 18 [RELEASE CANDIDATE 2] [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V7.0  (abort with ^G)
1> application:start(testlib).
ok
2> application:get_all_env(testlib).
[{testkey,testval},{included_applications,[]}]
```
Even if the application has no processes whatsoever, it can still be started and access its configuration.

**Comment by jhg** [comment]
@ferd ok, I did say "application" as diff of lib, as a project not lib, I don't say as Erlang application. I all case, "odbc:connect will be configure port_timeout for all calls or will be configure with others values in others calls?" in first case Erlang application environment is nice, in second case a parameter is better.

**Comment by ferd** [comment]
Ah alright, that's confusing because 'OTP library applications' are a thing, and I thought you meant the Erlang environment variables wouldn't work for these (people sometimes think that, because they do not always realise you can "start" a library application).

And yeah, I'm not arguing against parameters or explicit function arguments, just against using `os:getenv` as a general configuration mechanism.

**Comment by jhg** [comment]
@ferd yes, I now look I don't explain me good,a little error. And I think same about `os:getenv`. @IngelaAndin @psyeugenic or collaborator, etc, decide parameter option or `application:get_env`?

**Comment by IngelaAndin** [comment]
I do not want any OS environment variables. But an application environment variable can be viable, as it has to do with the internals of odbc and it is not really an  "ODBC"  option.  Of course the simplest choice is to have a parameter. I think that some options though should not be to simple to set as they
should only be set by people knowing what the are doing.

**Comment by sstrigler** [comment]
Sorry, was busy with other stuff.

I rebased on latest master, use application:get_env/2 now and added docs and a test.

I decided to go with the application:get_env/2 solution for reasons mentioned by @IngelaAndin amongst others. I think this option is not changing a property of the actual odbc connection being made but the behavior of the odbc application instead. 

I have to admit that I didn't run the tests myself as I don't know how to do it, i.e. what it takes to setup my environment correctly. I this is an issue I'd be happy if someone would be willing to show me how it works  or point me to some helpful documentation.

**Comment by IngelaAndin** [comment]
Odbc test are some what harder to run than other test suites as it is dependent on third party products 
that are not automatically set up. And also you would need to update one of the test module a little if I remeber correctly. 

I can say that initiating test cases that use application variables needs to include the following steps:
odbc:stop(),
application:load(odbc),
application:set_env(odbc, port_timeout, 0),
odbc:start(),

If you fix that we can try the test in our environment first and we will help you with the test environment if necessary to debug, but hopefully it will work.

**Comment by sstrigler** [comment]
Thanks, I assume I have to do the same when cleaning up (end_per_testcase), right?

**Comment by IngelaAndin** [comment]
application:unset_env(odbc,  port_timeout,)
odbc:stop(),

should be sufficient. 
and maybe odbc:start() depending on how the test suite is written.   (if odbc is started in init_per_SUITE och allways init_per_testcase.)

**Comment by sstrigler** [comment]
Ok, test updated accordingly.

**Comment by IngelaAndin** [comment]
Oh you need to rebase it on latest maint now, as 18.0 is now the maint track and master is 19 to be!

**Comment by sstrigler** [comment]
okay :)

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
