### PR TITLE
erts: send port exit status when process eofs without exiting on Windows

### LINKED ISSUE #8317: Port exit status message isn't sent when spawning Cygwin executables
**Describe the bug**

On Windows, ports created with the `exit_status` option don't send the exit status message to connected processes when a Cygwin executable is spawned.

**To Reproduce**

On a Cygwin shell:

```console
$ erl
Erlang/OTP 26 ...
1> Cmd = erlang:open_port({spawn_executable, os:find_executable("cmd.exe")}, [{args, ["/C", "echo Hello world"]}, exit_status, use_stdio, in, binary, hide]).
#Port<0.2>
2> flush().
Shell got {#Port<0.2>,{data,<<"Hello world\r\n">>}}
Shell got {#Port<0.2>,{exit_status,0}}
ok
3> Grep = erlang:open_port({spawn_executable, os:find_executable("grep.exe")}, [{args, ["--version"]}, exit_status, use_stdio, in, binary, hide]).
#Port<0.3>
4> flush().
Shell got {#Port<0.3>,
           {data,<<"grep (GNU grep) 3.11\nPackaged by Cygwin ...">>}}
ok
```

**Expected behavior**

An `exit_status` message should always be sent to the connected process.

**Affected versions**
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] (master)

**Additional context**

I noticed this issue because the Elixir Mix CLI kept hanging on my machine when I executed it on a Cygwin terminal, but worked correctly when executed from PowerShell or the command prompt. It seems Mix hangs on Cygwin when attempting to get the output of the Cygwin Git executable, but it doesn't hang when the Windows build of Git is executed.

### PR DESCRIPTION
**Pull request by yastanotheruser**
Fixes #8317, working on Windows 11, I will try to test it on older Windows versions.

Successfully compiles the latest Elixir version on Cygwin, and also normally compiles, tests and starts an Elixir application on Cygwin, since it fixes https://github.com/elixir-lang/elixir/issues/13449.

### CODE REVIEW

**Comment by yastanotheruser** [comment]
Working on Windows 10, couldn't start the VM on Windows 8 due to an unrelated console error.

**Review by frej — COMMENTED** [review]
>poll process handle as an special case of input, this allows to send the
>exit_status message when the process closes its stdout without exiting.

Do you really mean this? That would mean that you have no means to distinguish between a process that has exited and one that has closed its stdout but is still running. The issue you reported in #8317 was that the exit status message was lost on Windows if the process closes stdout, not that it should report the exit status as soon as stdout was closed.

If on the other hand your implementation matches the conclusion in #8317, the commit message needs to be revised.

**Comment by yastanotheruser** [comment]
@frej Polling the process handle is how it was solved, the purpose is tracking the process exit separately from the data input handle EOF.

> not that it should report the exit status as soon as stdout was closed.

I tried to handle all possible combinations of `eof` and `exit_status`, being consistent with how the messages are currently being sent on UNIX. Following this, the exit status is reported when the process exits, not when stdout is closed, otherwise this would require to kill the process if it hasn't exited, which is not the case.

**Comment by frej** [comment]
> Following this, the exit status is reported when the process exits, not when stdout is closed

Good! Then I suggest you change the commit message to make that clear, what about?:

```
erts: poll port process handles on Windows

Poll process handle as an special case of input. This allows
reliable detection of process termination, thus fixing an error
case on Windows where the exit_status message never was sent if
the process closed its stdout before exiting.

Closes #8317
```

**Comment by yastanotheruser** [comment]
@frej Sounds clearer, thank you.

**Comment by garazdawi** [comment]
Merged to master for inclusion i OTP 27. Thanks for your contribution!

**Pull request closed without merging**
