### PR TITLE
Fix SSH reverse search with CTRL+R

### PR DESCRIPTION
**Pull request by jjcarstens**
`group.erl` now sends `put_expand_no_trim` when entering a history search. `ssh_cli` does not support that message and so when entering a search when SSH is the underlying driver, the expanded result would not be displayed even though the search functionality would still technically work.

This adds support for that `put_expand_no_trim` message when using SSH

I look through the tests and not entirely sure where I would put this. I'm happy to write that if there is any direction of how others might want it tested. In the meantime, this is my quick manual setup to test it works:

**Start the Daemon**
```erlang
%% Create System host key
Priv = public_key:generate_key({rsa, 2048, 65537}).
PemEntry = public_key:pem_entry_encode(:"RSAPrivateKey", Priv).
Pem = public_key:pem_encode([PemEntry]).
ok = file:mkdir_p("/tmp/ssh"),
ok = file:write("/tmp/ssh/ssh_host_rsa_key", Pem).

%% Start SSH Daemon
Opts = [{system_dir, "/tmp/ssh"}, {pwdfun, fun (_, _, _, _) -> true end}],
application:ensure_all_started(ssh),
ssh:daemon(2222, Opts).
```

**SSH (no password)**
```
ssh localhost -p 2222
# CTRL+r to search history
```

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Thanks as it is vacation time it may take a little longer, but we will handle it.

**Comment by u3s** [comment]
> I look through the tests and not entirely sure where I would put this. I'm happy to write that if there is any direction of how others might want it tested.

Can you check if some simple test could be developed around ssh_basic_SUITE:do_shell code?

**Comment by jjcarstens** [comment]
Sorry! We seemed to have swapped vacation times and then I let this slip away from me until your recent comment 🤦🏼 Thanks for the help!

**Comment by u3s** [comment]
change of plans. we will merge both tests in this PR (removing the dependency towards #7627). I hope to merge your PR this week.

**Pull request merged**
