### PR TITLE
Move architecture knowledge out of hipe loader

### PR DESCRIPTION
**Pull request by richcarl**
Make code_server be responsible for finding the architecture and deciding whether to try to load native code, in order to avoid repeated calls to system_info(hipe_architecture) and clumsy uses of try/catch to test if hipe is enabled.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
As a code cleanup I like it.
But I'm a bit concerned about adding an extra call to system_info(hipe_architecture)
for each loaded module on a hipe enabled VM.

**Comment by richcarl** [comment]
Currently, that call will happen anyway, but within the hipe loader, and then it crashes because the result is "undefined", and then that crash is caught and turned into "no_native"... This just shortcuts the stoopid.

**Comment by sverker** [comment]
Yes, but it's a shortcut at the expense of the case with a hipe enabled VM, as system_info(hipe_architecture) is then called twice. And hipe_architecture is at the 14th place
of a long else-if chain in system_info_1.

I think the real solution should be to fix that stoopid and obscure behaviour in hipe_unified_loader:load_native_code() and distinguish between 'undefined' from other unknown or wrong architectures. Trying to load an incompatible architecture should result in an error message like the ones complaining about wrong version of hipe or incompatible runtime system.

**Comment by richcarl** [comment]
I was aiming for a minimal diff, but I could modify the hipe code too. However, I'd still like to keep it so that the module in hipe isn't called at all from the kernel code if the system isn't hipe-enabled. How about passing the architecture as an arg to the load_native_code() function?

**Comment by sverker** [comment]
Passing the architecture to hipe_unified_loader is fine with me.
However, hipe_unified_loader is part of the kernel without any runtime dependencies  to hipe,
and the module is still loaded in an hipe-disabled VM  (just tested it, not sure why).

**Comment by richcarl** [comment]
Started over more or less from scratch and reviewed all uses of system_info in hipe code.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by mikpe** [comment]
Looks good to me.  I'll give it a try with the HiPE testsuite this weekend.

**Comment by sverker** [comment]
Fine with me.

**Comment by proxyles** [comment]
Hello!
It looks like we already have done some changes to the parts in lib/kernel/src/code.erl
Could you rebase this upon latest master
Thank you

**Comment by richcarl** [comment]
Rebased.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by mikpe** [comment]
Rebased version now tested with the HiPE test suite.  No regressions from this patch.

**Comment by proxyles** [comment]
Hi!
code_SUITE:ext_mod_dep() is now failing across the boards.
Would you mind updating the test case according to your changes?

**Comment by richcarl** [comment]
Test suite fixed.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
