### PR TITLE
Obfuscate asserts to make Dialyzer shut up

### PR DESCRIPTION
**Pull request by richcarl**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
Merged  9bff4db

**Comment by richcarl** [comment]
@uabboli Hm, to where was this merged?

**Comment by garazdawi** [comment]
@richcarl it has not been synced to the github repo yet, but is has been merged into the internal master.

**Comment by okeuday** [comment]
Spooky, it is like it disappeared.

**Pull request closed without merging**
