### PR TITLE
Improve inet_backend = socket option parsing for gen_tcp (OTP-17580)

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
This is a rewrite of the option parsing in `gen_tcp_socket`, a.k.a the implementation module for `inet_backend = socket`.

The intention is to make it a little less messy, and to fix the bug in #5122.

### CODE REVIEW

**Comment by bmk** [comment]
filtermap_opts_1: list comprehension?

**Comment by RaimoNiskanen** [comment]
`filtermap_opts()` -> list comprehension...  That could work!

One perk of this implementation of `filtermap` is that it speculates to not change the result list, and if the result is not changed; no new list nor any garbage is created.  But I realize that it should at least follow the spec of `lists:filtermap/2`.  And premature optimization is known to be one root cause of evil...

**Comment by RaimoNiskanen** [comment]
I changed to list comprehensions - it worked nicely

**Comment by bmk** [comment]
Other then that, it looks good. Simplifying the option handling was neeeeded.

**Review by bmk — APPROVED** [review]

**Pull request merged**
