### PR TITLE
public_key: Correct argument order

### LINKED ISSUE #8832: verify_fun/3 receive cert as binary instead of OTPCertificate record
**Describe the bug**
public_key.erl calls pubkey_cert:apply_fun/5 in two places.
[Line 1713](https://github.com/erlang/otp/blob/master/lib/public_key/src/public_key.erl#L1713):
```erlang
try pubkey_cert:apply_fun(VerifyFun, Cert#cert.otp, Cert#cert.der, Reason, Userstat0) of
```
[Line 2422](https://github.com/erlang/otp/blob/master/lib/public_key/src/public_key.erl#L2422):
```erlang
try pubkey_cert:apply_fun(VerifyFun, OtpCert, DerCert, Reason, UserState0) of
```
[pubkey_cert:apply_fun/5](https://github.com/erlang/otp/blob/master/lib/public_key/src/pubkey_cert.erl#L383) reverses the order of OtpCert and DerCert and calls the user supplied verify_fun with DerCert instead of OtpCert:
```erlang
apply_fun(Fun, DerCert, OtpCert, Result, UserState) ->
    if is_function(Fun, 4) ->
            Fun(OtpCert, DerCert, Result, UserState);
       is_function(Fun, 3) ->
            Fun(OtpCert, Result, UserState)
    end.
```

**Affected versions**
27.1

### PR DESCRIPTION
**Pull request by IngelaAndin**
closes #8832

### CODE REVIEW

**Review by dgud — APPROVED** [review]
That is unfortunate other functions have the other order see, pubkey_cert:validate_signature/6 for example.

**Review by u3s — APPROVED** [review]

**Comment by u3s** [comment]
how come the related issue wasn't discovered in tests? are we missing some coverage?

**Comment by IngelaAndin** [comment]
@u3s I am a little confused about the reason just now, but I would say that it is mainly because coverage was not as good as it should have been.

**Comment by IngelaAndin** [comment]
@dgud This is just a internal function so maybe we can fix it other way around. I will consider it tomorrow!

**Comment by u3s** [comment]
> @u3s I am a little confused about the reason just now, but I would say that it is mainly because coverage was not as good as it should have been.

Should it be added in this PR?

**Comment by IngelaAndin** [comment]
It is.

**Comment by IngelaAndin** [comment]
@u3s  But I am think about possible further test.

**Pull request merged**
