### PR TITLE
Snmpstring

### PR DESCRIPTION
**Pull request by goertzenator**
Fix for ERL-164, no string escaping for SNMP config files.

This fixes and tests some of the escape problems in `snmpa_conf.erl`. There are more escape problems... fixing is easy but testing is hard.  I suspect there are more issues like this on the manager side, but I have not looked.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Fix ERL-164 for agent, vacm, and usm config files.
snmp tests demonstrating ERL-164, no string escaping for SNMP config files


----------------

I am a script, I am not human 

----------------

**Comment by goertzenator** [comment]
There is a period in one of the commit messages.  Should I resubmit this PR?  I have a [new branch](https://github.com/goertzenator/otp/tree/snmpstring2) ready.

**Comment by tuncer** [comment]
Given that you have a corrected branch, you can (1) delete the old branch, (2) rename the new branch, and (3) force push, in order for it to be reflected here. No need for a new pull request.

```
$ git checkout snmpstring2
$ git branch -D snmpstring
$ git branch -m snmpstring
$ git push origin +snmpstring
```

**Comment by IngelaAndin** [comment]
OTP 19 is due today, after the release we will need this PR to be based on the new maint. This PR will be consider for 19.1

**Comment by goertzenator** [comment]
Rebased on today's maint as requested. @tuncer: thanks for the git commands.  I didn't know rewriting history was acceptable for PRs.  And congrats on OTP 19!

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: snmp tests demonstrating ERL-164, no string escaping for SNMP config files


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We think that the change is good and we are now running it in our tests. It would be nice if you could fix it in the manager too. I will create an issue otherwise for the manager to be fixed and we will see when it gets prioritized.

**Comment by IngelaAndin** [comment]
As you have introduced a new test suite module you have to add it to modules.mk  in the test directory.
Now your test suite is not included when you build the tests and hence not run. Would you please add it. I know snmp is different from other OTP applications due to legacy reasons, but we have to live with that for now anyway.

**Comment by goertzenator** [comment]
Ah, that probably explains why it was so tedious to get the test to run (lots of manual invocations).  I will fix it.

Regarding the manager, I've never used it before and I don't think I can justify spending time on that at the moment.  Sorry.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: snmp tests demonstrating ERL-164, no string escaping for SNMP config files


----------------

I am a script, I am not human 

----------------

**Pull request merged**
