### PR TITLE
fix for ppc64le / add travis test for ppc64le

### PR DESCRIPTION
**Pull request by grooverdan**
Thanks @CShu12 for starting this.

### CODE REVIEW

**Comment by grooverdan** [comment]
Thanks @proxyles

**Comment by proxyles** [comment]
@grooverdan hmm There is an issue with the travis builds not setting up the libssl packages correctly "sometimes". If we can not solve it, I will have to revert this.

**Comment by grooverdan** [comment]
I've pinged some ibm folks to look. Thanks for the heads up.

**Comment by proxyles** [comment]
Looks like the problem solved itself.

snip build log

> libssl-dev is already the newest version (1.0.2g-1ubuntu4.13).

So we no longer try to fetch a package that "sometimes" fail

win win I guess

**Comment by ghatwala** [comment]
@proxyles - have updated the base image with this dependency - "libssl' and now have noted that the job consistently passes - https://travis-ci.org/ghatwala/otp/jobs/434234648#L404.  Also noted in your latest power build is passing too - https://travis-ci.org/erlang/otp/jobs/437008649#L404

**Comment by proxyles** [comment]
Thank you!

**Comment by proxyles** [comment]
@ghatwala @grooverdan looks like its still (or again) a problem with that same package.
Is there something I can do to facilitate this?

**Comment by ghatwala** [comment]
@proxyles - So this issue was due infra ( one of base image was missing that dependency -libssl ) .Now i have ensured all the base images which are being used for job deployments have that dependency always and not missed - Job seems having that dependency available now - https://travis-ci.org/erlang/otp/jobs/440702622#L407 .

**Pull request merged**
