### PR TITLE
Diameter proxy bugfix

### PR DESCRIPTION
**Pull request by systra**
I tried to use proxy feature of the diameter application and I encountered some problems
inside Diameter application when the diameter message includes grouped AVPs.

In such case (which is quite common) the message is decoded (i.a. to list of AVPs inside diameter_package record - `avps` field) but in a way that prevents encoding the same message back when passing message to another diameter peer.

I prepared the CT testing suite to show the problem (try running it on the recent Erlang version).

I found the buggy place and after patching performed all tests for diameter application after patching and everything is working fine.

Without the patch proxying of Diameter messages containing grouped AVPs is impossible.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by otp-anders** [comment]
As commented on pull/578, this changes the decode in a way that breaks an existing application, so it can't be accepted as-is. That said, it is a problem that the diameter_avp representation isn't complete: that component AVPs aren't represented by a diameter_avp in the decode of an AVP of type Grouped.

One problem with the provided patch is that it only deals with the successful case: if there are errors when decoding the components of a Grouped AVP then the diameter_avp representation is as incomplete as it is currently. There is a patch underway to change this, to give access to component AVPs in diameter_avp form regardless of success or failure.

I don't really understand the comment that it's impossible to proxy messages containing Grouped AVPs, in the absence of decode errors at least, since in that case there's the decoded record representation. What is it you can't currently do?

**Comment by systra** [comment]
I agree that the patch deals with the successful case but it is also sufficient (test suite) to show that the current solution deals badly with Grouped AVPs when using proxy mode.

The problem is that for proxied messages the AVPs list is used for sending the message along rather than the decoded record representation 

```
resend(false,
       Opts,
       #diameter_caps{origin_host = {_,OH}}
       = Caps,
       #diameter_packet{header = Hdr0,
                        avps = Avps}
       = Pkt,
       App,
       Dict0,
       #recvdata{service_name = SvcName,
                 sequence = Mask}) ->
    Route = #diameter_avp{data = {Dict0, 'Route-Record', OH}},
    Seq = diameter_session:sequence(Mask),
    Hdr = Hdr0#diameter_header{hop_by_hop_id = Seq},
    Msg = [Hdr, Route | Avps],
    resend(send_request(SvcName, App, Msg, Opts), Caps, Dict0, Pkt).
```

which leads to encoding exception

```
{'EXIT',{diameter_codec,encode,
                        {function_clause,[{diameter_codec,pack_avp,1,
                                                          [{file,"/opt/erlang/17.4/lib/diameter-1.8/src/base/diameter_codec.erl"},
                                                           {line,585}]},
                                          {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                                          {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                                          {diameter_codec,encode_avps,1,
                                                          [{file,"/opt/erlang/17.4/lib/diameter-1.8/src/base/diameter_codec.erl"},
                                                           {line,210}]},
                                          {diameter_codec,e,2,
                                                          [{file,"/opt/erlang/17.4/lib/diameter-1.8/src/base/diameter_codec.erl"},
                                                           {line,93}]},
                                          {diameter_codec,encode,2,
                                                          [{file,"/opt/erlang/17.4/lib/diameter-1.8/src/base/diameter_codec.erl"},
                                                           {line,71}]},
                                          {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,661}]},
                                          {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,434}]}],
                                         #diameter_header{version = 1,length = 172,cmd_code = 275,
                                                          application_id = 0,hop_by_hop_id = 2845728412,
                                                          end_to_end_id = 2845728412,is_request = true,
                                                          is_proxiable = true,is_error = false,
                                                          is_retransmitted = false}}}}
```

Presumably it would be better to use decoded record representation for this (I'll check this) but I'm not sure how this would influence existing applications.

**Comment by otp-anders** [comment]
The problem here is with encode, not decode: what's missing is the following clause on diameter_codec:pack_avp/1.

    pack_avp([#diameter_avp{} = GroupedAvp | ComponentAvps]) ->
        pack_avp(GroupedAvp#diameter_avp{data = ComponentAvps});

I'll fix this and add your tests to the branch where I'm fixing the diameter_avp representation in the error case. (My earlier comment was a bit too sweeping. Component AVPs are represented in the successful case: that's where ComponentAvps above comes from.)

**Comment by otp-anders** [comment]
There's a bit more wrong here than the encode. For one, your handle_request in the proxy suite is returning {proxy, []}. The code does indeed allow this but it's not a documented return value: what's documented is {relay, Opts} for a message received in the relay application. Forwarding in the proxy case isn't a problem that diameter currently lets you do with a return value from a handle_request callback. Maybe it should, but there's a bit more to look into than encode. A proxy may want to do more than add a Route-Record AVP for example. Let me look into it a bit more.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request closed without merging**
