### PR TITLE
Document the -epmd_module switch

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
What purpose does documenting -no_epmd serve when there is already -start_epmd true|false?

Also, the -epmd_module flag is documented in the init(3) documentation, not sure which place is better, or if we may as well put so when looking it is easier to find.

@legoscia Do you have any opinions?

**Comment by josevalim** [comment]
@garazdawi `-no_epmd` does not start the epmd OS process and does not start the Erlang epmd module. `-start_epmd` does not start the OS process but still starts the Erlang epmd module. So they have different behaviour.

After I read @legoscia's article, I looked at the `erl` docs and didn't find the documentation for the `-epmd_module`, hence the PR. :) I think that, given it is a flag to the `erl` command, we should at least mention it here even if it ends up linking to the `init` documentation. Could you please show me where it is documented in init? I couldn't find it. :S

Thank you!

**Comment by garazdawi** [comment]
What is the scenario when you want to use -no_epmd while still starting a distributed node?

Just search for -epmd_module in http://erlang.org/doc/man/init.html and you will find it.

**Comment by josevalim** [comment]
> What is the scenario when you want to use -no_epmd while still starting a distributed node?

With `-no_epmd` you have a guarantee the distribution services won't be started, not even later by calling `net_kernel:start/2`. With `-start_epmd`, you can still start the distribution services if `epmd` has been started on the side or by another node instance. So `-no_epmd` gives you a hard guarantee while `-start_epmd` doesn't.

Therefore I would prefer to use `-no_epmd` if I want to guarantee the distribution is not used. However, given I personally don't have a use case for it, take it with a grain of salt. I can see that @fenollp is already using the `-no_epmd` option on Kazoo, maybe he can expand why.

> Just search for -epmd_module in http://erlang.org/doc/man/init.html and you will find it.

Sweet, thank you. Btw, the switches `-s` and `-run` are also used by the init app and documented in `erl`. It has a note though in the `erl` page that they are an init flag, example:

    -s Mod [Func [Arg1, Arg2, ...]] (init flag)

I would recommend doing the same for `-epmd_module` then. I will let others chime in before I make any changes.

**Comment by garazdawi** [comment]
> > What is the scenario when you want to use -no_epmd while still starting a distributed node?

> With -no_epmd you have a guarantee the distribution services won't be started, not even later by calling net_kernel:start/2. With -start_epmd, you can still start the distribution services if epmd has been started on the side or by another node instance. So -no_epmd gives you a hard guarantee while -start_epmd doesn't.
>
> Therefore I would prefer to use -no_epmd if I want to guarantee the distribution is not used. However, given I personally don't have a use case for it, take it with a grain of salt. I can see that @fenollp is already using the -no_epmd option on Kazoo, maybe he can expand why.

Using it to disable starting of distribution seems a bit strange. You just have to call `erl_epmd:start().` before you call `net_kernel:start([Name]).` to be able to start it anyway.

The reason why I'm questioning documenting the option is that we guarantee backwards compatibility of options/flags that are documented. So if we document this option I want there to be a good use case for it. If we cannot come up with one, I'd rather leave it un-documented so that it may be removed in future releases without a deprecation cycle.

> Btw, the switches -s and -run are also used by the init app and documented in erl. It has a note though in the erl page that they are an init flag, example:
> 
> -s Mod [Func [Arg1, Arg2, ...]] (init flag)
> I would recommend doing the same for -epmd_module then. I will let others chime in before I make any changes.

Agreed.

**Comment by josevalim** [comment]
Good points. I was not aware the option may be private. I will update the
PR with the proposed changes.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by psyeugenic** [comment]
Good catch @garazdawi

**Comment by josevalim** [comment]
Updated to describe only `-epmd_module` and mention it is a init flag using the same markup as `-s`, `-run`, etc.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
