### PR TITLE
otp: Remove HiPE

### PR DESCRIPTION
**Pull request by jhogberg**
As [mentioned on our mailing list](http://erlang.org/pipermail/erlang-questions/2020-June/099645.html) earlier this year, we're going to remove HiPE unless someone can commit to maintaining it long-term. It has been half-broken since OTP 22 and no longer works in OTP 24.

We cannot commit any resources to fixing it before release, let alone maintain it over time, so now's the time to step up if someone wants to keep it.

### CODE REVIEW

**Comment by essen** [comment]
RIP.

**Comment by bjorng** [comment]
`compile_SUITE:forms_2/1` fails.

**Comment by bjorng** [comment]
(Testfallet testar fortfarande optionen `from_beam` som inte längre stöds.)

**Comment by bjorng** [comment]
Because you have removed `from_beam` you should also remove the mapping of the `.beam` extension in `erl_compile:compiler/1` and `compile:from_beam/3`.

**Comment by jhogberg** [comment]
> Because you have removed `from_beam` you should also remove the mapping of the `.beam` extension in `erl_compile:compiler/1` and the function `compile:from_beam/3`.

Done, also done the same for `c.erl` etc.

**Pull request merged**
