### PR TITLE
ftp dialyzer fixes

### PR DESCRIPTION
**Pull request by kostis**
Clean up the code of files under `lib/inets/src/ftp` to eliminate dialyzer warnings and make the code check for possible errors that may occur rather than just ignoring them.

The latter may cause test case failures in case there are tests that create erroneous situations but do not check for them.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by HansN** [comment]
Hi,
the `ok = file_close(Fd)`  changes are a bit dangerous.

With a server S and a client C connected to each other, there could be a situation when both S and C decides to close the connection at time Ts and time Tc respectively .  With Ts < Tc, and Tc-Ts within some intervall, C could have had the connection closed in the OS and the driver in the Erlang VM just BEFORE C calls `file_close/1`.  The result will of course be that `file_close/1` returns {error,Something} which gives a badmatch exception.

This is quite normal in protocol handling code and a thing to be prepared for.  With thinking of `file_close/1` semantics as _make sure the connection is closed at return_ the correct would be to let `file_close/1` always return `ok`.

When running the test suites there is indeed failures caused by such badmatches.  To be honest, I have not checked that the code itself calls `file_close/1` multiple times...

Otherwise it looks OK.

**Comment by kostis** [comment]
I can of course push a new commit that makes these `_ = file:close(Fd)` instead, but this may have as a side-effect that file errors are ignored.  Since there are only three places where `ok = file:close(Fd)` appears, it should be easy to check which of them are problematic in the test suites and perhaps investigate a bit deeper if the problems are real or not (i.e. it's the tests themselves that are not OK).

If you think it's not worth the effort, let me know and I can push a new commit that substitutes the three `ok` with `_`.

**Comment by HansN** [comment]
I had a look and traced the failing cases.  There is no error neither in the test suite nor in the ftp.erl code.  

What happens is that the particular server I test with does two operations(*) towards the client after a file transfer.  Both operations does (among other things) a `file_close/1` where the second one returns `{error,einval}`.  I belive the two operations can come in arbitrary order, so that both `file_close/1` can return `ok | {error,einval}` as correct results.

The best and most readable would of course be to replace the two problematic file_close/2 with
```
case file_close(Fd) of
    ok -> ok;
    {error,einval} -> ok
end
```

The third `file_close/1` in `send_file/2` should as far as I can see never return anything but ok.

(*) the two operations are: 1) close the data channel after a file transfer, and 2) send a "226 Transfer complete" message as response to the file transfer request.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
