### PR TITLE
erts: Remove `erts/etc/darwin/Info.plist`

### PR DESCRIPTION
**Pull request by wojtekmach**
Ref: https://github.com/erlang/otp/issues/6070#issuecomment-1168676066

### CODE REVIEW

**Comment by wojtekmach** [comment]
Also, please see the related PR #5393 that was already merged.

If accepted, I'm not sure if this should be against master or it is ok to be against maint.

cc @dominicletz

**Comment by dominicletz** [comment]
@wojtekmach if this is accepted it will not be possible with the default Erlang build will to use the WebView against localhost addresses. Which means electron like use cases, but even development can only be done with custom builds.

For that reason I recommend against emerging this.

**Comment by josevalim** [comment]
@dominicletz this is tricky because, by having this file included, then it becomes impossible for us to customize our own builds. So I would prefer to make custom builds required in order to access some features rather than not allowing configuring custom builds at all.

**Comment by dominicletz** [comment]
How does the default file impact a custom build? When you do a custom build you can choose any other plist file to be used instead - unless I'm missing something.

**Comment by josevalim** [comment]
@dominicletz Mac actually looks inside the running program first. If the running program has a plist, then it doesn't fallback to the one in the app bundle.

**Comment by dominicletz** [comment]
For a custom build you can control which plist file will be embedded and just use yours instead of the default. I'm not sure if you can change the embedded plist after compilation again? - Would be nice if there is an easier way than a full recompile.

**Comment by josevalim** [comment]
That's exactly the issue though. AFAIK it requires full compilation without the .plist. :(

**Comment by wojtekmach** [comment]
@dominicletz I put together a sample app that does two things:

1. starts a web server at port 8000, rendering some html and loading an image at `/logo.png`
2. starts a `wxWebView` pointed to `http://localhost:8000`

Here's the code: https://github.com/wojtekmach/demo

I built the app using the OTP compiled on this branch, without the Info.plist. As far as I can tell it works well, no problems with loading things from the localhost.

To simulate distributing the app, I copied the app to a blank slate Mac VM and it worked too.

If you'd like to try it out, here's the zipped app: [demo.zip](https://github.com/erlang/otp/files/9111505/demo.zip)

If I'm not triggering the use case behind the `NSAppTransportSecurity` setting, please let me know and I'll happily do more tests.

Btw, this is how I've confirmed that the Info.plist is gone:

```
# the app
~/demo[main]% otool -P _build/dev/demo.app/Contents/Resources/rel/erts-13.0.2/bin/beam.smp
_build/dev/demo.app/Contents/Resources/rel/erts-13.0.2/bin/beam.smp:

# my OTP checkout
~/src/otp[wm-remove-Info.plist]% otool -P release/x86_64-apple-darwin20.6.0/erts-13.0.2/bin/beam.smp
release/x86_64-apple-darwin20.6.0/erts-13.0.2/bin/beam.smp:

# OTP checkout at master, at another machine:
~/src/otp[master]% otool -P release/aarch64-apple-darwin21.5.0/erts-13.0.2/bin/beam.smp
release/aarch64-apple-darwin21.5.0/erts-13.0.2/bin/beam.smp:
(__TEXT,__info_plist) section
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
```

**Comment by wojtekmach** [comment]
@dominicletz sorry for a ping. If you could take a look at the comment above and help us out we’d really appreciate. Put it another way, if there is a sample app that requires this plist and that I could run myself, I’d be happy to dig into that. Thanks!

**Comment by dominicletz** [comment]
Hey @wojtekmach, no worries on the ping - This is an interesting experiment with bundling a plist file after compilation. Is there any way to run the development environment this way so that the WebView works in the development environment (e.g. while editing code) as well?

**Comment by wojtekmach** [comment]
@dominicletz sorry but just so we're on the same page what I'm saying is this setting isn't needed. I'm running OTP without the Info.plist and it works well. I have tested that demo project above, `erl> wx:demo().`, and https://github.com/elixir-desktop/desktop-example-app just now. Everything works well.

If you can help me reproduce a situation where that setting _is_ needed, I'm happy to keep digging.

**Comment by wojtekmach** [comment]
I forgot to mention, fwiw my setup is the following:

macOS Monterey 12.4
OTP with my patch off maint (just updated; see https://github.com/wojtekmach/otp/commits/wm-remove-Info.plist)
wxWidgets 3.1.7 (installed with brew)

Regarding running development environment and some sort of custom `MyApp.app/Contents/Info.plist` I think it's tricky to make it ergonomic but not impossible to do. I think what we'd need is some sort of `$ mix app` task that would build the project, build the `.app`, and `$ open /path/to/my.app`. So we'd have potentially two VMs running, one that started the Mix task (or equivalent) and one from the .app, and probably communication between the two so they exit together, etc. On one hand it is definitely adding decent amount of complexity but on the other hand something like this is required to test app events like "open url", "open file", etc, anyway. I'm keen on exploring this down the road, I think it will be very useful.

**Comment by wojtekmach** [comment]
I changed base branch to maint.

**Comment by dominicletz** [comment]
In terms of reproducing @wojtekmach the effect of the plist there are no doubts it's working as documented by Apple. I'm attaching a screen recording with two runs. One with the current build including the plist and one with the plist entry invalidated. You can see that without the `localhost` plist entry the WebView only renders a white page in the example. I'm running the default brew-based build of OTP 24.3.2 which comes with the built-in plist. For the second run, I invalidate the plist entry by binary replacing the word `localhost` with `localpost` so that it doesn't match anymore. 

https://user-images.githubusercontent.com/2987674/181038052-f6af9a27-3d53-45b3-b477-52da5d2c044b.mov

 This is precisely the reason why I'm opposed to merging this change, it will cause users to only see a white page -- there is not even an error message.

**Comment by wojtekmach** [comment]
Excellent, thank you, I will try to reproduce this behaviour on my machine. Again, in my OTP build per this branch everything worked correctly as in the beginning of the video, the app window was filled in with web content, hence I am pushing for this change. But I clearly need to understand more pieces so thank you again for providing a way to hopefully reproduce the results.

**Comment by dominicletz** [comment]
After some offline discussion with @wojtekmach we found that this behaviour changed in macos - When I contributed the plist file I was still using a pre macOS 10.12 - In addition, it seems the macOS versions only using the new default if no plist instructions `NSAppTransportSecurity` are present. This is explaining the behavior in the video above. From the docs:
 
https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking 

> In iOS 10 and macOS 10.12 and later, ATS allows all three of these connections by default, so you no longer need an exception for any of them. However, if you need to maintain compatibility with older versions of the OS, set both of the [NSAllowsArbitraryLoads](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads) and NSAllowsLocalNetworking keys to YES.

I've tested new builds now without the plist (as per this PR) and those seem to work fine. All this said I'm in favor of merging this PR. Thanks, @wojtekmach for being this persistent and for helping get to the root of this.

**Comment by wojtekmach** [comment]
Thank you @dominicletz!!!

**Comment by frazze-jobb** [comment]
Sorry for waiting so long, but this seems fine I will merge it

**Pull request merged**
