### PR TITLE
ssl: Fix ssl_pem_cache_SUITE.pem_cleanup test

### PR DESCRIPTION
**Pull request by essen**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Yes, this is a new test case introduced on maint, and as it is a white box test, it does need this update for master. We just had not had time to tend to it yet, so thank you for fixing it.

**Comment by zhird** [comment]
@IngelaAndin is still working with this code, so she will make sure to update the test as she makes changes.

**Comment by essen** [comment]
Fair enough.

**Pull request closed without merging**
