### PR TITLE
Add show econnreset socket option

### PR DESCRIPTION
**Pull request by nybek**
This is based on the fix_gen_tcp_shutdown branch pushed yesterday.

EEP Light for adding 'show_econnreset' TCP socket option
========================================================

Why do we need this new feature?
--------------------------------

In the current TCP implementation, Erlang/OTP treats ECONNRESET errors
on incoming receives as though they are a normal close. In other
words, incoming RSTs are treated as though they are FINs.

When writing many types of TCP servers and clients (all in my opinion)
it's important to be able to distinguish between connections that were
closed because a FIN arrived and those that were closed due to an RST.
An RST might be sent to us for a variety of reasons, such as:

  * A TCP peer intentionally aborts a connection, for whatever
    reason, by setting the option SO_LINGER to {TRUE, 0} on the
    socket.

  * A TCP peer calls close() without fully reading what's in the
    kernel receive buffer. On Linux, at least, the kernel sends
    an RST when this happens.

Unless you are using an application protocol which will confirm
that you have received a complete payload, you should treat an RST
as an indication that the payload you received was incomplete. Not
all application protocols are so helpful.

As a concrete example of when one might need to distinguish RSTs
from FINs, let's assume that we are writing a HTTP Proxy/Cache
server. The HTTP spec says that a client that receives a response
without a Content-Length header is supposed to treat this as a valid
response and read from the stream until the server closes the
connection [2]. Though the spec says nothing about RSTs in this
context, I certainly wouldn't intentionally cache any document
received in such a way when the connection was terminated with an
RST. Any yet with the way Erlang/OTP currently is, I don't have the
option of detecting RSTs.

There has already been at least one other person on the
erlang-questions mailing list who has requested the ability to
receive ECONNRESET errors (see [3]).

How did you solve it?
---------------------

By adding a socket option {show_econnreset, true|false} that
enables the display of received ECONNRESET errors. By default,
this option is set to false for each socket.

Risks or uncertain artifacts?
-----------------------------

If you look at the changes that this patch makes to inet_drv.c
you will notice that it translates an ECONNABORTED error received
on Windows into an ECONNRESET. Windows definitely returns
ECONNABORTED on some occasions to signify than an RST has
arrived - some of the test code will fail without this change.
However, it's possible that Windows returns ECONNABORTED on
a connected socket for other reasons also (I don't actually know),
and it might be the preference of the Erlang/OTP team to leave
this error to be returned as {error, econnaborted} and let the
user to handle it as they see fit. Note that you are currently
masking all close errors that return on Windows in this part of
the code to normal {error, closed}, so the translation this patch
makes isn't as disruptive as it might sound.

This patch only solves part of the problem. It stops ECONNRESET
errors that are received from a recv() syscall from being
treated as a normal connection termination. It does not solve
the problem where a send() syscall is made and an error is
returned there indicating that an RST has been received. This
second problem is more difficult to solve and will be handled
in a separate patch.

References:
-----------
[1] https://tools.ietf.org/html/rfc7230#section-6.6
[2] https://tools.ietf.org/html/rfc7230#section-3.3.3
[3] http://erlang.org/pipermail/erlang-questions/2015-February/083239.html

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We will revisit this patch and the other show_econnreset once we taken gen_tcp:shutdown/2 patch all the way, so please have some patience.

**Comment by nybek** [comment]
On Wed, May 20, 2015 at 03:29:39AM -0700, Ingela Andin wrote:
> We will revisit this patch and the other show_econnreset once we taken gen_tcp:shutdown/2 patch all the way, so please have some patience. 

Will do. Thanks.

**Comment by IngelaAndin** [comment]
We agree that it is desirable to be able to separate the cases of  tcp FIN and RST.
gen_tcp:shutdown/2 patch is now merged to master, so a first step will be to rebase this patch on current master.

**Comment by nybek** [comment]
Great, I'll rebase this (and #732) as soon as I see the shutdown/2 in master.

**Comment by nybek** [comment]
I've rebased it.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by nybek** [comment]
I've got an updated version of this patch and #732 which removes the ?line
macros from the tests. This brings them inline with the latest
gen_tcp_misc_SUITE. If you want them at any time, just let me know.

**Comment by IngelaAndin** [comment]
We have decided that we do not want to accept only this PR without accepting #732 also. Though we appreciate that you made them into tow PR from the start as the second on has more question marks. But it feels strange not have the whole solution at the same time.  And yes we like to get rid of the line macros. 

I have been reading windows documentation pondering on the return values. I think the description
of abort is quite vague.

I think that it feels natural to give a return value that is as accurate as possible. So if there has been a connection reset it is nice to know that that was the reason even in the send case. I do not like the idea to get some other error that is more vague because the real error state was lost, if it is possible for us to keep track of what really happed, which I believe your patch does.

We think that keeping Erlang APIs as portable as possible is a strong argument for your solution. 
It is hard to foresee all implications of translating the error codes, but introducing it as a separate
options with the name you have chosen makes it feel acceptable, and also a way that we can let people try and see what happens without taking to big risks.

@essen Although I see your point in wanting to get the reset errors without an  option that is way to risky in this stage of 18, and even if it had been before the release candidates it would have been risky.
I am not ruling out it could be default one day but we have to take small steps, especially in such areas that may have a big impact on a lot of code out there.

**Comment by essen** [comment]
Yep, one day, good enough to me. :-)

**Comment by nybek** [comment]
I am pleased that you are interested in both the patches together. I 
personally wouldn't turn on the show_econnreset option unless I have
the functionality in both patches. 

On the Windows side of things, I think it should be safe to release the
code as is. If bug reports come in where people have set show_econnreset
and are seeing {error,econnreset} in circumstances where no RST was ever
sent, then it might be possible to detect those exceptions and revert
to passing back {error,closed} in those cases.

When you were commenting on the accuracy of the return value, are you
suggesting:

 (a) It's better to return {error,epipe} when the OS says an EPIPE
     has occured because that more accurately reflects what the
     OS said; or

 (b) It's better to return {error,econnreset} when we know that
     an RST was sent from a peer, even though the OS reported EPIPE,
     because this more accurately represents what actually happened.

This patch obviously follows the approach (b).

Should I do the following to move forward:

 1. Squeeze the two commits together (with ?line macros removed).

 2. Update the commit message.

 3. Push the single commit to this branch (#731).

Thanks Ingela.

**Comment by IngelaAndin** [comment]
I meant b :) 

Well you do not necessarily  need to squeeze them. I would like the two commits on the same branch
(PR).  If to squeeze or not is kind of trade off I think. Even the both commits are highly related there can also be benefits in having the change occur  in smaller steps, as it makes reviewing and maintenance easier.

**Comment by nybek** [comment]
I'm in total agreement. I'd find it terribly confusing to read a single commit
for this feature.

Both commits are now on this branch. Is it okay if I close #732?

**Comment by IngelaAndin** [comment]
Yes thats okay, do that.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Tests fail:
*** CT Error Notification 2015-06-13 06:39:40.071 ***
gen_tcp:connect failed on line 148
Reason: badarg

=== Ended at 2015-06-12 23:07:47
=== Location: [{gen_tcp,connect,148},
              {gen_tcp_misc_SUITE,econnreset_after_async_send_passive,1352},
              {test_server,ts_tc,1408},
              {test_server,run_test_case_eval1,984},
              {test_server,run_test_case_eval,926}]
=== Reason: bad argument

Etc
We get badarg on:
gen_tcp_misc_SUITE	econnreset_after_async_send_passive
gen_tcp_misc_SUITE	econnreset_after_sync_send
gen_tcp_misc_SUITE	show_econnreset_passive
gen_tcp_misc_SUITE	econnreset_after_async_send_active
gen_tcp_misc_SUITE	econnreset_after_async_send_active_once
gen_tcp_misc_SUITE	show_econnreset_active_once
gen_tcp_misc_SUITE	show_econnreset_active

**Comment by nybek** [comment]
It's obviously not recognising the show_econnreset option given to
gen_tcp:connect/3. I expect the preloaded prim_inet.beam needs to
be updated.

During development I always used:

    ./otp_build update_preloaded --no-commit

To make it permanent, I expect you need to run:

    ./otp_build update_preloaded

**Comment by IngelaAndin** [comment]
You are correct, we have updated the preloaded now, it is looking better but not all builds have completed yet. If everything goes well when all builds have completed it will be merged for 18, if there are some problems then it depends ...

**Comment by nybek** [comment]
Ingela, whatever the outcome, thanks a million for your help with this patch
and with the shutdown/2 one.

Fingers crossed it makes it over the line!

**Comment by zhird** [comment]
Merged to master.

**Comment by essen** [comment]
Great work! \o/

**Comment by lpgauth** [comment]
:+1:

**Comment by nybek** [comment]
Really pleased! :-)

**Pull request closed without merging**
