### PR TITLE
RFC: ecdhe_psk cipher suites

### PR DESCRIPTION
**Pull request by RoadRunnr**
This PR adds:
* logic to make sure Certificate Requests are not send and rejected when received if a anon cipher suite has been negotiated.
* ECDHE_PSK cipher suites

There is no test for the Certificate Requests logic, as I don't have an idea how to test this.
The ECDHE_PSK suites might be broken, but the test suite passes anyway due to https://bugs.erlang.org/browse/ERL-460

I can split this into two PR's if needed. The two changes are somewhat related, but there is no dependency between them.

### CODE REVIEW

**Comment by RoadRunnr** [comment]
This PR addresses the question from @erszcz -- https://github.com/erlang/otp/pull/936#issuecomment-316974471

**Comment by RoadRunnr** [comment]
I've manually modified the test suite to work around ERL-460 and can confirm that the PSK ciphers work.

The new cset adds the ECDHE PSK with GCM ciphers. They also pass the tests. Their tls cipher ids are not finally assigned by IANA, yet. So we might want to postpone adding them?

**Comment by RaimoNiskanen** [comment]
We'll have to wait for Ingela to get back from her vacation.  She is rewriting the framework (writing a framework?) for certificate handling in the test suites...

**Comment by IngelaAndin** [comment]
Noticed you made the request for master, so testing will have to wait another day as my fix of running the test suites need to pass on all test machines for maint before merging it to master.

**Comment by IngelaAndin** [comment]
Tests are looking good. I am contemplating your other question about testing and splitting, will get back to you soon.

**Comment by IngelaAndin** [comment]
When it comes to the certificate request logic that is very hard to test. We are hoping to be able to add some quickcheck/proper test in an foreseeable future  and then we could have the bases to preform such test. We have code reviewed it and decided to accept it. Different commits will do no need to split this PR. I will merge this PR now and we appreciate if you help us keep track of IANA status.

**Pull request merged**
