### PR TITLE
Allow ssa_opt to run on modules with NIFs

### PR DESCRIPTION
**Pull request by frej**

### CODE REVIEW

**Review by bjorng — APPROVED** [review]
Looks good to me. Please rebase on the latest `master` and resolve the merge conflicts.

**Comment by frej** [comment]
> Looks good to me. Please rebase on the latest `master` and resolve the merge conflicts.

Done.

**Comment by bjorng** [comment]
Thanks! Added to our daily builds.

**Comment by bjorng** [comment]
Thanks for your pull request.

**Pull request merged**
