### PR TITLE
Compile external fun expressions to literals

### PR DESCRIPTION
**Pull request by michalmuskala**
The expressions `fun M:F/A`, when all elements are literals are also
treated as literals. Since they have consistent representation and
don't depend on the code currently loaded in the VM, this is safe.
This can provide significant performance improvements in code using such
functions extensively - a full function call to erlang:make_fun/3 is
replaced by a single move instruction and no register shuffling or
saving registers to stack is necessary. Additionally, compound data
types that contain such external functions as elements can be treated as
literals too.

---

The tests for parsing core and asm fail right now. I'm not really sure what would be a nice way to represent those literals in core and asm listings. You can see some attempts to bring `fun m:f/a` syntax to core, I'm not sure that's the best way to go.

I also got a failure in `qlc_SUITE:otp_5644/1`, but I don't really understand what is going on in there and why it might be failing.

Those are the only failures in compiler, stdlib and emulator suites - I would appreciate guidance on solving them.

### CODE REVIEW

**Comment by bjorng** [comment]
We like this idea.

I think that using the `fun M:F/A` syntax in Core Erlang is reasonable. @richcarl , what do you think?

We are quite busy at the moment, but we will try to get back to you regarding the failed QLC test case.

**Comment by bjorng** [comment]
The failure in `qlc_SUITE` has nothing to do with QLC. Here is a simple module that shows the bug:

```
t() ->
    case is_function(fun mod:name/0, 0) of
        true -> is_function;
        false -> is_not_function
    end.
```

```
1> t:t().    
is_not_function
2> 
```

The reason for the failure is the literal in the following instruction:

    {test,is_function2,{f,3},[{literal,#Fun<mod.name.0>},{integer,0}]}.

The test will fail for a literal fun because of the following line in `ops.tab`:

    is_function2 Fail=f acq Arity => jump Fail

(Make sure to add tests when you fix this.)

**Comment by michalmuskala** [comment]
Ah, that makes sense. Thank you for your help on this, I'll send a fix soon.

**Comment by michalmuskala** [comment]
I fixed the qlc issue and added tests for the literal expression. I also expanded the literal tests in general to cover more cases.

The issue with how to represent the function in both core erlang and in the assembly still remains open.

**Comment by bjorng** [comment]
I have pushed a commit to your branch that adds parsing (as terms) and printing of external fun literals. Here is an example how it looks in the shell:

```
1> fun erlang:abs/1.
fun erlang:abs/1
2>
```

With this commit, the `asm/1` test case succeeds.

I suggest that you use the same syntax in Core Erlang.

**Comment by michalmuskala** [comment]
I pushed a change that fixes the core roundtrip test. The core erlang now uses an explicitly quoted syntax: `fun 'erlang':'abs'/0` - I think that's consistent with the rest of the core syntax.

**Comment by bjorng** [comment]
Looks good. 

Please squash the commits. When you have done that, we will add this branch to our daily builds.

**Comment by michalmuskala** [comment]
Squashed and ready to test

**Comment by bjorng** [comment]
Thanks! Added to our daily builds. If tests are successful, this branch will be merged next week.

**Pull request merged**
