### PR TITLE
ssl: Add BEAST mitigation selection option

### PR DESCRIPTION
**Pull request by kennethlakin**
This PR adds a new ssloption that allows one to select the content splitting method (1/n-1 or 0/n) used by SSLv3 and TLSv1.0 connections or disable content splitting entirely.

Documentation updates and tests are included in the patch.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We do now want to put this branch into testing again, it was stalled due to gen_statem rewrite. 
Could you rebase it and please remove ?config macros from the tests and replace with proplists:get_value. This is a change we are doing to all test suites to remove legacy from test_server and make the tests suites purely common_test.

**Comment by kennethlakin** [comment]
Rebased with master and switched from ``?config`` to ``proplists:get_value/2`` in the tests that I authored. I also ran the ``ssl_basic_SUITE`` test suite. All tests passed.

**Comment by kennethlakin** [comment]
I rebased with master, made the requested changes, and ran the ``ssl_basic_SUITE`` test suite. All of my test cases still pass.

**Comment by IngelaAndin** [comment]
Thank you, have put it into the test machinery.

**Comment by IngelaAndin** [comment]
The following code needs to consider that the variable C might become undefined as not  all
test machines support all algorithms and hence all options are not always generated.

```
rizzo_add_mitigation_option(Value, Config) ->
    lists:foldl(fun(Opt, Acc) ->
                    C = proplists:get_value(Opt, Acc),
                    N = lists:keystore(beast_mitigation, 1, C,
                                       {beast_mitigation, Value}),
                    lists:keystore(Opt, 1, Acc, {Opt, N})
                end, Config,
                [client_opts, client_dsa_opts, server_opts, server_dsa_opts,
                 server_ecdsa_opts, server_ecdh_rsa_opts]).
    
```

**Comment by kennethlakin** [comment]
An appropriate change has been pushed. Do I need to handle the case where *no* algorithms are supported, or will the test suite simply not be run in that case?

Also, is there a way to enumerate the names of the available server/client opts? I created the hard-coded list from reading ``client_server_opts/2`` (lines 4286 through 4300), but looking at ``run_suites/4`` (particularly lines 4305 through 4361) makes me wonder if my list is incomplete.

**Comment by IngelaAndin** [comment]
There are additional cipher suites that are not supported by default, these will not be in the rizzo tests. 
I think a lot of things have been add adhoc to the tests and it is time to refactor, if I just can find the time.

**Comment by kennethlakin** [comment]
Ah, drat. I screwed up the formatting in ``lib/ssl/doc/src/ssl.xml``. The period on line 426 is outside the closing ``<p>`` tag which puts the period on another line and looks awful. Should I create a new PR to fix this, or rebase and push to my ``beast-mitigation-options`` branch, or is this a correction that's small enough to bypass that process?

The patch for the correction is at the end of this message. I'm more than happy to get the fix to you guys in another way.

```diff
diff --git a/lib/ssl/doc/src/ssl.xml b/lib/ssl/doc/src/ssl.xml
index 33ece8f..178e22f 100644
--- a/lib/ssl/doc/src/ssl.xml
+++ b/lib/ssl/doc/src/ssl.xml
@@ -423,7 +423,7 @@ fun(srp, Username :: string(), UserState :: term()) ->
       <tag><c>{beast_mitigation, one_n_minus_one | zero_n | disabled}</c></tag>
       <item><p>Affects SSL-3.0 and TLS-1.0 connections only. Used to change the BEAST
        mitigation strategy to interoperate with legacy software.
-       Defaults to <c>one_n_minus_one</c></p>.
+       Defaults to <c>one_n_minus_one</c>.</p>
 
       <p><c>one_n_minus_one</c> - Perform 1/n-1 BEAST mitigation.</p>
 
```

**Comment by IngelaAndin** [comment]
As your beast-mitigation option branch is already merged, it would be easiest for us if you could make a new PR.

**Comment by kennethlakin** [comment]
The new PR is #1087 .

**Pull request merged**
