### PR TITLE
Make shell history work for SSH shells

### PR DESCRIPTION
**Pull request by isvilen**
Give user customization opportunity before SSH shell history is loaded

### CODE REVIEW

**Comment by frazze-jobb** [comment]
Hi,
Im not sure what you are trying to solve with this PR, it looks like you might be missing some changes.
Since you do not seem to have added any customization.
We want to avoid saving to history when you for example have called io:get_line from within the standard erl shell.
If you use the erlang ssh_daemon you should be getting the shell history saved.
Maybe we can discuss and come up with something better?

**Comment by isvilen** [comment]
> Hi, Im not sure what you are trying to solve with this PR, it looks like you might be missing some changes. Since you do not seem to have added any customization. We want to avoid saving to history when you for example have called io:get_line from within the standard erl shell. If you use the erlang ssh_daemon you should be getting the shell history saved. Maybe we can discuss and come up with something better?

Hi,
I have application with custom SSH shell (which uses io:get_line in its REPL implementation).
Currently if shell history is enabled then the lines entered in Erlang standard interactive shell are available in SSH shell, but they are meaningless there, and the lines entered in SSH shell are not saved in the history.
 I am looking for a way to use custom shell_history module in which to distinguish between normal Erlang shells and my custom SSH shells. The changes in this PR solves this for my use case, but if there is other way I am open to suggestions.
:smile:

**Comment by frazze-jobb** [comment]
But either way, then your ssh shell would still have commands from the standard interactive shell.
I think what needs to be done is that a flag is added which decides if we should ignore io:get_line or not.
Add a flag:
`-stdlib shell_history_ignore_getline false`
`application:get_env(stdlib, shell_history_ignore_getline, true),`

And your ssh shell needs to have its own history file.
`-kernel shell_history_path ssh_shell_history_path`

**Comment by frazze-jobb** [comment]
With this change https://github.com/erlang/otp/pull/8792, it should be possible to select yourself which calls should be saved in history, feel free to continue the discussion if you disagree

**Comment by isvilen** [comment]
@frazze-jobb #8792 is unrelated to my problem, which is to have separate history files for normal erlang shells and custom SSH shells :disappointed:.
What I hope to get is some way to distinguish between normal shells and custom shells in my implementation of `shell_history` callback.

**Comment by frazze-jobb** [comment]
Okey my bad. 
Anyhow the change that you made in this PR is done in this PR when group was refactored. https://github.com/garazdawi/otp/blob/0169a29132aa8cec41e4c7fba608c11b012dd64d/lib/kernel/src/group.erl#L145
If you want more customizability pushed upstream, feel free to submit a new PR.

**Comment by isvilen** [comment]
> Okey my bad. Anyhow the change that you made in this PR is done in this PR when group was refactored. https://github.com/garazdawi/otp/blob/0169a29132aa8cec41e4c7fba608c11b012dd64d/lib/kernel/src/group.erl#L145 If you want more customizability pushed upstream, feel free to submit a new PR.

:smile:  I managed to miss that... I think that this is enough for my use case, thanks.

**Pull request closed without merging**
