### PR TITLE
Refactor Dialyzer parallel compilation

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit messages for details.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
"Inline functions in dialyzer_worker"
I don't agree with you here. Giving names to short pieces of code
can often act as documentation. But I think Stavros should comment
upon this commit as well on the other commits.

**Comment by lucafavatella** [comment]
Thanks for your feedback. I understand action is on me - I hope to come back to this in a month or so.

**Comment by uabboli** [comment]
I'll create a ticket for this pull request. All commits except bf3b922 will be included in the 'master' branch (OTP 19.0) with a few minor modifications.

**Comment by lucafavatella** [comment]
I see this merged in 5ca1e8e.
@uabboli Thanks. In future pull requests I will pay more attention to subjectivity in proposed code changes and proposed commit messages.

**Pull request closed without merging**
