### PR TITLE
Fix typos in lib/crypto

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by HansN** [comment]
Thanks!  Could you please rebase at least the documentation files onto maint?

**Comment by kianmeng** [comment]
> Thanks! Could you please rebase at least the documentation files onto maint?

@HansN Not sure how to proceed with this?

```bash
$ git checkout maint
hint: If you meant to check out a remote tracking branch on, e.g. 'origin',
hint: you can do so by fully qualifying the name with the --track option:
hint: 
hint:     git checkout --track origin/<name>
hint: 
hint: If you'd like to always have checkouts of an ambiguous <name> prefer
hint: one remote, e.g. the 'origin' remote, consider setting
hint: checkout.defaultRemote=origin in your config.
fatal: 'maint' matched multiple (2) remote tracking branches
```

**Comment by HansN** [comment]
@kianmeng I'm not quite sure what you need help with, but a good start is 

- check the git help: `git help rebase`
- the [github help](https://docs.github.com/en/get-started/using-git/about-git-rebase)

I _guess_ that what you need to do to rebase onto maint is something like:

```
git fetch upstream maint
git checkout maint
git checkout fix-typos-in-lib-crypto
git rebase --onto maint HEAD^
```
where upstream is the repository from which you fetched master.
You will probably get merge conflicts. In that case, do `git status` and edit the files that have conflicts. Follow the instructions printed by `git status` to proceed.

**Comment by kianmeng** [comment]
@HansN Thanks for the instructions. Please check again.

**Comment by HansN** [comment]
Thanks for the PR.

**Comment by kianmeng** [comment]
@HansN Welcome. Glad to help.

**Pull request merged**
