### PR TITLE
inets: Allow the body of httpc:request/5 to be an iolist

### PR DESCRIPTION
**Pull request by artman41**

### CODE REVIEW

**Comment by IngelaAndin** [comment]
You do not need to update the version manually that will be done by our scripts when it makes into a patch/release.

**Comment by artman41** [comment]
> You do not need to update the version manually that will be done by our scripts when it makes into a patch/release.

Reverted the change to `vsn.mk`, please let me know if any other changes are needed :)

**Comment by kikofernandez** [comment]
I think this pull request looks good

**Comment by kikofernandez** [comment]
@artman41 this is ready to be merged but, could you please rebase it on top of `maint`?
I think this change makes more sense to be available before OTP 26 release.
Thanks!

**Comment by artman41** [comment]
@kikofernandez just rebased on to `maint` 👍

**Comment by kikofernandez** [comment]
I will merge tomorrow if all tests are green. 
Thanks for your contribution @artman41 !

**Pull request merged**
