### PR TITLE
snmp: Make snmp build reproducibly

### PR DESCRIPTION
**Pull request by JeromeDeBretagne**
Remove the current date/time and snmp version from the header section of .hrl files generated by snmpc_mib_to_hrl.

Contributes to #4417 (ERL-1445) and #4482 (ERL-1446).

### CODE REVIEW

**Comment by bmk** [comment]
I am ok with removing the time/date info but I would like to keep the 'version'.

**Comment by JeromeDeBretagne** [comment]
Micael, could you explain the expected value of keeping this version in a comment of the generated header files ? It makes the code change regularly with little (obvious) benefit. If there is a usage I'm missing, I'm happy to add a corresponding comment to document it. In complement, snmpc_mib_to_hrl.erl hasn't changed in the last 10 years so it seems really stable.

**Comment by bmk** [comment]
If the version changes often, then I am thinking of a different 'version'.
I was thinking of 'MIB compiler version', which has not changed for a
long time (so I did not see the problem).

**Comment by JeromeDeBretagne** [comment]
> If the version changes often, then I am thinking of a different 'version'.
> I was thinking of 'MIB compiler version', which has not changed for a
> long time (so I did not see the problem).

If I'm correctly understanding the build system, the 'version' Macro seems defined in this Makefile here:   

https://github.com/erlang/otp/blob/master/lib/snmp/src/compile/Makefile#L32-L34
https://github.com/erlang/otp/blob/master/lib/snmp/src/compile/Makefile#L80-L84

```
include ../../vsn.mk

VSN = $(SNMP_VSN)

ERL_COMPILE_FLAGS += -I../../include \
                     -Dversion=\"$(VSN)$(PRE_VSN)\" \
```

so version is in sync with SNMP_VSN. In my initial tests, it was 5.6.1 and now it is 5.8 indeed.

Since there are many other ways to get the SNMP app version when debugging/reviewing code, I would still propose to remove this instance of 'version' found in a header comment as it adds little benefit I feel.

If you feel strongly it should be kept, let me know and I'll update my PR proposition accordingly. Thank you

**Comment by bmk** [comment]
Still not the version I was thinking about.
Digging a bit deeper I managed to find what I was looking for: mib-format-version
This is not the version printed here though.
Of course there is no way to find out what version of the (mib-) compiler was used when 'generating'
a file. But since we are talking about a rather trivial header file it can be ignored.

**Review by bmk — APPROVED** [review]

**Comment by JeromeDeBretagne** [comment]
@jhogberg Let me know if you have any feedback, now that @bmk has reviewed the proposed change. Thank you.

**Comment by IngelaAndin** [comment]
ping @jhogberg

**Comment by jhogberg** [comment]
Sorry about taking so long to get back on this, I missed the notification :(

 It looks good, thanks for the PR!

**Pull request merged**
