### PR TITLE
stdlib: add quote, unquote functions in uri_string

### PR DESCRIPTION
**Pull request by u3s**
- functions for percent encoding and decoding user data
- intended as utility functions for preparing URI components

### CODE REVIEW

**Comment by samwar** [comment]
🎊  It's great to see a partial solution for #5368. Also interesting that the stdlib was going to run into a problem when `http_uri:encode/decode` were removed.

**Comment by samwar** [comment]
Any thought to writing a set of tests to show that `http_uri:encode/decode` work the same way as 'uri_string:quote/unquote`? It would give us all a higher degree of confidence that the new functions are a drop-in replacement.

**Comment by u3s** [comment]
> Any thought to writing a set of tests to show that `http_uri:encode/decode` work the same/similar way as 'uri_string:quote/unquote`? It would give us all a higher degree of confidence that the new functions are a drop-in replacement.

Sure why not, I can add it for transition period.

**Comment by leoliu** [comment]
I am curious why not call them `encode/decode` as they are usually called? What to do about the api `uri_string:percent_decode/1`?

**Comment by u3s** [comment]
> I am curious why not call them `encode/decode` as they are usually called? What to do about the api `uri_string:percent_decode/1`?

that's a good question and I think maybe should be somehow addressed in a doc update as well.
I guess it's an attempt of choosing less confusing name in general (probably not perfect).

My thinking is that, uri_string also today contains 2 categories of functions
1. those which take URIMap, URIString types as input
2. those which don't

1st group - can act in a component wise manner and preferably implement RFC3986;

for example if path component provided by user contains characters not allowed in that specific component and `uri_string:recompose` is called, they will be automatically percent encoded.

`uri_string:percent_decode` belongs to 1st group as well, I think its primary intention was to revert automatic percent encoding (although its implementation can be used for general percent decode and overlap with `unquote/1` which I don't like :-/)

2nd group - utility functions, to be used in preparations before calling function from 1st group. `quote, unquote` would be member of it as well.
intention of not using verb "encode" or "percent_encode" was to make that characteristic easier to notice.

see also #5368 for more background

**Pull request merged**
