### PR TITLE
Implement ets:update_counter/4

### PR DESCRIPTION
**Pull request by nox**
A story of forbidden love between ets:update_counter/3 and dict:update/4. This new function is an extension of the former and introduces a default value as in the latter. If the key isn't found in the table, the default object is inserted and no elements are incremented.

That new BIF fails for the same reasons as ets:update_counter/3 and if:
 * the default object isn't a tuple;
 * one of the default object's elements mentioned in the operation list isn't an integer.

I have access to neither SPARC nor PPC, so I couldn't test that part of my HiPE changes.

### CODE REVIEW

**Comment by sverker** [comment]
I think you missed some words there.
But my proposal was to add an extra argument to db_lookup_dbterm_hash/tree which will be the default object to insert if key was not found. If the argument is THE_NON_VALUE it will work as before. I think db_lookup_dbterm_hash/tree is only called in two placed (update_counter and update_element).
If key was found OR if default object as inserted, bucket lock must be kept locked until db_finalize_dbterm_hash is called to release it.
Also note that a pseudo deleted object (INVALID_HASH) ) with our key may exist, in which case you should use replace_dbterm as objects with same key must not be separated in the list.
To insert the default object, I think the easiest way is still to make a temporary copy of the top tuple, write the correct key element, and then call either new_dbterm or replace_dbterm.

**Comment by nox** [comment]
I can't use db_lookup_dbterm_* because that function can only return handles but cannot insert new ones, or at least that's my understanding of it given the complexity of the actual db methods that insert new records.

**Comment by sverker** [comment]
I guess it will be a combination of db_put_hash and the old db_lookup_dbterm_hash. Like this:
Do copy-paste on db_put_hash.
Remove everything related to bag and duplicate bag.
Replace the existing key_clash_fail case with the handle initialization from db_lookup_dbterm_hash.
Add handle initialization also after calls to replace_dbterm and new_dbterm.
If no default object is supplied do not call replace_dbterm or new_dbterm but instead do WUNLOCK_HASH(lck) and return 0.

**Comment by nox** [comment]
There is another problem: I must not insert the default object only to later discover that some of its elements weren't integers that can be incremented.

**Comment by nox** [comment]
> If no default object is supplied do not call replace_dbterm or new_dbterm but instead do WUNLOCK_HASH(lck) and return 0.

If no default object, I can just use db_lookup_dbterm, can't I?

**Comment by sverker** [comment]
Yes, either you have to check the default object before inserting it, or implement some sort of rollback that deletes the inserted object.

Sure you can use the existing db_lookup_dbterm if no default object is supplied. I just thought it would be less code with a combined function that handled both cases.

**Comment by nox** [comment]
I changed DbUpdateHandle.mustResize in DbUpdateHandle.flags with constants DB_MUST_RESIZE and DB_NEW_OBJECT to be able to know whether the handle is for a new object or not in the finalize function. This way I can know whether nitems should be incremented in that function.

Furthermore, I added a new keep_object argument to rollback if some updates could not be done.

I've still got some code to write and I will publish my changes when it's done.

**Comment by nox** [comment]
Please refetch, should be good now.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Looks really good.

One bug found though:
replace_dbterm() may reallocate the object at a new address and free the old space. You can therefore not read b->next after replace_dbterm() has returned.

And I have to say the test case is a bit cheesy in more than one way ;-). At least use "repeat_for_opts" to run the tests with different table options. I would also add to the LooperF fun in update_counter_for/1, to do the same update operations with update_counter/4 on a default object. It would also be nice to use ets:safe_fixtable and ets:delete to provoke a pseudo deleted object with INVALID_HASH and get some code coverage on that replace_dbterm() case.

**Comment by nox** [comment]
How do I do code coverage in the C code?

**Comment by nox** [comment]
I used repeat_for_opts in my test, but have no idea what you want in LooperF.

**Comment by sverker** [comment]
I didn't expect you to run code coverage. But if your interested; there is a make target 'gcov' for the emulator and then you use LCOV (http://ltp.sourceforge.net/coverage/lcov.php) to generate html from the coverage logs. That is as much as I known from the top of my head. We have scripts that do this for our automated test runs.

**Comment by nox** [comment]
Oh ok. Can you explain a bit more what you meant about LooperF so I finish the tests?

**Comment by sverker** [comment]
About LooperF:
My idea was to repeat the exact same update operation(s). The only difference is that the object to update is not in the table but instead supplied as DefaultObj.
Something like this:

     + [DefaultObj] = ets:lookup(T, a),
       ?line Ret = ets:update_counter(T,a,Arg3),
     + Ret = ets:update_counter(T, b, Arg3, DefaultObj),   % Use other key
     + [NewObj] = ets:lookup(T, b),
     + ets:delete(T, b),     % cleanup for next loop round

**Comment by sverker** [comment]
repeat_for_opts will give you an Opts argument that you have to pass along to ets:new.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by nox** [comment]
I completed all tests except for the fixed table part. Shouldn't fixtable_next be updated instead?

**Comment by sverker** [comment]
I would do that in LooperF, because there you got all the different types of updates between small and big integers leading to replace_dbterm() having to shrink/reuse/grow the object. I can add that if your out of ideas.

**Comment by nox** [comment]
Would that be enough?

```
+ [DefaultObj] = ets:lookup(T, a),
   ?line Ret = ets:update_counter(T,a,Arg3),
+ ets:safe_fixtable(T, true)
+ Ret = ets:update_counter(T, b, Arg3, DefaultObj),   % Use other key
+ [NewObj] = ets:lookup(T, b),
+ ets:delete(T, b),     % cleanup for next loop round
+ ets:safe_fixtable(T, false)
```

**Comment by sverker** [comment]
No. The point is to provoke the case with a pseudo deleted object (marked with INVALID_HASH) and that can only be done by deleting an object while the table is fixated and keeping it fixated. A call to safe_fixtable(T,false) will purge all pseudo deleted object from the table.
I think the best way is to create a second table that is kept fixated from the start.
Then repeat the same calls with the 'b' key also toward that table.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by nox** [comment]
I've added tests in the update_counter_do function.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Thank you.

**Comment by zhird** [comment]
Merged to master.

**Comment by lpgauth** [comment]
amazing! :+1:

**Pull request closed without merging**
