### PR TITLE
Fix parsing of IPv6 addresses to limit leading zeros

### PR DESCRIPTION
**Pull request by nybek**
The current implementations of inet:parse_ipv6_address/1 and
inet:parse_ipv6strict_address/1 permit address strings which have an
unlimited number of leading zeros. Addresses such as:

    "0000000000000000000000000000000ffff::"
    "::00000000000000000000000000000000000000000000000000000000"
    "::0000000f435:1"

If we are using this facility to validate string representations of
IPv6 addresses, then we would end up validating addresses which are
non-conformant (with respect to RFC 4291 section 2.2) and potentially
dangerous.

This patch ensures that each segment of an IPv6 address has a maximum
of 4 hex digits.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
The patch is good - we want the correction, but I see that it can be better:

Can you instead rewrite hex/1 to take a second argument N to limit the number of hex digits already at the collection step, and then call it with N=4?  With your patch hex_to_int/1 calls length/1 on unknown input and with malicious input that can be expensive in CPU cycles.

/ Raimo Niskanen, Erlang/OTP

**Comment by nybek** [comment]
Nice catch! I followed the spirit of your instructions but left hex/1
intact and just modified hex/2 to take the N argument. I also reverted 
hex_to_int/1 to its original state. Hope that's okay!

**Comment by RaimoNiskanen** [comment]
That makes hex/1 less general than hex/2 would have been but minimizes the changes in the calling code, so why not. It is only used in this module. Looks good!

Since he input to hex_to_int/1 now is limited it should not double check the length so that is just fine.

**Comment by nybek** [comment]
On Thu, May 21, 2015 at 06:44:10AM -0700, RaimoNiskanen wrote:
> That makes hex/1 less general than hex/2 would have been but minimizes the changes in the calling code, so why not. It is only used in this module. Looks good!
> 
> Since he input to hex_to_int/1 now is limited it should not double check the length so that is just fine.

Sorry, I was trying to be conservative in what I changed. Happy to make the following edits if you'd like:

1. Change hex/1 to hex/2 as originally instructed.

2. Refactor hex_to_int/1 to remove the extra length() check (after strip0/1), turning it into:

     hex_to_int(Cs0) ->
         erlang:list_to_integer("0" ++ strip0(Cs), 16).

I expect you probably want this second change. Your call!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
1. Is not essential. Keep your version with less changes in the calling code. It is easier to read.
2. Yes please.  I am sorry I did not realize that I requested a new change since the length check was there before. I also think the strip0(Cs) call can be removed since list_to_integer/2 would not mind the zeros, what do you think?
  hex_to_int(Cs) -> erlang:list_to_integer("0"++Cs, 16).
I also do not understand why the "0" is prepended - that seems redundant since hex() should ensure 1..4 hex digits.
  hex_to_int(Cs) -> erlang:list_to_integer(Cs, 16).
Do you think that is a safe change?

**Comment by nybek** [comment]
Haha, good observations!

Your last version looks both safe and proper. I've pushed it.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
merged

**Pull request closed without merging**
