### PR TITLE
Fix SSL connection downgrade

### PR DESCRIPTION
**Pull request by vstavskyi**
ssl:close(Socket, {Pid, Timeout}) returned {handle_call,{'EXIT',{{badmatch,[<<21,3,3,0,48>>,<<..........
An error occurred at line: 1034 in ssl_connection.erl
`{BinAlert, ConnectionStates} = terminate_alert(Reason, Version, ConnectionStates0, Connection),`

### CODE REVIEW

**Comment by vstavskyi** [comment]
Next error {error,timeout}  occurred at line: 859
`{next_state, downgrade, State#state{terminated = true}, [{timeout, Timeout, downgrade}]};`
Second fix helps to reach at line: 791
`downgrade(internal, #alert{description = ?CLOSE_NOTIFY},`

**Comment by IngelaAndin** [comment]
Seems the downgrade test case is  a little to generous in its handling ok return values. We hade some problems with slow machines and it seems the test will accept timeout as success and all tests timeout!
I will enable your fix and see what happens in the test and we wil take it form there.

**Comment by vstavskyi** [comment]
There is as issue during connecting to Oracle database with sending a close_notify alert. 
This is the [project](https://github.com/erlangbureau/jamdb_oracle/blob/master/src/jamdb_oracle_conn.erl#L296).
Oracle close the underlying transport connection, if close_notify alert was sent.
Third fix helps to reach at line: 1039
`terminate(Reason, _StateName, #state{transport_cb = Transport, protocol_cb = Connection,`
So, during downgrade а close_notify alert is not mandatory for Oracle and maybe for many other servers.
We need options for ending the downgrade.

**Comment by IngelaAndin** [comment]
Maybe you want to use renegotiate? For downgrade to really work I think it needs to be agreed that it can be performed  check RFC 5246 section 7.2.1.  Closure Alerts.

**Comment by vstavskyi** [comment]
ssl:renegotiate sends only Encrypted Handshake Message, but Oracle awaits full Client-authenticated TLS handshake.

**Comment by vstavskyi** [comment]
Agreed. Module must just work without errors. And we must use patched module for Oracle requirement.

**Comment by IngelaAndin** [comment]
It could be possible to extend the close option to include some information not to send the close alert but to wait for the servers (because it does send it?!).  That could be used as a workaround.

**Comment by vstavskyi** [comment]
Fix #4. There is no Timeout checks in gen_tcp module. So, these checks can be removed in ssl module.

**Comment by IngelaAndin** [comment]
Thank you for alerting me that setopts and getopts for DTLS were not finished. I fixed it completely with test in #1485 

When it comes to your last fix, I do not really understand why weak input checks in one place would motivate to remove input checks in another place.

**Comment by IngelaAndin** [comment]
I think this PR has become some what outdated and changed focus from the original problem, could you please open a new PR if you think there are changes that are still relevant.

**Pull request closed without merging**
