### PR TITLE
Fix sys:get_status/1 noproc crash during release installation

### PR DESCRIPTION
**Pull request by RJ**
When release_handler_1:get_supervised_procs/0 does a recursive walk of
the supervision tree, it calls sys:get_status/1 on supervisors, to check
if they are suspended or running.

This fixes a race condition where a list of supervisor pids is gathered,
one of them (legitimately) exits before release_handler can examine it,
then sys:get_status/1 is called with a dead pid, causing an exit(noproc)

See: http://erlang.org/pipermail/erlang-questions/2015-August/085712.html

(To recreate this problem for testing, I added a timer:sleep into the
release_handler_1 code, and killed a supervisor during
get_supervised_procs being called).

### CODE REVIEW

**Comment by RJ** [comment]
ftr, i deployed this change and have successfully done upgrades with it.

am yet to hit the condition where it would have crashed, during normal upgrades.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Fix sys:get_status/1 noproc crash during release installation


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sirihansen** [comment]
Looks good. I did a minor fix to the text in the warning message, and added the PR to our nightly tests. Thanks!

**Comment by sirihansen** [comment]
Test ok for five nights. Including PR in OTP-18.3.

**Pull request closed without merging**
