### PR TITLE
Fix hipe bug in binary <<X/utf32>> construction

### PR DESCRIPTION
**Pull request by sverker**
This is a x86_64-only fix for hipe compiled code running binary constructions like

`<<X/utf32>>`

The **problem** is the generated code calls bif/primop `hipe_bs_validate_unicode` before it writes to the binary. But `hipe_bs_validate_unicode` may trigger GC in which case the binary data is written to the old deallocated heap and the constructed binary on the new heap will contain random bytes.

My **solution** is to introduce a new bif wrapper `nogc_bif_interface_1` for `hipe_bs_validate_unicode` that never triggers GC. So far I've only done it for x86_64.

To write test code that reliably **reproduces** the scenario where `hipe_bs_validate_unicode` will trigger GC is not trivial. Instead I did a commit where `hipe_bs_validate_unicode` always trigger GC. Remove the top revert-commit, (re)build the VM, compile the supplied module `t` as native, run `t:go()` and watch `<<X/utf32>>` return random bytes.

@kostis @mikpe 

**Is there a better way to fix this? Maybe change the generated native code.**

### CODE REVIEW

**Comment by margnus1** [comment]
It took me a while to convince myself that this actually works and fixes the problem. What an equally brilliant and awful hack.

As you've already surmised, the "better way" of fixing this is to change the native code generation. But that comes with the caveat that it does not solve the problem for already compiled code, so I'm not against applying this fix to `maint`, and then later, on `master`, reverting it and solving the problem at the source.

Here's a commit that demonstrates the way to fix native code generation that is the least intrusive and easiest to do: https://github.com/margnus1/otp/commit/a010bc5d69bfa1c05c8085ac67aeb1776c58b82e.

Here's the way of making tests for this kind of problems I decided to use for that fix: https://github.com/margnus1/otp/commit/b6ebce8970432b1abde8f3f0745f8b63da744d01. It is a validation pass that is run over the intermediary form to detect if a derived pointer is live over a call that can GC. Thus it does not require you to force a GC at runtime to detect these bugs. The only thing you'd need to add to make a test that would expose the bug that you are fixing in this PR, that will work once I get around to upstreaming the validation pass, is to add a test to the HiPE test suite that exercises `<<X/utf32>>`, and make sure that the RTL temporary that contains the offending pointer is properly marked as derived (called "gcunsafe" in the source). Most already are.

**Comment by mikpe** [comment]
I don't think `hipe_bs_validate_unicode` can _cause_ a GC: it only uses `P` to store `BADARG` in `freason` in case it detects an invalid parameter.  But if a GC was pending, then its wrapper will detect that and perform the GC, which of course breaks things here.

Changing the wrapper to one that does not check for GC is IMO the correct solution, but the wrapper should be called `nocons_primop_interface_1`.  So your solution is in the right direction.

Changing the compiler would also work, but would require more work.

**Comment by margnus1** [comment]
You are correct, but it is sort of an abuse of exception handling to use it for validation like this; the construction of the exception object, which is what allocates the heap fragment, is always unnecessary because the exception is always caught.

Also, the name `nocons_primop_interface_1` is just flat-out wrong. `hipe_bs_validate_unicode` _does_ cons. Otherwise the wrapper would never call the garbage collector. All the other `nocons_` wrappers do not copy `Htop` back from it's register to the PCB, so if implemented as it name suggests, wrapping `hipe_bs_validate_unicode`  with `nocons_primop_interface_1` would cause heap corruption whenever the validation fails, as it would overwrite something on the heap using the stale heap pointer from the PCB.

Another reason to dislike this solution is that it only fixes it for `x86_64`, and leaves it broken for 32-bit `x86` as well as all other architectures. Why work around the problem in five (and counting, as more backends are added; I know an `aarch64` backend has been under serious consideration for a while) places when it could be fixed in one?

So no, changing the compiler is *less work*.

If you are to go to the trouble of adding a new wrapper, why stop at a half-measure? The wrapper could just as well be `noproc_predicate_primop_interface_1` and not require the primop to allocate an exception object, but rather just return zero or nonzero. That would make this more of a use of exceptions and less of an abuse, improve performance, decrease code complexity in primops, be generalisable to other bif's that are used in this way, and even keep ABI so that existing code keeps working.

**Comment by sverker** [comment]
Thanks for your feedback.
I added a new commit with fix in generated code calling new primop `is_unicode`.

**Comment by mikpe** [comment]
LGTM, will need some cleanup of obsolete code in the VM though

**Comment by sverker** [comment]
I will do a cleanup on master and remove the old hipe_bs_validate_unicode.

**Pull request merged**
