### PR TITLE
Jinterface generic match and bind methods

### PR DESCRIPTION
**Pull request by x0id**
The proposed change facilitates implementing pattern matching and variable binding in the JInterface library. Particular implementations may vary, but proposed change provides low level interface base methods. Changes are backward compatible. Test cases added.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by x0id** [comment]
Closed, because need to cover matching list tail: [H|T] = term. Will open new one once done.

**Comment by x0id** [comment]
Fix made to cover cases when left-hand list tail is matching to right-hand nth-tail of longer list, for example: [1,2|T] = [1,2,3,4] -> T = [3,4], [a,b,c|T] = [a,b,c,d,e|f] -> T = [d,e|f] etc.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by vladdu** [comment]
This is ok. 

It is new functionality, the only modification of existing code is in OtpErlangMap and it is only internal.

Note that commit ab1cfe1 fixes a previous issue introduced in bb7fb3c3, that prevents the jinterface tests to compile.

**Comment by vladdu** [comment]
Hmm, I realized something: the change in OEMap, to use java.util.Maps, is only going to work on desktop applications. java.util is not available in the embedded Java versions. With the whole InternetOfThings stuff going on, I imagine that there will be embedded Java clients that want to talk to Erlang servers.

I think we should reimplement OEMap using arrays only, until we can figure out how to handle both cases in a nice way.

**Comment by vladdu** [comment]
Newer Java ME SDKs have the required Collections framework available, so we're good. If anyone had been trying to use older versions, they would already had issues and nobody complained, so I'd say it's safe to keep the same level of compatibility.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by vladdu** [comment]
Please squash the commits together to make code review easier. Thanks!

**Comment by x0id** [comment]
Squashed.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
@vladdu, any updates on the review here?

**Comment by vladdu** [comment]
Oh, sorry, I was sure that I had posted my answer. 

It looks ok to me.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
