### PR TITLE
compiler: replace size/1 by xxx_size/1

### PR DESCRIPTION
**Pull request by kikofernandez**
Relates to #6672

### CODE REVIEW

**Comment by michalmuskala** [comment]
Should this be against `master`, rather than `maint`? Otherwise looks like some sort of rebase/merge issue - there's a lot of irrelevant commits included. Similar in #6703 and #6702

**Comment by kikofernandez** [comment]
yes, I mess up :) 
Will fix it tomorrow, thanks!

**Comment by kikofernandez** [comment]
the same goes for other PRs similar to this one

**Comment by bjorng** [comment]
I've edited the pull request to change its base to `master`.

**Review by bjorng — APPROVED** [review]

**Pull request closed without merging**
