### PR TITLE
implement IPv6 multicast support

### PR DESCRIPTION
**Pull request by RoadRunnr**
Implement support for ipv6_join_group, ipv6_leave_group, ipv6_multicast_if,
multicast_ttl and multicast_loop UDP socket options for IPV6 sockets.

IPv6 multicast group membership socket options are suffcient different
from IPv4 to require an new socket option.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RoadRunnr** [comment]
Ping, are there some news about this PR ?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We are interested in the functionality, and we would like to have test  cases too. It seems that they are missing for ipv4 :(  So if we are lucky your ipv6 test can be run for ipv4 also.

**Comment by proxyles** [comment]
Reopen when you have added tests

**Pull request closed without merging**
