### PR TITLE
Improve error reporting for TLS distribution

### PR DESCRIPTION
**Pull request by legoscia**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Report bad options when accepting TLS distribution connections


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
This changes the semantics of how the process is terminated. I think the reason should be {shutdown, Reason} and not Reason to keep the semantics. The distribution code is a little special as it sort lives before Erlang applications and supervisor principals are properly supported, but I think it will make the intentions clearer if nothing else.

**Comment by legoscia** [comment]
That's a good point. I updated the patch to use `{shutdown, ...}` as exit reasons.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
