### PR TITLE
Decentralized counters for all ETS table types and an option to disable decentralized counters

### PR DESCRIPTION
**Pull request by kjellwinblad**
This pull request contains two commits. The first commit (ad2ce60) adds support for using decentralized counters to count the number of items and the memory consumption in the ETS table types that are implemented with hashing (`set`, `bag` and `duplicate_bag`). All tables with the `write_concurrency` option activated use decentralized counters by default after this commit has been applied. The second commit (efe06e4) in this pull request adds an ETS table option that can be used to turn off decentralized counters in tables. Such an option can be useful in applications that frequently call `ets:info(T)`, `ets:info(T,size)` or `ets:info(T,memory)` because such calls are substantially slower with decentralized counters compared to with centralized counters.

[This pull request has been experimentally evaluated][1] on a machine with 64 hardware threads and a machine with 8 hardware threads.  The results from the machine with 64 hardware threads indicate that decentralized counters give ETS tables a major scalability improvement in scenarios with many write operations (i.e., `insert/2` and `delete/2`) when many cores are being utilized. Furthermore, decentralized counters do not cause a major performance penalty in any of the scenarios that are included in the benchmarks.

[1]:  http://winsh.me/ets_catree_benchmark/decent_ctrs_hash.html

### CODE REVIEW

**Comment by max-au** [comment]
Thank you for this PR! We've hit the issue (ets:info got really slow for ordered_set, as if 10x regression), reproduced it with [erlperf](https://github.com/max-au/erlperf) and had to fall back for {write_concurrency, false}.

**Comment by kjellwinblad** [comment]
> Thank you for this PR! We've hit the issue (ets:info got really slow for ordered_set, as if 10x regression), reproduced it with [erlperf](https://github.com/max-au/erlperf) and had to fall back for {write_concurrency, false}.

Thanks for the feedback. The functions `ets:info/1`, `ets:info(T,size)` and `ets:info(T,memory)` are slow when decentralized counters are activated because they use the [thread progress functionality](https://github.com/erlang/otp/blob/d6285b0a347b9489ce939511ee9a979acd868f71/erts/emulator/internal_doc/ThreadProgress.md) to get atomic snapshots of the decentralized counters. We want to keep `ets:info(size)` and `ets:info(memory)` linearizable even when decentralized counters are used as we want to keep the same semantics as before.

Is it important that `ets:info(size)` is exact and atomic for you? If it is acceptable to get a good estimate of the table size, you may still be able to get the scalability benefit of decentralized counters by using the [counters API](http://webcache.googleusercontent.com/search?q=cache:XCxt15-G8MwJ:erlang.org/doc/man/counters.html+&cd=1&hl=en&ct=clnk&gl=se&client=ubuntu) to "manually" maintain the size of the table in a counter with the `write_concurrency` option enabled. This will, however, add extra overhead to all operations that remove and insert items. Such overhead could be avoided if we made it possible to get the approximate size of a table by calling e.g., `ets:info(approximate_size)`. Would that be useful?

**Comment by max-au** [comment]
As we found out, our use-case should be covered with a simple call to ets:whereis(), so slow ets:info(size) does not present an issue for us.

**Comment by kjellwinblad** [comment]
The benchmark results have been updated. 

The following changes have been made since the previous benchmark run:

1. @sverker has made the shrinking code more scalable and made the shrinking happen less eagerly  (3f4d0db4189d196abb2d1c769dc50411b52b08e6).
2. I have disabled shrinking when there are 100 or less buckets per lock and when decentralized counters are activated in the last commit of this pull request. This avoids frequent grows and shrinks due to bad estimates of the number of items in the table when the tables are small.

Results:

- [New results](http://winsh.me/ets_catree_benchmark/decent_ctrs_hash.html)
- [Old results](http://winsh.me/ets_catree_benchmark/hash_decent_old/decent_ctrs_hash.html)

**Pull request merged**
