### PR TITLE
Be suspicious of certificates without CRL distribution points

### PR DESCRIPTION
**Pull request by legoscia**
If a certificate doesn't contain a CRL Distribution Points extension, and the relevant CRL is not in the cache, and the `crl_check` option is _not_ set to `best_effort`, the revocation check should fail.

As far as I can tell, the algorithm described in [section 6.3 of RFC 5280](https://tools.ietf.org/html/rfc5280#section-6.3) would give the result "UNDETERMINED" if there are no defined distribution points and the CRL is not otherwise available. The documentation for the `best_effort` setting for `crl_check` says:

> if certificate revocation status can not be determined it will be accepted as valid.

which suggests that for the other settings, certificates should _not_ be accepted if the certificate revocation status could not be determined.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
The function crl_check_same_issuer already does this check, I think the way to fix it is to remove the cace clause e.i.

case dps_and_crls(OtpCert, Callback, CRLDbHandle, same_issuer) of
		[] ->
		    valid; %% No relevant CRL existed
		DpsAndCRls ->
		    crl_check_same_issuer(OtpCert, Check, DpsAndCRls, Options)		
	    end;

becomes 

crl_check_same_issuer(OtpCert, Check,  dps_and_crls(OtpCert, Callback, CRLDbHandle, same_issuer) , Options).

**Comment by legoscia** [comment]
That's a good point. I updated the patch.

**Comment by IngelaAndin** [comment]
Thank you I approved the patch to go to the daily test step.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
