### PR TITLE
Options for TLS distribution

### PR DESCRIPTION
**Pull request by legoscia**
This is the same pull request as #698, but with test cases added.

### CODE REVIEW

**Comment by fenollp** [comment]
@legoscia You know you can push commits to an already opened PR, right? You can even rebase a PR's commits.

**Comment by legoscia** [comment]
@fenollp Can I do that even if I didn't open the original PR?

**Comment by fenollp** [comment]
Ah. Sorry, I missed that!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by tombriden** [comment]
This is great, thanks for adding the tests :)

**Comment by rpgmaker** [comment]
Btw, The inet_dist_listen_min/inet_dist_listen_max kinda of work except that when using it with rabbitmq-server, it act as a blocking connection that is connected to the correct port but it allows user input on the command-line. But if the port is set to 0, it always return immediately after it connects but with random ports.

Thanks,

**Comment by IngelaAndin** [comment]
In the test case we think that you should set both min and max together to the same value if you
expect to get a specific port. We do not want a test case that depends on the current behaviour that we do note feel may be optimal, though the docs are quite vague. But this is a different issue.

**Comment by rpgmaker** [comment]
I was able to use the code using same value for both min and max and it works fine in the context of rabbitmq. I removed the logic that tries to connection to range of ports and stick with the logic that return the min value since that was what I was looking for in my scenario. I guess I will wait to see the test case that will be created for it.

Thanks,

**Comment by legoscia** [comment]
I changed the test to not rely on setting only the min port.

**Pull request merged**
