### PR TITLE
[ct_cover] Fix paths of incl_dirs in cover spec

### PR DESCRIPTION
**Pull request by studzien**
It seems like the commit 5a3c4668908254ee930c8db2e5cf9741945f9b2b also
broke the incl_dirs option and friends when given as relative paths.
When a cover spec contains a relative path it is looked-up in the
directory with the test results, not in the .cover file directory.

### CODE REVIEW

**Comment by sirihansen** [comment]
The patch looks good, but could you please add a test using absolute path for incl_dirs also - just to make sure it is not broken? Unfortunately this has not been tested before at all. Adding a test with excl_dirs would also be much appreciated...

**Comment by studzien** [comment]
Sure, I will do my best to do this this week.
Thanks for reviewing the patch.

**Comment by studzien** [comment]
Sorry for the delay.
I've added couple of tests. Please let me know if those are sufficient.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
