### PR TITLE
Fix `ct_property_test` result handling for failing properties

### PR DESCRIPTION
**Pull request by Maria-12648430**
While I have no clue what the `{set, {var, _}, {call, M, F, Args}}` part is all about (@HansN, maybe you can shed some light on this, `git blame` says this was done by you, albeit ~9 years ago :sweat_smile:), this fails with a `try_clause` exception if a property fails on input that is a non-empty list, like eg `[1, 2, 3]`. `Tool:counterexample()` will then return `[[1, 2, 3]]`, for which `lists:last(hd([[1, 2, 3]]))` will return `3`, for which there is no matching clause in the `try`.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
@Maria-12648430 Hans N has retired, but my team will look into it!

**Comment by IngelaAndin** [comment]
Well I guess this can be what is returned, or possibly was returned by one of the tools quickcheck, proper or triq when calling the
function counterexample, at least for some common case. And this was an attempt to pretty print the error.  Anyway this feels like an assumption we might not want to make about the counterexample. Maybe it makes more sense just failing with what ever counterexample returns !? Thoughts @u3s, @jhogberg, @Maria-12648430 ?

**Comment by Maria-12648430** [comment]
Fine with me. But right now it fails with whatever the last run of the property returned (unless `true`), usually `false`. Ie, not the counterexample.

**Comment by IngelaAndin** [comment]
Interesting, what quickcheck tool are you running? As far as I can understand from the code the result should be
coming from the tools callback function called counterexample (where tool can be quickcheck, proper, triq)

**Comment by IngelaAndin** [comment]
Oh, I see now it returns the result of quickcheck run unless the counterexample is on a certain form which it makes into a error-string.  So it would return {fail, false} as you say most of the time I guess. As if `Other` is true we have not failed and will match first clause and return only true.  If it fails I would of course be interested in the counter example. I guess we need to look how this return value is used. Last time I wrote property tests I do not remember missing this information maybe it is conveyed somewhere else.

**Comment by IngelaAndin** [comment]
This is interesting, in ssl application we will assert that ct_property_test:quickcheck returns true, that is the "common test" test case running the property will crash failing the "common test" testcase when the property test fails. But mostly the return value seems to be ignored, which I think will not work out with current implementation.

**Comment by Maria-12648430** [comment]
> what quickcheck tool are you running?

Usually PropEr. For research on this issue, I also tried looking into quickcheck mini, but I can only get that compiled, and so can not look at the source code. I never tried Triq.

> Oh, I see now it returns the result of quickcheck run unless the counterexample is on a certain form which it makes into a error-string. So it would return {fail, false} as you say most of the time I guess. As if `Other` is true we have not failed and will match first clause and return only true.

That is correct :slightly_smiling_face:

> If it fails I would of course be interested in the counter example. I guess we need to look how this return value is used. Last time I wrote property tests I do not remember missing this information maybe it is conveyed somewhere else.

It can be found in the ct logs.

> I guess we need to look how this return value is used.

This is returned as result of the wrapping common test, and handled somewhere in the `common_test` framework. This however points out an error/omission in the documentation of `common_test`/`ct_suite`. In the [documentation for `Module:Testcase/1`](https://www.erlang.org/doc/man/ct_suite#Module:Testcase-1) (and also in ["Writing Test Suites - 5.5 Test Cases"](https://www.erlang.org/doc/apps/common_test/write_test_chapter#test_cases)), it does not mention that returning a `{fail, ...}` tuple will make the test case fail. On the contrary, it says that _any_ return value except `{skip, ...}` will cause the test to be considered successful, with certain other tuples ( `{comment, ...}`, `{save_config, ...}`, ...) considered specially.

> This is interesting, in ssl application we will assert that ct_property_test:quickcheck returns true, that is the "common test" test case running the property will crash failing the "common test" testcase when the property test fails. But mostly the return value seems to be ignored, which I think will not work out with current implementation.

Hm, I don't know what you mean :sweat_smile: Can you point me to the test(s) you are talking about so I can take a look for better understanding?

**Comment by IngelaAndin** [comment]
So in ssl_eqc_SUITE.erl  we will do:

```
tls_handshake_encoding(Config) when is_list(Config) ->
    %% manual test:  proper:quickcheck(ssl_eqc_handshake:prop_tls_hs_encode_decode()).
    true =  ct_property_test:quickcheck(ssl_eqc_handshake:prop_tls_hs_encode_decode(),
                                        Config).

```
In string_property_SUITE in stdlilb (for instance)

```
recompose(Config) ->
    ct_property_test:quickcheck(
      uri_string_recompose:prop_recompose(),
      Config).

```

So common test testcases fail if the process running the test crashes either due to runtime failures such as "badmatch" or ct:fail is called exiting the test case process in a non "normal"  way. If the test case process finishes with a normal exit the test has succeeded.

**Comment by Maria-12648430** [comment]
Hm, I'm really not sure that I understand the problem... :sweat_smile: I have an idea that what you are thinking is related to the undocumented handling of returning `{fail, ...}` from a common test case, though.

The return value of `ct_property_test:quickcheck` is either `true` or `{fail, ...}`.
* `true` occurs when the property testing tools' check function returned `true`, ie that the property held by returning `true` for all the generated data passed to it. `true` is not one of the values handled specially by the common test framework, so the common test case succeeds.
* `{fail, ...}` occurs if the property testing tools' check method returned something else than `true`, ie that the property failed by returning something else than `true` for any of the generated data passed to it. `{fail, ...}` however _is_ handled specially (undocumented, in fact contradicting the documentation). If such a tuple is returned by a test case it means the test case has failed.

**Comment by IngelaAndin** [comment]
@Maria-12648430 you could be right about that, common test is not my area of expertise! I found this very surprising, but that could mean our test will work as expected that is nice.

**Comment by Maria-12648430** [comment]
Ok, with that out of the way (also see #7869), what should we do about this obscure special handling of some return of `Tool:counterexample` that we talked about in https://github.com/erlang/otp/pull/7824#issuecomment-1809781519? @u3s and @jhogberg haven't voiced any opinion yet, but I am for dropping it entirely.

**Comment by Maria-12648430** [comment]
Last commit removes all of the ominous special handling.

**Comment by IngelaAndin** [comment]
Thanks for the PR

**Pull request merged**
