### PR TITLE
Inherit options in gen_tcp:accept/1 in inet_drv directly

### PR DESCRIPTION
**Pull request by nox**
I can't test whether 'priority' and 'tos' are properly inherited here as OS X doesn't support these options.

Cc @reedr.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Under the current circumstances e.i. the patch breaking existing functionality,
the test case needs some work. The test sets active true, which is default and hence not a good test. 
And no figures backing up that the optimization is worth while. And looking at our current backlog this has a hard time making it to the top under these circumstance.

**Comment by nox** [comment]
Not like I *asked* how it could be fixed and improved… As for whether it's worth it or not, personally I find it not straightforward at all that any accept call would cause an unnecessary roundtrip for a handful of optional settings.

**Comment by essen** [comment]
I am interested in this patch now that I understand its purpose. Any chance you can give the man his feedback? :-)

**Comment by IngelaAndin** [comment]
If that question had been easy to answer, we would happily have done so. But nobody knows without spending a lot of time to investigating it. I am not saying that patch is not interesting, just that it currently is not interesting enough for us to spend a lot of time on. So for it to happen somebody else
will need to investigate and make all test pass. Also as I said the test case needs improving  by setting a non default value.

**Comment by proxyles** [comment]
Closed until someone get back to this

**Pull request closed without merging**
