### PR TITLE
Fix FSF mail address

### PR DESCRIPTION
**Pull request by matwey**

### CODE REVIEW

**Comment by okeuday** [comment]
It might be good to add a note somewhere too, to make it clear to people that edoc/eunit/syntax_tools are under the LGPL instead of the Apache License version 2.0, since that is a detail many probably overlook, which is why the address wasn't updated quicker (they have been at this new address for more than 5 years).

**Comment by tuncer** [comment]
Actually: #788.

**Comment by matwey** [comment]
I have not seen #788. I would be fine with any solution which drop out old FSF address, because rpmlint constantly complains about it.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
