### PR TITLE
Optimise ext table dumping

### PR DESCRIPTION
**Pull request by dszoboszlay**
When Mnesia is dumping transactions logs with operations on ext tables, it first groups operations in a commit by the ext storage engine. The current implementation folds over the list with `orddict:append/3`, which is an `O(n^2)` algorithm. This is especially problematic because there are typically only a handful of ext storage engines used by any database, while a transaction can contain an arbitrary large number of operations. So the `orddict` built this way will typically have very few keys with very long list of values stored under them.

It is faster to fold over the list in reverse order and prepend each operation to the list of already collected operations. A further optimisation is using a map instead of an orddict. And finally, since external storage engines with `disc_only_copies` semantics only need to be dumped at startup, we shall filter out operations on those right when building the map for all other dump types.

Together these optimisations yield a massive speed up when dumping large commits. In our scenario, we have 1 external storage engine with `disc_only_copies` semantics, and some transactions may contain ~1-2 million updates to these tables. Dumping these transactions takes hours. I made some measurements on my laptop to illustrate the effect (only considering the time it takes to group and iterate over the transactions, not the time to dump them to disc):

`InitBy` | `disc_copies` engines | `disc_only_copes` engines | Original | Optimised |
| --- | --- | --- | ---: | ---: |
| `user` | 1 with 30k ops | 1 with 30k ops | 6,605 ms | 12 ms |
| `user` | 0 | 1 with 30k ops | 2,182 ms | 2 ms |
| `user` | 0 | 1 with 10k ops | 159 ms | <1 ms |
| `user` | 0 | 1 with 1000 ops | 1,683 us | 47 us |
| `user` | 0 | 1 with 100 ops | 24 us | 19 us |
| `user` | 0 | 1 with 10 ops | 2 us | 1 us |
| `startup` | 1 with 30k ops | 1 with 30k ops | 5,337 ms | 18 ms |
| `startup` | 0 | 1 with 30k ops | 1,821 ms | 15 ms |
| `startup` | 0 | 1 with 10k ops | 161 ms | 2 ms |
| `startup` | 0 | 1 with 1000 ops | 2,172 us | 205 us |
| `startup` | 0 | 1 with 100 ops | 43 us | 18 us |
| `startup` | 0 | 1 with 10 ops | 2 us | 4 us |

My benchmarking methodology wasn't very advanced (doing a single run only, no consideration for gc etc.), but it looks obvious that the optimisations are useful, except for the smallest test scenarios where the two methods performed within the margin of error.

### CODE REVIEW

**Comment by dszoboszlay** [comment]
I was thinking a bit more about the problem, and now I believe the whole grouping by external engine bit is unnecessary. This would allow us to further simplify the code as seen in 48432cf.

However, that solution would change the order in which `insert_op/5` calls are made if there are more than one external engines involved in the commit (the `insert_op/5` calls from different engines would be interleaved, but each engine would receive its respective `insert_op/5` calls in the original order). I don't see any problems with this change, however I'm not confident enough with my understanding of Mnesia internals to definitely say it's correct.

So please consider carefully reviewing 48432cf as well!

**Comment by richcarl** [comment]
Well, Daniel sits at the table behind me, and this is a real thing that bit us when we had some unusually large transactions, so we just want this merged upstream. Paging @mikpe as well if he wants to weigh in.

**Comment by dszoboszlay** [comment]
I'm quite confident the change as seen in this PR is correct, because it does exactly the same thing as the original code, only in an optimised way.

But I would really like to hear your opinion on whether the alternative I proposed in 31542e4 could work? Is there any inherent reason for dispatching ops grouped by backend engine or is it only because that's how Mnesia does it with native `disc_copies` and `disc_only_copies` tables (where the ops are already grouped, so there's no performance penalty for this strategy)?

**Comment by uwiger** [comment]
I can't come up with a reason why the approach in [31542e4](https://github.com/erlang/otp/commit/31542e40d6ddf2be61979218e38dfa9f2829bd05) shouldn't work.

The performance gain is impressive, so the change seems like a good one.

**Comment by dszoboszlay** [comment]
I opened #2102 from 31542e4, if you think that patch is correct, it should be a better option than 28c4ec1 (this PR).

**Comment by mikpe** [comment]
Answering @richcarl 's page, my only comment is that we have been bitten badly by the O(N^2) behaviour of the current code on several occasions, so eliminating that is a top priority.

**Comment by dgud** [comment]
I can't see a problem with #2102 either as long as the order per engine is preserved it should be ok.

**Comment by dgud** [comment]
Merged #2102

**Pull request closed without merging**
