### PR TITLE
stdlib: Do not progress report dynamically started supervisors

### LINKED ISSUE #8715: tls_dyn_connection_sup progress logging includes megabytes of certificate data
**Describe the bug**
When progress logging is enabled and TLS is used, there is a supervisor `tls_dyn_connection_sup` started that logs all arguments used to started it.

When passing a custom certificate list to TLS start options, these are included as-is in the `cacerts` option to this supervisor which results in megabytes and tens of thousands of lines of logs every time this process is started (often resulting in making it impossible to see any lines before this in the terminal since most terminals have a default line limit well below this).

**To Reproduce**
Start an SSL connection with options like `[{cacerts, public_key:cacerts_get()}]` (or use e.g. [tls_certificate_check](https://github.com/g-andrade/tls_certificate_check)).

**Expected behavior**
Logs are useful and readable.

**Affected versions**
27.0.1 (and earlier)

**Additional context**

Example:

```erl
2024-08-13T09:33:27.614089+02:00 info:
    supervisor: {<0.1523.0>,tls_dyn_connection_sup}
    started: [{pid,<0.1525.0>},
              {id,receiver},
              {mfargs,
                  {ssl_gen_statem,start_link,
                      [client,<0.1524.0>,"idp.kivra.net",443,#Port<0.71>,
                       {#{psk_identity => undefined,log_level => notice,
                          eccs =>
                              {elliptic_curves,
                                  [{1,3,101,110},
                                   {1,3,101,111},
                                   {1,3,132,0,35},
                                   {1,3,36,3,3,2,8,1,1,13},
                                   {1,3,132,0,34},
                                   {1,3,36,3,3,2,8,1,1,11},
                                   {1,2,840,10045,3,1,7},
                                   {1,3,36,3,3,2,8,1,1,7}]},
                          verify_fun =>
                              {fun ssl_verify_hostname:verify_fun/3,
                               [{check_hostname,"idp.kivra.net"}]},
                          verify => verify_peer,secure_renegotiate => true,
                          early_data => undefined,protocol => tls,
                          supported_groups =>
                              {supported_groups,
                                  [x25519,x448,secp521r1,secp384r1,secp256r1,
                                   brainpoolP512r1tls13,brainpoolP384r1tls13,
                                   brainpoolP256r1tls13]},
                          fallback => false,depth => 100,
                          use_ticket => undefined,crl_check => false,
                          srp_identity => undefined,
                          alpn_advertised_protocols => undefined,
                          signature_algs_cert =>
                              [default,eddsa_ed25519,eddsa_ed448,
                               ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,
                               ecdsa_secp256r1_sha256,
                               ecdsa_brainpoolP512r1tls13_sha512,
                               ecdsa_brainpoolP384r1tls13_sha384,
                               ecdsa_brainpoolP256r1tls13_sha256,
                               rsa_pss_pss_sha512,rsa_pss_pss_sha384,
                               rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
                               rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,
                               rsa_pkcs1_sha512,rsa_pkcs1_sha384,
                               rsa_pkcs1_sha256,
                               {sha512,ecdsa},
                               {sha384,ecdsa},
                               {sha256,ecdsa},
                               rsa_pkcs1_sha1],
                          signature_algs =>
                              [eddsa_ed25519,eddsa_ed448,
                               ecdsa_secp521r1_sha512,ecdsa_secp384r1_sha384,
                               ecdsa_secp256r1_sha256,
                               ecdsa_brainpoolP512r1tls13_sha512,
                               ecdsa_brainpoolP384r1tls13_sha384,
                               ecdsa_brainpoolP256r1tls13_sha256,
                               rsa_pss_pss_sha512,rsa_pss_pss_sha384,
                               rsa_pss_pss_sha256,rsa_pss_rsae_sha512,
                               rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,
                               rsa_pkcs1_sha512,rsa_pkcs1_sha384,
                               rsa_pkcs1_sha256,
                               {sha512,ecdsa},
                               {sha384,ecdsa},
                               {sha256,ecdsa}],
                          cert_policy_opts => [],certs_keys => [],
                          handshake => full,
                          versions => [{3,4},{3,3}],
                          key_update_at => 388736063997,
                          crl_cache => {ssl_crl_cache,{internal,[]}},
                          reuse_sessions => true,max_handshake_size => 131072,
                          max_fragment_length => undefined,
                          renegotiate_at => 268435456,
                          customize_hostname_check =>
                              [{match_fun,#Fun<public_key.6.75820660>}],
                          cacerts =>
                              [<<48,130,5,100,48,130,3,76,160,3,2,1,2,2,16,83,
                                 213,207,230,25,147,11,251,43,5,18,216,194,42,
                                 162,164,48,13,6,9,42,134,72,134,247,13,1,1,12,
                                 5,0,48,76,49,46,48,44,6,3,85,4,3,12,37,65,116,
                                 111,115,32,84,114,117,115,116,101,100,82,111,
                                 111,116,32,82,111,111,116,32,67,65,32,82,83,
                                 65,32,84,76,83,32,50,48,50,49,49,13,48,11,6,3,
                                 85,4,10,12,4,65,116,111,115,49,11,48,9,6,3,85,
                                 4,6,19,2,68,69,48,30,23,13,50,49,48,52,50,50,
                                 48,57,50,49,49,48,90,23,13,52,49,48,52,49,55,
                                 48,57,50,49,48,57,90,48,76,49,46,48,44,6,3,85,
                                 4,3,12,37,65,116,111,115,32,84,114,117,115,
                                 116,101,100,82,111,111,116,32,82,111,111,116,
                                 32,67,65,32,82,83,65,32,84,76,83,32,50,48,50,
                                 49,49,13,48,11,6,3,85,4,10,12,4,65,116,111,
                                 115,49,11,48,9,6,3,85,4,6,19,2,68,69,48,130,2,
                                 34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,
                               ...
                        % 11 000 (!) more lines
```

### PR DESCRIPTION
**Pull request by IngelaAndin**
Closes #8715

### CODE REVIEW

**Comment by okeuday** [comment]
@IngelaAndin It is already possible to disable select supervisors using logger configuration with code like https://github.com/CloudI/CloudI/blob/9c4233246c5214cdf75b1f08d6d021fdea8ffb2a/src/lib/cloudi_core/src/cloudi_logger_kernel.erl#L42-L85
and configuration like https://github.com/CloudI/CloudI/blob/9c4233246c5214cdf75b1f08d6d021fdea8ffb2a/src/rel/files/vm.config.in#L25-L28 .

Preventing output from all dynamically started supervisors in a way that configuration is unable to disable, seems like a bad direction for people just trying to figure out what is happening in their system.  The default likely needs to allow dynamically started supervisors by default for consistency with past usage, to provide the least surprise for users.

Making it easier to filter the logger output is another approach, but being able to selectively disable processes reporting could likely make disabling progress report data simpler.  A configuration approach, e.g., in the `init/0` return value or a `supervisor:start_link/4` `Options` list value, could make the situation simpler.

**Comment by IngelaAndin** [comment]
@okeuday Yes I am fully aware that you can disable them, and this is what we told people several times when they reported it.  However the reports keep coming  and it is quite different to get the progress reports just for application start up and for each connection that happens frequently all the time. And this feels like a bad and not intended default behavior.
If progress reports had not been at info level from legacy I think we would have made them debug level reports. Changing that for all progress reports now is very backwards incompatible and probably would create complaints. However, I think you have a point and I changed the implementation to make only the dynamically started supervisor reports being on debug-level.

**Comment by okeuday** [comment]
@IngelaAndin Having dynamic supervisors more visible might not be a bad thing though, when considering all possible use.  Erlang source code benefits from having immutable data (in a way described at https://github.com/okeuday/varpool#readme ) and static supervision hierarchies should have less errors when compared to dynamically started supervisors.  From that perspective, it seems bad to disable or reduce logging output regarding dynamically started supervisors.  If the setting can be set selectively just when dynamically started supervisors happen to be annoying (and are considered unlikely to be a future problem), that should be best for everyone's use.

**Comment by IngelaAndin** [comment]
@okeuday The point is they are always annoying unless you are debugging and then you can turn on debug level logging.
For legacy reasons we will not do it for all progress reports, as it is less annoying for the statically started ones and might be expected by users due to legacy. Dynamically start ones I believe are less usual, and when they are used they will typically be used in dynamic contexts such as connections that goes up and down and spamming logs. Such supervisor will not be restarted automatically if the application is restarted and hence are a different kind of supervisor and no I do not think errors are more common in these supervisors
that statically started ones.  The errors in supervisors typically happens during development and default logging should not
focus on development but rather on deployment.

**Comment by eproxus** [comment]
This is already merged but I just wanted to chip in with my experience:

One could of course filter out the reports or part of the reports but it is neither trivial (as can be seen by the amount of configuration and code needed in the example above) nor enabled by default. I struggled many hours trying to solve this in various ways but could never figure out a log filter that stripped the binary certificates from the log output.

I prefer this solution because it somehow follows the principle of least surprise for most users (in my opinion). Now the opposite becomes true that one can get to these reports with extra configuration or code if it is really needed.

@okeuday I'll probably try to steal your filtering for our test runs where we have debug logging enabled (and which produce megabytes of logs each runs for just the certificates).

**Pull request merged**
