### PR TITLE
kernel: fix inet_backend option in connect with sockaddr

### PR DESCRIPTION
**Pull request by RoadRunnr**

### CODE REVIEW

**Comment by RoadRunnr** [comment]
The problem exists since at least OTP-24.3 (but might older).

**Review by ebengt — APPROVED** [review]
Very good find.

**Review by bmk — APPROVED** [review]

**Comment by bmk** [comment]
I would have liked this to be based on 24.3.4, to make it possible to make both 24 and 25 patches.
But I am currently unsure exactly how we (Erlang/OTP) handle this. I will check.

/BMK

**Comment by bmk** [comment]
Never mind. I will take care of the 24 and 25 patches.

**Comment by bmk** [comment]
Prepared for OTP 24 and 25 patches.

**Comment by IngelaAndin** [comment]
Solved in OTP-25.2.1  and OTP 24.3.4.7

**Pull request closed without merging**
