### PR TITLE
Sni with connect

### PR DESCRIPTION
**Pull request by qrilka**
Some websites require SNI extension to be filled (or they could also present multiple certificates on the same IP/port).
E.g. https://www.sagepub.com/ and https://www.bose.com/ don't work with HTTPC when requested with proxy.
As for the tests for this feature - it's not quite clear how to implement them with the current proxy suite setup. [SSLStrictSNIVHostCheck](http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslstrictsnivhostcheck) could be used but it's not a separate test and rather test setup configuration...
The code is based on https://github.com/erlang/otp/pull/800

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: inets: SNI should be passed with HTTPS requests through CONNECT


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Fetching pull requests from github failed:

    Host key verification failed.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.



----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I agree we want server_name indication to be sent. I am a little concerned with it being hard-coded.
The user may specify it and then it would be specified twice in the options list. Also currently it should be the DNS-name and I think it might end up as ip-address string in some cases.

**Comment by qrilka** [comment]
I have thought about it appearing twice but does it really cause a problem?
And as for IP - could you give some scenario when could that happen and cause a problem?

**Comment by IngelaAndin** [comment]
If the user specifies the IP-address in the URI instead of the hostname, probably not the common case but it is valid to do so.  As currently the server name indication is specified to be a DNS-name  there can potentially be a problem if its something else.

If an option is defined twice as the same value in the options list this will probably work as intended,
but conceptually I think this is not clean.  If the user has specified the option that is the value that should be used, if the user has not specified it you can set a default value.

**Comment by qrilka** [comment]
Thanks for you reply I will look into these questions.

**Comment by IngelaAndin** [comment]
ping

**Comment by qrilka** [comment]
sorry, was a bit distracted by other tasks - will look into this PR this week

**Comment by qrilka** [comment]
PR updated

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
Merged to maint.

**Pull request closed without merging**
