### PR TITLE
Do not unload modules during stop

### LINKED ISSUE #5031: init:stop() is slow to exit due to unloading modules
**Describe the bug**
Currently init:stop() unloads all modules before exiting and this can take a really long time on some platforms. For example, on a Raspberry Pi Zero unloading modules can take nearly 2 minutes even though loading all of them in took 10-20 seconds. 

This [mailing list thread](https://erlang.org/pipermail/erlang-questions/2021-July/101209.html) contains more information.

**To Reproduce**
I would imagine that init:stop() is slow on all platforms, but just not as obvious as it is on a Raspberry Pi Zero.

**Expected behavior**
init:stop() exits the VM in a couple seconds on a RPi Zero. Responses to the mailing list thread suggest removing the code that unloads modules, and based on what I've seen, that would fix the issue.

**Affected versions**
I only tested OTP 24.0.2.

### PR DESCRIPTION
**Pull request by josevalim**
Closes #5031.

I did not update the bootstrap code under the assumption you likely
don't want external contributors to change it, regardless of how
trustworthy they are. :)

### CODE REVIEW

**Comment by fhunleth** [comment]
I just confirmed that this patch reduces init:stop() from around 2 minutes to just under 2 seconds for the Raspberry Pi Zero in #5031 (see mailing list thread).

**Review by bjorng — CHANGES_REQUESTED** [review]
Any reason that this PR shouldn't be based on maint? I think that this change can be considered a bug fix and that it therefore should be included in OTP 24.1.

**Comment by josevalim** [comment]
Applied changes and rebased to maint.

**Review by bjorng — APPROVED** [review]

**Comment by bjorng** [comment]
Thanks! Added to our daily builds.

**Comment by bjorng** [comment]
Thanks for your pull request.

**Pull request merged**
