### PR TITLE
Use application:ensure_all_started/2 instead of hard-coding deps

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Use application:ensure_all_started/2 instead of hard-coding dependencies


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Use application:ensure_all_started/2 instead of hard-coding deps


----------------

I am a script, I am not human 

----------------

**Comment by HansN** [comment]
Added to nightly tests.

**Comment by HansN** [comment]
Graduated. Thanks!

**Comment by RaimoNiskanen** [comment]
I had to force the 'maint' branch since HansN accidentally merged in GitHub, which makes 'maint' deviate from our "true" branch 'maint'.  Sorry about that!

**Pull request merged**
