### PR TITLE
Include documentation of cerl and cerl_trees

### PR DESCRIPTION
**Pull request by nox**
More people are using Core Erlang now, these two utility modules should be documented.

### CODE REVIEW

**Comment by bjorng** [comment]
There is one huge problem with this patch, namely that a beginner that want to look at the documentation for the compiler will see the documentation for cerl and cerl_trees listed before the documentation for the compile module because module names are sorted in alphabetical order.

If you can find a way to put the links to the cerl documentation where innocent users will not stumble upon them, but advanced developers can still find them, we will accept the patch.

**Comment by nox** [comment]
I'm not sure how that is different from other sections of the documentation, like in "Object Request Broker & IDL". The only solution I see to that problem is making a user guide for the compiler.

**Comment by nox** [comment]
Reference manuals are always expected to be in alphabetical order.

**Comment by nox** [comment]
We can add a note at the beginning of cerl and cerl_trees' documentation stating that they are for advanced users though.

**Comment by bjorng** [comment]
Since the number of users that are interested in the cerl modules are probably very few, I don't want to cause *any* confusion for ordinary users. So I definitely don't want the cerl modules appearing among in the left column of the reference manual.

What would make most sense would be to have a link to "Internal Documentation", but we don't have that concept for any other application. I don't know how hard it would be to add it.

The next best thing would be to add a User's Guide. The User's Guide for erts and stdlib contains some pretty advanced reference material, so it is not without precedent.

**Comment by nox** [comment]
I don't see what can be confusing about having a big red note at the top of both modules stating they are probably not what the user is looking for.

**Comment by bjorng** [comment]
We have decided that we will include this pull request if we can change make the order of the modules in the documentation be: compile, cerl, cerl_trees.

Do you accept this change to your pull request? Or should we close it?

**Comment by nox** [comment]
OH: 'Hmm. The release notes for "compiler 6.0" says "The cerl and cerl_trees modules are now documented", but I don't see the docs here...'

**Comment by bjorng** [comment]
The release note was included accidentally.

**Comment by nox** [comment]
It's a bit tiring to be asked on IRC about cerl functions all the time, when its documentation exists and could be included in the hosted documentation. Just saying.

**Comment by fenollp** [comment]
This feels like a joke. Surely this was closed too early?
There is no documentation problem that cannot be solved with more documentation.

How about adding 2 lines at the top of the cerl XMLs that say something along the lines of
> `cerl_trees` is about Core Erlang, you may be looking for *LINK* instead.

Core-handling modules just have to be documented. [There's already a bunch of BEAM languages](https://github.com/llaisdy/beam_languages).
I thought that it would be encouraged to target Core Erlang.
I mean, one cool thing from there could then be used over here. The potential of using this common form is very interesting isn't it?

Can you consider reopening this?

**Comment by bjorng** [comment]
We don't want the `cerl` and `cerl_trees` modules to be listed before the `compile` module. Breaking the rule about alphabetic order in this case is fine.

**Comment by nox** [comment]
This has no precedent in any other application. The all important `erlang` module is in the nondescript application `erts`, preceded by `erl_prim_loader`. Same in `kernel`, where there are a bunch of modules real users never use, before `gen_udp` and `gen_tcp`. I could go on and find many other examples.

There is actual documentation for a module that is actually used by users, but no, let's not include it because "alphabetic order"!!1!

**Comment by DeadZen** [comment]
I'm commenting on this, cause I read it over a few times and I still don't get why we're opting out of documenting this?? Surely we can solve the visual problem and the knowledge asset problem simultaneously, right?

**Comment by tsloughter** [comment]
If an "innocent user" who can't figure out what is going on if these 2 are listed along side `compile` is delving into the Compiler Reference Manual then you've already lost... This makes no sense to not include.

**Comment by nox** [comment]
Yearly reminder that this is long overdue.

**Comment by nox** [comment]
Hey, psst, it's 2019 now. Here is another yearly reminder.

**Comment by garazdawi** [comment]
If someone wants to help me finish https://github.com/garazdawi/otp/tree/lukas/erl_docgen/add-internal-docs they are more than welcome.

**Comment by nox** [comment]
This is the wrong answer. There is nothing internal about those two modules, they are depended upon by third party projects and breaking changes would be unacceptable, making them not internal APIs.

I would be sympathetic to your alphabetical order argument if the kernel app had any other order and if its erlang module entry was more accessible. It is not the case. Cf. an earlier comment I wrote. Just merge the damn PR.

**Comment by nox** [comment]
The modules `cerl` and `cerl_trees` are *definitely* not internal APIs, the [Compiler Release Notes](http://erlang.org/doc/apps/compiler/notes.html) literally lists changes made to those modules.

**Pull request closed without merging**
