### PR TITLE
Map comprehensions

### PR DESCRIPTION
**Pull request by seriyps**
This is the implementation of map comprehensions, as described in the original maps proposal [EEP-43](https://www.erlang.org/erlang-enhancement-proposals/eep-0043.html).

Implementation is a joint effort of @cfclavijo, @pablocostass and @seriyps and it was done during the one day Erlang hackaton at @klarna.

The syntax we implemented is the one proposed in EEP-43:

```erlang
#{V => K || K := V <- MapExpr}
```

However we already got a feedback that it might make sense to introduce some other type of arrow for them, eg `<~`.

The way it's implemented is that we convert map generator syntax `K := V <- MapExpr` to list generator `{K, V} <- maps:to_list(MapExpr)`, and map comprehension `#{K => V || ...}` to list comprehension `maps:from_list([{K, V} || ..])`, which is definitely not the most efficient way it can be implemented, but it allowed us to reuse existing list comprehension code. Of course, implementation can be improved later without the semantics being affected.

Map comprehensions and generators can be freely combined with binary and list comprehensions/generators and filter expressions:

```erlang
#{K => V || K := V <- #{a => 1, 2 => 3}, is_integer(K)}.

#{K => K * 2 || K <- [1, 2, 3]}.
[K + V || K := V <- #{1 => 2, 3 => 4}].

#{K => V || <<K, V>> <= <<1, 2, 3, 4>>}.
<< <<K, V>> || K := V <- #{1 => 2, 3 => 4} >>.
```

Key and value in comprehension can be arbitrary expressions:

```erlang
#{handle_key(K) =>
    begin
        self() ! {K, V},
        {ok, V1} = handle_value(V),
        V1
   end || K := V <- MapExpr}
```

Also key and value in generators can be arbitrary patterns:

```erlang
Map = #{
  {a, "hello world"} => <<1, 2, 3>>,
  {b, "bye"} => nope
},
#{K => V || {a, "hello" ++ _} := <<1, _/binary>> <-  Map}.
```

Implementation is done in both the compiler and in the interpreter (so, syntax can be used in both Erlang modules and in Erlang shell).

Support was added to AST pretty-printer `erl_pp`, but we skipped `syntax_tools` for now.

Again, all the work have been done in just a one day and barely changed since then, so, some corners were cut.
Any feedback is appreciated!

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Very nice for a one day hackathon! Including tests, documentation, abstract syntax and all. :cake:

I imagine some syntax_tools working with abstract syntax need to be updated.

I don't think another arrow is needed, since there is no ambiguity. To compare with list and bitstring generators, there would be an ambiguity if they would use the same arrow, as in `<<X>> <- Variable` where Variable can be a list of binaries or a single binary, thus a different arrows are used to disambiguate the generators. For map generators, the `K := V` part of the generator prevents any ambiguity.

**Comment by kostis** [comment]
> ```erlang
> Map = #{
>   {a, "hello world"} => <<1, 2, 3>>,
>   {b, "bye"} => nope
> },
> #{K => V || {a, "hello" ++ _} := <<1, _/binary>> <- Map}.
> ```

K and V do not make sense in this example...


More importantly, can you show us some example where multiple generators are involved, esp. one where the set of keys in the different maps used as generators are not disjoint and what are the semantics in this case?

**Comment by seriyps** [comment]
@zuiderkwast yes, there are no ambiguities in the parser right now. Just there were discussions on Twitter about it.

@kostis oups, yes, I made those examples on-spot. There are more added in the `mc_SUITE` test suite.
This particular one could be rewritten as, eg:

```erlang
Map = #{
  {a, "hello world"} => <<1, 2, 3>>,
  {b, "bye"} => nope
},
#{a => V || {a, "hello" ++ _ = V} := <<1, _/binary>> <- Map}.
```

Multiple generators - not sure I understand, but here are some examples:

```erlang
> Map1 = #{1 => a, 2 => b, 3 => c}, Map2 = #{0 => 0, 1 => 1, 3 => 3, 4 => 4}.
> #{{K1, K2} => {V1, V2} || K1 := V1 <- Map1, K2 := V2 <- Map2}.
#{{1,0} => {a,0},
  {1,1} => {a,1},
  {1,3} => {a,3},
  {1,4} => {a,4},
  {2,0} => {b,0},
  {2,1} => {b,1},
  {2,3} => {b,3},
  {2,4} => {b,4},
  {3,0} => {c,0},
  {3,1} => {c,1},
  {3,3} => {c,3},
  {3,4} => {c,4}}
> #{K => V || K := V <- Map1, K := V <- Map2}.                  
#{0 => 0,1 => 1,3 => 3,4 => 4}
> #{K => V || K := V <- Map2, K := V <- Map1}.
#{1 => a,2 => b,3 => c}
> #{K => {V1, V2} || K := V1 <- Map1, K := V2 <- Map2}.
#{0 => {c,0},1 => {c,1},3 => {c,3},4 => {c,4}}
> #{K => {V1, V2} || K := V2 <- Map2, K := V1 <- Map1}.
#{1 => {a,4},2 => {b,4},3 => {c,4}}
```

All this behavior is defined by the fact that under the hood map comprehension like `#{K => V || K := V <- MapExpr}` is translated to `maps:from_list([{K, V} || {K, V} <- maps:to_list(MapExpr)])`. So, for example, when comprehension yields multiple values for the same key, `maps:from_list/1` defines which value will be assigned to duplicated key:

```erlang
> #{K => V || {K, V} <- [{a, 1}, {a, 2}, {b, 1}]}
#{a => 2,b => 1}
```

**Comment by kostis** [comment]
> Multiple generators - not sure I understand, but here are some examples:

Yeah, I was suspecting that my messages are hard to understand.,,,
Sometimes, even I do not understand them!

To help you understand why the semantics of your map comprehensions, although perfectly sensible IMO, are inconsistent with the current semantics of comprehensions, I've opened #4862

**Comment by garazdawi** [comment]
Hello!

Thanks for the PR! The OTP Technical Board had a meeting about this PR this afternoon and we would like to have map comprehensions added to Erlang. However, as you may have figured out, there is more work to be done before that can happen.

First of all this change needs to have a new EEP describing the syntax, semantics and a discussion about alternative approaches. This is needed so that we (the Erlang community) can have a record and separate discussion about map comprehensions.

Some of the extra things that we would like the EEP to look at are:

* What is the error behavior? What happens when a list is passed instead of a map as generator?
* Should map updates be allowed with map-comprehensions? that is should this be valid syntax: `M#{ K => V*2 || K := V <- M}`? or this `M#{ K := V*2 || K := V <- M}`?
* Should a maps iterator be allowed as generator? that is should this work `#{ K => V || K := V <- maps:iterator(M)}`?

You should also take a look at EEP 12 and see what it has to say about comprehensions in general and see if there are any parts worth taking from it (or if not, then write in the discussion why not).

For the implementation to be complete at least these things needs to be updated as well:
* debugger
* syntax_tools
* emacs mode

Adding new syntax constructs to Erlang is quite a lot of work, but we hope that you will continue working on it so that we all someday can enjoy map-comprehensions.

Lukas and the OTP Technical Board

**Comment by garazdawi** [comment]
I will close this PR while waiting for an EEP. We can reopen or create a new PR when that work is done.

**Comment by zuiderkwast** [comment]
I'm slightly sad to see it closed :cry: since the old maps EEP describes comprehensions, including the `{bad_generator, M0}` exception. (Update comprehension and iterator generator were not described, thus they were not suggested until now.)

Emacs mode seems to work as expected without modifications. (I just tried it out quickly.)

@cfclavijo, @pablocostass and @seriyps, are you willing to take on the extra work or do you need some help from the community? I'd just really like to see this happen....

**Comment by pablocostass** [comment]
Hey @garazdawi, give us some time to start working on this; we knew there would be extra things to change, but still it is quite a lot of work as you said. In any case, we will do it, slowly but surely :)

@zuiderkwast Thanks for checking up on us, if something arises that we need help with we will be sure to ask around for help!

**Comment by garazdawi** [comment]
> give us some time to start working on this; we knew there would be extra things to change, but still it is quite a lot of work as you said. In any case, we will do it, slowly but surely :)

There is no rush. The earliest this will be released is in Erlang/OTP 25, which is 11 months away, so there is plenty of time to finish this. If we can get this done sometime before 2022 I'm happy :)

**Comment by seriyps** [comment]
Hi. We opened a PR with map comprehensions proposal almost 5 months ago, collected some feedback from the community, but still didn't hear any opinions from the OTP team

https://github.com/erlang/eep/pull/32

Is there a chance we receive some attention? I'm afraid time is running out for us to be able to make it to OTP-25.

**Pull request closed without merging**
