### PR TITLE
Small fixes in syntax_tools

### PR DESCRIPTION
**Pull request by gomoripeti**
I targeted maint as if I know correctly there is already a code freeze on 21.0.

### CODE REVIEW

**Comment by gomoripeti** [comment]
I haven't noticed that the first commit is already fixed on master.
Let me know if the second commit is desirable and whether I should rebase it to somewhere.

**Comment by uabboli** [comment]
Yes, we are interested in the second commit (bitstrings). The indentation is a bit off, perhaps you'd like to adjust it. Rebasing onto 'maint' is fine.

**Comment by gomoripeti** [comment]
Rebased to latest maint and tried to adjust indentation (I had accidentally tab-with 4 before)

**Comment by uabboli** [comment]
Thanks.

**Pull request merged**
