### PR TITLE
Fix rounding bug in float_to_list/2

### PR DESCRIPTION
**Pull request by sverker**
Example:
```
1> float_to_list(0.145, [{decimals,1}]).
"0.2"
```
For a random float with decimals, about 5.5% risk of an invalid rounding up.

### CODE REVIEW

**Comment by kostyushkin** [comment]
Does this PR solve the same issue for a float_to_binary?

**Comment by sverker** [comment]
@kostyushkin Yes, they share the same back end function.

**Comment by kostyushkin** [comment]
Already saw, thank you)

**Comment by saleyn** [comment]
With this fix, referencing a test case from the mailing list, why is the new functionality considered correct for this case?

float_to_binary(2.7182818284590452354, [{decimals, 14}, compact]).

OTP 19.3: <<"2.71828182845905">>
OTP 20.3: <<"2.71828182845904">>

It seems that the old code produces the correct result, whereas the new one doesn't.
In C:
```C
#include <string>

int main()
{
  double d = 2.7182818284590452354d;
  printf("d = %.14f\n", d);
}
==Output==
d = 2.71828182845905
```

**Comment by sverker** [comment]
@saleyn Fixed on master by #1770.

**Comment by saleyn** [comment]
Thanks. I did some speed testing of that C function compared to the old one, and the new code seems about 3x slower when built in the optimized mode.

**Comment by sverker** [comment]
"A faulty algorithm can always be improved to run arbitrarily fast."

**Comment by sverker** [comment]
Ok, that's make sense. To do /10 and *10 is cheaper than %10 and /10.

Care to put this in a new PR for master?

**Comment by saleyn** [comment]
See #1792

**Pull request merged**
