### PR TITLE
Decode of Counter64 values larger than 16#7fffffffffffffff (9223372036854775807) failed

### PR DESCRIPTION
**Pull request by wahaha88**
From SNMPV2(RFC 1573), Counter64's range is 0-18446744073709551615.
From OTP-8563, Counter64's range is (-9223372036854775808)-(9223372036854775807) in erlang snmpm. If Counter64 is encoded and decoded by erlang snmpm, everything is ok. 
If Counter64 is collected by real network device and decoded by erlang snmpm, "{error,{bad_counter64,18446744073709551615}}}" will be reported by erlang snmpm. 

So I think "(Value >= 0) andalso (Value < 16#8000000000000000) ->" should be modified to "(Value >= 0) andalso (Value < 18446744073709551615) ->" in snmp_pdus.erl.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Fix EVP_aes_???_ctr to demand OpenSSL 1.0.1 or later.
beam_validator: Don't allow an 'undefined' entry label in a function


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Fix EVP_aes_???_ctr to demand OpenSSL 1.0.1 or later.


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
Hi @wahaha88,

Can you please either create a new pull request for this to master or rebase it on maint? 

I'm closing this for now :)

**Pull request closed without merging**
