### PR TITLE
Erl init cleanup

### PR DESCRIPTION
**Pull request by richcarl**
This cleans up the initial hand-over from C code to Beam code, making the old broken option +i work again (for future purposes), removing the broken +b option and the obsolete +# option and the corresponding undocumented and unused system flag 'display_items'. It replaces the weird name "otp_ring0.erl" (which ended up like that for historical reasons during the "standalone erlang" experiments, way back before OTP R6) with the name "erl_init.erl" to correspond with erl_init.c.

### CODE REVIEW

**Comment by michalmuskala** [comment]
Looking at this code, I wonder - why there's this indirection between the `erl_init` and `init` modules? Couldn't the C code call into the `init:boot/1` function directly?

**Comment by richcarl** [comment]
@michalmuskala The intermediate module was introduced by the experiments with Standalone Erlang and is not strictly needed in order to launch init:boot/1, but I think it's a good idea too keep it. The init module is very specific for Erlang and its bootup sequence and services, and the erl_init module can be kept as a neutral launchpad making it easier to experiment with alternative language implementations that may want to do their own bootup from scratch.

**Comment by richcarl** [comment]
I think it's still a good ide to have a fixed piece of Beam code that defines the entry point, because some things may be easier to do on the Erlang level than in C. For instance, if you call a module from C, it must already be loaded (from C). In erl_init, you could e.g. easily start the prim loader and load the requested boot module dynamically. It makes it simpler to do such extensions by just writing a bit of Erlang instead of dropping to C.

**Comment by richcarl** [comment]
You could also move most of the loading-of-preloaded-modules from erl_init.c to erl_init.erl (only requiring the erl_init.beam module to be actually compiled into the C image). This is similar to what the old Standalone Erlang did.

**Comment by richcarl** [comment]
Note to OTP maintainers: as you see, I had to run update_preloaded twice - once after adding erl_init, and once again after removing otp_ring0. This could not be done as a single step.

**Comment by richcarl** [comment]
Yay!

**Pull request merged**
