### PR TITLE
Map error logger warnings to warning messages by default

### PR DESCRIPTION
**Pull request by richcarl**
Also fix and document the broken +We option.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by jlouis** [comment]
Nice catch. This one always perplexed me a bit when I first read about it.

**Comment by zhird** [comment]
This is making some tests in error_logger_warn_SUITE fail, can you please make sure that they are all passing?

**Comment by richcarl** [comment]
I think I've modified the test cases correctly this time. At least the suite passes now.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Merged to master with the following changes:

 * In `kernel` updated `code_SUITE:on_load_errors/1` to reflect the new changes.
 * In `stdlib` updated `qlc_SUITE:otp_6964/1` to reflect the new changes.

**Comment by richcarl** [comment]
Hm, I don't see it in master yet. Just my commit merged a while back followed by a revert.

**Comment by psyeugenic** [comment]
Right, we don't always push master/maint to GitHub directly, only to our internal upstream. I'm sure we'll push it tomorrow.

**Pull request closed without merging**
