### PR TITLE
Add callbacks attributes to snmp

### PR DESCRIPTION
**Pull request by garazdawi**

### CODE REVIEW

**Comment by bmk** [comment]
You have defined the type 'pdu_types()' twice; snmpa_network_interface_filter.erl and snmpm_network_interface_filter.erl.
Maybe put it in snmp.erl instead? There are other basic type defs there.
Also there are already types that you have not used, e.g. 'tdomain()'.

**Comment by bmk** [comment]
I have also just discovered that a whole bunch of test cases fail because
the 'bahaviour_info' function has been removed (its used to check that
callback modules are valid).

**Comment by garazdawi** [comment]
> You have defined the type 'pdu_types()' twice; snmpa_network_interface_filter.erl and snmpm_network_interface_filter.erl.
Maybe put it in snmp.erl instead? There are other basic type defs there.

I would have, but they are not identical (manager has `'trappdu'`). Should I take the common parts and put them in snmp.erl?

> Also there are already types that you have not used, e.g. 'tdomain()'.

I was just following [the documentation](https://www.erlang.org/doc/man/snmpa_network_interface_filter#data-types), which stated that snmpa_conf is where the description for the types are, so I assumed that the actual types should be there as well. I've updated  snmpa_conf:transportDomain to use snmp:tdomain().

> I have also just discovered that a whole bunch of test cases fail because
the 'bahaviour_info' function has been removed (its used to check that
callback modules are valid).

The behaviour info function was generated, it was just that the optional_callbacks were not removed from the check in snmp_misc. Fixed.

**Comment by bmk** [comment]
Common types in snmp.erl.
Manager pdu_type in snmpm.erl
Agent pdu_type in snmpa.erl

**Pull request merged**
