### PR TITLE
Use code_server path cache in code:where_is_file/1

### PR DESCRIPTION
**Pull request by the-mikedavis**
`application:load/1` slows down as the number of directories in the code path increases because the call to `code:where_is_file/1` for the '.app' file must scan each directory for the app. The code_server maintains a cache of the contents of directories in the path depending on their `code:cache()` setting since https://github.com/erlang/otp/pull/6729 / https://github.com/erlang/otp/pull/8049. Re-using and updating that cache when searching for '.app' files in `application:load/1` can improve its runtime, especially when loading multiple applications.

~Internally to make this possible I've added a `code_server:where_is_file/1` function that the application_controller uses instead of `code:where_is_file/1`. This re-uses the code_server's existing cache helper functions to find the file and update the caches along the way, respecting the `code:cache()` option for each dir.~

For a reasonably large project (RabbitMQ) with a high number of code path dirs (111 at time of writing), loading an application might take upwards of 20ms. With the code_server's cache, loading each application takes at most around half of a millisecond instead. `application:load/1` is used for loading plugins in Rabbit's CLI for example, and this change can save as much as 750ms for a run of `rabbitmqctl --help` (30% of the total run time). It also improves boot time for the broker since `application:load/1` is used by `application:start/2`.

### CODE REVIEW

**Comment by josevalim** [comment]
@the-mikedavis perhaps it would make sense to change `code:where_is_file/1` itself to go through the code server and use the cache? This would optimize both `which` and `where_is_file` as well.

**Comment by kikofernandez** [comment]
Does it make sense if `which/1`:

```erlang
which(Module) when is_atom(Module) ->
    case is_loaded(Module) of
	false ->
            which(Module, get_path());
	{file, File} ->
	    File
    end.
```
Gets updated to:
```erlang
which(Module) when is_atom(Module) ->
    case is_loaded(Module) of
      false ->
        File = atom_to_list(Module) ++ objfile_extension(),
        where_is_file(File);
      {file, File} ->
        File
    end.
```

The `get_path()` function in the first snippet of code calls back to `#state.path` in `code_server`, which is the same behaviour as caling `where_is_file/1`. The `where_is_file/1` performs a check to see if something is already in the cache (and updates it if needed). I think this makes sense? Any reason for not doing this?

**Comment by josevalim** [comment]
@kikofernandez I agree it makes sense. Perhaps we should get rid of `where_is_file/2`. It seems to be private and it seems we no longer use it anywhere?

**Comment by kikofernandez** [comment]
I initially thought so, but `where_is_file/2` seems to be used by [`which/2`](https://github.com/erlang/otp/pull/8078/files#diff-742ca058889126acdedf4d1d70c48fc534ecac2c39a1d38fc3233d487a20d158R1626-R1628), and `which/2` is used by `module_status/2` (copied below), and the comment seems to imply that we cannot go via `which/1`. 

I do not fully understand the "why" certain things are as they are, so I am not sure that we can remove `which/2` without doing some more refactoring.

```erlang
%% Note that we don't want to go via which/1, since it doesn't look at the
%% disk contents at all if the module is already loaded.
module_status(Module, PathFiles) ->
    case is_loaded(Module) of
        false -> not_loaded;
        {file, preloaded} -> loaded;
        {file, cover_compiled} ->
            %% Cover compilation loads directly to memory and does not
            %% create a beam file, so report 'modified' if a file exists.
            case which(Module, PathFiles) of
                non_existing -> removed;
                _File -> modified
            end;
```

**Review by kikofernandez — APPROVED** [review]
Looks good to me.
Unless someone objects, I will merge in a few days.

Thanks!

**Pull request merged**
