### PR TITLE
remove repeated words and small typos

### PR DESCRIPTION
**Pull request by ivanov**
I found a repeated word typo, and decided to start going through and removing repeated words where they were accidentally present, both in documentation and in comments. This first commit already has 70 changes in 50 files, and I'm about 10% of the doubled words that I found (there are lots of false-positives, like `long long`).

This seems like a reasonable chunk to review, but I am open to either breaking it up further into smaller chunks, if necessary, or adding more to this change set, if that would be more desirable. Please let me now how to proceed.

I also have a question about vendor-ed 3rd party code: I intend to submit the relevant patches upstream, but I don't know if you'd prefer to exclude them (for example, asmjit and zlib patches)

(apologies for  accidentally opening this PR not in Draft mode initially, I miss-clicked)

### CODE REVIEW

**Comment by garazdawi** [comment]
Hello!

We do not want any changes to vendored code, please submit those changes upstream and we will get them when we update.

This is a good size to review.

**Comment by ivanov** [comment]
Thank you for your patience. I've removed the `zlib` and `asmjit` portion of the typo fixes from this PR. 

The `zlib` fixes were  [sent upstream and accepted.](https://github.com/madler/zlib/commit/643e17b7498d12ab8d15565662880579692f769d). The `asmjit` ones I [only submitted just now](https://github.com/asmjit/asmjit/pull/425). 

I think all that remains here is Erlang/OTP fixes, so this one is now ready for review. Thanks!

**Comment by jhogberg** [comment]
Thanks, I've added it to our nightly builds. :)

**Comment by jhogberg** [comment]
Merged, thanks for the PR!

**Pull request merged**
