### PR TITLE
Fix filename:split/1 when given <<>>.

### PR DESCRIPTION
**Pull request by KOUCHANG**
Now, given `<<>>` to `filename:split/1`, `<<"/">>` is returned. I think it is strange that come back `<<"/">>`, when there is no path. So I was modified to return an empty list `[]`.
This also is the same as the behavior when given an empty string.

- previous behavior
```erl
> filename:split(<<>>).
[<<"/">>]
```

- post behavior
```erl
> filename:split(<<>>).
[]
```

### CODE REVIEW

**Comment by crownedgrouse** [comment]
Hi I think this should keep the input type and return :
[<<"">>]
because when giving a valid binary path, a list of binary element is returned while a list of string is return when using a string path.
$> filename:split("/home/test").
["/","home","test"]
$> filename:split(<<"/home/test">>).
[<<"/">>,<<"home">>,<<"test">>]

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Fix filename:split/1.


----------------

I am a script, I am not human 

----------------

**Comment by KOUCHANG** [comment]
Thank you for reviewing.

Ok.
In that case, when `""` is given, the return value is `[""]`?

- Current behavior
```
> filename:split("").
[]
```

- Expected behavior
```
> filename:split("").
[""]
```

(Personally, I want to return `{error, badarg}`, because `""` and `<<"">>` has no meaning as paths.)

**Comment by crownedgrouse** [comment]
yes this should be consistent for both case. Changing the return value to {error, badarg} would make sens either, but this should be valided by OTP team, I guess. 
The return value is a list of elements. if an empty path is given, it should probably return a list of an empty string or binary and not an empty list. 

dear OTP team, a decision on this ?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Returning an empty list from both filename:split("") and filename:split(<<"">>) makes most sense. That is, the correction itself is OK.

However, we want a better description of what has been fixed in the commit message, and the split/1 test case in filename_SUITE should also be updated with similar tests as in split_bin/1 (don't add any ?line macros).

**Comment by KOUCHANG** [comment]
I have fixed commit message, and updated test. Please review again.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
I don't see any updated commit message, but I see a commit authored by Mikael Pettersson and commited by you. Seems that something has gone wrong.

Since you have found a bug, I will treat this pull request as as bug report and fix the bug myself. The correction will be merged to master next week if not earlier.

**Pull request closed without merging**
