### PR TITLE
Extend shell c(...) to find and recompile modules

### PR DESCRIPTION
**Pull request by richcarl**
(This is a much-reworked version of functionality that we've been using at Klarna for many years.)

This extends the shell function c/1 and c/2 so that if the argument is a module name instead of a file name, it automatically locates the .beam file and the corresponding source file, and then recompiles the module using the same compiler options (plus any options passed to c/2). If compilation fails, the old beam file is preserved. Also adds c(Mod, Opts, Filter), where the Filter argument allows you to remove old compiler options before the new options are added.

### CODE REVIEW

**Comment by richcarl** [comment]
Note that this is preliminary. I have not written documentation for the new behaviour of c(). The function filename:find_src() is deprecated, but some of its functionality is useful so I made a new entry point locate_source(), and made it a bit more powerful. This could be dropped if you don't want it, or it could be moved to filelib.erl instead, which seems a better place than filename.erl.

**Comment by richcarl** [comment]
Another thing that could be done is to break out all the compilation code to a new module "c_compile.erl" or similar.

**Comment by expelledboy** [comment]
@richcarl I actually developed something very similar about 2 years ago. Was very very useful!! 👍

**Comment by bjorng** [comment]
@richcarl Did you notice that "All checks have failed"?

**Comment by bjorng** [comment]
The test case `shell_SUITE:restricted_local/1` in stdlib fails.

I think it would be a good idea to move the `find_src` to `filelib` as you suggested. It is more logical place. The `filename:find_src/1,2` should be deprecated and call the corresponding functions in `filelib`. I think that the warning against using `find_src` should be removed. When we wrote the warning we had tools such as `debugger` and `cover` in mind.

I don't think it is necessary to create a `c_compile` module.

**Comment by richcarl** [comment]
@bjorng Not sure what to do with that failing test. For some reason, that line checks that calling c(F) with a fun F results in {error,...}. Unclear why this would be a useful test. Also, the reason that it currently "works" is that it's actually the call to compile:file/1 that returns {error,function_clause} if you pass it a fun - and this is not even a valid return value according to the docs for compile:file/1 (but maybe that behaviour needs documenting).

**Comment by bjorng** [comment]
@richcarl Yes, the test is strange. I think that the purpose of it is to test that the restricted shell allows calling `c:c/1`. I have pushed a new commit that makes sure that the compilation succeeds.

**Comment by richcarl** [comment]
Thanks! I'm currently moving the find_src code to filelib and reworking it a little. Will also add documentation.

**Comment by richcarl** [comment]
Moved and reworked the new find_file/source functions, fixed test cases, added documentation, and squashed it all up nicely.

**Comment by richcarl** [comment]
Now what? I can't see what's gone wrong in that failed check.

**Comment by bjorng** [comment]
I can't explain it either. I had the same problem with my most recent PR. I restarted the test twice, and the second time it didn't fail.

Restarting the test for this PR...

**Comment by richcarl** [comment]
Worked now, thanks.

**Comment by bjorng** [comment]
We will test this PR in our daily builds.

**Comment by bjorng** [comment]
There was a warning in our Jenkins build about a missing anchor. I have pushed a fixup commit that adds the missing anchor. Please squash it into the original commit.

**Comment by richcarl** [comment]
Done.

**Comment by bjorng** [comment]
Thanks!

**Comment by bjorng** [comment]
I have pushed a fix for the last bug (TM).

Deprecated functions should have a `-deprecated()` attribute in the module itself (for the benefit of `xref`). We have a test case in `otp_SUITE` to test that, because it is easy to forget.

Please squash this commit.

**Comment by richcarl** [comment]
Squashed.

**Comment by bjorng** [comment]
Thanks!

**Comment by expelledboy** [comment]
Nice, in what release will be available?

**Comment by bjorng** [comment]
OTP 20.

**Comment by sirihansen** [comment]
@richcarl , in this PR you [explicitly set the default `outdir` option to the directory where the source file is found](https://github.com/erlang/otp/blob/master/lib/stdlib/src/c.erl#L258). This differs from the previous behavior, and seems to be the root cause behind [this bug](https://bugs.erlang.org/browse/ERL-438). Could you please shed some light on this decision?

**Comment by richcarl** [comment]
@sirihansen Thanks for the heads-up. I'll make further comments in the bug report, but as far as I can remember, when I tested the functionality manually, it seemed bad to end up with the beam files in the current directory when you compiled a file residing in a subdirectory. It can probably be reverted to the old behaviour with no ill effects.

**Comment by sirihansen** [comment]
Thanks, @richcarl ! I have commented in the bug report also - it's probably a good idea to remove the use of `c` from `make`. And we'll discuss a bit more before deciding on the default `outdir` in `c`.

**Pull request merged**
