### PR TITLE
ssl:recv timeout() can be 0

### PR DESCRIPTION
**Pull request by joedevivo**
gen_tcp:recv allows this, and if you're doing something like
`Transport:recv(Socket, 0, 0)`, TCP will work and SSL will exit with
`function_clause`

There were other cases of this throughout the module. This PR cleans
them all up.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
I have made a master based version and put it into the test machinery, as the next planned release is 19.

**Comment by joedevivo** [comment]
Thank you! Will it be available in any future patch release for 18?

**Comment by IngelaAndin** [comment]
We will not make a special patch release for 18 with it, but it is possible that we can include it if we need to make a 18 patch for some other reason.

**Comment by joedevivo** [comment]
That's fair. Thanks.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
The patch does not break anything, however it would be nice if you could add a test case that fails before adding your change so that we have regression testing.

Also there are a lot of whitespace  changes it would be good if you could avoid them.

**Comment by joedevivo** [comment]
The test suite is intimidating, and I don't really have time to figure out where it should go. If you point me to the right spot, I'll take a look.

**Comment by IngelaAndin** [comment]
Look at ssl_basic_SUITE.erl  test case ssl_recv_timeout, you should be able to make something similar with 0 timeouts.

**Comment by IngelaAndin** [comment]
I added a basic test and removed the white space errors, have merged to master.

**Pull request closed without merging**
