### PR TITLE
crypto: Check NID_* for each elliptic curve at compile time

### PR DESCRIPTION
**Pull request by HansN**
Check for supported elliptic curves at compile-time.
The problem was reported in [ERL-823](https://bugs.erlang.org/browse/ERL-823)

### CODE REVIEW

**Comment by mrallen1** [comment]
This is a bit ugly I admit but there's but there is no better solution at the moment. Thank you!

**Comment by mrallen1** [comment]
Yeah, definitely open to including it in the context of kerl but we'll have to see how much backporting work it would take to make it work for each of those releases.

**Comment by RoadRunnr** [comment]
I don't think this is the ways to go.

I've not been looking into this lately, but when I remember correctly:

1. NO_EC2M disables support for some specific algorithms needed for a certain type of EC curves
2. Erlang does not use the NIDs from OpenSSL, but rather defines the curve parameters itself.

For example you might have a OpenSSL that does not define the NIDs for the Brainpool curves, but that has still the required algorithmic support for those curves. Since Erlang is defining the base parameters for the curves itself, it would still be able to use those curves despite the missing OpenSSL NIDs.

**Comment by HansN** [comment]
I'll close this PR without merging.
On the mailing-list erlang-questions Per showed by counterexample that a NID could be defined but unsupported in at least one distro.  And @RoadRunnr gave a perfect argument against it.
Thanks a lot to all!

**Pull request closed without merging**
