### PR TITLE
Strong Dialyzer support and better type specification syntax for maps

### PR DESCRIPTION
**Pull request by margnus1**
This pull request introduces strong type inference for maps into Dialyzer, as
well as improves the type specification syntax for maps.

## New Map Type Syntax
Although it only constitutes a small fraction of the code in this PR, let's
first talk about the type specification syntax improvements.

The difference from the previous syntax is the following:

 * Mandatory (`:=`) pairs. They apply the same constraint on a value as an
   optional (`=>`) pair, but, in addition, also require the value to contain at
   least one key matching the key type in the pair. They are necessary to
   Dialyzer internally in order to provide adequate analysis strength, but are
   also useful as (Dialyzer-checkable!) documentation; see the `supervisor.erl`
   changes for an example.
 * Overlapping pairs. The previous version left unspecified what having
   overlapping pairs in a type meant. With the new syntax, we now explicitly
   allow this, and specify that the leftmost pair with a matching *key* type
   takes precedence. We may now, for example, write a type
   `#{integer() => integer(), any() => any()}`, which means a map with any key,
   but integer keys may only be mapped to integer values. The value `#{1 => hi}`
   does not belong to this type, even though it does belong to
   `#{any() => any()}`.
 * `...` is allowed as a syntactic short-hand for the pair `any() => any()` when
   used as the last pair in a type. This is very useful to write "any map, as
   long as it contains a key `X`" (`#{X := _, ...}`).
 * The special case of `#{}` is removed, changing its semantics from "a map of
   any size" to "the empty map" (only). This is the only breaking change from
   the previous (experimental) syntax.

As alluded to above, with the exception of `#{}`, all types that were
well-defined with the previous syntax continue to parse and keeps existing
semantics with this new syntax.

### Formal Description
Formally, a map value `M` belongs to a type `#{Pairs}` iff:

 * For each pair `K => V` in `M`, there exists at least one pair `KT => VT` or
   `KT := VT` in `Pairs` such that `K ∈ KT`, and, for the leftmost such pair in
   `Pairs`, `V ∈ VT`.
 * For each pair `KT := VT` in `Pairs`, there exists a pair `K => V` in `M` such
   that `K ∈ KT`.

## Dialyzer (and Typer) Support
This pull request begins by adding an internal representation of map types into
the `erl_types` type system shared by HiPE, Dialyzer, and Typer. Special
knowledge of the following Built-In Functions is implemented:

 * `maps:from_list/1`
 * `maps:get/2`
 * `maps:is_key/2`
 * `maps:merge/2`
 * `maps:put/3`
 * `maps:size/1`
 * `maps:to_list/1`
 * `maps:update/3`

Then, strong Dialyzer type-inference support is added for the following map
features, for both the type signature inference pass and the module-wide
data-flow pass: map expressions, map patterns, and the `erlang:is_map/1` BIF.

Lastly, a new warning message, `{map_update, [Type, Key]}` is added for bad
exact (`:=`) map updates, and is formatted like this:

    A key of type Key cannot exist in a map of type Type

### Limitations
The current implementation of the map type uses an internal representation that
is less expressive than the new syntax. In particular, it requires that all but
the last pair of an internal map type to have a singleton key type. A singleton
type is a type with only one possible value, such as a literal atom, integer, or
tuple of other literal types. So, for example, if a type specification writes
the type `#{integer()=>integer(), string()=>string()}`, this implementation will
represent that internally as `#{integer()|string() => integer()|string()}`.
This is, naturally, not written in stone and can be improved in the future.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Thanks for the updates!

We are currently testing [margnus1/dialyzer-maps/PR-1014](/erlang/otp/compare/master...psyeugenic:margnus1/dialyzer-maps/PR-1014) in master-opu

That is your current branch and some other changes on to of that by me and @uabboli

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Merged to master: b6975497fc5d8e4b50c6a3237a2b24be0e2585c1

**Pull request closed without merging**
