### PR TITLE
Ensure dbg tracer exits when dbg is stopped

### PR DESCRIPTION
**Pull request by fishcakez**
Previously the tracer might receive an 'EXIT' message in the trace receive loop and treate it as garbage instead of stopping.

See: http://erlang.org/pipermail/erlang-questions/2014-October/081179.html

/cc @leoliu

### CODE REVIEW

**Comment by marcusarendt** [comment]
@fishcakez ping?

**Comment by fishcakez** [comment]
Ah sorry! I have pushed a test case. Do I need to add the `?line` macros?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
The ?line macro is obsolete. It should not be added to new test code or when editing old code.

**Comment by bjorng** [comment]
In the commit message: "treat" is spelled without an "e" at the end.

**Comment by bjorng** [comment]
Otherwise it looks good.

**Comment by fishcakez** [comment]
I have fixed the typo in the commit messages and removed the unnecessary receive clauses.

**Comment by bjorng** [comment]
Thanks! We will test it in our daily builds.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Merged.

**Pull request closed without merging**
