### PR TITLE
Avoid erts_cmp jump in atom, int and float comparisons

### PR DESCRIPTION
**Pull request by josevalim**
Avoid erts_cmp jump in atom, int and float comparisons

Given the function definition below:

    check(X) when X >= 0, X <= 20 -> true.

@nox has originally noticed that perfoming lt and ge
guard tests were performing slower than they should be.

Further investigation revealed that most of the cost
was in jumping to the erts_cmp function. This patch
brings the operations already inlined in erts_cmp
into the emulator, removing the jump cost.

After applying these changes, invoking the check/1
function defined above 30000 times with different
values from 0 to 20 has fallen from 367us to 213us
(measured as average of 3 runs). This is a
considerably improvement over Erlang 18 which takes
556us on average.

Floats have also dropped their time from 1126us
(on Erlang 18) to 613us.

### CODE REVIEW

**Comment by josevalim** [comment]
This is a rebase of #810 against master.

* Due to other improvements in master, this pull request makes integer comparison ~60% faster compared to Erlang 18.
* Differently from #810, this pull request also inlines floats and makes them about ~40% compared to Erlang 18 (about ~25% compared to master itself).
* The exact code used for benchmark and an example of the inlined function can be found here: https://gist.github.com/josevalim/6082ce080c7f29312949

**Comment by kostis** [comment]
A small, but perhaps important, objection/correction to the phrasing of the commit: These are not "the same function", as the first also works for floating point numbers, while the second does not.  Can it be that the first function should also contain an `is_integer(X)` guard?

**Comment by josevalim** [comment]
@kostis agreed, thank you. The guard in this case won't affect the optimization but I assume I can remove the function comparison.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by josevalim** [comment]
@bjorng I have pushed a new commit to a separate branch that I would like your opinion on. I have noticed that this commit has removed the direct `(a) == (b)` and `(a) != (b)` checks from from CMP_LT and CMP_GE, seen here:

https://github.com/erlang/otp/pull/952/files#diff-3b4adc3cf770771657e498344c65ff3bL182

Of course, those checks are useful only on occasions where we write `X <= 20` and X is 20. I have added them back in a commit and I have noticed that the matching cases are about 10% faster without a noticeable impact on other cases.

I have also used the opportunity to avoid jumping on `==` and `!=` as well. For such cases, inlining make those operators roughly 30% faster.

You can see all changes here: https://github.com/josevalim/otp/commit/30933d5c99086a4306843994e14db1824f19c486

Two questions:

  1. Should I merge the changes above into this branch? They do make the code uglier but they yield further improvements.

  2. Is there any reason for having both `cmp_eq` and `CMP_EQ` definitions? The difference between them is only the `(a) == (b)` check, shown below:

    ```c
    #define cmp_eq(a,b)          (CMP_EQ_ONLY((a),(b)) == 0)
    #define CMP_EQ(a,b)          ((a) == (b) || cmp_eq((a),(b)))
    ```

  I have noticed that `cmp_eq` is only called by the `==` BIF. What is the rationale for not performing the `(a) == (b)` check inside the BIF? Is it because it would never match or is it because it would be semantically wrong? If we can perform `(a) == (b)` inside the BIF, then we could inline `CMP_EQ` into `cmp_eq`.

Thank you.

**Comment by bjorng** [comment]
1. Yes.

2. No, there is no reason to keep both sets of macros. As far as I know, the code ended up the way it looks just for historical reasons. Some of the macros was first added to beam_emu.c and later moved to erl_utils.h. So it would be a good thing to clean away all unnecessary macros (keeping the uppercase names).

**Comment by josevalim** [comment]
@bjorng thank you. I have pushed the changes. We now have two commits, one that applies the optimizations and another one that cleans up the macro usage.

**Comment by bjorng** [comment]
Thanks! We will test in our daily builds.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Merged.

**Comment by josevalim** [comment]
Thank you @bjorng!

**Pull request closed without merging**
