### PR TITLE
Consider total when computing tprof layout width

### LINKED ISSUE #8139: OTP27: tprof may truncate the total value
**Describe the bug**
`tprof` doesn't seem to consider the width of the total value (final row) and therefore prints a truncated number.

**To Reproduce**
Given `tprof_test.erl` like this:
```
-module(tprof_test).

-export([loop_f/1]).

loop_f(N) ->
    [f(M) || M <- lists:seq(1, N)].

f(M) ->
    B = integer_to_binary(M),
    <<B/binary, B/binary>>.
```
I get the following result:
```
1> tprof:profile(tprof_test, loop_f, [1000], #{type => call_memory}).

****** Process <0.284.0>  --  100.00% of total *** 
FUNCTION                             CALLS  WORDS  PER CALL  [    %]
lists:seq_loop/3                       251   2000      7.97  [13.33]
tprof_test:'-loop_f/1-lc$^0/1-0-'/1   1001   2000      2.00  [13.33]
erlang:integer_to_binary/1            1000   3000      3.00  [20.00]
tprof_test:f/1                        1000   8000      8.00  [53.33]
                                            15000            [100.0]

2> tprof:profile(tprof_test, loop_f, [10000], #{type => call_memory}).

****** Process <0.291.0>  --  100.00% of total *** 
FUNCTION                             CALLS  WORDS  PER CALL  [    %]
lists:seq_loop/3                      2501  20000      8.00  [13.33]
tprof_test:'-loop_f/1-lc$^0/1-0-'/1  10001  20000      2.00  [13.33]
erlang:integer_to_binary/1           10000  30000      3.00  [20.00]
tprof_test:f/1                       10000  80000      8.00  [53.33]
                                            15000            [100.0]
```
In the first case everything is good. In the second case the last digit of the total was truncated - it should be 150000.

**Affected versions**
27.0-rc1

### PR DESCRIPTION
**Pull request by josevalim**
Prior to this patch, the length of the total
value being measured was not taken into account
into the layout. This commit addresses it and
also removes outdated comments and redundant
variables.

Closes #8139.

### CODE REVIEW

**Comment by max-au** [comment]
You beat me to it, so let's take in this patch. However, I also added the code from #8139 as a test (for a repro), could you do the same?

**Comment by josevalim** [comment]
@max-au I pushed a test case but it is not one that I am very pleased with, as it seems to be very coupled with how lists:seq/2 may allocate. At the same time, I don't mind closing this if you have a separate PR with better tests, feel free to use the above in whatever shape or way. :)

**Review by max-au — APPROVED** [review]
Haha, you won't like mine either, as the code is the same :-D
Looks good to me though.

**Comment by garazdawi** [comment]
Thanks!

**Pull request merged**
