### PR TITLE
Md5 fixes r18

### PR DESCRIPTION
**Pull request by richcarl**
Improve module_info in presence of native code

- Set module md5 based on native code, if used
- Add module info entry 'native' -> true | false
- Handle empty md5 field gracefully (do not return random bytes)
- Remove obsolete 'imports' key from module_info spec

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Set module_info md5 for native-loaded modules based on native code, not beam


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Set module_info md5 for native-loaded modules based on native code


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Looks good.

In beam_bif_load.c there already is a function is_native used by the BIF code_is_module_native_1.
You can call that in your has_native() to avoid code duplication.

**Comment by richcarl** [comment]
Yes... I found that function after the fact, but it looked to me like it was answering a slightly different question, since it's looking at both loaded versions of the module, while I only want to know about the active one. So I didn't dare reuse that function. Can you help figure out what the right solution is?

**Comment by sverker** [comment]
I meant to make use of the helper function "is_native" in your has_native function.

Maybe the best is to move is_native to beam_load.c, remove "static", rename it "erts_is_module_native" (for global name scope), and put a function declaration in beam_load.h.

**Comment by richcarl** [comment]
OK, I did that, and modified it to do check for null automatically, to simplify the call sites.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
This patch breaks --enable-native-libs. Reproduce the problem like this:

    git clean -dxfq
    ./otp_build setup -a --enable-native-libs

The compiler will crash in the diameter application while attempting to load erl_syntax.

**Comment by richcarl** [comment]
The problem seems to be that bootstrap/lib/kernel/ebin/hipe_unified_loader.beam needs to be updated. Do you want me to try to do that as part of this pull request, or do you want to do it yourselves? (Note that accepting a beam file from the outside would be a possible attack vector - someone could sneak in arbitrary nasty stuff...)

**Comment by bjorng** [comment]
I'll do it.

**Comment by bjorng** [comment]
OK. It worked. I have merged the branch.

**Comment by richcarl** [comment]
Lovely.

**Pull request closed without merging**
