### PR TITLE
Update DNS lookup to support CERT type records (per RFC 4398)

### PR DESCRIPTION
**Pull request by jgautsch**
Usage example:
```erlang
1> [{CertType,KeyTag,Algo,Cert}] = inet_res:lookup("direct.aprima.com", in, cert).
[{"PKIX",6425,"RSASHA1",
  <<48,130,5,86,48,130,4,62,160,3,2,1,2,2,16,6,250,70,36,
    25,25,176,216,218,...>>}]
```

This is my first contribution here, and although I've read the contribution guides, any guidance is much appreciated!

### CODE REVIEW

**Comment by RaimoNiskanen** [comment]
Thank you for your first contribution!

First I would like you to separate all whitespace changes into a separate commit - they make the actual change hard to see.

Then I want you to also mention RFC 4034 since there is where the algorithm type mnemonics can be found.  Both in the comment for `decode_algorithm/1` and in the commit comment.

The `inet_dns` module uses lowercase atoms for all mnemonics that are presented as uppercase in a zone file.  For example a normal RR record "erlang.org. IN A 192.121.151.106" is by `inet_res:lookup` returned as:
```erlang
#dns_rr{
    domain = "erlang.org", type = a, class = in,
    data = {192,121,151,106}}
```
That is: class `in` type `a` for an IN A record.

So change all mnemonics to lowercased atoms.  The algorithm types too.

I also think decoding should be more forgiving so unrecognized cert types and algorithm types should be returned as their integer value.

Furthermore test cases are missing.  There is a test suite `inet_res_SUITE` in the kernel test directory.  It should be possible to extend that to look up a CERT RR, for example in `resolve/1`.

Also, all other record types have got encode functions besides decode functions.  So for completeness please add that too.

**Comment by jgautsch** [comment]
Thank you for the very helpful feedback! I'll work on these improvements

**Comment by jgautsch** [comment]
Quick update- I've been very busy with work, but still plan on making these improvements. Thanks!

**Comment by IngelaAndin** [comment]
How is this going?  I should also look at RFC 6944, https://tools.ietf.org/html/rfc6944 , that updates RFC 4398

**Comment by IngelaAndin** [comment]
We are closing this PR due to inactivity,  you (or someone) are welcome to reopen it you want to work on it.

**Pull request closed without merging**
