### PR TITLE
[pg] Implement group membership monitoring

### PR DESCRIPTION
**Pull request by max-au**
This PR consists of multiple commits for review convenience:
- internal refactoring (does not change logic) to bring consistency for record and function naming
- scope-level monitor implementation
- group-level monitor implementation

I believe that first two commits are self-explanatory, with the only question I can think about is naming. I named the function to monitor the entire scope as `monitor_scope/0,1` to avoid clashes with the `monitor` function implemented in the third commit. If we end up scratching the third commit, the name can be changed to just `monitor/0,1`.

As for the third commit, it is debatable whether a new API `monitor/1,2` (starts monitoring for a specific group membership updates) belongs to `pg` or not. It is possible to implement per-group monitoring using a separate process (that monitors all changes to the scope and notifies subscribers). This does not even need to be a part of OTP (third-party pub/sub solution would work just as well). Performance-wise, separating per-group monitoring to an extra process uses a tiny bit more CPU overall, but it allows to separate `pg` updates from group membership notifications, improving group update latency.

On the other side, it is convenient to have `monitor/1,2` implemented in OTP, as that's the actual use-case for majority of applications (that care only about their own group membership updates).

I can think of several ways forward:
- remove the third commit from the PR and merge the first two (keeping the door open for the third commit as a separate PR)
- merge as-is after fixing review comments (keeping third commit)
- refactor third commit implementation - let `pg` scope to start an extra (child) process that will use use `monitor_scope` subscription to receive all scope updates, and then perform group-level notifications

### CODE REVIEW

**Comment by rickard-green** [comment]
The `pg_SUITE:initial` test has failed each night since introduced like this, but only on one machine each night:
```
pg_SUITE:initial failed on line 317
Reason: {assertEqual,[{module,...},{...}|...]}

=== Ended at 2022-06-13 02:21:46
=== Location: [{pg_SUITE,initial,[317]},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,317},
                      {expression,
                          "rpc : call ( Node , pg , get_members , [ ? FUNCTION_NAME , ? FUNCTION_NAME ] )"},
                      {expected,[<0.18390.3>]},
                      {value,[]}]}
  in function  pg_SUITE:initial/1 (pg_SUITE.erl, line 317)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

**Comment by rickard-green** [comment]
The `pg_SUITE:monitor_scope` has failed once since introduction as well:
```
pg_SUITE:'-monitor_scope/1-fun-4-' failed on line 575
Reason: {assertEqual,[{module,...},{...}|...]}

=== Ended at 2022-06-12 12:16:02
=== Location: [{pg_SUITE,'-monitor_scope/1-fun-4-',[575]},
              {pg_SUITE,monitor_test_impl,[627]},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,575},
                      {comment,"pg did not remove DOWNed scope monitor"},
                      {expression,"ScopeMonitors"},
                      {expected,
                          #{#Ref<0.966810714.3589537794.57312> =>
                                <0.19284.3>}},
                      {value,
                          #{#Ref<0.966810714.3589537794.57312> => <0.19284.3>,
                            #Ref<0.966810714.3590848513.109041> =>
                                <55879.89.0>}}]}
  in function  pg_SUITE:'-monitor_scope/1-fun-4-'/3 (pg_SUITE.erl, line 575)
  in call from pg_SUITE:monitor_test_impl/5 (pg_SUITE.erl, line 627)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

**Comment by rickard-green** [comment]
Also once since introduction:
```
pg_SUITE:disconnected_start failed on line 496
Reason: {assert,[{module,...},{...}|...]}

=== Ended at 2022-06-12 09:59:48
=== Location: [{pg_SUITE,disconnected_start,[496]},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assert,[{module,pg_SUITE},
                          {line,496},
                          {expression,"lists : member ( Node , nodes ( ) )"},
                          {expected,false},
                          {value,true}]}
  in function  pg_SUITE:disconnected_start/1 (pg_SUITE.erl, line 496)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

**Comment by max-au** [comment]
Hm, I wasn't able to reproduce any of these.
Is there any correlation between machine CPU and failure rate? I am probably pushing it to the limit running too many concurrent test cases with too tight timeouts (which also means I have a clowny test design, will look into that and submit fixes).

**Comment by rickard-green** [comment]
.> Is there any correlation between machine CPU and failure rate?

Really hard to find any correlation. A lot, but not all, of the runs that fail execute in an environment or with a configuration that probably affects timing. For example, in a container on a machine which potentially could get more executing threads than logical processors, using address sanitizer, configured with --enable-sharing-preserving (in terms passed between processes, etc), or configured with --enable-dirty-schedulers-test (which execute various BIFs on dirty schedulers). I think, but am not sure, that the address sanitizer (asan) runs are over-represented. I don't think I've seen debug builds, though, which often changes timing quite substantially.

**Comment by max-au** [comment]
I pushed a number of fixes:
- pg_SUITE:initial and pg_SUITE:double test had a genuine race condition (discover -> exchange protocol is 3 messages, nodeup -> discover -> exchange), but original test implementation was flushing the message queue only once
- monitor and monitor_scope have not been properly starting remote monitor, so I made the test more reliable (linking the remote monitor process too)

There may be a few more test issues caused by race conditions (missing syncs), I'll take a closer look separately. 

The most mysterious one is 'errors' failure. How could it be a 'timeout', given that as soon as `pg` receives a broken message, it crashes unconditionally? Can it be something wrong with process aliases (e.g. when 'EXIT' is not delivered through process alias somehow).

**Comment by max-au** [comment]
You're right! This 100 ms timeout is accidental left-over, I'll fix that as well in the next iteration.

**Comment by rickard-green** [comment]
### Failed test-cases after the latest fixes (5eece21) of the PR

#### PR merged into maint branch

`monitor_scope` (OTP built with `--enable-sharing-preserving`):
```
=== Location: [{pg_SUITE,monitor_test_impl,630},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,630},
                      {comment,"Local monitor failed"},
                      {expression,"SecondMonMsgs"},
                      {expected,
                          [{#Ref<0.3735042508.3571449858.239448>,join,1,
                            [<55756.90.0>,<55756.90.0>]},
                           {#Ref<0.3735042508.3571449858.239448>,leave,1,
                            [<0.18730.3>]},
                           {#Ref<0.3735042508.3571449858.239448>,leave,1,
                            [<55756.90.0>]}]},
                      {value,
                          [{#Ref<0.3735042508.3571449858.239448>,join,1,
                            [<55756.90.0>,<55756.90.0>]},
                           {#Ref<0.3735042508.3571449858.239448>,leave,1,
                            [<0.18730.3>]}]}]}
  in function  pg_SUITE:monitor_test_impl/5 (pg_SUITE.erl, line 630)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

`forced_sync` (OTP built with `--enable-sharing-preserving`):
```
=== Ended at 2022-06-17 05:48:09
=== Location: [{pg_SUITE,forced_sync,537},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,537},
                      {expression,
                          "lists : sort ( pg : get_members ( ? FUNCTION_NAME , ? FUNCTION_NAME ) )"},
                      {expected,[<55751.89.0>,<55751.89.0>]},
                      {value,[]}]}
  in function  pg_SUITE:forced_sync/1 (pg_SUITE.erl, line 537)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

`two` (default config on dedicated machine):
```
=== Location: [{pg_SUITE,two,251},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,251},
                      {expression,
                          "lists : sort ( pg : get_members ( ? FUNCTION_NAME , ? FUNCTION_NAME ) )"},
                      {expected,[<55758.92.0>,<55758.93.0>]},
                      {value,[]}]}
  in function  pg_SUITE:two/1 (pg_SUITE.erl, line 251)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

`netsplit` (OTP built with `--enable-dirty-schedulers-test`):
```
=== Location: [{pg_SUITE,netsplit,341},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,341},
                      {expression,
                          "peer : call ( Peer , erlang , nodes , [ ] )"},
                      {expected,[]},
                      {value,[test_server@shadowfax]}]}
  in function  pg_SUITE:netsplit/1 (pg_SUITE.erl, line 341)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

#### PR merged into master branch

`monitor_scope` (OTP built with `--disable-kernel-poll`):
```
=== Location: [{pg_SUITE,monitor_test_impl,630},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,630},
                      {comment,"Local monitor failed"},
                      {expression,"SecondMonMsgs"},
                      {expected,
                          [{#Ref<0.3727845675.112984065.157921>,join,1,
                            [<55704.90.0>,<55704.90.0>]},
                           {#Ref<0.3727845675.112984065.157921>,leave,1,
                            [<0.18259.3>]},
                           {#Ref<0.3727845675.112984065.157921>,leave,1,
                            [<55704.90.0>]}]},
                      {value,
                          [{#Ref<0.3727845675.112984065.157921>,join,1,
                            [<55704.90.0>,<55704.90.0>]},
                           {#Ref<0.3727845675.112984065.157921>,leave,1,
                            [<0.18259.3>]}]}]}
  in function  pg_SUITE:monitor_test_impl/5 (pg_SUITE.erl, line 630)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

`disconnected_start` (cover test):
```
=== Ended at 2022-06-16 03:11:44
=== Location: [{pg_SUITE,disconnected_start,502},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assert,[{module,pg_SUITE},
                          {line,502},
                          {expression,"lists : member ( Node , nodes ( ) )"},
                          {expected,false},
                          {value,true}]}
  in function  pg_SUITE:disconnected_start/1 (pg_SUITE.erl, line 502)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

`forced_sync` (OTP built with `--disable-esock`):
```
=== Ended at 2022-06-16 04:05:31
=== Location: [{pg_SUITE,forced_sync,537},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,537},
                      {expression,
                          "lists : sort ( pg : get_members ( ? FUNCTION_NAME , ? FUNCTION_NAME ) )"},
                      {expected,[<55488.89.0>,<55488.89.0>]},
                      {value,[]}]}
  in function  pg_SUITE:forced_sync/1 (pg_SUITE.erl, line 537)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

**Comment by rickard-green** [comment]
All tests above, except for the one where I wrote "on dedicated machine", executes in a container on a machine that executes multiple containers simultaneously.

**Comment by max-au** [comment]
I pushed two more fixes:
- monitor_scope: indeed, it was a race condition (needed to ensure that message queues on the local node are processed from the point of view of the remote node)
- two: same problem (it's been there from the beginning)

However for `netsplit`, `forced_sync` and `disconnected_start`, there are very clear symptoms of a distribution connection created despite of specifying command line arguments: `-kernel dist_auto_connect never` (also `-connect_all false` that should not affect behaviour).
It is especially clear from the `disconnected_start` when a new peer node is asserted to be not in the `nodes()` list. It could be something specific to `cover`, but two other (forced_sync and netsplit) exhibit exactly the same symptom - getting peer node connected when it's not expected to be.

Could it be that `-kernel dist_auto_connect never` stopped working reliably?

**Comment by rickard-green** [comment]
Thanks, added these changes to our nightly tests, so they will be run during the weekend.

> Could it be that -kernel dist_auto_connect never stopped working reliably?

Not impossible, but it is strange that no other test-cases have picked up on it. I'm not sure how many good tests we got for this, though. Will look into it next week.

**Comment by rickard-green** [comment]
We've looked into `dist_auto_connect` `never` and we cannot find any issues with it. The `disconnected_start` testcase is explained by the `test_server` node not using `dist_auto_connect` `never` in combination with usage of `cover`. This since `cover` does `rpc:call` to the newly started node from the `test_server` node. I actually cannot understand how this testcase ever succeeds in combination with `cover`, but in about half of the times it does...

The `netsplit` sometimes fails like below when it got an unexpected connection. That can not be explained by `cover`, but the `test_server` node might still auto connect to the node for some other reason. Other applications/services might have seen it since it already has been connected.
```
=== Location: [{pg_SUITE,netsplit,352},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assert,[{module,pg_SUITE},
                          {line,352},
                          {expression,"lists : member ( Node , nodes ( ) )"},
                          {expected,false},
                          {value,true}]}
  in function  pg_SUITE:netsplit/1 (pg_SUITE.erl, line 352)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

We also gotten the below failures, but I don't see that those should have anything to do with an unexpected connection:
```
=== Location: [{pg_SUITE,empty_group_by_remote_leave,275},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,275},
                      {expression,
                          "pg : get_members ( ? FUNCTION_NAME , ? FUNCTION_NAME )"},
                      {expected,[]},
                      {value,[<55868.90.0>]}]}
  in function  pg_SUITE:empty_group_by_remote_leave/1 (pg_SUITE.erl, line 275)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)

=== Location: [{pg_SUITE,forced_sync,537},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,537},
                      {expression,
                          "lists : sort ( pg : get_members ( ? FUNCTION_NAME , ? FUNCTION_NAME ) )"},
                      {expected,[<55892.89.0>,<55892.89.0>]},
                      {value,[]}]}
  in function  pg_SUITE:forced_sync/1 (pg_SUITE.erl, line 537)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)

=== Location: [{pg_SUITE,double,468},
              {test_server,ts_tc,1782},
              {test_server,run_test_case_eval1,1291},
              {test_server,run_test_case_eval,1223}]
=== === Reason: {assertEqual,
                     [{module,pg_SUITE},
                      {line,468},
                      {expression,
                          "rpc : call ( Node , pg , get_members , [ ? FUNCTION_NAME , ? FUNCTION_NAME ] )"},
                      {expected,[<0.18481.3>,<0.18481.3>]},
                      {value,[]}]}
  in function  pg_SUITE:double/1 (pg_SUITE.erl, line 468)
  in call from test_server:ts_tc/3 (test_server.erl, line 1782)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1291)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1223)
```

I've pushed a commit on top of your branch which skips the `disconnected_start` test if `cover` is running, and sets the `gen_server:call` timeout to `infinity` in the `errors` testcase (it has timed out once on an `asan` test run even with the default 5000 ms timeout). You can squash it into one of your commits if you want.

Pg tests looks much better than before, so I'll merge this tomorrow even though we still got some failures.

**Pull request merged**
