### PR TITLE
Improve typespec for `ssl:str_to_suite/1`

### PR DESCRIPTION
**Pull request by Maria-12648430**
Should be obvious 😉

### CODE REVIEW

**Comment by IngelaAndin** [comment]
@Maria-12648430 well sure seems I overlooked that. Maybe we should fix it on maint instead of waiting for OTP-25 ;)

**Comment by Maria-12648430** [comment]
Whatever you think is best :)

**Comment by IngelaAndin** [comment]
@Maria-12648430 So please rebase your branch on maint

**Comment by Maria-12648430** [comment]
@IngelaAndin done, please check.

**Pull request merged**
