### PR TITLE
TLS distribution: allow specifying connect options

### PR DESCRIPTION
**Pull request by legoscia**
The option `inet_dist_connect_options` was missed in #897. With this change, all the options for plain TCP distribution are also supported for TLS distribution.

Also remove calls to deprecated functions in the test suite.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We think the semantics would be clearer if you did  lists:ukeymerge(1,  ConnectOpts, Opts).

**Comment by legoscia** [comment]
That might not be correct if the lists are not already sorted, would it? I made that `lists:ukeysort(1, ConnectOpts ++ Opts)`, which should work for unsorted lists as well, preferring options from `ConnectOpts`.

**Comment by IngelaAndin** [comment]
Yes good catch, that will be fine :)

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
