### PR TITLE
Update httpd_request_handler.erl

### PR DESCRIPTION
**Pull request by s1eepwalker**
fix case clause

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Humm... seems regression test for mod_esi could be better. Would you mind extending httpd_SUITEs
esi_put test to use a lager body so that we can get a test case for your fix.

**Comment by s1eepwalker** [comment]
simple call chain
httpd_request:body_chunk_first/3 ->httpd_request:whole_body/2 -> return {?MODULE, add_chunk, [Body, Length, nolimit]};

terminated with reason: no case clause matching {httpd_request,add_chunk, [....]}  in httpd_request_handler:handle_body/3 line 518

**Comment by IngelaAndin** [comment]
I understand how it can happen and that the feature that I added for a customer is the reason for the bug. I am just saying that we need a regression test, unfortunate the ones we had did not trigger the bug. And I was hoping you could add to the test suite as well as fixing the bug. Of course if you do not we will, it is just a matter of time an priorities.

**Comment by IngelaAndin** [comment]
Thank you for reporting the error, I have now written a test case and fixed the bug after your suggestion.
It will be pushed to maint after passing our nightly build in a day or two.
I will close this PR now, as without a regression test, we view it as a trouble report rather than a PR.

**Pull request closed without merging**
