### PR TITLE
kernel: Added clean function for saved shell history when shell history is enabled

### PR DESCRIPTION
**Pull request by mangalakader**
- Enabling Shell History using ERL_AFLAGS allowed users to persist their erlang shell history across
multiple sessions

- But, if the user wants to delete the previously saved shell histories, it's not possible

- Hence, added a new clean function, which allows the user to delete the saved history via `group_history.erl`

### CODE REVIEW

**Comment by josevalim** [comment]
@mangalakader I believe the group_history module is private to OTP. So maybe it would be worth adding a function to the `c.erl` module called `clean_history()` that invokes the function you defined here? This way developers can call `clean_history()` directly from their erl shell.

**Comment by mangalakader** [comment]
@josevalim  Thanks for guiding in a proper direction. I have added the same to the shell_default also for easier access.

**Comment by garazdawi** [comment]
Looks good to me. However, the documentation also needs updating before this can be merged.

**Comment by garazdawi** [comment]
Closing due to inactivity. Feel free to re-open if/when you find the time to work on this again.

**Pull request closed without merging**
