### PR TITLE
Allow ICMP over DGRAM socket

### PR DESCRIPTION
**Pull request by hauleth**
Fix ERL-1048

### CODE REVIEW

**Comment by hauleth** [comment]
While there I would need to ask @bmk who authored this file, why we need to check the protocol/type pair in the Erlang code instead of passing as is and allowing underlying OS implementation to return error if needed. This would make this PR needless and would not require fixes in future in case if some OS would support more abstract protocol/type pairs.

**Comment by bmk** [comment]
Hi,

Could you please rebase this on maint.
Most of our development (of socket related stuff) is done on maint.

Regards,
/BMK

**Comment by hauleth** [comment]
Sure, no problem. It is my first time, so sorry for the problem.

**Comment by bmk** [comment]
Hi,

I have removed the testing label.

This has been done because the change is in a
'preloaded' module which require special handling.
What I instead have done is to base my own branch
on top of yours (add remote, fetch remote, branch)
and then add the extra stuff. And this branch (which
includes your changes) will be part of the testing.

Regards,
	/BMK

**Pull request merged**
