### PR TITLE
musl erl_interface build fix

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
@zenhack, I will remove uint32_t commit, once #861 is merged.

**Comment by tuncer** [comment]
@mikpe, can you please verify that eb1bdba is good?

**Comment by tuncer** [comment]
@psyeugenic, we should maybe check for the available (5 vs 6 args) `gethostbyname_r()` in `configure.in`. Do you know why it's tested in `erts/configure.in` and not `lib/erl_interface/configure.in`? That said, this fix (4f80d0c) is trivial and small enough for a build fix, so we should probably go with that.

**Comment by tuncer** [comment]
@mikpe, don't bother, it didn't build on Travis-CI, but it did on my gcc-5.2_glibc-2.22 machine. Back to the drawing board.

**Comment by tuncer** [comment]
So, the `uint32_t` and `ei_resolve.c` fixes look reasonable and uncontroversial. That leaves us with having to support musl in the highly libc-specific `hipe_x86_sigaction.c`.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by mikpe** [comment]
@tuncer, I have a preliminary patch with musl-support for hipe_x86_signal.c.  Builds and works with some simple examples.  I want to run it through HiPE's test suite too, so expect a pull request sometime this weekend.

**Comment by tuncer** [comment]
Thanks, @mikpe!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
