### PR TITLE
hipe: Fix alignment of byte-sized constants

### PR DESCRIPTION
**Pull request by kostis**
The first commit (Fix alignment of byte-sized constants) fixes a behavior seen on NetBSD/amd64 reported as ERL-376.  The other two commits cleanup the code that handles the constant table by removing code that is no longer used.

### CODE REVIEW

**Comment by rneswold** [comment]
This seems to fix the problems I've seen on NetBSD/amd64. I built a dozen of our applications and two of our systems which are packaged as OTP releases (they use the `-boot` option to run the `boot.script`.) In all these uses of the VM, I never saw a memory alignment error, warning or crash.

Thanks (and your solution is much, MUCH more elegant than the direction I was going to take.)

Hopefully nothing was broken for ARM targets...

**Comment by kostis** [comment]
This can now be merged.  A further cleanup of the constant table may follow, but this is independent of the issue which is fixed here and moreover I will base that on `master` instead of `maint`.

**Comment by sverker** [comment]
I will let it run one more night to make sure it does not break on ARM.

@kostis Do you know of a small code sample that will reproduce this bug, to put in our tests.
I tried dump.erl published in ERL-376 but that compiled and loaded fine for me.

**Comment by kostis** [comment]
Never seen such a failure on any of the platforms we have access to (32-bit x86 and 64-bit AMD64 and x86_64 running Linux and SPARC running Solaris).  The problem seems to be NetBSD-specific.

**Comment by rneswold** [comment]
We're working on the assumption that the NetBSD allocator will return  a smaller alignment if the data size is smaller than the requested alignment. You can't write test cases for that. However, @kostis found how sub-word constants are created. Maybe a test can be made to make sure they're allocated correctly (indirectly testing the effect that failed on NetBSD's allocator.)

**Comment by sverker** [comment]
The following module gives me a data size of 2
```
-module(d).
-export([t/1]).

t(X) -> <<X, "42">>.
```
and that may fail on NetBSD or other malloc that does not align for small sizes.

But you also showed this output:
```
$ erlc +native dump.erl
hipe_bifs_alloc_data_2: erts_alloc(496) returned 0x7f7fade01210 which is not 128-byte aligned
```
where the alignment demand seems to have been increased to 128 bytes
and that can fail on any OS.

@kostis Can the bug fixed by this PR also explain that overly large alignment demand?

When I compile dump.erl myself, I get a normal 8 byte alignment demand.

**Comment by sverker** [comment]
The more I look at that output from "erlc +native dump.erl" the more confused I get.
The error message says 128-byte alignment but the exception thrown says
hipe_bifs:alloc_data was called with 8 as argument for alignment.

Maybe it's not worth trying to figure out what really happened there.

**Comment by kostis** [comment]
> Can the bug fixed by this PR also explain that overly large alignment demand?

Could be.  It's a bit difficult to say something intelligent about what may be happening on some machine one does not have access to.

**Comment by rneswold** [comment]
> Could be. It's a bit difficult to say something intelligent about what may be happening on some machine one does not have access to.

And to give you access to the machine, we'd have to get you a Kerberos account which I don't they'd let me do just to solve this issue. Sorry.

BTW, the only time I saw the 128-byte alignment was running OTP 19.2. In OTP 18.*, I only saw warnings about 8-byte alignment.

The problem seems to have been fixed. Writing a test case is going to be difficult, if not impossible. If the problem re-occurs in a future release, we can try to do more digging (i.e. I'll try to get you an account on the machine.)

**Comment by margnus1** [comment]
@sverker HiPE will never ask for a 128-byte alignment. The alignment requirement (prior to this PR) was always to the word size for all entries in the data section, except for constants generated by LLVM when vectorizing, which are limited to 32 bytes by [`hipe_consttab:insert_binary_const/3`](https://github.com/erlang/otp/blob/master/lib/hipe/misc/hipe_consttab.erl#L197), although I'm unable to find any program that needs more than 16 bytes (and the commit message that introduced the guard, 7814ec18b0, only mentions 16 bytes).

**Comment by sverker** [comment]
@margnus1 `erts_alloc` does not guarantee 16 byte alignment. Don't this mean that we need to fix hipe_bifs:alloc_data to pad up to proper alignment?

**Comment by margnus1** [comment]
@sverker Yes, it does. Something like 3e35d8f70 should do it, right?

**Comment by sverker** [comment]
@margnus1 Something like that, except I would add the extra bytes from start and do one erts_alloc. Less code complexity, cpu cycles and memory fragmentation risk.

**Pull request merged**
