### PR TITLE
Support for unicode expander

### PR DESCRIPTION
**Pull request by platinumthinker**

### CODE REVIEW

**Comment by uabboli** [comment]
I'm trying to figure why this is useful. Neither module names nor
function can have Unicode characters in OTP 19. Do you have an example?

**Comment by platinumthinker** [comment]
I write their implementation ssh shell on the basis of the standard shell. I use standard expander for russian language commands

**Comment by uabboli** [comment]
Sorry, but I still don't get it...

edlin_expand:expand/1 asks the code module about names of modules and
functions, and nothing else. What am I missing? How have you managed to
get completion on command names (using edlin_expand)?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by platinumthinker** [comment]
I use edlin_expand as universal expander for commands in my cli (like clish).

**Comment by uabboli** [comment]
Still, how do you use edlin_expand, unmodified, for universal
expansion of commands, and not only for module and function names?

I don't know about clish, so that reference did not give me any clue.

**Comment by platinumthinker** [comment]
I use edlin as shell in ssh. For expand my command i use unmodified edlin_expand

**Comment by uabboli** [comment]
It has been suggested to me that you probably call edlin_expand:format_matches(). If so, please add a testcase to lib/stdlib/test/edlin_expand_SUITE.erl.

**Pull request merged**
