### PR TITLE
Implement cond expressions

### PR DESCRIPTION
**Pull request by nox**
This makes the 'cond' keyword useful and introduces an expression similar to if expressions, without guard semantics.

```erlang
cond E1 -> B1;
     ...;
     Ek -> Bk
end.
```

This code is more or less equivalent to k nested cases, with the difference that bindings from tests Ei do not spill in the subsequent Ei+1 and Bi+1 trees.

```erlang
case E1 of
    true ->
        B1;
    false ->
        case ... of
            true ->
                ...;
            false ->
                case Ek of
                    true ->
                        Bk;
                    false ->
                        error(cond_clause);
                    Other ->
                        error({badbool,Other})
                end;
            Other ->
                error({badbool,Other})
        end;
    Other ->
        error({badbool,Other})
end.
```

The current implementation may be lacking with regard to warnings, please follow up on any shortcoming.

### CODE REVIEW

**Comment by bjorng** [comment]
You do know what language changes require an EEP, don't you?

In this particular case, the EEP must describe the rules for variable scopes. Your commit message says that variable bindings will not leak to the next clause. That is a reasonable position and some people in the OTP group thinks that is the right thing to do. Other people would say that it is inconsistent with the rest of the language, because the clauses in the 'cond' are evaluated in expression context and the scope of bindings in expressions extends to the end of the function. That is also a reasonable position.

That means that the EEP must contain a clear description of the scoping rules and a good motivation why we should use those rules.

Next, in my upcoming comment, a few words about your suggested implementation.

**Comment by bjorng** [comment]
There seems to be one bug in the implementation compared to the description in the commit message. In this example:

    t() ->
        cond
            begin A = 42, false end -> x;
            begin A = 43, true end -> y
        end.

the binding of A *is* leaked from the first clause to the second.

Other than that, I would want to see a new cond_SUITE with test cases and examples of how 'cond' is used.

**Comment by bjorng** [comment]
Since we already have too many outstanding pull requests, I will close this pull request.

When you or someone else has written an EEP, you can open a new pull request.

**Comment by nox** [comment]
That was the plan, I wanted some feedback about where to add tests and whatnot. Will reopen it when it's done and I've written the damn EEP.

**Comment by mrallen1** [comment]
Hey @nox any progress on this? Or is it pretty much dead?

**Pull request closed without merging**
