### PR TITLE
fix MAC signature algo selection in TLS 1.0/1.1 only server

### PR DESCRIPTION
**Pull request by RoadRunnr**
pre TLS 1.2 server should ignore the signature_algorithms extension.
The server code would attempt to select the signature/hash algorithm
even when using TLS 1.0 or 1.1. Instead it should simply use the default
algorithm on those versions.

### CODE REVIEW

**Comment by RoadRunnr** [comment]
I know that this probably should have a unit test, but I don't really have to time to work on one. Sorry.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
You are maybe in luck, ssl_to_openssl_SUITE:basic_erlang_server_openssl_client fails on some platforms, this could be a possible cause. But I have not tried it yet, we will see.

**Comment by IngelaAndin** [comment]
Your  patch fixes the test case. But just to make sure I  added a unit test too. I will merge my version of your branch to master when it passed our nightly-tests.

**Pull request closed without merging**
