### PR TITLE
Add functions to 'code' for loading multiple modules at once

### PR DESCRIPTION
**Pull request by bjorng**
`code:atomic_load(Modules)` will load all modules at once, or fail having loaded none of them. Since we cannot guarantee the atomicity if there are modules with -on_load functions, the list of modules must not contain any modules with an -on_load function.

Also, to make it possible to put an application into an inactive state for as short time as possible, also add `code:prepare_loading/1` and `code:finish_loading/1`. They are used like this:

    {ok,Prepared} = code:prepare_loading(Modules)
      .
      .
      .
    ok = code:finish_loading(Prepared)

`code:ensure_modules_loaded/1` is useful as a pure optimization to ensure that modules that will be needed soon have been loaded. It will not reload modules that have already been loaded and
it *will* accept modules that have an -on_load function. Therefore, it does not make sense to give any atomicity guarantees.

I did consider overloading the existing `code:ensure_loaded/1` function, but rejected it because the return value is very different. Having different forms of return values depending on the types of arguments is confusing.

### CODE REVIEW

**Comment by ferd** [comment]
This is going to make a whole lot of upgrades a lot simpler. This is great.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by okeuday** [comment]
@bjorng These are very useful additions.  The only problem seems to be a general one with the code server, since none of the functions work with an explicit timeout, though internally there appears to be a timeout used by the code server.  I have seen the code server fail on a virtualized system running CT tests, without enough information to report the problem.  The failure appears to be a failure of the code server to read the file from disk within a sufficient amount of time and the value for this timeout isn't clearly specified within the code module (when I looked at it).  Is it possible to add code functions that have a timeout value as an additional parameter, to have more control of the potential for the code server to fail, when loading modules?  I am asking here because this would affect new functions too.

**Comment by bjorng** [comment]
As far a I know, the code server has no timeouts unless the `inet` loader is used (`erl -loader init`). common_test has a default timeout of 30 minutes (I think) before a test case is aborted.

Can you provide any more details?

**Comment by okeuday** [comment]
@bjorng I often have CT tests with the init_per_suite/1 function calling the reltool_util:application_start function at https://github.com/okeuday/reltool_util/blob/master/src/reltool_util.erl#L143 which does load modules when they are not already loaded (in reltool_util:module_loaded/1 at https://github.com/okeuday/reltool_util/blob/master/src/reltool_util.erl#L596 ).  I believe I have seen an exception due to the code server due to the reltool_util:module_loaded/1 usage in reltool_util:application_start in a virtualized instance running CT tests at https://travis-ci.org/CloudI/CloudI .  However, the only information available was the console output of the CT test, only showing the exception (no stack trace) and it seems the build was restarted so the output is no longer available.

Anyway, if there really is no way for the code server to timeout, that is very good and I am mistaken (it must have been CT enforcing its timeout, perhaps while being stuck waiting for a module to load).

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request closed without merging**
