### PR TITLE
HiPE: Range splitting register allocation

### PR DESCRIPTION
**Pull request by margnus1**
HiPE uses sophisticated register allocators to maximise the performance of the code it generates, but the register allocators are often unable to do much due to the large amount of function calls in the code, and any value that is live over a function call must be spilled to stack. Many operations that HiPE inline have fallbacks that use helper functions to deal with the trickier cases. Addition, for example, goes something like `if (are_fixnums(a, b)) res = a+b; else res = erlang:'+'(a, b);`, and any value live over this construct is also live over the `erlang:'+'/2` call, and is forced to stack.

_Live range splitting_ is the name of the technique used to combat these kinds of problems in register allocation. When a value cannot be allocated to a register for the entirety of its lifetime, live range splitting divides the lifetime into several parts, giving the value different names in each. This means that some of these names may be allocated to registers even if all of them cannot, and the quality of the register allocation improves.

There are two approaches to live range splitting. Either it is integrated directly into the register allocator, or it is an independent pass that is run on the program before it is fed to the register allocator.

This PR adds two different range splitters, both of the independent variety, to HiPE. The first range splitter is fast and simplistic, and is called `hipe_restore_reuse`. It attempts to eliminate fully redundant restores and spills. For example, the addition example below would, without range splitting, contain three restores of `a` and `b`. `hipe_restore_reuse` will eliminate the restores for the uses inside the if statement, by reusing the values restored for the `are_fixnums` test, thus leading to the example only needing two restores.

The second range splitter, called just `hipe_range_split`, is more sophisticated. It addition to what `hipe_restore_reuse` does, it can also insert spills before calls and restores after calls. In order to pick where to spill and restore, it considers the static branch prediction associated with branch instructions. Effectively, it tries to move stack accesses to the "cold path" of a function, unless it causes too much code size increase. In the addition example, it is considered likely for both the operands to be fixnums, and `hipe_range_split` will insert spills before the call to `erlang:'+'/2` and restores after it, allowing `a` and `b` to stay in registers for the rest of the program.

One of the reasons that two different range splitters are introduced is for the sake of compilation speed. `hipe_range_split` causes the program to be significantly more complicated to register allocate, and for enormous functions, take unacceptably long. For such functions, `hipe_range_split` automatically falls back on `hipe_restore_reuse`, which is much easier on register allocation.

### CODE REVIEW

**Comment by sverker** [comment]
What about this for release note (with just an hint of the fancy implementation details):
"Improve hipe compiler to generate better CPU register utilization in runtime by the use of 'Live Range Splitting' techniques."

**Comment by margnus1** [comment]
Sounds good, although I'm slightly confused by the "in runtime" part. I presume it means the same as "at runtime."

**Comment by sverker** [comment]
yes, "at runtime" is probably less swedish and more english.

I just wanted to make clear this improvement was wrt runtime performance
as there are other release notes about hipe compile speed.

**Comment by kostis** [comment]
Unfortunately, this pull request (most likely) breaks the HiPE compiler on x86.  Making the system with `--enable-native-libs` crashes with:

> make[1]:
> Entering directory '/home/kostis/HiPE/otp-git/lib'
> make[2]: Entering directory '/home/kostis/HiPE/otp-git/lib/stdlib'
=== Entering application stdlib
make[3]: Entering directory '/home/kostis/HiPE/otp-git/lib/stdlib/src'
 ERLC   ../ebin/dets_v9.beam
<HiPE (v 3.15.4)> Error: [hipe:864]: INTERNAL ERROR
while compiling dets_v9:free_list_to_file/6
crash reason: {badmatch,true}
  in function  hipe_x86_ra_postconditions:do_pseudo_spill_move/3 (hipe_x86_ra_postconditions.erl, line 305)
  in call from hipe_x86_ra_postconditions:do_insns/5 (hipe_x86_ra_postconditions.erl, line 50)
  in call from hipe_x86_ra_postconditions:do_bbs/5 (hipe_x86_ra_postconditions.erl, line 45)
  in call from hipe_regalloc_loop:alloc/9 (hipe_regalloc_loop.erl, line 50)
  in call from hipe_regalloc_loop:ra/7 (hipe_regalloc_loop.erl, line 25)
  in call from hipe_x86_ra:ra/2 (hipe_x86_ra.erl, line 54)
  in call from hipe_x86_main:rtl_to_x86/3 (hipe_x86_main.erl, line 59)
  in call from hipe_main:rtl_to_native/4 (hipe_main.erl, line 559)
dets_v9.erl: internal error in native_compile;
crash reason: {badmatch,true}
/home/kostis/HiPE/otp-git/make/i686-pc-linux-gnu/otp.mk:119: recipe for target '../ebin/dets_v9.beam' failed
make[3]: *** [../ebin/dets_v9.beam] Error 1
make[3]: Leaving directory '/home/kostis/HiPE/otp-git/lib/stdlib/src'
/home/kostis/HiPE/otp-git/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[2]: *** [opt] Error 2
make[2]: Leaving directory '/home/kostis/HiPE/otp-git/lib/stdlib'
/home/kostis/HiPE/otp-git/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[1]: *** [opt] Error 2
make[1]: Leaving directory '/home/kostis/HiPE/otp-git/lib'
Makefile:452: recipe for target 'libs' failed
make: *** [libs] Error 2


Same thing happens if I use `hipe:c(dets_v9).` on the shell:

> Eshell V9.0  (abort with ^G)
> 1> hipe:c(dets_v9).
<HiPE (v 3.15.4)> Error: [hipe:864]: INTERNAL ERROR
while compiling dets_v9:free_list_to_file/6
crash reason: {badmatch,true}
  in function  hipe_x86_ra_postconditions:do_pseudo_spill_move/3 (hipe_x86_ra_postconditions.erl, line 305)
  in call from hipe_x86_ra_postconditions:do_insns/5 (hipe_x86_ra_postconditions.erl, line 50)
  in call from hipe_x86_ra_postconditions:do_bbs/5 (hipe_x86_ra_postconditions.erl, line 45)
  in call from hipe_regalloc_loop:alloc/9 (hipe_regalloc_loop.erl, line 50)
  in call from hipe_regalloc_loop:ra/7 (hipe_regalloc_loop.erl, line 25)
  in call from hipe_x86_ra:ra/2 (hipe_x86_ra.erl, line 54)
  in call from hipe_x86_main:rtl_to_x86/3 (hipe_x86_main.erl, line 59)
  in call from hipe_main:rtl_to_native/4 (hipe_main.erl, line 559)
** exception exit: {badmatch,true}
     in function  hipe:run_compiler_1/4 (hipe.erl, line 689)
     in call from hipe:run_compiler/4 (hipe.erl, line 632)
     in call from hipe:c/3 (hipe.erl, line 326)
2> hipe:c(dets_v9, [no_ra_range_split]).
{ok,dets_v9}

Good news is that this is just a compiler crash (i.e., this is not a crash due to generating bad native code) and this is *x86* specific.  x86_64 works OK in everything I've tried.

**Comment by margnus1** [comment]
I've tracked the crash down to an off-by-one in the register allocators. A fix PR is incoming as soon as it passes the test suites.

**Pull request merged**
