### PR TITLE
Do not emit dialyzer warnings for compiled generated patterns

### PR DESCRIPTION
**Pull request by josevalim**
This fixes a regression in Erlang 19.0-rc where warnings
are emitted for patterns that are compiled generated.

### CODE REVIEW

**Comment by kostis** [comment]
Please provide a test for this: some Erlang code snippet that generates dialyzer warnings in 19.0-rc but did not do so in prior Erlang/OTP releases.

**Comment by josevalim** [comment]
@kostis it cannot be triggered by Erlang code snippets. We would need to either use Erlang Abstract Format (which now supported the `{generated, true}` annotation that becomes `compiler_generated`) or use Core. Is there any part of the dialyzer test suite that uses both Core or Erlang Abstract Format as its input for testing dialyzer?

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Do not emit dialyzer warnings for compiled generated patterns


----------------

I am a script, I am not human 

----------------

**Comment by josevalim** [comment]
@kostis I have included tests. I had to write the Erlang Abstract Format by hand since it cannot be generated by the Erlang compiler externally.

@OTP-Maintainer The commit message has been amended.

**Comment by bjorng** [comment]
Did you run the entire dialyzer test suite? There are failed test cases. Here is the result for the first failed test case (`map_SUITE:exact/1`):

    {test_case_failed,
                     {differ,
                         [{old,3,
                              "exact.erl:19: The variable _ can never match since previous clauses completely covered the type #{'a':=_, ...}\n"}]}}

In additition, if the `hipe` application has been skipped in the build for some reason your new test suite also fails:

    {thrown,
                     {dialyzer_error,
                         "Not a regular file: /ldisk/daily_build/19_master-opu_o_debug.2016-06-07_20/otp/lib/erlang/lib/hipe-3.15/ebin/erl_bif_types.beam\n"}}

**Comment by josevalim** [comment]
The dialyzer suite passes here. :S I am doing:

    cd releases/tests/test_server
    erl -eval "ts:run(dialyzer, [batch])."

Am I missing some important step or a better way to run tests?

**Comment by bjorng** [comment]
Your method should work.

The tests failed in our daily builds. @uabboli then verified by removing other branches that could possibly make dialyzer fail, and I finally build your branch and test suites from scratch before running the test suites. Before running the tests, I built a new PLT from scratch including erts, kernel, stdlib, and compiler.

Could you check again? Examine common_test's web pages and logs and see if there are any skipped test cases or anything else strange going on.

**Comment by bjorng** [comment]
By the way, have you checked that the correct `erl` is started?

My way to start the test suites is like this:

     (cd release/tests/test_server && $ERL_TOP/bin/erl)

and then:

     ts:run(dialyzer, [batch]).

That way, I am sure that the correct Erlang system is started. (I recall the command from the shell history.)

**Comment by josevalim** [comment]
@bjorng I have rebuilt my tests and PLT from scratches and now I get the failures. My solution is definitely wrong: there are many other occasions where all the clauses of a case is generated and we still want to emit dialyzer warnings for those.

That said, I am not sure how to fix this. Maybe we could ignore the warning for some kinds of error (for example, unmatched_clauses) but even though I am afraid we will silence warnings that we should not. I am totally open to explore any other ideas you might have but we should maybe consider that the best I can contribute to this problem is a failing test case. If that's the case, I am glad to close this and open up a bug report with the sample test case instead.

And thanks for all the hand holding on my contributions, it is really appreciated.

**Comment by bjorng** [comment]
Yes, opening a bug report seems to be the best way forward.

**Pull request closed without merging**
