### PR TITLE
Prevent zip:zip_open/1,2 from leaking ports

### PR DESCRIPTION
**Pull request by danielwhite**
The case was discovered where a parent process would exit before closing
the zip file. The result was that a port would be left open
indefinitely, as the small zip server would not detect this condition.

By comparison, the file module will close the associated port when the
parent exits for any reason. This change would make the zip module more
consistent with the semantics of similar modules.

This change is breaking for any callers expecting to pass the handle to
another process for processing (assuming it exits).

With this in mind, it may need a bit more thought with regards to:

1. Is this the best way to cope with a parent process exiting?
2. Should an equivalent of `gen_tcp:controlling_process/2` to deal with
    migrating an open zip to another process?
3. If backwards compatibility is necessary, then would it be worth
    introducing new functions without the "zip_" prefix?

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
The patch is good, can you add a line about keeping the process alive in the doc for zip_open.

**Comment by danielwhite** [comment]
Updated.

However, after looking at the equivalent documentation for the `file:open/2`, I think it might be worth updating this pull request to match its semantics more closely:

> If any process to which the IoDevice is linked terminates, the file will be closed and the process itself will be terminated.

**Comment by dgud** [comment]
Hmm do not like that you described the internals. 
Handle is just an opague data, the implementation might change in the future.
How about "The handle will be closed if the process which originally opened the archive dies."

**Comment by OTP-Maintainer** [comment]
Building the documentation failed:

    ndate "$date" --stringparam appname "stdlib" --stringparam appver "2.3" --stringparam specs_file "$specs_file" --xinclude -path /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/dtd  -path /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/dtd_man_entities /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/xsl/db_man.xsl zip.xml
      Error in zip:zip_open/-: unknown annotation Handle
    make[4]: *** [../man3/zip.3] Error 10
    make[4]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib/doc/src'
    make[3]: *** [release_docs] Error 2
    make[3]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib/doc/src'
    make[2]: *** [release_docs] Error 2
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib'
    make[1]: *** [release_docs] Error 2
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib'
    make: *** [release_docs] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by danielwhite** [comment]
The current type spec for `zip_open/1,2` indicates it is a `pid()`. If it is indeed intended to be opaque, should I update the type specs accordingly?

For instance:

```erlang
-opaque handle() :: pid().
...
-spec(zip_get(ZipHandle) -> {ok, [Result]} | {error, Reason} when
      ZipHandle :: handle(),
      Result :: file:name() | {file:name(), binary()},
      Reason :: term()).
```

**Comment by danielwhite** [comment]
Either way, the documentation has been updated as suggested.

**Comment by dgud** [comment]
Oh didn't know about the specs, yes please update the specs in a separate commit.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by danielwhite** [comment]
Forgot to mention, I've added a commit to update the specs.

**Pull request merged**
