### PR TITLE
Fix crash on init restart, embedded mode

### PR DESCRIPTION
**Pull request by lrascao**
On load handler process not being launched on a restart, NIF's
such as asn1rt_nif require it to be present for correct loading.

To reproduce issue (example for 18.0, but any version works):
- create t.rel file with content:
`{release,
    {"t", "1.0.0"},
    {erts, "6.3"},
    [{kernel, "4.0"},
     {stdlib, "2.5"},
     {sasl, "2.5"},
     {asn1, "4.0"}]}.`
- generate t.boot, t.script:
`1>  systools:make_script("t", [local]).`
- start erl in embedded mode:
`erl -boot t -mode embedded`
- perform restart:
`1> init:restart().`
- node crashes with error:
`{"init terminating in do_boot",{'cannot load',asn1rt_nif,get_files}}`

- Research

A `init:par_load_modules/2` command is executed in response to a `{primLoad, Mods}`script directive, this requests prim loader to load modules requested. A callback is passed to load the module when the binary code has been read successfully, this callback calls `init:load_mod_code/3`.
`init:load_mod_code/3` checks if the `asn1rt_nif` module is loaded, determines that it's not and then tries to load it with `erlang:load_module/2`, `{error,on_load}` is returned so a message `{loaded,Mod}` is sent to `?ON_LOAD_HANDLER`, since this process was never launched it is not registered, the sent message command fails with `badarg`. This exception in the callback is caught and propagated to `erl_prim_loader:get_files/2` that returns `{error, Mod}` thus generating the tuple `{'cannot load',Mod,get_files}`that we see in the output

### CODE REVIEW

**Comment by tuncer** [comment]
How relevant is it that asn1 (and crypto) leave the reload function in ERL_NIF_INIT undefined?

**Comment by sverker** [comment]
@tuncer It's not relevant. The NIF reload callback is a deprecated feature and is not used by init:restart. The recommended value is NULL.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
