### PR TITLE
guards-color: remove colouring of now-inexisting guards

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
We see no reason to remove these, they are still "valid" as guards.

**Comment by fenollp** [comment]
@dgud I understand they are valid for outdated code. However BEAM has no longer support for these guards in the current state of things (`erlang:is_builtin/3` returns `false` for all said guards).

Since OTP's BEAM is packaged along with the Emacs syntax-handling script, if one uses say R13B01, then one can use the elisp from that release which will correctly handle said guards. On recent versions however these guards have been removed and thus I see no reason not to remove them other than lazy/wrong tooling configuration.

Can you enlighten me please?

**Comment by dgud** [comment]
They have not been removed only deprecated.

This is still valid code and compiles (with warnings) and might be used
somewhere.
thus by not coloring it as the other guards you would just confuse people.

type(A) when atom(A) ->
    atom;
type(B) when integer(B) ->
    integer.

**Comment by fenollp** [comment]
Oh I didn't know that! Maybe `erlang:is_builtin/3`'s doc needs an update?

**Comment by fenollp** [comment]
Maybe it's time to delete that deprecated code.

**Pull request closed without merging**
