### PR TITLE
Add `lists:enumerate/3`

### PR DESCRIPTION
**Pull request by Maria-12648430**
The ability to specify a step value seems to me a logical extension to `lists:enumerate/2`.
I also condensed the docs a bit by combining all three variants of this function into one paragraph.

_(Note to self: don't forget to ask for a token for the `since` tag :sweat_smile:)_

### CODE REVIEW

**Review by bjorng — APPROVED** [review]
Looks good to me. The ticket id for the since tag is OTP-18495. Please amend your commit and force-push.

**Comment by Maria-12648430** [comment]
Done :)

**Comment by bjorng** [comment]
Thanks! Added to our daily builds.

**Comment by bjorng** [comment]
Thanks for your pull request.

**Pull request merged**
