### PR TITLE
Fix typos in lib/eldap

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by HansN** [comment]
Could you please rebase this on maint since there are documentation files affected?

**Comment by kianmeng** [comment]
> Could you please rebase this on maint since there are documentation files affected?

@HansN Done.

**Comment by HansN** [comment]
@kianmeng  Thanks, but it still reads "_...wants to merge 1 commit into erlang:_**master** _from kianmeng:fix-typos-in-lib-eldap_" on top of this page.  Did you forget to update the PR after rebasing?

**Comment by kianmeng** [comment]
@HansN Done. Please check again.

**Comment by HansN** [comment]
Thanks for the PR.

**Comment by kianmeng** [comment]
:+1: :tada:

**Pull request merged**
