### PR TITLE
ei breakage (Reported-by: Sergei Golovan)

### PR DESCRIPTION
**Pull request by tuncer**
Fix erl_interface build error on Debian/Hurd and Debian/kFreeBSD.

### CODE REVIEW

**Comment by tuncer** [comment]
I've also restored the previously omitted `defined(__ANDROID__)` check.

**Comment by tuncer** [comment]
Can we get this merged soon, so that it lands in 18.2.2?

**Comment by legoscia** [comment]
It might be possible to copy/adapt what curl is doing to check this the "proper" way: https://github.com/bagder/curl/blob/master/m4/curl-functions.m4#L2461

**Comment by tuncer** [comment]
@legoscia, yeah that's the planned long-term fix, and seeing how much code it is, I think we should merge this patch into 8.2.2 and leave the autoconf check for 19.0.

**Comment by tuncer** [comment]
@legoscia, that said, if you're certain about license compatibility, feel free to submit a patch for otp.git master with a copy of configure.in code. Maybe we should also identify other places like that and fix it properly as well.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by tuncer** [comment]
Can we get this into 18.2.4?

**Comment by tuncer** [comment]
ping?

**Comment by proxyles** [comment]
pong!

**Comment by tuncer** [comment]
@proxyles, what the status here? This is a simple build fix, correcting what I broke earlier. We've missed 18.2.2 and 18.2.3 already.

**Comment by tuncer** [comment]
@proxyles, what's the status here? This is a simple build fix, correcting what I broke earlier. We've missed 18.2.2 and 18.2.3 already.

**Comment by tuncer** [comment]
@proxyles, what's the status here? This is a simple build fix, correcting what I broke earlier. We've missed 18.2.2 and 18.2.3.

**Comment by proxyles** [comment]
I think it will show up here today or tomorrow.

**Comment by tuncer** [comment]
Thanks.

**Pull request merged**
