### PR TITLE
Missing a curly bracket

### PR DESCRIPTION
**Pull request by rustkas**
Fix missing a curly bracket.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Thank you for the PR. Could you please base it on maint, so that it can be part of the OTP-25 track.

**Comment by rustkas** [comment]
> Thank you for the PR. Could you please base it on maint, so that it can be part of the OTP-25 track.

Have done it.

**Comment by IngelaAndin** [comment]
@rustkas  you need to do a rebase of the branch that will only include your fix and not all changes that were done to master lately. Probably easiest is to bring your branch back to master and then do rebase --onto maint HEAD~1 (1 as you have one commit that is yours)

**Comment by rustkas** [comment]
@IngelaAndin I have made your suggested solution. Unfortunately I've got conflicts into other part of OTP. I'm afraid that fixing those conflicts will lead to some unexpected complications.

I think the easiest and most efficient way is to close this  PR and create a new one in maint.
I have done it successfully. [https://github.com/erlang/otp/pull/6091](https://github.com/erlang/otp/pull/6091)

**Comment by IngelaAndin** [comment]
That works too, although my suggestion was not to fix the conflicts but rather get rid of them through cherry-picking to the maint branch via rebase --onto command. But no worries I merged your new PR.

**Comment by rustkas** [comment]
> That works too, although my suggestion was not to fix the conflicts but rather get rid of them through cherry-picking to the maint branch via rebase --onto command. But no worries I merged your new PR.

I'll do that next time. 
```
> git checkout my_patch_branch
> git rebase --onto original/maint
```
Thank you for your assistance and suggestions, @IngelaAndin.

**Pull request closed without merging**
