### PR TITLE
Fix global_group.erl

### PR DESCRIPTION
**Pull request by xumingthepoet**
check #1004 for details

### CODE REVIEW

**Comment by zhird** [comment]
Hi @xumingthepoet, 

Thanks for the PR! It looks good but it would be great if you can add a test to verify this! It would save us some time and we would be able to merge this fix faster :) Can you do that?

Cheers

**Comment by xumingthepoet** [comment]
OK,  as soon as possible

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by xumingthepoet** [comment]
Hi @zhird, please have a check. I found this bug occasionally on my production environment and i don't think this module is popular to other guys or it could not exist for so long. I am glad to help if you have anything else about it. Thanks~

**Comment by zhird** [comment]
Great, thanks a lot @xumingthepoet!

We are currently closer to a master release than a maint one, so I rebased it on master and I also made some changes to get the test to work, but now it is in our nightly build and will probably be merged tomorrow if all goes well :)

Cheers!

**Comment by zhird** [comment]
Merged to master! :)

**Pull request closed without merging**
