### PR TITLE
Improve some log events from OTP

### PR DESCRIPTION
**Pull request by sirihansen**
The `report_cb` used for `gen_server` terminate reports is originally written for multi-line logging. Setting `single_line=>true` in the `logger_formatter` configuration causes newlines to be replaced by ", " and the result of this is not very good for `gen_server` terminate reports.

This pull request changes this `report_cb` to behave differently for multi-line vs single-line logging. See examples:

Multi-line:
```
=ERROR REPORT==== 28-May-2019::16:37:48.922225 ===
** Generic server <0.87.0> terminating 
** Last message in was {a,message,which,is_not,handled}
** When Server state == {state,<0.85.0>,
                               [some,data,in,stored,in,my,state],
                               <<"and a binary as well">>}
** Reason for termination ==
** {{badmatch,{a,message,which,is_not,handled}},
    [{gs,handle_call,3,[{file,"gs.erl"},{line,32}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,663}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,692}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
** Client <0.85.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},
    {gen_server,call,2,[{file,"gen_server.erl"},{line,211}]},
    {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},
    {shell,exprs,7,[{file,"shell.erl"},{line,686}]},
    {shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},
    {shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]
```

Single-line original:
```
2019-05-28T16:40:17.356553+02:00 error: ** Generic server <0.87.0> terminating , ** Last message in was {a,message,which,is_not,handled}, ** When Server state == {state,<0.85.0>,[some,data,in,stored,in,my,state],<<"and a binary as well">>}, ** Reason for termination ==, ** {{badmatch,{a,message,which,is_not,handled}},[{gs,handle_call,3,[{file,"gs.erl"},{line,32}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}, ** Client <0.85.0> stacktrace, ** [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,211}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]

```

Single-line modified:
```
2019-05-28T16:37:48.922225+02:00 error: gen_server <0.87.0> terminating, last message: {a,message,which,is_not,handled}, state: {state,<0.85.0>,[some,data,in,stored,in,my,state],<<"and a binary as well">>}, reason: {{badmatch,{a,message,which,is_not,handled}},[{gs,handle_call,3,[{file,"gs.erl"},{line,32}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,663}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,692}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}, client <0.85.0> stacktrace: [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,211}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]
```

Crash reports from `proc_lib` were earlier not much limited in size by the `chars_limit` option in `logger_formatter`. This is also improved with this PR.

### CODE REVIEW

**Comment by sirihansen** [comment]
@RaimoNiskanen I used lower case letters to resemble what the proc_lib crash report looks like. But that's probably not a good reason for making the gen_server report less readable... Wondering if I should use semicolons instead of dots, though, since this is what is used in proc_lib to separate the crasher and its neighbours.

**Comment by sirihansen** [comment]
@RaimoNiskanen On the other hand - semicolons followed by upper case letters might not look that good :-/

**Comment by sirihansen** [comment]
Just pushed a fixup for the gen_server part of @RaimoNiskanen 's suggestion. The single line output is now:
```
2019-06-14T13:37:36.512474+02:00 error: Generic server <0.97.0> terminating. Last message: {a,message,which,is_not,handled}. State: {state,<0.94.0>,[some,data,in,stored,in,my,state],<<"and a binary as well">>}. Reason: {{badmatch,{a,message,which,is_not,handled}},[{gs,handle_call,3,[{file,"gs.erl"},{line,35}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,663}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,692}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}. Client <0.94.0> stacktrace: [{gen,do_call,4,[{file,"gen.erl"},{line,167}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,211}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]}].
```
A thought I had was if I should swap the orders a bit, and put the exit reason before last message, in case `max_size` is set in the formatter (which could cause truncation of the line). Assuming that the exit reason is more important than last message and state...?

**Comment by IngelaAndin** [comment]
> 
> A thought I had was if I should swap the orders a bit, and put the exit reason before last message, in case `max_size` is set in the formatter (which could cause truncation of the line). Assuming that the exit reason is more important than last message and state...?

Humm ... I think it is really hard to priorities between the entries as it so  much depends. But when I think about it I think the exit reason and the last message in conjunction is more important than the state. And if I have to choose between exit reason an last message probably the exit reason as it is sort of the starting point to finding out what went wrong.

**Comment by sirihansen** [comment]
Swapped the order of information fields in the `gen_server` termination reports, as described in [this comment](https://github.com/erlang/otp/pull/2265#issuecomment-502077089). 

And changed `"neighbours: <number>"` to `"neighbourts: <pid-list>"` in `proc_lib` crash reports, when `chars_limit` is set to an integer.

**Comment by sirihansen** [comment]
Rebased and squashed. And added an example test case for proc_lib:report_cb/2 when chars_limit is set.

**Comment by garazdawi** [comment]
Leaving some notes for myself:
* Before merging I'd like to do the same modifications to proc_lib, supervisor and all the other gen_ things.
* Change so that the depth and limit budget is spent on all terms equally, not first come first serve. `proc_lib` already does this. Would this be a nice thing to have in `io_lib:format/3`?
* I think we should have the format of the reports to be as similar to how the default `single_line` formatter works as possible. i.e. small letters to start with and use `,` to separate terms. I see `single_line` to be mainly a machine read mode. No matter how good we are at formatting, it will not be possible to make the below readable:
  ```
  =ERROR REPORT==== 26-Sep-2019::16:25:59.744050 ===
  Generic server tst terminating. Reason: {{badmatch,{error,{already_started,<0.99.0>}}},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,453}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]}. Last message: {'EXIT',<0.97.0>,{{badmatch,{error,{already_started,<0.99.0>}}},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,453}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]}}. State: [[{'$initial_call',{tst,init,1}},{'$ancestors',[<0.97.0>]}],{state}].
  =CRASH REPORT==== 26-Sep-2019::16:25:59.744707 ===
  crasher: initial call: tst:init/1, pid: <0.99.0>, registered_name: tst, exit: {{{badmatch,{error,{already_started,<0.99.0>}}},[{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,453}]},{shell,exprs,7,[{file,"shell.erl"},{line,686}]},{shell,eval_exprs,7,[{file,"shell.erl"},{line,642}]},{shell,eval_loop,3,[{file,"shell.erl"},{line,627}]}]},[{gen_server,decode_msg,9,[{file,"gen_server.erl"},{line,432}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}, ancestors: [<0.97.0>], message_queue_len: 1, messages: [{'EXIT',<0.97.0>,normal}], links: [], dictionary: [], trap_exit: true, status: running, heap_size: 6772, stack_size: 27, reductions: 8504; neighbours:
  ```
  So better to make it easier to read by machines.

**Comment by KennethL** [comment]
I think the one line version is better than the old one but I am wondering what the syntax is for the one liner?
As I see it it should be a regular syntax which is easy to parse or prettyprint afterwords.
It could be json format or it could be the printed format of a possible nested Erlang map. Now I think it is something almost following a regular syntax (correct me if I am wrong).

What bothers me is the "Generic server <0.97.0> terminating" and "Client <0.84.0> stacktrace" where I think it would be better to have something like Generic_server_terminating: <0.97.0> , ....
and Client: <0.84.0> , stacktrace: ...... .

But I think the suggested format is ok and maybe it is yet another format if we should make it easy parse-able like printed Erlang Maps or Json.

**Comment by garazdawi** [comment]
We haven't made any attempts at making this easy to parse. The changes we have been are to make it easier for a human to read the single-line format. If you want to be able to parse the log output then you should use a logger_formatter that either output to json (as you say) or something like https://github.com/ferd/flatlog.

**Pull request merged**
