### PR TITLE
Fix cover crash

### PR DESCRIPTION
**Pull request by lpgauth**
Cover crashes when it encounters a beam file without a declared main file.

e.g. generated dtl templates

before the patch:

    1> rp(cover:compile_beam_directory("/Users/lpgauth/Git/project/_build/test/lib/project/ebin")).

    =ERROR REPORT==== 5-Nov-2015::16:05:17 ===
    Error in process <0.44.0> with exit value:
    {function_clause,[{cover,find_main_filename,
                             [[]],
                             [{file,"cover.erl"},{line,1461}]},
                      {cover,transform,4,[{file,"cover.erl"},{line,1454}]},
                      {cover,do_compile_beam,3,[{file,"cover.erl"},{line,1385}]},
                      {cover,main_process_loop,1,
                             [{file,"cover.erl"},{line,626}]}]}
    ** exception exit: {function_clause,[{cover,find_main_filename,
                                                [[]],
                                                [{file,"cover.erl"},{line,1461}]},
                                         {cover,transform,4,[{file,"cover.erl"},{line,1454}]},
                                         {cover,do_compile_beam,3,[{file,"cover.erl"},{line,1385}]},
                                         {cover,main_process_loop,1,
                                                [{file,"cover.erl"},{line,626}]}]}
         in function  cover:call/1 (cover.erl, line 541)
         in call from cover:compile_beams/2 (cover.erl, line 348)

after the patch is applied:

    2> rp(cover:compile_beam_directory("/Users/lpgauth/Git/project/_build/test/lib/project/ebin")).
    [{error,{no_main_file,"/Users/lpgauth/Git/project/_build/test/lib/project/ebin/template_dtl.beam"}},
     {ok,test}]
    ok

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lpgauth** [comment]
Anything I can do to move this forward?

**Comment by proxyles** [comment]
Not at this time.
We are mid release, and as far as I can see that team has not been able to look at your patch yet

**Comment by sirihansen** [comment]
Hi - I'm sorry for the late answer. Since this patch is based on a very old version of cover, I have now re-implemented it on the latest maint branch, and added a test case. It will be included in the next release, which is probably OTP-18.3.

Thanks for your  contribution!

**Comment by lpgauth** [comment]
@sirihansen great, thanks!

**Comment by lpgauth** [comment]
can you point to the commit once it's merged in the public tree? cheers

**Comment by sirihansen** [comment]
I will. Just added it til the daily builds now, and will let it run for a couple of days before merging.

**Comment by sirihansen** [comment]
I just added this to the maint (and master) branch, so it will be included in the next push to github (probably today)

**Comment by NobbZ** [comment]
Should this problem be fixed in 18.3?

Since it is still not working for our project ([disco-framework](https://github.com/disco-framework/disco)). Or is there something more to do than just setting `{cover_enabled, true}` in rebar.conf? Is there something we need to change elsewhere?

**Comment by sirihansen** [comment]
The crash should have been corrected with [this commit](https://github.com/erlang/otp/commit/064990cac9e5012aafba1169d9e098a7140d812a). Note that the correction only does what the description above says - it makes sure that there is an error return instead of a crash.

**Pull request closed without merging**
