### PR TITLE
inets: Forward connection errors with https proxy

### PR DESCRIPTION
**Pull request by qrilka**
httpc should return meaningful error reason disregarding whether
it is being used with http proxy or not

### CODE REVIEW

**Comment by qrilka** [comment]
The error reason I've set in this PR looked the most logical (they look like the one we get with no proxy):
```
3> httpc:request("https://dl.sciencesocieties.org/publications/jeq/abstracts/22/3/JEQ0220030409").

=ERROR REPORT==== 24-Jul-2015::10:54:39 ===
SSL: certify: ssl_handshake.erl:415:Fatal error: certificate unknown
{error,{failed_connect,[{to_address,{"dl.sciencesocieties.org",
                                     443}},
                        {inet,[inet],{tls_alert,"certificate unknown"}}]}}
4> httpc:set_options([{proxy,{{"localhost",8080},[]}}]).
ok
....
7> httpc:request("https://dl.sciencesocieties.org/publications/jeq/abstracts/22/3/JEQ0220030409").

=ERROR REPORT==== 24-Jul-2015::12:44:56 ===
SSL: certify: ssl_handshake.erl:415:Fatal error: certificate unknown
{error,{failed_connect,[{to_address,{"dl.sciencesocieties.org",
                                     443}},
                        {tls,[],{tls_alert,"certificate unknown"}}]}}
```

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Would you kindly add a test for this?

**Comment by qrilka** [comment]
I have thought about it and tried already to get something for another proxy-related PR but httpc_proxy_SUITE requires not a trivial setup so that at least will require some time to get implemented

**Comment by qrilka** [comment]
@proxyles test created
Are there any plans to make proxy tests easier to set up or at least add some line how to set it up?
I've spent some hours before I have realized that the code is for Apache 2.2 while Ubuntu has 2.4 for Trusty...

**Comment by OTP-Maintainer** [comment]
Fetching pull requests from github failed:

    Host key verification failed.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.



----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I have merged this PR. I think that  there is room for improvement of the test suite. However it is far from the top of the backlog. If anyone wants to contribute feel free  to do so.

**Comment by qrilka** [comment]
@IngelaAndin sorry for asking but where was it merged into?

**Comment by IngelaAndin** [comment]
18.1 (not visible on github yet)

**Pull request closed without merging**
