### PR TITLE
Eliminate crash for nested guards in record initialization

### LINKED ISSUE #8190: [erlc] internal error in erl_expand_records:in_guard/1
**Describe the bug**
Running `erlc` on the following code:
```erlang
-record(r0, {rf0}).
-record(r1, {rf1 = (#r0{rf0 = #{ok => ok || ok}})}).

f3() ->
    <<0 || #r1{}>>.
```
causes the following crash:
```
internal error in pass expand_records:
exception error: no match of right hand side value true
  in function  erl_expand_records:in_guard/1 (erl_expand_records.erl, line 215)
  in call from erl_expand_records:lc_tq/3 (erl_expand_records.erl, line 560)
  in call from erl_expand_records:expr/2 (erl_expand_records.erl, line 304)
  in call from erl_expand_records:expr_list/2 (erl_expand_records.erl, line 473)
  in call from erl_expand_records:expr_list/2 (erl_expand_records.erl, line 474)
  in call from erl_expand_records:expr/2 (erl_expand_records.erl, line 308)
  in call from erl_expand_records:expr_list/2 (erl_expand_records.erl, line 473)
  in call from erl_expand_records:expr_list/2 (erl_expand_records.erl, line 474)
```

**Affected versions**
- master

### PR DESCRIPTION
**Pull request by bjorng**
Closes #8190

### CODE REVIEW

**Comment by RobinMorisset** [comment]
Thanks for the fix.
It reduced by 100x the number of failing testcases, but there is one that remains and it changed its error message:
```erlang
-record(r0, {rf0}).
-record(r1, {
    rf1 = fun
        (0.0) ->
            (list_to_bitstring(ok))#r0.rf0;
        (_) when ok ->
            ok
    end
}).

f() ->
    <<0 || (#r1{})>>.
```
still fails, and now its error message is
```
Function: f/0
/home/rmorisset/minimized/test7949.erl: internal error in pass core_to_ssa:
exception error: no match of right hand side value {b_remote,{b_literal,erlang},{b_literal,list_to_bitstring},1}
  in function  beam_core_to_ssa:call_cg/5 (beam_core_to_ssa.erl, line 2788)
  in call from beam_core_to_ssa:guard_cg/3 (beam_core_to_ssa.erl, line 2726)
  in call from beam_core_to_ssa:guard_cg/3 (beam_core_to_ssa.erl, line 2720)
  in call from beam_core_to_ssa:guard_clause_cg/3 (beam_core_to_ssa.erl, line 2701)
  in call from beam_core_to_ssa:match_cg/3 (beam_core_to_ssa.erl, line 2403)
  in call from beam_core_to_ssa:match_cg/3 (beam_core_to_ssa.erl, line 2404)
  in call from beam_core_to_ssa:cg/2 (beam_core_to_ssa.erl, line 2357)
  in call from beam_core_to_ssa:cg_fun/2 (beam_core_to_ssa.erl, line 2319)
```
I don't know whether it is a related bug, or a different one that was masked by the issue in erl_expand_records.

**Comment by bjorng** [comment]
I've updated the pull request to fix the second bug too.

**Comment by RobinMorisset** [comment]
Two other related crashes were found overnight:
```erlang
-record(r0, {rf0}).
-record(r1, {
    rf0 = {
        ((ok)#r0{})#r0.rf0,
        case ok of
            _ when ok ->
                ok
        end
    }
}).

f() ->
    #{ok => ok || (#r1{})}.
```
and
```erlang
-record(r0, {rf0}).
-record(r1, {
    rf0 =
        (begin
            ((_ = ok)#r0.rf0),
            (try
                ok
            catch
                _ when ok ->
                    ok
            end)
        end)
}).

f() ->
    #{ok => ok || (#r1{})}.
```
crash with this PR with
```
Function: f/0
/home/rmorisset/minimized/test185701.erl: internal error in pass core:
exception error: no function clause matching v3_core:unforce_tree(
... [very big expression I'm omitting] ...
)
  in function  v3_core:unforce/3 (v3_core.erl, line 593)
  in call from v3_core:force_booleans/4 (v3_core.erl, line 545)
  in call from v3_core:gexpr/3 (v3_core.erl, line 370)
  in call from v3_core:gexpr_top/2 (v3_core.erl, line 357)
  in call from v3_core:guard/2 (v3_core.erl, line 344)
  in call from v3_core:clause/2 (v3_core.erl, line 306)
  in call from v3_core:clauses/2 (v3_core.erl, line 298)
```
Without the PR, they crash with the same error message as the original testcase.

**Comment by bjorng** [comment]
I've force-pushed another update to fix the last two crashes.

**Pull request merged**
