### PR TITLE
erts: Fix so that quotes are respected in erlexec args files

### PR DESCRIPTION
**Pull request by garazdawi**
Before this fix any double space ('a  b') would be stripped to a single space even if quoted.

### CODE REVIEW

**Comment by okeuday** [comment]
This fixes [ERL-1051](https://bugs.erlang.org/browse/ERL-1051).  Works with " quotes as expected.

**Comment by okeuday** [comment]
@garazdawi After testing with this change merged into master @ https://github.com/erlang/otp/commit/0dc1a5522657d14a95954af902611748216c7a82 (locally) I am unable to start a release with more complex command-line usage (I confirmed that things work fine without the current change here).  The error I get is:

    {"could not start kernel pid",application_controller,"error in config file \"./.config\" (none): configuration file not found"}

So, I am not sure what the problem with the change here is, but it doesn't appear to be ready to merge.  My command-line (for executing a build of https://github.com/CloudI/CloudI/) is similar to:

    /.../install_test1/lib/cloudi-1.7.5/erts-10.5.3/bin/erlexec -boot /.../install_test1/lib/cloudi-1.7.5/releases/1/cloudi -config /.../install_test1/lib/cloudi-1.7.5/etc/vm.config -args_file /.../install_test1/lib/cloudi-1.7.5/etc/vm.args -mode embedded -shutdown_time 65000 -- console start

**Comment by garazdawi** [comment]
Should be fixed now, please test it again.

**Comment by okeuday** [comment]
@garazdawi The change works fine now.  Thanks for the fix!

**Pull request merged**
