### PR TITLE
HiPE: Optimise receives matching unique references

### PR DESCRIPTION
**Pull request by margnus1**
With the simplification to this optimisation in BEAM by #1626, it is now almost trivial to implement in HiPE.

### CODE REVIEW

**Comment by fenollp** [comment]
```
ssl_connection.erl:2009: Matching of pattern {'server_ecdhe_psk_params', _, {'server_ecdh_params', ECCurve, _}} tagged with a record name violates the declared type of #server_srp_params{srp_n::binary(),srp_g::binary(),srp_s::binary(),srp_b::binary()}
```

I really wish Dialyzer would pretty print records with the shell's rr/rp... Any objections @kostis ?

**Comment by bjorng** [comment]
This PR did not cause the dialyzer failure. The failure is caused by a previous merge from maint to master.

**Comment by kostis** [comment]
I am not sure whether off-topic comments/wishes in pull requests are a good idea, but since this one apparently contains some, here are some more:

1. I think that merges should not happen without first checking that all tests pass.

2. It's high time that all Erlang/OTP members learn to first create pull requests rather than pushing directly to 'maint' / 'master'.  (Yes, it takes some more time, but it's a good thing to do.)

These are my wishes.

As to the suggestion/wish by @fenollp, if I understand the dialyzer error message right, note that it is as it should be.  It says that the code is trying to match with a tuple, which is tagged by a record tag, but it does not contain as many fields as the record is expected to have.  Also, note that (in the same dialyzer message) dialyzer *is* using #record notation in its printout.  In any case, as @bjorng pointed out, the warning here is created by the repo being in an inconsistent state, so it's perhaps not worth discussing it more.

**Comment by mikpe** [comment]
LGTM

**Pull request merged**
