### PR TITLE
os_mon: Implement cpu_sup:util/0,1 for FreeBSD

### PR DESCRIPTION
**Pull request by wmalik**
This pull request has the following changes:

 - Add util_measure function to lib/os_mon/c_src/cpu_sup.c for FreeBSD
 - Update cpu_sup.erl to run the port driver on FreeBSD
 - Update tests
 - Update docs

### CODE REVIEW

**Comment by wmalik** [comment]
Sure.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
PR #528 has been merged to master. Please rebase this PR to master.

**Comment by johannesh** [comment]
@psyeugenic, rebased onto master: https://github.com/erlang/otp/issues/746 Feel free to close this one as it's based on maint and thus off by 1840 commits.

**Pull request closed without merging**
