### PR TITLE
stdlib: Export all types used in supervisor API

### PR DESCRIPTION
**Pull request by mhssler**

### CODE REVIEW

**Comment by mhssler** [comment]
Ping?

**Comment by uabboli** [comment]
We usually export types on a case by case basis, and only when there
are good reasons for exporting the types. You've mentioned all types
under the DATA TYPES header, and it might be a bit too generous. If
you can provide use-cases for (some of) the types, it'll be easier for
us to decide if more types should be exported from the supervisor
module.

**Comment by mhssler** [comment]
I made this PR because I was missing supervisor:startlink_ret() and supervisor:sup_ref(). But then I though that someone else might need the rest of them. Something like this: 

```
-module('sup-ref-example-pr1767').

-export([start_child/3, start_link/0]).

-type type() :: atom().

-spec start_child(supervisor:sup_ref(), supervisor:child_id(), atom()) ->
                         supervisor:startchild_ret().
start_child(Sup, Id, Type) ->
    ChildSpec = #{id       => Id,
                  start    => get_mfa(Type),
                  restart  => temporary,
                  shutdown => get_shutdown(Type),
                  type     => worker},
    supervisor:start_child(Sup, ChildSpec).

-spec start_link() -> supervisor:startlink_ret().
start_link() ->
    supervisor:start_link(?MODULE, []).

-spec get_shutdown(type()) -> supervisor:shutdown().
get_shutdown(foo) ->
    brutal_kill;
get_shutdown(_) ->
    5000.

-spec get_mfa(type()) -> supervisor:mfargs().
get_mfa(foo) ->
    {foo, bar, []};
get_mfa(_) ->
    {gazonk, gurka, undefined}.
```

Yields:

```
$ dialyzer sup-ref-example-pr1767.erl 
  Checking whether the PLT /home/test/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
Unknown types:
  supervisor:startlink_ret/0
  supervisor:sup_ref/0
 done in 0m0.59s
done (passed successfully)
$ 
```

With this PR:

```
$ dialyzer sup-ref-example-pr1767.erl 
  Checking whether the PLT /home/test/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis... done in 0m0.60s
done (passed successfully)
$ 
```

**Comment by fenollp** [comment]
>   Proceeding with analysis... done in 0m0.60s

Nice. Dialyzer's time reporting may need some fixing.

**Comment by uabboli** [comment]
OTP Technical Board has begun discussing guidelines for exporting
types. It's hard to give precise advice, but as indicated in my first
comment, one should be restrictive when exporting types. The closest
to a recommendation we've come up with so far is this: if the user has
a reason to declare the type, it should be exported.

When it comes to the supervisor module, I think we can export
startlink_ret/0, startlink_err/0, and startchild_err/0. More types can
be exported later, if the need arises.

**Comment by uabboli** [comment]
I added a few types and committed 887eb6ee7cb44df0c8f02c5b8e8455bc96b83b33 into master.

**Pull request closed without merging**
