### PR TITLE
Emacs: add test-erlang-mode

### PR DESCRIPTION
**Pull request by johanclaesson**
This script tests only very basic stuff.  Mainly that erlang.el can be loaded at all.

Note that this script will fail until https://github.com/erlang/otp/pull/1948 is merged. Case in point.

It might be nice if this script could be called from the main test machinery.  But i don't know anything about that so i don't know if it is a good idea.  The option -f maybe should be used then so that it do not fail if there is no suitable emacs version available.

### CODE REVIEW

**Comment by johanclaesson** [comment]
Alternatively https://github.com/erlang/otp/pull/1942 will also make the test script succeed (i closed 1948 since it is identical to 1942).

**Comment by velimir0xff** [comment]
It'd be great to run the script as part of CI process (PR builder?).

**Comment by dgud** [comment]
I would prefer if you added the tests to emacs_SUITE.erl in tools/test.
There is an ```indent/1``` test that you should be able to base the tests off.

**Comment by dgud** [comment]
I thought something more like the commit I pushed.
If you like it, can you squash some commits and rebase ontop of the maint branch.

**Comment by johanclaesson** [comment]
Well, let's discuss a bit before we continue.  There are pros and cons
i guess.  And mostly due to personal preferences.  For me it is more
convenient to run a bash script.  Running the script standalone takes
about 2 seconds which is a decently quick turnaround.  Running a TS
suite seem to me like a roundabout way in comparison.

I understand the value of that the tests are triggered from the
emacs_SUITE in order to tie it in with the CI machinery.  But i prefer
a minimal suite testcase that just calls the bash test script.

One idea with the test-erlang-mode script is that it could work as a
quick smoke test for pull requests.  And to run a shell script seem to
me a reasonable requirement or recommendation to do before posting a
pull request.  To build and run testcases in a custom test framework
on the other hand seem a bit much to put on a potential elisp
contributor.

What do you see as the advantages to have the test logic in
emacs_SUITE instead of test-erlang-mode?

In particular i don't understand the reasons for the moving of
erlang-test.el to emacs_SUITE_data.  I think that erlang-test.el
should be distributed together with the other elisp files.  The
emacs_SUITE is one way to tell emacs to run the tests in
erlang-test.el.  But one can also tell emacs directly to run them and
that possibility should not be blocked.

**Comment by johanclaesson** [comment]
Well, my mention of "personal preference" was a confession, not meant
as an argument or excuse. :)

In particular i personally have no problem to run the emacs_SUITE on
my pull requests now that i know it exist.  But if we look at all
current and all potential contributors to OTP elisp then i estimate
that the average person would find it easier to execute a shell script
compared to running a suite in common_test.  That have to count for
something.

These elisp files happen to live in a erlang based repository.  But it
is still elisp and i think it is a bit overzealous to apply all
repository-local rules to them.  Since the rules were designed with
erlang code in mind.

If anyone would care about Windows then at least the following would
need to be ported to pure erlang: os:cmd(["diff ", Orig, " ", File]),
os:cmd("emacs --version | head -1") and os:cmd(Cmd ++ " ; echo $?").
I think we can agree that would be a waste of time.  Since emacs_SUITE
already calls inline bash expressions it might as well call a bash
script on file.

Anyway, if you decide to move the test-erlang-mode script into
emacs_SUITE then i will try to run it on new pull requests.  But i
will keep test-erlang-mode outside the repo for my own usage.

I have rebased to maint but i will not squash your changes into mine
since i oppose some of them.

You are right that erldoc.el works in later versions of Emacs 24.  It
depends on cl-lib which was introduced in 24.3.

Sounds good to add erlang-test.el in the Makefile.

These two issues and some other minor things were added in a commit on
top of yours (this one you can squash into your commit if you prefer).

I did not have any luck with the provided commands [1].  But what i
would really like is a script that runs only the emacs_SUITE and
return non-zero if any test fails.  For now i use the hack [2] which calls the
escript [3].  But this forces me to determine success or failure by
staring at a browser.  How can i make the escript return non-zero if
any test failed?


[1]
```
goblin (otp:dgud-test)  0:002 p/lib/tools/test 0$ erl
Erlang/OTP 22 [DEVELOPMENT] [erts-10.0.8] [source-0348488330] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.0.8  (abort with ^G)
1> c(emacs_SUITE).
{ok,emacs_SUITE}
2> emacs_SUITE:test([]).
** exception error: undefined function emacs_SUITE:test/1
3> emacs_SUITE:Test([]).
* 1: variable 'Test' is unbound
4> 
```

[2]
```bash
#!/bin/bash

set -e

cd ~/build/otp

export ERL_TOP="$PWD"
export PATH="$ERL_TOP/bin:$PATH"

pushd lib/tools/test
echo '{suites,"../tools_test",[emacs_SUITE]}.' > tools.spec
popd

./otp_build tests

pushd release/tests/test_server
escript $(dirname $0)/otp-test.escript
popd

pushd lib/tools/test
git checkout tools.spec
popd

firefox "$ERL_TOP/release/tests/test_server/index.html"
```


[3]
```erlang
#!/usr/bin/env escript

main([]) ->
    ts:install(),
    ts:run(tools, [batch]).
```

**Comment by johanclaesson** [comment]
> I expect people that modify the elisp code for erlang have some
> knowledge in erlang.
> 
> You where supposed to replace the variable `Test` with a testcase name
> in the example I provided, I thought that was obvious, my bad.

Well, it seem like one of those people (me) do not have enough such
knowledge. :)

> You can probably run the whole suite from the command line with
> `ct_run` script, I personally don't use that so I don't know how nor
> if it sets the exit status.

Awesome.  It does have a sensible exit status and it takes away a lot
of the pain i feel about CT.

**Comment by johanclaesson** [comment]
Is there something more that needs to be done with this pull request?
Just checking if you are waiting for me to do something.

**Comment by dgud** [comment]
Nope, I'm trying to get my erlang code through CI :-)
Will merge today if the tests have gone well.

**Comment by dgud** [comment]
Thanks.
Merged to maint (and master).

**Pull request closed without merging**
