### PR TITLE
first stab at fixing index_[read|match_object] w plugins

### PR DESCRIPTION
**Pull request by uwiger**
Re. https://bugs.erlang.org/browse/ERL-556

A fix for `mnesia:index_match_object/3` also added: simply that it recognizes a plugin name and then reverts to a simple `match_object()`, much like if the index attribute position contains a variable in the match pattern.

No test suite additions yet. The following mini-test did pass, though:

```erlang
-module(ixlib).

-export([value_elems/3,
         test/0, test1/0]).
-compile(export_all).

value_elems(_Storage, _Tab, {_, _, L}) when is_list(L) ->
    L;
value_elems(_, _, _) ->
    [].

test() ->
    mnesia:start(),
    mnesia_schema:add_index_plugin({ve}, ?MODULE, value_elems),
    mnesia:create_table(t, [{type,ordered_set},{index,[{ve}]}]),
    fill_table(t),
    test1(t).

test1() ->
    test1(t).

test1(t) ->
    ok = test_dirty_index(t),
    ok = mnesia:activity(async_dirty, fun() -> test_index(t) end),
    ok = mnesia:activity(sync_dirty, fun() -> test_index(t) end),
    ok = mnesia:activity(transaction, fun() -> test_index(t) end),
    ok = mnesia:activity(sync_transaction, fun() -> test_index(t) end),
    fill_table(t),
    ok = mnesia:activity(async_dirty, fun() -> test_index2(t) end),
    ok = mnesia:activity(sync_dirty, fun() -> test_index2(t) end),
    ok = mnesia:activity(transaction, fun() -> test_index2(t) end),
    ok = mnesia:activity(sync_transaction, fun() -> test_index2(t) end),
    fill_table(t),
    ok = mnesia:activity(async_dirty, fun() -> test_index3(t) end),
    ok = mnesia:activity(sync_dirty, fun() -> test_index3(t) end),
    ok = mnesia:activity(transaction, fun() -> test_index3(t) end),
    ok = mnesia:activity(sync_transaction, fun() -> test_index3(t) end),
    fill_table(t),
    ok = test_dirty_index_match_obj(t),
    ok = mnesia:activity(sync_dirty, fun() -> test_index_match_obj(t) end),
    ok = mnesia:activity(async_dirty, fun() -> test_index_match_obj(t) end),
    ok = mnesia:activity(transaction, fun() -> test_index_match_obj(t) end),
    ok = mnesia:activity(sync_transaction, fun() -> test_index_match_obj(t) end).


fill_table(t) ->
    [mnesia:dirty_write({t,N,[N-1,N,N+1]}) || N <- lists:seq(1,10)].

test_dirty_index(t) ->
    [{t,2,[1,2,3]},
     {t,3,[2,3,4]},
     {t,4,[3,4,5]}] = mnesia:dirty_index_read(t,3,{ve}),
    ok.

test_index(t) ->
    [{t,2,[1,2,3]},
     {t,3,[2,3,4]},
     {t,4,[3,4,5]}] = mnesia:index_read(t,3,{ve}),
    ok.

test_index2(t) ->
    mnesia:write({t,3,[2,4]}),
    [{t,2,[1,2,3]},
     {t,4,[3,4,5]}] = mnesia:index_read(t,3,{ve}),
    ok.

test_index3(t) ->
    mnesia:write({t,3,[2,3,4]}),
    mnesia:delete({t,3}),
    [{t,2,[1,2,3]},
     {t,4,[3,4,5]}] = mnesia:index_read(t,3,{ve}),
    ok.

test_dirty_index_match_obj(t) ->
    [{t,3,[2,3,4]}] = mnesia:dirty_index_match_object(t,{t,3,'_'},{ve}),
    ok.

test_index_match_obj(t) ->
    [{t,3,[2,3,4]}] = mnesia:index_match_object(t,{t,3,'_'},{ve},read),
    ok.
```

### CODE REVIEW

**Comment by dgud** [comment]
Please add the testcase..

**Comment by dgud** [comment]
ping

**Comment by uwiger** [comment]
I've been a bit busy, and haven't had time to complete the test suite.

BR,
Ulf

Den mån 13 aug. 2018 kl 14:51 skrev Dan Gudmundsson <
notifications@github.com>:

**Comment by ECrownofFire** [comment]
I've been trying this patch (because I'm impatient) and noticed that it actually breaks `mnesia:(dirty_)match_object` in many cases because `mnesia:remote_dirty_match_object/3` can't handle index plugins. Simple enough fix, just needs a clause to skip past `{_,_,_}` in `PosList`.

**Comment by uwiger** [comment]
As noted in bugs.erlang.org

I have been working on a leveled-based mnesia backend, and put together a test suite that actually fails on vanilla OTP 21, but passes with my (updated) fixes.

https://github.com/aeternity/mnesia_leveled/pull/1

The critical test is:
https://github.com/aeternity/mnesia_leveled/blob/f579789b516fa92110491ef9e52e89f26596ab30/test/mnesia_leveled_indexes.erl

The problem with `dirty_match_object()` is also addressed.

**Comment by uwiger** [comment]
Squashed and rebased against current master

**Comment by uwiger** [comment]
Rebased again and force-pushed

**Comment by dgud** [comment]
The new code added in mnesia.erl is not covered by test when running coverage tests.

The whole block of 'add_ix_match' and the second clause of 'add_ix_match' is not covered,
can you please take a look.

**Comment by dgud** [comment]
Thanks looks good to me, can you squash the commits to one.

**Comment by uwiger** [comment]
Squashed and rebased against master

**Pull request merged**
