### PR TITLE
feat: add type specs to gen_server

### PR DESCRIPTION
**Pull request by pouriya**

### CODE REVIEW

**Comment by ferd** [comment]
If those are being revisited, I'm curious if it'd be worth having types such as `-type noreply(T) :: {noreply, T}` and `-type reply(R, S) :: {reply, R, S}` that would allow stricter typing by the callback by parametrizing things. I.e. assume that the spec for `handle_reply` is:

```erl
-type handle_call_result() :: handle_call_result(term(), term(), term(), term()).
-type handle_call_result(StateT) :: handle_call_result(StateT, term(), term(), term()).
-type handle_call_result(StateT, ReplyT) :: handle_call_result(StateT, ReplyT, term(), term()).
-type handle_call_result(StateT, ReplyT, StopT) :: handle_call_result(StateT, ReplyT, StopT, term()).
-type handle_call_result(StateT, ReplyT, StopT, ContinueT) ::
                              {reply, ReplyT, StateT} 
                            | {reply, ReplyT, StateT, timeout()}
                            | {reply, ReplyT, StateT, hibernate}
                            | {reply, ReplyT, StateT :: term(), {continue, ContinueT}}
                            | {noreply, StateT} 
                            | {noreply, StateT, timeout()}
                            | {noreply, StateT, hibernate}
                            | {noreply, StateT, {continue, ContinueT}}
                            | {stop, StopT, ReplyT, StateT} 
                            | {stop, StopT, StateT}.
```

which could even be broken down further (with each subtype exported) such as:

```erl
-type reply() :: reply(term(), term(), term()).
-type reply(StateT, ReplyT) :: reply(StateT, ReplyT, term()).
-type reply(StateT, ReplyT, ContinueT) ::
                              {reply, ReplyT, StateT} 
                            | {reply, ReplyT, StateT, timeout()}
                            | {reply, ReplyT, StateT, hibernate}
                            | {reply, ReplyT, StateT :: term(), {continue, ContinueT}}.

-type noreply() :: noreply(term(), term()).
-type noreply(StateT) :: noreply(StateT, term()).
-type noreply(StateT, continueT) ::
                              {noreply, StateT} 
                            | {noreply, StateT, timeout()}
                            | {noreply, StateT, hibernate}
                            | {noreply, StateT, {continue, ContinueT}}.

-type stop() :: stop(term(), term(), term()).
-type stop(StateT, StopT) :: stop(StateT, StopT, term()).
-type stop(StateT, StopT, ReplyT) ::
                              {stop, StopT, ReplyT, StateT} 
                            | {stop, StopT, StateT}.

-type handle_call_result() :: handle_call_result(term(), term(), term(), term()).
-type handle_call_result(StateT) :: handle_call_result(StateT, term(), term(), term()).
-type handle_call_result(StateT, ReplyT) :: handle_call_result(StateT, ReplyT, term(), term()).
-type handle_call_result(StateT, ReplyT, StopT) :: handle_call_result(StateT, ReplyT, StopT, term()).
-type handle_call_result(StateT, ReplyT, StopT, ContinueT) ::
                              reply(ReplyT, StateT, ContinueT)
                            | noreply(StateT, ContinueT)
                            | stop(StateT, StopT, ReplyT).

```

the objective being that someone is now able to typespec things such as:

```erlang
-spec handle_call(local_messages(), gen_server:reply(), state()) -> gen_server:reply(state(), ok | {error, _}).
``` 
and hopefully make it clear that it is never expected from that call to actually stop or ignore a message.

That being said I'm not sure that in practice Dialyzer would be good enough to deal with parametrized type and find issues with this accurately. My understanding was that callback attributes would allow to do the analysis of callback functions without needing to annotate them to be annotated, but I kind of like the idea of being able to be more specific in my own code to find even more.

**Comment by Pouriya-Jahanbakhsh** [comment]
Actually I saw parameterized types in `gen_statem` and they were not very readable (at least for me). But if you think it's better to make them parameterized (for dialyzer, readability, etc), I will change them.

**Comment by Pouriya-Jahanbakhsh** [comment]
Should I put `_ = ` before these lines:
```text
application_controller.erl:1014: Expression produces a value of type 
          {_, _}, but this value is unmatched

application_controller.erl:1962: Expression produces a value of type 
          'ok' | {_, _}, but this value is unmatched

beam_lib.erl:1069: Expression produces a value of type 
          {_, _}, but this value is unmatched

beam_lib.erl:1097: Expression produces a value of type 
          {_, _}, but this value is unmatched

dets_server.erl:187: Expression produces a value of type 
          {_, _}, but this value is unmatched

dets_server.erl:288: Expression produces a value of type 
          {_, _}, but this value is unmatched

disk_log_server.erl:127: Expression produces a value of type 
          {_, _}, but this value is unmatched

disk_log_server.erl:187: Expression produces a value of type 
          {_, _}, but this value is unmatched

disk_log_server.erl:245: Expression produces a value of type 
          {_, _}, but this value is unmatched

dist_ac.erl:450: Expression produces a value of type 
          {_, _}, but this value is unmatched

dist_ac.erl:478: Expression produces a value of type 
          {_, _}, but this value is unmatched

dist_ac.erl:1280: Expression produces a value of type 
          {_, _}, but this value is unmatched

dist_ac.erl:1288: Expression produces a value of type 
          {_, _}, but this value is unmatched

dist_ac.erl:1299: Expression produces a value of type 
          {_, _}, but this value is unmatched

eprof.erl:293: Expression produces a value of type 
          {_, _}, but this value is unmatched

eprof.erl:310: Expression produces a value of type 
          {_, _}, but this value is unmatched

erl_compile_server.erl:97: Expression produces a value of type 
          {_, _}, but this value is unmatched

gen_server.erl:862: Expression produces a value of type 
          {_, _}, but this value is unmatched

gen_server.erl:865: Expression produces a value of type 
          {_, _}, but this value is unmatched

gen_server.erl:946: Expression produces a value of type 
          {_, _}, but this value is unmatched

global.erl:240: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:275: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:297: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:333: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:397: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:912: Expression produces a value of type 
          pid() | {_, _}, but this value is unmatched

global.erl:1045: Expression produces a value of type 
          {[{atom(), _}], [atom()]}, but this value is unmatched

global.erl:2176: Expression produces a value of type 
          'ok' | {_, _}, but this value is unmatched

global_group.erl:699: Expression produces a value of type 
          {_, _}, but this value is unmatched

global_group.erl:725: Expression produces a value of type 
          {_, _}, but this value is unmatched

global_group.erl:755: Expression produces a value of type 
          {_, _}, but this value is unmatched

global_group.erl:964: Expression produces a value of type 
          'not_found_ignored' | 'ok' | {_, _}, but this value is unmatched

global_group.erl:1202: Expression produces a value of type 
          'not_found_ignored' | 'ok' | {_, _}, but this value is unmatched

global_group.erl:1203: Expression produces a value of type 
          'not_found_ignored' | 'ok' | {_, _}, but this value is unmatched

logger_olp.erl:171: The inferred return type of init/1 
         ('ok') has nothing in common with 
          'ignore' |
          {'ok', _} |
          {'stop', _} |
          {'ok', _,
           'hibernate' | 'infinity' |
           non_neg_integer() |
           {'continue', _}}, which is the expected return type for the callback of the gen_server behaviour

net_kernel.erl:1226: Expression produces a value of type 
          {_, _}, but this value is unmatched

net_kernel.erl:1230: Expression produces a value of type 
          {_, _}, but this value is unmatched

release_handler.erl:634: Expression produces a value of type 
          {_, _}, but this value is unmatched

release_handler.erl:638: Expression produces a value of type 
          {_, _}, but this value is unmatched

release_handler.erl:645: Expression produces a value of type 
          {_, _}, but this value is unmatched

release_handler.erl:668: Expression produces a value of type 
          {_, _}, but this value is unmatched

rpc.erl:150: Expression produces a value of type 
          {_, _}, but this value is unmatched
```

**Comment by Pouriya-Jahanbakhsh** [comment]
@ferd to avoid misunderstanding, what if we change the `Reply` message to `Response`?

**Comment by Pouriya-Jahanbakhsh** [comment]
@ferd 
> the objective being that someone is now able to typespec things such as:
> 
> ```erlang
> -spec handle_call(local_messages(), gen_server:reply(), state()) -> gen_server:reply(state(), ok | {error, _}).
> ```
> 
> and hopefully make it clear that it is never expected from that call to actually stop or ignore a message.
> 
I think it will be:
```erlang
-spec handle_call(local_messages(), gen_server:from(), state()) -> gen_server:reply(state(), ok | {error, _}).
```

**Comment by ferd** [comment]
Yeah you're right, that was a brain fart of mine. Not sure if my whole thing is worth doing anyway :man_shrugging:

**Comment by Pouriya-Jahanbakhsh** [comment]
ping

**Comment by dgud** [comment]
We will have to take a discussion on the first part and exporting the new types.
If you write types in your callback I do think you should write the types used and not "catch all" type that include all possible types.
Thus I'm not convinced we want to export the types as you did here.

Is an internal type `cb_options() :: timeout() | hibernate | {continue, term()}` a good idea?

`gen_server:reply` should be changed to return ok and the documentation fixed.
That will solve most of the warnings.

The other warnings should be solved where that calls are made.

**Comment by Pouriya-Jahanbakhsh** [comment]
I opened another pr #2411 to fix `gen_server:reply/2`.  
Are you convinced of something like [types proposed](https://github.com/erlang/otp/pull/2375#issuecomment-528338874) by @ferd ?

**Comment by dgud** [comment]
I have discussed this internally and for now we don't want to export the generalized types for the callbacks.

So can you remove the changes for the callbacks specs, and remove the export_type attribute.

**Comment by IngelaAndin** [comment]
Closed in favour of #5751

**Pull request closed without merging**
