### PR TITLE
Make sure the data segment of HiPE modules is aligned even if the allocator misaligns it

### PR DESCRIPTION
**Pull request by margnus1**
7814ec18b made `hipe_bifs:alloc_data/3` expect alignments greater than 8
from `erts_alloc()`, which is not something that it guarantees. Fix it up
so that it pads the allocation up to the required alignment, in case it
does not initially satisfy the alignment requirement.

See the discussion in #1386.

### CODE REVIEW

**Comment by sverker** [comment]
I have cherry-picked this commit into a branch that touches all hipe allocation calls.

**Comment by margnus1** [comment]
Alright. I'll close the PR, then.

**Comment by kostis** [comment]
Might be good if this branch gets merged soon on master so that we can test it.

**Comment by sverker** [comment]
I'll merge tomorrow if tests look good.

**Comment by sverker** [comment]
Merged to master at deaa890b3da0.

**Pull request closed without merging**
