### PR TITLE
Improve standard_error

### PR DESCRIPTION
**Pull request by nox**
The process handling standard_error didn't handle the getopts request correctly, nor its options were consistent with standard_io and was subject to crashes on bad protocol input (e.g. `io:put_chars(standard_error, [oops])`).

No tests yet because I would like to discuss it first.

Cc @alco

### CODE REVIEW

**Comment by sirihansen** [comment]
Great, thanks! I have approved this patch now!

**Comment by marcusarendt** [comment]
@nox  Dialyzer complains:
standard_error.erl:203: (call) 
The call erlang:list_to_binary(Chars::{'error',binary(),binary() | maybe_improper_list(binary() | maybe_improper_list(any(),binary() | []) | char(),binary() | [])} | {'incomplete',binary(),binary()}) 
breaks the contract (IoList) -> binary() when is_subtype(IoList,iolist())

**Comment by nox** [comment]
Seems like the second clause of put_chars became obsolete or something.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by marcusarendt** [comment]
merged on maint

**Pull request closed without merging**
