### PR TITLE
Correct some errors in compiler source comments

### PR DESCRIPTION
**Pull request by frej**
121c858342e44405d08bd030a3967388e2b02a01 should be reviewed by @bjorng as the original author.

### CODE REVIEW

**Comment by bjorng** [comment]
Thanks for noticing the misleading comment. I have addressed it in #8586.

**Comment by frej** [comment]
Refreshed the branch to only contain the commit with typo corrections.

**Review by kikofernandez — APPROVED** [review]

**Comment by kikofernandez** [comment]
Maybe this should be rebased onto `maint`, instead of `master` :)

**Comment by bjorng** [comment]
I think `master` is fine for correcting comments.

**Pull request merged**
