### PR TITLE
Simplify `maps:groups_from_list/2,3`

### PR DESCRIPTION
**Pull request by Maria-12648430**
This PR simplifies the implementation of `maps:groups_from_list/2,3` by using `lists:foldl` instead of reinventing the wheel. A performance test shows no difference in speed between the old and new implementation.

A small difference exists in the case when an improper list is given as input. In the old implementation, the `error` originating from `lists:reverse` is caught and re-`error`-ed from `maps:groups_from_list`. The new implementation lets it pass through. This can be changed if you think it necessary.

### CODE REVIEW

**Comment by bjorng** [comment]
> A small difference exists in the case when an improper list is given as input. In the old implementation, the `error` originating from `lists:reverse` is caught and re-`error`-ed from `maps:groups_from_list`. The new implementation lets it pass through. This can be changed if you think it necessary.

Yes, I think it is necessary.

This module contains both BIFs implemented  in C and Erlang functions. The Erlang functions are deliberately written to report errors in the same ways as BIFs written in C would.

**Comment by Maria-12648430** [comment]
@bjorng ok, changed and updated te commit :)

**Comment by bjorng** [comment]
I don't consider this change a simplification, and neither do a few my colleagues in the OTP team. I think we should keep the original code.

**Comment by Maria-12648430** [comment]
Yeah, granted, it's not much 😅

**Comment by Maria-12648430** [comment]
Btw @bjorng, I'm currently preparing another PR whichs adds the ability to give a list of key functions (instead of a single one) and accordingly returns groups of groups (a group hierarchy, if you want). Is there any interest in that?

**Comment by jhogberg** [comment]
That sounds dreadfully close to `sofs`. :smile:

I'm not sure having something like that in `lists` is warranted, do you have any particular use case?

**Pull request closed without merging**
