### PR TITLE
New file erldoc.el to look up Erlang/OTP HTML documentation

### PR DESCRIPTION
**Pull request by leoliu**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
[See writing commit message](https://github.com/erlang/otp/wiki/Writing-good-commit-messages)

I don't know how to use it, or what it is supposed to do or why we should add it.

And I can't test it since we are stuck on 24.3 here, and that doesn't seem to work.

**Comment by leoliu** [comment]
hi @dgud,

I'll fix the commit message.

The core feature of `erldoc` is to open manual entry of any function in the browser. For example, `M-x erldoc-browse RET erlang:binary_to_integer/1 RET` will open the manual of the `erlang` module anchored on `binary_to_integer/1`.

Another feature is to open any chapters of any user guides i.e. `M-x erldoc-browse-topic RET common_test#Common Test Basics` will open the Chapter `Common Test Basics` of CT in the browser.

Both `erldoc-browse` and `erldoc-browse-topic` support completion so you don't have to type these long names.

Command `erldoc-apropos` helps find MFAs containing a substring. For example, `M-x erldoc-apropos RET first RET` will list matching entries in a buffer and make them clickable:

```
binary:first/1
dets:first/1
ets:first/1
mnesia:first/1
mnesia:dirty_first/1
odbc:first/2
odbc:first/1
wxImage:findFirstUnusedColour/2
wxImage:findFirstUnusedColour/1
......
```

The last feature is to show call tips (via eldoc) for all the MFAs in the manual.

**Comment by dgud** [comment]
Thanks.

Still have a problem with testing this, I guess it's not possible to make it work on older emacs versions?

Can you rebase on top of new maint when you edit the commit msg as well.

**Comment by leoliu** [comment]
There seems little stopping it from working on 24.2 (may be even 24.1, but 24.2 is the oldest I have on an old macbook) as long as it is compiled with libxml2 so that `libxml-parse-html-region` is available. 

I will rebase the commit after making it work on 24.2.

**Comment by dgud** [comment]
I guess most people don't build their own emacs, I know I don't.
The` libxml-parse-html-region ` lisp function exists on my ubuntu-14.04 version if that is enough.

I don't want to prohibit functionality on newer versions either, just because we can't make it work on old versions.

**Comment by leoliu** [comment]
I have briefly tested it on 24.2 and 24.3 and it seems to work well.

I forgot since when emacs compiled with libxml2 by default (probably 24.4). Now there is also a text browser `eww` (comes with emacs) which also depends on `libxml-parse-html-region`  i.e. in new versions of emacs `libxml-parse-html-region` is pretty standard.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
Things work much better when I clean out 20 year old trash from my` .emacs` file, sigh.
Things like  '(browse-url-browser-function (quote browse-url-netscape)) and regexp proxy hacks
which didn't work.

It might be time to scratch that file and start all over :-/

**Pull request merged**
