### PR TITLE
Update Unicode to 14.0.0

### PR DESCRIPTION
**Pull request by maintenance-beam-app**
This is an automated commit generated by the Maintenance project.
https://github.com/eksperimental/maintenance

If you find any issue in this PR, please kindly report it to
https://github.com/eksperimental/maintenance/issues

### CODE REVIEW

**Comment by eksperimental** [comment]
Hi [OTP people](@erlang/otp),
I have created an app that will be automatically submitting PRs upon certain conditions.

For OTP, it will be updating the Unicode files as soon as a new version is released, as the app checks for changes several times daily.

Please let me know if there is something else I could add to ease with the development of OTP, or if there is something that you considered could be improved.

The source code for the app is here: https://github.com/eksperimental/maintenance

**Comment by dgud** [comment]
Have you read the spec and seen if any rules are changed?

**Comment by eksperimental** [comment]
> Have you read the spec and seen if any rules are changed?

what specs?

**Comment by dgud** [comment]
The Unicode-14 spec http://www.unicode.org/versions/Unicode14.0.0/

**Comment by eksperimental** [comment]
> The Unicode-14 spec http://www.unicode.org/versions/Unicode14.0.0/

Nope. It will require someone with the proper Unicode and Erlang knowledge to assess whether extra changes are required to the `unicode`  module.

I will update the app to add a link to the Unicode specs and requiring someone to review them, before mergin the PR.
Thank you for mentioning it.

**Comment by dgud** [comment]
Looks good to me, thanks.

**Comment by eksperimental** [comment]
Thank you @dgud for taking care of it.
There's also https://github.com/erlang/otp/pull/5598 if you want to have a look at.

**Pull request merged**
