### PR TITLE
Fix gen_tcp_api_SUITE test cases and inet_drv.c multi-timer logic

### PR DESCRIPTION
**Pull request by nybek**
This request contains two commits:

    76562a9 Fix 6 tests in gen_tcp_misc_SUITE
    2bc5b97 Fix add_multi_timer() in inet_drv.c

I've put these two commits together because it's possible that fixing the test
cases in the first commit will lead to intermittent failures of tests due to the
flaw handled in the second commit.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Hello!

As we no longer use the ?line macros we are in the (slow) process of removing them.
Most of the time we remove them from the files we are working in at the moment. Now someone has been through the gen_tcp_misc_SUITE and removed them, and also made a few changes. Would you mind rebasing upon latest master and removing your ?line macros?

Thank you!

**Comment by psyeugenic** [comment]
My test case cuddling was mainly to reduce test running time. I've noticed some inconsistencies in the test cases in `gen_tcp_misc_SUITE` so I was pleased to see this patch .. which also solves the actual bug. I have reviewed it and it looks good to me.

To be clear, we don't want patches that removes `?line` macros in any other places than in relation of the topic for the pull request.

**Comment by nybek** [comment]
Glad it worked out!

The ?line macros are gone now.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: public_key: Align "=" sign in type declarations to decided policy


----------------

I am a script, I am not human 

----------------

**Comment by nybek** [comment]
On Thu, Jun 04, 2015 at 11:02:32AM -0700, OTP Maintainer wrote:
> The summary line of the commit message is too long and/or ends with a "."
> Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.
> 
> Bad message: public_key: Align "=" sign in type declarations to decided policy


You might want to check the regex you use to test commit messages; it
seems to get triggered if there is a "." anywhere in the message.

I've updated the second commit message from:

    Fix add_multi_timer() in inet_drv.c
to:
    Fix add_multi_timer() in inet_drv

Hope that fixes the problem. I have no idea what the "Bad message" line is
about.

**Comment by proxyles** [comment]
Nah "public_key: Align "=" sign in type declarations to decided policy" is actually 66 chars long, max is 50 (script accepts 60)
I will look to improve and/or change the message when time allows 

If you want to remove the 250+ commits you will need to change the target of the PR to master instead of maint.
But as Github does not have the ability to change the target branch for a pullrequest (yet). Your only choice right now is to close and reopen towards master instead of maint. 
Andalso send a feature request towards github for this, as they have some kind of vote-based backlog.


Thank you for the swift action, running it now.

**Comment by nybek** [comment]
Ah yeah, that makes sense now! :-) I've added my vote on github.

Let me know if you require me to open a new PR with master as target and I'll
do exactly that.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: public_key: Align "=" sign in type declarations to decided policy


----------------

I am a script, I am not human 

----------------

**Pull request merged**
