### PR TITLE
Garbage collect supervisors after initialization

### PR DESCRIPTION
**Pull request by josevalim**
Supervisor may generate garbage during initialization,
especially if logging is enabled, and this garbage may
never be collected, especially if a supervisor does not
perform additional work.

This commit forces the supervisor to immediately
garbage collect after initialization.

See #5608.

### CODE REVIEW

**Comment by lhoguin** [comment]
The same should probably be done on the top-level process (application behavior) because work that is done in `start/2` may never be freed. We can trigger the GC manually in this case so it's less of an issue.

**Comment by ferd** [comment]
Would post-initialization hibernation make more sense, since it GCs and compacts memory at once and we know there's likely a bunch of other processes ready to do work (as part of initialization)?

**Comment by josevalim** [comment]
@ferd I think you could argue for hibernation too but I went with GC because it is the minimal amount of work. Not sure if we could end-up doing "too much".

**Comment by IngelaAndin** [comment]
Probably hibernation would be better except for simple_one_for_one supervisors.

**Comment by josevalim** [comment]
@IngelaAndin no worries. The PR is only 7 LOC and if you would prefer to go with another approach, then feel free to close this. hibernation may be even fewer lines :D

**Comment by IngelaAndin** [comment]
@josevalim ok I do not have time to do this for RC1 as deadline is today. I will leave this open, as a placeholder, until I have time to make an other PR that can replace it.

**Comment by IngelaAndin** [comment]
Replaced by #6895

**Pull request closed without merging**
