### PR TITLE
EEP-59 - Documentation Attributes

### PR DESCRIPTION
**Pull request by kikofernandez**
## Implementation of EEP-59 - Documentation Attributes

- Documentation attributes are added to the binary beam file, following format of [EEP-48](https://www.erlang.org/eeps/eep-0048), via `+beam_docs` compiler flag

- Warnings related to documentation attributes are dealt with in the `beam_docs.erl` instead of adding them to `erl_lint.erl`

### Example 1

```erlang
-module(warn_missing_doc).

-export([test/0, test/1, test/2]).
-export_type([test/0, test/1]).

-type test() :: ok.
-type test(N) :: N.

-callback test() -> ok.

-include("warn_missing_doc.hrl").

test() -> ok.
test(N) -> N.
```

Using the compiler flag `warn_missing_doc` will raise a warning when doc. attributes are missing in exported functions, types, and callbacks.

### Example 2

```erlang
-module(doc_with_file).

-export([main/1]).

-moduledoc {file, "README"}.

-doc {file, "FUN"}.
-spec main(Var) -> foo(Var).
main(X) ->
    X.
```

`moduledoc`s and `doc`s may refer to external files to be embedded.

### Example 3 - Warnings and Types

```erlang
-export([uses_public/0]).
-export_type([public/0]).

-doc false.
-type hidden_type() :: integer().

-type intermediate() :: hidden_type().
-type public() :: intermediate().

-spec uses_public() -> public().
uses_public() ->
    ok.
```

Compiler warns about exported functions whose specs refer to hidden types. In the example above, the `hidden_type()` is set as `hidden` either via `-doc false` or `-doc hidden` and `public() :> intermediate() :> hidden_type()`. When documentation attributes mark a type as hidden, they won't be part of the documentation. Thus, the warning that the `hidden_type()` is not part of the documentation, yet used in an exported function.

### CODE REVIEW

**Comment by garazdawi** [comment]
You can read the documentation about doc attributes [here](https://garazdawi.github.io/otp/doc/system/documentation.html). 

If you want to see more examples of how this would look in practice you can checkout [my branch converting all of Erlang/OTP](https://github.com/garazdawi/otp/tree/lukas/convert-docs-to-markdown). For example: [base64](https://github.com/garazdawi/otp/blob/lukas/convert-docs-to-markdown/lib/stdlib/src/base64.erl), [dict](https://github.com/garazdawi/otp/blob/lukas/convert-docs-to-markdown/lib/stdlib/src/dict.erl) or [erlang](https://github.com/garazdawi/otp/blob/lukas/convert-docs-to-markdown/erts/preloaded/src/erlang.erl).

**Comment by josevalim** [comment]
Should +beam_docs be enabled by default? Or should the configuration be written in a way where we can turn it on and off in case we want to swap defaults? I'd say having Erlang/OTP, my deps, and my code compiled with docs will improve the `c:h/1` experience. And, given release tools already discard the docs chunk anyway, we wouldn't see an actual impact in production.

**Comment by michalmuskala** [comment]
Is there any support for documenting macros or records with this new API? I know edoc allows documenting only functions, and here we're expanding to also types & callbacks. That said, it would be nice if all "constructs" of the language could be documented.
At the same time, I can definitely see the challenge, given records and macros, especially if defined in headers, don't "live" in any particular module, so it's not clear where the documentation should end up.

**Comment by garazdawi** [comment]
There is no support for records nor macros right now. As you say, it is a difficult thing as they don't belong to a specific module. In our docs we document them using extra pages, like [assert.hrl](https://garazdawi.github.io/otp/lib/stdlib-5.1.1/doc/html/assert_hrl.html). 

The only way I can see (for now) to support them is to allow `-doc` attributes to be associated with them, but then treat them the same as un-exported functions, i.e. they don't end up in the doc chunk. This would allow IDEs to use the `-doc` for intellisense, just as `-doc` for non-exported functions, but that would be the end of it.

Not sure it is worth adding support for that "just" to make the docs available in the IDE...

There is a workaround of sorts for records and that is by declaring a type for the record. That way you can attach documentation to the type that describes the record, like what is done for [file:file_info/0](https://garazdawi.github.io/otp/lib/kernel-9.1/doc/html/file.html#t:file_info/0) (allthough now that I look at it, I need to fix ExDoc to render the entire record as is done by [erl_docgen](https://www.erlang.org/doc/man/file.html#type-file_info))

**Comment by josevalim** [comment]
> There is a workaround of sorts for records and that is by declaring a type for the record. 

This looks like a very fair compromise to me!

**Pull request merged**
