### PR TITLE
add binary string uri encode/decode functions

### PR DESCRIPTION
**Pull request by tsloughter**
The naming is a bit inconsistent with modules like `base64` which use `_string`, and I'd maybe prefer not having a separate function name at all but simply checking if the argument is a list or binary, but that may not be an option for backwards compatibility reasons?

I also don't see any http_uri encode/decode tests to extend.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
./otp_build all -a failed:

    ce/otp/lib/inets/src/inets_app'
    make[4]: Entering directory `/ldisk/henrik/git/otp_pulls/tmp/workspace/otp/lib/inets/src/http_lib'
     ERLC	../../ebin/http_chunk.beam
     ERLC	../../ebin/http_transport.beam
     ERLC	../../ebin/http_request.beam
     ERLC	../../ebin/http_util.beam
     ERLC	../../ebin/http_response.beam
     ERLC	../../ebin/http_uri.beam
    http_uri.erl:114: variable 'Reserved' is unbound
    http_uri.erl:251: Warning: function uri_encode_binary/2 is unused
    make[4]: *** [../../ebin/http_uri.beam] Error 1
    make[4]: *** Waiting for unfinished jobs....
    make[4]: Leaving directory `/ldisk/henrik/git/otp_pulls/tmp/workspace/otp/lib/inets/src/http_lib'
    make[3]: *** [opt] Error 2
    make[3]: Leaving directory `/ldisk/henrik/git/otp_pulls/tmp/workspace/otp/lib/inets/src'
    make[2]: *** [opt] Error 2
    make[2]: Leaving directory `/ldisk/henrik/git/otp_pulls/tmp/workspace/otp/lib/inets'
    make[1]: *** [opt] Error 2
    make[1]: Leaving directory `/ldisk/henrik/git/otp_pulls/tmp/workspace/otp/lib'
    make: *** [libs] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by tsloughter** [comment]
Does the script not rerun and post that it has now passed?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by HansN** [comment]
1) in encode_binary/2 you call uri_encode/2.  Should that be the uri_encode**_binary**/2 to work?
2) please update the documentation for http_uri with your two new api functions
3) we are aware that there is no test case for the existing http_lib functions, but could you please add a simple testcase for your two additions?

**Comment by vans163** [comment]
Anyway to get a base64 url safe encoding as well.  The current erlang base64 can produce 2 or 3 uri invalid characters, and offers no option to produce a uri safe one.

**Comment by tsloughter** [comment]
@HansN thanks, I'll get the code updated and docs/tests added.

**Comment by HansN** [comment]
Closed due to inactive. Please submit a new PR if you still want to contribute.

**Pull request closed without merging**
