### PR TITLE
Disk log tweaks

### PR DESCRIPTION
**Pull request by richcarl**
Found an old branch with cleanups of disk_log and decided to finish it.
- Improves behaviour of internal write cache
- Some small efficiency gains
- Clarifies some points in documentation and types
- Eliminates code duplication and other cleanups

### CODE REVIEW

**Comment by uabboli** [comment]
In commit 025da19 you need to remove the dlog_byte type from disk_log.xml.

**Comment by uabboli** [comment]
Thanks, looks good. Some nitpicking:

Commit b653dc, "Only read log format once in collect loop"
I don't know about the new function log_loop/4...
What do you think about the following?

    diff --git a/lib/kernel/src/disk_log.erl b/lib/kernel/src/disk_log.erl
    index 5b40e02..bd5117d 100644
    --- a/lib/kernel/src/disk_log.erl
    +++ b/lib/kernel/src/disk_log.erl
    @@ -691,8 +691,8 @@ handle({From, {log, Format, B}}=Message, S) ->
		reply(From, {error, {read_only_mode, L#log.name}}, S);
	    #log{status = ok, format=external}=L when Format =:= internal ->
		reply(From, {error, {format_external, L#log.name}}, S);
    -	#log{status = ok} ->
    -	    log_loop(S, From, [B], []);
    +	#log{status = ok, format = LogFormat} ->
    +            log_loop(S, From, [B], [], iolist_size(B), LogFormat);
	    #log{status = {blocked, false}}=L ->
		reply(From, {error, {blocked_log, L#log.name}}, S);
	    #log{blocked_by = From}=L ->
    @@ -708,8 +708,8 @@ handle({alog, Format, B}=Message, S) ->
	    #log{status = ok, format = external} when Format =:= internal ->
		notify_owners({format_external, B}),
		loop(S);
    -	#log{status = ok} ->
    -	    log_loop(S, [], [B], []);
    +	#log{status = ok, format = LogFormat} ->
    +            log_loop(S, [], [B], [], iolist_size(B), LogFormat);
	    #log{status = {blocked, false}} ->
		notify_owners({blocked_log, B}),
		loop(S);
    @@ -742,8 +742,8 @@ handle({From, sync}=Message, S) ->
	 case get(log) of
	    #log{mode = read_only}=L ->
		reply(From, {error, {read_only_mode, L#log.name}}, S);
    -	#log{status = ok} ->
    -            log_loop(S, [], [], [From]);
    +	#log{status = ok, format = LogFormat} ->
    +            log_loop(S, [], [], [From], 0, LogFormat);
	    #log{status = {blocked, false}}=L ->
		reply(From, {error, {blocked_log, L#log.name}}, S);
	    #log{blocked_by = From}=L ->
    @@ -1008,9 +1008,6 @@ enqueue(Message, #state{queue = Queue}=S) ->

     -define(MAX_LOOK_AHEAD, 64*1024).

    -log_loop(S, Pids, Bins, Sync) ->
    -    log_loop(S, Pids, Bins, Sync, iolist_size(Bins), (get(log))#log.format).
    -
     %% Inlined.
     log_loop(#state{cache_error = CE}=S, Pids, _Bins, _Sync, _Sz, _F) when CE =/= ok ->
	 loop(cache_error(S, Pids));

Commit c91d79, "Clarify that the type for disk log data is iolists"
Our technical writers say we shall not write "and/or".
Just "These functions log one or more iolists." would do, I think.

Commit fcee00, "Eliminate more code duplication"
If the format is 'external', there are now more tests in handle/2 as
compared to the old code. I assume you've thought about it, but maybe
there should be a clarifying comment in the code.

**Comment by richcarl** [comment]
Eliminated log_loop/4 and fixed doc. I don't think one additional atom comparison in one case is worth mentioning, since test for 'log' vs 'blog' has been eliminated, and anyway, the code is doing much heavier stuff like iolist_size() and rflat().

**Comment by uabboli** [comment]
Running Dialyzer shows that declaring bytes() as iolist() isn't
correct since binary() is no longer accepted.
(I've asked Björn to improve the travis check.)

**Comment by richcarl** [comment]
binary() not accepted? Where? As far as I can see it is accepted by blog() and balog().

**Comment by richcarl** [comment]
However, the local bytes() declaration seems redundant and could be replaced with iolist() everywhere; I just didn't eliminate it so as not to make any visible changes on the outside.

**Comment by bjorng** [comment]
> Running Dialyzer shows that declaring bytes() as iolist() isn't
correct since binary() is no longer accepted.
(I've asked Björn to improve the travis check.)

This branch is based on an older revision of `master` which does not have the Dialyzer checks in travis. That's why travis didn't complain.

**Comment by uabboli** [comment]
binary() is not a subtype of iolist(). I did not write that
iodata() is the type to use because I haven't checked it
carefully. But perhaps it is that simple.

The type dlog_head_opt() has the same issue (but the union
including 'term()' hides it).

**Comment by richcarl** [comment]
Bah, iodata() is of course right. I still can't keep those separated...
I'll revise it.

**Comment by uabboli** [comment]
Forgot to mention a minor thing: if I'm not mistaken, [bytes()] is
now a proper subtype of bytes(). Perhaps that can be used to
simplify some code. And the contracts().

**Comment by richcarl** [comment]
It doesn't get easier to distinguish these types when list_to_binary() takes an iolist, and iolist_to_binary() takes iodata()...

**Pull request merged**
