### PR TITLE
Fix typos in lib/diameter

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by otp-anders** [comment]
Sorry for the slow response. All fine, but can you remove the changes below doc/standard and update the copyright year at the top of the changed files? The RFCs aren't our documents so we're not going to fix typos in them.

**Comment by kianmeng** [comment]
@otp-anders Done. Please check.

**Comment by otp-anders** [comment]
Looks good, thanks.

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
