### PR TITLE
Added s390x support for Travis CI

### PR DESCRIPTION
**Pull request by sangitanalkar**
Added changes for s390x in `.travis.yml` file for building erlang/otp for s390x.

### CODE REVIEW

**Comment by garazdawi** [comment]
Please squash you two commits and write a better commit message. If you need help have a look at: https://github.com/erlang/otp/wiki/Writing-good-commit-messages

**Comment by sangitanalkar** [comment]
@garazdawi I have squashed two commits into one with a commit message. 
Please let me know if anything else is needed from my side.

**Comment by garazdawi** [comment]
Sorry to nag about the commit message, but please keep the initial line below 50 characters, as described in the link I posted.

**Comment by garazdawi** [comment]
The lastest travis job failed in s390x, do you know why?

**Comment by sangitanalkar** [comment]
Hi @garazdawi , travis job failed because of s390x VM booting issue which we were facing 2 days back. The issue is fixed now, hence can you please re-trigger the build for s390x ?

**Comment by sangitanalkar** [comment]
Hi @garazdawi , all checks have passed. Please review.

**Comment by garazdawi** [comment]
Looks good, thanks for your contribution.

**Comment by garazdawi** [comment]
> Will the binaries be made available for downloading for s390x now?

No. The travis build only checks if things work, it does not create any binaries to download. If you need that you will have to build it yourself.

**Comment by garazdawi** [comment]
@sangitanalkar I keep seeing timeouts like this: https://travis-ci.org/garazdawi/otp/jobs/622590495

Any ideas why?

**Comment by sangitanalkar** [comment]
Hi @garazdawi 

I see one test case is failing for s390x for `tests.kernel_test.inet_SUITE.cases` as seen at line 2052 in job "https://travis-ci.com/sangitanalkar/otp/jobs/265486758".

So as per code at "https://github.com/erlang/otp/blob/master/scripts/run-smoke-tests#L14" , build should exit with 1 if there are failures, not really sure why it is getting timed out.

**Comment by sangitanalkar** [comment]
Hi @garazdawi ,

I tried executing the exact steps which are present in travis build, manually on s390x VM and all the smoke-tests are passing.
Attaching smoke-tests log for reference.

[smoke-tests-s390x_logs.txt](https://github.com/erlang/otp/files/3949070/smoke-tests-s390x_logs.txt)

Please let me know in case of any queries or concerns.

**Comment by garazdawi** [comment]
I would like to know why it fails in the automated travis build? And what can be done about it?

**Comment by sangitanalkar** [comment]
Hi @garazdawi , the `inet_SUITE:t_gethostnative` test failure might be due to network configuration on lxd worker spinned up for s390x 
```
inet_SUITE:t_gethostnative failed on line 696
Reason: case_clause
```
As noticed in `Worker information` in travis build logs, the s390x travis job runs on lxd worker/instance `c923ffbf-fc38-4bcd-ad9a-ce73cd0cecea@268039.lxd-s390x-travis-ci-production-1-worker13-org` where as the amd64 is running on gce-production instance and ppc64le on openstack instance.

**Comment by garazdawi** [comment]
ok, so can you fix it? We do not have any incentive to have s390x in travis, so if it is going to keep failing I will remove it.

**Comment by sangitanalkar** [comment]
Hi @garazdawi , we are working on it and have raised an issue ([link](https://bugs.erlang.org/browse/ERL-1124)) to find out the more details.

**Comment by garazdawi** [comment]
Great. I've reverted this PR while you are working on a fix for it as it interferes with all PRs opened at the moment. Feel free to open a new PR once it is solved.

**Comment by sangitanalkar** [comment]
Hi @garazdawi 

There are 2 approaches to fix the failure for s390x as following and using both the approaches all the Travis jobs are passing:

**1st approach**: Add extra case for "try_again" error in [file](https://github.com/erlang/otp/blob/master/lib/kernel/test/inet_SUITE.erl#L700) ([Travis job link](https://travis-ci.com/sangitanalkar/otp/builds/144126727))
image

**2nd approach**: Change the hostname string in [file](https://github.com/erlang/otp/blob/master/lib/kernel/test/inet_SUITE.erl#L697) ([Travis job link](https://travis-ci.com/sangitanalkar/otp/builds/144116224))
image

Can you please help us know which approach will be feasible to use?

**Comment by garazdawi** [comment]
I think that the first approach is the best.

Thanks for taking the time to dig into this.

**Comment by sangitanalkar** [comment]
Created PR #2509 with the changes to fix the issue.

**Pull request merged**
