### PR TITLE
Fix maps internal sorting bug for gcc flag "-flto"

### PR DESCRIPTION
**Pull request by sverker**
Closes GH-4846.

### CODE REVIEW

**Comment by mikpe** [comment]
I've tested this branch (merged into maint) with gcc-10.3 (Fedora 32) and gcc-11.1 (Fedora 34). The good news is that with this branch the build with `-flto` succeeds. The bad news is that the `emulator` suite hangs in tight CPU-consuming loops (`gdb` backtrace points to `select()`).

**Comment by sverker** [comment]
I just tried the same on Ubuntu 18 with gcc-10.3 and it hangs spinning in test case erts_debug_SUITE:stack_check. Is is the same for you?

**Comment by sverker** [comment]
Ok, the test case `stack_check` is suppose to do body recursive calls until native stack limit is reached. It does an inter-object-file function call to dummy function erts_ptr_id() to prevent last call optimization. But with -flto gcc is not fooled by that, making it an endless loop as the stack pointer never changes.

**Comment by sverker** [comment]
Test case `erts_debug_SUITE:stack_check` was introduced in its current state in OTP-20.0.

**Comment by mikpe** [comment]
> I just tried the same on Ubuntu 18 with gcc-10.3 and it hangs spinning in test case erts_debug_SUITE:stack_check. Is is the same for you?

I _think_ so. Since it hangs I have to ^C it, so I get incomplete results, but it did seem to point to erts_debug_SUITE as being the last thing run.

**Comment by mikpe** [comment]
> Ok, the test case `stack_check` is suppose to do body recursive calls until native stack limit is reached. It does an inter-object-file function call to dummy function `erts_ptr_id()` to prevent last call optimization. But with `-flto` gcc is not fooled by that, making it an endless loop as the stack pointer never changes.

Good find. I'll take a look tomorrow, but a strategically-placed `asm()` might cure that, or an `attribute(noinline,noclone)` (but I don't know how well that one works with `-flto`).

**Comment by mikpe** [comment]
This fixed the `emulator` suite for me:
```
diff --git a/erts/emulator/beam/utils.c b/erts/emulator/beam/utils.c
index 1657431875..c5d36949d1 100644
--- a/erts/emulator/beam/utils.c
+++ b/erts/emulator/beam/utils.c
@@ -5104,9 +5104,12 @@ erts_check_above_limit(char *ptr, char *limit)
     return ptr > limit;
 }
 
-void *
+void * ERTS_NOINLINE
 erts_ptr_id(void *ptr)
 {
+#ifdef __GNUC__
+    asm("" : "+r" (ptr), "+m" (* (char *) ptr) : "0" (ptr));
+#endif
     return ptr;
 }
 
```

**Comment by sverker** [comment]
So, the asm is an opaque dummy thing just make gcc to back off and don't optimize away the function?

**Comment by sverker** [comment]
I get the following from gcc-10.3:
```
beam/utils.c: In function ‘erts_ptr_id’:
beam/utils.c:5121:5: error: inconsistent operand constraints in an ‘asm’
 5121 |     asm("" : "+r" (ptr), "+m" (* (char *) ptr) : "0" (ptr));
      |     ^~~
```

**Comment by mikpe** [comment]
> So, the asm is an opaque dummy thing just make gcc to back off and don't optimize away the function?

It's there to ensure there is a USE of the `&c` being passed in, and a DEF for the return value, without gcc realizing it's the identity function.

**Comment by mikpe** [comment]
> I get the following from gcc-10.3:
> 
> ```
> beam/utils.c: In function ‘erts_ptr_id’:
> beam/utils.c:5121:5: error: inconsistent operand constraints in an ‘asm’
>  5121 |     asm("" : "+r" (ptr), "+m" (* (char *) ptr) : "0" (ptr));
>       |     ^~~
> ``

What platform is that on, and with what compiler flags?

**Comment by sverker** [comment]
> 
> What platform is that on, and with what compiler flags?

It's Ubuntu 18 gcc-10.3.0. It looks like I get it only for debug build, when passing -O0. Here is my full compile command line:

`gcc-10 -O0 -Werror=undef -Werror=implicit -Werror=return-type  -fno-common -g -fomit-frame-pointer -I/home/sverker/src/otp4/erts/x86_64-pc-linux-gnu    -D_GNU_SOURCE  -DHAVE_CONFIG_H -Wall -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Wdeclaration-after-statement -DUSE_THREADS -D_THREAD_SAFE -D_REENTRANT -DPOSIX_THREADS -D_POSIX_THREAD_SAFE_FUNCTIONS  -DERLANG_GIT_VERSION="\"d8d345b390\"" -DBEAMASM=1 -Ix86_64-pc-linux-gnu/opt/jit -Ibeam -Isys/unix -Isys/common -Ix86_64-pc-linux-gnu -Izlib  -Ipcre -I../include -I../include/x86_64-pc-linux-gnu -I../include/internal -I../include/internal/x86_64-pc-linux-gnu -Ibeam/jit -Ibeam/jit/x86 -c beam/utils.c -o obj/x86_64-pc-linux-gnu/opt/jit/utils.o`

If I change `-O0` to `-O2` (or anything at all) it goes away. Strange.

**Comment by frej** [comment]
Gcc won't do the tail call optimization if the function has the `__attribute__((noreturn))` attribute, see [this GCC wontfix bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=10837). If Clang does the same, this could be an alternative to the inline assembly.

**Comment by sverker** [comment]
Added some more C code that protects against tail call optimization but also seem to prevent it.

**Comment by mikpe** [comment]
This one (merged onto maint) passes the emulator suite fine for me when compiled with `CFLAGS="-O2 -flto"` (Fedora 33, gcc-10.3.1). No `asm()` needed apparently :-)

**Pull request merged**
