### PR TITLE
Option to erlang:garbage_collect to request minor (generational) GC

### PR DESCRIPTION
**Pull request by kvakvs**
Note: Minor GC option is a hint, and GC may still decide to run fullsweep.
Test case for major and minor gc on self
Test case for major and minor gs on some other process + async gc test check
Documentation adjusted

### CODE REVIEW

**Comment by psyeugenic** [comment]
Why?

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Option to erlang:garbage_collect to request minor (generational) GC


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
@psyeugenic in order to attempt to control that only newly created data is considered in the GC. For instance if you have some large permanent term structure that you search through and create something which you want to immediately gc away (most likely in order to release binary references), but don't want to copy the entire old heap.

Maybe @dgud also has some use-case? If i remember correctly he came up with the original request.

**Comment by dgud** [comment]
I do think that a language that is (or was) promoted as soft-realtime
language should give the programmer the choice to make a (small) gc when
(s)he knows that there is dead temporary data on the heap and there is a
couple microseconds to spare after a calculation.

**Comment by psyeugenic** [comment]
@garazdawi To my recollection we rejected the idea due to bad guarantees. Yeah @dgud has probably wanted this for at least 10 years and every time it came up we said no.

**Comment by psyeugenic** [comment]
@kvakvs Regardless if you got requested to this feature or not, you should still explain why the feature is needed. If why wasn't explained in the request, you should refuse. There is always a why.

@dgud It's so close you can taste it now .. =)

Ok, we should challenge the previous decision and see where we are.

**Comment by garazdawi** [comment]
merged to master

**Pull request closed without merging**
