### PR TITLE
Short-circuit common dict operations

### PR DESCRIPTION
**Pull request by josevalim**
Stop traversing all segments and buckets of empty
dictionaries by adding a clause that checks the
dictionary size.

This improved compilation of an erlang project from
7.5s to 5.5s seconds when trying out a sample
implementation of erl_lint that uses dicts.

Related to #617.

### CODE REVIEW

**Comment by josevalim** [comment]
Now split in three commits.

**Comment by bjorng** [comment]
Thanks! Looks good. We will merge it to master after a few days testing our daily builds.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Merged to master.

**Pull request closed without merging**
