### PR TITLE
Correct typo in logger formatter docs

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by sirihansen** [comment]
Thank you for the fix! Could you please rebase this on the maint branch instead?

**Comment by lpil** [comment]
There you go!

**Comment by garazdawi** [comment]
You can change it. Press "Edit" up top and change the base.

**Comment by lpil** [comment]
Well I be. How long has that been there? I'd no idea 😄 

Thanks @garazdawi. All done I think @sirihansen

**Comment by garazdawi** [comment]
It has been there a year or two. I discovered it by accident while editing the title of a pr...

**Pull request merged**
