### PR TITLE
Improve comments for wx.erl and wxEvtHandler.erl

### PR DESCRIPTION
**Pull request by leoliu**

### CODE REVIEW

**Comment by dgud** [comment]
Can you remove {callback, {nospawn, Fun}} changes, I don't want it documented, it easily leads to deadlocks.

**Comment by leoliu** [comment]
Thanks for the comment.  Feel free to squash them. I tried to do it myself but somehow push to gh failed.

**Comment by dgud** [comment]
Can you try the push again, if I squash you will loose your credits.

**Comment by dgud** [comment]
Also rebase it master and fix merge conflicts.

**Comment by leoliu** [comment]
Replaced by PR #5626.

Don't know how to modify this PR as suggested so I created a new one. Hope it's OK. Thanks.

**Comment by dgud** [comment]
You could have just force pushed the branch.

**Comment by leoliu** [comment]
Will try next time.  Sorry for the inconvenience!

**Pull request closed without merging**
