### PR TITLE
Remove archives fallback in code path

### PR DESCRIPTION
**Pull request by josevalim**
Archives have a feature where both the archive directory and the application directory can co-exist and the contents of the archive will be read as a fallback. This pull request removes this feature as it is implicit behaviour and has a direct impact on each code path added to the code server with two additional file system lookups per code path.

Furthermore, I struggle to see the benefit of this feature:

1. This could be used to provide a fallback `ebin` directory for a given application, but this requires an application without `ebin` to be added to the code path, which is slightly contradictory as the `ebin` directory is the one typically added to the code path in the first place

2. You most likely cannot  add `priv` from an archive because the functions in the `file` module cannot read contents from archives. Therefore, if you do `file:read_info(code:priv_dir(megaco))`, it will return `error` if the path points to an archive (and we most likely don't want to make that support archives as it will make all error paths from the `file` module more expensive)

Finally, reading any content from an archive is actually considerably slower than reading from an unpacked archive. Therefore we should promote users to unpack archives and use them directly whenever possible. Still, Erlang/OTP should still support archives, especially for cases like escripts, and this pull request removes only one specific implicit feature from them.

---

Apologies for sending another pull request which is removing existing behaviour. But I believe there is merit on this proposal, similar to the one in #6683. Both are implicit behaviours that have an impact in all users while they are likely rarely used. And I keep running into those scenarios while looking into #5811 and #6692.

Given archives are still tagged as experimental, perhaps this is a good opportunity to clean up those implicit behaviours and streamline code loading, with the goal of eventually marking archives as stable.

### CODE REVIEW

**Comment by michalmuskala** [comment]
You can read priv directories from archives with `erl_prim_loader(code:priv_dir(megaco))` - and this is where the "fallback" feature works. You can have an application in an archive (probably shared as a build system artifact) and priv dir on disk to provide some host-specific configuration - at least this seems like the intention of how the feature was designed - weather it's used like that in practice is a different question

**Comment by josevalim** [comment]
Correct, the issue is that all code upfront has to be written with erl_prim_loader but most projects that have to read do so through the file API. So for example, if you have a CSV file, you most likely cannot use the built function from a CSV library to read files and rather roll your custom one. At this point, you might as well read the configuration from anywhere. Is there any benefit from reading it as a priv fallback? Also consider that the priv directory cannot be partially replaced, it is all or nothing, so this sort of configuration fully blocks you from using priv for your own purposes in the future.

Other than fallbacks, archives do have their uses, so +1 in making them faster. At the same time, the implicit behavior does have a measurable effect on the system:

* `2*pa*pz+Paths` lookups for every `{path, Paths}` instruction in the boot scripts

* 2 lookups for each path, -pa, -pz, apps in OTP root, apps in erl libs in the code server

**Comment by michalmuskala** [comment]
Yes, I agree the double traversal is problematic. 

However, I think that in general we might need to rethink a bit the whole code loading process and how it's commonly integrated into various tooling to make it really fast. I see leveraging archives as great opportunity for that.

**Comment by frazze-jobb** [comment]
I researched this a little bit to get an understanding on how we should deal with host specific parts, like NIFs that you could bundle in a Zip file (with application structure) together with a .ez archive.

I feel like it would be more convenient if it was put inside the .ez archive (without compression). To streamline them some more. We are not the only ones having this problem. Google put .so files in their .apk and extracted them out of the .apk on installation. So then you would have them both in the .apk and on disk. They solved that by forking glibc and added a dlopen_with_offset. But since we can't do that, then probably the currently most efficient way to distribute an archive with a .so is like it has currently been designed.
I was thinking if you could take out the .so file of the .ez archive on startup, either to disk or a ramdisk and then load it with dlopen().

We want to have archives, and we want them to be performant. I don't know why they aren't that currently, I need to dig some more, @michalmuskala feel free to enlighten me!

**Comment by frazze-jobb** [comment]
I asked around and we accept this change, and we will try to get the dynamic libraries inside the .ez/escript file in the future. If we get a lot of complaints for removing this functionality without providing an alternative we may have to revert this change.

**Pull request merged**
