### PR TITLE
New file erlang-edoc.el to support EDoc in erlang-mode

### PR DESCRIPTION
**Pull request by leoliu**
- EDoc markup font-locking and tag completion
- EDoc comment indentation

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
The file is missing in Makefile and thus installed systems will not have the mode and fail at startup?

If I don't enable the edoc-mode, *Messages* is cluttered with

> let: Symbol's function definition is void: run-hook [21 times]
> let: Symbol's function definition is void: run-hook

Hmm I get the warning even after I add enable edoc-mode. emacs-version 24.3.1

**Comment by leoliu** [comment]
I fixed these issues in https://github.com/erlang/otp/commits/master (the warnings were due to an embarrassing typo) but unfortunately it seems to cause the PR to be closed. Should I send a new one?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
Can you rebase the branch to maint. New feature but in dev tool so it is ok to be included in next maint release.

**Comment by dgud** [comment]
replaced by #1195

**Pull request closed without merging**
