### PR TITLE
jit: Add support for 64-bit ARM processors

### PR DESCRIPTION
**Pull request by jhogberg**
This PR is a continuation of https://github.com/erlang/otp/pull/2745, adding support for AArch64 platforms such as Apple's new M1-based Macs and Amazon's Graviton instances. We've also backported a few improvements we found along the way to x86_64.

As before we use the excellent [`asmjit`](https://github.com/asmjit/asmjit/) library for run-time assembly, which is getting full AArch64 support through a project sponsored by the Erlang Ecosystem Foundation (@erlef). We've included a pre-release version of it in this PR that ought to work out of the box on most platforms. Feel free to take it for a spin!

#### Performance

The performance gains are similar to the x86_64 JIT.  `dialyzer` is nearly twice as fast compared to the interpreter, compile times are generally reduced by a third, and JSON wrangling with [`jason`](https://github.com/michalmuskala/jason) is 1.4-3x as fast depending on the benchmark. One notable improvement over the x86_64 JIT is that the code is much more compact, often beating the interpreter by a small margin.

I've included the results from a few runs on an M1 Mac below:

Interpreter: https://gist.github.com/jhogberg/ee41535b5caa2917c84499277cb8c58f
JIT: https://gist.github.com/jhogberg/492456086c971e285954494ba3ea42f9

### CODE REVIEW

**Comment by wojtekmach** [comment]
This is very exciting! I tried this branch and it works great.

For anyone else trying this out, I noticed that when merging latest master, to e.g. get the recent openssl fix, with this branch, it seems we get the build without JIT:

```
~% sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
~% uname -m
arm64

~/src/otp[master]% gl -1
21ced5ac77 (HEAD -> master, origin/master, origin/HEAD) Merge branch 'maint'

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% gl -1
6dbab60b39 (HEAD -> bjorn/erts/jit-for-arm/OTP-17119) jit: Implement code generation for ARM

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% git merge master

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% git clean -dfx && time MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)" ./otp_build setup -a --with-ssl=$(brew --prefix openssl) | tee build.log
473.08s user 110.89s system 388% cpu 2:30.39 total

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% grep -i jit build.log
 CC	/Users/wojtek/src/otp/erts/emulator/pcre/obj/aarch64-apple-darwin20.4.0/opt/pcre_jit_compile.o
 CC	/Users/wojtek/src/otp/erts/obj/aarch64-apple-darwin20.4.0/jit-reader.o
 LD	/Users/wojtek/src/otp/bin/aarch64-apple-darwin20.4.0/jit-reader.so

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% ./bin/erl
Erlang/OTP 25 [DEVELOPMENT] [erts-12.0.1] [source-beaa58db96] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

~/src/otp[bjorn/erts/jit-for-arm/OTP-17119]% ./bin/erl -emu_flavor jit
erlexec: Invalid emulator type or flavor. Available combinations are:
  -emu_flavor emu
  -emu_flavor smp
```

**Comment by bjorng** [comment]
> I noticed that when merging latest master, to e.g. get the recent openssl fix, with this branch, it seems we get the build without JIT

That is because #4835 that commits the `configure` scripts has been recently merged. Until we have rebased this PR on the latest master, you can run `./otp_build update_configure` yourself to update the `configure` scripts.

**Comment by wojtekmach** [comment]
Yup, thank you!

**Comment by bjorng** [comment]
I have rebased this PR on the latest master and committed a generated `configure` script.

**Pull request merged**
