### PR TITLE
crypto: Enable AES-GCM tag length to change

### PR DESCRIPTION
**Pull request by mururu**
This commit enables AES-GCM encryption/decryption to change the tag
length between 1 to 16 bytes.

[old spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf), which crypto module refers to, says that the tag length can be any value between 0 and 128, whereas [new spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-revised-spec.pdf) says between 64 and 128.

For now, this implementation allows values between 1 and 16 bytes(it means between 8 and 128), based on the openssl's implementation(https://github.com/openssl/openssl/blob/master/crypto/evp/e_aes.c#L1350-L1355).

Use case: [quic](https://docs.google.com/document/d/1g5nIXAIkN_Y-7XJW5K45IblHd_L2f5LTaDUDwvZ5L6g/edit) uses 12-byte tag.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Looks good. I have put it into our test machinery.

**Pull request merged**
