### PR TITLE
Not streamed responses with `once`

### PR DESCRIPTION
**Pull request by qrilka**
You have closed https://github.com/erlang/otp/pull/594 saying that you want to do some better streaming implementation for `httpc` and there were no other news about it since January.
It appears that the current streaming (or rather not streaming other than 200/206 responses) is broken with `{self,once}`.
This PR shows the problem and how did we resolve it in our httpc (OTP) fork (i.e. it's based on top of https://github.com/erlang/otp/pull/594 ).
Hope that will give some ideas or at least serve as a bug report :)

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Sorry I do not set all the priorities, and there have been a lot of other things that has had higher priority.
We have now revisited this and we decide that we will take this patch as step 1, and then alter it so that all bodies are streamed except  for  reason codes 1xx, 204, and 304.

**Comment by proxyles** [comment]
httpc_SUITE	not_streamed_once fails.
Reason: {test_case_failed,{#Ref<0.0.1.46213>,stream_start,
                   [{"content-length","32"}],
                   <0.2132.0>}}

all platforms

**Comment by qrilka** [comment]
Sorry, missed corresponding test responses
Amended

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
merged

**Pull request closed without merging**
