### PR TITLE
Fix race in persistent_term:get/0 and info/0

### PR DESCRIPTION
**Pull request by sverker**
Have seen to cause failed assert in debug VM.

### CODE REVIEW

**Review by max-au — APPROVED** [review]
Confirming this fixes the race.

**Comment by sverker** [comment]
@max-au Thank you for the bug provoking test code.

**Comment by max-au** [comment]
Thanks goes to @potatosalad, who discovered the actual race, I only happened to know the cause.

**Comment by sverker** [comment]
Merged to master for OTP 24 and in pipe for next OTP-23.3.x.

**Comment by sverker** [comment]
Fix released in OTP-23.3.2.

**Pull request closed without merging**
