### PR TITLE
Fix cerl_trees:label/2 bug with map K/V swap

### PR DESCRIPTION
**Pull request by margnus1**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by margnus1** [comment]
@psyeugenic Sure! Would a simple unit test suffice? As far as I can tell, no OTP app currently misbehaves because of this bug.

It does not seem to fit the pattern in `regressions_SUITE`, so do I add it to `misc_SUITE`, or create a new `cerl_SUITE`?

**Comment by psyeugenic** [comment]
Correct, nothing in the compiler uses `cerl_trees:label/1,2`, that I can see, only HiPE and Dialyzer. So perhaps add the test case in one of those applications. How did you find it? Are you hacking away in HiPE or Dialyzer?

**Comment by margnus1** [comment]
I will do so. It was indeed found by hacking HiPE and Dialyzer. Kostis and I are touching up some code for map-related type inference we had lying around from a course of his, for inclusion in OTP proper. We decided to submit this bug fix separately.

**Comment by kostis** [comment]
It's probably not the best way of doing things, but perhaps having/adding a test in that pull request (the HiPE-map related one that we will soon submit) suffices?

**Comment by psyeugenic** [comment]
Yeah, I was about to suggest that anyway. Since `cerl_trees:label/1,2` doesn't affect anything in the compiler currently, so this change is fine. And the tests in HiPE will test it in a later PR we're all good.

**Pull request merged**
