### PR TITLE
Add comments for understanding io_lib_pretty

### PR DESCRIPTION
**Pull request by richcarl**
Found an old branch with comments I added separately while I was working on the log message depth problem. Think this could still be useful for the next person trying to understand the io formatting code.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
Thanks!

The comment in the last clause of io_lib_pretty:print/8 is a bit
speculative. A comment like "atomic data (bignums, atoms, ...)
are never truncated" would suffice, I think.

pp_tag_tuple(), rec_indent(): "this uses TInd". Perhaps there
should be a comment in print/8 explaining that TInd is the tried
indentation.

print_length(): "%% redundant(?) special case of the final clause"
Good catch. Removing this clause and calling iolist_size()
instead of lists:flatlength() in the last clause would be
an improvement.

**Comment by richcarl** [comment]
Done. Yes, the "TInd" was a pretty mysterious name...

**Comment by uabboli** [comment]
Regarding "TInd"... I don't know what I was thinking of when I
suggested "tried". "TInd" seems to be the indentation to use for
the elements of tagged tuples and records. -1 means that the tag
determines the indentation. So "T" must stand for "tag".
Something like "compute the indentation to use for tagged tuples
and records" seems to be more accurate. Maybe you can find a
better wording.

**Comment by uabboli** [comment]
[I wrote:]
> Removing this clause and calling iolist_size() instead of
> lists:flatlength() in the last clause would be an improvement.

It turned out to be wrong. A testcase in jinterface,
nc_SUITE:utf8_atom(), fails as iolist_size() cannot handle
Unicode.

Maybe the best thing to do is to restore the old clause, and add a
comment about Unicode to the last clause.

**Comment by richcarl** [comment]
Ok, done.

**Pull request merged**
