### PR TITLE
Microstate accounting

### PR DESCRIPTION
**Pull request by garazdawi**
The pull request introduces two new features: os:perf_counter/0 and erlang:statistics(microstate_accounting). They are placed in the same pull request as microstate accounting depends on os:perf_counter.

# Performance counter

The performance counter can be used to get very low overhead time stamping of events. You can either use the `os:perf_counter/0` call to get a counter in native resolution, or you can use `os:perf_counter/1` to get it in the resolution you specify. i.e. `os:perf_counter(1000)` returns a timestamp in 1/1000 s resolution. 

# Microstate accounting

Microstate accounting is a way to track which state the different threads within ERTS are in. The main usage area is to pin point performance bottlenecks by checking which states the threads are in and then from there figuring out why and where to optimize.

Since checking whether microstate accounting is on or off is relatively expensive if done in a short loop only a few of the states are enabled by default and more states can be enabled through configure.

Example usage:

```

1> msacc:start(1000).
ok
2> msacc:print().
Average thread real-time    : 1000513 us
Accumulated system run-time :    2213 us
Average scheduler run-time  :    1076 us

        Thread      aux check_io emulator       gc    other     port    sleep

Stats per thread:
     async( 0)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
     async( 1)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
       aux( 1)    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%   99.99%
 scheduler( 1)    0.00%    0.03%    0.13%    0.00%    0.01%    0.00%   99.82%
 scheduler( 2)    0.00%    0.00%    0.00%    0.00%    0.03%    0.00%   99.97%

Stats per type:
         async    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%  100.00%
           aux    0.00%    0.00%    0.00%    0.00%    0.00%    0.00%   99.99%
     scheduler    0.00%    0.02%    0.06%    0.00%    0.02%    0.00%   99.89%
ok
```

The currently available states are: alloc, aux,  bif, busy_wait,  check_io,  emulator, ets,  gc,  gc_full, nif, other, port, send, sleep, timers.

For more details see the documentation.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lpgauth** [comment]
Is this planned for 17.* or 18?

**Comment by psyeugenic** [comment]
@lpgauth No more 17 releases scheduled. As for 18 - depends on if `msacc` gets compatible with the new timer implementation. According to @garazdawi it wasn't compatible right now.

**Comment by garazdawi** [comment]
I need to change the way that performance counter values are converted to actual time, and since all the internal time handling stuff is completely rewritten it will take some time. Most probably will not be done in time for 18.

**Comment by garazdawi** [comment]
rebased on top of the latest master, seems to work. Have to do some profiling before merge.

**Comment by tuncer** [comment]
> rebased on top of the latest master, seems to work. Have to do some profiling before merge.

Excellent, thanks, @garazdawi!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
rebased and added fix for doc builder annotations for maps.

The extra commits regarding ose is because github master is not in sync with internal master.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
merged to be included in 19.0

**Pull request closed without merging**
