### PR TITLE
Fix various ssh key exchange problems

### PR DESCRIPTION
**Pull request by dotsimon**
This pull request addresses a number of issues related to key exchange and re-exchange.
The bugs were:
* Re-exchange would occur each minute after the rekey_limit (default, 1GB) was passed
* The server did not actually do rekeying when requested from the client
* The client would not correctly respond with a KEXINIT message during rekeying initiated by the server
* Both client and server allowed sending of arbitrary messages during re-exchange
These are fixed and tests added around functionality

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by HansN** [comment]
Great job!
Please remove commit d4cf4d4 since I committed the patch you sent me eariler. It is available in master from 18-rc2. And see comments inline in e1d9641, I do not quite see that it works as intended...

**Comment by dotsimon** [comment]
Should I rebase on master then? Otherwise the tests will fail on maint without d4cf4d4

**Comment by dotsimon** [comment]
I pushed the fixed tests and I'll await your comment if you want this on master.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by HansN** [comment]
Looks good - master would be perfect!

**Comment by dotsimon** [comment]
I rebased this on master without the rekey data volume commit.
Tests pass but now the pul request looks a mess with all the rebase-related commits.
Hope this was what you wanted and/or I did not mess something up :-)

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: beam_utils: Teach check_liveness/3 to understand get_map_elements
beam_validator: Stop validating the 'aligned' flag for binaries
beam_utils: Be less conservative about liveness for exit instructions


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Unfortunately github is missing the feature to switch target for a pull request. This is aimed towards "maint" and you want it towards "master"
at the moment there is no way to change this besides closing this and reopening towards "master"

Feel free to submit a request for this feature to github (they have some kind of vote based backlog system)

**Comment by dotsimon** [comment]
Ok, but how do you want to handle this pull request now? Should I close this one and make a new one? Or can you just take the commits directly? I think "we" all agree the changes are needed.

**Comment by HansN** [comment]
Yes we all agree!   I'll take care of taking your commits.  Just leave the pull request as it is.

Thank you very much for your work!
-Hans
________________________________

**Comment by HansN** [comment]
Merged to master.

**Pull request closed without merging**
