### PR TITLE
doc: Fix spelling errors

### PR DESCRIPTION
**Pull request by lagebr**

### CODE REVIEW

**Comment by RaimoNiskanen** [comment]
Looks fine. Thank you for your pull request!

**Comment by IngelaAndin** [comment]
@lagebr Hi as Raimo missed doing the actual merge I am just wondering if you are interested in moving the document enhancements to the maint branch so that the documentation will be improved already in OTP-24 and not have to wait for OTP-25 (sometime next year).

**Comment by IngelaAndin** [comment]
@lagebr you need to do a rebase --onto and force push your branch, moving things backwards with github button does not work I am afraid.

**Comment by RaimoNiskanen** [comment]
Thank you (again) for your pull request!

**Pull request merged**
