### PR TITLE
Multiple trace sessions

### PR DESCRIPTION
**Pull request by sverker**
The ability for different users/tools to use the Erlang trace primitives (`erlang:trace` and `erlang:trace_pattern`) without risk interfering with each other's trace settings.

This PR is aimed for OTP 27.0-rc1 but the new API additions are not set in stone yet and may change:

New functions:
```
S = erlang:trace_session_create([{tracer,T}])
erlang:trace_session_destroy(S)
erlang:trace_info(S, _, _)
```
New options
```
erlang:trace(_, _, [{session,S}|_])
erlang:trace_pattern(_, _, [{session,S}|_])
```

This is totally backward compatible. The old single "legacy" trace session works as before if no dynamic trace session is specified.

### CODE REVIEW

**Comment by essen** [comment]
Hello! I wonder what this change will mean for the future. Obviously tools that use tracing can work together instead of conflicting with each other. But this change enables us to use tracing in application code directly, too. Will we see new patterns emerge?

**Comment by sverker** [comment]
> Hello! I wonder what this change will mean for the future. Obviously, tools that use tracing can work together instead of conflicting with each other. But this change enables us to use tracing in application code directly, too. Will we see new patterns emerge?

The main purpose was to enable different tools, like logging tracers, profilers and debuggers, to operate independent of each other without interference. A secondary feature was the automatic cleanup of all trace settings of a session when it was killed to avoid leaving breakpoints and other tracing hooks behinds by mistake consuming memory and cpu in vain.

To use tracing in application code as part of the regular control flow is _possible_ (and now even so without getting disturbed by other use). But this is not what tracing was designed to do, then or now. For example, the current implementation of trace sessions does not priorities to smoothly handle a massive number of simultaneous sessions. Another older example is that `erlang:trace_pattern` is optimized to not disturb the multicore scalability performance of running beam code. This is achieved at the expense of its own call latency. In a busy node a call to `erlang:trace_pattern` can block for a significant time before returning even if only affecting one traced function.

We can of course not hinder anybody. But if the urge arises to (ab)use tracing, I think some introspection is in place to question the reason. Is my application design missing something? Are the regular Erlang/OTP primitives missing something?

**Comment by gomoripeti** [comment]
> A secondary feature was the automatic cleanup

Does this mean that after `trace_session_destroy` all traces and trace patterns of that session should be cleared? What I see on 27.0-rc1 is that function tracing still continues. (I'm not sure what to expect when using a session ref after destroy, maybe a `badarg` but `trace_info` still accepts the destroyed session ref) What am I missing? (I might make some obvious mistake somewhere in the below shell)
```
% erl
Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V14.3 (press Ctrl+G to abort, type help(). for help)
1> Pid1 = spawn(fun() -> receive stop -> ok end end).
<0.88.0>
2> S1 = erlang:trace_session_create([{tracer, Pid1}]).
#Ref<0.352182729.932315144.220094>
3> erlang:trace(all, true, [{session, S1}, call]).
47
4> erlang:trace_pattern({lists, nth, '_'}, true, [{session, S1}]).
1
5> lists:nth(1, [a, b, c]).
a
6> process_info(Pid1, messages).
{messages,[{trace,<0.86.0>,call,{lists,nth,[1,[a,b,c]]}}]}
7> erlang:trace_session_destroy(S1).
ok
8> lists:nth(2, [a, b, c]).
b
9> process_info(Pid1, messages).
{messages,[{trace,<0.86.0>,call,{lists,nth,[1,[a,b,c]]}},
           {trace,<0.86.0>,call,{lists,nth,[2,[a,b,c]]}}]}
10> erlang:trace_info(S1, {lists, nth, 2}, all).
{all,[{traced,global},
      {match_spec,[]},
      {meta,false},
      {meta_match_spec,false},
      {call_memory,false},
      {call_time,false},
      {call_count,false}]}
```

**Comment by sverker** [comment]
> Does this mean that after `trace_session_destroy` all traces and trace patterns of that session should be cleared? 

It _should_. But the cleanup mechanic did not make it into OTP-27.0-rc1. I'm working on it for rc2.

The API has not yet been decided, but it seems reasonable that trace_info _should_ raise badarg or other error for a destroyed trace session.

**Comment by gomoripeti** [comment]
aha, I was too early with my expectations, thank you! btw great feature!

**Pull request merged**
