### PR TITLE
the key stored in ets table might be term()

### PR DESCRIPTION
**Pull request by getong**
Just fix it for dialyzer.

### CODE REVIEW

**Comment by kostis** [comment]
The documentation of this module specifies that the environment `Par`armeters used as keys are `atom()`s.
It's true that you _can_ use any `term()` as a key in an ETS table (and your Erlang code that does this will not crash), but this does not mean that you should do so in all places where some key-value association is stored in an ETS table.  Do you have a convincing use case where it is needed to use a more complex `term()` as an environment parameter rather than an `atom()`?

**Comment by getong** [comment]
Yes, I use the dialyzer for the erlcloud project:
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L604
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L610
https://github.com/erlcloud/erlcloud/blob/master/src/erlcloud_aws.erl#L878-L881

**Comment by ferd** [comment]
There's a gotcha that if you set the environment values in the .app file's `env` tuple, only atoms are supported, and this is validated when loading the application at first.

The documentation extends this concept and keeps it in line with what is supported in the app files and sys.config files.

**Comment by sirihansen** [comment]
I think that this problem must be solved in erlcloud and not in OTP. These are keys of environment variables, and I don't think that complex keys should be allowed. Maybe erlcloud should use an own ets table instead of the application environment variable storage?

**Pull request closed without merging**
