### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by c-rack**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Im closing this as you have yet to respond to the license email, I will make a fix locally.

Thank you for your contribution!

**Comment by c-rack** [comment]
@proxyles Thanks!
To my knowledge, I did not get a license mail.
How can I get it or what shall I do for future contributions?

**Comment by zhird** [comment]
@c-rack, sorry if you haven't gotten the email, but what you'll have to do is sending the text below to license-change@erlang.org. You only need to do this once. I'll reopen the pull request and wait for your email.

"I hereby confirm that I am the copyright holder or authorized by the copyright holder of this contribution. As such I hereby confirm that all contributions made to Erlang by me or on behalf of me, hereby is licensed under the Apache 2.0 License [http://www.apache.org/licenses/LICENSE-2.0].

I am aware that any future submissions from myself also will be considered to be
licensed under Apache 2.0 unless I expressly state otherwise. "

**Comment by c-rack** [comment]
@proxyles Thanks for your fast response.
Confirmation mail just sent out.

**Comment by zhird** [comment]
Great, thanks! I rebased it on maint and merged it, so now the change is in.

**Pull request closed without merging**
