### PR TITLE
Allow metadata and ignore to be computed in logger funs

### PR DESCRIPTION
**Pull request by josevalim**
This commit allows the logger metadata to be
computed lazily via the logger `msg_fun`.
The `msg_fun` itself can also return `ignore`.

These features are useful when computing the
metadata or if the message should be logged or
not is expensive and you want to do so only
after the log level match.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @garazdawi, do you have any concerns about moving this forward?  I am drafting the changes we will do on Elixir's Logger in the next version and this will help inform us which direction to go. Thank you!

**Comment by hauleth** [comment]
@josevalim could you point me to that document? Maybe I could help with that.

**Comment by garazdawi** [comment]
I had forgotten about this.

I don't see any problems with this, will talk with the others at OTP to make sure that they don't have any objections.

**Comment by garazdawi** [comment]
Putting into test for inclusion in OTP-24.

**Comment by garazdawi** [comment]
I rebased your commit on latest master and also added a commit expanding the documentation a bit. I'll let this run one more night in tests and then merge.

**Comment by garazdawi** [comment]
Merged! Thanks!

**Pull request merged**
