### PR TITLE
filename join/split fixed for win32 share

### PR DESCRIPTION
**Pull request by c-bik**
#### Currently
 
```erlang
> filename:join("\\\\", "test").
"/test"
> filename:split("\\\\test").
["/","test"]
```

#### Fixed by this PR
```erlang
> filename:join("\\\\", "test").
"//test"
> filename:split("\\\\test").
["//","test"]
```

Also fixes `filelib:wildcard/1,2` for win32 share type paths

### CODE REVIEW

**Comment by c-bik** [comment]
Newbie, so not sure how to go about it. Please correct me if this is not the way things are done here.
Since its a been a day and I was hoping some kind of feedback as the PR passed the first test. @bufflig and @garazdawi requesting your kind attention to this PR as I noticed most win32 related works are from you in this module.

**Comment by dgud** [comment]
Just chill, we deal with pull requests when we have time. Might be today or in a couple of weeks, but it will be done eventually.

**Comment by c-bik** [comment]
@dgud Thanks for breaking the silence!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
It seems that your new code will accept "//" or "\\" in any position in a filename, not only at the beginning.

We will need test cases before we can consider including this patch in OTP. We have recently done a major clean up of test cases, so make sure that you rebase your patch on the `master` branch before adding the test cases to avoid merge conflicts.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
There seems to be a new merge commit added to this branch, but I don't see any new contents.

I will close this PR now. If/when you fix the issues I mentioned, please open a new pull request.

**Comment by c-bik** [comment]
Fine with me, thanks. I will create a new PR with fixes and tests.

**Pull request closed without merging**
