### PR TITLE
Don't make assumptions about build tools paths

### PR DESCRIPTION
**Pull request by binarin**
One more followup to https://github.com/erlang/otp/pull/1056 and
https://github.com/erlang/otp/pull/1023

This time it's about `/usr/bin/env` and `/bin/cp`:
- `/usr/bin/env` in `diameterc` was used to find the bootstrapped
  `escript` executable. Changed it to exlpicit call to `escript` in
  Makefile.
- `/usr/bin/env` and `/bin/cp` were referenced in documentation
  build/install process. Now full paths to this tools are injected using
  autoconf magic.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
Why can't you use /usr/bin/env? In the other patches that you reference you have changed to use /usr/bin/env to locate the perl program.

**Comment by binarin** [comment]
So the reason for all this is that I'm trying to make erlang buildable on NixOS in sandboxed mode without any additional patching. Sandboxed means that every dependency (including `env` executable) should be explicitly specified. `/usr/bin/env` is automatically patched in shebangs during installation process, but it didn't help in case when `env` is used as a part of a build process itself.

Perl patch was about `./otp_build tests`, which I was running in less restricted environment where `/usr/bin/env` was available. But you are right, it looks inconsistent. I think I should fix it.

**Comment by garazdawi** [comment]
What about all of the /usr/bin/env in erts/emulator/utils/*, why do they work?

**Comment by binarin** [comment]
I've checked a few scripts from there - they work because Makefile's invoke perl on them explicitly, like:
```
erts/emulator/Makefile.in
575:    $(gen_verbose)LANG=C $(PERL) utils/make_alloc_types -src $< -dst $@ $(ENABLE_ALLOC_TYPE_VARS)
585:    $(gen_verbose)LANG=C $(PERL) utils/make_driver_tab -o $@ -nifs $(NIF_OBJS) $(STATIC_NIF_LIBS) -drivers $(DRV_OBJS) $(STATIC_DRIVER_LIBS)
```

**Comment by garazdawi** [comment]
aha, ok. That explains it.

**Comment by binarin** [comment]
Added separate commit for perl/make_emakefile

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
