### PR TITLE
feat: Adds ssh_sftp:list_dir_details/2,3

### PR DESCRIPTION
**Pull request by isaacsanders**
https://bugs.erlang.org/browse/ERL-235?jql=project%20%3D%20ERL%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20ssh

### CODE REVIEW

**Comment by HansN** [comment]
Welcome First-Time Contributor!

THnak you, but documentation + a test case increases the likelihood to get the PR accepted :) See [Adding a new feature](https://github.com/erlang/otp/blob/master/CONTRIBUTING.md#adding-a-new-feature) in the wiki.

I can't handle this PR before Wednesday, since we have a code stop for OTP-23.0-rc3, then there is a less than two weeks window to get contributions into the OTP-23.0

**Comment by isaacsanders** [comment]
Any advice on compiling with LibreSSL?

**Comment by HansN** [comment]
The function returns `Details :: #ssh_xfer_attr{}`. This is an internal record in the ssh application since it is defined in an internal .hrl file in src.
If a record is returned from an API-function, it must be documented and exported in an include/X.hrl.

So either you need to do all of that, or preferably return some other datatype as a property list or a map.

The ssh_sftp:read_file_info returns a [file:#file_info{}](https://erlang.org/doc/man/file.html#type-file_info). Could that record be used for some of the data returned by list_dir_details?

**Comment by HansN** [comment]
Closed due to inactivity

**Pull request closed without merging**
