### PR TITLE
ERL-151: Make erl_tidy work on input file with tilda (~) character.

### PR DESCRIPTION
**Pull request by mbucc**
See http://bugs.erlang.org/browse/ERL-151 for a test case.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: ERL-151: Make erl_tidy work on input file with tilda (~) character.


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: ERL-151: Make erl_tidy work on input file with tilda (~) character.


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
this commit msg "ERL-151: Make erl_tidy work on input file with tilda (~) character." ends in a "."

**Comment by mbucc** [comment]
Just tried to rebase then ammend.  FAIL.  Is the terminating period blocking acceptance?

**Comment by dgud** [comment]
Could you add a testcase, for instance the one in the ERL-151.
No the period is not blocking.

**Comment by mbucc** [comment]
Sure.

Is ```otp/lib/syntax_tools/test/syntax_tools_SUITE.erl``` where I should add the new test?

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Remove array brackets that got in by mistake.
Add unit test that duplicates bug.
ERL-151: Make erl_tidy work on input file with tilda (~) character.


----------------

I am a script, I am not human 

----------------

**Comment by mbucc** [comment]
@dgud: test committed.

**Comment by dgud** [comment]
I saw that, we didn't have time to look at this before code freeze.

**Comment by uabboli** [comment]
A few things should be fixed before the patch is merged:

 - Replace 'tilda' with 'tilde'.

 - Squash all commits together.

 - Let the commit message begin with "syntax_tools: ".
   You can mention ERL-151 in the commit message
   ("ERL-151" will also be included in the final branch name).

 - Even if it's not strictly necessary, the test module should
   compile.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Remove array brackets that got in by mistake.
Add unit test that duplicates bug.
ERL-151: Make erl_tidy work on input file with tilda (~) character.


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
Merged commit 0969ecad9e2978bacb7b27f663cd16aa5ea6c460 into erlang:maint.

**Pull request closed without merging**
