### PR TITLE
Remove unused private keys in the SSH engine suite

### PR DESCRIPTION
**Pull request by lexmag**
ECDSA is not supported in crypto:privkey_to_pubkey/2.

### CODE REVIEW

**Comment by HansN** [comment]
Please separate the single commit into two: one that solves the problem and one with the formatting changes.

**Comment by lexmag** [comment]
Done.

**Comment by HansN** [comment]
Please rebase this branch on maint so it could be tested for the next maint release.

**Comment by HansN** [comment]
Closed due to inactivity.

**Pull request closed without merging**
