### PR TITLE
Teach Dialyzer call to funs `M:F/A` (literal M, F, A)

### PR DESCRIPTION
**Pull request by lucafavatella**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lucafavatella** [comment]
I rebased on recent `maint` (that has #789 merged).

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
I think the patch looks OK.

**Pull request merged**
