### PR TITLE
Use inet_dist options when setting up TLS Dist proxy

### PR DESCRIPTION
**Pull request by tombriden**
When using SSL for a cluster, the inet_dist_listen_min/max options are ignored and the socket is bound  to whatever port the kernel gives it. This patch makes the 'World' socket in the tls dist proxy use the same options as the listener in lib/kernel/src/inet_tcp_dist.erl

### CODE REVIEW

**Comment by nox** [comment]
This lacks tests and documentation.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: tls_dist_proxy: enable reuseaddr in listen Options for World socket


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: tls_dist_proxy: enable reuseaddr in listen Options for World socket


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: tls_dist_proxy: enable reuseaddr in listen Options for World socket


----------------

I am a script, I am not human 

----------------

**Pull request closed without merging**
