### PR TITLE
Add missing dtrace return invocations

### PR DESCRIPTION
**Pull request by lrascao**
Some return paths were not going through dtrace
hooks so no function-return probes were being triggered
on dtrace/systemtap.

### CODE REVIEW

**Comment by lrascao** [comment]
this still isn't quite right, with this patch the `function-return` gets triggered however the mfa argument from the prob looks like it came from further up the call stack, maybe using the continuation pointer here wasn't the best choice?

**Comment by jhogberg** [comment]
Thanks for the PR!

If I'm reading this right, it ought to work if you move `DTRACE_RETURN_FROM_PC(c_p);` before `$RETURN()`

**Comment by jhogberg** [comment]
> Thanks for the PR!
> 
> If I'm reading this right, it ought to work if you move `DTRACE_RETURN_FROM_PC(c_p);` before `$RETURN()`

You'll want to pass the current stack pointer (`E`) to the macro as well, as the one on the process isn't up to date:

```diff
diff --git a/erts/emulator/beam/beam_emu.c b/erts/emulator/beam/beam_emu.c
index e8a0c666e3..435d309dc5 100644
--- a/erts/emulator/beam/beam_emu.c
+++ b/erts/emulator/beam/beam_emu.c
@@ -437,10 +437,10 @@ init_emulator(void)
         }                                                                                      \
     } while(0)
 
-#define DTRACE_RETURN_FROM_PC(p)                                                        \
+#define DTRACE_RETURN_FROM_PC(p, sp)                                                        \
     do {                                                                                \
         ErtsCodeMFA* cmfa;                                                                  \
-        if (DTRACE_ENABLED(function_return) && (cmfa = find_function_from_pc(cp_val((p)->stop[0])))) { \
+        if (DTRACE_ENABLED(function_return) && (cmfa = find_function_from_pc(cp_val((sp)[0])))) { \
             DTRACE_RETURN((p), cmfa);                               \
         }                                                                               \
     } while(0)
```
That ought to make the behavior equivalent to that of OTP 21.

**Comment by lrascao** [comment]
thanks for the pointer, tracing is now a little bit better, but still off by one, consider the following example, a simple gen_server:

`init(_Args) ->
    gen_server:cast(self(), init),
    {ok, #{counter => 0}}.

handle_call(_Request, _From, State) ->
    {reply, ok, State}.

handle_cast(init, State) ->
    erlang:send_after(2000, self(), ping),
    {noreply, State};
handle_cast(_Msg, State) ->
    {noreply, State}.

handle_info(ping, #{counter := Counter0} = State) ->
    ok = local_method(State),
    ok = ?MODULE:exported_method(),
    erlang:send_after(2000, self(), ping),
    {noreply, State#{counter => Counter0 + 1}};
handle_info(_Info, State) ->
    {noreply, State}.
`
and the follow dtrace script:

`erlang*:::global-function-entry
{
    printf("pid %s enter (global)  %s depth %d\n",
	   copyinstr(arg0), copyinstr(arg1), arg2);
    self->ts = timestamp;
}

erlang*:::local-function-entry
{
    printf("pid %s enter (local)  %s depth %d\n",
	   copyinstr(arg0), copyinstr(arg1), arg2);
    self->ts = timestamp;
}

erlang*:::function-return
/self->ts/
{
    printf("pid %s return %s depth %d\n",
	   copyinstr(arg0), copyinstr(arg1), arg2);
    @samples[copyinstr(arg1)] = quantize(timestamp - self->ts);
}
`

this is the output i'm seeing on one iteration:

` 2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:decode_msg/9 depth 12

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:handle_msg/6 depth 12

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:try_dispatch/3 depth 12

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:try_dispatch/4 depth 12

  2   3557 fixed_apply:global-function-entry pid <0.291.0> enter (global)  pool_perf_research_srv:handle_info/2 depth 21

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  pool_perf_research_srv:handle_info/2 depth 21

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  pool_perf_research_srv:local_method/1 depth 21

  2   3550     process_main:function-return pid <0.291.0> return pool_perf_research_srv:handle_info/2 depth 21

  2   3558 process_main:global-function-entry pid <0.291.0> enter (global)  pool_perf_research_srv:exported_method/0 depth 21

  2   3550     process_main:function-return pid <0.291.0> return pool_perf_research_srv:handle_info/2 depth 21

  2   3550     process_main:function-return pid <0.291.0> return gen_server:try_dispatch/4 depth 24

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:handle_common_reply/8 depth 24

  2   3560 process_main:local-function-entry pid <0.291.0> enter (local)  gen_server:loop/7 depth 24
`

**Comment by jhogberg** [comment]
That's consistent with OTP 21 as far as I can tell, the probe tells you which function is returned _to_ rather than which function is returned _from_.

We agree that the latter makes more sense, but there may be users that rely on the current (and rather confusing) behavior. We'll ask around to see if it can be changed in OTP 23.

The following should get you "return from:"

```diff
diff --git a/erts/emulator/beam/beam_emu.c b/erts/emulator/beam/beam_emu.c
index 9f8b56a5d5..4bc09a2e1a 100644
--- a/erts/emulator/beam/beam_emu.c
+++ b/erts/emulator/beam/beam_emu.c
@@ -517,10 +517,10 @@ init_emulator(void)
         }                                                                                      \
     } while(0)
 
-#define DTRACE_RETURN_FROM_PC(p)                                                        \
+#define DTRACE_RETURN_FROM_PC(p, i)                                                        \
     do {                                                                                \
         ErtsCodeMFA* cmfa;                                                                  \
-        if (DTRACE_ENABLED(function_return) && (cmfa = find_function_from_pc(cp_val((p)->stop[0])))) { \
+        if (DTRACE_ENABLED(function_return) && (cmfa = find_function_from_pc(i))) { \
             DTRACE_RETURN((p), cmfa);                               \
         }                                                                               \
     } while(0)
@@ -530,7 +530,7 @@ init_emulator(void)
 #define DTRACE_GLOBAL_CALL(p, mfa)       do {} while (0)
 #define DTRACE_GLOBAL_CALL_FROM_EXPORT(p, e) do {} while (0)
 #define DTRACE_RETURN(p, mfa)            do {} while (0)
-#define DTRACE_RETURN_FROM_PC(p)             do {} while (0)
+#define DTRACE_RETURN_FROM_PC(p, i)     do {} while (0)
 #define DTRACE_BIF_ENTRY(p, mfa)         do {} while (0)
 #define DTRACE_BIF_RETURN(p, mfa)        do {} while (0)
 #define DTRACE_NIF_ENTRY(p, mfa)         do {} while (0)
diff --git a/erts/emulator/beam/instrs.tab b/erts/emulator/beam/instrs.tab
index 38b1e5909b..c3a4180445 100644
--- a/erts/emulator/beam/instrs.tab
+++ b/erts/emulator/beam/instrs.tab
@@ -118,6 +118,7 @@ dealloc_ret.execute() {
     //| -no_next
 
     E = ADD_BYTE_OFFSET(E, num_bytes);
+    DTRACE_RETURN_FROM_PC(c_p, I);
     $RETURN();
     CHECK_TERM(x(0));
     DispatchReturn;
@@ -135,6 +136,7 @@ move_deallocate_return(Src, Deallocate) {
     Eterm src = $Src;
     E = ADD_BYTE_OFFSET(E, bytes_to_pop);
     x(0) = src;
+    DTRACE_RETURN_FROM_PC(c_p, I);
     $RETURN();
     CHECK_TERM(x(0));
     DispatchReturn;
@@ -380,8 +382,8 @@ i_call_fun_last(Fun, Deallocate) {
 
 return() {
     //| -no_next
+    DTRACE_RETURN_FROM_PC(c_p, I);
     $RETURN();
-    DTRACE_RETURN_FROM_PC(c_p);
     CHECK_TERM(r(0));
     HEAP_SPACE_VERIFIED(0);
     DispatchReturn;
@@ -676,6 +678,7 @@ move_window5(S1, S2, S3, S4, S5, D) {
 move_return(Src) {
     //| -no_next
     x(0) = $Src;
+    DTRACE_RETURN_FROM_PC(c_p, I);
     $RETURN();
     DispatchReturn;
 }
```

**Comment by lrascao** [comment]
thanks! that did the trick, i've updated the PR.

> We agree that the latter makes more sense, but there may be users that rely on the current (and rather confusing) behavior.

I started looking into this on 19.3 and it's not working there as well, not sure on the other versions though. My perception tells me that there is not a lot of people relying on this behaviour

**Comment by jhogberg** [comment]
We've decided to change the behavior in OTP 23 as `dtrace`/`systemtap` support is experimental. I suspected this could affect `LTTng` but that turned out not to be the case, so I've added it to our nightly tests now.

**Comment by lrascao** [comment]
👍

**Comment by lrascao** [comment]
note to future self: i've [backported this to 21.3](https://github.com/lrascao/otp/commits/support/21.3.x/bugfix/missing_dtrace_function_returns)

**Comment by ferd** [comment]
Re: the change in behaviour, I'm guessing looking at the sample scripts provided with OTP for dtrace and systemtap might be decent. From memory I've updated these in the past and based myself off of them and totally assumed that the return was the "return from" value. It probably worked accidentally when deeper-nested calls returned to the parent function.

**Comment by jhogberg** [comment]
Good point, the example and probe description (`erlang_dtrace.d`) should be updated to say that the MFA is the function returned from.

**Comment by lrascao** [comment]
rebased and pushed a commit with improved function call probe documention, can we assume that bif/bif-return will have the same behaviour (ie. mfa shows function returned from)?

**Comment by jhogberg** [comment]
> rebased and pushed a commit with improved function call probe documention

Great, can you update `erlang_dtrace.d` as well?

> can we assume that bif/bif-return will have the same behaviour (ie. mfa shows function returned from)?

Yes, they're "return from" as far as I can see.

**Comment by lrascao** [comment]
> Great, can you update erlang_dtrace.d as well?
done

**Comment by jhogberg** [comment]
Merged, thanks again for the PR!

**Pull request merged**
