### PR TITLE
Logger updates for Erlang/OTP 21.0

### PR DESCRIPTION
**Pull request by sirihansen**
This pull request contains all updates to Logger that are done between release candidate 2 and OTP-21. The pull request is published since some of the changes are not backwards compatible. The most important changes are listed here:

- The concept of "global log level"/"global configuration" is changed to "primary log level"/"primary configuration". Due to this, the name of some API functions are also changed:
```
get/set/update_logger_config  -> get/set/update_primary_config
add/remove_logger_filter -> add/remove_primary_filter
```
- Log events originating from `error_logger:info_report` and `error_logger:info_msg` now have level `notice` instead of `info`. 
- The default primary log level is changed from to `notice` (used to be `info`).  
- Earlier `info` level log events from STDLIB and Kernel are changed to `notice`, except progress reports which are still `info`
- Kernel parameter `logger_progress_reports` is removed. By default, progress reports are stopped by the primary log level, and can be enabled by changing that to `info` (e.g. using Kernel parameter `logger_level`)
- The atoms `all` and `none` are now valid level configurations.
- The default handler level is changed from `info` to `all`. This is to allow enabling of more verbose logging by only changing the primary log level.
- `logger:i/0,1` is removed. A new function, `get_config/0` replaces `i/0`. The pretty printing variant of `i/1` will probably be replaced in a later release.
- Some more functions for reading config are added, and some return values have changed (`HandlerId` and `Module` are no longer returned as separate parameters, as they always occur in the `Config` map with keys `id` and `module`, respectively)
- API for setting/reading module levels are extended a bit.
- The template configuration for the default formatter is updated. Nested keys are now specified as lists instead of tuples, and tuples are used in a similar way as in lager - to specify "if key exists - else".
- Logger no longer obeys the +W command line flag, but `error_logger` still does when sending events to its own event handlers.
- Handler specific configuration is now restricted to one key (`config`) in the handler config map. This has caused some changes to the built-in handlers, which earlier used their module names as keys in the map.
 - The type `logger:config()` is split into two separate types, `primary_config()` and `handler_config()`.
- Names of config parameters for overload protection in the built-in handlers are changed.
- Build-in handlers now print log events to inform that overload protection actions are taken, e.g. when dropping or flushing log events.

### CODE REVIEW

**Comment by tsloughter** [comment]
@sirihansen another useful function would be one to either reload all logger config settings from the application `logger` config or as an argument that is the same as the app env, like:

```
logger:update_handler_configs( [[{handler, default, logger_std_h,
      #{ formatter => { logger_formatter,
                                 #{ template => [time," ",pid," ",msg,"\n"]}}
       }}]}].
```

Issue is `rebar3 shell`where kernel is already started when we load the config the user has set. We can manually go through each one and use set/update handler config, but a single function and keeping the logic in logger module would be nicer :).

**Comment by garazdawi** [comment]
Hmm, I'm not 100% sure what you mean, but could logger:add_handlers/1 be used to achieve what you want? http://erlang.org/documentation/doc-10.0-rc2/lib/kernel-6.0/doc/html/logger.html#add_handlers-1

**Comment by tsloughter** [comment]
`add_handlers` won't work for the default handler, it errors because it will already exist after boot. An `update_handlers` that accepts the application like `add_handlers` does would solve it I think.

**Comment by garazdawi** [comment]
What if you configure the kernel default logger to be disabled at startup and then use `add_handlers`?

**Comment by tsloughter** [comment]
Hm, possible. We can add that to the escript vm args and to the rebar3 shell script `erl` command.

We likely need to then also setup the default handler if none is included in the config, and do this for shell, ct and eunit, but seems doable.

@ferd thoughts?

**Comment by ferd** [comment]
Since we boot from an escript, we don't get to choose the boot options -- the user does through stuff like flags and whatnot. Whatever we end up with, we'll probably need a set up where we take the current configured values, and find what needs to be added/removed to get to the config we want to apply.

Probably the same way we'd want to do it if it were for a live code upgrade with code and config changes.

**Comment by tsloughter** [comment]
@ferd we do get to choose the options for the escripts vm, `{escript_emu_args, "%%! +sbtu +A1\n"}.`

**Comment by tsloughter** [comment]
So we'd have, `{escript_emu_args, "%%! +sbtu +A1 -kernel logger '[{handler, default, undefined}]'\n"}.`

**Comment by tsloughter** [comment]
And since it just sets some env vars it works on pre-21 as well, as those kernel vars are just not used.

**Comment by garazdawi** [comment]
So, in conclusion, does `add_handlers` work for you? or would it still be nice with an `update_handlers`? One thing to keep in mind is that when you use `add_handlers` for the `default` handler, any logging events reported before the `default` handler is added is replayed in all installed handlers. So if you do `update_handlers`, any events that happen before then will be formatted according to the default formatting rules.

**Comment by ferd** [comment]
How much of a buffer is kept for that replay?

**Comment by garazdawi** [comment]
10 messages, after that a log message saying that N log messages were dropped is logged.

**Comment by sirihansen** [comment]
@ferd It's 10 log events (as in the old error_logger simple handler).

**Comment by sirihansen** [comment]
Just for info: I had to merge this due to code stop for the 21, so if `update_handlers` is needed, we will have to add it after the release.

**Comment by ferd** [comment]
I'll probably try my hand at something for rebar3 at some point during OTP 21. If I get something reasonable I may always try to submit it here to be included in mainline.

**Pull request merged**
