### PR TITLE
Do some minor optimizations of binary matching

### PR DESCRIPTION
**Pull request by bjorng**
This pull request contains two commits that do some minor optimizations of binary matching.

### CODE REVIEW

**Comment by michalmuskala** [comment]
Since the second commit starts tracking binaries in `beam_type`, would it make sense to also try tracking construction and the type checks with `is_binary` and `is_bitstring` and eliminating those checks where applicable?

This could be beneficial for elixir in some situations where the following syntax:
```ex
bar = "bar"
"foo #{bar} baz"
```
compiles into something like:
```erl
Bar = <<"bar">>,
<<"foo ",
  case Bar of
      Rewrite when is_binary(Rewrite) ->
          Rewrite;
      Rewrite->
          'Elixir.String.Chars':to_string(Rewrite)
  end/binary,
  " baz">>.
```

Tracking the binaries should allow eliminating the `case` completely.

**Comment by bjorng** [comment]
@michalmuskala Your example code is already fully optimized, even by the compiler in OTP 20. Here is the generated code:

```
{function, t, 0, 2}.
  {label,1}.
    {line,[{location,"t.erl",5}]}.
    {func_info,{atom,t},{atom,t},0}.
  {label,2}.
    {move,{literal,<<"foo bar baz">>},{x,0}}.
    return.

```

This optimization is done by `sys_core_fold` (it is a combination of constant propagation and simplification of a `case` with a constant expression).

Do you have any more complicated code that is not already optimized (where the built binary is not a literal)?

**Comment by fenollp** [comment]
I have a few though it's not about binaries per se:
```erlang
true() -> rand:uniform() < 1.0.
```
Very surprising to me:
```erlang
-record(r, {'1', '2', '3', '4', '5'}).
%% Does not compile to a literal but gets close!
d() -> (fun (R) -> setelement(1+2, R, "deux") end)(#r{}).
%% Not even trying:
c() -> (fun () -> setelement(1+2, #r{}, "deux") end)().
```

My personal favourite:
```erlang
-module(unfold4).
-export([a/0, b/0]).
%% Runtime: a() = b()
-record(r, {'1', '2', '3', '4', '5'}).

a() ->
    S = {some, "state"},
    Fs = [fun two/2
         ,fun three/2
         ,fun five/2
         ,fun 'TWO'/2
         ],
    lists:foldl(fun (F, R) -> F(R, S) end, #r{}, Fs).

two(R, _) -> setelement(1+2, R, "deux").
'TWO'(R, _) -> setelement(1+2, R, "DEUX").
three(R, _) -> setelement(1+3, R, "trois").
five(R, _) -> setelement(1+5, R, "cinq").

b() ->
    #r{'2' = "DEUX"
      ,'3' = "trois"
      ,'5' = "cinq"
      }.
```
There are more [in these HRLs](https://github.com/fenollp/erlscp/tree/master/test/asm_data) ;)

**Comment by michalmuskala** [comment]
@bjorng I'm sorry, my example was a bit too simplistic. Here's a better one:

```erl
-module(test).

-export([test/1]).

test(Bar) when is_binary(Bar) ->
    <<"foo ",
      case Bar of
          Rewrite when is_binary(Rewrite) ->
              Rewrite;
          Rewrite ->
              'Elixir.String.Chars':to_string(Rewrite)
      end/binary,
      " baz">>.
```

Another one would be:
```erl
-module(test).

-export([test/1]).

test(Arg) ->
    Bin = <<Arg>>,
    <<"foo ",
      case Bin of
          Rewrite when is_binary(Rewrite) ->
              Rewrite;
          Rewrite ->
              'Elixir.String.Chars':to_string(Rewrite)
      end/binary,
      " baz">>.
```

I tried compiling it on current master and it wasn't optimised. That's why I mentioned tracking binary construction (should solve second example) and the `is_binary` and `is_bitstring` checks (which should solve the first one).

**Comment by bjorng** [comment]
@michalmuskala I have updated the optimization so that the `case` is now optimized away in both of your examples. I have also added a new commit that separates the simplification of instructions from updating the type database.

**Comment by michalmuskala** [comment]
That looks great, thank you!

**Pull request merged**
