### PR TITLE
public_key: Add support for crypto engine in sign/3 and verify/3

### PR DESCRIPTION
**Pull request by erauer**
Add support for using crypto engine in `public_key:sign` and `public_key:verify`. Relies heavily on existing support in `crypto` so changes are minor. 

Please let me know of any additional changes or tests that I need to add.

### CODE REVIEW

**Comment by garazdawi** [comment]
Hello! The github actions fail when building the documentation for this PR. You need to update the public_key.xml file to include the new type that you have created.

**Comment by erauer** [comment]
@garazdawi Thanks, I've started running the actions on my fork and will try and address this weekend.

**Comment by HansN** [comment]
@erauer have you had time to fix the update of the public_key.xml file?

**Comment by erauer** [comment]
@HansN I haven't had time to do the updates. I'll close this for now and will reopen when I have the CI tests passing.

**Comment by HansN** [comment]
@erauer I'm looking forward to the reopening!

**Pull request closed without merging**
