### PR TITLE
erts: Add garbage_collection_info to process_info/2

### PR DESCRIPTION
**Pull request by garazdawi**
This info request returns greater details about the current gc state. For some reason this information was previously only available as trace messages.

Suggestions on a better name than garbage_collection_info would be greatly appreciated.

### CODE REVIEW

**Comment by andrejlamov** [comment]
Awesome. :thumbsup:

**Comment by psyeugenic** [comment]
What about just appending the additional information to the already existing 'garbage_collection' info?

**Comment by garazdawi** [comment]
@psyeugenic I didn't want it to be part of erlang:process_info(self()) as that is used a lot in the shell and would add 11 new lines to that output. And it is not very common that you would want to know these details.

**Comment by psyeugenic** [comment]
I think taking that hit is better than an additional option .. but that just my 2 cent opinion. If you take your route you better come up with an awesome option name =D

**Comment by andrejlamov** [comment]
Is it possible to add major_gcs?

Experimented a bit with it [here](https://github.com/andrejlamov/otp/commit/deb4504b01d44b614c16b68f871821f288d6fb78), but not sure about correctness. Had to add a new variable to ``struct process``.

**Comment by psyeugenic** [comment]
Possible but I wouldn't agree with it. First, with Uint16 it would probably wrap pretty quickly rendering the value fairly useless. Using an Uint64 counter makes the PCB larger which isn't good either. When would you need it? Anyway, it shouldn't be in this PR.

**Comment by andrejlamov** [comment]
To put the number of minor gcs into perspective, since the ```gen_gcs``` counter is reset after each major collection.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
