### PR TITLE
Replace ref() with reference() in inets docs

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by kostis** [comment]
This is a good change. However, why not go one step further and add these as type specifications instead of just comments?  (Similar, for many/all other commented out types.)

**Comment by IngelaAndin** [comment]
This is old code and we would happily accept changes that modernises it the way Kostis suggests.

**Comment by kostis** [comment]
IIn https://github.com/erlang/otp/blob/maint/lib/inets/src/http_client/httpc_handler.erl#L792 are the first two clauses of `code_change` really needed these days?  The first one in particular is not at all type-friendly.

**Comment by IngelaAndin** [comment]
No they can be removed. We only support soft upgrade in a short perspective then the default becomes restart_application.

**Comment by kostis** [comment]
Did not know how to add to this so created a new PR (#1188).

**Comment by IngelaAndin** [comment]
I will close this on in favour of #1188

**Pull request closed without merging**
