### PR TITLE
Add CRL cache module for OpenSSL-style CRL directories

### PR DESCRIPTION
**Pull request by legoscia**
OpenSSL comes with a script called `c_rehash` that, given a directory full of CRL files, creates symlinks based on issuer name hashes, such that a program can easily locate the right CRL given a certificate issuer name. This functionality is used e.g. in Apache when specifying the `SSLCARevocationPath` configuration directive. This pull request adds the same functionality to the `ssl` application, in a module called `ssl_crl_hash_dir`.

This pull request changes the behaviour `ssl_crl_cache_api` (introduced in 18.0), adding an issuer argument to the `lookup` function. That seemed to be the only reasonable way to implement this extension (see additional comments in the commit message); hopefully there are not yet that many behaviour implementations that would need changing.

I added the functions that generate hashes from issuer names to the `public_key` module, as that seemed to be a logical place for them, many functions manipulating certificates already being present there.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I understand why you want to make the API change, we are contemplating if we can live with it.  
I cherry-picked the typo commits and they should turn up on github at the next push of our internal repo.

**Comment by IngelaAndin** [comment]
We now have some questions and reflections.

* The documentation typos have been included in the upcoming release, so you can drop those commits.

* This is a fairly new big feature that potentially will be not backwards compatible so we want this
for OTP-19. (Current master)

* Would it not be possible to keep the old lookup  with two arguments for those that do not want to use this new feature? Maybe phase it out. 

* The functions that you added to public_key how hard are they tied to OpenSSL? We would prefer if
they not be called openssl_* . I know there are some ssh_* functions and they are called so since they parse the openSSH file format.  If the functions are not too tightly coupled to OpenSSL but provides the same kind mechanism as OpenSSL does then it could more easily extened or changed if we do not tie it OpenSSL.  

* We think that you can improve the readability of this type of code  by using the bit syntax

  HashThis = encode_name_for_openssl_hash(Name),
  <<A, B, C, D, _/binary>> = crypto:hash(sha, HashThis),
    HashValue = (D bsl 24) bor
        (C bsl 16) bor
        (B bsl 8) bor
        A,
    lists:flatten(io_lib:format("~8.16.0b", [HashValue])).

**Comment by legoscia** [comment]
I opened #982, with patches against `master`, superseding this pull request.

**Pull request closed without merging**
