### PR TITLE
ssl: SNI server support (master)

### PR DESCRIPTION
**Pull request by fqj1994**
reopen ("https://github.com/erlang/otp/pull/574") against master branch rather than maint branch.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
One last thing in ssl.erl there also needs  to be a
-deprecated({connection_info, 1, next_major_release}). 
I forgot about it too :(  Could you please add it?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fqj1994** [comment]
@IngelaAndin 
done

**Comment by fqj1994** [comment]
@IngelaAndin 

@labria suggested to implement a feature allow ssl module to call external module's functions to update ssl options for different domains rather than a predefined sets of certs. 

It looks good to me, how do you think of that? If it's good for you, He or I will manage to implement that. And is it proper for another pull request or just adding new commits in this PR?

**Comment by IngelaAndin** [comment]
Sounds like a good idea. As we have not merged this PR yet its viable to continue using this PR.
@fqj1994 what do you think?
@labria maybe  you should make a commit so that you can show us in detail how you would like the API.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by ferd** [comment]
This PR seems to get stuck. Is there anything that contributors could do to get involved and help?

**Comment by IngelaAndin** [comment]
We where fairly content when @labria suggested some sort of callback instead of the predefined set.
I thought it sounded like it might be a good idea, but then there has only been silence. I am considering getting more involved myself but time is short and there is a lot of other 18 stuff to do. So input form potential users of this functionallity if the API is good as it is or if maybe we should have some sort of callback could help getting it going.

**Comment by fqj1994** [comment]
@IngelaAndin 
just came back to school yesterday.
I'll try implement these callback in this weekend.

**Comment by essen** [comment]
@IngelaAndin I think that like ALPN, we should first start with plain options and then if needs arise add a callback in a future release. While it definitely sounds interesting here, I suspect in most cases people won't need a callback as most deployments operate on a fixed set of hostnames. I don't believe it should be either options or a callback, but rather options for normal case and callback for power users.

**Comment by fqj1994** [comment]
is `sni_fun` a okay name of these callback option?

**Comment by IngelaAndin** [comment]
It sound like it could be an ok name. What do you think yourself about the option, does it make sense to you? Maybe like @essen suggested we should have both possibilities. Either use your orginal option or the sni_fun option.  If we do not feel sure about the sni_fun in a couple of days we will consider taking the patch as it is now for 18.

**Comment by fqj1994** [comment]
@IngelaAndin 
The feature makes sense to me, but I don't have such circumstances with lots of domains and certificates.
I've just implemented a version, it should pass all tests.
@labria mentioned their production environment will require a lot of domains and certificates and certificate info will be loaded from database. These may slow down the process of SSL handshake as we need extra info from outside erlang VM to determine with certificate to send. Another approach I talked about to @labria is to provide a function to allow modifications of sni_hosts options on-the-fly (just like nginx reload), he personally prefers the callback function approach.
All discussions about these are welcome.

**Comment by fqj1994** [comment]
Of course the callback approach is more powerful. Like in @essen's cowboy, their can be a function reading the url mapping and returning different certs for different hostname dynamically as the cowboy's  routing hostmatch syntax is more complicated than the current sni_hosts.

**Comment by ferd** [comment]
Yeah, I'd be interested in exploring Erlang and SNI for large deploys with hundreds of thousands of hostnames as a possible target. A callback function that lets me do the lookup from wherever I want is likely something far better from my perspective than a nginx-like 'reload' mechanism where I'd be bound by the default implementation.

A default callback to specify a list of domains could be supported I guess, I'd just really like a way to override this.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I would prefer if the API could look as this: 

<tag>{sni_fun, SNIfun::fun()}</tag>
 <item><p>If the server receives a SNI (Server Name Indication) from the client,
  the sni_fun function will be called to retrive ssloptions() for
  the indicated server. These options will be will be merged into predefined
  ssloptions().</p>

  <p> The function should be defined as </p>

 <code>
    fun(ServerName :: string()) -> ssloptions() 
</code>

<p> Can be specified directly as a fun or as named fun module:function/1</p>

</item>

And then the case clause chcking the option can be changed to:

case OrigSSLOptions#ssl_options.sni_fun of
     {} ->
       proplists:get_value(SNIHostname, OrigSSLOptions#ssl_options.sni_hosts);
     SniFun ->
       SniFun(SNIHostname)
end.

**Comment by IngelaAndin** [comment]
Thanks :)  A suggestion on the documentation is that I think it would be clearer to say that they are mutely exclusive with each other than to say that they conflict.

**Comment by fqj1994** [comment]
@IngelaAndin 
I just added an error while handling ssloptions() to throw an error when both sni_hosts and sni_fun are specified. Making this exclusion not mute. So I documented a conflict in the documentation.
Code: https://github.com/fqj1994/otp/blob/7358ee6c63f4c6f4bd38dd0cd1862a57800acbaa/lib/ssl/src/ssl.erl#L737-L748

Do you prefer (throwing an error) or (suppressing the error, and mutely exclusive) ?

**Comment by IngelaAndin** [comment]
Hum sorry misspelled that, I  meant mutually exclusive e.i can not occur in the same time. So I think
the implementation shall be as you made it, but that I did not feel that the word "conflicts" in the documentation explained it in a clear way.

**Comment by fqj1994** [comment]
done

**Comment by IngelaAndin** [comment]
Grate, I have put this patch in approved which means that it still needs to run through our nightly/daily  tests before it can be merged, but we are getting there now.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fqj1994** [comment]
fixed a small problem in ssl_internal.h

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fqj1994** [comment]
Hello, any update?

**Comment by IngelaAndin** [comment]
The following tests are failing on serveral platfroms. We have not had time to figure out why yet,
it could be a test case problem.  At least some of these platforms run very old openssl versions.

ssl_sni_SUITE	 sni_match_fun	
ssl_sni_SUITE	 no_sni_header_fun	
ssl_sni_SUITE	 no_sni_header	

ssl_to_openssl_SUITE	erlang_server_openssl_client_sni_no_header	
ssl_to_openssl_SUITE	erlang_server_openssl_client_sni_no_match_fun	
ssl_to_openssl_SUITE	erlang_server_openssl_client_sni_match	
ssl_to_openssl_SUITE	erlang_server_openssl_client_sni_no_match	
ssl_to_openssl_SUITE	erlang_server_openssl_client_sni_match_fun

**Comment by fqj1994** [comment]
Can you provide a detailed log?
This looks wired for me, same test with _fun and without _fun should both fail or pass, as the only difference between them is use sni_fun or sni_hosts.

**Comment by IngelaAndin** [comment]
Here is one example of ssl_sni_SUITE:sni_match/1 

Options: [[{sni_hosts,[{"a.server", [{certfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/cert.pem"}, {keyfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/key.pem"}]}, {"b.server", [{certfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/cert.pem"}, {keyfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/key.pem"}]}]}, {ssl_imp,new}, {reuseaddr,true}, {certfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/cert.pem"}, {keyfile,"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/key.pem"}], [{server_name_indication,"a.server"}, {ssl_imp,new}, {reuseaddr,true}]]


*** User 2015-05-04 03:28:13.690 *** ssl_test_lib:63 ssl:listen(0, [{sni_hosts, [{"a.server", [{certfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/cert.pem"}, {keyfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/key.pem"}]}, {"b.server", [{certfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/cert.pem"}, {keyfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/key.pem"}]}]}, {ssl_imp,new}, {reuseaddr,true}, {certfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/cert.pem"}, {keyfile, "/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/key.pem"}])


*** User 2015-05-04 03:28:13.692 *** ssl:transport_accept({sslsocket,nil, {#Port<0.13016>, {config, {ssl_options,tls, [{3,0}], verify_none, {#Fun,[]}, #Fun,false,false,undefined,1, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/cert.pem">>, undefined, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/server/key.pem">>, undefined,[],undefined,<<>>,undefined,undefined, undefined,undefined,undefined, [<<0,57>>, <<0,56>>, <<0,53>>, <<0,22>>, <<0,19>>, <<0,10>>, <<0,51>>, <<0,50>>, <<0,47>>, <<0,9>>], #Fun,true,268435456,false,undefined, false,undefined,undefined,undefined,undefined,true, undefined, [{"a.server", [{certfile, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/cert.pem">>}, {keyfile, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/a.server/key.pem">>}]}, {"b.server", [{certfile, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/cert.pem">>}, {keyfile, <<"/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@saradas.2015-05-04_03.12.03/test.ssl_test.logs/run.2015-05-04_03.12.07/log_private/b.server/key.pem">>}]}], {},false,true,false,false, {ssl_crl_cache,{internal,[]}}}, [{reuseaddr,true}], <0.14158.0>, [{reuseaddr,true}, {packet_size,0}, {packet,0}, {header,0}, {active,false}, {mode,binary}], {gen_tcp,tcp,tcp_closed,tcp_error}, tls_connection}}})


*** User 2015-05-04 03:28:13.692 *** ssl_test_lib:189 ssl:connect("saradas", 56379)@test_server@saradas


*** User 2015-05-04 03:28:13.692 *** SSLOpts: [{server_name_indication,"a.server"},{ssl_imp,new},{reuseaddr,true}]


*** User 2015-05-04 03:28:13.693 *** ssl_test_lib:141 ssl:ssl_accept({sslsocket,{gen_tcp,#Port<0.13018>,tls_connection,<0.14158.0>}, <0.14161.0>}, infinity)


*** User 2015-05-04 03:28:13.803 *** ssl_test_lib:91 Server: apply(ssl_sni_SUITE,send_and_hostname,[{sslsocket, {gen_tcp,#Port<0.13018>, tls_connection,<0.14158.0>}, <0.14161.0>}])


*** User 2015-05-04 03:28:13.804 *** ssl_test_lib:96 Server Msg: "a.server"


*** User 2015-05-04 03:28:13.804 *** ssl_test_lib:194 Client: connected


*** User 2015-05-04 03:28:13.804 *** ssl_test_lib:200 Client: apply(ssl_sni_SUITE,recv_and_certificate,[{sslsocket, {gen_tcp,#Port<0.13017>, tls_connection,undefined}, <0.14160.0>}])


*** User 2015-05-04 03:28:17.812 *** ssl_test_lib:205 Client Msg: {badrpc,{'EXIT',{test_case_failed,{timeout,[],"K"}}}}


*** CT Error Notification 2015-05-04 03:28:17.813 *** test_server:ts_tc failed on line 1408 Reason: {test_case_failed,{{expected,{<0.14159.0>,{utf8String,<<"a.server">>}}}, {got, {<0.14159.0>, {badrpc, {'EXIT',{test_case_failed,{timeout,[],"K"}}}}}}}} Full error description and stacktrace




=== Ended at 2015-05-04 03:28:17
=== Location: [{test_server,ts_tc,1408},
              {test_server,run_test_case_eval1,984},
              {test_server,run_test_case_eval,926}]
=== Reason: {test_case_failed,
                     {{expected,{<0.14159.0>,{utf8String,<<"a.server">>}}},
                      {got,
                          {<0.14159.0>,
                           {badrpc,
                               {'EXIT',
                                   {test_case_failed,{timeout,[],"K"}}}}}}}}

**Comment by fqj1994** [comment]
I did find a problem at ssl_sni_SUITE.erl. A new commit is pushed. I'll squash it after you confirmed it works. It should fixes the timeout error on snl_sni_SUITE.

Can you provide an example of error log on the openssl suite?

**Comment by IngelaAndin** [comment]
Here you go!

*** User 2015-05-04 06:09:03.398 *** Options: [[{sni_hosts,[{"a.server", [{certfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/a.server/cert.pem"}, {keyfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/a.server/key.pem"}]}, {"b.server", [{certfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/b.server/cert.pem"}, {keyfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/b.server/key.pem"}]}]}, {ciphers,[{dhe_rsa,aes_256_cbc,sha}, {dhe_dss,aes_256_cbc,sha}, {rsa,aes_256_cbc,sha}, {dhe_rsa,'3des_ede_cbc',sha}, {dhe_dss,'3des_ede_cbc',sha}, {rsa,'3des_ede_cbc',sha}, {dhe_rsa,aes_128_cbc,sha}, {dhe_dss,aes_128_cbc,sha}, {rsa,aes_128_cbc,sha}, {rsa,des_cbc,sha}]}, {ssl_imp,new}, {reuseaddr,true}, {certfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/server/cert.pem"}, {keyfile,"/net/frumgar/ldisk/daily_build/18_master-opu_o.2015-05-03_20/test/test_server/ct_run.test_server@frumgar.2015-05-04_05.50.07/test.ssl_test.logs/run.2015-05-04_05.50.13/log_private/server/key.pem"}], "openssl s_client -connect frumgar:36490 -servername c.server"]


*** User 2015-05-04 06:09:03.404 *** ssl_test_lib:268 openssl unknown option -servername


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl usage: s_client args


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -host host - use -connect instead


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -port port - use -connect instead


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -connect host:port - who to connect to (default is localhost:4433)


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -verify depth - turn on peer certificate verification


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -cert arg - certificate file to use, PEM format assumed


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -certform arg - certificate format (PEM or DER) PEM default


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -key arg - Private key file to use, in cert file if


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl not specified but cert file is.


*** User 2015-05-04 06:09:03.405 *** ssl_test_lib:268 openssl -keyform arg - key format (PEM or DER) PEM default


*** User 2015-05-04 06:09:03.406 *** ssl_test_lib:268 openssl -pass arg - private key file pass phrase source


*** User 2015-05-04 06:09:03.406 *** ssl_test_lib:268 openssl -CApath arg - PEM format directory of CA's


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -CAfile arg - PEM format file of CA's


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -reconnect - Drop and re-make the connection with the same Session-ID


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -pause - sleep(1) after each read(2) and write(2) system call


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -showcerts - show all certificates in the chain


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -debug - extra output


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -msg - Show protocol messages


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -nbio_test - more ssl protocol testing


*** User 2015-05-04 06:09:03.407 *** ssl_test_lib:268 openssl -state - print the 'ssl' states


*** User 2015-05-04 06:09:03.414 *** ssl_test_lib:268 openssl -nbio - Run with non-blocking IO -crlf - convert LF from terminal into CRLF -quiet - no s_client output -ign_eof - ignore input eof (default when -quiet) -ssl2 - just use SSLv2 -ssl3 - just use SSLv3 -tls1 - just use TLSv1 -dtls1 - just use DTLSv1 -mtu - set the MTU -no_tls1/-no_ssl3/-no_ssl2 - turn off that protocol -bugs - Switch on all SSL implementation bug workarounds -serverpref - Use server's cipher preferences (only SSLv2) -cipher - preferred cipher to use, use the 'openssl ciphers' command to see what is available -starttls prot - use the STARTTLS command before starting TLS for those protocols that support it, where 'prot' defines which one to assume. Currently, only "smtp" and "pop3" are supported. -engine id - Initialise and use the specified engine -rand file:file:...


*** CT Error Notification 2015-05-04 06:11:03.402 *** ssl_test_lib:check_result failed on line 264 Reason: timetrap_timeout Full error description and stacktrace




=== Ended at 2015-05-04 06:11:03
=== Location: [{ssl_test_lib,check_result,264},
              {ssl_to_openssl_SUITE,erlang_server_openssl_client_sni_test,1286},
              {ssl_to_openssl_SUITE,erlang_server_openssl_client_sni_no_match,last_expr},
              {test_server,ts_tc,1408},
              {test_server,run_test_case_eval1,984},
              {test_server,run_test_case_eval,926}]
=== Reason: timetrap timeout

**Comment by IngelaAndin** [comment]
I also see these dialyzer warnings:

tls_connection.erl:402: (unused_fun)
    Function update_ssl_options_from_sni/2 will never be called
    tls_connection.erl:459: (pattern_match)
    The pattern [{ClientHello = {'client_hello', _, _, _, _, _, HelloExtensions}, _}] can never match the type [#certificate{} | #client_key_exchange{} | #finished{} | #next_protocol{}]

**Comment by fqj1994** [comment]
Is any error log on sni_no_header case?
The last log is due to too old openssl client (without -servername support).

**Comment by fqj1994** [comment]
As for the dialyzer warnings:

line 402: 
update_ssl_options_from_sni/2 is called at line 464:
`NewOptions = update_ssl_options_from_sni(State0#state.ssl_options, Hostname)`

line 459:
Packets is from tls_handshake:get_tls_handshake/2
menans: Packets: `[ tls_handshake() ]`
and ` -type tls_handshake() :: #client_hello{} | ssl_handshake:ssl_handshake().`
It should match with `#client_hello{}`


I don't know why dialyzer reports these warnings.

**Comment by IngelaAndin** [comment]
Yes that was my guess, but I have not had time to look into it further.  We need to make 
sni test cases be skipped for old openssl versions as we need to test such platforms too.

You should be able to do something similar to ssl_to_openssl_SUITE:check_openssl_npn_support/1

**Comment by IngelaAndin** [comment]
Dialyzer often catches errors even though it is not always evident at first glance what the error is, but it could also be a spec that is wrong. I will help you analyze them if they persist after your new changes.

**Comment by fqj1994** [comment]
updated. Could you please check whether there're failing cases?
Thanks

**Comment by IngelaAndin** [comment]
error log for sni_header case looks the same as for sni_match.  I will know tomorrow as all test are
run on the various platforms during the night. I will let you know.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
The check for OpenSSL support works fine. 
Some of the other tests still fail now with a new error.

=== Ended at 2015-05-05 04:50:48
=== Location: [{test_server,ts_tc,1408},
              {test_server,run_test_case_eval1,984},
              {test_server,run_test_case_eval,926}]
=== Reason: {test_case_failed,
                     {{expected,{<0.13279.0>,{utf8String,<<"a.server">>}}},
                      {got,{<0.13279.0>,{printableString,"a.server"}}}}}

Seems to be some kind of encoding problem.

**Comment by IngelaAndin** [comment]
Many of the failing platforms run really old versions of OpenSSL, that is used to generate the certificates for the tests. The newest versions with the problem is  
OpenSSL 1.0.0j-fips OpenSSL 1.0.1f both most failing platforms use OpenSSL 0.9.8*
Maybe the solution is to let the test case accept both >,{utf8String,<<"a.server">>} and {printableString,"a.server"} ?!

**Comment by fqj1994** [comment]
I updated the test to make it compatible to both printableString and utf8String.
Wouldn't the content in `rdnSequence` independent to the platforms?

**Comment by IngelaAndin** [comment]
Well independent of platforms yes, independent of OpenSSL version well not necessarily. 
I do not of the top of may head know when they added unicode support, but it is not very surprising that older versions may use printableString instead of utf8String when creating some parts
of the rndsequence in a certificate.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fqj1994** [comment]
Is everything good now?

**Comment by IngelaAndin** [comment]
It is much better but not good yet. I am looking into the dialyzer warnings and I am refactoring the code to fix it but I have a few other things to do too, so I am not sure if I will finish it today. But I think
we can manage in time for 18.

**Comment by IngelaAndin** [comment]
I eliminated the dialyzer warnings and have included my version of your branch for rc_2. There is
still some test cuddling to do, nothing that fails on all platforms. I think it is a timing glitch in the test cases, I will investigate and let you know how it goes.

**Comment by IngelaAndin** [comment]
It was a test case "flaw" test case code. You used a utility function in ssl_test_lib  that depending on timing could consume more messages than you had in mind. I have fixed the test case. Thank you for your contribution, it will be in 18.

**Pull request closed without merging**
