### PR TITLE
Fixes ERL-675 RSA options rsa_mgf1_md, rsa_oaep_md, and rsa_oaep_label do not work.

### PR DESCRIPTION
**Pull request by stevegraham**
PR #838, which reimplemented various parts of the crypto application to use OpenSSL EVP APIs was merged manually. During the manual merge the macro define for HAVE_RSA_OAEP_MD was lost. The result being that setting rsa_mgf1_md and rsa_oaep_md for any other value than sha causes the nif to return not_sup.

Support for configurable MGF1 digests and OAEP labels is available in OpenSSL version 1.1.0, a cursory look at libressl does not seem to reveal support so it is not added in this PR.

The defective functionality has been returned by defining HAVE_RSA_OAEP_MD alongside HAVE_CHACHA20_POLY1305, i.e. OpenSSL >= 1.1.0 and NOT libressl.

### CODE REVIEW

**Comment by stevegraham** [comment]
cc @potatosalad

**Comment by RaimoNiskanen** [comment]
Great finding!

Can you please refactor the white-space changes into a separate commit?

**Comment by stevegraham** [comment]
Apologies. My editor was configured to chomp whitespace on save. Now fixed.

**Comment by RaimoNiskanen** [comment]
I know this might be a tall order, but could you also write at test case for this?

**Comment by stevegraham** [comment]
You're right. It is a tall order. What would you be looking for in the test cases?

**Comment by RaimoNiskanen** [comment]
Well, I have have not had time to really understand the implications of this bug, but you said the symptom was "that setting rsa_mgf1_md and rsa_oaep_md for any other value than sha causes the nif to return not_sup", so I do not know if it would be possible to test that it does not return `not_sup`, under some precondition that the separate features are supported...  Maybe?

**Comment by RaimoNiskanen** [comment]
We routinely ask for a test case, but if is to hard to write, so be it.

**Comment by stevegraham** [comment]
> so I do not know if it would be possible to test that it does not return not_sup, under some precondition that the separate features are supported...

I don't think this is a valuable test, i.e. the test would still pass with any garbage output other than the notsup atom. A valuable test would be asserting that a plaintext can be encrypted with OAEP padding and arbitrary digests, but I don't see a precedent for this elsewhere in the codebase. Having said that I think it would be a good idea. 

> Well, I have have not had time to really understand the implications of this bug

The implication is some functionality is broken and has never worked. Even in the absence of a test case I think it's valuable to merge. I defer to Core to make that call however.

**Comment by HansN** [comment]
@stevegraham  I agree to your comment about test case for this fix, I'll accept it without a test case this time.
The fix in the PR is valuable, but could you rebase it to the maint branch instead?  In such a case this error correction will be released in 21.1 now in September. The master branch will not be released until June next year (22.0).

**Comment by stevegraham** [comment]
Closing this PR in favour of #1899, which branches from `maint`

**Pull request closed without merging**
