### PR TITLE
No longer support OTP 19 beam files in Dialyzer

### PR DESCRIPTION
**Pull request by josevalim**
This is a follow up to #1367 that removes support for old beam files from Dialyzer. It should be merged after OTP 20 is released. Or even OTP 21 depending on how long we want to support old beams in Dialyzer.

I am submitting it now so we don't forget to clean up the code in the future. If you would prefer this to be moved elsewhere (for example JIRA), please let me know.

### CODE REVIEW

**Comment by josevalim** [comment]
The commit fails because the preloaded files have not yet been updated in master to use the new chunk.

**Comment by bjorng** [comment]
I have now updated the preloaded files.

**Comment by josevalim** [comment]
This PR can now be merged into master if desired. If merged, BEAM files from OTP 19/18/... won't work with dialyzer on Erlang 21 (i.e. they will have to be recompiled).

**Comment by uabboli** [comment]
Merged commit e8a2cae09282b25a8eda9b6f04876e23a854336b into erlang:master.

**Pull request closed without merging**
