### PR TITLE
Lookup of key/value in dictionary using process_info/2

### PR DESCRIPTION
**Pull request by rickard-green**
Support for looking up a value associated with a specific key in the process dictionary of a process using `process_info/2`. For example, `{{dictionary, Key}, Value} = process_info(Pid, {dictionary, Key})`.

### CODE REVIEW

**Comment by lhoguin** [comment]
Hello! I am wondering how efficient this is, considering this enables out of band communication. Sometimes all we want from a process is just a value, so if that value can be taken from the dictionary directly instead of querying the process... Also I wonder if getting a process dictionary value from an hibernated process wakes it up. Thank you!

**Comment by garazdawi** [comment]
> I am wondering how efficient this is, considering this enables out of band communication.

It is a bit more efficient than doing gen_server call, how much is hard to say without benchmarking. They use the same internal queue system, so it is the code in gen_server that adds the overhead, not the actual handling of the request. If you have a long messages queue though this will somewhat skip the line, so the latency may be alot shorter.

> Also I wonder if getting a process dictionary value from an hibernated process wakes it up.

Any `process_info/2` request will leave the process hibernated, this includes `dictionary`.

**Comment by lhoguin** [comment]
> Any `process_info/2` request will leave the process hibernated, this includes `dictionary`.

That is great news, thank you! We have been suffering from hibernation wake-up issues in the past, where too many hibernated processes get woken up for metrics and whatnot. This may help in at least some cases. Thank you!

**Comment by garazdawi** [comment]
> That is great news, thank you! We have been suffering from hibernation wake-up issues in the past, where too many hibernated processes get woken up for metrics and whatnot. This may help in at least some cases. Thank you!

There have been (and might still be) bugs in this area, but it is meant to not wake up processes. If you find any case where it does, please report them.

**Comment by lhoguin** [comment]
Sorry if I wasn't clear. Our issues are due to messages waking the processes. I'm not aware of `process_info/2` doing that.

**Pull request merged**
