### PR TITLE
Include Merl in Syntax Tools

### PR DESCRIPTION
**Pull request by richcarl**
The Merl library has been stable for quite some time now and has several users (and no known bugs). It's really just a simpler way of working with erl_syntax parse trees, and making it a part of syntax_tools will make metaprograming and run-time code generation a standard feature of the Erlang/OTP distribution.

### CODE REVIEW

**Comment by vladdu** [comment]
I'm all for brackets, too.

**Comment by p1er** [comment]
@richcarl has done great work all these years with erlang, hipe and merl, but I really think the brackets solution is much better. I hope the OTP team takes a serious look at brackets.

**Comment by erlanger** [comment]
It takes a great man to realize that somebody elses solution is better than his own, I think @richcarl is that kind of person. I hope he embraces _brackets_ as **his own** project and makes it robust and fast.

**Comment by richcarl** [comment]
I finally had time to take a good look at the brackets suggestion, and I wrote my comments over there. In brief, I like the idea of metaprogramming as part of the language itself, but there are lots of things you have to get right in order to do that (and I don't have the time to work on it myself even if I think it would be fun). Meanwhile, Merl works well, and should really be integrated with syntax tools so that you can rely on it - I'd e.g. like to be able to use Merl to improve things in Igor and erl_tidy. It's a single module (and a small header file) and doesn't interfere with anything else.

**Comment by richcarl** [comment]
Ping?

**Comment by tolbrino** [comment]
I agree with @richcarl and would like to see Merl included before any other (better) solution is pursued. The short-term gains are tangible.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
We discovered some issues when we merged this branch to master. Please rebase this branch on top of the latest master and fix the issues:

* The type erl_scan:location() has been deprecated. The type is now in erl_anno (the compiler warning message will remind you about this).

* There is a call from merl to erl_syntax:record_access/2. That function has been removed on master.

* There are also 3 dialyzer warnings (4 if you turn on the option warn_unmatched_return).

**Comment by richcarl** [comment]
Do you have a particular way of running dialyzer on the OTP codebase so I can reproduce the warnings?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
I run dialyzer like this. (My PLT only has erts, kernel, and stdlib, so there is one warning for an unknown function in compiler.)

```
$ PATH=$ERL_TOP/bin:$PATH dialyzer -Wunmatched_returns --apps syntax_tools
  Checking whether the PLT /home/bjorn/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
merl.erl:340: Expression produces a value of type {'error','badarg' | 'badfile' | 'native_code' | 'nofile' | 'not_purged' | 'on_load' | 'sticky_directory'} | {'module',atom() | tuple()}, but this value is unmatched
merl.erl:552: Function parse_error/1 has no local return
merl.erl:554: The pattern {{L, C}, M, R} can never match the type {integer(),atom() | tuple(),_}
merl.erl:1059: Function fail/1 has no local return
Unknown functions:
  compile:noenv_forms/2
 done in 0m44.27s
done (warnings were emitted)
```

**Comment by richcarl** [comment]
Thanks, reproduced locally. The warning on 554 is apparently because erl_parse:error_info() is defined as {erl_scan:line(),...}, not {erl_scan:location(), ...}, which seems wrong. Not sure if it's worth trying to fix that as part of this branch.

**Comment by bjorng** [comment]
Not sure about this. @uabboli: Is the spec for erl_parse:error_info() correct?

**Comment by uabboli** [comment]
@bjorng: You probably need to generate a new erl_parse.erl. And pehaps rebase.

**Comment by richcarl** [comment]
@uabboli @bjorng In the latest master, erl_parse.yrl still contains this:
    %% XXX. To be refined.
    -type error_info() :: {erl_anno:line(), module(), error_description()}.

**Comment by bjorng** [comment]
Yes, it seems that the spec is wrong. The first element should probably be erl_anno:location(). We will fix that in a separate branch. Ignore the warning at line 554 for now.

**Comment by richcarl** [comment]
Rebased and fixed warnings and a couple of minor doc errors.

**Comment by bjorng** [comment]
Thanks! We will test it in our daily builds.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
There are only a few minor problems left:

In an edoc comment in merl.erl there is the following text: "@see tree/2". But there is no tree/2.

merl and merl_transform both contain "coding: latin-1" comment. We have rule to encode all files as utf-8 in the otp repository and to not use any "coding:" comments.

**Comment by richcarl** [comment]
Fixed.

**Comment by bjorng** [comment]
Thanks! Re-fetched.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Merged.

**Pull request closed without merging**
