### PR TITLE
Delay creation of stack frames

### PR DESCRIPTION
**Pull request by bjorng**
`v3_codegen` currently wraps a stack frame around each clause in a function (unless the clause is simple without any `case` or other complex constructions).
    
Consider this function:
    
    f({a,X}) ->
        A = abs(X),
        case A of
            0 ->
                {result,"0"};
            _ ->
                {result,integer_to_list(A)}
        end;
    f(_) ->
        error.
    
The first clause needs a stack frame because there is a function call to `integer_to_list/1` not in the tail position. `v3_codegen` currently wraps the entire first clause in stack frame.
    
We can delay the creation of the stack frame, and create a stack frame in each arm of the `case` (if needed):
    
    f({a,X}) ->
        A = abs(X),
        case A of
            0 ->
            %% Don't create a stack frame here.
                {result,"0"};
            _ ->
            %% Create a stack frame here.
                {result,integer_to_list(A)}
        end;
    f(_) ->
        error.
    
There are pros and cons of this approach.
    
The cons are that the code size may increase if there are many `case` clauses and each needs its own stack frame. The allocation instructions may also interfere with other optimizations, but new optimizations also introduced in this pull request will mitigate most of those issues (see the individual commit messages for a description of those optimizations).
    
The pros are the following:
    
* For some clauses in a `case`, there is no need to create any stack frame at all.
    
* Often when moving an allocation instruction into a `case` clause, the slightly cheaper 'allocate' instruction can be used instead of `allocate_zero`. There is also the possibility that the allocate instruction can be be combined with a `test_heap` instruction.
    
* Each stack frame for each arm of the `case` will have exactly as many slots as needed.

### CODE REVIEW

**Comment by bjorng** [comment]
@michalmuskala Have you run your version of otp-diffable-asm with this pull request? Does it look good?

**Comment by michalmuskala** [comment]
I think there's a bug on the branch. The following code does not work correctly (this is taken from Elixir's mix):
```elixir
defmodule Test do
  def env_path(config) do
    build = config[:build_path] || "_build"

    case config[:build_per_environment] do
      true ->
        Path.expand("#{build}/#{Mix.env()}")

      false ->
        Path.expand("#{build}/shared")

      other ->
        Mix.raise("The :build_per_environment option should be a boolean, got: #{inspect(other)}")
    end
  end
end
```
When called as `Test.env_path([build_per_environment: false])` it fails with `badarg` instead of returning `"<cwd>/_build/dev"`
When translated directly to erlang it is:
```erlang
-file("test.ex", 1).

-module('Elixir.Test').

-compile(no_auto_import).

-export([env_path/1]).

env_path(Vconfig@1) ->
    Vbuild@1 =
        case 'Elixir.Access':get(Vconfig@1, build_path, nil) of
            _@1
                when
                    _@1 =:= nil
                    orelse
                    _@1 =:= false ->
                <<"_build">>;
            _@2 ->
                _@2
        end,
    case 'Elixir.Access':get(Vconfig@1, build_per_environment, nil) of
        true ->
            'Elixir.Path':expand(<<case Vbuild@1 of
                                       Vrewrite@1
                                           when is_binary(Vrewrite@1) ->
                                           Vrewrite@1;
                                       Vrewrite@1 ->
                                           'Elixir.String.Chars':to_string(Vrewrite@1)
                                   end/binary,
                                   "/",
                                   case 'Elixir.Mix':env() of
                                       Vrewrite@2
                                           when is_binary(Vrewrite@2) ->
                                           Vrewrite@2;
                                       Vrewrite@2 ->
                                           'Elixir.String.Chars':to_string(Vrewrite@2)
                                   end/binary>>);
        false ->
            'Elixir.Path':expand(<<case Vbuild@1 of
                                       Vrewrite@3
                                           when is_binary(Vrewrite@3) ->
                                           Vrewrite@3;
                                       Vrewrite@3 ->
                                           'Elixir.String.Chars':to_string(Vrewrite@3)
                                   end/binary,
                                   "/shared">>);
        Vother@1 ->
            'Elixir.Mix':raise(<<"The :build_per_environment option sho"
                                 "uld be a boolean, got: ",
                                 ('Elixir.Kernel':inspect(Vother@1))/binary>>)
    end.
```

I'll try compacting it to a minimal erlang example that would also fail.

**Comment by michalmuskala** [comment]
Here's a somewhat minimized erlang example:
```erlang
-module(test).

-export([env_path/2]).

env_path(Arg1, Arg2) ->
    Build =
        case get(Arg1, build_path, nil) of
            X when X =:= nil orelse X =:= false -> <<"_build">>;
            X -> X
        end,
    case id(Arg2) of
        true ->
            id(<<case Build of
                     Rewrite when is_binary(Rewrite) ->
                         Rewrite;
                     Rewrite ->
                         id(Rewrite)
                 end/binary,
                 "/",
                 case foo() of
                     Rewrite when is_binary(Rewrite) ->
                         Rewrite;
                     Rewrite ->
                         id(Rewrite)
                 end/binary>>);
        false ->
            id(<<case Build of
                     Rewrite when is_binary(Rewrite) ->
                         Rewrite;
                     Rewrite ->
                         id(Rewrite)
                 end/binary,
                 "/shared">>);
        Other ->
            io:printf(<<"The :build_per_environment option should be a "
                        "boolean, got: ~w~n">>,
                      [Other])
    end.

foo() ->
    <<"foo">>.

get(List, Key, Default) ->
    case lists:keyfind(Key, 1, List) of
        {_,Value} ->
            Value;
        false ->
            Default
    end.

id(Arg) ->
    Arg.
```

When called as `test:env_path([], false)` fails with `badarg` instead of returning `<<"_build/shared">>`

**Comment by bjorng** [comment]
Thanks for the minimal example!

As as temporary fix, I have reverted the commit that `git bisect` pointed out as the first bad commit. I will investigate the bug more thoroughly tomorrow.

**Comment by michalmuskala** [comment]
Ok, now I can compile elixir 🙂 

Looking at the diffs, I don't see anything bad. In many cases stack frames are eliminated completely, in others reduced. In some cases `allocate_zero` is moved further, and changed to `allocate` with a couple `init` instructions. In some cases there are more `allocate` instructions, but this is expected since they are more precise. There's also quite a few `get_tuple_element` changed to `move,nil`

In some places, I found `{allocate_zero,0,X}` and `{deallocate,0}` - are those valid? I even found `{allocate,0,0}`.

Here's a full diff: [elixir-diff.txt](https://github.com/erlang/otp/files/1560034/elixir-diff.txt)

**Comment by bjorng** [comment]
> In some places, I found `{allocate_zero,0,X}` and `{deallocate,0}` - are those needed? I even found `{allocate,0,0}`.

Yes, they are needed to save the continuation pointer on the stack before calling another function. (The `call` instruction save the continuation pointer to `c_p->cp`, not to the stack.)

**Comment by bjorng** [comment]
I have pushed a correction for the bad commit.

**Comment by michalmuskala** [comment]
I don't think I see any changes with and without that commit.

**Pull request merged**
