### PR TITLE
hipe: the basic HiPE tests

### PR DESCRIPTION
**Pull request by kostis**
This is a big portion of the old 'basic_tests' of the HiPE compiler.

The tests have been enhanced with some 'sanity_tests' that check
that the native code compiler does not exhibit any bad behavior.

While at it, added some more tests to the 'bs_SUITE'.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Use function from hipe module instead of a locally-defined one
Add function to prevent running these tests when testing the LLVM backend
More basic tests (and some tests that the HiPE compiler is not causing trouble)


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: ssl: Convert all test to use "ssl_test_lib:portable_open_port"


----------------

I am a script, I am not human 

----------------

**Comment by kostis** [comment]
It looks like your script complains about commit messages that are not part of this pull request.
If you want to force volunteers to adhere to it, the least you can do is to force *all* commits to OTP to also adhere to it!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
