### PR TITLE
inets: Remove obsolete code from httpd_serve_SUITE

### PR DESCRIPTION
**Pull request by jchristgit**
The bug requiring this workaround was fixed by fc63402c4448fada630ee77ee3577115319487eb and b813bc0b09b44d9b5ada70f153904c435c4b4aa1.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Currently inets master is having some problems,  taking this out of testing to possible rule this PR out.

**Comment by IngelaAndin** [comment]
@jchristgit  Yes I suspect that PR is related (but I am not sure it is the root cause). It looked fine when I merged it but we had some problems with some of our test machines that was not run.  It seems there is a problem with machines running FreeBSD (maybe it could be some kind or resource problem) . It manifests as 

```
  {error,
                     {failed_connect,
                         [{to_address,{"myhost",54593}},
                          {inet,[inet],econnreset}]}}
```

**Comment by jchristgit** [comment]
@IngelaAndin thank you, I've managed to reproduce it: It seems that on Linux, when connecting to a local TCP socket whose backlog is full, the client trying to connect will hang for a while before timing out. But on FreeBSD, you get an instant connection reset. With the default listen backlog in `gen_tcp` of 5, I think that's contributing to the problem here.

That said even 1000 commits back on master I can reproduce _some_ timeouts so I'll assume that's because of my VM being slow..? Test cases involving the HTTP server need ~ 7 seconds each..

I've opened #7939 which fixes the new errors in my VM. Can you test it with your internal machines?

**Comment by IngelaAndin** [comment]
Not related to this fix either, but probably to one of your others is this that happens on a netbsd and openbsd machine. 
Happens to IP version related testcases in in httpd_Serve_SUITE.

```
    {error,  {failed_connect,
                         [{to_address,{"0.0.0.0",13096}},
                          {inet6,[inet6],nxdomain},
                          {inet,
                              [inet],
                              {eoptions,
                                  [binary,{packet,0},{active,false},inet]}}]}}
```

**Comment by IngelaAndin** [comment]
I will merge this PR now, will see when I have time to cuddle the other problem, suggestions welcome.

**Comment by jchristgit** [comment]
@IngelaAndin sorry for all the breakage :sweat_smile: Seems like I was relying on more Linux platform specifics than I thought. I've opened #7953, can you let me know if that helps?

**Pull request merged**
