### PR TITLE
Add ssl:getstat/1 and ssl:getstat/2

### PR DESCRIPTION
**Pull request by essen**
These functions call getstat on the underlying TCP socket.
The only way to do this before now was to use a hack, either
by looking inside the #sslsocket{} record directly, or by
not using the SSL listen/accept functions and upgrading
from a TCP socket that is kept around for the purpose of
calling getstat later on.

A separate commit also exports the type inet:stat_option/0
to be able to use it in the ssl module's specs.

### CODE REVIEW

**Comment by essen** [comment]
The PR at https://github.com/erlang/otp/pull/364 served of inspiration for the documentation and tests. However the functionality in this PR is purposefully different from the one in #364. RabbitMQ has a Web interface that details how much traffic goes in and out, and currently uses a hack to get this information out of SSL sockets. This PR aims to provide an alternative to the hack and eventually clean things up inside RabbitMQ.

**Comment by stolen** [comment]
Nice! Simple and solves the main problem.

Maybe some day it would be better to have access to both stats (TLS frame stats like in #364 and transport sockets stats as here). I'm unsure about API. May be other function name (`get_transport_stat` or `get_frame_stat`) or special stat name (`transport_recv_cnt` or `frame_recv_cnt`) with reasonable defaults.

**Comment by essen** [comment]
Adding more stat names specific to the getstat/2 function would be great (perhaps leaving the defaults of getstat/1 to behave the same as inet:getstat/1). But that can be done as a second step. :-)

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Your testcase fails due to tls 1.1 and ssl 3.0 needs a 1/n-1 split as they are  vulnerable to Rizzo/Dundon attacks. Your testcase must handle this or not run on those versions.

**Comment by essen** [comment]
@proxyles I'm sorry but I have no idea what you just said. What's the error message and where does the failure happen?

**Comment by proxyles** [comment]
ssl_basic_SUITE:getstat, fails when tls is version 1.1 and/or ssl is 3.0 due to some special attack they are vulnerable to. It is called Rixxo/Dundon, There are example code for other tests in i.e. ssl_basic_SUITE. So you need to adapt to that or skip the tests on those versions. 
@IngelaAndin might be able to explain it better.

**Comment by IngelaAndin** [comment]
Rizzo/Dungon  the attack  is called. The counter measurement is to split all TLS packets in first byte and the rest, so if you send "Hello world" there will be two sends first we send "H" and then "ello world". (This also applies only to some cipher suites) This means in active mode you might  receive only the first byte or the whole message. This attack only applies to SSL 3.0 an TLS 1.0.  But your test case will currently run on all TLS versions  and will full fill the requirements for the counter measurement  to be applied  and crashes with 

"ssl_basic_SUITE:getstat failed on line 613
Reason: {badmatch,"H"}"

So either it is the case that you think it is relevant to run the test for all TLS versions supported and
then the test case needs to handle the possible spilt of the data sent or you should specify your test not to be run on all SSL/TLS versions by grouping it correctly. 

To handle it you want something like 

    receive
	{ssl, Socket, "Hello world"} ->
	    ok;
	%% Handle 1/n-1 splitting countermeasure Rizzo/Duong-Beast
	{ssl, Socket, "H"} ->
	    receive
		{ssl, Socket, "ello world"} ->
		    ok
	    end
    end,

**Comment by essen** [comment]
Ah there's a `"Hello world" = Data` in the tests, I see. I thought I wasn't matching on anything, due to changing the original tests on purpose to avoid this kind of issue. These tests don't need to match on the data so this should be a simple fix. Will have it ready soon, thanks!

And thanks for the detailed explanations, I now understand why SSL often receives only 1 byte and then the rest of the message. Always been wondering. :-)

**Comment by essen** [comment]
Updated the test. Should work for you too now.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Alas to late for 18.3, will be included in next release

**Comment by essen** [comment]
No problem at all. 19 is good. :-)

**Comment by essen** [comment]
Do you need me to rebase this to master?

**Comment by IngelaAndin** [comment]
That would be nice :)

**Comment by essen** [comment]
I don't know what I did, but looks like what I pushed last time didn't include my changes. Sigh.

Anyway closing in favor of new PR against master.

**Pull request closed without merging**
