### PR TITLE
RFC: Application Base Directories

### PR DESCRIPTION
**Pull request by psyeugenic**
Add Application Base Directories via `filename:basedir/2,3`

By Application we mean programs written in Erlang used from the operating system, not Erlang applications in the Erlang environment. One example is the dialyzer tool.

The idea is to have a standard way to access XDG directories on Linux or the equivalent on Mac OSX and Windows. For details see, http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

The directories are for example:

 * `$HOME/.cache/some_app`
 * `$HOME/.config/some_app`

For Linux, and by this we mean non Mac OSX or Windows environments, we respect the XDG environment variables. 

My primary question is what we should use for directories on Mac OSX. View it as a native Mac app and respect `/Library/Application Support/`and the like or view Mac as Linux and respect XDG paths?

For Windows most paths uses the environment value of `$LOCALAPPDATA` as its base except for `user_config` which uses `$APPDATA` and is roaming.

The `os` option is used to override the default for the current OS and `author` is only used on Windows.
```erlang
-type basedir_type() :: 'user_cache' | 'user_config' | 'user_data'
                      | 'user_log'
                      | 'site_config' | 'site_data'.

-spec basedir(Type,Application) -> file:filename_all() when
      Type :: basedir_type(),
      Application :: string() | binary().

-spec basedir(Type,Application,Opts) -> file:filename_all() when
      Type :: basedir_type(),
      Application :: string() | binary(),
      Opts :: #{author => string() | binary(),
                os => 'windows' | 'darwin' | 'linux',
                version => string() | binary()}.
```
Useful?

### CODE REVIEW

**Comment by tsloughter** [comment]
This is what we do for rebar3. In OSX we still follow the XDG standard. And actually, for Windows as well, though open to changing that if there is a better standard. For all 3 we get `$HOME` with `init:get_argument(home)`.

**Comment by psyeugenic** [comment]
@tsloughter I based my API on https://pypi.python.org/pypi/appdirs/1.4.0 and included some of their choices.

I believe using XDG standard on Mac is the most beneficial, however I get critique from some of my colleagues on that, so it's native there right now.

I don't think simply using `$HOME` on windows is the right way to do it.  If I recall correctly newer Windows, i.e. Windows 7 and beyond, can use `$HOME`. However Windows is such an odd duckling anyway I don't really know what to do there. They have some order to their madness.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Rebased to master.

**Pull request closed without merging**
