### PR TITLE
Accept all valid key sizes in aes_cfb_8_crypt and aes_cfb_128_crypt

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Despite the confusion caused by the name, `aes_cfb_8_crypt` and `aes_cfb_128_crypt` can use key lengths of 128, 192, or 256. The integer in the function name refers to the block size for CFB mode. Change the `aes_cfb_8_crypt` and `aes_cfb_128_crypt` functions to accept and use keys of length 128, 192, or 256. Also augment the existing testing for these functions using the NIST test vectors for the additional key lengths to ensure the changes function properly.

This is a follow-on from the comments on https://github.com/erlang/otp/pull/451 and should supersede the need for that PR.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Accept all valid key sizes in aes_cfb_8_crypt and aes_cfb_128_crypt


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Feature looks ok.

Code nitpicking:
* Too long lines. Put the now long key.size conditions on new lines.
* Don't make white space changes in otherwise untouched lines,
  or make them in a separate cleanup-commit if you can't resist the urge.

Tip: With "git gui" you can "Stage lines for commit".

/Sverker, Erlang/OTP

**Comment by kellymclaughlin** [comment]
> Code nitpicking:

Sorry, emacs automatically cleans up extra whitespace for me and I didn't notice that it crept in the commit. I updated the commit to make the suggested changes. Thanks!

**Comment by sverker** [comment]
Thanks, but you still got white space changes left.

**Comment by kellymclaughlin** [comment]
Ok, I think I got it all now.

**Comment by sverker** [comment]
Almost. One last sweep and this patch will be spotless.
I think you changed the indentation in all the lines of the two if-statements.

**Comment by kellymclaughlin** [comment]
Right, a tab versus space issue. Ok reverted back to tabs for those if statements.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
