### PR TITLE
ets: use initial salt different from phash2

### PR DESCRIPTION
**Pull request by max-au**
It is convenient to use erlang:phash2 to determine frag (ETS table)
to use. If salt is the same, both phash2 and ets hashing generate
the same frag/bucket number.
Since ETS hash is not portable, there is no need to keep backwards
compatibility with previous releases.

### CODE REVIEW

**Comment by sverker** [comment]
make_internal_hash() used by ETS is actually a separate implementation from phash2. It was created as a copy-paste of phash2 and then tweaked, but it still returns same hash for some types. Maybe a better solution would be to tweak make_internal_hash some more to diverge further from phash2.

**Comment by max-au** [comment]
I assumed having a different initial salt would lead to the same outcome, and attempted to avoid larger rewrites. However might be wrong here, e.g. there could be more hash clashes possible. One I can think about is atom hashing. 
Would it make sense to start with documenting how existing hashing works (unless it's already documented somewhere)?

**Comment by max-au** [comment]
It might be challenging to make a larger change on how make_internal_hash works, would it be possible to review this patch as-is, to have a chance of getting it into RC?

**Comment by sverker** [comment]
Sorry for being a bit slow on this.
A simple thing to do is to move the salt from ETS into make_internal_hash, like
`Uint32 hash = salt ^ 33554467UL;
`
By the way, is there a reason you chose a salt only 25 bits long?

**Comment by max-au** [comment]
You are indeed right, I completely missed make_internal_hash definition. Thank you for suggestion!

25-bit salt is a historical choice, based on 32-bit hash, and 6 bits (assuming, wrongly) used by tagging schema. It's a prime closest to the middle of remaining 26 bits. Feel free to adjust it to any other number (prime, ideally).

**Comment by bjorng** [comment]
The test cases `map_SUITE:t_hashmap_balance/1` and `persistent_term_SUITE:collisions/1` fail.

**Comment by sverker** [comment]
I will look at that.

**Comment by max-au** [comment]
Thank you! Indeed it was my fault, I did not realise these tests had hardcoded has values.

**Pull request merged**
