### PR TITLE
stdlib: Fix argparse:format_help/2 crash on 'hidden' command

### LINKED ISSUE #9150: argparse crash in format_help for hidden commands
**Describe the bug**

since 1aa91e7 `argparse:format_help/1` will crash when its `Options` contain a `'hidden'` command.

invocation of `argparse:run/3` with a `'hidden'` commands in `Args` will -- when `argparse:parse/3` fails -- print the error and then an exception message (instead of the related help).

**To Reproduce**

```
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace] [sharing-preserving]

Eshell V15.1.2 (press Ctrl+G to abort, type help(). for help)
1> Cmd = #{commands => #{"foo" => #{help => hidden, arguments => [#{name => x, help => "the X", type => integer}]}}}.
#{commands =>
      #{"foo" =>
            #{arguments => [#{name => x,type => integer,help => "the X"}],
              help => hidden}}}
2> argparse:run(["foo", "NaN"], Cmd, #{}).
error: erl foo: invalid argument for x: NaN is not an integer
** exception error: bad generator hidden
     in function  argparse:'-format_help/2-lc$^1/1-1-'/3 (argparse.erl, line 1652)
     in call from argparse:format_help/2 (argparse.erl, line 1652)
     in call from argparse:run/3 (argparse.erl, line 782)
3> 
```

**Expected behavior**

```
Erlang/OTP 26 [erts-14.2.5.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace] [sharing-preserving]

Eshell V14.2.5.4 (press Ctrl+G to abort, type help(). for help)
1> Cmd = #{commands => #{"foo" => #{help => hidden, arguments => [#{name => x, help => "the X", type => integer}]}}}.
#{commands =>
      #{"foo" =>
            #{arguments => [#{name => x,type => integer,help => "the X"}],
              help => hidden}}}
2> argparse:run(["foo", "NaN"], Cmd, #{}).
error: erl foo: invalid argument for x: NaN is not an integer
Usage:
  erl foo <x>

Arguments:
  x the X (int)
```

**Affected versions**

[OTP-27.1.3](https://github.com/erlang/otp/releases/tag/OTP-27.1.3)
[OTP-27.1.2](https://github.com/erlang/otp/releases/tag/OTP-27.1.2)
[OTP-27.1.1](https://github.com/erlang/otp/releases/tag/OTP-27.1.1)
[OTP-27.1](https://github.com/erlang/otp/releases/tag/OTP-27.1)

### PR DESCRIPTION
**Pull request by sg2342**
Fixes #9150

### CODE REVIEW

**Review by max-au — APPROVED** [review]
Good catch! Thanks for adding the test case for explicitly added sub-command. Looks good to me.

**Comment by garazdawi** [comment]
Thanks for the fix. I will merge this to maint for release in 27.3 as soon as 27.2 is out.

**Comment by garazdawi** [comment]
I did a rebase of your commit to `maint` for inclusion into 27.3. Added to nightly tests and will merge next week if nothing pops up.

**Comment by garazdawi** [comment]
Thanks!

**Pull request merged**
