### PR TITLE
Forbid bytes type modifier for unsized part of binary generators

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Forbid bytes type modifier for unsized part of binary generators


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lexmag** [comment]
Ping. :)

**Comment by zhird** [comment]
Merged to master :)

**Pull request closed without merging**
