### PR TITLE
Update orddict to use parameterized types and specs

### PR DESCRIPTION
**Pull request by kuenishi**
With parametrized types and specs, modules using
orddict can be statically checked with dialyzer.
Although orddict have not been builtin types, it is
good and more natural to have its exported types and
specs aligned to builtin types.

### CODE REVIEW

**Comment by ferd** [comment]
Changing the type from `-type` to `-opaque` is gonna be very funny when people who didn't call `orddict:to_list/1` on them will start getting errors for looking at lists.

Opaque types still have some funny corner cases whenever they're used with non-tagged tuples that can be confused with the default datatypes the language usually uses, too.

**Comment by OTP-Maintainer** [comment]
Building the documentation failed:

    gendate "$date" --stringparam appname "stdlib" --stringparam appver "2.4" --stringparam specs_file "$specs_file" --xinclude -path /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/dtd  -path /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/dtd_man_entities /ldisk/jenkins/jobs/pullrequests/workspace/otp/bootstrap/lib/erl_docgen/priv/xsl/db_man.xsl orddict.xml
      Error in orddict:orddict: ambiguous type
    make[4]: *** [../man3/orddict.3] Error 10
    make[4]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib/doc/src'
    make[3]: *** [release_docs] Error 2
    make[3]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib/doc/src'
    make[2]: *** [release_docs] Error 2
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/stdlib'
    make[1]: *** [release_docs] Error 2
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib'
    make: *** [release_docs] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by kuenishi** [comment]
@ferd Thank you for your commentary. That makes sense and I'll replace opaque with types.

But I don't have any idea why documentation build is failing. Removing `-type dict() :: dict(_, _).` line fixes it but that's impossible for now. Is `dict()` also should be added to builtin type deprecation notices in `erl_lint`?

**Comment by ferd** [comment]
I don't exactly know why that happens. I'm wondering if the documentation compiler only does a single pass on type definitions, and so you would need to put them in order of definition and declare `orddict/2` before `orddict/0` as a type given `orddict/0` uses `orddict/2`.

If that is the case, though, I'd argue this is an Edoc bug more than anything.

**Comment by kuenishi** [comment]
Both order of `/2` and `/0` did not work for quick experiment, but I'll try once again. Also, I'll try debug output of Edoc generation.

**Comment by kostis** [comment]
I just saw this pull request.

In principle, I am very much in favor to it (with the `opaque` in it) but the problem is that ordict's documentation (http://erlang.org/doc/man/orddict.html) explicitly mentions that the representation is a list, so there may be applications out there that take advantage of this fact.  I guess that a better approach would be to take out this *promise for the list representation" from the documentation first (i.e. *now*) and mention that `orddict` will be declared an opaque data type in e.g. 19.0.  Then applications have some time to adapt to this change (i.e. add appropriate `orddict:to_list`, `orddict:from_list` and `ordict:new` calls).

@ferd's argument about "Opaque types still have some funny corner cases" is IMO a bad one.  If there still are such cases, which may well be the case, then we should just find them and fix them instead of avoiding using `opaque` declarations where appropriate.  I'm sure that there are applications out there that confuse orddicts with key-value lists without an order (and are ignorant of this fact).

**Comment by okeuday** [comment]
I don't see any advantage of using `opaque` here, but I do see the advantage of using `type` here.  You could then enforce the key/value type on the orddict contents, which I believe is valuable, when using the data structure result as a list (i.e., not required to associate it with the orddict usage everywhere since it wouldn't be an opaque type).  I believe the documentation does support usage of `type` here, instead of `opaque`, as previously mentioned.

**Comment by kostis** [comment]
Would the fact that this call currently works (and is not detected as an error) convince you?
<pre>
1> orddict:append(foo, 3, [{zzz, [2]}, {foo, [1]}]).
[{foo,[3]},{zzz,[2]},{foo,[1]}]
</pre>

**Comment by okeuday** [comment]
@kostis No, I agree that situation is a problem, because a list that is not sorted is provided as input to the orddict module, so normally the result should be:

    1> orddict:append(foo, 3, [{foo,[1]},{zzz,[2]}]).
    [{foo,[1,3]},{zzz,[2]}]

If we could add a sorted_list/1 type to what dialyzer supports, that seems like a better way to make the orddict `type` more descriptive, and that would prevent the orddict error you have shown.

**Comment by kostis** [comment]
@okeuday With all due respect, your suggestion about a `sorted_list(T)` type is a bit naive (It is just too late in the night?)  Is the following a `sorted_list({term(),[term()])` type or not in your definition?
<pre>
  [{foo,[1]},{foo,[2]},{zzz,[3]}]
</pre>
According to the `lists:sort/1` function it is.
<pre>
  1> lists:sort([{foo,[1]},{foo,[2]},{zzz,[3]}]).
  [{foo,[1]},{foo,[2]},{zzz,[3]}]
</pre>
Even if dialyzer could be enhanced with "sorted_lists", which is not easy to do, I can show you more problematic cases...

The point is that orddicts need more properties than sortedness.  They are actually an abstract data type.  There are good software engineering arguments for ADTs to be non-forgeable and this is what opaque types give you.

**Comment by okeuday** [comment]
@kostis My suggestion is serious and I agree it is naive due to not understanding the difficulty within dialyzer to add it (though I can understand how an extra constraint makes processing difficult and more expensive).  However, my expectation was that sorted_list/1 would be uniquely sorted, so the output of lists:usort/1 since that should be the more common case of sorted list usage, and another type can handle having duplicates.  If the type names replicated the lists module functions, it would probably need to be usorted_list/1 and sorted_list/1.

So, while the approach is more difficult when pursuing the addition of sorted list types, I see usage of `opaque` as giving up on the opportunity to catch more errors and further limiting the usage of the orddict module due to its type (i.e., creating an opaque type that is more difficult to use in a generic/list way).  Since the documentation already defines what the orddict datastructure should be, I think that should be accessible as a clearly defined type that is not opaque.  The (uniquely) sorted constraint on the list can be added later, assuming we can agree it would be beneficial to have in dialyzer.

**Comment by okeuday** [comment]
Just to be clear, my point is that types being more explicit (with `type`) helps Erlang development more than preventing the reuse of a data structure by making the data structure `opaque`, assuming the data structure is basic enough that it may be reused outside the module.  The orddict module is a great example of a basic data structure that is always used outside of its module (with the data structure already explicitly defined in the documentation text, which will hopefully not change simply due to a whim in this pull request).

While it is a slightly weaker argument, I would also argue that the queue module data type should not be opaque, since the queue module data structure is such a basic typical implementation of a queue as two stacks (often used as an interview question).  Making it opaque prevents custom usage of the queue module (from being easy) in places like https://github.com/okeuday/pqueue/blob/master/src/pqueue4.erl#L11532-L11555 .  I would hope the queue module data structure would not change just due to how it affects the whole module and that any more complex structure be put into a separate module, just due to its impact on performance.

orddict offers a more basic example of something that should be transparent to the user.  Otherwise orddict becomes less useful just due to it being more difficult to reuse the data structure as a list.  I don't consider this forging the data structure, but rather a flexibility of the dynamic type checking.

It is obvious why things like array, dict, and the other more complex data structures must have opaque types, since their implementation can be done in many different ways and the opaque type hides their complexity.  opaque types are great for hiding the data structure, which would be contrary to usage of orddict in typical source code.

**Comment by uabboli** [comment]
I'll substitute 'type' for 'opaque' and update the docs. Thank you.

**Comment by kuenishi** [comment]
Looks like this is the fix? https://github.com/uabboli/otp/commits/hb/dialyzer/fix_opaque_types/OTP-12493

**Comment by uabboli** [comment]
Is it the question raised by Thorsten Schütt [schuett@zib.de] you allude to?
I cannot reproduce what he reports. Can you?

The branch you mention has nothing to do with this PR.

**Pull request closed without merging**
