### PR TITLE
Improve figures in documentation

### PR DESCRIPTION
**Pull request by jchristgit**
This pull request improves most of the figures in the documentation that were created via `xfig`, primarly by upscaling them slightly and setting the smoothing factor via `fig2dev -S4 -m$SCALE image.{fig,gif}`. I couldn't nicely format the company table ERD from the mnesia getting started table and went with GraphViz there instead.

Some examples:

Distributed applications - situation 1 (old)

image

Distributed applications - situation 1 (new)

image

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Thank you very much for the suggestion, we indeed think this is a good idea. We are however in a planning stage at the moment where we are considering some big changes to how we handle the documentation so we we will stall the decision if to merge this or maybe use your approach when restructuring things.

**Comment by jchristgit** [comment]
Thanks for the info!

Just a question about your changes, are PRs updating the documentation still welcome (even if they may stall for a while) or should they be held off until your restructure is done? Or does it depend on the scope?

**Comment by IngelaAndin** [comment]
It depends on the scope!

**Comment by jchristgit** [comment]
Hi @IngelaAndin @kikofernandez! When you talked about "big changes" in the documentation the last year I was wondering whether you're going to add triple-quoted strings, markdown support or something else. Turns out it's all three! :smile: I like the changes a lot, even though I somewhat miss the manpages (my favourite way to read the references), I think they're no longer a thing?
Either way, I've updated the PR to the latest changes from `master`, please let me know what you think :slightly_smiling_face:

**Comment by IngelaAndin** [comment]
Looks good to me.

**Comment by IngelaAndin** [comment]
Maybe odbc picture could also be further improved by a mermaid diagram but I think the one here will be an improvement for now.

**Review by kikofernandez — APPROVED** [review]

**Comment by kikofernandez** [comment]
It looks like an improvement to what we had before :)
Thanks for this contribution.

There seems to be some conflict in mnesia_chap2 that needs to be fixed.
From my side, I think this looks good. Others will provide more feedback :)

**Comment by Benjamin-Philip** [comment]
> Maybe odbc picture could also be further improved by a mermaid diagram but I think the one here will be an improvement for now.

I was planning to send patches to port most of the diagrams changed later this (or next) week. Out of the ones changed here, the only one I can't port is the Venn diagrams in xref docs.

Maybe I should create an issue with a list of diagrams to port to mermaid, so that other contributors are synchronized and we don't get merge conflicts?

**Review by bmk — APPROVED** [review]
I have only looked at the snmp related images,
but they look good.

**Comment by IngelaAndin** [comment]
@Benjamin-Philip and we much apricate that. Time to be included for OTP-27.0 is running out. Deadline is tomorrow.
@jchristgit if you remove the mnesia one  I think we could include the others as an improvement over now and later @Benjamin-Philip could improve them further.

**Comment by jchristgit** [comment]
Thanks for the feedback! I've rebased from master so the merge conflict is gone now. I think the test failures are unrelated.
I do personally prefer these over mermaid because they don't require a browser to display. These "pre-rendered" pictures can be included in other output as well, run offline & without JS. But it's personal preference, whatever makes the most comprehensive documentation is probably the best pick :slightly_smiling_face:

**Review by garazdawi — APPROVED** [review]

**Comment by kikofernandez** [comment]
@jchristgit can you rebase again? Sorry for the inconvenience

**Comment by kikofernandez** [comment]
Sorry, I meant if you can rebase on `maint`, so that these changes are used in OTP-27 :) 
Sorry again for the inconvenience

**Pull request merged**
