### PR TITLE
Remove extra ">" in examples

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by IngelaAndin** [comment]
As 19 is the next planned release I rebased it to master and merged it for 19

**Comment by eksperimental** [comment]
@IngelaAndin so what branch should future patches be sent to?

**Comment by IngelaAndin** [comment]
Normally patches should be for maint, but there is a window when there are no more planned service releases for a major release and the next planned release is the next major release and then it is master. But no worries it was a trivial rebase.

**Comment by eksperimental** [comment]
@IngelaAndin no worries then

**Pull request closed without merging**
