### PR TITLE
Place move S x0 instructions at the end of blocks

### PR DESCRIPTION
**Pull request by michalmuskala**
The loader has a lot of fused instructions that include move S x0. Placing them
at the end of blocks makes it possible to take advantage of this optimization
more frequently.

### CODE REVIEW

**Comment by bjorng** [comment]
`erlc +no_copt trycatch_SUITE.erl` does not terminate.

**Comment by bjorng** [comment]
Ping!

Do you have any plans to update this PR in the near future? If not, I will close it.

**Comment by michalmuskala** [comment]
Hey, sorry for the delay, I forgot a bit about this patch. I would like to finish it, I think I should be able to get around to it during the weekend.

**Comment by michalmuskala** [comment]
@bjorng updated. Once again sorry for the delay.

**Comment by bjorng** [comment]
Looks good! Added to our daily builds.

**Pull request merged**
