### PR TITLE
Document eunit's default 5 second test timeout

### PR DESCRIPTION
**Pull request by stevendanna**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
@richcarl correct?

**Comment by c-rack** [comment]
I am not Richard, but would say it's correct:
https://github.com/erlang/otp/blob/maint/lib/eunit/src/eunit_internal.hrl#L12

**Comment by richcarl** [comment]
Yes, that is correct. Thanks.

**Comment by proxyles** [comment]
Ill add it, Thanks

**Comment by stevendanna** [comment]
Thanks! Apologies for not linking to the relevant code or adding an explanation in the PR.

**Pull request merged**
