### PR TITLE
Document allowed integer ops in types

### PR DESCRIPTION
**Pull request by gomoripeti**
I'm not sure about the language of "must evaluate to".
Maybe "is an expression which has positive integer value" or "is a positive integer or an expression evaluating to a positive integer value" is better or clearer?

### CODE REVIEW

**Comment by uabboli** [comment]
I agree it's probably a good idea to document singleton integer types.

I think <tt>BinaryOp</tt> and <tt>UnaryOp</tt> can be compressed onto one line. And that the convention to quote atoms in types can be used:

<tt>
  BinaryOp :: '*' | 'div' | 'rem' | 'band' | '+' | '-' | 'bor' | 'bxor' | 'bsl' | 'bsr'

  UnaryOp :: '+' | '-' | 'bnot'
</tt>

Regarding the <tt>Integer_Value</tt> type. Notice that characters (<tt>$C</tt>) are allowed, and that parentheses can be used.

<tt>M</tt> and <tt>N</tt> in the <tt>Bitstring</tt> type are of type <tt>Integer_Value</tt>.

Maybe I've missed something.

Related: in "The Abstract Format" in the ERTS User's Guide, under the heading <tt>Types</tt>, if I'm not mistaken, it should be stated that not only atom and integer literals are types, but also character literals:
<tt>If T is an atom, character, or integer literal L, then Rep(T) = Rep(L).</tt>
I'll correct that.

**Comment by gomoripeti** [comment]
thank you for the review, I pushed the suggested changes.
(I skipped parentheses, as every type can be parenthesized just as every expression, so works based on common sense)

**Comment by gomoripeti** [comment]
squashed and rebased to latest maint. (I totally forgot about this PR in the summer holidays 🌞 )

**Comment by uabboli** [comment]
Thank you!

**Pull request merged**
