### PR TITLE
Reenable tls prf test

### PR DESCRIPTION
**Pull request by NelsonVides**
As far as I could discover, it seems to me that in the commit
ec0f8d69a98b08b2effd07121b5f87e327d370ee, when moving around many test
suites, the prf test was left out, and it hasn't been running tests for
a while. Here I re-enable it, fixing also any other changes that seemed
necessary to make the test pass.

@IngelaAndin @peterdmv 

edit: there's a second commit, 8e19af3, removing some duplicated code as well, the prf code was copy&pasted and duplicated.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
When testing this I see interop problems on some of our machines that run quite old OpenSSL versions (it might be part of a test cuddling problem that lead to the test accidently being excluded in the first place). I think that the following diff could help. Would you mind including it in your PR? 

```
- diff --git a/lib/ssl/test/ssl_api_SUITE.erl b/lib/ssl/test/ssl_api_SUITE.erl
- index 15cd418d88..aabbc28890 100644
- --- a/lib/ssl/test/ssl_api_SUITE.erl
- +++ b/lib/ssl/test/ssl_api_SUITE.erl
- @@ -2665,7 +2665,7 @@ prf_ciphers_and_expected(TlsVer, PRFs, Results) ->
-      case TlsVer of
-          TlsVer when TlsVer == tlsv1
-                      orelse TlsVer == 'tlsv1.1' orelse TlsVer == 'dtlsv1' ->
- -            Ciphers = ssl:cipher_suites(default, TlsVer),
- +            Ciphers = ssl:cipher_suites(all, TlsVer),
-              Expected = [Expect#{prf := md5sha} || Expect <- Results],
-              [[{tls_ver, TlsVer}, {ciphers, Ciphers}, {expected, Expected}, {prf, md5sha}]];
-          TlsVer when  TlsVer == 'tlsv1.2' orelse  TlsVer == 'dtlsv1.2'->
- @@ -2693,10 +2693,10 @@ prf_get_ciphers(TlsVer, PRF) ->
-                                  false
-                          end
-                  end,
- -    ssl:filter_cipher_suites(ssl:cipher_suites(default, TlsVer), [{prf, PrfFilter}]).
- +    ssl:filter_cipher_suites(ssl:cipher_suites(all, TlsVer), [{prf, PrfFilter}]).
-  
-  prf_run_test(_, TlsVer, [], _, Prf) ->
- -    ct:fail({error, cipher_list_empty, TlsVer, Prf});
- +    ct:comment(lists:flatten(io_lib:format("cipher_list_empty Ver: ~p  PRF: ~p", [TlsVer, Prf])));
-  prf_run_test(Config, TlsVer, Ciphers, Expected, Prf) ->
-      {ClientNode, ServerNode, Hostname} = ssl_test_lib:run_where(Config),
-      BaseOpts = [{active, true}, {versions, [TlsVer]}, {ciphers, Ciphers}, {protocol, tls_or_dtls(TlsVer)}],
- 
```

**Comment by NelsonVides** [comment]
Hi @IngelaAndin 
I've applied the patch as you mentioned, and I've tested it building against up to openssl 1.0.2, but I couldn't easily build older versions of openssl locally to test, I'll try to get that working for the future. In the meantime I hope the patch fixes the issue :)

**Comment by IngelaAndin** [comment]
I will enable it in our test after OTP-24-RC3 (on Wednesday) and we will probably know at the end of the week. Thank you.

**Comment by IngelaAndin** [comment]
Still not passing on those old OpenSSL versions. We will need to investigate.

**Comment by NelsonVides** [comment]
> Still not passing on those old OpenSSL versions. We will need to investigate.

Can you give me a bit more detail? Which OpenSSL versions, maybe what system is running on (OS, kernel, cpu, etc)? I can give it a try as well :)

**Comment by IngelaAndin** [comment]
OpenSSL 0.9.8h, OpenSSL 0.9.8k,  linux 2.6.16 and 2.6.27 

TLS-1.2 will fail with TLS client: In state hello received SERVER ALERT: Fatal - Insufficient Security
and previous versions with TLS client: In state hello received SERVER ALERT: Fatal - Handshake Failure

**Comment by IngelaAndin** [comment]
Any luck @NelsonVides ? My coworker has updated cryptos configure which seems to have removed some other strange test case problems, so I will enable these tests again to see if it could be the problem here too.

**Comment by IngelaAndin** [comment]
It did not help, still failing!

**Comment by IngelaAndin** [comment]
Ok, so I think I found the problem, the following patch ought to fix it. Can you include it too. Note the patch is based on master.

```
index 15cd418d88..d907f5a2c8 100644
--- a/lib/ssl/test/ssl_api_SUITE.erl
+++ b/lib/ssl/test/ssl_api_SUITE.erl
@@ -2693,7 +2693,17 @@ prf_get_ciphers(TlsVer, PRF) ->
                                 false
                         end
                 end,
-    ssl:filter_cipher_suites(ssl:cipher_suites(default, TlsVer), [{prf, PrfFilter}]).
+    RSACertNoSpecialConf = fun(rsa) ->
+                                   true;
+                              (ecdhe_rsa) ->
+                                   lists:member(ecdh,crypto:supports(public_keys)); 
+                              (dhe_rsa) ->
+                                   true;
+                              (_) ->
+                                   false
+                           end,
+    ssl:filter_cipher_suites(ssl:cipher_suites(default, TlsVer), [{key_exchange, RSACertNoSpecialConf},
+                                                                  {prf, PrfFilter}]).
 
 prf_run_test(_, TlsVer, [], _, Prf) ->
     ct:fail({error, cipher_list_empty, TlsVer, Prf});

```

**Comment by NelsonVides** [comment]
@IngelaAndin hi there, thanks for having a look at this, I was off for a few days and then got a big workload at the job on my return. Taking action soon 👍🏽

**Comment by NelsonVides** [comment]
Right, passing the regular tests in my system, but for the love of Cthulhu I cannot build any version of OpenSSL before 1.0 to test those, still to find out why 🤷🏽‍♂️

**Comment by IngelaAndin** [comment]
Well it is an ancient version no longer supported by OpenSSL, but we have some pretty old test platforms that primarily tests other things. But anyhow it is good for testcases to check preconditions and create interoperable configurations.

**Comment by IngelaAndin** [comment]
Sorry if I was unclear but we need both my suggested patches.

**Comment by NelsonVides** [comment]
> Sorry if I was unclear but we need both my suggested patches.

Not sure I understand you this time. So you mean rebase on master, apply the `key_exchange` filter, and make `ssl:cipher_suites/2` use `all` instead of `default`? 🤔 

If code from master is needed, can you point to me to the change (PR or so) that explained why this was an issue? I'm trying to study these cipher filters now 🙂

**Comment by IngelaAndin** [comment]
Well yes, because now I see this failure again ``` {test_case_failed,{error,empty_prf_test_plan}}```
for TLS-1.2 on the old platforms, which is fixed by 

```
-  prf_run_test(_, TlsVer, [], _, Prf) ->
- -    ct:fail({error, cipher_list_empty, TlsVer, Prf});
- +    ct:comment(lists:flatten(io_lib:format("cipher_list_empty Ver: ~p  PRF: ~p", [TlsVer, Prf])));
```
The all vs default is because legacy cipher suites from TLS-1.0 and TLS-1.1 that may be needed to run this test against legacy OpenSSL servers are not part of the default as they are consider weak.

**Comment by NelsonVides** [comment]
> empty_prf_test_plan

Right, the error `empty_prf_test_plan` is thrown elsewhere, by `prf_run_test` caller, at `prf/1`, that's the one that fails for empty plans. The patch you mention here is already applied and it didn't fix it, I'm fixing that one before as well 👍🏽

**Comment by NelsonVides** [comment]
@IngelaAndin hi there, any news on this PR? :)

**Comment by IngelaAndin** [comment]
I re-enabled it in the test now! We had public holiday in Sweden in the end of last week so not so much has happened after the release. And just before was the code freeze.

**Comment by IngelaAndin** [comment]
It now passes TLS-1.2 with OpenSSL-0.9.8h but TLS-1.1 and TLS-1.0 still
fail  with:
 
```
TLS server: In state hello at tls_dtls_connection.erl:686 generated SERVER ALERT: Fatal - Handshake Failure
 - malformed_handshake_data

```

**Comment by NelsonVides** [comment]
Rebasing onto maint, easy, will do later today. The OpenSSL issue, can't say how long would that take me 😔 

But about maint, that reminds me, that one of the goals I wanted to achieve originally, was to have TLS exporters for v1.3, and this prf test was something I encountered when basically trying to do that other thing, so I guess it's about time I ask you for advise about it. Is it in your release plan already? Onto which branch should I base the work? Maybe we should start a discussion about that in the erlang mailing lists?

**Comment by NelsonVides** [comment]
Rebased onto maint 👍🏽

**Comment by IngelaAndin** [comment]
We have no current plan to add any additional exporters (than the existing keylog exporters)  for TLS-1.3.
The are available with the  keep_secrets option enabled. Could you elaborate of what you had in mind?

**Comment by IngelaAndin** [comment]
`@NelsonVides`  I think I found the last update needed for this PR.

```
prf_create_plan(TlsVer, _PRFs, Results) when TlsVer == tlsv1
		                             orelse TlsVer == 'tlsv1.1'
                                             orelse TlsVer == 'dtlsv1' ->
    Ciphers = prf_get_ciphers(TlsVer, default_prf),
    {_, Expected} = lists:keyfind(md5sha, 1, Results),
    [[{ciphers, Ciphers}, {expected, Expected}, {prf, md5sha}]];

```
If you change the function clause above in ssl_api_SUITE to look like above the tests will pass. I actually run the on one of our old machines like this and it passed. Also note my last comment if you have not seen it yet!

**Comment by NelsonVides** [comment]
@IngelaAndin Applied this patch, `default_prf`, I think that makes sense, how did you realise this one? 😄 

About the exporters, my main goal was to achieve [this draft](https://datatracker.ietf.org/doc/html/draft-ietf-kitten-tls-channel-bindings-for-tls13-08), but that requires the TLS implementation to expose [exporters](https://datatracker.ietf.org/doc/html/rfc8446#section-7.5). I haven't seen the `exporter_master_secret` being calculated in the ssl libraries, so that's the first place I wanted to edit, to calculate and store that value somewhere for future usage. `keep_secrets` option, didn't notice that one, will look after it 🙂

**Comment by IngelaAndin** [comment]
> @IngelaAndin Applied this patch, `default_prf`, I think that makes sense, how did you realise this one? 

I code to review the test case trying to understand why my previous suggestions fixed the test case for TLS-1.2 but not for previous versions.  

> About the exporters, my main goal was to achieve [this draft](https://datatracker.ietf.org/doc/html/draft-ietf-kitten-tls-channel-bindings-for-tls13-08), but that requires the TLS implementation to expose [exporters](https://datatracker.ietf.org/doc/html/rfc8446#section-7.5). I haven't seen the `exporter_master_secret` being calculated in the ssl libraries, so that's the first place I wanted to edit, to calculate and store that value somewhere for future usage. `keep_secrets` option, didn't notice that one, will look after it

Ah, I see. Without digging too deep I think it sounds like we should extend the prf to work for TLS-1.3. We are still working on TLS-1.3 features. It might be able to reuse some of the things done for keylogging, which has a debugging purpose and can be used with Wireshark for a system that you have control over.

**Pull request merged**
