### PR TITLE
Fix mistranslations in beam_disasm

### PR DESCRIPTION
**Pull request by the-mikedavis**
This PR builds on some prior work in #6447, #6451, #6452 for resolving instructions in `beam_disasm` so that they mirror `beam_asm` and are accepted by `beam_validator`. Each commit is a separate fix and the commit messages explains each change. (I can break these into separate PRs if that is desired.)

Thank you!

### CODE REVIEW

**Comment by bjorng** [comment]
The reason that we have the `beam_disasm` module at all is because it was used as a part of the [HiPE](https://www.it.uu.se/research/group/hipe/) native compiler when compiling from BEAM files. (HiPE was removed in OTP 24.) It was never a priority to make the output of `beam_diasam` identical to that of `.S` files. For example, `arithbif` was more convenient for the HiPE compiler because arithmetic instructions were translated differently compared to other guard BIF calls. You might want to adjust some of your commit messages (especially those about `arithbif` and `raise`).

**Comment by the-mikedavis** [comment]
Oh, I see now, thank you for the pointer! I have reworded some of the commit messages (mostly the arithfbif and raise ones).

> It was never a priority to make the output of `beam_diasam` identical to that of `.S` files.

Now that HiPE is removed, is it ok to patch `beam_disasm` to emit `.S` output? Or are you looking to remove `beam_disasm` in the future?

We use this in [rabbitmq/khepri](https://github.com/rabbitmq/khepri) to compile transaction functions into self-contained modules (through `code:get_object_code/1`, `beam_disasm:file/1`, and `compile:forms/2` with the `from_asm` option). It's very close to working out-of-the-box: we just needed these translations and to add some `var_info` type and match-context annotations to satisfy `beam_validator`.

**Comment by bjorng** [comment]
> Now that HiPE is removed, is it ok to patch `beam_disasm` to emit `.S` output?

Yes.

> Or are you looking to remove `beam_disasm` in the future?

We have no plans to remove it.

**Comment by bjorng** [comment]
Thanks for your pull request!

**Pull request merged**
