### PR TITLE
Add math:log2/1

### PR DESCRIPTION
**Pull request by oliv3**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Looks good to me. Tentative ok. It will run through our test first.

**Comment by sverker** [comment]
I see no reason not to do the simple optimization of replacing log(2.0) with compile time constant
0.6931471805599453.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Use a constant for log(2.0).


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
Yes - but now I want you to squash your commits to a single commit. After you've done that you can (force) push your branch again.

**Comment by oliv3** [comment]
Should be ok

**Comment by psyeugenic** [comment]
:thumbsup:

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by marcusarendt** [comment]
merged on master

**Pull request closed without merging**
