### PR TITLE
ERL-1030 SSL failing to handle a 'cRLIssuer' entry in a CRL distribution point extension

### PR DESCRIPTION
**Pull request by tgleeson272**
SSL is failing to handle a populated 'cRLIssuer' entry in a CRL distribution point extension in a certificate.

Specifically, ssl_crl_hash_dir:lookup/3 confuses the structure of 'CertIssuer' with 'CRLIssuer' which is potentially a list.

Fix by using the existing pubkey_crl:dp_crlissuer_to_issuer/1 to unwrap the CRLIssuer.

Added test to repro the problem.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
I have been reviewing the PR and I believe that the solution should be a different one. The following solution fits my understanding of the RFC 5280 better and it does not introduce the use of internal public_key functions into the ssl application. Also you based your branch on maint-19 it should be based on maint, when I changed it there is a conflict in make_certs.erl. Could you please try my solution toghter with your test on maint based branch. 

`diff --git a/lib/ssl/src/ssl_crl_hash_dir.erl b/lib/ssl/src/ssl_crl_hash_dir.erl
index 9478ff9b78..0a15bb6602 100644
--- a/lib/ssl/src/ssl_crl_hash_dir.erl
+++ b/lib/ssl/src/ssl_crl_hash_dir.erl
@@ -27,27 +27,25 @@
 -export([lookup/3, select/2, fresh_crl/2]).
 
 lookup(#'DistributionPoint'{cRLIssuer = CRLIssuer} = DP, CertIssuer, CRLDbInfo) ->
-    Issuer =
-       case CRLIssuer of
-           asn1_NOVALUE ->
-               %% If the distribution point extension doesn't
-               %% indicate a CRL issuer, use the certificate issuer.
-               CertIssuer;
-           _ ->
-               CRLIssuer
-       end,
-    %% Find all CRLs for this issuer, and return those that match the
-    %% given distribution point.
-    AllCRLs = select(Issuer, CRLDbInfo),
-    lists:filter(fun(DER) ->
-                        public_key:pkix_match_dist_point(DER, DP)
-                end, AllCRLs).
+    case CRLIssuer of
+        asn1_NOVALUE ->
+            %% If the distribution point extension doesn't
+            %% indicate a CRL issuer, use the certificate issuer.
+            select([{directoryName, CertIssuer}], CRLDbInfo);
+        _ ->
+            CRLs = select(CRLIssuer, CRLDbInfo), 
+            lists:filter(fun(DER) ->
+                                 public_key:pkix_match_dist_point(DER, DP)
+                         end, CRLs)
+    end.
 
 fresh_crl(#'DistributionPoint'{}, CurrentCRL) ->
     CurrentCRL.
 
-select(Issuer, {_DbHandle, [{dir, Dir}]}) ->
-    case find_crls(Issuer, Dir) of
+select([], _) ->
+    [];
+select([{directoryName, Issuer} | _], {_DbHandle, [{dir, Dir}]}) ->
+    case find_crls(public_key:pkix_normalize_name(Issuer), Dir) of
         [_|_] = DERs ->
            DERs;
         [] ->
@@ -62,8 +60,10 @@ select(Issuer, {_DbHandle, [{dir, Dir}]}) ->
                {module, ?MODULE},
                {line, ?LINE}]),
             []
-    end.
-
+    end;
+select([_ | Rest], CRLDbInfo) ->
+    select(Rest, CRLDbInfo).
+    
 find_crls(Issuer, Dir) ->
     case filelib:is_dir(Dir) of
         true ->

`

**Comment by IngelaAndin** [comment]
Getting closer.  The commit  769c764 creates a merge, we need all your commits to come cleanly
after each on a branch based on maint.  You need not include the solution we dropped.

Also we get a dialyzer warning  (which is my fault). In order to keep backwards compatibility
we need to change the the select function to 

```
select({} = Issuer, DbHandle) ->
  select([{directoryName, Issuer}], DbHandle)
select([], _) ->
    [];
select([{directoryName, Issuer} | _], {_DbHandle, [{dir, Dir}]}) ->
...
select([_ | Rest], CRLDbInfo) ->
...
```
And then we can change the function call in ssl_crl_hash_dir.erl
```
select([{directoryName, CertIssuer}], CRLDbInfo);
```
to 
```
select(CertIssuer, CRLDbInfo);
```
we also need to  extend 

ssl_crl_cache_api.erl

from
```
-callback select(issuer_name(), db_handle()) ->  [public_key:der_encoded()].
```

```
-callback select(issuer_name() | list(), db_handle()) ->  [public_key:der_encoded()].
```
The list argument can be further improved but I like to export an other type from public_key and
I can fix that later to make the workload for this PR not to explode.

**Comment by tgleeson272** [comment]
With the most recent commit, all ssl_crl_SUITE and ssl_dist_SUITE tests pass.

The error in ssl_dist_SUITE crl_cache_check_pass was caused because GenNames in dps_and_crls() was coming through as:
[{directoryName,
     {rdnSequence,
         [[{'AttributeTypeAndValue',{2,5,4,3},<<"\f\berlangCA">>}],
          ...
         ]}},
 {rfc822Name,"peter@erix.ericsson.se"}]

I'm a bit unsure why this hadn't caused problems before, since the interface for select() is public and expects a single rdnSequence.

**Comment by IngelaAndin** [comment]
Yes that is why I said we need to extend the external API!  Adding things to APIs is not breaking backwards compatibility :)

**Comment by tgleeson272** [comment]
Signed

**Comment by IngelaAndin** [comment]
Thanks for signing :) I have enabled the tests again as updates to the PR can cause them to be disabled so there should be results tomorrow.

**Comment by IngelaAndin** [comment]
Thank you for your pull request. In this case I will fix the documentation as I am anyway doing some 
other work that is related.

**Comment by tgleeson272** [comment]
Thanks for your help.

**Pull request merged**
