### PR TITLE
cover:filter_options/1: preserve tuple_calls

### PR DESCRIPTION
**Pull request by mikpe**
Fixes https://github.com/erlang/otp/issues/4796

### CODE REVIEW

**Comment by bjorng** [comment]
Could you add a test case?

**Comment by mikpe** [comment]
> Could you add a test case?

I'll give it a try.

**Comment by mikpe** [comment]
Test case added, verified to fail without the fix and pass with it. Squashed. Had to rebase due to a merge conflict.

**Comment by bjorng** [comment]
Thanks! Added to our daily builds.

> Question: how do you want references to issues on github to look? "otp_NNNNN" are for your OTP-private bugs, "erl_NNNN" for the old non-github bug tracker, so I chose "GH-NNNN" as a general reference and "gh_NNNN" for function/module names.

Yes, that is the convention that we use.

**Pull request merged**
