### PR TITLE
mnesia_ext

### PR DESCRIPTION
**Pull request by richcarl**
The mnesia_ext patch rebased on OTP 18.1.2.

This required reverting 027726d, because that optimization needs to be reworked from scratch (if at all) based on the mnesia_ext version of the code.

### CODE REVIEW

**Comment by lemenkov** [comment]
Awesome to see this happens!

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by dgud** [comment]
Have not started looking at the code yet but:

Am I missing something?
There is ONE testcase on the new functionality which is not even run?
Seems like a large commit is missing.

With this patch I can not connect to a node running an older version of mnesia.

Do not know if I like the you have documented mnesia_schema functionality, I'm not sure
that it works and there is no testcases.

The doc/src/mnesia_backend_type.xml is a brief copy of mnesia_schema.xml and should be removed, it seems unfinished?

Should not mnesia_sext be in stdlib?

**Comment by uwiger** [comment]
Disclaimer: I'm not actively involved in this PR, but *was* actively involved in the development of the mnesia_ext functionality, at least until ca 1.5 years ago. For now, I'll just comment on two things:

> There is ONE testcase on the new functionality which is not even run?

Earlier, we ran the full test suite by applying a parse_transform, replacing all instances of `disc_only_copies` with `leveldb_copies`. This was done in part because it would have been unmaintainable to patch all places in the test suite where extra backends would need to be added. A small number of test cases didn't pass - most of which were making explicit assumptions about the dets backend, but a couple of tests failed in ways that I found more or less impossible to debug.

The file `test/mnesia_ext_filesystem.erl` was intended as both a reference example and as a backend to use in the test suite.

> Should not mnesia_sext be in stdlib?

If so, I suggest you take [sext](https://github.com/uwiger/sext) directly. You have my permission to do so, and I'd even be happy to assist, but please note that the tests for sext use EQC.

**Comment by mikpe** [comment]
I tested mnesia_ext last summer using mnesia's own test suite.  My primary goal then was to eliminate all regressions from the mnesia_ext patch itself, and I managed to get it to that state.  To test the ext hooks themselves requires a working backend, and as far as I recall the one somewhere in the doc or test directory wasn't quite up to the job -- I'm thinking we may have to write a new simple (naive even) backend for documentation and regression testing purposes.

However, we've used mnesia_ext + our leveldb backend in production for a year now, with no real issues.

**Comment by mikpe** [comment]
What does the error when connecting to a node with an older mnesia look like?

**Comment by dgud** [comment]
The schema merge fails and it causes a fatal error.
I can fix the merge problem I've done it before with Ulf's additions :-) 
but the I will need the testcases if I'm gonna maintain it.

**Comment by dgud** [comment]
I have looked at this PR/branch from time to time.

I have split up the commits to several based on functionality or modules, just 
so it will be easier for me to review.
In the end of the branch I have removed stuff that was not finished, dead code
and fixes based on my testing and/or my understanding of the usage.

I split the branch in two parts so that I could diff between your original branch and
mine, but I have rebased it on the latest master so that will not work anymore.

The commit comments are my brain dumps at the time..so don't take it to seriously.

Have still not looked at the index code, would be nice with some explanations of what
you did there.

https://github.com/dgud/otp/tree/dgud/mnesia/klarna-mnesia-ext

Would be nice if you could take a look at what I have done so far.

**Comment by uwiger** [comment]
Briefly about the index code.

* The `mnesia_index:index_vals_f(Storage, Tab, Pos)` function returns a Fun, where `F(Obj) -> [IxValue]`.
* For external copies, either a callback can be specified using `Mod:semantics(Alias, index_fun)`, which is then called as `Mod:IxFun(Alias, Tab, Pos, Obj)` and shall return a list of index values. If no index_fun is defined, the default action is `[element(Pos, Obj)]`. Note that the callbacks can operate on the whole object, but when a position is given, this might seem a bit quirky. A workaround could be to put a whole-object index on the key position, but that's only slightly better. Better then to use 
* The code in `mnesia_index` has thus been modified to deal with possibly more than one index value per object+index.
* Indexes can be either bag or ordered, where `ordered` corresponds to `{{Val, Key}}` instead of the bag representation `{Val, Key}`. Ordered indexes seem to do much better esp. with large fan-outs.
* Index plugins are added via the schema API. They have the form `{Name, M, F}`, are referred to as `{Name}`, and are called in a similar way as the external copy indexing callbacks, i.e. `M:F(Tab, {Name}, Obj)`. They are not tied to a particular table, table type or position, but of course need to be able to make sense of the object being passed.
* A callback function `ExtMod:is_index_consistent(Alias, IxTag)` is used to determine whether the index should be rebuilt at load time. This is intended for very large tables. The flag is set to true once the index has been built (by calling `ExtMod:index_is_consistent(Alias, IxTag)`). It's up to the backend type to store the flag persistently.

**Comment by dgud** [comment]
Any comments on my changes?
I have for example added create_table before all load_table so that the tables are always opened by mnesia_monitor, I need that otherwise tables disappear  when transaction process dies, i.e. it is the owner of the tables. So now create is (almost) always followed by a load_table which might be strange.

Also in index code, duplicate_bag is removed/replaced with ordered_set shouldn't it be default for ram_copies and disc_copies?

**Comment by uwiger** [comment]
Looking through the changes, I haven't seen much yet to argue with. I haven't inspected all commits yet, partly because github seems to have a bad day.

The create_table before load_table looks good. I absolutely think the ordered_set index type could be default for ram_copies and disc_copies, but didn't want to push that decision by myself.

On commit f480b7c - mnesia_sext - there *is* a branch in [uwiger/sext](https://github.com/uwiger/sext/tree/uw-maps) that implements maps support. I note that it's a bit behind the master branch, so I could try to bring it up to date.

I'm perfectly fine with letting sext become part of stdlib if you so wish. ;-)

**Comment by dgud** [comment]
For now I removed mnesia_sext completly since there is nothing that needs it in this branch,
that is a dependency from eleveldb.

Will do some measurements on the index and see if can change the default to ordered_set

**Comment by uwiger** [comment]
Yes, sorry, as I worked my way up the commits list, I noticed it being reverted. :)

**Comment by uwiger** [comment]
I've scanned all commits and have no complaints. Looks good from a cursory inspection.

**Comment by dgud** [comment]
Thanks.

This index handling get overly complex, and I don't know how to make it work.
Earlier the index implementation was decided by the table type, i.e. ram and disc used duplicate_bag, and disc_only used bag.
You have replaced duplicate_bag with bag or ordered, and let the user decide, but now 
the index must be the same for all backends and I don't see a need for that.
It must be better to only have ordered for ram tables (which currently doesn't work) and bag for disc_only.

Is there really a need to implement several index implementations per backend?

**Comment by dgud** [comment]
Pushed some new changes to my branch. 
Changed the user supplied index type to be preferred and fixed the bugs re-introduced in first revert commit.

**Comment by uwiger** [comment]
BTW, I thought I had written a 'combine' check verifying that all specified backends for a certain table supported all specified index semantics (essentially, bag or ordered), but if I did, I guess it got lost along the way.

**Comment by uwiger** [comment]
So ordered indexes now work for ram_copies (at least according to my tests)?

**Comment by dgud** [comment]
> BTW, I thought I had written a 'combine' check verifying that all specified backends for a certain table supported all specified index semantics (essentially, bag or ordered), but if I did, I guess it got lost along the way.

You had, I removed it in [](https://github.com/dgud/otp/commit/5d21dd8ec4677995087a6e42de7bab5374db65af)

I don't think there is a need for the index to be the same, each backend can decide how it's index will be implemented.

Yes they work and are default, and according to my measurements roughly equal in perf to duplicate_bag.

**Comment by uwiger** [comment]
Ordered indexes are of course not only useful for performance, but also enable new operations, such as index_first and index_next, and possibly also index_prefix_match, where prefix matching is done on the index value. But in this case, if an index is expressly specified as 'ordered', it would need to be actually ordered on all nodes where the table resides. Otherwise, the semantics would be different depending on which backend was used.

If the user has _not_ specified an ordered index, I agree that it should be up to the backend to choose the optimal representation.

**Comment by dgud** [comment]
Merged with my modifications.

**Comment by benoitc** [comment]
@dgud I don't see the commits in master

**Comment by dgud** [comment]
As always we have our internal master branch and the changes will be seen
as soon as our repo is synced with github.

**Pull request closed without merging**
