### PR TITLE
Add Erlang alignment regexps

### PR DESCRIPTION
**Pull request by davidw**
These allow for the alignment of maps and records with the Emacs `align` command.

I think this may be a better, more 'emacsy' way of doing things than this:

https://github.com/erlang/otp/pull/1707

### CODE REVIEW

**Comment by dgud** [comment]
Is there some initialization missing or is this new functionality?
I get "File mode specification error: (void-variable align-rules-list)" in emacs-24.5  and we want to
work with emacs-24.1.

I assume this replaces #1707

**Comment by dgud** [comment]
When testing on some files I noticed that it's missing ':=' for maps.

**Comment by fenollp** [comment]
Hi there, noticed this patch brings some regressions now that #1681 is merged:
https://travis-ci.org/fenollp/erlang-formatter/builds/349321370
Maybe your regexps do not match that recent patch?

**Comment by davidw** [comment]
@fenollp I'm looking, but... I don't see how my patch and that one even interact?  My patch is for maps and records.  I'm not familiar with that test suite - is there some advice on how I could run it locally to check?

**Comment by dgud** [comment]
Merged, Thanks

**Pull request merged**
