### PR TITLE
inets: Copy ipfamily from state into requests & expand httpc IPv6 testing

### PR DESCRIPTION
**Pull request by jchristgit**
See #7802

On redirected and retried requests, the newly started httpc_handler may lose the ipfamily that was originally selected in the request. When sending a request over IPv6 using option `{ipfamily, inet6fb4}` and a redirect is returned by the server, the second request would end up wrongly connecting over IPv4 instead.

### CODE REVIEW

**Comment by jchristgit** [comment]
While trying to make a test case for this (not very successful so far) I found that at the moment to participate in IPv6 testing the host needs to be in the `ipv6_hosts` CT config option. This doesn't seem to be enabled in CI and I wasn't aware of this previously. Is there maybe a more automatic way we could do this? For the `httpd serve` tests I matched on `eaddrnotavail` returns to sometimes skip the case (unfortunately seemed a bit brittle, see #7777)

**Comment by jchristgit** [comment]
I've updated `httpc_SUITE` to add a new group, `sim_http_ipv6` that's essentially the same as `sim_http` but runs it over IPv6. At least `redirect_relative_uri` fails without the fix.

That said, the tests are not being run automatically yet without configuring `ipv6_hosts`, and the `server_closing_connection_on_second_response` & `process_leak_on_keepalive` tests don't seem to work yet, the rest passes (on my end).

**Comment by IngelaAndin** [comment]
The host will be in {ipv6_hosts, [host1, host2 ...]} that is internal to our test runs. This i because this kind of configuration is specific to the environment running the tests. You can make your own common test configuration file with the same kind of entry. Or comment out the requirement in the test suite. The problem is we have not found a good way to ask all our test hosts and get a reliable answer if  they are able to run ipv6 or not.

**Comment by jchristgit** [comment]
> The problem is we have not found a good way to ask all our test hosts and get a reliable answer if they are able to run ipv6 or not.

Ok, that makes sense! I'll go the manual route then. Thank you for the explanation :slightly_smiling_face:

**Comment by IngelaAndin** [comment]
@jchristgit your new group will not initialize TLS setup that is why the test cases fail. See intit_per_group second clause.

**Comment by jchristgit** [comment]
@IngelaAndin Thank you for the help. I did some more investigating and it turned out that including `{ipfamily, inet}` for all requests caused redirects on plain IPv4 _with HTTPS_ to break. Since it's the default, I've updated the code now to not add the ipfamily if we're on plain IPv4 already.

Unfortunately my rebase from maint seems to have crept in some problem with CI - `0.371 Makefile.in has been updated, please re-run configure!` that I'm not sure what to do about - maybe some cache problem?

**Comment by IngelaAndin** [comment]
@jchristgit  if your rebase on latest maint now the check should pass!

**Pull request merged**
