### PR TITLE
stdlib(sys): install one debug function more times & fix bug

### PR DESCRIPTION
**Pull request by Pouriya-Jahanbakhsh**
Hi. First let's find the bug.  
Suppose that i want to install a debug function on `kernel_sup` process:
```erl
1> F = fun(_, _, _) -> io:format("done~n"), new_state end.
#Fun<erl_eval.18.118419387>

2> sys:install(kernel_sup, {F, state}).
ok

3> sys:get_status(kernel_sup).
{status,<0.35.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.34.0>]}],
         running,<0.34.0>,
         [{#Fun<erl_eval.18.118419387>,state}], %% It's here
         [{header,"Status for generic server kernel_sup"},
          ...

4> supervisor:count_children(kernel_sup).
done
[{specs,11},{active,10},{supervisors,4},{workers,7}]

%% I can't install this function again
5> sys:install(kernel_sup, {F, state}).
ok

6> supervisor:count_children(kernel_sup).
done
[{specs,11},{active,10},{supervisors,4},{workers,7}]

7> sys:get_status(kernel_sup).           
{status,<0.35.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.34.0>]}],
         running,<0.34.0>,
         [{#Fun<erl_eval.18.118419387>,new_state}], %% We have just previous function
         [{header,"Status for generic server kernel_sup"},
          ...

%% I will add new function
8> F2 = fun(_, _, _) -> io:format("done~n"), undefined end.
#Fun<erl_eval.18.118419387>

9> sys:install(kernel_sup, {F2, undefined}).               
ok
10> sys:get_status(kernel_sup).                             
{status,<0.35.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.34.0>]}],
         running,<0.34.0>,
         [{#Fun<erl_eval.18.118419387>,undefined}, %% Added
          {#Fun<erl_eval.18.118419387>,new_state}],
         [{header,"Status for generic server kernel_sup"},
          ...
%% Test
11> supervisor:count_children(kernel_sup).                  
done
done
[{specs,11},{active,10},{supervisors,4},{workers,7}]

%% Can i add it again ???
12> sys:install(kernel_sup, {F2, undefined}).
ok

13> sys:install(kernel_sup, {F2, undefined}).
ok

14> sys:install(kernel_sup, {F2, undefined}).
ok

15> sys:get_status(kernel_sup).              
{status,<0.35.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.34.0>]}],
         running,<0.34.0>,
         [{#Fun<erl_eval.18.118419387>,undefined}, %% They have been added !
          {#Fun<erl_eval.18.118419387>,undefined},
          {#Fun<erl_eval.18.118419387>,undefined},
          {#Fun<erl_eval.18.118419387>,undefined},
          {#Fun<erl_eval.18.118419387>,new_state}],
         [{header,"Status for generic server kernel_sup"},
         ...
16> supervisor:count_children(kernel_sup).   
done
done
done
done
done
[{specs,11},{active,10},{supervisors,4},{workers,7}]
```
Because [here](https://github.com/erlang/otp/blob/maint/lib/stdlib/src/sys.erl#L586) we assume that function does not exist but it exists and its state is `undefined`!  
I'm writing new Erlang monitoring app. I want to install debug function to erlang processes and send their I/O to websockets. But i can't install same function more times on one process for sending I/O to more than one websocket process. I think it's good to add same debug function more times on a process. This pull request fixes above bug and can support this feature.

New `install` function:
```erl
 1> F = fun(_, _, _) -> io:format("done~n"), undefined end.
#Fun<erl_eval.18.99386804>

2> FuncState = undefined.
undefined

3> sys:install(kernel_sup, func_id_1, F, FuncState).
ok

%% I can't add any function with func_id_1 again
4> sys:install(kernel_sup, func_id_1, F, FuncState).
{error,already_exists}

5> sys:install(kernel_sup, func_id_2, F, FuncState).
ok

6> sys:install(kernel_sup, func_id_3, F, FuncState).
ok

7> supervisor:count_children(kernel_sup).
done
done
done
[{specs,12},{active,11},{supervisors,4},{workers,8}]

8> sys:get_status(kernel_sup).                      
{status,<0.37.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.36.0>]}],
         running,<0.36.0>,
         [{func_id_3,{#Fun<erl_eval.18.99386804>,undefined}}, %% here
          {func_id_2,{#Fun<erl_eval.18.99386804>,undefined}},
          {func_id_1,{#Fun<erl_eval.18.99386804>,undefined}}],
         [{header,"Status for generic server kernel_sup"}, 
         ...

9> sys:remove(kernel_sup, func_id_1).
ok

10> sys:remove(kernel_sup, func_id_1).
{error,not_found}

11> sys:get_status(kernel_sup).       
{status,<0.37.0>,
        {module,gen_server},
        [[{'$initial_call',{supervisor,kernel,1}},
          {'$ancestors',[<0.36.0>]}],
         running,<0.36.0>,
         [{func_id_3,{#Fun<erl_eval.18.99386804>,undefined}}, %% func_id_1 has been removed
          {func_id_2,{#Fun<erl_eval.18.99386804>,undefined}}],
         [{header,"Status for generic server kernel_sup"},
         ...
```

### CODE REVIEW

**Comment by Pouriya-Jahanbakhsh** [comment]
Hi. I'm newbie in Erlang contribution. What **Team:MW** label means and what is for?

**Comment by garazdawi** [comment]
Hello! The Team labels represent an assignment to the team that will review and eventually merge your pull request. It is for our own bookkeeping and does not effect you.

**Comment by sirihansen** [comment]
Thanks for the information! I see that the possibility of adding multiple instances of a fun would be good, so please go ahead with your new suggestion.

**Comment by Pouriya-Jahanbakhsh** [comment]
Ok. I will open new PR for fixing above bug and adding this new feature (without fixing indentations or white spaces). Thx for reply.

**Pull request closed without merging**
