### PR TITLE
Support emulator restart with new flags

### PR DESCRIPTION
**Pull request by bitwalker**
**NOTE:** This PR requires updating the preloaded beams, which has not been done in this PR, so that changes can be made/it can be merged without conflict. For those interested, you can play with the PR by running the `./otp_build update_preloaded` task after fetching the changes.

This change introduces `init:restart/1`, a variant of `init:restart/0`
which takes a list of flags which will override/extend the ones provided
during first boot, to be applied post-restart.

The purpose of this change is to support the ability to partially
boot a system, perform some reconfiguration, and then restart into that
new configuration cleanly. For example:

* Boot into a minimal system using an initial boot script and base config
file
* During boot, an instruction to apply a function is executed, this
function looks up some configuration from the system environment and
fetches secrets from a configuration management system; this
configuration is merged over the base config, and persisted to a new
`sys.config`
* `init:restart/1` is invoked, updating `-boot`, `-config`, and
potentially `-name` and `-setcookie` flags
* The system boots fully configured

A key point here is that this process allows the reconfiguration step to
configure _any_ application, including `kernel`.

This use case is actually already part of OTP, albeit somewhat hidden. Installing
a new release and making it permanent causes `init` to replace the
`-boot` and `-config` flags, so that restarting the emulator will
restart into the newly installed release, and not the old. The addition
of `init:restart/1` is a generalized extension of this to support additional use
cases.

/cc @josevalim @dch

### CODE REVIEW

**Comment by josevalim** [comment]
This looks great @bitwalker! I do have a question though, based on this:

> This use case is actually already part of OTP, albeit somewhat hidden. Installing a new release and making it permanent causes init to replace the -boot and -config flags, so that restarting the emulator will restart into the newly installed release, and not the old. 

Do you have a link to the release code that does this? Because, depending on the release code, maybe a better API would be `init:set_flags(...)` that both releases and other parties could use? This way we can achieve what you propose by setting `init:set_flags(Opts), init:restart().`. The `set_flags` API would be a bit more general and it would work with releases too, but I am not quite sure if this is desirable.

**Comment by bitwalker** [comment]
@josevalim The code that I'm talking about is actually part of `init`, specifically [`make_permanent/4`](https://github.com/erlang/otp/blob/master/erts/preloaded/src/init.erl#L505). It already consumes the internal `set_flag` function (and as part of the changes in this PR, is refactored to use the new `set_flags`. This function is called after a new release version is installed, and is active, but is not yet marked permanent so that when the VM restarts or is rebooted, the new release is the one booted into.

I think it is probably not desirable to allow setting flags which aren't in effect, i.e. if you can call `init:set_flag/2` but not `init:restart/0`, subsequent calls to `init:get_argument/1` or `init:get_arguments/0` will return potentially anomalous values (depending on what the flags represent). I opted for the approach in this PR for two reasons: it is atomic (the flags are set and a restart initiated in one go, no way to have flags overwritten by another process) and the intended usage is encoded in the API - you can restart with new flags, and they can be passed on the command line, but they always reflect the current VM configuration.

That said, if we want to proceed in that direction instead, that's fine by me, just let me know and I can make the changes :)

**Comment by josevalim** [comment]
> I think it is probably not desirable to allow setting flags which aren't in effect, i.e. if you can call init:set_flag/2 but not init:restart/0, subsequent calls to init:get_argument/1 or init:get_arguments/0 will return potentially anomalous values (depending on what the flags represent). I opted for the approach in this PR for two reasons

This makes sense, thanks for the clarifying! :+1:

**Comment by sirihansen** [comment]
Please add tests and documentation after addressing the comments in the review.

The documentation should possibly include a warning saying you should not do this unless you really know what you are doing.

**Comment by josevalim** [comment]
Hi @sirihansen!

I have been exploring this feature in a side-project. What I want to achieve is to start part of the system, process some configuration files written in Elixir, write them down as `.config` files, and then restart the system with this new configuration. When the system is restarted, I detect the configuration file was already written, so I let it continue to boot without the restart.

I can achieve all of this without this patch by doing the following:

  1. Careful ordering of how the applications are started in the boot file. I want to start a minimum subset of the system until I process the Elixir config

  2. The initial boot is done with a sys.config that points to an empty "elixir.config" (it has only `[].`). On the first boot, I detect this file is empty, process the  Elixir config, and then write down the new "elixir.config". Then I trigger the reboot and all of my new configs should be loaded

The only trouble I have ran so far is regarding the `-name` and `-sname` flags. I don't want the VM to register to EPMD on the first boot. But I do want it to be registered on restart. I have read the `kernel` docs and there is no configuration to disable starting of the distribution. Have I missed something? I could of course have a dummy epmd_module and swap that instead but it may be overkill?

The reason why I am asking this is because we may have an easier way to achieve a large subset of this PR by simply adding a configuration to kernel that controls if distribution is started. That's because we can write a proper boot file and rely on sys.config to include other configs. So we only need to find a way to handle `-name` and `-sname`. Thanks for your time!

**Comment by josevalim** [comment]
I actually went ahead and sent a PR here: https://github.com/erlang/otp/pull/2088

And now when I boot the system the first time, I have these two files:

    # sys.config
    [{kernel. [{start_distribution, false}]}, "elixir.config"}].

    # elixir.config
    [{elixir, [{reboot_configs, [{"elixir.exs", "elixir.config"}]}]}].

And then in Elixir I detect the `reboot_configs` and evaluate the "elixir.exs" config file, writing its results to "elixir.config". The final "elixir.config" will have many options set, including one that enables the distribution back:

    # elixir.config
    [{kernel, [{start_distribution, true}]}, ...otherconfig...].

And this works like a charm. To recap, it does not provide all capabilities in this PR, but by relying on the fact `sys.config` can have multiple config files and that I can also control the boot order, I can achieve something similar as setting the `-boot` and the `-config` flags by hand. The only missing 
 part is controlling when distribution runs, which is possible with the PR above.

**Comment by sirihansen** [comment]
@josevalim Have you looked at net_kernel:start/1? If you start the node without distribution, you could use this after init:restart/0  - to turn the node into a distributed one. You need to pass the name in some way that is not the `-name` or `-sname` flags though.

**Comment by josevalim** [comment]
@sirihansen the reason why I still want to pass -name and -sname is because there is other behaviour associated with those flags, such as starting `epmd` automatically. `inet_config` also behaves different if those flags are given and I want all of those to behave the same.

Furthermore, by skipping the distribution services, I can guarantee that the first and initial boot goes a bit faster too. :)

Thoughts?

**Comment by sirihansen** [comment]
Ok, I see your point. In that case I think that #2088 is a better solution than this PR, since I believe you can do much more harm with `init:restart/1` than with the `start_distribution` parameter.

**Comment by sirihansen** [comment]
Is it ok to close this now, after #2088 has been merged? Or is there still something here that you want to continue on?

**Comment by bitwalker** [comment]
I think it's fine to close this for now, thanks!

**Pull request closed without merging**
