### PR TITLE
Implementation of Little Endian encoding for ports.

### PR DESCRIPTION
**Pull request by cleverfox**
My implementation of little endian packet header for decode_packet/3 and ports.
To select little-endian header specify negative length: {packet, -2} or {packet: -4}
Update preloaded module prim_inet needed!

Sorry I didn't tried to build on win32.

### CODE REVIEW

**Comment by okeuday** [comment]
It would be nice to be able to choose 'native' along with 'little'.  That would probably required a proplist entry with the key 'packet_endian' with the values 'big' (default), 'little', or 'native'.  Doing things that way would be easier to understand than the negative numbers, in addition to supporting the native endian.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Implementation of little and native endian via {packet_endian,X}
Implementation of Little Endian encoding for ports.


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Implementation of little and native endian via {packet_endian,X}
Implementation of Little Endian encoding for ports.


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Implementation of Little Endian encoding for ports.


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by cleverfox** [comment]
I made {packet_endian,X}, as you asked. Tested on FreeBSD/amd64, FreeBSD/i386 and Linux(Ubuntu)/i686 (little endian hardware) and also FreeBSD/sparc64 (big endian hardware). Everything working as expected. 
Unfortunately I can't compile erlang on win32 yet, but it must be tested, because patch also contains win32 specific code. I keep trying to make win32 build environment. I not win32 expert, if somebody familiar with windows development can help me with building and testing win32 version, it will be perfect.

**Comment by okeuday** [comment]
Yeah, it looks like a good approach to me.  It just requires an Erlang/OTP team member from Ericsson to guide this, since they control Erlang development.

**Comment by sverker** [comment]
Is there a **real** use case for this feature?

/Sverker, Erlang/OTP

**Comment by okeuday** [comment]
@sverker My interest in this feature is that it allows Erlang socket use without forcing everyone to use big endian which is often inconvenient.  Allowing a native endian size to be provided is simpler when using basic C or C++ source code, or even a higher level programming language.  The little endian option would provide a way for Erlang to work with existing protocols that are legacy and had decided that little endian was best in the past.  This feature makes Erlang socket integration more flexible and useful than it currently is.

**Comment by essen** [comment]
This is something that would have helped me way back when I was learning Erlang, as my first aim was to use Erlang to reimplement a game server that used little endian size in the first 4 bytes of all of its 300ish different packet types.

**Comment by cleverfox** [comment]
There are too much software with little endian packet headers (native endian in real, but most of computers are little endian). I seen many programms with packet header in first element of C struct (in native endian).
Very often these methods are used for Unix sockets, but also in TCP. I understand that this method is not good and there is "network byte order" which is big-endian, but many of us still need support tons of legacy applications, which is not well designed. I understand that I can do it by {packet, 0} sockets, but will be nice (and faster), if Erlang will do it itself.
If you google about little endian packet support in Erlang, you will see many questions about it. Also there is  EEP 34, which is partially implemented in my patch.

**Comment by sverker** [comment]
Thanks guys for the input. I just wanted to get the motivation out of the way before discussing the interface.

There have been objections raised here at OTP about the interface; a new option 'packet_endian' that only affects a subset of the existing packet protocols. If we instead include byte order information in the existing packet option. Something like:

{packet, {4, little}}
{packet, 4, little}
{packet, '4_little'}

We will discuss this next week. Opinions, anyone?

**Comment by essen** [comment]
`{packet, 4, little}` gets my vote. Probably pointless to add `big` or `native`, `little` should be enough.

**Comment by okeuday** [comment]
`native` would have been helpful for my usage of localhost sockets and it helps match Erlang binary endian syntax, so I strongly believe it is beneficial. The `{packet, {4, little}}` format matches current usage of the packet tuple best due to keeping it 2 elements, matching the Erlang binary syntax order (size, endian), and it doesn't require making new odd atoms.

**Comment by cleverfox** [comment]
I believe that native endian really needed. I don't know about moderm CPUs, but I now that exists CPUs with middle endian byte order (l1,l0,l3,l2 or l2,l3,l0,l1) (http://en.wikipedia.org/wiki/Endianness#Middle-endian). 
I disagree with {packet, 4, little} and {packet, '4_little'} variants. First because this tuples is not compatible with proplists and may break compatibility, second variant also not too elegant. 
But vartiant with {packet, {4, little}} and {packet, 4}, {packet_endian, little} looks OK, and I have no idea which of them better. 
All of us may vote for favorite variant. :)

**Comment by sverker** [comment]
The OTP technical board thinks this is a desirable feature.

But we think the interface should be {packet, {N, Endian}}
where N is 2 or 4 (for now) and Endian is big, little or native (the same atoms used in bit-syntax).

To further approve the patch it must have
* Documentation.
* Tests. It's probably a good idea to complement existing tests, such as gen_tcp_echo_SUITE, decode_packet_SUITE, port_SUITE, ssl_packet_SUITE.
* Erlang implementation for ssl that also supports the packet option.
* Correct indentation. The indentation was really off in some code.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by ollema** [comment]
What is the status on this?

**Comment by cleverfox** [comment]
Sorry, guys, I too busy now. But I will make it a little bit later.

**Comment by proxyles** [comment]
Ill close this for now

**Pull request closed without merging**
