### PR TITLE
Export type gen_udp:socket/0.

### PR DESCRIPTION
**Pull request by ethercrow**
It's documented but not exported, that got me confused.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Export type gen_udp:socket/0.


----------------

I am a script, I am not human 

----------------

**Comment by ethercrow** [comment]
I've removed the "."

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
LGTM

**Pull request merged**
