### PR TITLE
changes to fix erlang hung issue on IPv6 setup

### PR DESCRIPTION
**Pull request by peculiar-pooja**
Fixing problem in inet_drv.c where code is crashing due to infinite loop while searching interfaces
Also updated code to avoid use of uninitialised pointer and updated macro to set variable to NULL after free.

For more details refer rabbitMQ thread: https://groups.google.com/g/rabbitmq-users/c/FJgf_Pp1O4c?pli=1

### CODE REVIEW

**Comment by bmk** [comment]
Looks good.
The only thing we did not like was the changes to the FREE macro.

**Comment by lukebakken** [comment]
@bmk you should be able to push directly to the `peculiar-pooja:ip_interface_fix` branch and revert the changes.

**Comment by peculiar-pooja** [comment]
@bmk I actually changed macro to make sure that freed variable is always assigned to NULL, this will avoid dangling pointer issue.

**Comment by bmk** [comment]
Sorry for the delay.
Yes, I/we got why the macro was changed. Its just that this macro is used *everywhere*,
and this is rather basic behaviour (which now hides side effects).
Anyway, I made a branch based on your branch and reverted the macro. When I compiled,
I (the compiler actually) also found a missing '}', which I fixed.
At the moment, we do not have a IPv6-only machine, so we cannot verify this...

**Comment by bmk** [comment]
And now I *think* I managed to push my updates to your branch...better late than never...

**Comment by peculiar-pooja** [comment]
please let me know next step to merge this into master branch?

**Comment by lukebakken** [comment]
@peculiar-pooja - @bmk made this statement:

> At the moment, we do not have a IPv6-only machine, so we cannot verify this...

Can you provide an IPv6-only server (a VM would be ideal), or instructions for how to create one?

**Comment by bmk** [comment]
The test would be to simply call the function and make sure it does not hang.
And also returns the expected information.
There is only one (1) explicit test case for this function (in the inet_SUITE),
but it is used (as a utility) in several test suites.
For the future it would of course be *useful* to have the instructions for how to create one
(we tried, but could not figure out how to make it work), so *please* provide them!

**Comment by bmk** [comment]
Something I have forgotten:
Depending on what version (of OTP) you are using, net:getifaddrs/0,1,2 might work.

**Pull request merged**
