### PR TITLE
Add stacktrace in max heap size log

### PR DESCRIPTION
**Pull request by zzydxm**
This commit externs the current_stacktrace function and use it in erl_gc when doing max heap event log. This is especially useful when debugging a process that has been killed by the heap limit.

I'm not sure if this is the right way doing it, but here is how it will look like:

```
./bin/erl +hmax 1000000
Erlang/OTP 27 [DEVELOPMENT] [erts-14.0.2] [source-05c52ba036] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> lists:seq(1,1000000).
=ERROR REPORT==== 25-Aug-2023::14:41:56.256793 ===
     Process:            <0.85.0>
     Context:            maximum heap size reached
     Max Heap Size:      1000000
     Total Heap Size:    1029719
     Kill:               true
     Error Logger:       true
     Message Queue Len:  0
     GC Info:            [{old_heap_block_size,318187},
                          {heap_block_size,711488},
                          {mbuf_size,0},
                          {recent_size,150168},
                          {stack_size,26},
                          {old_heap_size,196624},
                          {heap_size,196616},
                          {bin_vheap_size,0},
                          {bin_vheap_block_size,46422},
                          {bin_old_vheap_size,8},
                          {bin_old_vheap_block_size,46422}]
     Stacktrace:         [{erl_eval,do_apply,7,
                                    [{file,"erl_eval.erl"},{line,750}]},
                          {shell,exprs,7,[{file,"shell.erl"},{line,780}]},
                          {shell,eval_exprs,7,[{file,"shell.erl"},{line,736}]},
                          {shell,eval_loop,4,[{file,"shell.erl"},{line,721}]}]

** exception exit: killed
2>
```

### CODE REVIEW

**Comment by zzydxm** [comment]
Hmmm could anyone point out which test SUITE does the code fail? I can't figure it out from the log and I don't see anything fail in my local make test.

**Comment by sverker** [comment]
I added two commits. Basically to avoid building the stack trace on the process heap. I'm not sure but it may be problematic when we have reached `max_heap_size`.

**Comment by zzydxm** [comment]
Thanks for the suggestions! It looks good to me.

Are the failing tests otp_17127_local_link_with_simultaneous_link_unlink and otp_17127_local_random? They both worked on my laptop (m1 macbook). Is there anything I can do here?

**Comment by sverker** [comment]
> Are the failing tests otp_17127_local_link_with_simultaneous_link_unlink and otp_17127_local_random? They both worked on my laptop (m1 macbook). Is there anything I can do here?

Yes, those are the failing ones. It's due to a bug on master branch.

**Comment by zzydxm** [comment]
Sure, will do. Thanks a lot!

**Pull request merged**
