### PR TITLE
Fix typo in xmerl_scan:string/1

### PR DESCRIPTION
**Pull request by goofansu**

### CODE REVIEW

**Comment by goofansu** [comment]
I have a problem about format.

I'm using erlang-mode in Emacs. By default, I enabled `whitespace-cleanup` for saving a file. But I found the format was messed when I save the file,  I can only disable `whitespace-cleanup` to modify it. So what's the config to edit the project?

Thanks

**Comment by goofansu** [comment]
@legoscia Thanks for the explain. Why does it keep both tabs and spaces? Can we just format it replacing tabs with spaces?

**Comment by goofansu** [comment]
@legoscia I agree, thanks.

**Comment by garazdawi** [comment]
> While it would be a "bump" in the version history, it would be fairly easy to ignore when looking for changes further back in history.
We quite often base fixes on old releases and merge them forward to maint/master in case someone needs the patch on older releases. Having a commit that causes merge conflicts all the time would create a lot of extra work.

Anyways, @goofansu would you mind rebasing this fix onto latest "maint" and change this PR to target that branch instead? That way the fix will be released soon rather than in 1 years time.

**Comment by goofansu** [comment]
@garazdawi done

**Comment by garazdawi** [comment]
thanks for you contribution!

**Pull request merged**
