### PR TITLE
Fix erl_tar's handling of filename/path length limits

### PR DESCRIPTION
**Pull request by bitwalker**
Previously, erl_tar was not properly handling the case where
a filename either exceeded the maximum allowed length (including path),
or if any one component was longer than 100 bytes. The former would
fail when asserting that the total header size was 512 bytes, the latter
would fail with a difficult to trace error for users, and is incorrectly
requiring every path component to be 100 bytes or less.

This commit fixes the error handling in both cases by ensuring that
errors are bubbled up to the caller. Callers can then format errors
appropriately.

This commit addresses the first issue by checking the filename length up
front and returning an error if it's length exceeds the maximum allowed.
It addresses the second issue by modifying the old filename splitting
code to return errors in the correct cases.

This commit also updates the code which performs zero-padding to use
`lists:duplicate/2`, rather than the previous implementation which was over-complicated (probably because `lists:duplicate/2` didn't exist when `erl_tar` was written, but that's just a guess) - this makes the code much simpler to understand,
and is likely more efficient as well (though I haven't benchmarked it).

### CODE REVIEW

**Comment by bjorng** [comment]
> This commit also updates the code which performs zero-padding to use
`lists:duplicate/2`, rather than the previous implementation which was over-complicated (probably because `lists:duplicate/2` didn't exist when erl_tar was written, but that's just a guess) - this makes the code much simpler to understand, and is likely more efficient as well (though I haven't benchmarked it).

No, that's not reason. `lists:duplicate/2` did exist when I wrote `erl_tar`. The reason is that `zeroes/1` produces less garbage and iterates fewer times than `lists:duplicate/2`.

Over-complicated? I am not sure. Let's say that I agree that it is more complicated than using `lists:duplicate/2`.

There was no bit syntax when I wrote `erl_tar`, so I could not simply write:

`<<0:Number/unit:8>>`

The change to `zeroes/1` is unrelated to the fix of error handling, so please make it in a separate commit. It is OK to include it in the same branch.

**Comment by bjorng** [comment]
Please add tests to the test SUITE to test your changes. Otherwise it is difficult to know that they are correct.

**Comment by josevalim** [comment]
@bjorng given the limitations folks are running with 100 characters in filenames for `.tar`, shall we add `systools:make_zip` that builds a release using a zip? The release handler could automatically unpack based on the file extension. From a quick glance at the code, this should be relatively straight-forward as the code groups all of the `erl_tar` access functions in a single place.

**Comment by bjorng** [comment]
> Given the limitations folks are running with 100 characters in filenames for `.tar`, shall we add `systools:make_zip` that builds a release using a zip?

Yes, I think that is a good idea. It would be possible to modify `erl_tar` to support a newer TAR standard that allows longer file names, but I would expect that to be a non-trivial amount of work.

@sirihansen what do you think?

**Comment by bitwalker** [comment]
@bjorng Ah I see, I'll update the PR and remove that change.

RE: Supporting zip, I've got another PR with most of that completed, though I hit a snag due to not being able to modify zip files (there is no `zip:add` which mirrors `erl_tar:add`), so I have to rethink it a bit. A co-worker of mine was going to send me some details on a newer tar format, and I'm going to check that out to see if it is actually a simpler change, given the restriction above.

**Comment by bitwalker** [comment]
It looks to me like we can add support for the `pax` format while remaining backwards-compatible with `ustar` (i.e. we can extract old `ustar` tarballs, but use `pax` for anything new). That thinking is based on what I'm reading [here](https://github.com/libarchive/libarchive/wiki/ManPageTar5#POSIX_ustar_Archives), if anyone else would be willing to take a look and give me your thoughts on whether supporting `pax` is worthwhile (I believe so, as it effectively removes any filename limits), or whether an alternative packaging format like zip is preferred, I'd greatly appreciate it.

I think we want `erl_tar` to support `pax` archives anyway, since it's effectively the latest standard, so it seems like we would kill two birds with one stone.

**Comment by bjorng** [comment]
Yes, it would be useful for `erl_tar` to support `pax`, so if you are willing to implement it would be great.

**Comment by bitwalker** [comment]
Great! I've started work on that, I'll open another PR when that's ready.

**Comment by sirihansen** [comment]
I believe that supporting `pax` is the best way to go. A PR will be much appreciated!

**Comment by bjorng** [comment]
Should we close this PR, now that #1320 add PAX support? I suppose this PR could still be released as a bug fix for the next minor release. I am not sure that it would be worth doing.

**Comment by bitwalker** [comment]
I'm not sure to be honest - on the one hand, the error received currently is really bad, but it is documented in the places where people are most likely to encounter it (namely when building releases with relx/exrm/distillery), so it's not a high priority - the important bit is the support for PAX. I'll let you decide one way or the other :)

**Comment by bjorng** [comment]
In that case I will close it. I agree that it is not high priority to fix this bug, and this PR would require additional work (additional tests cases + code review) before it would be ready to be merged.

**Pull request closed without merging**
