### PR TITLE
Fix unsafe edge cases for in-place update of records

### PR DESCRIPTION
**Pull request by bjorng**

### CODE REVIEW

**Review by garazdawi — APPROVED** [review]

**Comment by alexandrejbr** [comment]
@bjorng we have noticed a performance degradation (execution time) after this change. I don't have any more information than this at the moment.

Since I don't have yet any more information at the moment I just want to ask if you'd be expecting that a performance degradation would occur after this change?

**Comment by bjorng** [comment]
Yes, a performance degradation can occur if the change disabled an unsafe in-place tuple update in your code.

**Comment by alexandrejbr** [comment]
@bjorng thanks! We must be doing some kind of anti pattern because for certain test cases we are seeing 36% execution time increase with OTP 27.0.1 compared to the -12% gain we had when we switched to OTP 27.0.

**Comment by alx242** [comment]
@bjorng I am trying to see if any such thing is happening in our code atm but I have hard time detecting it. Do you happen to have a simple method to detect the disabling of an unsafe in-place tuple update?

**Comment by bjorng** [comment]
There is a change in the compiler in Erlang/OTP 27.0.1 that could potentially explain the slowdown: 28d0a974c11c11f0a2d392b92b55c243c2487f98.

If you have re-compiled your source code with Erlang/OTP 27.0.1, it is possible that some record update operations are no longer optimized. If you have not re-compiled your source, the change in the compiler is not responsible.

To check whether a record update operation uses the in-place optimization, compile using the `-S` option. Examine the `.S` files. The first operand for an `update_record` instruction is `{atom,inplace}` if operation could be safe to do in-place.

**Comment by alx242** [comment]
I have recompiled my code with the fix from 5dccb4539994ad57e446becee273d225d9485a21 and with it the performance degrades a bit. If I revert that commit my code runs faster. 

I checked the assembly listings of my module that is affected and I did see a few locations with `update_record`  that have `{atom,inplace}` instruction. However the generated assembly listing looks the same with or without the commit mentioned above.

So can the above mentioned commit impact performance even if the assembly listing becomes the same?

**Comment by alx242** [comment]
Sorry I mentioned the wrong commit. Rather it is this commit that made my performance degrade: a1805974f864fe68280feecac2839be6e4ea0016.

**Comment by alx242** [comment]
FYI! I tried adding this line: `p->high_water = (Eterm *) (Uint) -1;` in `erts/emulator/beam/erl_gc.c`  on an OTP-25 version instead and noticed the degradation there as well with my code.

The commit mentions JIT which I'm not using so it feels like it has impact outside of that.

**Comment by bjorng** [comment]
> Sorry I mentioned the wrong commit. Rather it is this commit that made my performance degrade: [a180597](https://github.com/erlang/otp/commit/a1805974f864fe68280feecac2839be6e4ea0016).

That's make more sense to me. I expect that #8751 should fix it. Please try it.



> The commit mentions JIT which I'm not using so it feels like it has impact outside of that.

Yes, it has.

**Comment by alx242** [comment]
Will try it 👍

**Comment by alx242** [comment]
My performance issues disappeared :-D great!

**Comment by bjorng** [comment]
Thanks for reporting this performance regression!

**Comment by alx242** [comment]
Thank you for fixing it :)

**Pull request merged**
