### PR TITLE
Do not crash/warn in group_history during disk_log shutdown

### PR DESCRIPTION
**Pull request by josevalim**
Because the disk_log is started after the `user` process, there
is a chance for race conditions on shutdown, where disk_log will
terminate before `group`, which will fail to log.

Furthermore, if disk_log terminates BEFORE the shell starts,
then the whole shell will fail to start, which will trigger
another shell recursively, until the system finally shuts down.
This can be reproduced with this command:

    $ erl -kernel shell_history true -s init restart

### CODE REVIEW

**Comment by josevalim** [comment]
Arguably, a better fix would be to permanently solve the race condition. However, changing the kernel initialization order need to be done carefully. Another option is to make the `init` module aware of the shell and have it terminate or flush the user_drv early on shutdown, but I am not sure this is desired either. After all, if the system gets stuck during shutdown, you may still want to connect remotely to it.

/cc @ferd

**Comment by josevalim** [comment]
Please hold on, there are other race conditions. Sometimes `group` fails to start because `disk_log` is shutting down.

**Comment by ferd** [comment]
The patch looks good to me. I would be very nervous about changing init order. The group order or making init aware of the shell (and even then we could trigger some races)

**Comment by garazdawi** [comment]
looks file to me, putting into test. Speaking of tests, would it be possible to add any for this, or is it very difficult to trigger?

**Comment by josevalim** [comment]
@garazdawi I cannot always reproduce it but I think we could write a test that checks that `erl -kernel shell_history true -s init stop` closes without writing "*** ERROR: Shell process terminated! ***". The issue though is that this error only happens when starting the shell with tty and I don't know how to do that programmatically. Every time I programmatically start `erl` it uses the old shell. Any ideas on how to address that or is there any test case I can use as an example?

**Comment by garazdawi** [comment]
You can check the `interactive_shell_SUITE` for examples about how to do that. It is not simple, but it is possible :) I think we can live without a test if you cannot manage to create one.

**Comment by josevalim** [comment]
@garazdawi test pushed!

**Pull request merged**
