### PR TITLE
Always fallback to source when we can't parse AST

### PR DESCRIPTION
**Pull request by josevalim**
This commit fixes a bug in Dialyzer where it would assume
all Erlang AST can be converted back to valid Erlang code.
A case where this was is no true was already documented
in the source code, in relation to opaque  types, but this
can also be true when it comes to other BEAM languages.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @uabboli, sorry for pinging, but any chance this can be merged? Dialyzer is failing to report errors for many Elixir users. Thank you.

**Comment by uabboli** [comment]
Sorry it's been taking so long. Thank you for the PR and your patience.

I've tried to come up with an alternative implementation, but I don't
think there is one. The only thing that would work is that if the
Backend in dialyzer_utils:get_core_from_beam could do some rewriting
into valid Erlang, but I assume that is not really an alternative.

The reason I'm been trying to find an alternative is that I think it's
better to crash if there is a bug, but I'm sure not everyone agrees.

Anyway, it's not a big deal, and we'll accept the PR. Maybe the
comment in dialyzer.erl about catching any error doesn't need to
mention the DEBUG macro in erl_types; it should suffice to say that
the AST not necessarily transforms into valid Erlang code. What do you
think?

The 22.1 release (maint, not master) is scheduled for September. To
get the fix into 22 before that, I'll rebase your branch and test it
on the 22 patch branch.

**Comment by josevalim** [comment]
> I've tried to come up with an alternative implementation, but I don't
> think there is one. The only thing that would work is that if the
> Backend in dialyzer_utils:get_core_from_beam could do some rewriting
> into valid Erlang, but I assume that is not really an alternative.

One other option I can think of is to somehow detect if this is an erlang module or not. Maybe we can look at the source and see if it ends with `.erl`? And then we do no formatting if that is not the case.

**Comment by uabboli** [comment]
> One other option I can think of is to somehow detect if this is an
> erlang module or not. Maybe we can look at the source and see if it
> ends with .erl? And then we do no formatting if that is not the case.

I had convoluted thoughts about saving the Backend, but couldn't make
it work. (*)

Using the filename associated with the message is much easier, but I'm
not sure it's doable. There are extensions .hrl, .xrl, .yrl, and
possibly more, see erl_compile. And the -file attribute makes it
possible to cheat.

(*)

- in dialyzer:get_core_from_beam one can store the Backend in the
  annotation of the top of the tree;

- dialyzer_dataflow can find the annotation and store in its state,
  and when a message is generated, the backend can be associated
  with (the whole) message somewhere, globally accessible; format_warning
  just needs to look up the message to find the backend;

- but if the messages are formatted after some time--if, for example,
  they are read from a file--that won't work since the lookup table is
  gone. But maybe it'd be OK not to crash if the formatting fails and
  there is no lookup table?

**Comment by josevalim** [comment]
Yes, it does look convoluted. :( The only other option I can think of is to have an option to raise and instruct tools like rebar3-dialyzer integration and change OTP's makefiles to pass this option. It does mean it won't error by default in some case but if the goal is to catch bugs in OTP (which is the only time raising would be called), it should be good enough?

**Comment by uabboli** [comment]
I think I'll stick to my first comment of yesterday--it seems like
this is far more work than is motivated by such a small gain. If
someone experiences an unindented warning, I trust they will report it
as a bug.

So, if you could simplify the comment, I'll make sure the PR makes
into next 22-patch.

**Comment by josevalim** [comment]
@uabboli done, thanks!

**Comment by uabboli** [comment]
Merged commit 9991cba7ba29d632dfad03783e6a0183611f06ee into erlang:maint.

**Pull request closed without merging**
