### PR TITLE
Fix various small typos in the OTP Design Principles

### PR DESCRIPTION
**Pull request by lars-olsson**
While reading the OTP Design Principles, I noticed various minor typos in the writing. 
Here is my attempt to fix those.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
We think that this PR improves the language, and we will merge it. However could you rebase it to maint, as it would be a shame for the improvements to have to wait until OTP-24 next year.  Your branch did not trivially rebase, so I guess you need to do a rebase --onto and force push .

**Comment by lars-olsson** [comment]
Forgive my errors, I'm not very familiar with using the more advanced features of git. I've been experimenting with how to do the rebase/push. I ended up doing 'git rebase --onto maint master'. I hope this is what was desired.

**Comment by sverker** [comment]
I saw some of my merged commits part of this PR, so I took the liberty to clean things  up.

I force pushed a new version of branch docs/design_principles_typos to your github repo. It contains **one** commit (https://github.com/erlang/otp/commit/f5cf1840e6b491512d545037cc2cf4189ec79907) which **you** created with git rebase --onto maint master. Assuming that rebase went well we should be fine now.

To sync your local branch do
git checkout docs/design_principles_typos
git reset --hard f5cf1840e6b4915

**Comment by sverker** [comment]
I also clicked the "Edit" button at the top of this page and changed base from master to maint.

**Pull request merged**
