### PR TITLE
User defined tls alert for selfsigned cert

### PR DESCRIPTION
**Pull request by sircinek**
This PR aims at giving user possibility to generate custom TLS alert for path validation errors.
Previously, no matter what user defined verify_fun returned, the alert was always Bad Certificate.
The changes allow user to control TLS alert in similar way that is done for certificates with valid paths.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Thank you for your contribution. We think that the principal is sound, that is the return of the users verify_fun should be honored.  We have included the PR in our test runs.  We also want to ask you to
change the documentation <note> to  a  <warning>.

**Comment by sircinek** [comment]
> Thank you for your contribution. We think that the principal is sound, that is the return of the users verify_fun should be honored. We have included the PR in our test runs. We also want to ask you to
> change the documentation to a .

How would you want me to change it? I was looking for right words to express the changed behavior and that important information might be lost along the way now.

**Comment by IngelaAndin** [comment]
Argh, I should have code quoted. I edited my comment above!

**Comment by sircinek** [comment]
> Argh, I should have code quoted. I edited my comment above!

Sure ! Pushed  requested changes.

**Comment by IngelaAndin** [comment]
I rebased the change to maint as master is now for the upcoming OTP-24 release.  We will merge it once it has passed our test and we reviewed the new documentation (once it is built).

**Pull request merged**
