### PR TITLE
edoc: support multiple clauses in -spec

### PR DESCRIPTION
**Pull request by attah**
This works as far as testing in our project can tell, but i do want to fix a few things:

- The function function in edoc_data that makes argument lists to list of lists of the weren't already (The @spec-parser could perhaps be made to produce list-of-list, even if it doesn't make sense for such specs)
- Passing both clause and nth of a list to element.(but can't think of a much better solution just yet)
- Re-remember or explain the call to flatten in edoc_tags
- Add a test, but how to verify anything more than a non-crash?

Putting it here for hope of help/review and the ability to contribute from home.

### CODE REVIEW

**Comment by attah** [comment]
Well, that failed spectacularly... 
In other news; the flatten in edoc_tags, is probably just me being stupid in doc_specs.erl:88
The crash is an @spec whose data is not a list-of-list for obvious reasons - can be worked around, but should it?
After that follows an xml problem for which i have a fix, but it needs further analysis on why it was needed the first place.
That makes the docbuild pass, but is far from pretty. Stay tuned.

**Comment by josevalim** [comment]
@attah is this code the one responsible for parsing the `@spec` in `edoc` or for formatting existing `-spec` module definitions into the edoc? The reason I ask is because I would rather see `@spec` in `edoc` to be deprecated in favor of `-spec`. Or is there a reason to have both still?

**Comment by attah** [comment]
@josevailm Some of the code in this lib is, yes. But I have really only been dealing with where it is merged with what was found in `-spec` though, as well as adapting the layouting accordingly. Perhaps `@spec` should be more deprecated than it already is. All of edoc is essentially deprecated it seems. This is just a bugfix needed/wanted for a project where we already use it extensively. Deprecating things in Erlang/OTP is not my thing to do, and as such not part of this pull request. If it happens to be planned, i'd be happy to wait for it though.

Since edoc isn't getting much love any more, i'm not sure anyone cares that much about deprecating a part of it even more. I'd rather see what comes of http://erlang.org/eeps/eep-0048.html

**Comment by attah** [comment]
What on earth just happened?
That's what i get for reading how-tos online.

**Comment by attah** [comment]
Anyway, my even more duct-taped (but now passing docbuild) version is here https://github.com/attah/otp/commit/bb14f293dadb71460b0f1003615d41105f5ccf2d
I'll meditate on it a bit and not try to attempt any more git magic for today.

**Pull request closed without merging**
