### PR TITLE
Remove mnemosyne rules support from syntax_tools

### PR DESCRIPTION
**Pull request by richcarl**
Mnemosyne rule syntax is no longer supported in Erlang. This removes the corresponding support in syntax tools.

### CODE REVIEW

**Comment by marcusarendt** [comment]
@richcarl: edoc_extract:collect/7 calls undefined erl_syntax:rule_clauses/1

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
@richcarl, there are no tests covering these changes, can you please add that?

**Comment by richcarl** [comment]
You want tests for functionality that's been removed?

**Comment by zhird** [comment]
Haha no, but no tests are actually testing that the code you changed didn't break. It's more about tests missing from the start but I heard you have done most of these things anyway, right? Right now there are no tests verifying that the old but slightly changed code isn't broken by the changes which I think is bad. It would be great if you can add tests for the changes in erl_prettypr, erl_syntax_lib and erl_tidy (the other "changes" are covered already). Sure the changes are small and the functionality that isn't removed "shouldn't" have changed but since there are no tests for it it's hard to verify that's really the case :)

**Comment by richcarl** [comment]
No, I don't have time to start adding tests now, and I think it's easy to see that the changes only affect code that cannot be executed anymore since the rules and mnemosyne field syntax was removed. I looked over the diff again to verify. Also, pretty much all the erl_syntax and erl_syntax_lib functions get exercised regularly when you run edoc as part of generating docs.

**Comment by zhird** [comment]
Ok, sure, I went through the diff in detail again and it looks good. This time it's ok since it isn't really these changes here that are missing tests, but the already existing functionality. Thanks for the contribution!

**Pull request merged**
