### PR TITLE
Extend CSE to eliminate list and tuple matching

### PR DESCRIPTION
**Pull request by bjorng**
In generated code and in code involving inlining/macros, a newly constructed list or tuple could be matched in the same function.

Here is an example of generated code:

    %% : sqrsum  dup *  swap  dup *  + ;
    sqrsum(SP_0) ->
        [X1|_] = SP_0,
        SP_1 = [X1|SP_0],         % dup

        [X2,X3|SP_2] = SP_1,
        SP_3 = [(X2*X3)|SP_2],    % *

        [X4,X5|SP_4] = SP_3,
        SP_5 = [X5,X4|SP_4],      % swap

        [X6|_] = SP_5,
        SP_6 = [X6|SP_5],         % dup

        [X7,X8|SP_7] = SP_6,
        SP_8 = [(X7*X8)|SP_7],    % *

        [X9,X10|SP_9] = SP_8,
        [(X9+X10)|SP_9].          % +

Here is the main part of the BEAM code for the function:

    {test,is_nonempty_list,{f,5},[{x,0}]}.
    {get_list,{x,0},{x,1},{x,0}}.
    {gc_bif,'*',{f,0},2,[{x,1},{x,1}],{x,1}}.
    {test,is_nonempty_list,{f,4},[{x,0}]}.
    {test_heap,4,2}.
    {get_list,{x,0},{x,2},{x,0}}.
    {put_list,{x,1},{x,0},{x,0}}.
    {put_list,{x,2},{x,0},{x,0}}.
    {get_list,{x,0},{x,1},{x,0}}.
    {gc_bif,'*',{f,0},2,[{x,1},{x,1}],{x,1}}.
    {test,is_nonempty_list,{f,3},[{x,0}]}.
    {get_list,{x,0},{x,2},{x,0}}.
    {gc_bif,'+',{f,0},3,[{x,1},{x,2}],{x,1}}.
    {test_heap,2,2}.
    {put_list,{x,1},{x,0},{x,0}}.
    return.

We can see that there are redundant list construction and
list matching instructions. This commit extends the
existing Common Sub Expression elimination optimization
so that the redundant instructions are eliminated:

    {test,is_nonempty_list,{f,4},[{x,0}]}.
    {get_list,{x,0},{x,1},{x,0}}.
    {gc_bif,'*',{f,0},2,[{x,1},{x,1}],{x,1}}.
    {test,is_nonempty_list,{f,3},[{x,0}]}.
    {get_list,{x,0},{x,2},{x,0}}.
    {gc_bif,'*',{f,0},3,[{x,2},{x,2}],{x,2}}.
    {gc_bif,'+',{f,0},3,[{x,2},{x,1}],{x,1}}.
    {test_heap,2,2}.
    {put_list,{x,1},{x,0},{x,0}}.
    return.

### CODE REVIEW

**Comment by garazdawi** [comment]
Just curious, how much does this optimization show in diffable?

**Review by jhogberg — APPROVED** [review]

**Comment by bjorng** [comment]
> Just curious, how much does this optimization show in diffable?

```
$ diff -u 0 1 | grep ^diff
diff -u 0/beam_ssa_opt.S 1/beam_ssa_opt.S
diff -u 0/erl_erts_errors.S 1/erl_erts_errors.S
diff -u 0/rand.S 1/rand.S
diff -u 0/ssl.S 1/ssl.S
diff -u 0/string.S 1/string.S
```
(`ssl` shows up because of a huge literal map.)

The optimization is applied more than once in `string`.

**Comment by michalmuskala** [comment]
Would it be useful to do something similar for tuples?

**Comment by bjorng** [comment]
> Would it be useful to do something similar for tuples?

Yes. Thanks for the suggestion.

Here is the list of modules that benefitted from optimizing tuples:

```
$ diff -u 1 2 | grep ^diff
diff -u 1/Elixir.String.S 2/Elixir.String.S
diff -u 1/beam_ssa_opt.S 2/beam_ssa_opt.S
diff -u 1/dets_server.S 2/dets_server.S
diff -u 1/dialyzer_utils.S 2/dialyzer_utils.S
diff -u 1/dist_util.S 2/dist_util.S
diff -u 1/elixir_def.S 2/elixir_def.S
diff -u 1/elixir_locals.S 2/elixir_locals.S
diff -u 1/gen_tcp_socket.S 2/gen_tcp_socket.S
diff -u 1/prim_socket.S 2/prim_socket.S
diff -u 1/ssl.S 2/ssl.S
diff -u 1/xmerl_scan.S 2/xmerl_scan.S
```

**Pull request merged**
