### PR TITLE
inets: added missing required property server_name

### LINKED ISSUE #5276: inets example rootserver not starting
Rootserver examples in inets do not start

**To Reproduce**
tony@resurrection:~/bin/otp_src_24.0/lib/inets/examples/server_root$ erl
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

running .erlang in home directory
.erlang completed
Dependencies:  []
LibDir /usr/local/lib/erlang/lib
Eshell V12.0  (abort with ^G)
1> inets:start().
ok
2> inets:start(httpd,[{file,"conf/8080.conf"}]).
{error,{missing_property,server_name}}
3> 

**Expected behavior**
I expected the file option to cause the apache style configuration file 8080.conf to load and start the webserver, which then would have been available via web browser.

**Affected versions**
Version 24.0, other versions not tried

**Additional context**
Stepping through the code, there is no attempt to convert the apache style configuation file to a property list.  Instead httpd_sup tries to validate the supplied property list and finds it lacking.  It looks like support for apache style configuration has been dropped without changing the examples.  The {file,Path} option is documented but not working when called in this way, and if the example should be started with some other procedure, that is not clear from a readme or other documentation.

### PR DESCRIPTION
**Pull request by tonywallace64**
config file changed from apache format to erlang terms

Closes #5276

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Hi, thank you for the PR. Could you please base it on maint so that it can be part of the OTP-25 track, this improvement I think should not be delayed until OTP-26!

**Comment by IngelaAndin** [comment]
Closes #5276

**Comment by IngelaAndin** [comment]
You need to stand on your branch and do a rebase --onto maint HEAD~1

**Comment by u3s** [comment]
tony can you do some more adjustments in this PR or would you prefer if I take it over and do it?

Those are things I was thinking about:
1. rebase on latest `erlang:maint`
2. adjust the PR to target `erlang:maint` branch
3. squash your commits
4. solve conflict if still present

**Comment by tonywallace64** [comment]
Please do.  I have rebased onto maint.  However I put wrong PR request
on pull.  Rickard-green has added team:PS label two days ago.
 Screenshot attached.  

There also remains the issue of ssl.conf example.  I have converted the
file but have not yet got it running. I could put that on my own github
fork if it helps.

Tony

**Comment by u3s** [comment]
please push it to your fork. I will combine it when time allows. thanks for contribution.

**Comment by tonywallace64** [comment]
Okay, pushed new ssl.conf to master branch on my fork

**Comment by u3s** [comment]
sorry to write this, but I've been busy with other tasks. This need to wait to little longer.

**Comment by tonywallace64** [comment]
I have just pushed some more conf files.  I did not do the ssl one
as a straight format conversion did not work so that will take a bit
more work.

**Comment by anupamasingh10** [comment]
Hi @tonywallace64, the conf files should look something like:
`[{port,8080},
{server_name,"your.server.net"},
{socket_type,ip_comm},
{modules,[mod_alias,mod_auth,mod_esi,mod_actions,mod_cgi,mod_dir,mod_get,
          mod_head,mod_log,mod_disk_log]},
{server_admin,"jocke@erix.ericsson.se"},
{server_root,"/var/tmp/server_root"},
{error_log,"logs/error_log_8080"},
{transfer_log,"logs/access_log_8080"},
{security_log,"logs/security_log_8080"}|...].`

In case you wouldn't be able to make these changes, then please let me know and I can continue with this.

**Comment by anupamasingh10** [comment]
Hi @tonywallace64, the conf files should look something like:
```[{port,8080},
     {server_name,"your.server.net"},
     {socket_type,ip_comm},
     {modules,[mod_alias,mod_auth,mod_esi,mod_actions,mod_cgi,mod_dir,mod_get,
          mod_head,mod_log,mod_disk_log]},
     {server_admin,"jocke@erix.ericsson.se"},
     {server_root,"/var/tmp/server_root"} | ...].```
In case you wouldn't be able to make these changes, then please let me know and I can continue with this.

**Comment by anupamasingh10** [comment]
Hi @tonywallace64, the conf files should look something like:
```
[{port,8080},
 {server_name,"your.server.net"},
 {socket_type,ip_comm},
 {modules,[mod_alias,mod_auth,mod_esi,mod_actions,mod_cgi,mod_dir,mod_get,
          mod_head,mod_log,mod_disk_log]},
 {server_admin,"jocke@erix.ericsson.se"},
 {server_root,"/var/tmp/server_root"} | ...].
```

Please let me know if you wouldn't be able to make these changes. I can continue with this then.

**Comment by IngelaAndin** [comment]
Closed in favor of #7079

**Pull request closed without merging**
