### PR TITLE
dialyzer: Clarify how to declare records used in match patterns

### PR DESCRIPTION
**Pull request by uabboli**
See also https://bugs.erlang.org/browse/ERL-892.

### CODE REVIEW

**Comment by mheiber** [comment]
I'm glad this is being discussed, I think it's important to have a standard way of dealing with records used in match patterns when using Dialyzer.

What about match variables like `'$1'` `'$2'` etc.?

**Comment by uabboli** [comment]
You mean the example should be extended to also include pattern variables?

**Comment by mheiber** [comment]
> You mean the example should be extended to also include pattern variables?

Thanks for following up, fwiw I like your idea of extending the example.

I also question the scalability of the approach for code that has a lot of pattern variables, and wonder if a tweak to Dialyzer itself might be better. But this PR is a big improvement over the status quo so I'd really like to see it get in.

**Review by mheiber — APPROVED** [review]
Happy to see documentation for how to solve this common problem.

**Comment by uabboli** [comment]
> wonder if a tweak to Dialyzer itself might be better.

It's not so easy to find a good tweak. Dialyzer needs to somehow know
that the constructed record is be used in match patterns, and nowhere
else.

The example, "ets:match_object(Tab, #person{name = Name, _ = '_'})",
can possibly be handled without much difficulty, but in general I
think types need to be tagged as match patterns internally in
Dialyzer. This resembles how opaque types are implemented, and taking
one step further in that direction would IMHO be a mistake.

But perhaps there is a smart tweak, but until it's found, I think
documentation is the best option.

**Pull request merged**
