### PR TITLE
Optimise ext table dumping

### PR DESCRIPTION
**Pull request by dszoboszlay**
The original algorithm first grouped ops in a commit by ext engine type via folding over the list with `orddict:append/3`, that resulted in an `O(n^2)` algorithm.

However, grouping the ops is not needed, the ops can be dispatched to `insert_op/6` one-by-one, after looking up the storage semantics of their respective engine. This is a much cheaper algorithm, assuming looking up the storage semantics is cheap (which should be).

### CODE REVIEW

**Comment by dszoboszlay** [comment]
This is to replace #2081 based on @uwiger's comment https://github.com/erlang/otp/pull/2081#issuecomment-456339707.

**Comment by dszoboszlay** [comment]
Fixed a mix up of what to pass down to `insert_op/5` (it needs the `Ext` engine itself in the 2nd argument, not the `storage_semantics(Ext)` semantics).

**Comment by dgud** [comment]
You don't need the version check in insert_ext_ops, "ext" was not available in the old mnesia versions.

**Comment by dszoboszlay** [comment]
@dgud I dropped the version check as you suggested. Any other comments?

**Comment by dgud** [comment]
I have not had time to look further into this PR (either).

**Pull request merged**
