### PR TITLE
Fix typo in SSH documentation

### PR DESCRIPTION
**Pull request by c-rack**
"default" instead of "defult"

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
This has already been corrected on master, but thanks for the pr!

**Comment by c-rack** [comment]
@zhird Perfect. Just for my understanding: would I have been better opened the PR to `master` instead of `maint` branch in this case? From the contribution guide it is not clear to me which branch shall be used for a PR.

**Comment by zhird** [comment]
It kind of depends on the timing. Right now our closest planned release is for master (June), so for the moment master would be better. Usually maint is the way to go though, so if you don't want to keep updated on release dates etc its fine to continue to open the PRs on maint. We'll just rebase it to master if needed.

**Comment by c-rack** [comment]
Thanks for clarification!

**Pull request closed without merging**
