### PR TITLE
Honour dist_nodelay socket option in tls_dist proxy

### PR DESCRIPTION
**Pull request by tombriden**
We've seen quite a significant performance impact with a rabbitmq cluster when using TLS for the cluster communications. The only difference I can see, apart from the TLS, is that the plaintext cluster enables the nodelay socket option but TLS doesn't at all. Setting it to true for the incoming/outgoing connection of the tls socket as well as the local plaintext socket seems to speed things up again.

This pull request will honour the existing dist_nodelay option so that a switch from plaintext to TLS uses the same value as configured

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
We will consider this patch for 18.1

**Comment by IngelaAndin** [comment]
I think that the patch looks good, the show stopper at the moment is that there is now test case.
A minimum test could perhaps be one that sets the kernel variable and runs a basic test from
the ssl_dist_SUITE

**Comment by legoscia** [comment]
I pushed a test case on top of this branch in pull request #871.

**Comment by IngelaAndin** [comment]
Accepted #871 instead

**Pull request closed without merging**
