### PR TITLE
Add a bit of documentation about restart_application

### PR DESCRIPTION
**Pull request by davidw**
It should be explicitly stated that the application will not actually be
restarted, depending on how it was originally started, even if it is
currently running.

### CODE REVIEW

**Comment by davidw** [comment]
Relevant to this change:

https://github.com/erlang/otp/commit/3cdd158193146c95c1480d6d11ff4cc277649c24#diff-55e88adafebd4f299ddc8bc4e5a998ab

**Comment by sirihansen** [comment]
Thanks, this is a good addition. I would, however, prefer to have it a bit more specific - like in the description of the `add_application` instruction, that is, please describe what exactly happens for the different start types.

Also, please change `<c>restart_type()</c>` to just `start type`, so the concepts are the same throughout  the document.

**Comment by davidw** [comment]
@sirihansen thanks for having a look! Would it also be worth adding something to the effect of "if you need to restart the application, you can add .... to the appup file"?

**Comment by sirihansen** [comment]
> Would it also be worth adding something to the effect of "if you need to restart the application, you can add .... to the appup file"?

Yes, I guess that would be ok. Were you thinking about an `apply` instruction?

**Comment by davidw** [comment]
@sirihansen yes, if that's not too repetitive.

**Comment by sirihansen** [comment]
That would be ok. If you want to add it, I will need it by the end of this week to be able to get it into OTP-20.3. If later, then OTP-21 will be the release for you.

**Comment by sirihansen** [comment]
Hi, I'm including this in our nightly builds now, and will probably merge it by the end of the week. If you have any addition, then it's time...

**Comment by davidw** [comment]
Cool, thanks!  I would have liked to add an example of `apply`, but this week was a busy one; I'll look into doing it in the future.  Thanks again

**Pull request merged**
