### PR TITLE
Fix dirty scheduler collapse

### PR DESCRIPTION
**Pull request by falkevik**
I have been having issues with dirty schedulers dropping down to only perform work on a few of the online schedulers.
And there is a problem with the list of sleeping schedulers that can be inconsistent.
In some cases, at least when suspending schedulers the schedulers are re-added to the sleepers list.
Can be illustrated with suspending some schedulers with erlang:system_flag/2 providing dirty_cpu_schedulers_online.

In some cases the list of sleeping schedulers became a loop with only one scheduler.
So the only woken up scheduler was that one when there was job arriving.

[collapsed_dirty_scheduler_sleeper_list.txt](https://github.com/erlang/otp/files/2603389/collapsed_dirty_scheduler_sleeper_list.txt)

This PR propose a fix that has been working for me so far.
It is trying to make sure that a scheduler are only added once to the list of sleeping schedulers.
Please have a look and tell me what needs to be changed, if you are to accept this change.

First commit is just to be able to print some dirty_cpu_scheduler info from the break handler.
That commit should probably be removed since it will also add the same information to the crash dump. It was added to be able to check the state of the sleepers list before and after the change.

### CODE REVIEW

**Comment by rickard-green** [comment]
Thanks for the PR! I do, however, not want traversal of the whole list of waiters while holding a spin-lock. I've instead made a PR #2093 solving this issue in a slightly different way. I'm planning the release that fix next week, unless we find any issues with it. Please try it out!

**Comment by falkevik** [comment]
Thanks for looking at the issue.

It is better to not do the traversal of the sleeping schedulers.
I thought I was going to get away with it since it is only when a scheduler are suspended or multi-scheduling are blocked.

Do you think it would be possible to not try to acquire the spin-lock if there are no schedulers in the sleppers list?
I.e. check the sleeper lists with a memory barrier and if empty we do not need to claim any spin-lock.
At least it feels like a theoretically speed up under heavy load.
Maybe it is not worth it?


I will try your PR as soon as possible. 

Thanks!

**Comment by rickard-green** [comment]
> Do you think it would be possible to not try to acquire the spin-lock if there are no schedulers in the sleppers list?
> I.e. check the sleeper lists with a memory barrier and if empty we do not need to claim any spin-lock.
> At least it feels like a theoretically speed up under heavy load.
> Maybe it is not worth it?
> 

In the normal case we expect that there are sleepers in the list. Trying to avoid taking the lock when there are no sleepers would cause the expected case to cost more. The cost will probably not be much, but still an extra cost, and I don't like taking an extra cost in the expected most frequent case in order to optimize the unexpected case. Dirty jobs are also expected to execute for a long time so even if there are no sleepers the lock should not get highly contended.

**Comment by rickard-green** [comment]
We just released OTP-21.2.3 containing the fix in #2093.

**Pull request closed without merging**
