### PR TITLE
httpc: fixed bug when user callback was not called after "remote_close" socket error (ERL-455)

### PR DESCRIPTION
**Pull request by artgl**
Problem and  test case are described in https://bugs.erlang.org/browse/ERL-455

### CODE REVIEW

**Comment by IngelaAndin** [comment]
It would be really good if you could translate your little python test server to Erlang code and add
it to the httpc_SUITE so that we have a regression test.  Also I think the you could remove the deliver_answer function as it always preform the same two lines of code and is only called in one place.
This however I think is a result earlier refractors and such ...

**Comment by artgl** [comment]
Ok, I will rewrite test server using erlang httpd, and will try to integrate this test into httpc_SUITE. However I'm not sure that it is good for any test to wait several minutes till timeout occurs. Another possible problem is that default tcp socket buffer size can differ on different machines, so this should be taken into account during test preparation.

**Comment by IngelaAndin** [comment]
Preferably you can set much lower timeout values that still triggers the behaviour. The timeout of a test does not have to be realistic as long as it emulates the problem correctly.

**Comment by IngelaAndin** [comment]
ping

**Comment by IngelaAndin** [comment]
I managed to trigger the bug in a simpler scenario and make a test case, I also made a slightly different fix.  Thank you for the PR but as it was not completed  we will merge our own version once it passed on all test machines.

**Pull request closed without merging**
