### PR TITLE
Code change utils

### PR DESCRIPTION
**Pull request by richcarl**
Add support for checking whether a module has changed on disk, including new shell shortcuts mm() and lm().
See http://erlang.org/pipermail/erlang-questions/2016-April/088756.html

### CODE REVIEW

**Comment by richcarl** [comment]
Note: I had to update preloaded modules in order to pass the dialyzer check, since I updated types in erlang.erl. You probably want to drop that commit and do it yourselves.

**Comment by bjorng** [comment]
> Note: I had to update preloaded modules in order to pass the dialyzer check, since I updated types in erlang.erl. You probably want to drop that commit and do it yourselves.

Yes. Next time you can just mention that the preloaded modules needs to be updated and we will do it and push it to your branch.

When you pushes this branch next time, remove the commit with preloaded modules.

**Comment by bjorng** [comment]
This looks good. We will test it in our daily builds. I have pushed a fixup commit that fixes the indentation in `code_SUITE` to be consistent with the rest of the file.

If no problems turn up in the testing, the only thing that seems to be missing is documentation. `c.xml` and `code.xml` should be updated (`edoc` comments will not be included in the documentation automatically).

**Comment by richcarl** [comment]
I'm working on some documentation...

**Comment by richcarl** [comment]
By the way, we also have a utility function for listing and purging all loaded modules that have been removed from disk, but that didn't seem as universally useful, so I didn't include it in the above. Is this something you'd like to have as well?

**Comment by bjorng** [comment]
> By the way, we also have a utility function for listing and purging all loaded modules that have been removed from disk, but that didn't seem as universally useful, so I didn't include it in the above. Is this something you'd like to have as well?

No, seems to be too specialized.

**Comment by richcarl** [comment]
Documentation done and minor things (like missing specs) fixed. You'll need to update preloaded again; I dropped your commit by mistake.

**Pull request merged**
