### PR TITLE
Add dialyzer_plt:relocate/3

### PR DESCRIPTION
**Pull request by johanclaesson**
dialyzer_plt:relocate(OldFile, NewFile, BaseDirs) will change the file
paths in given plt file OldFile and save it to NewFile.  The file paths
in NewFile will all be found under the directories in BaseDirs.

This is useful for erlang libraries.  A plt file for all beam files can
be included in the library distribution.  Users of the library can then
relocate the plt file according to where ever they extracted the
library.  This is much faster than building a plt from the beams.

### CODE REVIEW

**Comment by johanclaesson** [comment]
Let me know if i should amend an interface function in dialyzer.erl and doc for that.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by kostis** [comment]
I could see the usefulness of this pull request for some users.  But, IMO, this cannot yet be included as is. For starters, it should come with some tests that guarantee that its basic functionality works and that erroneous situations are properly reported. Moreover, dialyzer comes with a command-line interface where one can build a PLT (`--build_plt` option), add files to it (`--add_to_plt`), or select a plt to use (`--plt`).  Dialyzer's command line interface should also be extended with a `--relocate_plt` option that provides the new functionality.

**Comment by johanclaesson** [comment]
Thanks for the reply.  I agree with your points and i will attempt to add tests, doc and command-line interface when time allows.

**Comment by proxyles** [comment]
reopen when that time has been found

**Pull request closed without merging**
