### PR TITLE
Add `SIGWINCH` and `SIGINFO` support

### PR DESCRIPTION
**Pull request by dumbbell**
## `SIGWINCH`

This signal is emitted when the terminal window is resized to allow an application to redraw its content.

## `SIGINFO`

This signal is emitted when a user types Ctrl+T in a terminal. This is only supported by few operating systems such as *BSD and OSX.

By default, the operating system displays on stdout the system process PID, the system load and the duration the process is running. The signal allows the application to display more details about its status and progress.

### CODE REVIEW

**Comment by jhogberg** [comment]
Merged, thanks for the PR! :-)

**Comment by dumbbell** [comment]
Awesome, thank you!

Just to help me plan my work on RabbitMQ, in which release(s) is this patch likely to land in?

**Comment by jhogberg** [comment]
You targeted `master`, so OTP 28 next year. :-)

**Comment by dumbbell** [comment]
Thank you!

I thought all new features should target `master`. Was it an option to fork `maint` to have the feature shipped earlier?

**Comment by jhogberg** [comment]
New features should as a general rule go into `master`, but something as minor as this can sometimes sneak into `maint` -- OTP 27.2. :-)

I'll try to remember to backport it to `maint` next week.

**Comment by garazdawi** [comment]
`SIGWINCH` is used by the shell to listen for window resize events, so with this change the shell will no longer do that if `os:set_signal(winch, ...)` is called. IMO `prim_tty` should be updated to use os:set_signal/2 and registering a handler. @dumbbell would you mind taking a look?

**Comment by dumbbell** [comment]
No problem, I will look at `prim_tty`.

**Comment by dumbbell** [comment]
@garazdawi: I see that `prim_tty_nif.c` sets a handler for `SIGCONT` in addition to `SIGWINCH`. Should this signal be supported by Erlang/OTP as well and then both signals handled the same way for consistency’s sake?

Also, do you have an example use case to observe the behavior of the shell response to a window size change? Like, what is redrawn?

**Comment by garazdawi** [comment]
Yes, might as well include SIGCONT as well.

There are a bunch of testcases in kernel -> interactive_shell_SUITE that test it. The most thorough is probably [shell_update_window](https://github.com/erlang/otp/blob/master/lib/kernel/test/interactive_shell_SUITE.erl#L948). The test makes sure that the shell cursor is correctly displayed as the window is resized.

**Comment by dumbbell** [comment]
I submitted the first pull request to add `SIGCONT` support: #8938.

The patch to change `prim_tty` to use `os:set_signal/2` is ready as well, but it depends on `SIGCONT`. I will submit after the first pull request is accepted and merged.

**Pull request merged**
