### PR TITLE
Optimize filelib:wildcard/2 with double star patterns

### PR DESCRIPTION
**Pull request by josevalim**
The previous implementation would execute file:list_dir/2
twice for every file found in a double star (**) pattern.
This patch changes it so it only calls it once per file,
literally cutting the traversal time in half.

### CODE REVIEW

**Comment by bjorng** [comment]
I have pushed a fixup commit with the following changes:

* Following the convention in the rest of the file to end the incoming version of a variable with a zero (i.e. I change `Result` to `Result0`).

* Reindented  your code with Erlang mode in Emacs.

If you agree with my changes, please squash the commits and force push.

**Comment by josevalim** [comment]
@bjorng squashed and force pushed.

**Comment by bjorng** [comment]
@josevalim Thanks!

**Comment by michaelst** [comment]
It looks like this fix was included in 22.2.5, however, when I build the docker images with 22.2.5 there doesn't seem to be any change in the performance of this function. Is there possibly something I am missing in building the elixir container from Erlang:22.2.5?

**Comment by josevalim** [comment]
Hi @michaelst! Looking at the commits in the 22 branch, I don't see this particular change. Were you able to find it?

**Comment by michaelst** [comment]
Oh I read that wrong, it is showing up in the commits to master since that tag. Sorry about that.

**Pull request merged**
