### PR TITLE
Add math:fmod/2 BIF

### PR DESCRIPTION
**Pull request by g-andrade**
A recent erlang-questions [thread](http://erlang.org/pipermail/erlang-questions/2016-October/090690.html) made me realize this is actually quite simple, assuming there's no gotchas I'm not accounting for.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Looks good. Also no problems in our daily builds and tests.

There is only one minor thing remaining before we can merge it. To make it easy to see when a BIF was added, the new line in `bif.tab` should be in the section labeled "New in 20.0". You have added a entirely new section.

I have pushed a fixup commit to your branch. To fix your branch, fetch the commit. Then do like this to correct your commit:

     git rebase -i --autosquash HEAD~4

Then force push the branch to your github repository.

When you have done that, the branch is ready to be merged.

**Comment by lexmag** [comment]
I'm wondering, should it be called `frem` instead, since we have `rem` already?

**Comment by g-andrade** [comment]
@lexmag , that's a good point; on the other hand, I get the feeling that the 'math' module intends on cloning the standard C math interface and, if so, naming it frem would make it inconsistent, break expectations and possibly impact discoverability.

An alternative would be to expose it in the 'erlang' module as well - under the name 'frem' - but it could be controversial as some people think that the 'erlang' module is quite bloated already.

**Comment by lexmag** [comment]
@g-andrade ah, I see, didn't think about that relation with C. 👍

**Comment by lrascao** [comment]
@bjorng out of curiosity, how were you able to push a commit to @g-andrade's private branch? is this some sort of configuration flag in the OTP repo?

**Comment by lexmag** [comment]
@lrascao that's relatively new addition on GitHub: https://github.com/blog/2247-improving-collaboration-with-forks.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lrascao** [comment]
@lexmag nice, thanks

**Pull request merged**
