### PR TITLE
According to spec format can be io:format/0

### PR DESCRIPTION
**Pull request by hauleth**
Earlier it accepted only charlist which could be confusing for users that would expect it to accept the same types as `io:fwrite/2`.

### CODE REVIEW

**Comment by garazdawi** [comment]
Shouldn't it also allow binaries if the spec is to be followed? Also there needs to be tests for this.

**Comment by hauleth** [comment]
It checks for string as well, `IS_STRING` already does that.

**Comment by garazdawi** [comment]
> It checks for string as well, IS_STRING already does that.

Ah, yes. Missed that part.

**Comment by hauleth** [comment]
@garazdawi added tests.

**Pull request merged**
