### PR TITLE
Add support for utf8 atoms in enif_get_atom/enif_get_atom_length

### PR DESCRIPTION
**Pull request by define-null**
Hi this little PR adds support for utf8 atoms in enif_get_atom/enif_get_atom_length functions.

### CODE REVIEW

**Comment by sverker** [comment]
Nice initiative!
But to be released I think we want all functions receiving enum `ErlNifCharEncoding` to also accept the new `ERL_NIF_UTF8`.
```
enif_make_existing_atom
enif_make_existing_atom_len
enif_get_string
enif_make_string
enif_make_string_len
```

**Comment by define-null** [comment]
Can we consider them to be undocumented for now, or it's more or less either support for all or nothing ?)

**Comment by sverker** [comment]
I would prefer a full documented implementation released in a major release.

A reason for this comes from the fact that the existing functions do not reject invalid encoding values (apart from ASSERTS only executed in debug build). If someone builds against a new erl_nif.h with ERL_NIF_UTF8, but the NIF module is later loaded into an older VM without this support, strange behavior may arise due to wrong character encodings. To protect against this we can increase the interface version number which will prevent a new lib from being loaded into an old VM. But it doesn't feel right to impose such a limitation for an undocumented feature.

**Comment by rickard-green** [comment]
Please make a new PR when/if fully implemented

**Pull request closed without merging**
