### PR TITLE
Fixed typos across code comments

### PR DESCRIPTION
**Pull request by AndrewDryga**
Hello,

There are many typos in source code comments, I'm trying to clean it up (at least some of them). If this PR should be structured in another way - just tell.

### CODE REVIEW

**Comment by AndrewDryga** [comment]
This is only 30% of work done, but I think it's more than enough for a single PR.

**Comment by AndrewDryga** [comment]
This PR is bases on list of common typos taken from Wikipedia. I searched for them the source code and manually fixed typos, making sure I did not touch typos in code (only comments are affected).

Ready to be merged. 

Should I try to fix typos in variable names and error messages in next PR?

**Comment by garazdawi** [comment]
You have mixed multiple different fixes into your commits:

 * whitespace fixes
 * typos in release notes/documentation
 * typos in comments

Please separate each of these into different commits so that we can review them individually and decide whether to merge it or not.

Personally I'm against merging the whitespace fixes and the comment fixes as they don't bring much value, but does make it more likely to get merge conflicts when merging fixes in maint upstream to master. Fixing typos in variable names suffers from the same problem, but also adds the extra risk that it is actual source code that is changed.

I would be very interested in fixing typos found in error messages.

**Comment by AndrewDryga** [comment]
@garazdawi I can remove trailing spaces over all project, it's relatively easy with modern IDE's. So "spaces" commit will be aimed to remove this issue once and, hopefully, for all. Should I do that?

**Comment by garazdawi** [comment]
Focus on fixing spelling mistakes.

We've had discussions about doing project wide whitespace fixes before and I've yet to see any benefit of doing it. If we would like to fix all of the trailing whitespaces, we'll just write a small sed script that does it. As you say, it is not a difficult thing to do.

**Comment by garazdawi** [comment]
Closing this, please open a new PR if you want to continue to pursue these changes. As I said, we would be very interested in spelling misstakes in documentation and error messages.

**Pull request closed without merging**
