### PR TITLE
Prepare for 64-bit pids

### PR DESCRIPTION
**Pull request by sverker**
Today Erlang process identifiers are restricted to 32 bits (including 4 bits type info) even on 64-bit architectures.

This PR is the first step in an upgrade path toward 64-bit pids. The local node (OTP-24) will still only generate 32-bit pids but we accept 64-bit pids from other nodes.

### CODE REVIEW

**Comment by vans163** [comment]
This is nice but there are problems with spawning many pids, like allocation contention.  Often noticeable when taking an app on a  8core system to 64/128 cores, and not getting a horizontal speedup.

**Comment by okeuday** [comment]
@sverker The external term format doesn't need to change to support 64bit pids because `NEW_PID_EXT` already exists, right?

**Comment by sverker** [comment]
@vans163 Our main purpose for 64-bit pids is to practically eliminate the problem of pid reuse by wraparound.

**Comment by sverker** [comment]
@okeuday Yes, NEW_PID_EXT already contains space for 64 bits. The PR just accepts all bits to be used by removing checks for too large values (for external pids) and makes sure all 64 bits are stored.

**Comment by crownedgrouse** [comment]
Could a 64bit pid format include the flavor of a Pid? Io server or process etc...? This wait we could guard on pid input, while is_pid/1 still available.

**Pull request merged**
