### PR TITLE
Fix port communication with win32sysinfo.exe

### LINKED ISSUE #6156: os_mon_sysinfo:get_disk_info/1 does not work
**Describe the bug**

The following always crashes on my Windows 10 system:

```
application:ensure_all_started(os_mon).
os_mon_sysinfo:get_disk_info(["C:\\"]).
```

**To Reproduce**

Start `werl.exe`, then run the above two functions.

**Expected behavior**

Output similar to that for `os_mon_sysinfo:get_disk_info()`:

```
10> os_mon_sysinfo:get_disk_info().               
["C:\\ DRIVE_FIXED 720496750592 1013310287872 720496750592\n",
 "Y:\\ DRIVE_REMOTE 0 0 0\n","Z:\\ DRIVE_REMOTE 0 0 0\n"]
```

**Affected versions**

Tested with verson 25.0.2 on Windows 10 Pro Workstation.

**Additional context**
https://github.com/rabbitmq/rabbitmq-server/pull/4328
https://github.com/rabbitmq/rabbitmq-server/pull/5241

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #6156

Note: I have not yet been able to build from this branch on Windows to test this out.

### CODE REVIEW

**Comment by garazdawi** [comment]
> Note: I have not yet been able to build from this branch on Windows to test this out.

There is a [windows installer](https://nightly.link/erlang/otp/actions/artifacts/355917955.zip) built by github actions that you can use to test things if you have a Windows machine. I have a Windows 10 Virtual Box on my Linux that I do all my Windows work on and that works great.

**Comment by lukebakken** [comment]
Aha! Thank you for pointing that out. I'll try it today.

**Comment by lukebakken** [comment]
@garazdawi testing with the [latest installer](https://nightly.link/erlang/otp/actions/artifacts/357015985.zip) is successful.

```
Eshell V13.0.4 (press Ctrl+G to abort, type help(). for help)
1> application:ensure_all_started(os_mon).
{ok,[sasl,os_mon]}
2> os_mon_sysinfo:get_disk_info().
["C:\\ DRIVE_FIXED 587780251648 1013310287872 587780251648\n"]
3> os_mon_sysinfo:get_disk_info("C:\\").
["C:\\ DRIVE_FIXED 587780251648 1013310287872 587780251648\n"]
```

I tried to match the C code formatting as best I could.

**Comment by garazdawi** [comment]
The fix looks good to me and will merge as soon as it has gone through testing.

As I said in #6156 the module you are calling is undocumented and untested, so if you want this to continue working in the future I would suggest extending this PR (or create a new one) with documentation and test cases for this API.

**Comment by lukebakken** [comment]
> The fix looks good to me and will merge as soon as it has gone through testing.

Great let me know if you'd like me to do additional testing.

> As I said in https://github.com/erlang/otp/issues/6156 the module you are calling is undocumented and untested, so if you want this to continue working in the future I would suggest extending this PR

> As I said in https://github.com/erlang/otp/issues/6156 the module you are calling is undocumented and untested, so if you want this to continue working in the future I would suggest extending this PR (or create a new one) with documentation and test cases for this API.

Great, I think I'll open a new PR for making `get_disk_info/[0,1]` "official" once I get work done on #6283 (since that's the ideal solution).

**Comment by KennethL** [comment]
I think the official public API should be in the module `disksup`. 
The module `os_mon_sysinfo` should remain private to the os_mon application.

**Comment by lukebakken** [comment]
> I think the official public API should be in the module disksup.

Yep, that's what @garazdawi suggested 👍

**Comment by lukebakken** [comment]
Thanks everyone 😄

**Pull request merged**
