### PR TITLE
Dialyzer: Warning suppression for non-Erlang BEAM languages

### PR DESCRIPTION
**Pull request by margnus1**
This PR adds warning suppression to compiler-generated case statements.
Warnings about clauses that cannot match and are also compiler generated
are suppressed unless none of the clauses return.

This feature is useful for non-Erlang BEAM languages (such as Elixir)
that compile to Erlang and expand certain language constructs into case
statements. In that case, as long as the language construct can succeed,
these warnings are undesired and appear spurious to users that do not
check the Erlang code that their program expands into.

This feature is needed for Elixir to be able to generate efficient code without causing Dialyzer to generate warnings on type-correct programs as of OTP 19, due to improvements to Dialyzer.

Thanks to José Valim for the test (slightly modified).

This PR addresses [ERL-159](http://bugs.erlang.org/browse/ERL-159). See also PR #1086, which was an earlier attempt at this feature.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by aaronjensen** [comment]
I'm new to OTP release processes... when would this get released? It doesn't look like it has shown up in patch releases, will it show up in the next minor?

**Comment by garazdawi** [comment]
@aaronjensen yes, it will be released in the next minor release.

**Comment by KronicDeth** [comment]
Built the merge commit (784f845) using kerl (`kerl build git https://github.com/erlang/otp.git 784f845e2d1ec66b9505339b4b0e43d55c2d49a9 PR1121), using that version of Erlang and Elixir 1.3.2, I still [get > 120 warnings](https://gist.github.com/KronicDeth/f99dc00285dac133dfc082451017db63), most of them about generated code from Phoenix and Ecto.  Those warnings aren't there under Erlang 18.3+Elixir 1.3.2.  Was this PR meant to fix those types of warnings or only enable Elixir 1.4+ to mark the clauses as compiler generated, so I should wait for Elixir 1.4+ with Erlang 19.1 to get those new warnings suppressed?

**Comment by margnus1** [comment]
You're right in that cooperation from the compiler is required to use the warning suppression. IIrc, only one of the affected language constructs are marked by Elixir 1.3.1 in this way (the one covered by https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/fixtures/dialyzer/remote_call.ex, which should now be free of spurious warnings even without the supression attributes at the start. Note that the first function `map_var()` *should* receive warnings, as it always crashes at runtime.) I can have a look at Phoenix and Ecto if you think some of the warnings should have been supressed, but some of those warnings are clearly not spurious. Probably, there are bad type specs somewhere in there.

**Pull request merged**
