### PR TITLE
[erl_syntax]: Fix some type declarations

### PR DESCRIPTION
**Pull request by kostis**

### CODE REVIEW

**Comment by uabboli** [comment]
Hi Kostis,

Something needs to changed in the documentation as well. If you look
at erl_syntax(3), you'll notice that, for example,
erl_parse:af_generator() links to the top of erl_parse(3), that is,
the datatype does not exist.

Adding the datatypes like this example (in erl_parse.xml):

    <datatype>
      <name name="af_generator"></name>
    </datatype>

might not the best thing to do as it introduces links to other
datatypes: anno() can be replaced by erl_anno:anno(), but af_pattern()
as well as af_binelement_size() and type_specifier_list() need to be
added, introducing more links to the types of erl_parse.

An alternative is to add this (to erl_parse.xml):

    <datatype>
      <name><marker id="type-af_binelement"/>af_binelement(_)</name>
      <desc>
        <p>Abstract representation of an element of a bit string.</p>
      </desc>
    </datatype>
    <datatype>
      <name><marker id="type-af_generator"/>af_generator()</name>
      <desc>
        <p>Abstract representation of a generator
          or a bit string generator</p>
      </desc>
    </datatype>
    <datatype>
      <name><marker id="type-af_remote_function"/>af_remote_function()></name>
      <desc>
        <p>Abstract representation of a remote function call.</p>
      </desc>
    </datatype>

The downside is that it may be confusing for the reader of
erl_parse(3)--why these types, and not the other ones?

BR, Hasse

**Comment by kostis** [comment]
Thanks for the comment and for checking what happens with the documentation.

I think I prefer the second alternative -- and I can add it to the PR if we agree on this. IMO, the "philosophical" question why these types are exported (and documented) and not others is already answered by a relevant comment in the code of `erl_parse`. If other applications / users would like more types to be exported they can describe their use case and submit the relevant PR.  A decision about that problem can then be made.

**Comment by uabboli** [comment]
I agree. If you add the second alternative to the PR, I'll merge it. Thanks.

**Comment by kostis** [comment]
Added.

**Comment by uabboli** [comment]
I've fixed my mistake locally. You don't have to do anything.

**Comment by uabboli** [comment]
Merged commit 7788362a80a86b34d2228b201b3199b186f2d66a to erlang:master.

**Pull request closed without merging**
