### PR TITLE
gen statem improvements OTP-13929 - dirty_timeout, state_enter, and state_timeout

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
This pull request is about two things that surfaced during discussions with @ferd at the recent EUC:
* The default proxy process for `gen_statem:call(Server, Request, Timeout)` with an integer `Timeout`
* How to implement state entry code

#### The Proxy Process
When `gen_*:call/*` times out it throws an `exit` exception which is ment to kill the client, so therefore it can not get a late reply since it is dead.  Historically code has been written to catch this exception for various reasons, and if you do that you may get this late reply, and since `gen_server:call/2` uses a default timeout of 5000 ms you may use a timeout value by accident.

This anomality has bitten some of our users, so I wrote `gen_statem` to use a proxy process for the call which avoids a late reply since it will arrive at the now dead proxy process.

But this hits performance for the original valid use case of having a timeout and not catching exceptions from the call.

So in the first commit of this pull request there I have added `{safe_timeout,T}`, `{dirty_timeout,T}` and `{timeout,T}` as possible timeout specifiers in addition to the previous just `T :: timeout()`.

Now remains the question of naming; is `proxy_timeout` a better name than `safe_timeout`, is `unsafe_timeout` a better name than `dirty_timeout`?

And also the question of default; now is `safe_timeout` the default so `T` means `{safe_timeout,T}`.  But is this the right default?

#### State Entry Code
I have finally a workable suggestion of how to implement state entry code.  I extended the set of return values from `Module:callback_mode()` to allow for a list of `callback_mode() | state_entry_events`, and if you return a list containing `state_entry_events` you will get an event of type `enter` with content `OldState` whenever your state machine changes states.

This makes state entry events optional to use, and is handled as a code property just like the callback mode.

The question is then, is the return type `[callback_mode()|state_entry_events]' the right choice? 

You might think of this as a minor mode of the callback mode where both callback modes today supports the same minor mode, and then something like '{callback_mode(),MinorMode}' or '{callback_mode(),[ModeFlag]}' would be more natural.

But I think this new mode is orthogonal to the callback mode.  It activates an automatic event generation and that is totally unrelated to the callback mode, so therefore `Module:callback_mode()` should return a list of modes were `state_functions` or `handle_event_function` is mandatory but `state_entry_events` is optional.

However, since this new code property is orthogonal, should it be a new callback e.g `Module:state_entry_events() -> boolean()`?  I think that would be an unnecessary callback...

So, comments, please!

[Reference Manual](http://erlang.org/~raimo/doc-8.0.3/lib/stdlib-3.1/doc/html/gen_statem.html)
[User's Guide](http://erlang.org/~raimo/doc-8.0.3/doc/design_principles/statem.html)

### CODE REVIEW

**Comment by RaimoNiskanen** [comment]
We are waiting for the release before we can use the maint branch again...

**Comment by ferd** [comment]
Hooray!

As for naming, I'd think `{clean_timeout, T}` and `{dirty_timeout, T}` would be good enough (safe and unsafe has little to do with it, since `dirty_timeout` is safe as long as you die).

Just the `T` timeout could proxy to `{clean_timeout, T}`: let's be clean by default. The current best use case for `gen_statem` is SSL code, and I can't imagine it would be a great idea to trade off the safety in there of a clean timeout implementation for a performance one. It does mean a break with what happens in other `gen_*` module, but it's a cleaner design and may be worth working a switch for. 

If we favor uniformity, then we could double-down on current design and have `T` be synonymous with `{dirty_timeout, T}`, which would require SSL code to always specify clean timeouts; more prone to errors and issues, I think.

 I see no reason to have `{timeout, T}` be another default for proxying there, unless this option has an equivalent in other gen_* modules and could be fine with having it taken out entirely. I don't remember seeing that option before though.

I'll voice an opinion on state entry events in another comment, since I'll need more time to digest that one.

**Comment by RaimoNiskanen** [comment]
@ferd wrote:
> As for naming, I'd think {clean_timeout, T} and {dirty_timeout, T} would be good enough (safe and unsafe has little to do with it, since dirty_timeout is safe as long as you die).

I like those names.

> I see no reason to have {timeout, T} be another default for proxying there, unless this option has an equivalent in other gen_* modules and could be fine with having it taken out entirely. I don't remember seeing that option before though.

That is right - it is a new one.  I just placed it there as an alias for T to get the default behaviour in tuple form.  So if we would add {timeout,T} to gen_server it would mean {dirty_timeout,T} just as T does today.

It is as you say redundant due to the old non-tuple form, I just liked the symmetry.  Perhaps if the timeout type would be a configuration parameter for some application that since that only wants to use the tuple form... Maybe...

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
I have given `{timeout,T}` a second thought, and you are right!  We should not transfer the old semantics of different behaviour in different `gen_*` behaviours into a new option form.  It is better to force a conscious decision on the user... I will drop the `{timeout,T}` form.

**Comment by RaimoNiskanen** [comment]
I have updated the branch to use `{clean_timeout,T}`, removed `{timeout,T}` and polished the documentation a bit.

The new documentation should be visible within the hour.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by ferd** [comment]
So the `state_entry_event` mechanism is decent, but I think risks being a bit confusing regarding enqueuing and so on.

What happens if, for example, I `postpone` the event? Can I send it to myself via `next_event` ? They're having interesting semantics all of a sudden there, since they muddy the water of 'selective receives'.

I also think that this:

> Note that a state entry event will be inserted when entering the initial state even though this formally is not a state change. In this case OldState will be the same as State, which can not happen for an actual state change. 

Should probably seen as a warning about the semantics we're looking at. I guess my question is what should we expect from enter events?

There's many options, right:

- side-effecting code that does not modify the stored state
- additional state modifications
- a mixture of both
- change the flow of the state machine and state of the mailbox

The interesting bit for me here is that what we really care about is possibly not *entering a state*, but rather *a state transition*, which happens to be something we want to handle closer to code either when leaving or when entering a given state.

A proper way to think of it for me, would therefore be to work with:

`on_transition(FromState, ToState, Data) -> NewData`

This form of hook would mean that it allows:

- side-effecting code that does not modify the stored state
- additional state modifications
- a mixture of both

Missing from this list is 'changing the flow of the state machine and state of the mailbox' -- you cannot re-enqueue events, you do not have to worry about unclear semantics, and you restrict the power of the feature -- which may actually be fine, but I'm not sure what your requirements are there.

The big gotcha of this format is that it looks sane for the `handle_event_function` callback mode, but really jankier for `state_functions`. 

The question then is whether you should consider enter events to:

1. need to generate new callbacks (`FromState_to_ToState(...)`) which I think sounds bad, is conflict-prone, and requires generating a bunch of dynamic atoms, which I'm not comfortable with;
2. specify a `{State, TransitionTo/3}` tuple in `Module:callback_mode()`'s return value instead of a generic `state_entry_event`, which is definitely verbose and less friendly
3. can specify enter events as `{enter, FromState}`, which are forbidden from being accepted by the `next_state` function or `postpone` operation.
4. Should instead decide to reopen the semantics of how we want selective receives to work to account for the weird stuff re-queued enter events may create.

I don't know, that's what I have in mind for now. I'm personally thinking 3 is the least annoying one -- it's probably easier to think of these events as not re-enqueueable than making the selective receive semantics more complex.

**Comment by RaimoNiskanen** [comment]
@ferd: Can you elaborate on what your alternative 3 `{enter, FromSate}` means; I did not quite get it.

I think as you said that a separate `handle_transition(FromState, ToState, Data)` function might work for `handle_event_function`, but even there it forces handling of the state transition in code maybe far from the other state code.  And it would kill `state_functions`.

I thought of having `StateName(FromState, Data)` i.e arity 2 functions for handling state entries (and `handle_event(State, FromState, Data)` for `handle_event_function`),  but decided that it would be a shame to take so much of the arity 2 namespace.  But maybe not...?

On the topic of state entries vs. state transitions a state transition kind of has 3 or at least 2 parts. First when the exiting state decides to return `{next_state, NewState, Data}`, (second when the `gen_statem` engine updates its state,) and third when the new state is called because of some event in the new state.  You can write a state transit function yourself that runs the state transit code and then returns `{next_state, NewState, Data}`, but what I want is a guarantee from the `gen_statem` engine that the code for the new state will be informed that it has been entered so the state entry code can be written right there by the other event handling code, and from this code's perspective it is the entry that is interesting - the exit may have done different things from different `OldState`s.  Therefore I think the name *state entry* is relevant for this feature.  We already have the exit part, and a transition consists of the combination of one exit and one entry.

I first implemented these events to only be generated at state transitions i.e not on the first state, but though it was impractical.  I think the feature is more useful if also the initial state can have the same code executed however it is entered since I noticed that I wanted to use `{next_event,enter,undefined}` to fake it from `init/1`, which answers one of your questions: I have no special treatment on the event type `enter`; it can be inserted with `next_event`.

I also have no special treatment for `postpone`, so you can if you like messy stuff postpone an `enter` event.  The event handling has not changed except from these `enter, OldState` events being automatically inserted.  So if you postpone an `enter` event it will be retried in a subsequent state.

A state function gets:
1. If the state changed: `enter,OldState`
2. `next_event` events from the previous callback invocation
3. If the state changed: previously postponed events, in order of postponing
4. Yet unseen events

It is only 1. that has been added.

I do not know if preventing `enter` events from being `postpone`d and `next_event`ed would be a good safety measure.  It would need special treatment in the `gen_statem` code, which in general is a warning sign.

**Comment by RaimoNiskanen** [comment]
As always, things clear up a bit in my head *after* I have posted...

There are (at least) two paths to walk for this state entry code feature:
1. As events - state entry full fledged events
2. Not events - or restricted ditto

I have so far in this pull request explored 1. to avoid special handling of any events.

For 2. two possible alternatives showed up in the discussion above. Either:
a. `StateName/2` + `handle_event/3` functions
b. restricted events that can not be inserted.

There may exist more.

There is nothing that says that state entry code need to be handled as actual events.  We simply want code to be called at state entry, and that could the `gen_statem` engine do outside its normal event handling.

Against 2a. speaks that for `handle_event_functions` all state entry code will be collected in the arity 3 function while the state implementation is in the arity 4 function, so they may be far from each other.  Also against is that we for `state_functions` would interfere with the arity 2 namespace in addition to currently the arity 3 namespace.

Against 2b. speaks that an `enter,OldState` really looks like an event but is not since it can not be inserted (nor postponed), which is a bit asymmetric.  Not being able to insert such an event can also be limiting in that you can not re-enter the current state, which might be a nice-to-have or essential feature.  You would have to enter some `internal` event with the same effect and get code duplication.

Against 1. speaks the complexity of describing how the queueing of `enter,OldState` works and the increased possibilities to shoot yourself in the feet.

**Comment by ferd** [comment]
I'd say that's about right, yeah. That would be the fun spot we're in.

**Comment by asabil** [comment]
Is dropping support for the `state_functions` callback mode an option? If we were to do that, then the problem could be solved by having `handle_event/4` and `handle_transition/3`.

I have been using `gen_statem` quite a bit since it has been released in 19.0, my experience is that every time I have started by using the `state_functions` callback mode, I always ended up reverting to the `handle_event` mode.

**Comment by okeuday** [comment]
@asabil The main problem with state machines is managing their complexity as they grow and `state_functions` helps to organize the state machine more than the `handle_event_function` approach, while the `handle_event_function` may allow hierarchical state machines to work well.  It is best to keep both modes.

@RaimoNiskanen I do not think a `handle_transition(FromState, ToState, Data)` would kill `state_functions` in any way, it just needs to be made clear that the callback would be for **state entry only**.  I like the usage of `state_entry_events` in the `callback_mode/0` return value to keep this feature orthogonal to the storage of state logic, as an extra (optional) feature to only use if you really need it (since it is functionality that is leading back into problems that exist in `gen_fsm` where state logic gets scattered in different callbacks, though minimal use of this feature is better than not having it).  It is better to just use the `callback_mode/0` function for this optional atom to keep things simpler (you only need to look in one place to understand how the module was implemented).

It should be best if you use a restricted event, and avoid the association to the pre-existing event concept to avoid confusion, i.e., a `transition` might be clearer and would internally be implemented as a restricted event (something that can never be postponed/inserted, etc., as mentioned in 2b at https://github.com/erlang/otp/pull/1170#issuecomment-248274771) that shouldn't even look like an event due to depending on an optional callback.  So, `state_entry_events` might want to change to be `state_transitions`.

**Comment by RaimoNiskanen** [comment]
@asabil, I agree with @okeuday in that the `state_functions` mode is valuable and can not be dropped.  And so is `handle_event_function`.  I myself so far has almost exclusively used `state_functions`.

@okeuday: Thank you for your input on how to activate this feature i.e from`Module:callback_mode/0` with a list of atoms.  At least one agrees then, and nobody is so far against.

I think a `handle_transition(FromState, ToState, Data)` function would be bad for `state_functions` since the state entry code may wind up pages away from the rest of the state code, which is exactly what I aimed to avoid with `gen_statem`, so 'kill' may be a strong; 'devastating' may be better.  And I think it is almost as bad for `handle_event_function` for the same reason.

I also think that of the available actions you may want to do from state entry code `hibernate`, `{timeout,,}` and `{reply,,}` may be essential, `{next_event,,}` useful or not needed I do not know, but `postpone` is straight up silly and dangerous.

Therefore it is rather tempting to re-use the normal state function machinery for state entry code, and a special event type fits fairly well.  It is possible to disallow it from `postpone` and `{next_event,,}`.  Would that be sufficient?  What would the error behaviour be - ignore or fail?

The name, I think, should indicate 'state' and 'entry' since it is about the entry part of a state transition.  `state_entries`?

What about the `StateName(OldState, Data)` + `handle_event(OldState, State, Data)` suggestion?  I still think it is unfortunate for `handle_event_function` since it separates the state entry code from the rest of the event code, but for `state_functions` you can write the state entry function right above the state function.

**Comment by asabil** [comment]
@RaimoNiskanen, @okeuday the reason for suggesting dropping `state_functions` is simply because it is something that can be easily, as in 1 line of code, implemented on the `gen_statem` user side: `handle_event(Type, Content, State, Data) -> ?MODULE:State(Type, Content, Data).`

I think that the proposed approach conflates transitions and events, if entering a new state is considered an event, what about leaving that state, shouldn't that be an event as well? entering a state is the dual to leaving another state for that particular transition at time T.

In the current implementation of `gen_statem` an event has certain semantics: it can be ignored, processed or postponed. If `enter/leave` where to be events, then I should be able to ignore, process or postpone them, otherwise they are not events, but something else. I don't think postponing `enter/leave` makes much sense.

What I am suggesting is to simplify as much as possible, make `gen_statem` almost as easy to use as `gen_server`: `init`, `handle_event`, `handle_transition`, `terminate`, `code_change`. This will make it very easy to learn, explain, document, test... no modes, or flags or changing behaviour based on which options are passed.

If you are really set on handling transitions as events, maybe you could consider changing `callback_mode` to `flags` or `options`, and make it return a proplist? or maybe go back to what we had before `callback_mode` was introduced returning the proplist directly from `init`?

**Comment by RaimoNiskanen** [comment]
@asabil: Well I created `gen_statem` to be a usable alternative to `gen_fsm`, especially for `StateName()` functions, which maps very well to state machine diagrams with named states.  That was and is still my primary goal.

I agree that the proposed approach of auto inserting a special event type during a state transition blurs the line between transitions and events. The goal is to be able to write code that is executed when a state is entered right besides the other state implementation code.  The proposal as it is today allows you to ignore, process, postpone and insert these auto inserted events, so in that respect it is a rather clean concept.  These events are auto generated by state transition, that is all.

And I can not think of any case where `postpone` of an `enter,OldState` event makes any sense.  But one maybe could get away with "If it hurts, don't do that!".

Regarding returning a proplist from `init/1` for setting callback mode; that approach failed during code upgrades and downgrades, and `Module:callback_mode/0` is the solution for that problem.

**Comment by ferd** [comment]
I personally do not mind the form `handle_transition(OldState, State, Data) -> Return` for the `handle_event_function` approach (and their equivalent for named state approach); I'm quite okay with a callback for general event handling and a callback for state transition triggers. 

The idea of a distinct callback mode for state transitions for me is clearer than a special kind of event -- I can now put them in separate mental boxes rather than considering one of them to be an exception.

It's true that we would be jumping around a bit in files, but technically we already do that by splitting up the interface (where `gen_statem:call` and others) are declared. 

Of course even picking that form leaves open the question of what is the acceptable return type: can `handle_transition/3` or `StateName/2` return only `{ok, NewData}`, or are they allowed to return the subset of `{stop, ...}` and `{next_state, ...}` with similar restrictions? If they're allowed a subset,  which subset? 

The case where we only allow changing the internal state, IMO, makes for a good mental split of purpose: one case handles the state events, the other one handles the transition [and the API calls are elsewhere too], but cannot impact the FSM progression otherwise. It is purposefully less powerful than state transitions and acts as a trigger.

On the other hand, there could be interesting uses to the more flexible return values. It's just that allowing the more flexible uses makes the difference between both modes more minimal. I guess the interesting bit is that the types returned from a distinct callback could be made smaller and easier to check with dialyzer than a full runtime check of the return values ("no, you cannot postpone this type of event here", whereas the postpone and next_event values just make no sense to return in a distinct callback).

Maybe thinking of it in terms of types makes for a useful discriminator here.

**Comment by okeuday** [comment]
@RaimoNiskanen @ferd After thinking about this more, I agree that it is more important to group the state handling logic together with a restricted event concept than to add a new callback since gen_statem is meant to really make sure and keep state logic grouped so it is easy to understand, even if the state machine has lots of complexity, so that it provides a very clear benefit when compared to gen_fsm.  It seems important to try and list the reasons for either approach, to see if something is missing and make sure the restricted event approach is best.

restricted event added for state entry:
- Keeps state logic grouped together, which is **very important** for managing complexity in the source code
- Misuse of a restricted event should cause a failure, due to it being a development mistake, rather than silently ignoring the problem (so there isn't extra noise in the source code that is misleading)
- Does make the use of a state entry concept a bit more complex in the documentation, since it lacks clear separation, but ideally it could be described as a "state entry" without using the word "event" to provide some clear separation that supports its separate semantics
- The runtime checking of the restricted event can't be expressed with type checking in this approach

handle_transition/3 callback added for state entry:
- Easier to understand but keeps state logic separate from state event handling, making complex state machines more difficult to understand and maintain, so this approach unfortunately makes gen_statem less effective
- As @ferd mentioned, this approach has better control over the return types that would be allowed, which is a nice feature for both type checking and encapsulation of functionality (with this approach, it is important to make sure the function can't cause a state transition, to prevent misuse)

That is my view of the situation based on the comments above, with a restricted event approach being best.

**Comment by RaimoNiskanen** [comment]
@okeuday: I agree completely.

I will rewrite this pull request and then present the state entry calls not as events, but as special calls, so there will not be an event type 'enter'.

I hope it will be possible to express this in the type system, something like:
```
-callback state_name(enter, OldState::state_name(), data()) -> enter_function_result();
                                  (event_type(), EventContent::term(), data()) -> state_function_result().
```

**Comment by IngelaAndin** [comment]
I think it is important to try to exemplify the use case.  As Raimo has explained it to me it is
common in FSM specifying logic to have the possibility of "entry actions/events".  As I understand it this will be something that happens every time I enter a state regardless of how I ended up there and regardless of any other conditions.  So in my particular use case (SSL/TLS) this is not useful, as my state functions have several clauses but no common code in the beginning that should always happen when entering that state. But if you have such code it could be useful to have the machinery guarantee that it will be called on every state entry. As I see it we do not want to clutter the code for use cases that do not need this, and we like to have a solution that works for both state functions and the handle_event approach and feels intuitive. So far, a "special event" seems to be the solution that is most promising. But I still think we lack the simple explanation or naming that makes it become clear.  And also question marks on how it is to be treated. I do not think it should be postponable, it makes no sense. I also think it is questionable that you should be able to change state when handling it, even if I heard the argument that you should be able to change to an error state.

**Comment by IngelaAndin** [comment]
@RaimoNiskanen Your comment did not exist when I started writing mine. Nice that you have new good ideas already. I wanted to put out some points from our internal discussion to enable  others to take part of the ongoing way forward.

**Comment by RaimoNiskanen** [comment]
@ferd, @okeuday, @asabil, @IngelaAndin:

I have pushed a new suggestion that changes the "state entry events" into "state enter calls", which besides a changed name also changes the semantics according to the suggestions in this discussion, as I interpreted them.

Please review!  I think it is a better suggestion than my original, with fewer rough edges.

I have updated the documentation snapshot:
[Reference Manual](http://erlang.org/~raimo/doc-8.0.3/lib/stdlib-3.1/doc/html/gen_statem.html)
[User's Guide](http://erlang.org/~raimo/doc-8.0.3/doc/design_principles/statem.html)

**Comment by ferd** [comment]
- In the user guide might be useful to link the state entry actions section from the state enter calls section (4.3 -> 4.15)
- +1 on the split types in the documentation and checks. It would be nice if dialyzer were strong enough to trigger on a bad return to help it all (haven't tried it)

I'm okay with the shape this has taken.

**Comment by okeuday** [comment]
@RaimoNiskanen Everything looks good, except for one small type issue at https://github.com/RaimoNiskanen/otp/blob/04d40c5cd18aca449606c19608e8044f593ee99e/lib/stdlib/src/gen_statem.erl#L191-L196 : shouldn't `ActionType` be a type (isn't it currently considered `any()`?).

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
@ferd: Good suggestion - I will insert a link.  I am also hoping that Dialyzer will be able to do its thing with these types.

@okeuday: Good catch!  I will fix it.

I am also working on additional commit(s) for state timeouts triggered by a post on erlang-questions.

**Comment by RaimoNiskanen** [comment]
@ferd, @okeuday: I have updated according to your suggestions.

#### State Timeouts
I have also added a commit introducing State Timeouts which I really think is more useful than the current timeouts inherited from `gen_fsm` that are Event Timeouts.  Have a look!

I have updated the documentation snapshot:
[Reference Manual](http://erlang.org/~raimo/doc-8.0.3/lib/stdlib-3.1/doc/html/gen_statem.html)
[User's Guide](http://erlang.org/~raimo/doc-8.0.3/doc/design_principles/statem.html)

**Comment by ferd** [comment]
Hm, the state_timeout option is interesting. I guess it has some limitations if you try to represent complex states (the transition is not the same) but you can fallback to regular timeouts then. It sounds generic and well-adjusted to use cases of FSMs, and rolling it by hand is cumbersome enough to be worth consideration in a more generic pattern in there.

---

About the doc, section 4.7 mentions event timeouts (or just `timeouts`) with the sentence "The time-out occurs when the door has been in state open for 10 seconds." -- this makes it hard to get the difference at a glance with a state time out. On the other hand, in 4.13, state time outs mention: "Suppose that we do not want a button to lock the door, instead we want to ignore button events in the open state. "

Those sound like bad examples for these. Event timeouts in 4.7 should be about inactivity (if nobody has locked the door or tried to use it in 10 minutes, it self-locks!), whereas those in 4.13 should be about a maximal state duration ("a user cannot remain authenticated for more than 30 minutes no matter what they do and we transition them back to logged out").

Also the doc introduces 'normal timeouts' in 4.14. Event types are introduced in 4.12. I think there needs to be a reordering there so that:

- normal (generic) timeouts are first
- you then show the event timeouts (historically, they've been there a lot)
- you then show the state timeouts
- you then use the event types from 4.12 (since they mention "The previous sections mentioned a few event types. [...] The following is a complete list of event types and where they come from" so they can be used as a summary)

----

The other thing I'd wonder about is whether regular timeouts should be renamed flatly to `event_timeouts`. I guess it would make sense to distinguish values, but would clash so much with existing Erlang/OTP history that it's better to keep it as is (as is currently the case in the implementation)

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
Regarding `state_timeout` the only snag I see is that I think a "bump" feature will be wanted; but what shall it be named? `{state_timeout,{add|bump,Time}, Msg}`, `{state_timeout,-Time,Msg}`, or... And are there more unforeseen operations we should think of.  Should we think generalizing it to `{state_timeout,fun(TimerRef) -> ok}`...

-------

Regarding the doc (statem.xml) I, again, tried to get away easily, which always gets back at you.  Having bad examples always misses its pedagogical purpose.  The 'fsm' documentation used its timeout for exactly this purpose (to lock the door after a certain time) and went around the problem that its timeout is not a state timeout by not expecting any events in that state.  And I took the same example.

So I will rework the doc.  Use good examples, not bad examples. I will talk about event timeouts or state timeouts and just state that they are called `{timeout,...}` and `{state_timeout,...}`.  I will not talk about "normal" timeouts, nor "regular" timeouts.  Instead about erlang timers / `erlang:start_timer/3,4` where that is what I mean.

But I think I want to explain the event types first.  Perhaps move Event Types and Actions to early between State Enter Calls and Example since that part of the user guide is centered around concepts.  Then explain event timeouts as an inactivity timeout for the user not pressing buttons right along state timeouts for locking the door after a certain time.  And finally how to use erlang timers for generic timeouts.

-------

Regarding the name `timeout` I think the event timeout had better keep the `timeout` tag, for historical reasons and to be more similar to `gen_fsm`, but we should always talk about "event timeout" in the documentation.

**Comment by ferd** [comment]
Regarding the add/bump, since cancelling the timeout is done by setting it to `infinity`, it sounds reasonable to me to assume that just setting a value again cancels the old one and adds a new value to it. You do get the same race condition that you can see with most other timers (it timed out while you were in the state itself) though, and that one remains tricky to resolve. That problem currently exists with the `infinity` reset anyway.

I'd also be careful about names like `add` and `bump` which make it sound like you can just *add* to the current timeout value (so a 1 minute timeout with 3892 ms left, bumped by 1000 ms would now have 4892 ms left! Don't think that is easy to do?)

The reordering of doc makes sense to me. Also agreed on the naming for historical reasons.

**Comment by RaimoNiskanen** [comment]
Setting a timer to a new value now cancels the old timer and starts a new with the this time requested time from now, that is restarts the timer, and ensures you do not get a timeout message, should the timer have timed out.  And that is also what the time `infinity` does.

And 'bump' or 'add' I want(ed) to be *exactly* as you describe.  When you cancel a timer you get how much is left of it so you can add that value to the requested time.  It is not that that hard to do.  But come to think of it - why on earth would anyone want that.  What was I thinking?

It is a simple restart you want even when you talk about bumping a timer.  'add' is a bogus operation. 'bump' means restart. And we already have restart.  Thank you for making me see that clearly!

**Comment by vans163** [comment]
@RaimoNiskanen I replied to mail list with {state_timeout,incr|decr|set,Time, Msg} (set atom implies 3 size original tuple).  But {state_timeout,{add|bump,Time}, Msg} is better to keep the tuple the same size.

**Comment by RaimoNiskanen** [comment]
@vans163: I just argued against erlang-questions `incr|decr|set` on erlang-questions with the motivation that what most want is restarting the timer, and that is already possible.

**Comment by RaimoNiskanen** [comment]
@ferd, New update of documentation, types and the emacs mode.

Here is a new documentation snapshot:
[Reference Manual](http://erlang.org/~raimo/doc-8.0.3/lib/stdlib-3.1/doc/html/gen_statem.html)
[User's Guide](http://erlang.org/~raimo/doc-8.0.3/doc/design_principles/statem.html)

**Comment by vans163** [comment]
Could there be a race condition here?

```erlang
cancel_timer(undefined) ->
    ok;
cancel_timer(TRef) ->
    case erlang:cancel_timer(TRef) of
	TimeLeft when is_integer(TimeLeft) ->
	    ok;
	false ->
	    receive
		{timeout,TRef,_} ->
		    ok
	    after 0 ->
		    ok
	    end
    end.
```

What happens if we call cancel_timer at the exact same time it expires but BEFORE the message hits the mailbox, that after 0 is what worries me. It should crash after 0 since that should NEVER happen.  I am not aware if Erlang runtime guarantees a message to be delivered to mailbox before returning false from cancel_timer.

Also is TimeLeft when is_integer(TimeLeft) necessary? Since this cancel_timer will be called a lot, an optimization may be to put the false case first, and _ second.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
@vans163: Good catch!

I had to re-read the documentation of `erlang:cancel_timer/1,2` thoroughly, and you are right!  Here is hopefully correct code.  And you have to know that you do not double cancel a timer!

The `is_integer(TimeLeft)` guard would only be interesting for `{info,false}` or `{async,true}` to `erlang:cancel_timer/2`, which is not the case here. 

```
cancel_timer(undefined) ->
    ok;
cancel_timer(TRef) ->
    case erlang:cancel_timer(TRef) of
	false ->
	    %% We have to assume that TRef is the ref of a running timer
	    %% and if so the timer has expired
	    %% hence we must wait for the timeout message
	    receive
		{timeout,TRef,_} ->
		    ok
	    end;
	_TimeLeft ->
	    ok
    end.
```

**Pull request merged**
