### PR TITLE
Fix webtool by removing reference to mod_include

### PR DESCRIPTION
**Pull request by waisbrot**
Symptom:

In 18.x:

```
    1> webtool:start().
    {error,
        {shutdown,
            {failed_to_start_child,
                {httpd_instance_sup,{127,0,0,1},8888,default},
                {shutdown,
                    {failed_to_start_child,
                        {httpd_manager,{127,0,0,1},8888,default},
                        {error,
                            {invalid_option,
                                {module_does_not_exist,mod_include}}}}}}}}

    =ERROR REPORT==== 7-Mar-2016::15:47:36 ===
    Failed initiating web server: 
    undefined
    {invalid_option,{module_does_not_exist,mod_include}}
```

This is true; `mod_include` was deleted as part of a [removal of server-side includes](https://github.com/erlang/otp/commit/b314eeff3dd14f046a18305ccd68371108936244#diff-36f64405bcdc2334a1dec1015c2c1069). However there are still a number of references to `mod_include`, such as in the start-up code of webtool.

Deleting the single line from `webtool.erl` allows it to run for me. I've also done a find-and-delete of `mod_include` elsewhere in the code, primarily hitting tests and example files.

There's still mention of mod_include in `lib/dialyzer/test/r9c_SUITE_data/results/inets` and `lib/runtime_tools/test/system_information_SUITE_data/information_test_report.dat` which are maybe outputs of prior test runs?

### CODE REVIEW

**Comment by psyeugenic** [comment]
I've got a couple of comments here. Webtool will be removed in 19.0 and it's already removed in master.

You should typically *not* alter such testcases since they test regressions for older releases. Parsing information generated by older releases. In this case I think dialyzer just wanted some thing to test against and system_information does indeed test parsing old information.

Other than that I think references to `mod_include` should definitely be removed.
I'm sure @IngelaAndin will have some comments later on regarding inets.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
The removal of references in inets should be done. They are mainly there because of legacy reasons and we have not had enough time to clean it all up. For instance old_httpd_SUITE is on its way out, but it takes time to ensure all its functions that we still need are covered by the new test suite. When it comes to dialyzer it has copied inets code and using it for its own purposes so that could be ok.

I think you should make a PR for the removals in inets based on master (OTP 19). As we are not making an more planned 18 releases.  And this  does not solve any serious bug in 18.

**Comment by waisbrot** [comment]
I can open a PR against "master" with changes along these lines. 

Are you saying that this PR should be closed (and that webtool will be left broken in 18.x)?

**Comment by IngelaAndin** [comment]
What I am saying is that I do not see that  this bug in webtool will motivate an "unplanned patch of 18", possible it could be included if we for some other reason, make another patch to18. So you could make a PR for maint that would be on the wish list so to speak, but it will not guarantee a patch.  The inets changes should be made but are not really important for the functionality of inets in 18, and as there are no more planed 18 patches it is logical to aim for 19.

**Comment by psyeugenic** [comment]
I'll remove the dependency to `mod_include` in Webtool and push it to maint before release.

**Comment by IngelaAndin** [comment]
+1 for good will Egil :)

**Comment by waisbrot** [comment]
Thanks! I've opened a PR against master to about the other changes.

**Comment by SamuelCox** [comment]
Which release is this fix in?

**Pull request closed without merging**
