### PR TITLE
Fix init:stop()

### PR DESCRIPTION
**Pull request by richcarl**
The Status argument to init:stop/1 is not sanity checked, and when it eventually gets passed to halt(Status), it can cause the init process to die in an uncontrolled way instead of cleanly shutting down.  For example:
    1> init:stop(blah).
    ok
    2> 
    Crash dump is being written to: /tmp/erl_crash_dump...done
    System process <0.0.0> terminated: {badarg,[{erlang,halt,[blah],[]},{init,do_stop,2,[]}]}

This patch checks the argument to init:stop/1 and causes a badarg if it is not acceptable for passing to halt/1. (The special 'abort' atom is not allowed either.) Also updates the documentation of halt() to clarify that the string may only be a list of bytes, not longer than 200.

(Note that I have run "./otp_build update_preloaded" in order for this to pass automated tests, but you should probably drop that commit before merging and run it again yourselves, unless you trust that I don't sneak anything nasty into the preloaded beam files...)

This is related to ERL-49.

### CODE REVIEW

**Comment by richcarl** [comment]
Updated: don't exit with badarg if Status is a valid byte list longer than 200 chars. Instead, truncate it so that it is accepted by halt/1. This is because the string may be dynamically computed, and the shutdown shouldn't fail just because the slogan string gets too long. (In our case, it was a very long file name that caused us to discover this.)

**Comment by richcarl** [comment]
Related to ERL-49.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Merged to master with some extra commits to do the string truncation in erlang:halt.

**Pull request closed without merging**
