### PR TITLE
Add function to align maps

### PR DESCRIPTION
**Pull request by davidw**
It's convenient to have a function that aligns map keys and values.

### CODE REVIEW

**Comment by davidw** [comment]
Maybe adding some alignment rules would make more sense?

https://www.emacswiki.org/emacs/AlignCommands

**Comment by larshesel** [comment]
Great idea @davidw ! Do you think it would be possible to also align the `::` in record specs as well?

**Comment by davidw** [comment]
@larshesel probably, but one thing at a time!

**Comment by davidw** [comment]
I tried a different approach, that lets people use Emacs `align` in the other PR.

**Comment by dgud** [comment]
Closing this, I prefer #1728 that builds on existing emacs functionality.

**Pull request closed without merging**
