### PR TITLE
Default compiler flags

### PR DESCRIPTION
**Pull request by richcarl**
I think it's time to start warning for the use of export_all by default. This should never be left in the code by mistake, as it often ends up being. If you use it in production, you should know about it and suppress warnings explicitly.

Also, fix up some leftovers from when warn_obsolete_guard got enabled by default, in particular the documentation.

### CODE REVIEW

**Comment by psyeugenic** [comment]
I agree with this. `export_all` should never really be there .. it leads to bad behaviour. It's a gateway attribute.

**Comment by bjorng** [comment]
The system does not build if I build it from scratch after updating the primary bootstrap:

```
compile: warnings being treated as errors
unix_telnet.erl:56: export_all flag enabled - all functions will be exported
make[3]: *** [../ebin/unix_telnet.beam] Error 1
make[3]: *** Waiting for unfinished jobs....


```

To update the primary bootstrap, first build the system. Then:

    PATH=$ERL_TOP/bin:$PATH ./otp_build update_primary

**Comment by richcarl** [comment]
Fixed and tested with updated bootstrap. (I didn't include the bootstrap commit, since only you should do that step.)

Also note that when "make tests" is run, you get quite a lot of warnings, as expected, but nothing breaks. Suppressing such warnings or eliminating the need for export_all in test modules is a separate issue.

**Comment by bjorng** [comment]
Some test suites are built when they are run. One of them is the test suite for `asn1`, which also uses `warnings_as_errors`. I fixed that in a separate commit. I also fixed a test case for `diameter`.

**Comment by bjorng** [comment]
I've added the branch to our daily builds.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: diameter tests: Eliminate use of -compile(export_all).
asn1 test suite: Suppress warnings for -compile(export_all).
Remove left-over uses of -compile(export_all).


----------------

I am a script, I am not human 

----------------

**Comment by richcarl** [comment]
@bjorng Since you added the latest commits, you get the honor of amending the messages of all that end in a dot. :-)

**Comment by bjorng** [comment]
The sentences don't end in a dot. It is the -compile(export_all) directive that ends in a dot! But the script is too stupid to see that. :-)

Anyway, I removed the dots in my commits. I tried to amend your commit with the dot, but github did not accept my change, so you will have to fix that commit yourself.

**Comment by psyeugenic** [comment]
Errm, I think all of our linter tests in stdlib is now lighting up like it's christmas morning.

**Comment by richcarl** [comment]
Perhaps it would be good if the more trivial sanity checks, like commit message formatting, were done as soon as possible in the chain. I didn't get a warning for the dot in my commit until yours were also checked.

**Comment by psyeugenic** [comment]
@richcarl It would be a good idea. I think @bjorng is in the process of rewriting that script so perhaps he could do something. Or perhaps enhancing the travis thing would be better since it works on push triggers. I don't know how easy that would be since I know very little about travis.

**Comment by bjorng** [comment]
> Perhaps it would be good if the more trivial sanity checks, like commit message formatting, were done as soon as possible in the chain. I didn't get a warning for the dot in my commit until yours were also checked.

Agreed. I am not sure how frequent the current script is run, but I certainly think it should be run more frequently.

**Comment by essen** [comment]
If my mailbox is any indication, the "dot" script runs every evening around 8 on all PRs that changed during that day.

**Comment by bjorng** [comment]
> Errm, I think all of our linter tests in stdlib is now lighting up like it's christmas morning.

Did you see this? Many test cases in STDLIB fail because they get unexpected warnings. There are failed test cases in: `qcl_SUITE`, `erl_lint_SUITE`, `epp_SUITE`. Please fix them.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by richcarl** [comment]
I think you'll need to update primary bootstrap again.

**Pull request merged**
