### PR TITLE
dialyzer: Fix slow Dialyzer run on Elixir source code

### PR DESCRIPTION
**Pull request by lucioleKi**
Fix https://github.com/erlang/otp/issues/9135. Dialyzer was slow because in `dialyzer_dataflow:handle_guard_call/5`, previous way of handling opaque warnings required one extra round of binding for guards. In Elixir source code, guards in the format of `when digit in ?0..?9` can be expanded to more than 10 guards during Dialyzer's analysis, which made the inefficiency more obvious.

### CODE REVIEW

**Comment by bjorng** [comment]
Nitpick: it is actually doing `in` with a right-hand side operand being a literal list that expands to multiple guard tests. For example:

```
  def check(n) when n in [1, 2, 3, 4, 5, 6], do: :ok
  def check_digit(digit) when digit in ?0..?9, do: :ok
```

This result in the following Erlang code:

```
check(_n@1)
    when
        ((((_n@1 =:= 1
            orelse
            _n@1 =:= 2)
           orelse
           _n@1 =:= 3)
          orelse
          _n@1 =:= 4)
         orelse
         _n@1 =:= 5)
        orelse
        _n@1 =:= 6 ->
    ok.

check_digit(_digit@1)
    when
        is_integer(_digit@1)
        andalso
        _digit@1 >= 48
        andalso
        _digit@1 =< 57 ->
    ok.
```

**Comment by josevalim** [comment]
@bjorng would you recommend it being left-side or it is all the same? IIRC it was left-side a long time ago and we changed it because Dialyzer was unhappy. :)

**Comment by lucioleKi** [comment]
I think Dialyzer sees both cases in different places. After this fix, I see less `orelse` than `andalso, =<, >=` in guards. The total number of them isn't unusual, comparing to other expressions in guards. I'm leaning towards that our previous mistake made the corner case bigger. Maybe there aren't many places where guards were expanded to linearly many `orelse, =:=` guards, but they overwhelmed the previous analysis.

**Comment by josevalim** [comment]
> That it, like so:

Yes. I did some digging and apparently it was a compiler issue:

* Issue: https://github.com/elixir-lang/elixir/issues/10114
* Fix: https://github.com/elixir-lang/elixir/commit/4a2047af1fda32f814e6b9a07b5aa5acd59e1d6b

Although I also remember a related Dialyzer issue. I will continue digging.

**Review by bjorng — APPROVED** [review]

**Pull request merged**
