### PR TITLE
ssl: verify cert signature against original cert binary

### PR DESCRIPTION
**Pull request by xenolinguist**
The process of round-trip decoding and re-encoding of arbitrary certificates in the wild can be lossy in some cases, and so re-encoding an `#'OTPCertificate'` to check its digital signature is problematic. Some comments on Github commit ad92184636f134b8fc6f3e897c55dd5b27bac560 discuss one scenario, and this PR includes a test case reproduction of a different scenario I encountered in the wild:

Our Erlang/OTP program calls out to a third-party web service over HTTPS. That web server's certificate includes the `id-ce-keyUsage` extension with typical values for a web server: `digitalSignature` and `keyEncipherment`. However, the bit string representation for this value is encoded in a nonstandard way:

    733:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
    738:d=5  hl=2 l=   1 prim: BOOLEAN           :255
    741:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:030200A0

The `00` byte indicates zero unused bits in the bit-string. Standard encoding has `05` instead, since only bits 1 and 3 are set, leaving 5 trailing zero bits.

This certificate parses just fine in OTP, but it does not include the necessary fields in its `id-ce-authorityKeyIdentifier` extension and therefore the issuer must be looked-up in the `CertDB`. Because OTP encodes the key usages according to standard as hex `030205A0`, the process of re-encoding the certificate when searching for the issuer in the `CertDB` causes signature verification to fail erroneously, since the signature is valid over the original DER certificate presented during the handshake. This causes our program's client to fail to validation of the server's certificate and send the alert `unknown_ca`.

/cc @jwheare @oferrigni @chef/erlangers

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I agree with this, and the tests pass. Merged to maint just now.

**Comment by xenolinguist** [comment]
@IngelaAndin thanks! I'm not seeing the change on Github's `maint` yet, is there some lag before that merge gets pushed?

**Comment by garazdawi** [comment]
@xenolinguist yes there is a delay from the internal merge to when it is visible on github

**Pull request closed without merging**
