### PR TITLE
Rewrite RR cache access time update to preserve table insert order

### LINKED ISSUE #7577: DNS caching causes host records to be returned in sorted order
**Describe the bug**
When DNS caching is enabled, and a host has multiple records associated with it, the DNS cache returns those records in sorted order. 

@starbelly helped me in [this Erlang Forum post](https://erlangforums.com/t/why-does-erlangs-dns-caching-sort-host-ips/2806) and showed how the issue stems from the usage of maps for de-duplication. When a host has <= 32 records it qualifies as a "small map" and the current implementation in Erlang will sort the entries by key. It explains why we were seeing calls to `inet:getaddrs/2` returning IPs in sorted order.

**To Reproduce**
[This gist](https://gist.github.com/mattbaker/e1aaa66be03c11f69649fded0d931107) is a fairly tight reproduction of the issue that you can run from the command line if you have docker installed. It demonstrates the issue by calling `inet:getaddrs` multiple times with and without caching enabled to highlight the difference.

Nothing about this bug is docker specific, but docker just so happens to offer a simple round-robin DNS system when you launch multiple containers with the same alias so it was very convenient for this bug report!

**Expected behavior**
We would expect the order of the records in the cache to match the order returned by the DNS server. We would not expect the order to be modified.

**Affected versions**
I believe this was introduced in https://github.com/erlang/otp/pull/4633, which means this would affect OTP 24.0 and later based on [references in the OTP 24 README](https://erlang.org/download/OTP-24.0.README).

**Additional context**
The current behavior of the cache breaks the [round-robin DNS](https://en.wikipedia.org/wiki/Round-robin_DNS) load balancing strategy in which a DNS server randomizes the order of records it returns for a given host lookup in order to distribute load evenly. 

Because the cache returns the records in sorted order, an Erlang application with DNS caching enabled will always select the "lowest" record by sort order which sends all the load to a single, consistent IP. 

My impression is round-robin DNS, while not without flaws, is a common enough practice that the current behavior of the DNS cache is probably not desirable.

I do wonder if the idea of passing a custom `inet_tcp` module mentioned in [this comment](https://github.com/erlang/otp/pull/4633#issuecomment-811020449) could be a good short-term fix for anyone dealing with a similar concern.

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
The cache ETS table is a bag table that in itself preserves insert order, and when access times in the table are update, it is possible to do the insertion of RRs with updated access time in the same order, which overall preserves insert order.

To preserve the RR order; rewrite the deduplication code to not store the deduplicated result in a map, but instead use a map for deduplication lookup and store the result in a list.

All this to not get in the way of DNS servers that e.g. implement load balancing by returning RRs in some specific order.

Closes #7577

### CODE REVIEW

**Comment by starbelly** [comment]
@RaimoNiskanen LGTM! I was quite convinced there was an edge case that would not afford simply switching to list for everything to just work ™️  Thanks for showing me otherwise ❤️

**Comment by starbelly** [comment]
Ok, double checked, triple checked even 😄,  and it looks solid 👍 

Here's a [gist](https://gist.github.com/starbelly/27c2f1e8da56356b99151b0673d1bd38) of the test.

**Comment by sneako** [comment]
> It would also be nice if @mattbaker could verify that it solves his #7577, and if @sneako could verify that his heavy load cache tests does not suffer regression...

Wow, exciting! Thank you for working on this. I just got back from vacation so I have a bit of catch up to do, but I will make sure to test this out this week.

**Comment by mattbaker** [comment]
First time compiling Erlang but I think I got it 😅 

I can confirm that records no longer appear sorted with this patch, looks like a success to me 👍

**Comment by sneako** [comment]
I've been running this patch on a single node in a cluster for 2 hours so far and performance looks identical to the unpatched peers. Have not noticed any adverse side effects. LGTM, thanks everyone!

**Pull request merged**
