### PR TITLE
Specialise some instructions for r source

### PR DESCRIPTION
**Pull request by michalmuskala**
Especially select_val2 with values true/false or false/nil (for Elixir)
is frequent as a result of a boolean case (or Elixir if).

The instructions already used micro instructions so the increase in size
for the main emulator loop should be minimal.

### CODE REVIEW

**Comment by bjorng** [comment]
Have you made any measurements to see whether this change is actually beneficial?

On a 64-bit computer without ASLR this change does not actually reduce the size of any of the instructions, because the X register number will be packed in the instruction word. I think that this platform is the most common platform.

On a 32-bit computer or 64-bit computer with ASLR the X register number can't be packed into the instruction word, so on those platforms there would be a size reduction.

**Comment by michalmuskala** [comment]
I'm not sure if running this on my mac hits the ASLR runtime or not, but compiling a simple function:

```erlang
test(a) -> 1;
test(b) -> 2;
test(c) -> 3.
```

results in this code before the changes:

```
000000010BB11638: i_func_info_IaaI 0 test test 1 
000000010BB11660: i_select_val_lins_xfI x(0) f(000000010BB11638) 4 c a b -1 f(000000010BB116C8) f(000000010BB116A8) f(000000010BB116B8) f(000000010BB11638) 
000000010BB116A8: move_return_c 1 
000000010BB116B8: move_return_c 2 
000000010BB116C8: move_return_c 3 
```

So the size of the select instruction is 72 bytes. While after the changes the size is 64 bytes from the resulting code:

```
000000010D983C68: i_func_info_IaaI 0 test test 1 
000000010D983C90: i_select_val_lins_rfI r(0) f(000000010D983C68) 4 c a b -1 f(000000010D983CF0) f(000000010D983CD0) f(000000010D983CE0) f(000000010D983C68) 
000000010D983CD0: move_return_c 1 
000000010D983CE0: move_return_c 2 
000000010D983CF0: move_return_c 3 
```

**Comment by michalmuskala** [comment]
I pushed some even more changes to couple more instructions that benefit from this as well.

Here are the diffs for the `beam_hot.h` and `beam_warm.h` files from my machine: https://gist.github.com/michalmuskala/3efd1bdfcbac390ca8b8ef694a5c9565

**Comment by bjorng** [comment]
My comment about ASLR was somewhat simplified. `beam_makeops` doesn't actually care about ASLR. What it cares about is whether pointers to code fits in 32 bits.

The Mac uses ASLR. However, if HiPE is enabled on the Mac, an extra linker option `-pagezero_size 0x10000000` will be given to force all code to lower addresses. Addresses will still be randomized, but  all code pointers will still fit in 32 bits.

To find out which code model is used, the generated `Makefile` for the emulator can be examined. On my Mac, it is found here: `$ERL_TOP/erts/emulator/x86_64-apple-darwin17.7.0/Makefile`

The interesting part is the invocation of `beam_makeops` which looks like this on my Mac:

```
$(TTF_DIR)/OPCODES-GENERATED: $(OPCODE_TABLES) utils/beam_makeops
	$(gen_verbose)LANG=C $(PERL) utils/beam_makeops \
		-wordsize 64 \
		-code-model small \
		-outdir $(TTF_DIR) \
		-DUSE_VM_PROBES=$(if $(USE_VM_PROBES),1,0) \
		-DNO_FPE_SIGNALS=$(if $(filter unreliable,$(FPE)),1,0) \
		-emulator $(OPCODE_TABLES) && echo $? >$(TTF_DIR)/OPCODES-GENERATED
```

`-code-model small` means that pointers to code will fit in 32 bits.

Another way to find out which code model is used is to look at the generated code. Here is some code from `beam_hot.h` from my Mac:

```
{
  Eterm select_val2;
  OpCase(i_select_tuple_arity2_rfAA):
  {
    select_val2 = r(0);
  }
  goto select_val2__get_arity;

  OpCase(i_select_tuple_arity2_xfAA):
  {
    select_val2 = xb(BeamExtraData(I[0]));
  }
  goto select_val2__get_arity;

  OpCase(i_select_tuple_arity2_yfAA):
  {
    select_val2 = yb(BeamExtraData(I[0]));
  }
  goto select_val2__get_arity;
```

`BeamExtraData(I[0]))` retrieves a 32-bit value from the instruction word.

I have High Sierra on my Mac and I have HiPE enabled (the default). Which macOS do you use? Have you disabled HiPE?

**Comment by bjorng** [comment]
By the way, instruction sizes can be found in `beam_opcodes.c` (in the same directory as `beam_hot.h`). Here are the lines for the `select_val` instructions:

```
/* 260 */  {"i_select_val2_rfcc", {0x200408,0x21062106,0x0}, 1, 4, 0, "", "rfcc"},
/* 261 */  {"i_select_val2_xfcc", {0x200008,0x21062106,0x0}, 0, 4, 0, "ggf4#ppp", "xfcc"},
/* 262 */  {"i_select_val2_yfcc", {0x200010,0x21062106,0x0}, 0, 4, 0, "ggf4#ppp", "yfcc"},
```

The instruction size is 4 words.

**Comment by michalmuskala** [comment]
Ah, yeah, I usually run the VM with hipe disabled. That's probably why I don't see the small code layout.

I'll look into making the changes you've requested.

**Comment by bjorng** [comment]
I'll close this PR now, because it's too late to include in OTP 22.

If you want to rework this PR for OTP 23, please note that `bs_start_match2` is not used in code compiled by OTP 22 or higher.

There is a new HOW-TO for [Counting Instructions](https://github.com/erlang/otp/blob/master/erts/emulator/internal_doc/CountingInstructions.md) that could be useful if you are going to update the PR.

**Pull request closed without merging**
