### PR TITLE
multi function define in one line cause cover:analyze_to_file output incorrect

### PR DESCRIPTION
**Pull request by slepher**
multi function define in one line (may happens in generated code by parse_transform) cause cover:analyze_to_file output incorrect

run sh test/cover_SUITE_data/run_multi.sh at lib/tools/ directory
will output two files
test/cover_SUITE_data/multi_before.html
test/cover_SUITE_data/multi_after.html

first one is incorrent output
second one is correct output

### CODE REVIEW

**Comment by slepher** [comment]
this fix is incomplete
plz wait for my other commit
thanks

**Comment by uabboli** [comment]
Thanks for pointing out the bug. We'll reject your patch, though,
since it has issues. The test doesn't play well with the test
suite, for example. Please have a look at the branch at
uabboli/otp mentioned above, and let me know if there is
anything I've missed.

**Comment by slepher** [comment]
it works well on my project, thanks for fixing this.

**Comment by uabboli** [comment]
Merged commit c0af217b1255361ad11d0508e6591b8e649ebc7a into erlang:maint.

**Pull request closed without merging**
