### PR TITLE
Add get_arguments function to escript

### PR DESCRIPTION
**Pull request by ebengt**
Escript lacks functions to handle main()'s arguments.
To fix this I copied the existing functions found in the init module.
Originally I thought to resuse that code, but could not find it.
Potential future project: Use a NIF to get at it?

### CODE REVIEW

**Comment by garazdawi** [comment]
hmm, I don't think this should be builtin into the escript module. Personally I use https://hex.pm/packages/getopt to do argument handling in my escripts, there are also other great third-party libraries that give provide this functionality much better than can be done by OTP.

**Comment by ebengt** [comment]
Greetings,

I agree that there are better alternatives, but I would definitely suggest that some functionality should be present in Erlang/OTP.
So, if somebody else want to make a better alternative that is fine, but I do think get_arguments is better than nothing.

Best Wishes,
bengt

**Comment by vladdu** [comment]
Wouldn't it be better to extract the get_arguments functionality into a common module, to be used by init and escript? 

The problem with relying on third-party utilities is that it might be difficult to find and to know if they are any good and if they are maintained. With the same argument we could say that get_arguments should be removed from init too.

**Comment by ebengt** [comment]
init is using C code, or rather, I could not find any Erlang for init’s get_argument.
By writing for the same interface it will be possible to use the same code in the future.
If that means building an interface for the escript version to access init's, or the other way around, I do not know.
If my pull request is accepted I will look at both. And maybe find that neither is good idea...

**Comment by garazdawi** [comment]
init:get_argument/1 is implemented here: https://github.com/erlang/otp/blob/master/erts/preloaded/src/init.erl#L110 and eventually ends up here: https://github.com/erlang/otp/blob/master/erts/preloaded/src/init.erl#L1266

**Comment by ebengt** [comment]
The code in init.erl directly send a request to the init process. I did not find where it is received. Therefore my guess at C code.
If it is not C then it might be easier to share the implementation. If accepted, etc.

**Comment by bjorng** [comment]
We reject this pull request because we don't think this functionality belongs in OTP.

It is often simpler to parse the command line by simple list matching. When the arguments/options get more complicated, one of will often have to work around the limitations of the command parsing utilities or do it oneself anyway.

Therefore, I predict that if we would actually include utility functions for parsing arguments/options, there would soon be many bug reports and request for extensions.

**Pull request closed without merging**
