### PR TITLE
Improving ETS performances

### PR DESCRIPTION
**Pull request by fltt**
Add nested linear hash tables to ETS.

### CODE REVIEW

**Comment by fltt** [comment]
Hello again.
This is the three stages implementation of the nested LHT: no memory overhead at all when the nested LHT is not active.

From a simple test I made, set and bag/duplicate_bag performances are almost identical, so it may be reasonable to merge "erl_db_nested_hash.c" and "erl_db_hash.c".
If you agree, I can do it now (I mean, within a few days).

In regards to the "yielding" problem of some ETS' functions, I can do that too, but not anytime soon.
Regards.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fltt** [comment]
In the meanwhile I've merged erl_db_hash into erl_db_nested_hash, just in case:
```
git fetch https://github.com/fltt/otp.git ets_nested_lht-merged

https://github.com/fltt/otp/compare/erlang:maint...ets_nested_lht-merged
https://github.com/fltt/otp/compare/erlang:maint...ets_nested_lht-merged.patch
```

**Comment by sverker** [comment]
Oh good. I haven't had time to give it a serious look yet. Soon...

FYI: This was brought up on the mailing list a while ago about iteration
over bag with a lot of key duplicates behaves a bit strange:
http://erlang.org/pipermail/erlang-questions/2015-September/085949.html

**Comment by fltt** [comment]
I'll look into it...

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by fltt** [comment]
The ordering bug is fixed.

Regarding the optimization issue I could find the following solution (which I actually don't like, because of the "heuristic" part).

**NOTE**: When I talk about objects skipped or returned twice or more, I'm referring to those objects that were present in the table when the lookup started and that were not deleted in the meanwhile. Whether objects inserted or deleted during the lookup are returned or not, is not an issue here.

To minimize the amount of memory associated to the continuation term, a single "reference" object, say the next object to be returned, could be stored in the continuation instead of the whole bucket.
For duplicate_bag tables, an index would also be stored in the continuation, to distinguish between different instances of the same object.
This index would count the numbers of instances from the *tail* of the bucket.
This is so, because new objects are inserted from the head.

As long as the reference object is not removed from the ETS, it is possible to reliably continue the lookup.
However, if the reference object is deleted, then things became tricky.

In the case the table is fixed, a slight change in the way pseudo-deletion works (namely retaining *all* the objects deleted, not just one of them per key), would do.
Whereas, in the case the table is not fixed, some heuristics could be done.
For instance, the position of the reference object in the bucket (in terms of offset from the tail or maybe the head) could be stored, alongside the length of the bucket, in the continuation.
If the reference object cannot be found, then the one at the position computed scaling linearly the saved position against the new length of the bucket could be chosen as the new reference object.
This is far from perfect as several objects could be skipped or returned twice or even more than twice, if the chunk size is very small.

Note that the current implementation is more reliable than this solution: it doesn't return the same object twice and it's highly improbable to skip objects (although not impossible).

What do you think? Any better idea?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lpgauth** [comment]
any updates for this pull-req? is it in review?

**Comment by sverker** [comment]
In limbo waiting to be reviewed. This is a big change a would need some serious attention before it can make it into a release. It's a matter of priority.

**Comment by sverker** [comment]
Sorry for the inactivity for so long.
We appreciate the contribution but, apart from being based on maint branch, this PR will not be merged due to two main reasons:

- `ets:lookup` returns all objects without yielding. This can be a real performance problem as this feature itself encourage the use case of lots of object with identical keys. To implement this can be a bit tricky as objects may be inserted and deleted while `ets:lookup` is yielding.
- I think there is a simpler and more efficient implementation for this whole feature. We don't really need one nested hash table per key. They can all share the same hash table where the entire object is the hash-key. Maybe for `write_concurrency` we want one hash table per lock (64). One could also imagine to let each object be hashed only once, in either the key-table or the object-table, which would reduce memory overhead per object.

To go further with this feature, create a new pull request based on master branch.

**Comment by fltt** [comment]
The project this patch was meant for was cancelled a few weeks after my first e-mail on the subject. So, at the moment, I don't need such a feature. Should I need it in the future, you'll hear from me again. Until then, bye.

**Pull request closed without merging**
