### PR TITLE
hipe_x86_signal: add support for musl libc

### PR DESCRIPTION
**Pull request by mikpe**
- change #if tests at default Solaris case to explicitly check for __sun__
- add new default case, instantiate it for musl

### CODE REVIEW

**Comment by mikpe** [comment]
hipe_x86_signal.c is getting a bit unwieldy, so I'm planning on doing some cleanups by dropping support for ancient systems and refactoring a bit.  Longer-term I think some tests should be done in configure.{ac,in} rather than via the pre-processor.

**Comment by tuncer** [comment]
Thanks, @mikpe.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by jj1bdx** [comment]
Correction: NetBSD was not suitable for FreeBSD. Copying DARWIN code for FreeBSD seems to be compiling ok, but more tests are needed.

**Comment by mikpe** [comment]
The correct fix is indeed for a port like FreeBSD to have its own specific block of code.  Piggy-backing on others or worse the default doesn't work in the long run.

There's a basic HiPE test suite in there somewhere.  You should also try --enable-native-libs.

**Comment by jj1bdx** [comment]
Testing with --enable-native-libs is a good point. I'll try that out. I've included a new block of code in https://github.com/erlang/otp/issues/925 for FreeBSD.

**Pull request merged**
