### PR TITLE
fix: rename `openssl/md5.h` to avoid include conflicts with OpenSSL

### PR DESCRIPTION
**Pull request by paulswartz**
Ref: #7987

I didn't look into it, but an alternate approach would be to use the OpenSSL implementation directly if OpenSSL is present (`--with-ssl`).

### CODE REVIEW

**Comment by garazdawi** [comment]
Hi @paulswartz! Thanks for the PR!

Github CI does not pass, so it would seem like you have missed to update a couple of places?

Could you also please rebase the change onto the `maint-26` branch (`git rebase --onto maint-26 HEAD~1`) so that we can release the fix as a patch on OTP 26.

**Comment by garazdawi** [comment]
Ah, is that was is causing the issues... getting a build cache correct is hard...

If you add a commit with:

```
- deleted: '**.h'
```

To the [`no-cache` filter](https://github.com/erlang/otp/blob/master/.github/workflows/main.yaml#L98) it will skip using the cache whenever anyone deletes a .h file.

**Comment by paulswartz** [comment]
@garazdawi thanks for the pointer! The build looks better now.

**Comment by garazdawi** [comment]
Fix merged, will be part of next OTP-26 patch. I'm closing this PR manually as the fix will not be merged to maint-26 until the patch is actually released.

Thanks for the fix!

**Comment by dvkch** [comment]
It would be needed for version 24.3.4.17 as well, haven't been able to install on Sonoma 14.6 as well.

**Pull request closed without merging**
