### PR TITLE
Run dialyzer (for some apps) in travis

### PR DESCRIPTION
**Pull request by kostis**

### CODE REVIEW

**Comment by bjorng** [comment]
Thanks!

I have duplicated this pull request, rebasing it on `master` to test that it really can detect dialyzer problems.

**Comment by bjorng** [comment]
Yes, it works! 👍

**Comment by kostis** [comment]
Of course it works!  What did you expect? ;)

Note that this PR is only a trimmed-down version of the real change I wanted to make.  It does _not_ test all applications it could.  AFAIK, currently, the following applications dialyze cleanly with `-Wunmatched_returns`:

  `asn1 compiler crypto debugger dialyzer edoc eldap erl_docgen erts et hipe odbc os_mon otp_mibs parsetools percept public_key runtime_tools sasl stdlib syntax_tools tools typer wx xmerl`

and till recently `common_test`, until a commit this week by @pekadan introduced the following warning:
  `ct_util.erl:191: Expression produces a value of type 'ignore' | {'error',_} | {'ok',pid()}, but this value is unmatched`
which he may want to fix.

Note that this set does _not_ include `kernel` because this app still needs `-Wno_improper_lists` for a clean dialyzer run.  You probably want to fix that so that at least `kernel` is included.

Unfortunately though, such big set of applications can not be run on Travis currently.  The main problem is that the `warning` pass of dialyzer currently requires too much memory.  Somebody (@uabboli ?) may want to look into that and improve the memory consumption of this pass.  Another problem I run into, is that Travis, for its own reasons that I do not fully understand, sometimes kills jobs that are computationally or memory demanding.  (This happens to me once yesterday when I tested this pull request and it is _not_ related to the warning problem I describe above.)

Still, this is a good set of applications to start with.  It can become better in the short term with kernel's inclusion. Adding more applications to the second line of the patch is a longer term project.

**Comment by okeuday** [comment]
@kostis I have run into a [travis 10 minute timeout](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) when no output is received, which might be the problem you are experiencing.  I added a progress bar to the problematic script ( [here](https://github.com/okeuday/reltool_util/blob/ba074cf61415ff1e10c5ae05868c6bb960fd4276/scope#L908-L979) ) to avoid the problem.  Perhaps dialyzer could benefit from a progress bar?

**Comment by fenollp** [comment]
@kostis Travis seems to have a maximum of 2GB memory, which Dialyzer can eat pretty fast. 

What we used to do at 2600Hz is dialyze only files changed by the PR and also dialyzing them one by one. 

CircleCI has something like 60GB RAM

**Comment by kostis** [comment]
@okeuday : I doubt that the timeout when no output not the problem here.  Note that dialyzer runs with the `--statistics` options which prints statistics about each pass that finished. (You can see that if you expand the dialyzer runs on the travis script.)  Also, in absolute terms, none of the dialyzer runs needs longer than 10 mins.

**Comment by kostis** [comment]
It's probably a good suggestion for the second invocation.  Just because there are no unknowns today, it does not mean that they will still not be after changes.  Yes, go ahead and add this.

For the first invocation, that builds the PLT, it's also a good idea but I am afraid it will not work.  Note that invocation currently does not run any warning pass in dialyzer.  The warning pass is currently very memory hungry as I wrote above and, most likely, travis will kill the job if we add this.  (Purely guessing here; have not actually tried this.)

**Comment by margnus1** [comment]
From what I can tell, adding `-Wunknown` to a `--build_plt` run does not run the warning pass (it's not printed with `--statistics`, at least). Also, even without `-Wunknown`, `--build_plt` produces a list of all unknown modules and functions; I think the only thing `-Wunknown` changes is whether dialyzer produces a non-zero return code in those cases.

**Comment by kostis** [comment]
OK then, go ahead and add them.

**Comment by bjorng** [comment]
I have already merged this PR.

And I have opened #1248 to analyze fewer applications, because Travis has already crashed twice when I have pushed branches.

If reducing the number of application does eliminate the crashes, I will have to revert this PR.

**Comment by bjorng** [comment]
> Note that this set does not include kernel because this app still needs -Wno_improper_lists for a clean dialyzer run. You probably want to fix that so that at least kernel is included.

We don't see any warnings for improper lists in kernel. Maybe you run with a tweaked dialyzer that detects more problems?

**Comment by kostis** [comment]
Where exactly were the crashes? On which invocation, the first of the second line?
I think it's important that the first line contains all / most these applications because this is this a set that contains no "unknown functions".
The second invocation can of course be trimmed down. As a matter of fact, if the PLT is reasonably complete, the second invocation can be substituted by multiple ones (i.e. similar lines) where smaller sets of applications are analyzed at a time.

PS.  My bad about `kernel`.  Yes, it can be added.

**Comment by bjorng** [comment]
Second line.

**Comment by kostis** [comment]
Then split it into multiple ones.  This should do it -- and it should allow you to add _all_ applications mentioned above (in sets that logically belong together).  Do not forget to add `-Wunknown` to these lines as @margnus1 suggested.

**Comment by bjorng** [comment]
OK. I have done that.

**Pull request merged**
