### PR TITLE
Add BIFs term_to_json and json_to_term

### PR DESCRIPTION
**Pull request by dhull**
This branch implements two new BIFs, `erlang:term_to_json` and `erlang:json_to_term`, for converting between Erlang terms and JSON-encoded binaries.  These BIFs are well-behaved: long running calls periodically yield to other processes.  The BIFs are fast: on my data, encoding is about five times faster and decoding is about three times faster than the other libraries. See the [json.org](https://github.com/dhull/otp/blob/master-json/json.org) file for more information.

### CODE REVIEW

**Comment by vans163** [comment]
Nice!
```
erlang:json_to_term always returns keys as binaries.
```

Is it possible to add an option to return atoms, I know the logic, its not safe because the endpoint can cause atom flood, but in a lot of cases you interact with endpoints you control or that are 99.99999% not gonna attack you.  The binary->atom key in the BIF will be a huge performance win than doing it from managed code.

Also an extra note of the returned keys/values that are binaries would be nice in the docs.  Are they copies or references to the original json library? Meaning if I do mnesia:dirty_write(lock_mem, {json_key, json_value}), the entire source json will be held on the shared heap?

**Comment by hauleth** [comment]
How will it encode:

- pids
- refs
- tuples

**Comment by crownedgrouse** [comment]
And dates with microsecondes

**Comment by mko-io** [comment]
Erlang term and JSON don't match well
JS Object to Erlang Map kind match,
but JS Array is  a big question, Does it match to tuple or List?

Why just open a port to nodejs, and let it does what it's designed for (doing stuff with JSON and JS object) and pass the result back to beam

**Comment by dhull** [comment]
> Is it possible to add an option to return atoms [as object keys]?

Yes, it would not be hard to add that as an option. The reason that I did not do that already is the atom exhaustion problem that you refer to.

> Also an extra note of the returned keys/values that are binaries would be nice in the docs. Are they copies or references to the original json library?

All JSON string values, including object keys, are returned as new binaries.

> How will it encode: * pids, * refs, * tuples.

It doesn't encode any of those things. These functions aren't meant as a general way to store Erlang terms as JSON, they're meant as a way to generate and parse JSON as quickly as possible.

> And dates with microsecondes

The functions only convert to and from the JSON types, so there is no special handing for dates. You'd have to use some string or number encoding for dates and convert your data to that encoding before converting to JSON.

> Erlang term and JSON don't match well
> JS Object to Erlang Map kind match,
> but JS Array is a big question, Does it match to tuple or List?

The BIFs convert between JSON arrays and Erlang lists. This is the same thing that all of the other Erlang JSON libraries that I am aware of do.

> Why just open a port to nodejs, and let it does what it's designed for (doing stuff with JSON and JS object) and pass the result back to beam

The reason to write these JSON conversion functions as BIFs is for speed. I believe that [Jiffy](https://github.com/davisp/jiffy) is about as fast as any non-BIF that does JSON conversion can be, and Jiffy was becoming the limiting factor in my application.

**Comment by hauleth** [comment]
In that case it shouldn’t use `term_to_*` and `*_to_term` naming, as from such naming I would expect that `*_to_term(term_to_*(Data)) =:= Data`. Also it probably shouldn’t be in `erlang` module.

--
Łukasz Jan Niemier

**Comment by dhull** [comment]
> In that case it shouldn’t use `term_to_*` and `*_to_term` naming, as from such naming I would expect that `*_to_term(term_to_*(Data)) =:= Data`. Also it probably shouldn’t be in `erlang` module.

The names `term_to_json` or `json_to_term` were the ones suggested in [EEP-0018](http://erlang.org/eeps/eep-0018.html) but I'm happy to rename them to anything else that the community likes better. I probably would have used `json:encode` and `json:decode` but there is already a ["json" Erlang module](https://github.com/talentdeficit/json) and a ["json" Elixir module](https://github.com/cblage/elixir-json) and I was reluctant to stomp on those modules.

**Comment by crownedgrouse** [comment]
Date in json can be written 1970-01-01T00:00:00.000Z and erlang counterpart would be {{1970,1,1},  {0,0,0.0}} but is not recognized as an erlang date format.

**Comment by josevalim** [comment]
Great work @dhull!

Regarding pids, dates, etc, it is worth remembering JSON is a very poor data format. It doesn't support decimals, so often a string is used. Datetimes may be represented either as a string or integers (from POSIX epoch). I don't think it would be possible for this API to handle all of those cases and therefore it is most likely that one extra pass over the data will be necessary both when encoding and decoding by most users. The question then is: how would the benchmarks look like if we take into consideration that an early pass on the data is necessary to convert it to "barebones" data structures?

> The BIFs are fast: on my data, encoding is about five times faster and decoding is about three times faster than the other libraries.

Is there any particular reason why the BIFs can be 5x faster than NIFs? Is it a limitation on the NIF APIs or is the extra cost caused by the switch between NIF/Erlang?

**Comment by crownedgrouse** [comment]
For pids ref and tuples , this could be encoded in external Term format  -> json. From json this could cost overhead to detect an external format from a simple utf8 string...

**Comment by josevalim** [comment]
@crownedgrouse that would, IMO, make the built-in functions unsafe for decoding external data. I don't want to give users the ability to inject pids and refs into the system. If someone desires that, then they can explicitly choose how to encode/decode it and add the relevant checks. Also, tuples are composite data types. If you have atoms in the tuples, would you term_to_binary/binary_to_term them too?

I really think that, if those functions are added, they should do basic mapping between JSON and  Erlang types and nothing more. But ideally, I would prefer to close the performance gap between NIFs and BIFs, if at all possible.

**Comment by crownedgrouse** [comment]
yes agree. It is up to user to choose if a binary should be decoded from an external term format if this is what is expected in context.

**Comment by llelf** [comment]
> For pids ref and tuples , this could be encoded in external Term format -> json

You can encode such things manually if you want this insanity.
Also, you cannot store arbitrary binaries as JSON strings.

**Comment by crownedgrouse** [comment]
OK but in such case this should not use term_to and to_term semantic if some erlang term cannot be converted or not in bijective manner . As already mentioned.

**Comment by llelf** [comment]
There's no clear/obvious/one way to make it bijective.  So it shouldn't be there at all.  As already mentioned.

---

That said, `json:{encode,decode}` with strict types is a different question…

```erlang
% for example
-type json_term() :: 'null'
                   | boolean()
                   | number()
                   | unicode:unicode_binary()
                   ⋮

-spec encode(json_term()) -> iodata().

```

**Comment by dhull** [comment]
> > The BIFs are fast: on my data, encoding is about five times faster and decoding is about three times faster than the other libraries.
> 
> Is there any particular reason why the BIFs can be 5x faster than NIFs? Is it a limitation on the NIF APIs or is the extra cost caused by the switch between NIF/Erlang?

I'm not completely sure. When I started this project my suspicion was that Erlang's [erl_nif](http://erlang.org/doc/man/erl_nif.html) functions were adding a lot of overhead, but I no longer think that. I now think that one reason that my BIFs are faster than Jiffy is that Jiffy uses the erl_nif functions to maintain its state. (Look at all of the `enif_make_list_cell` calls in Jiffy's [`encode_iter`](https://github.com/davisp/jiffy/blob/master/c_src/encoder.c#L625) function.) Another issue may be that the NIF interface doesn't have a function to just return the type of a term, so Jiffy has to do a whole series of `if(enif_is_binary(...))`, `if(enif_is_atom(...))` calls instead of just being able to `switch` on the type.

**Comment by dhull** [comment]
> That said, `json:{encode,decode}` with strict types is a different question…
> […]

I don't know if the commenters here have looked at the [json.org](https://github.com/dhull/otp/blob/master-json/json.org) document that I linked to in my description, but it gives a type specification for the Erlang types that it accepts.

```erlang
-typedef jobject()      :: { list({jkey(), jvalue()} | jpreencoded()) } % proplist form
                         | #{ jkey() => jvalue(), json => binary() }.   % map form
-typedef jarray()       :: list(jvalue()).
-typedef jvalue()       :: jstring()
                         | jnumber()
                         | 'true'
                         | 'false'
                         | jnull()
                         | jobject()
                         | jarray()
                         | jpreencoded().
-typedef jstring()      :: unicode:unicode_binary().
-typedef jnumber()      :: integer()
                         | float().
-typedef jkey()         :: jstring()
                         | atom().              % For term_to_binary only. Encoding is UTF-8.
-typedef jpreencoded()  :: { 'json', binary() }.
-typedef jnull()        :: 'null'
                         | 'nil'.               % If `use_nil'.
```

**Comment by dhull** [comment]
I probably should have better explained the motivation for this work in my description on this pull request.

I work on a service whose main purpose is receiving requests from another service, encoding those requests as JSON, sending the JSON to a set of external servers, receiving their responses as JSON, decoding the JSON, and returning the decoded response to the caller. This service was spending 70 to 80% of its time encoding and decoding JSON; using these BIFs it only spends around 20% of its time on those functions. This service runs on hundreds of machines worldwide, and we expect to be able to repurpose many of these machines for other uses or save money as we move the service into the cloud.

These BIFs aren't intended to be for the general-purpose encoding of Erlang terms as JSON. If you need to serialize and deserialize Erlang terms the `term_to_binary` and `binary_to_term` BIFs already do that very well. These BIFs are for when you need to encode and decode messages for one of the many existing services that uses JSON for its data interchange.

**Comment by lpgauth** [comment]
@dhull good old OpenRTB 😉

**Comment by lpgauth** [comment]
@dhull first of all thanks for this. This should save us quite a bit of CPU cycles too.

Any reason atoms cannot be keys?

```
1> jiffy:encode({[{<<"hello">>, world}]}).
<<"{\"hello\":\"world\"}">>
2> term_to_json({[{<<"hello">>, world}]}).
** exception error: bad argument
     in function  term_to_json/1
        called as term_to_json({[{<<"hello">>,world}]})
```

**Comment by okeuday** [comment]
@dhull The `binary` module seems like a good place to put this functionality, instead of the `erlang` module (because of how much already exists in the `erlang` module).  Thanks for adding this!  The performance improvement sounds like it will be very helpful for everyone.

**Comment by archseer** [comment]
I personally think closing the NIF vs BIF gap (or finding the cause at least) would be the best solution too.

If we add JSON support to the standard library, where do we set the line? If JSON is added, someone can come along and make the same reasoning for YAML/BSON/CBOR/messagepack/TOML/etc

**Comment by boboxiaodd** [comment]
i think ， `maps` <=> `json` is  very userfull

**Comment by okeuday** [comment]
@archseer Yes, closing the NIF/BIF gap is important, but JSON support in Erlang/OTP has been requested for many years.  Adding the JSON support now solves the performance issues now.  In the future, JSON support could be moved to a NIF along with `re` (https://bugs.erlang.org/browse/ERL-207).

**Comment by josevalim** [comment]
@okeuday it is still unclear if this patch will solve the performance issues for most applications, if we assume that most applications will have to do another pass on the data to pre-encode/post-decode domain information.

It is also unclear if the current implementation, as a NIF, would be equally performant as in this patch. It may as well be, see @dhull's reply above.

I personally think adding features to Erlang/OTP for performance reasons can be a slippery slope. Focusing on the foundation means every encoding/decoding operation benefits, regardless of format. If a NIF can be made equally as fast as the current patch, I don't see any benefit in adding this directly to Erlang/OTP.

**Comment by starbelly** [comment]
On one hand it would be nice to have such  performance with JSON parsing, but since it's not clear why the performance boost might only be because of it being a BIF, then that needs to be confirmed and quantified. @michalmuskala had commented after having a cursory glance at this, that the performance boost may be due to having greater control over yielding in a BIF. 

OTOH, this just doesn't feel like it belongs in erlang/otp. As @archseer said, if this get in, then there  would be likely more PRs to add  "YAML/BSON/CBOR/messagepack/TOML/etc" in the form of BIF to erlang/otp. I personally want to see erlang/otp shrink vs grow as well 😄 

I  agree with all that the performance gap between BIFs and NIFs should be closed if possible. However, I wonder if there is a good reason and perhaps one that concerns safety in regards to having more control in a BIF vs NIF though...

**Comment by essen** [comment]
A lot of internet standards require JSON. I don't think it's foolish to add JSON and refuse adding other formats. Heck, it was even considered for new HTTP headers not so long ago.

**Comment by crownedgrouse** [comment]
Agree. And OTP is already handling ASN.1 and XML .

**Comment by hauleth** [comment]
ASN.1 support is required for supporting SSL/TLS and SNMP. An personally I would love to see `xmerl` to be extracted from main tree to Hex package, this would provide much more flexibility in development. 

--
Łukasz Jan Niemier

**Comment by archseer** [comment]
Agree with Łukasz. Adding more bells and whistles to the standard library means more maintenance burden and patch releases in terms of security patches and bugfixes. Having them implemented as a separate NIF package allows us to release updates without cutting a new OTP release.

Ruby for example faced such a problem with some of it's standard library, and they [ended up splitting the packages out](https://bugs.ruby-lang.org/issues/5481) but including them with the base installation for backwards compatibility &mdash; note that JSON was one of them. ([Much in the same way, OTP recently split out Corba](https://github.com/erlang/corba).)

Delegating the work out to third-party maintainers also anecdotally leads to a better maintained library down the road. XML is a good example of that, while important, it's [definitely not extremely important in OTP](https://github.com/erlang/otp/commits/master/lib/xmerl), whereas [erlsom](https://github.com/willemdj/erlsom) had recent updates and performs 3-5x faster for me. Yet a lot of developers will reach for xmerl simply because it's in stdlib.

Either way, I admit a can be made for JSON inclusion (more so than for other formats), so I'm not completely ruling it out, but would prefer to see some investigation into jiffy first. In my opinion BIF vs NIF shouldn't really have any trade-offs (other than one built into the VM, the other one loaded by the user) so I'd consider any wide performance gap as a bug.

**Comment by KennethL** [comment]
Some initial thoughts from the OTP team, we will discuss this more internally and come with more input soon.
It has been suggested before that json support should be part of OTP ( EEP-0018 ) , I wrote like this 2010:

"Since we have introduced NIFs as a way to implement and dynamically
load parts of the functions in a
module in C there is no need to introduce new BIFs (Built In
Functions) for encoding /decoding between
Erlang terms and JSON.
EEPs are suggestions regarding extensions of the language and standard
libraries. And BIF's are mostly regarded as
part of the language. Now we don't need a new BIF just because
something is implemented in C (for efficiency reasons)
and thus no EEP.

The suggested functionality in EEP 18 is still very valid and we
welcome the implementation of JSON library or module
that we can include in the distribution or that is distributed separately."

We still think that JSON functionality is interesting and could be part of OTP in that case mostly for the
reason that it is a so common need to encode/decode json and if it is included in OTP then it is always there without creating any extra dependencies.

Some initial thoughts about this solution:
- Should not belong to the erlang module.
- Should not be named term_to_json/json_to_term but rather json:encode/decode (but with a name not conflicting with other json implementations)
- Should rather be an application of it's own even if it is included in OTP.
- Should not be BIFs just because of performance. If close to the same performance can not be achieved with NIFs then we have to investigate why and try to fix this. We know a few reasons why NIFs can not be as efficient as BIFs but need to look deeper into this.
- While discussing JSON I also think there is need for a streaming API both for encode and decode. Decode could work in a similar way as the xmerl_sax_parser with callbacks for each decoded part. The streaming API is to avoid the must of creating a very large Erlang term for a huge input.
- I think this is nice work but have to understand more about why it is more performant than other existing alternatives.

**Comment by ferd** [comment]
Without wanting to join the debate in any way, a new implementation should at least explain how it compares with existing community versions in terms of API and implementation behaviors.

JSON is full of edge cases, and not everyone will support features or deal with edge cases the same way. For example: support for utf-8 validation when encoding/decoding, surrogate values in strings, handling behaviour when keys in an object are duplicate, atom/binary/charlist choices, maps vs. key-vals, sub-binaries or copied binaries per field, and so on.

It is likely easy to make a very fast implementation when dropping some features or taking some shortcuts that have side-effects on the final implementation in the wild (i.e. the binaries being sub-binaries is likely to be much faster, but yield more frequent memory "leaks").

So far, aside from saying "this PR implements JSON", there is a very limited amount of details.

**Comment by hauleth** [comment]
> Another issue may be that the NIF interface doesn't have a function to just return the type of a term, so Jiffy has to do a whole series of `if(enif_is_binary(...))`, `if(enif_is_atom(...))` calls instead of just being able to `switch` on the type.

I have just checked and it is possible to `switch` on type of the `term`, at least in current Erlang versions via `ERL_TYPE(x)` macro, so this seems like either backward compatibility or bug in jiffy.

**Comment by garazdawi** [comment]
> > Another issue may be that the NIF interface doesn't have a function to just return the type of a term, so Jiffy has to do a whole series of `if(enif_is_binary(...))`, `if(enif_is_atom(...))` calls instead of just being able to `switch` on the type.
> 
> I have just checked and it is possible to `switch` on type of the `term`, at least in current Erlang versions via `ERL_TYPE(x)` macro, so this seems like either backward compatibility or bug in jiffy.

What is it that you have tested? The ERL_TYPE in Erlang is part of erl_interface and used to work with those types.

**Comment by garazdawi** [comment]
> Without wanting to join the debate in any way, a new implementation should at least explain how it compares with existing community versions in terms of API and implementation behaviors.

I get the feeling that you may have missed to read the linked description? https://github.com/dhull/otp/blob/master-json/json.org

I found it to be quite thorough.

**Comment by KennethL** [comment]
I agree with @ferd that this implementation must be compared with the other existing JSON implementations for Erlang/Elixir both when it comes to API and other capabilities plus also performance. I would for example like to know why it is so much faster than the NIF implementation in Jiffy. I think a NIF implementation should be able to have close to the same performance.

**Comment by ferd** [comment]
> 
> 
> > Without wanting to join the debate in any way, a new implementation should at least explain how it compares with existing community versions in terms of API and implementation behaviors.
> 
> I get the feeling that you may have missed to read the linked description? https://github.com/dhull/otp/blob/master-json/json.org
> 
> I found it to be quite thorough.

Well, it supports `return_maps` for example, but also mentions that it "does not support Jiffy’s `dedupe_keys` option" nor does it have `strict_keys`, so you still don't know what wins or not for that case, but you know maps can't have duplicate values so a decision is made implicitly somewhere.

But yeah it's at least clear that it never returns a sub-binary, handles surrogate pairs, invalidates utf-8, and so on. 

But if it mostly covers all that evaluation and it is that fast as the spec says, I'll support @KennethL's point of view that it might be more important to find out why NIFs have such a higher overhead than to just bring in JSON as a BIF for speed purposes -- especially since a lot of code is being migrated to use NIFs in Erlang's VM itself.

**Comment by okeuday** [comment]
@KennethL If BIFs and NIFs can have equal performance, converting the PCRE/`re` integration in ERTS to a NIF may be a good way of proving it is possible.  That should be justifiable due to the maintenance involved (as previously discussed in https://bugs.erlang.org/browse/ERL-207).

**Comment by garazdawi** [comment]
> If BIFs and NIFs can have equal performance, converting the PCRE/`re` integration in ERTS to a NIF may be a good way of proving it is possible. That should be justifiable due to the maintenance involved (as previously discussed in https://bugs.erlang.org/browse/ERL-207).

In PCRE's case it is the overhead of switching to dirty execution that is the performance problem. Which is unrelated to the performance issues of a library that already does co-operative scheduling, such as jiffy or this PR.

**Comment by okeuday** [comment]
@garazdawi You are assuming that a PCRE NIF requires dirty execution, but that doesn't seem correct.  A PCRE NIF could yield using `enif_consume_timeslice` in the same way jiffy does instead of `BUMP_REDS`/`BUMP_ALL_REDS` for BIFS or `COST`/`COST_CHK` (as described at [`erts/emulator/pcre/README.pcre_update.md`](https://github.com/erlang/otp/blob/master/erts/emulator/pcre/README.pcre_update.md#what-the-diff-means)) in the current PCRE modifications.  If `enif_consume_timeslice` is inadequate, then the effort to use it would point to the need for more functionality to control reductions bumping.  Not sure if that means enif functions equivalent to `erlang:bump_reductions/1`/`erlang:yield/0` will become necessary, but it looks like it was desired in the [past](https://github.com/basho/eleveldb/commit/ab9d0dda761ca4ca37ffe320656c179c36cc8d04).

**Comment by starbelly** [comment]
>> Without wanting to join the debate in any way, a new implementation should at least explain how it compares with existing community versions in terms of API and implementation behaviors.

> I get the feeling that you may have missed to read the linked description? https://github.com/dhull/otp/blob/master-json/json.org
 I found it to be quite thorough.

@garazdawi I think the tests are thorough in regards to conforming to a spec, but I think if this is to be accepted it should be accompanied by a battery of property and/or fuzzing tests. So, from my perspective I am less concerned about "normal" edge cases and more concerned with security. There are some function (sprintf, memcpy, etc.) that are used that may be changed to improve security, but would need to be looked into further as they may be fine with proper bounds checking.

**Comment by dhull** [comment]
> > Another issue may be that the NIF interface doesn't have a function to just return the type of a term, so Jiffy has to do a whole series of `if(enif_is_binary(...))`, `if(enif_is_atom(...))` calls instead of just being able to `switch` on the type.
> 
> I have just checked and it is possible to `switch` on type of the `term`, at least in current Erlang versions via `ERL_TYPE(x)` macro, so this seems like either backward compatibility or bug in jiffy.

The data types operated on by the erl_interface library are not the ones used internally by the BEAM VM.  My BIF code uses the [`tag_val_def`](https://github.com/erlang/otp/blob/50ce3f30ca1f6548fb7fdf7fca268e4d5ef6094b/erts/emulator/beam/erl_term.h#L1379) function to get the term type, but this function isn't available to NIFs. It's possible to add a NIF function to get the type of an Erlang term, but it doesn't currently exist.

**Comment by dhull** [comment]
> [...] I think if this is to be accepted it should be accompanied by a battery of property and/or fuzzing tests. [...]

The json_SUITE includes the [random_round_trip](https://github.com/dhull/otp/blob/master-json/erts/emulator/test/json_SUITE.erl#L599) test, which generates a random "jobject" term, converts it to JSON and back, and compares the result to the original term. By default it runs for 10 seconds whenever the test is run.

**Comment by starbelly** [comment]
>> [...] I think if this is to be accepted it should be accompanied by a battery of property and/or fuzzing tests. [...]

> The json_SUITE includes the [random_round_trip](https://github.com/dhull/otp/blob/master-json/erts/emulator/test/json_SUITE.erl#L599) test, which generates a random "jobject" term, converts it to JSON and back, and compares the result to the original term. By default it runs for 10 seconds whenever the test is run.

I did see that and that's a bit more than others do 👍 I do think we should try harder to break it though 😄 And property testing is excellent for this. I think myself not unlike others are quite wary when it comes to BIFs/NIFs, but even more when it's C and JSON. Adding property testing to the mix here would just further help boost confidence IMO, but it's not something that can be whipped together real quick, so to be clear, I wasn't not necessarily suggesting it be part of this PR.

**Comment by dhull** [comment]
On NIF vs BIF speed: Two things that would help speed Jiffy up are:

* A NIF version of `tag_val_def` so that Jiffy could switch on a term's type  instead of calling each conversion function in turn on the term until one  succeeds.

* A way to turn off garbage collection. Since Jiffy needs to return back to the emulator to yield, it has to ensure that if garbage collection happens  that none if its in-progress work will be lost. This requires that Jiffy  construct Erlang terms to hold its state (the `enif_make_list_cell` calls I mentioned above)  and return that state back to the VM level. The BIF, by comparison, can turn off garbage collection and just shove the partially-constructed return value in a C struct and not have to worry about them being garbage collected when it gets to run again.

**Comment by hauleth** [comment]
Only reason I see to have JSON in the core is to support [JER](https://www.oss.com/asn1/resources/asn1-papers/Overview%20of%20JER.pdf) in `asn1ct`, however I think it would be possible to implement such with external libraries by using some kind of callback module.

**Comment by garazdawi** [comment]
> * A way to turn off garbage collection. Since Jiffy needs to return back to the emulator to yield, it has to ensure that if garbage collection happens  that none if its in-progress work will be lost. This requires that Jiffy  construct Erlang terms to hold its state (the `enif_make_list_cell` calls I mentioned above)  and return that state back to the VM level. The BIF, by comparison, can turn off garbage collection and just shove the partially-constructed return value in a C struct and not have to worry about them being garbage collected when it gets to run again.

Do you have any numbers/guesses on how likely it is that the process has to yield when encoding? Doing lazy creation of the yield state could be very beneficial if it is very unlikely that a yield has to happen.

**Comment by dhull** [comment]
> > * A way to turn off garbage collection. Since Jiffy needs to return back to the emulator to yield, it has to ensure that if garbage collection happens  that none if its in-progress work will be lost. This requires that Jiffy  construct Erlang terms to hold its state (the `enif_make_list_cell` calls I mentioned above)  and return that state back to the VM level. The BIF, by comparison, can turn off garbage collection and just shove the partially-constructed return value in a C struct and not have to worry about them being garbage collected when it gets to run again.
> 
> Do you have any numbers/guesses on how likely it is that the process has to yield when encoding? Doing lazy creation of the yield state could be very beneficial if it is very unlikely that a yield has to happen.

The `term_to_json` code is structured very much like the `term_to_binary` code. I created a `T2JContext` very like to `term_to_binary`'s `TTBContext`, and it uses a `ErtsWStack` for its state. If the function never needs to yield then it avoids some yield-state-creation logic. (See the [code in the `erts_term_to_json_int`](https://github.com/dhull/otp/blob/1414a4cf10e2ed1caf468afedab4b619aef7e6b9/erts/emulator/beam/json.c#L235) function.)

The `enc_json_int` function bumps reductions in essentially the same way that `enc_term_int` does: one reduction for each 32 terms or 256 binary bytes converted.

I haven't ever measured what fraction of the time that `term_to_json` ends up yielding on my own data. If you look at the [poison benchmark data](https://github.com/devinus/poison/tree/master/bench/data) you'll find some (govtrack, json-generator) that are going to yield a lot and others (blockchain) not so often. The [benchmark results](https://github.com/dhull/otp/blob/1414a4cf10e2ed1caf468afedab4b619aef7e6b9/json.org#encoding) are in the json.org file.

**Comment by dhull** [comment]
> Well, it supports `return_maps` for example, but also mentions that it "does not support Jiffy’s `dedupe_keys` option" nor does it have `strict_keys`, so you still don't know what wins or not for that case, but you know maps can't have duplicate values so a decision is made implicitly somewhere.

[My document](https://github.com/dhull/otp/blob/1414a4cf10e2ed1caf468afedab4b619aef7e6b9/json.org#objects) mentions that my code calls [`erts_map_from_validated_list`](https://github.com/dhull/otp/blob/1414a4cf10e2ed1caf468afedab4b619aef7e6b9/erts/emulator/beam/erl_map.c#L276) to create the map. I didn't look carefully enough before, but this is the same code that is called by `maps:from_list/1` so I can make the same guarantee that it does, which is that the last value associated with a duplicate key will be the one that is kept.

**Comment by AndrewDryga** [comment]
FYI. There are a nice library and research for making extremely fast JSON parsers using SIMD instructions, in case we would still decide to write a NIF: https://github.com/lemire/simdjson.

**Comment by lpgauth** [comment]
@andrewdryga mixing SIMD workload with non-SIMD workload is not recommended. This could affect negatively the performance of the whole system.

e.g. https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/

**Comment by AndrewDryga** [comment]
@lpgauth I believe we already use SIMD instructions for optimizations, correct me if I'm wrong.

**Comment by KennethL** [comment]
We have discussed this pull request in the OTP team and we have the following comments and conclusions:

We stick to our standpoint which we gave when the EEP-0018 was new (2010):
"_Since we have introduced NIFs as a way to implement and dynamically
load parts of the functions in a
module in C there is no need to introduce new BIFs (Built In
Functions) for encoding /decoding between Erlang terms and JSON.
BIF's are mostly regarded as part of the language. 
Now we don't need a new BIF just because something is implemented in C 
(for efficiency reasons)._"

We agree that it is important to have JSON encode/decode functions with
high performance. There are a number of implementations already available
as separate applications. Jiffy is one using a NIF implementation and
after a quick look we see that there is room for optimizations.

We are convinced that a NIF implementation can come very close to the
perfomance you get with these BIFs even without new functionality in the
NIF API. Should it be necessary we are very interested in helping out with
the performance of a NIF implementation.
We can even think of adding functionality in the NIF API if that should
be necessary. The performance gap between a BIF and a NIF should not be
that big.
We are for example planning to add a function `enif_term_type` to the
NIF API in OTP 22, but we think this will only have marginal
impact on the performance. 

We also think for now that the JSON implementation should continue to
be a separate component (not part of OTP).

So we really appreciate this pull request which we think is valuable as an eye
opener regarding performance and propose that the code is reused in a new
JSON NIF implementation or contributed to some existing JSON component as
a way to improve performance.

We then reject the pull request.

**Comment by okeuday** [comment]
@KennethL Will the OTP team move the PCRE integration from a BIF to a NIF to help prove the same performance is possible with either?  While it may seem off-topic, both JSON encoding/decoding and PCRE integration look like they have the same problems as NIFs (trouble yielding/bumping-reductions and trouble with efficient env/struct use), which is why I am asking.

**Comment by vans163** [comment]
The modulation of the BIF / preloaded modules that was talked about for OTP22 (or was it OTP21) comes to mind.  A way to configure Erlang with exactly what you need, as kind of a level above the runtime.

There is NO REASON for example openssl should be statically linked to the runtime, that should be a seperate NIF.

**Comment by KennethL** [comment]
@vans163 van there is no linking of openssl to the runtime (the Erlang VM) and has never been.
The only dependency there is to Openssl is via the crypto application which implements a number of NIFs
which are dynamically linked towards libcrypto from Openssl (or libressl).

**Comment by KennethL** [comment]
@okeuday 
> @KennethL Will the OTP team move the PCRE integration from a BIF to a NIF to help prove the same performance is possible with either? While it may seem off-topic, both JSON encoding/decoding and PCRE integration look like they have the same problems as NIFs (trouble yielding/bumping-reductions and trouble with efficient env/struct use), which is why I am asking.

No the OTP team will not move the PCRE integration from BIF to NIF simply because it will just be
useless extra work at this point. 
When we already have PCRE integrated as BIFs there is nothing to gain by changing it to NIFs.
If we where about to integrate a new regexp library now we would most probably do it as NIFs but for
PCRE there is no point in doing that.
PCRE is not integrated as is. It is modified to allow yielding in order to not block the schedulers too long.
The same has to be done in a NIF unless dirty schedulers are used. Dirty schedulers will imply that
each call to a regexp operation will be scheduled on another thread. I don't think our users want the performance degradation caused by that.

**Comment by lpgauth** [comment]
@KennethL @garazdawi @rickard-green How do you suggest we move forward? What is the OTP team plan to bridge the gap between NIF and BIF (other than `enif_term_type`)? Do you plan on helping building a new JSON NIF?

I'm thinking we should start a Slack channel and organize a community around this initiative... What do you think @dhull? I'd rather not maintain an OTP fork :/

**Comment by josevalim** [comment]
@lpgauth I think the next step is to verify if there is really a gap between NIFs and BIFs and understand the root cause for the gap. We know that this implementation is faster than jiffy but we can't be sure if the difference is all due to NIFs vs BIFs, as they are different implementations altogether.

My understanding is that the OTP team is very interested in improving the NIF API if necessary to get better performance but at the moment no one is sure what exactly has to be done.

So maybe converting the current patch to a NIF and running more benchmarks could lead to more insights and more actionable input to the OTP team?

**Comment by KennethL** [comment]
@josevalim from the OTP team side we think it would be a good idea to optimize the Jiffy NIFs as Jiffy is a well known component with a well known API.
We could then compare that version of Jiffy with the BIF implementation and with old Jiffy (because we know the relation between the BIF impl. and old Jiffy). From that we could see if we need to do something more in otp to make the NIF implementation even faster.

If someone is interested working with optimization of Jiffy we are interested in helping out.
John at the OTP team has already looked at possible optimizations in Jiffy and will come back with some ideas tomorrow.

**Comment by jhogberg** [comment]
Aside from the things already mentioned in this thread, I think the main reason Jiffy is slower is because it's been given less attention; compare [enc_long](https://github.com/davisp/jiffy/blob/ee8b48cb448a999e1fddbb5e2e32e7dfe33acf5c/c_src/encoder.c#L401) with the same code in the encode BIF. The former is basically a wrapper around `snprintf`, while the latter calls a highly optimized integer-only routine.

String encoding is also less efficient; [enc_string](https://github.com/davisp/jiffy/blob/ee8b48cb448a999e1fddbb5e2e32e7dfe33acf5c/c_src/encoder.c#L244) walks through the string once to get the length (validating _each byte_ as it goes) and then does so again to encode the data. The BIF handles it in a single sweep and encodes several bytes at once, only bailing out if the first byte of a codepoint is illegal.

Jiffy is also split into multiple modules and is compiled without link-time optimization, so trivial functions like `utf8_esc_len` or `should_yield` don't get a chance to be inlined, whereas the BIF is in a single file.

These examples probably don't make much of a difference on their own, but wherever I look it's clear that the BIFs have been given more attention and I believe that Jiffy could be much faster if we put as much effort into it.

I don't have any silver bullets but a few things come to mind:

* When encoding, keep the state stack in a plain C array instead of an Erlang list and call `enif_make_tuple_from_array` when yielding.
* Move to a dirty scheduler when yielding so we won't have to care about it again.
   
   Most of the cost of a dirty NIF call comes from having to reschedule the process, but we're _already_ rescheduling ourselves when yielding so moving to a dirty scheduler doesn't cost much extra at that point. We still have to pay the cost of jumping back to a normal scheduler after we return, but we no longer need to yield several times on large inputs, and we hopefully don't have to yield in the first place.
* When decoding, look at the size of the input and move to a dirty scheduler if it's "large enough," otherwise run it on a normal scheduler. In neither case will we need to care about yielding.
* Turn on link-time optimization when available. It likely won't make a big difference, but why not?

**Pull request closed without merging**
