### PR TITLE
WIP Pass map as credentials

### PR DESCRIPTION
**Pull request by hauleth**
This is needed due to fact that Erlang do not provide any way to check size of `pid_t`, `uid_t`, and `gid_t` which is needed for proper handling of the data passed to the socket. This allows user to pass map containing 3 fields - `pid`, `uid`, and `gid` that will be changed to the `struct ucred` before passing via socket. It also decodes data that come out of the socket when possible.

Ref [ERL-1201](https://bugs.erlang.org/projects/ERL/issues/ERL-1201)

### CODE REVIEW

**Comment by bmk** [comment]
Hi,

First, thanks for the contribution.
But, ..., I had some issues. Basically two things:
1) The types of the fields of the ucred struct was
   pid:         sint32
   uid and gid: uint32
   This effected the code when those values where 
   converted from / to ENIF types.
2) Missing blocks ({}) in the switches.
    Which, at least on my machine (Linux Mint 19.3) caused failures.

I have pushed this into a branch on my public repo:

https://github.com/bmk/otp/tree/bmk/erts/esock/20200323/pass-map-as-creds

Also, we are currently trying to push RC2 out the door so it may be a couple of
days before we can take this branch into testing.
Also, as it includes changes to socket.erl, we also need to augment this with
a build of socket.erl (preloaded). I will add this to my branch before including
it into the nightly builds.

**Comment by hauleth** [comment]
@bmk I understand. I need to study BSD sockets a little bit more to check how this can be handled there as each of the *nixes handles that a little bit differently. For example there is no `struct ucred` on BSDs.

**Comment by bmk** [comment]
The checking could be done by adding to the erts/configure.in:

```
AC_CHECK_MEMBERS([struct ucred.pid,
                                       struct ucred.uid,
                                       struct  ucred.gid], ...)
```

But, if they do not have `struct ucred`, do they have `SCM_CREDENTIALS`?

**Comment by bmk** [comment]
On FreeBSD, OpenBSD and NetBSD its in /usr/include/sys/ucred.h

FreeBSD 12.1:
```
struct ucred {
        u_int   cr_ref;                 /* reference count */
#define cr_startcopy cr_uid
        uid_t   cr_uid;                 /* effective user id */
        uid_t   cr_ruid;                /* real user id */
        uid_t   cr_svuid;               /* saved user id */
        int     cr_ngroups;             /* number of groups */
        gid_t   cr_rgid;                /* real group id */
        gid_t   cr_svgid;               /* saved group id */
        struct uidinfo  *cr_uidinfo;    /* per euid resource consumption */
        struct uidinfo  *cr_ruidinfo;   /* per ruid resource consumption */
        struct prison   *cr_prison;     /* jail(2) */
        struct loginclass       *cr_loginclass; /* login class */
        u_int           cr_flags;       /* credential flags */
        void            *cr_pspare2[2]; /* general use 2 */
#define cr_endcopy      cr_label
        struct label    *cr_label;      /* MAC label */
        struct auditinfo_addr   cr_audit;       /* Audit properties. */
        gid_t   *cr_groups;             /* groups */
        int     cr_agroups;             /* Available groups */
        gid_t   cr_smallgroups[XU_NGROUPS];     /* storage for small groups */
};

```
OpenBSD 6.6:
```
struct ucred {
        u_int   cr_ref;                 /* reference count */

/* The following fields are all copied by crset() */
#define cr_startcopy    cr_uid
        uid_t   cr_uid;                 /* effective user id */
        uid_t   cr_ruid;                /* Real user id. */
        uid_t   cr_svuid;               /* Saved effective user id. */
        gid_t   cr_gid;                 /* effective group id */
        gid_t   cr_rgid;                /* Real group id. */
        gid_t   cr_svgid;               /* Saved effective group id. */
        short   cr_ngroups;             /* number of groups */
        gid_t   cr_groups[NGROUPS_MAX]; /* groups */
};
```

NetBSD 9.0:
```
struct uucred {
        unsigned short  cr_unused;              /* not used, compat */
        uid_t           cr_uid;                 /* effective user id */
        gid_t           cr_gid;                 /* effective group id */
        short           cr_ngroups;             /* number of groups */
        gid_t           cr_groups[NGROUPS_MAX]; /* groups */
};
```

So, this looks like it will involve a bit of work...

**Comment by hauleth** [comment]
Ok, it seems as my misunderstanding as macOS also has `ucred`:

```c
struct ucred {
	LIST_ENTRY(ucred)       cr_link; /* never modify this without KAUTH_CRED_HASH_LOCK */
#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L && !defined(__STDC_NO_ATOMICS__)
	_Atomic u_long          cr_ref;  /* reference count */
#elif defined(__cplusplus) && __cplusplus >= 201103L
	_Atomic u_long          cr_ref;  /* reference count */
#else
	volatile u_long         cr_ref;  /* reference count */
#endif

	struct posix_cred {
		/*
		 * The credential hash depends on everything from this point on
		 * (see kauth_cred_get_hashkey)
		 */
		uid_t   cr_uid;         /* effective user id */
		uid_t   cr_ruid;        /* real user id */
		uid_t   cr_svuid;       /* saved user id */
		short   cr_ngroups;     /* number of groups in advisory list */
		gid_t   cr_groups[NGROUPS];/* advisory group list */
		gid_t   cr_rgid;        /* real group id */
		gid_t   cr_svgid;       /* saved group id */
		uid_t   cr_gmuid;       /* UID for group membership purposes */
		int     cr_flags;       /* flags on credential */
	} cr_posix;
	struct label    *cr_label;      /* MAC label */
	/*
	 * NOTE: If anything else (besides the flags)
	 * added after the label, you must change
	 * kauth_cred_find().
	 */
	struct au_session cr_audit;             /* user auditing data */
};
```

However this is only for in-kernel use. The externally available representation is:

```c
/*
 * This is the external representation of struct ucred.
 */
struct xucred {
	u_int   cr_version;             /* structure layout version */
	uid_t   cr_uid;                 /* effective user id */
	short   cr_ngroups;             /* number of advisory groups */
	gid_t   cr_groups[NGROUPS];     /* advisory group list */
};
```

Also according to the [FreeBSD test suite](https://github.com/freebsd/freebsd/tree/master/tools/regression/sockets/unix_cmsg) the structs used for authentication are `cmsgcred` and `socketcred` depending on how credentials are passed.

**Comment by bmk** [comment]
Just so you know, the preloaded socket module has been renamed to prim_socket.erl
The 'public' interface module (socket.erl) has been moved to kernel.

**Comment by hauleth** [comment]
@bmk yes, I am aware, however I need to find a way to make this code platform independent, so it would be possible to use it on Linux and BSD-likes as each of these use different struct to pass FDs.

**Comment by bmk** [comment]
It looked like you pushed a 'socket.erl' into preloaded/src. But that module is now named
'prim_socket.erl'. The "real" socket module is in kernel.
Not sure how to resolve that. Manually "merge" your socket stuff into prim_socket and kernel/socket
respectively?

**Comment by hauleth** [comment]
Yeah, I will be rebasing that manually. This one is still WIP so I will convert it to draft to mark that.

**Comment by bmk** [comment]
This has been idle for a long time.
Is it ok to close this or do you have anything new?

**Comment by hauleth** [comment]
@bmk not yet. We can close it for now and I will reopen it as soon as I will have updates there

**Pull request closed without merging**
