### PR TITLE
Optimize printing of floating point numbers

### PR DESCRIPTION
**Pull request by bjorng**
Optimize printing of floating point numbers in `io:format/2` by
pre-calculating the powers of 10 and storing them in a a persistent
term. The pre-calculation is done the first time a floating point
number is printed.

### CODE REVIEW

**Comment by michalmuskala** [comment]
Wouldn't it make sense to just have them as a literal value in the module? Alternatively in a separate file that is `-include`d so that it does not obscure the logic?

**Comment by bjorng** [comment]
> Wouldn't it make sense to have them as a literal value in the module? Alternatively in a separate file that is -included so that it does not obscure the logic?

An included file would make sense, yes, to avoid obscuring the logic.

But the included file would either need to be generated beforehand and committed to the repository, increasing the size of the repository. That seems unnecessary and wasteful. Otherwise, we would have to run a script at build time to generate the include file. That would be possible, but seems a lot of work for a minor optimization.

Therefore, it made more sense to add a few lines of code to achieve this minor optimization. The alternative would be to not make the optimization. The hassle with an include file is too heavy price.

**Comment by garazdawi** [comment]
I think that this change causes the persistent_term_SUITE to fail as it adds terms to the store that it expects to be empty.

**Comment by bjorng** [comment]
@garazdawi Yes, it is a bug in the test suite. I tried to handle the case that there were preexisting persistent terms not created by the test suite, but evidently I botched it.

**Comment by bjorng** [comment]
After discussions in the OTP team, we decided that we will not do the optimization in this way.

Since this was an opportunistic optimization (easy to make, but not based on a real-world use case), we will postpone the optimization until there is a real-world need for it.

**Pull request closed without merging**
