### PR TITLE
Add option for using TLS distribution over IPv6

### PR DESCRIPTION
**Pull request by legoscia**
Add the `-ssl_dist_ipv6` option for using IPv6 sockets for TLS distribution. Not sure if this is the best option name; I'm open to other proposals.

This patch depends on the patch in #871, though they are logically unrelated. I could separate this one out if desired.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by RaimoNiskanen** [comment]
This should not be handled through an option to inet_tls_dist, but through a new distribution module inet6_tls_dist.  Have a look at how inet_tcp_dist and inet6_tcp_dist in kernel on the maint branch have recently been restructured to reuse code.

And please make this patch independent of #871 since that should also be solved in a slightly different way.

**Comment by legoscia** [comment]
I pushed a new change, making `inet_tls_dist` more general and adding a new module `inet6_tls_dist` that reuses the code.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by legoscia** [comment]
I rebased this onto the current maint branch.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
This was meged to OTP-18.3

**Pull request closed without merging**
