### PR TITLE
Quote the atom `maybe` in the `ssl` application

### PR DESCRIPTION
**Pull request by belltoy**
Quote the `maybe` atoms and functions in the `ssl` application.

### CODE REVIEW

**Comment by u3s** [comment]
Can you agree on CLA please ? see automated comment above.

**Comment by belltoy** [comment]
> Can you agree on CLA please ? see automated comment above.

👌🏼

**Comment by u3s** [comment]
upon review of code it was proposed to rename `maybe` instead of quoting which looks ugly in source.
_Maybe_ `maybe` could become `maybe_do` instead of `'maybe'` :-) ?

**Comment by belltoy** [comment]
> upon review of code it was proposed to rename `maybe` instead of quoting which looks ugly in source.
> _Maybe_ `maybe` could become `maybe_do` instead of `'maybe'` :-) ?

Sounds good. Updated and amended commit.

**Pull request merged**
