### PR TITLE
ssl: Enhance error message

### PR DESCRIPTION
**Pull request by IngelaAndin**

### CODE REVIEW

**Review by dgud — APPROVED** [review]
Tests?

**Comment by IngelaAndin** [comment]
The code is covered by the existing test, however we do not normally match on the description part.

**Comment by Sinc63** [comment]
Thanks for this improvement. I look forward to debugging my next instance of this after upgrading. 

I expect my next request might be to enhance the output for Unknown_CA.

**Comment by IngelaAndin** [comment]
@Sinc63 that might be trickery to implement and give good information about as it means we where not able to verify or recreate a verifiable certificate chain that ends with a certificate that we trust.

**Pull request merged**
