### PR TITLE
Optimize proc_lib:raw_initial_call(Pid)

### PR DESCRIPTION
**Pull request by mikpe**
Monitoring tools sometimes need to call proc_lib:translate_initial_call/1 to get a more useful version of the initial_call of a process.  Currently that requires retrieving the _entire_ dictionary of the target process, even though only a single usually small entry is needed.  This updates the VM to support retrieving that one entry directly, and then updates proc_lib to do so instead of retrieving the entire dictionary.

At the moment this is an RFC because:

1. Ideally the VM should support process_info(Pid, {dictionary,Key}) queries, but the implementation of process_info/2 really wants info keys to be plain atoms not composite terms.

2. Alternatively one could add erlang:get/2, taking Pid and Key.  This is nicely general, but unfortunately requires copying much of the process_info/2 implementation.

3. For this RFC I opted for a simple solution, namely to add '$initial_call' as an info item key to process_info/2.  It's however entirely specific to the proc_lib use case.

So this is an RFC to highlight the use-case and solicit opinions on how to solve it properly.

### CODE REVIEW

**Comment by essen** [comment]
:+1: 

Similar case with retrieving `'$ancestors'` for figuring out where in the supervision tree an arbitrary process sits in. A general case would be nice as that would help with processes that put useful metadata in the dictionary.

If going for a general case, maybe don't limit it to one key, allow querying multiple keys at once.

**Comment by k32** [comment]
Looks good to me. But it's harder to remove features than to add, so I wonder if going straight for alt. 1 is actually cheaper.

**Comment by fenollp** [comment]
Aren't 1. or 2. actually breaking Process Dictionary usage?

From the docs:

> 12.9  Process Dictionary
> Each process has its own process dictionary, accessed by calling the following BIFs: [...]

one can assume that no other process can access (read/write) its p.dict.

Wouldn't the introduction of either 1. or 2. clash with this semi-directly documented assumption?

I think one can find code like http://erlang.org/pipermail/erlang-questions/2007-April/026333.html in the wild, which makes the assumption that no racy `erlang:get(Pid, Key) where Pid /= self()` action can ever happen.

How would synchronization of calling `erlang:get/2` from one process to another be defined? If this stays undefined, how could one trust this call at all?

**Comment by mikpe** [comment]
Your assumption is incorrect: a process' Process Dictionary can _already_ be read by another process using process_info/2.  This PR is about optimizing the common case where one wants just a single value (or perhaps a few) rather than the entire dictionary.

**Comment by garazdawi** [comment]
If this optimization is to be merged, then only suggestion 1 or 2 are options. Which ones of those is the best, I'm not sure.

Also, any implementation that does this needs to make sure that the process from which we read the process dictionary does not wake up from hibernation.

We'll need to discuss this internally before deciding and given that summer is approaching it may be a while until we can reach a decision.

**Comment by mikpe** [comment]
Force-pushed an update to implement option 1.  You can now call process_info/2 with one or more {dictiionary,Key} items.  There is one limitation still: those Keys must be immediates, e.g. atoms or fixnums; I need to marshal non-immediate Keys via an intermediate buffer to support non-immediate Keys in the one-process-signals-another case.  That's doable but not implemented yet.

**Comment by binaryseed** [comment]
Hello folks! This morning during the EEF Observability Working Group, we talked about this PR (specifically the ability to get one key from another process dictionary) as a potential way to facilitate context propagation for distributed tracing...

https://docs.google.com/document/d/18JVh6ICLyRCJBpRVIXwcR1fb-K4qRX3WHYgtM7mFx2U/edit#heading=h.3iwpkpo8alw3

I'm wondering what it'd take to push that forward, it seems like it'd be a useful addition..

cc @tsloughter @josevalim

**Pull request closed without merging**
