### PR TITLE
add aes ecb to crypto library

### PR DESCRIPTION
**Pull request by andreaTP**
In man pages you say that it is supported but I cannot find it so this could be the implementation.
If anything is missing to the implementation, please, just ask and I will provide.

p.s.
Any plan to move the crypto library to a dirty-schedulers implementation?

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
I guess this API can be a bit confusing. It's a mixture of old deprecated functions that has been replaced by new generic function that can handle different types of hash/ciphers/algorithms.

1. Remove all your -export statements. This patch should not add any new exported functions.
2. Remove all your -deprecated statements. This patch should not deprecate any functions.
3. Remove aes_ecb_encrypt and aes_ecb_decrypt from FUNC_LIST.
4. Add aes_ecb to ciphers in function supports.
5. Add aes_ecb to -spec for block_decrypt/3.
6. Add space before all words "according" in docs, even in old block_encrypt/4 and block_decrypt/4.

7. Suggestion: Remove aes_ecb_encrypt/2 and aes_ecb_decrypt/2 and instead call aes_ecb_crypt/3 directly from block_encrypt/3 and block_decrypt/3.

**Comment by andreaTP** [comment]
Aligned as asked the first 6 points, about 7 I leave it "as is" 'cause the implementation is more close to "des_ecb_crypt" one and also more readable.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by marcusarendt** [comment]
merged on master

**Pull request closed without merging**
