### PR TITLE
Maps API additions

### PR DESCRIPTION
**Pull request by psyeugenic**
Adds the functions `maps:take/2` and `maps:update_with/3,4` to the maps module:

```erlang
-spec take(Key,Map1) -> {Value,Map2} | error when
    Key :: term(),
    Map1 :: map(),
    Value :: term(),
    Map2 :: map().
```
`maps:take/2` removes a Key and the value associated to it from a Map and returns a tuple with the removed Value and a new Map without the association. If the Key does not exist `error` is returned.

This is the equivalent of doing a `maps:find/2` and then `maps:remove/2` but `maps:take/2` should be faster.

```erlang
-spec update_with(Key,Fun,Map1) -> Map2 when
      Key :: term(),
      Map1 :: map(),
      Map2 :: map(),
      Fun :: fun((Value1 :: term()) -> Value2 :: term()).

-spec update_with(Key,Fun,Init,Map1) -> Map2 when
      Key :: term(),
      Map1 :: Map1,
      Map2 :: Map2,
      Fun :: fun((Value1 :: term()) -> Value2 :: term()),
      Init :: term().
```
This is the Maps equivalent to `dict:update/3,4`. No special performance concern with `maps:update_with/3,4` has been taken.

### CODE REVIEW

**Comment by leoliu** [comment]
There are two typos in the doc. `does not exists` should be `does not exist` and `associated to` `associated with`. I am not a native English speaker so take it with a grain of salt. Thanks.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by psyeugenic** [comment]
@leoliu Thank you, I will look over those.

@jlouis Any concerns regarding function names? :smile:

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
