### PR TITLE
Add options for creating reproducible tars

### PR DESCRIPTION
**Pull request by ericmj**
I have tested locally that created tarballs always have the same checksum, but it's difficult to test because extracted tarballs only preserve the `mtime` from the archive. We also cannot test for non-empty directories and links because file_info is never written for them.

Any guidance in improving the tests for this would be appreciated.

### CODE REVIEW

**Comment by ericmj** [comment]
Any news on this? It would be great to get this into OTP 21 if possible.

**Comment by uabboli** [comment]
We've planned to look into it some time next month, and to include it in OTP 21.

**Comment by uabboli** [comment]
Thank you! Looks good in general. A few minor things need be fixed,
though.

The length of lines should be well under 80 characters. Applies to the
`Option` type in erl_tar.xml and the last lines of
tar_SUITE:apply_file_info_opts().

The initiation of the `#add_opts.read_info` is also too wide.
Introducing a new function, for example:

```erlang
   apply_file_info_opts_fun(Options) ->
       fun(F) ->
	       apply_file_info_opts(Options,
				    file:read_file_info(F, [{time, posix}]))
       end.
```

would avoid code duplication as well as open up for shorter lines:

```erlang
	RF = apply_file_info_opts_fun(Options),
	Opts = #add_opts{read_info=RF},

    add_opts([dereference|T], AllOptions, Opts) ->
	RF = apply_file_info_opts_fun(AllOptions),
	add_opts(T, AllOptions, Opts#add_opts{read_info=RF});
```

The fields of `#add_opts{}` in erl_tar.hrl should line up.

The documentation is a bit too terse. An example:

```xml
            <p>Sets the last time, as
	      <seealso marker="erts:time_correction#POSIX_Time">
              POSIX time</seealso>, when the file was read. See also
              <seealso marker="kernel:file#read_file_info/1">
              <c>file:read_file_info/1</c></seealso>.</p>
```

Finally, you need to sign the license.

**Comment by ericmj** [comment]
I signed the license and made changes based on your feedback.

**Comment by uabboli** [comment]
Merged commit b6d0807aebf676063ab522833ded99b2a7fb31c9 into erlang:master.

**Pull request closed without merging**
