### PR TITLE
ssl: Use new socket:monitor/1

### PR DESCRIPTION
**Pull request by IngelaAndin**
To be able to fully work with new gen_tcp socket backend.

### CODE REVIEW

**Comment by bmk** [comment]
Why don't you use inet:monitor/1?

**Comment by IngelaAndin** [comment]
@bmk as I did not know it existed, that is why you should review the code! Do I understand it correctly that it will work for both new and old sockets and that I then can skip the is_port guard in the original code?

**Comment by bmk** [comment]
Yes, it should work for "all" kinds of sockets.
The function socket:monitor/1 *is* official, but is intended for when you *only* work with 'socket' sockets.

**Comment by IngelaAndin** [comment]
Replaced by #5050

**Pull request closed without merging**
