### PR TITLE
gen_statem improvements OTP-13929: Named Timeouts

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
This is a branch currently running in our daily builds as to-be-merged to 'maint' upcoming OTP-19.2.

It contains some documentation, type and diagnostics improvements.  Plus a rewrite of the timer handling and the last commit implements Named Timeouts.

The rewrite caused a very small semantic change in how timeout zero Event Timers are handled that I think you will have to try hard to notice.  I introduced this change because when having multiple timers it became clear that the old semantics were illogical.

Named Timeouts are started with the action `{{named_timeout,Name},Time,Msg}`, but it could just as well be `{{timeout,Name},Time,Msg}` except that it would be confusingly similar to `{timeout,Time,Msg}` which is the Event Timeout that gets cancelled by any other event, whilst Named Timeouts has no automatic cancelling.

I thought that such different features should be named differently, therefore the atom `named_timeout`.  Opinions?

One may also argue that Named Timeouts is a feature we could and therefore should live without.  I think they are handy enough to be worth having.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by ferd** [comment]
I don't think my position on this has changed much since last time -- mostly for the flexibility of things, using regular timers would still be my means of choice of doing this.

**Comment by okeuday** [comment]
@RaimoNiskanen I think it is valuable to have a named timeout concept, to allow `gen_statem` timer usage to be more explicit, despite the extra complexity (which should be mainly in the `gen_statem` impl, not the documentation or semantics), since it allows the name to be distinct from the `Msg` data.  However, if this concept exists in `gen_statem`, it seems best to not use the `named_timeout` atom, and instead just allow a 2 element tuple for both `timeout` and `state_timeout`.  That way, the actual functionality is the same, the only difference is that a name is tacked onto the timer (i.e., from the perspective of the developer).

The named timeout concept may be a bit unfamiliar, since it doesn't exist elsewhere, but it should help make the implementation of a state machine with `gen_statem` easier to follow.  However, I am suggesting the feature would work for both `timeout` and `state_timeout`.

The argument against named timeouts is that they don't necessarily add extra functionality, unless there is the option to cancel a named timeout (I don't see this functionality in this pull request).  Otherwise, it would be easy to say that named timeouts are too similar to using a name within the `Msg` data.  So, we probably also need the ability to cancel the timeout, by only passing the name.

**Comment by okeuday** [comment]
@RaimoNiskanen The `named_timeout` atom usage is meant to show that the semantics are separate from `timeout` and my comment above is blurring the difference by asking for named `timeout` and `state_timeout` usage.  If we could use the `timer` atom instead of the `named_timeout` atom, and be able to name anything, as well as cancel anything with a name, that would probably be the most flexible (while perhaps annoy the person doing the gen_statem changes).  So, that would allow `{timeout, Name}` and `{state_timeout, Name}` with the existing `timeout` and `state_timeout` semantics, and then add `{timer, Name}` by just changing the name from `named_timeout` to `timer` (with the addition of being able to cancel anything with a name explicitly).

**Comment by vans163** [comment]
@okeuday using infinity as the timeout value cancels the timer.

In terms of semantics my natural instinct wanted to do [{timeout, TimeoutName, Timeout}, {timeout, TimeoutName2, Timeout2}].  This way now 2 named_timeout are set.  But this does not allow to pass any metadata.

A 4 size tuple or a 3 size work:
{timeout, TimeoutName, Metadata, Timeout}
{ {timeout, TimeoutName}, Metadata, Timeout}

And yea what is the difference between named_timeout and timeout then?

**Comment by RaimoNiskanen** [comment]
@ferd: Thank you for your opinion. I share it (today) to 25%, and to 75% think `named_timeout` is useful to improve readability by shortening the state machine implementation (for say hopefully 90% of the use cases)...

@okeuday:

Having multiple event timeouts `{timeout,Name}` does not make any sense since when the first timeout `Name1` happens all others are cancelled because an event arrived.  Roughly the same applies to multiple state timeouts.  For both these timer classes the shortest will cancel the others.  Plus the implementation would have to traverse all timers to find the `{state_timeout,_}` ones for cancellation during a state change.  I think it is prettier to just have to look up the one `state_timeout`.

Cancelling a named timeout works as for any timeout: you set it to 'infininity'.  It is documented in this PR.  As well as restarting for one particular `Name` by setting it to a new `Time`.  Without the separation into `Name,Msg`, and the possibility to set/restart/cancel by `Name` instead of having to track each `TimerRef`, named timers contributes with nothing over regular Erlang timers.

Yes you are right - the tag `named_timeout` is intended to highlight that it has different semantics from `timeout` and `state_timeout`.  The `_timeout` suffix is intended to indicate that it is a feature with great similarity to `timeout` and `state_timeout` so I think `timeout` should be a part of its name.

**Comment by okeuday** [comment]
@RaimoNiskanen It still seems possible to want to use `timeout` and `state_timeout` with separate names, even when they are cancelled together.  Cancelling by using `infinity` isn't really explicit though, since you are saying something will happen after an infinite amount of time, you aren't saying something is really really cancelled and will never happen in the future.  Using the `named_timeout` name helps to isolate this naming feature, preventing it from being applicable to other timeouts which is the reason for a more generic `timer` name, since this is more similar to automatic management of a timer than a single `timeout` provided by other OTP behaviours.  This is just my opinion and everyone has an opinion, but you are in charge of implementation :-)

**Comment by RaimoNiskanen** [comment]
@okeuday: If you can find a use case for named `timeout` and `state_timeout` I am eager to hear, but right now I can not foresee one, at least not one that `named_timeout` would not cover.

I agree that cancelling by using `infinity` is not particularly explicit, but the only reasonable interpretation of setting a timeout to `infinity` is that it is equivalent to not setting a timeout so I documented that.  Therefore restarting a timeout with `infinity` must be equivalent to cancelling a timeout, so I documented that too.

So there is a way of cancelling a timeout, and to now create a more explicit way to e.g by setting it to `cancel` would, I think, be more confusing than useful.  It has been suggested that a 'cancel' operation would differ in semantics by crashing if no timeout with that name is active, but I am still not convinced that such an operation is needed.  I fear that most programmers will use `infinity` of pure laziness since they know it will not crash, and then we have a seldom used almost equivalent operation `cancel` which is confusing.  When you read someone else's code you will have to look it up in the manual, read and understand both `infinity` and `cancel`, find the difference and figure out if it is correct in this case.

Regarding naming.  You suggest having `timeout`, `state_timeout`, and `{timer,Name}` to indicate that this new feature is about handling `erlang:start_timer/3,4` through a `Name` while I have proposed `timeout`, `state_timeout`, and `{named_timeout,Name}` to indicate the similarity of this new feature to the already existing timeouts.  I see your point now, and we will consider it!

**Comment by RaimoNiskanen** [comment]
@vans163:  The difference between `timeout` and `named_timeout` lies, besides the `Name`, in the auto cancelling that event timeouts have (also state timeouts) while named timeouts do not.

I chose the action as `{{named_timeout,Name},Time,Msg}` since we now get:

Action | Event
------- | -------
`{timeout,Time,Msg}` | `(timeout, Msg, ...)`
`{state_timeout,Time,Msg}` | `(state_timeout, Msg, ...)`
`{{named_timeout,Name},Time,Msg}` | `({named_timeout,Name}, Msg, ...)`
I.e: `{Type,Time,Msg}` | `(Type, Msg, ...)`

which I think is a neat pattern.

**Comment by okeuday** [comment]
@RaimoNiskanen I agree that using the `cancel` atom alongside the `infinity` atom doesn't improve the situation, I just had hoped that a separate cancel-timeout operation might be available, but I understand that usage of the `infinity` atom is the most succinct approach with these semantics.  The discussion about `timeout` and `state_timeout` allowing a name parameter too isn't very critical, since matching can already occur on the `Msg` term to describe the timeout's context.  However, adding names to all the timeouts gen_statem supports doesn't seem bad necessarily (it keeps the timeout features similar), nor does it seem like something that wouldn't get used.

I am mainly considering the usage of a named `state_timeout`, since sometimes a state will have 2 or more timers that need to occur separately, that relate to transitions away from the state.  If the `state_timeout` allowed an explicit name, it seems like it could make the logic easier to follow.  A named `timeout` (not the `named_timeout` atom usage described above) would probably not be commonly used.

It appears like my desire to have more than 1 `state_timeout` and more than 1 `timeout` doesn't match `gen_statem` as-is, because it appears the `timeout` is attempting to be the single timeout, similar to other OTP behaviours.  If that is the case, then it just forces ad-hoc usage of TimerRefs, which limits the benefit to the `gen_statem` "timeout" functionality.  So, my suggestion about having named `state_timeout` and `timeout` is with the assumption that we should be able to have more than 1 timeout event with these semantics.

**Comment by RaimoNiskanen** [comment]
Well, `timeout` is the event timeout inherited from `gen_fsm` and `gen_server`, which maybe just should be left as-is.  An event timeout is seldom useful, and having multiple less so.

Regarding multiple `state_timeout`: do you mean several running in parallel e.g every 2 s send a ping but after 10 s change states (and cancel the 2 s timeout)?  That is a use case!  This particular one could be solved with the state timeout running repeatedly for 2 s and a named timeout to exit the state.  The state timeout can be replaced with a named timeout just by cancelling it when changing states.

So I think it is uncommon to want multiple timeouts running in a state that all should be cancelled when changing states, and when that is needed you can always do it with named timeouts and explicit cancellations.

But if there is a common enough pattern to have multiple state timeouts, they should be activated with `{state_timeout,Name}`, and if so `{named_timeout,Name}` becomes strangely named as the naming property lies in the 2-tuple, not in the tag.  The tag should say "not auto cancelled", "generic", "nothing special" or something like that.  Using `{timeout,Name}` would be right if we hadn't had `timeout` as the event timeout - it would be confusing if `timeout` and `{timeout,Name}` differed not only in being named but also in one of them being auto cancelled!  Or would it?  `{timer,Name}` is another name suggestion.

If we can decide that we will never introduce `{state_timeout,Name}` then `{named_timeout,Name}` is a good enough name for multiple generic timeouts.  Otherwise it might need a new name. `{timer,Name}`, `{timeout,Name}`, `{generic_timeout,Name}`, `{multi_timeout,Name}`, `{manual_timeout,Name}`, `{vanilla_timeout,Name}`, ...

**Comment by RaimoNiskanen** [comment]
On the other hand what named timeout gives over regular Erlang timers is the ability to control them with a name, so maybe `{named_timeout,Name}` _is_ good.  And if state timeouts should follow the same pattern, so be it!

**Comment by vans163** [comment]
@okeuday 
Options:
#1 Patching OTP modules (timer, and erlang BIF) to accept cancel alongside infinity to cancel timeout.
#2 Making gen_statem convert cancel atom as Timeout to infinity for OTP.

I think OTP is correct using infinity in this case.  Because indeed you do not cancel the timer by using a send_timeout of infinity (or do you).  I am not sure if this has any memory implication or cpu implication if you have 100m timers on infinity, vs actually cancelling them.

**Comment by ferd** [comment]
I think this entire discussion is getting dangerously close to escaping the original intent of gen_statem as I understood it; a better gen_fsm that allowed us to recapture selective receives and use complex nested states.

Last revision added state-timeouts which were a welcome inclusion that are difficult to manage without access to the underlying FSM code or without requiring a lot of tricky state tracking and transitioning.

Named timeouts to me feel like a lot of bike-shedding to find a different way to handle timeouts in general, for which there's already multiple solutions and means to do (`erlang` timer BIFs. `timer` module, etc.) 

I'm worried that gen_statem is on its path to gaining in complexity to the point where it's a general development behaviour that could encompass all Erlang operations with side-effects, which frankly I feel is a bad idea: this tends to fail, the same way DSLs sooner or later turn out turing complete and difficult to handle and you get to debug things in an entirely new unfamiliar context. There's much complexity deduplicating the efforts of existing primitives people have already learned and can lift more flexibly for little benefit there.

Just naming a timeout the way it's done here is seriously doable with a map and 2-3 wrapper functions:

```erlang
set_timeout(Name, Delay, Timeouts) ->
     _ = cancel_timeout(Name, Timeouts),
     Ref = erlang:start_timer(Delay, self(), Name),
     Timeouts#{Name => Ref}.

cancel_timeout(Name, Timeouts) ->
     try maps:get(Name, Timeouts) of
          Ref ->
               case erlang:cancel_timer(Ref) of
                    false -> flush_timeout(Ref);
                    _ -> maps:remove(Name, Timeouts)
               end
         catch _:_ -> Timeouts
    end.

flush_timeout(Ref) ->
     receive {timeout, Ref, _} -> ok after 0 end.

...
```
and so on. 

The idea that these wrappers are cumbersome, to me, speaks to the possible necessity of offering these wrappers already, rather than baking their full use within the behaviour itself. Then they start being way more useful in a general manner, and you're decoupling timer usage from the behaviour itslef.

I can guarantee that within a short period of time we're going to get in the game of implementing all kinds of exponential backoff with and without jitter and so on. Because that's the next step of course.

**Comment by vans163** [comment]
@ferd 

I agree with you to a extent. First I agree about the exponential backoff and I feel this plagues Elixir.  There are so many contributions that its a dangerous ecosystem, as something can change or become deprecated in the next release, or superseeded, or its just plain useless and adds complexity to understanding Elixir.

But there is some functionality that seems natural and basic to have.  Some things like for example Mnesia, why do we have mnesia? When we can just use ETS and handle the persistence part ourselves.  We have Mnesia because it provides a necessary and important convolution that is very useful.

This gen_statem timeout to me seems to fit this paradigm.  Simply because a "state machine" can be in multiple states in 1 time, a "finite state machine" can be in 1 state at 1 time.  Because this is not gen_fsm but gen_statem, we can assume we are not a finite 1 state at 1 time state machine.  Again I will reiterate that we get the behaviour by using handle_event_function as the callback mode.  If you want something more tuned to gen_fsm use state_functions as the callback mode and ignore multiple timeouts.

Just because we have two hands but use 1, does not mean we should cut the other hand off to reduce drag.

**Comment by ferd** [comment]
I'm purely talking against named timeouts here.

**Comment by ferd** [comment]
If timeouts don't fit state timeouts or idle timeouts, then the logic is not tied to states or idleness purely. I would just manage all of them by hand. Like I currently do in all the other places.

If I just add functions to: reset_timeout(Name, Delay, Map), cancel_timeout(Name, Map), received_timeout(Timeout, Name, Map) (the latter being just a convenient to clear the map of old timeouts) then I can do all of what you mentioned too, and everything that is currently being added to gen_statem.

Except I can now reuse these very convenient functions elsewhere, not just within gen_statem. 

The reason for this is that you're after an abstraction for timeouts overall, to make them easy to manage. Whether you do it with `{named_timeout, Name, Duration}` or `reset_timeout(Name, Duration, Map)`, the actual complexity is the name, you're just picking a slightly different syntax to do it. But you gain more flexibility, and the code can be reused elsewhere by not forcing the abstraction to reside within the OTP behaviours themselves.

**Comment by vans163** [comment]
@ferd 

Your right about the abstraction, I am thinking now if this should belong in gen_server and anything else that returns at the end of init/handle/etc, thus naturally being in gen_statem.

Regardless this functionality is needed.  I see the problem if it goes to gen_statem first, it will never leave there.  

Another problem is changing things like gen_server which have been iconic and untouched for so long seems wrong.  I see gen_statem replacing most of my gen_servers with the multiple timeouts. If gen_servers had multiple timeouts I can see gen_statem replacing a lower but still significant amount.

gen_statem outside of the multiple timeouts makes some guarantees that make it ideal to replace gen_server, I am talking about race conditions specifically around initiation.  Going forward I can see gen_server being deprecated as the go-to behaviour.

**Comment by okeuday** [comment]
@vans163 Using `cancel` in any way similar to `infinity` is not a good pursuit, since it just makes usage more complicated.  My usage of the word `cancel` is specifically in reference to `erlang:cancel_timer`, since that is the core timer BIF that is most useful due to the `timer` module having scalability issues and just adding latency.  Having explicit "cancel" word usage is more straight-forward to read than to read source code about an infinite delay, since the `infinity` atom can be ignored while skimming.

@ferd To make timer usage simpler and more predictable to encourage more reliable FSM creation is a good pursuit, so I believe it isn't a form of misdirection that is leading `gen_statem` away from its goals.  I agree that it is unlikely for `gen_statem` to support all possible timer usage, which is ok and should be accepted.  The goal with having more features for timers within `gen_statem` is avoiding custom functions like the ones you mentioned, to avoid the extra state management (i.e., avoiding side-effects within your source code and keeping those side-effects in OTP source code to make reliable source code easier), the potential for edge-cases and the mental burden that ad-hoc source code creates (i.e., avoiding a C programmer mentality where anyone should be able to write low-level source code that is flawless despite it being a waste of time).  Reducing the complexity that was typical in `gen_fsm` usage is the main goal and you are attempting to suggest something similar to the `gen_fsm` approach.

@RaimoNiskanen The use-case of a named `state_timeout` that I am thinking of, is for coordination between separate Erlang processes (say 2 as a base-case) which must provide events within a certain timeout period independently.  They are likely to want the same timeout length, however, it is helpful to be able to cancel them independently as their respective events are handled, while being in the appropriate state.  Having complexity like that represented in a way that is easy to read is beneficial.  While you may say that it is sufficient to use a single timer to handle 2 or more events that must be received within the timeout period, that is possible, until each timeout period needs to vary independently (either the initial setting and/or delays during the processing within that state which update the timeout period for a single event).

**Comment by ferd** [comment]
I'm just saying, it wouldn't be ad-hoc code if it were living inside a library other than gen_statem.

**Comment by IngelaAndin** [comment]
I think that we should not stress this functionality. gen_statem is
fairly new and we should let it rest and gather experience from real
implementations before adding a lot of new features.

I think that named timeouts in gen_statem might be solving the problem in the wrong
place. I agree with @ferd  that having a timer abstraction could be
useful but should probably not be gen_statem specific.

I think gen_statem should not be aiming to replace gen_server. It was a
problem before that gen_server replaced gen_fsm, which I think it did
as it did not support the semantics of selective recive and hence it
just made life complicated instead of providing the the semantics you
need to do your state machine implementation. So people thought they
might as well handle it on their own in gen_sever. So if
named_timeout would make people use gen_statem where gen_server really
is the be the best fit, this would be a bad thing.

I think multiple time-outs can be thought of as spawned worker processes
that may generate an external event that needs to be handled by the state
machine.

I do not think that a state-timeout should be multiple, as I think the
state-timeout is a timeout that conveys the information that now we have
resided in this same state during this period of time.

**Comment by RaimoNiskanen** [comment]
Let's compare code...

Assuming multiple `state_timeout`s: 

```erlang
lobby(enter, _, _Data) ->
    {keep_state_and_data,
     [{state_timeout,15000,ok},
      {{state_timeout,{check_friend_online,'bob#54'}},30000,ok},
      {{state_timeout,{check_friend_online, 'john#67'}},30000,ok}]};
lobby(info, {delete_friend,FriendTag}, Data) ->
    {keep_state,
     delete_friend(FriendTag, Data),
     [{{state_timeout, {check_friend_online, FriendTag}}, infinity}]};
lobby({state_timeout,{check_friend_online,FriendTag}}, _, Data) ->
    case check_friend_online(FriendTag) of
        true ->
            {keep_state_and_data,
             [{state_timeout,{check_friend_online,FriendTag}},30000,ok}]};
        false ->
            {keep_state,
             delete_friend(FriendTag, Data)}
    end;
```

Assuming a suitable timer library:

```erlang
lobby(enter, _, #{timers := Timers} = Data) ->
    NewTimers =
        timers:start(
            {check_friend_online, 'john#67'}}, 30000, ok,
            timers:start(
                {check_friend_online,'bob#54'}, 30000, ok, Timers),
    {keep_state_and_data,
     [{state_timeout,15000,ok}]};
lobby(info, {delete_friend,FriendTag}, #{timers := Timers} = Data) ->
    NewTimers = timers:cancel({check_friend_online, FriendTag}}, Timers),
    {keep_state,
     delete_friend(FriendTag, Data#{timers := NewTimers})};
lobby(info, {timeout,TRef,ok} = Timeout, #{timers := NewTimers} = Data)
  when is_reference(TRef) ->
    case timers:lookup(TRef, Timers) of
        {check_friend_online,FriendTag} ->
            case check_friend_online(FriendTag) of
                true ->
                    NewTimers =
                        timers:start(
                            {check_friend_online,FriendTag}, 30000, ok, Timers),
                    {keep_state, Data#{timers := NewTimers};
                false ->
                    NewTimers = timers:timeout(TRef, Timers),
                    {keep_state,
                     delete_friend(FriendTag, Data#{timers := NewTimers})}
            end;
        undefined ->
            handle_event(info, Timeout, ?FUNCTION_NAME, Data)
    end;
```

So with a timer library we get 30 LOC instead of 18, we have to explicitly handle the `Timers` state data variable, and have to explicitly handle unknown `timeout` messages.  But we get flexibility in that this indirectly proposed timer library is usable from any code, not just `gen_statem`.  And both are readable.

With a few helper functions wrapping these `timers:` functions that work directly on `Data` and abstracts away the timer handling into friend handling the difference between the code examples will be significantly less since we do not need to handle the `timers := Timers` map entry everywhere.

I think that after having state timeouts, multiple timeouts is a suitable feature for a state machine engine, but as said we maybe really want them for more general use...

So I will go with my colleagues and @ferd and put the multiple timeouts feature on ice for now to see if the idea benefits from ageing, or if some other suggestion comes and obsoletes it.

**Comment by vans163** [comment]
@RaimoNiskanen That second example is just hard on the eyes to read and increases codes maintenance cost as a result. (its much easier to introduce mistakes and bugs when you write code like that)

@IngelaAndin An example in the SSL module is say that if the server gets the client hello, sends the server hello, now the server sets two timers:

 timer #1 is the delay before the client authentication. If no client auth received after X time we close socket + produce warn/error. Say 2 minutes.

 timer #2 is the total delay we want to wait if something went wrong.  If we somehow got into an unknown state due to a programming oversight (Erlang is reliable vs programming errors as well!) to timeout say after 10 minutes and produce a nice error saying something went completely wrong.


How would you do this? Do you use your own timers for both timeouts? Or do you use 'timeout' for the first and your own for the second?  It seems to me 'timeout' does not belong then.  You should always be using your own timer library then.

**Comment by IngelaAndin** [comment]
Also a side note, the rational of having state-functions vs handle_event approach  is that the
latter actually provides additional semantics that is not offered by state-functions, but that in many cases just is overkill.  We do not consider it good to have two ways of doing the exact same thing. So you can consider state-functions as the main stream approach vs the handle_event approach that has more flexibility at the cost of beeing more complex.

**Comment by vans163** [comment]
@IngelaAndin I like handle_event simply because it takes care of 1 shortcoming of the actual Erlang language, where you cannot have two different functions intertwined. handle_event just works.

You can keep blocks of logic in 1 place, vs having things at the top, having things in the middle and having functions in the bottom all related to 1 block of logic. It makes reading code a nightmare when you need to jump around to 3 places in the module just to understand what is going on.

**Comment by IngelaAndin** [comment]
@vans163 That depends on how you look at your problem and how big it is. I do not want to go into a discussion of  personal preferences, nobody is stopping you from using handle_event, but if you have a big state machine normal you want to have the logic of one state in the same place so it is easily overviewed, having one giant function soon will loose that. I do not see a problem with jumping in the code to see the details. What you want in the state functions is the read thread logic.

**Comment by vans163** [comment]
@IngelaAndin That all works with simple states, but with complex states its different.  I think what I will do is manually put in the code for multiple state and named timeouts and start using gen_statem in some of my new projects then report back how it fits with some actual in practice details.  Plus post the code so it can be evaluated for correctness.

**Comment by IngelaAndin** [comment]
Please do. I will close this for now and we will see what happens. I know some of my colleagues might
do some prototyping too.

**Comment by vans163** [comment]
Testing this currently for a one way state updater and there exists a need for something like timeout_absolute as well.

The problematic scenario is this.  You have something that every 200 ms sends an update to a remote peer.  Anytime the state of the gen_statem updates you set a timeout of 200ms, once 200ms expires you fire off the timeout, perfect.

Enter problem. Your gen_statem state function you made gets called every 100ms, updating the state very rapidly, you will never timeout now.  The only solution is to track your own timer, but if gen_statem is to avoid timer tracking, a timeout that functions like so would be useful.

This means if you return 'timeout_absolute' or equivalent with a timeout, any future 'timeout_absolute' will not override an already running 'timeout_absolute' until that 'timeout_absolute' expires.

So indeed @IngelaAndin it maybe turtles all the way down without handling the timer yourself.

**Pull request closed without merging**
