### PR TITLE
sendfile: Fix sending of files larger than the OS send buffer on FreeBSD

### PR DESCRIPTION
**Pull request by theom**
This patch has been tested to work correctly on FreeBSD 10.1-RELEASE-p10.

### CODE REVIEW

**Comment by garazdawi** [comment]
Please restructure the code so that the sys/socket.h include and __BSD_VISIBLE define is written in a similar way to how sys/sendfile.h is guarded on linux+sunos.

Also add a comment in the code next to the define saying something like this:

    /* Need to define __BSD_VISIBLE in order to expose prototype of sendfile */

**Comment by tuncer** [comment]
Can we also test on 9.3?

**Comment by tuncer** [comment]
A sufficiently large file (> send buffer) should be part of the test suite.

**Comment by tuncer** [comment]
The test suite should also check that sending a file larger than the OS send buffer doesn't fail.

**Comment by theom** [comment]
Done.

**Comment by garazdawi** [comment]
@theom I cannot see the new code in this PR

**Comment by theom** [comment]
Ah, sorry. When I pushed the change I got an error and I was too tired to
notice. It should be there now.

**Comment by garazdawi** [comment]
@theom please squash all of your commits into one and remove all white space only changes.

**Comment by theom** [comment]
Ah, the white space changes is emacs removing spaces from the end of the
line when saving. I've disabled that.
I have no idea how to squash my commits so I just created a new branch and
a new pull request that cleans this up. Hope that's ok:
https://github.com/erlang/otp/pull/841

**Comment by fenollp** [comment]
@theom 
```
git checkout your-branch
git rebase -i HEAD~$(git rev-list maint.. | wc -l)
# replace "pick" with "f" on every line but the first one
git push --force
```

**Comment by garazdawi** [comment]
@theom that's fine, closing this pr and continuing in #841

**Pull request closed without merging**
