### PR TITLE
Avoid forking sed to get basename.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by garazdawi** [comment]
In https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Shell-Substitutions.html#Shell-Substitutions ## is not one of the functions listed as portable across all platforms.

What is the reason that you want to make this change?

**Comment by adelton** [comment]
I was `strace`ing startup of `erl` and saw that fork+exec of `sed` which seemed unnecessary. Basically I'm trying to get rid of one extra runtime dependency.

I understand that while required by POSIX, the `##` might not work on all shells. Is that something that erlang's CI could catch?

Also, if even the slightest possibility of regression is not acceptable, I wonder if changing the patch to fall back to `sed` (for example if the `PROGNAME` ends up being empty string) would help get it in?

**Comment by garazdawi** [comment]
On solaris 10 we get this error:
```
erlc -W  +debug_info -Werror +warn_export_vars +warn_missing_spec +warn_untyped_record -o../ebin hipe_consttab.erl
/ldisk/daily_build/21_master-opu_o.2018-05-16_20/otp_src_21/bootstrap/bin/erl: bad substitution
```
So something needs to be done to fix that.

**Comment by okeuday** [comment]
It is better the way it was to keep the shell script more cross-platform, IMO.

**Comment by tsloughter** [comment]
Is `basename` really not available in all support nix platforms?

**Comment by okeuday** [comment]
@tsloughter Based on https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Limitations-of-Usual-Tools.html#Limitations-of-Usual-Tools "not all hosts have a working `basename`" (`dirname` is also a problem)

**Comment by adelton** [comment]
Using `basename` would just replace forking `sed` with different binary. My primary goal was to avoid the fork. I will have to figure out if there is reasonable way to fall back to the external process. Perhaps something like

```
PROGNAME=${0##*/} 2> /dev/null
if ! [ "$?" = "0" ] ; then PROGNAME=`echo $0 | sed 's/.*\///'` ; fi
```

?

**Comment by RaimoNiskanen** [comment]
On Thu, May 24, 2018 at 12:26:27AM -0700, Jan Pazdziora wrote:
> Using `basename` would just replace forking `sed` with different binary. My primary goal was to avoid the fork. I will have to figure out if there is reasonable way to fall back to the external process. Perhaps something like
> 
> ```
> PROGNAME=${0##*/} 2> /dev/null
> if ! [ "$?" = "0" ] ; then PROGNAME=`echo $0 | sed 's/.*\///'` ; fi
> ```

Testing on Solaris 10:
$ uname -a
SunOS carcharoth 5.10 Generic_125100-10 sun4u sparc SUNW,Netra-240
$


Seems to not quite cut it:
$ PROGNAME="${0##*/}" 1>/dev/null 2>&1
bad substitution
$ PROGNAME="${0##*/}" : 1>/dev/null 2>&1
bad substitution
$ eval PROGNAME="${0##*/}" 1>/dev/null 2>&1
bad substitution
$

The text "bad substitution" must be printed by the current shell so the
redirecion has no effect.  The current shell fails to parse a command.



$ if ! [ "$?" = "0" ] ; then PROGNAME=`echo $0 | sed 's/.*\///'` ; fi
!: not found

Sorry, the ! negation is not Bourne shell.



This works apart from the "bad substitution" printout:

$ PROGNAME="${0##*/}"
bad substitution
$ [ $? = 0 ] || PROGNAME="`echo $0 | sed 's/.*\///'`"
$ echo $PROGNAME
sh

-- 

/ Raimo Niskanen, Erlang/OTP, Ericsson AB

**Comment by adelton** [comment]
Thanks all for their comments and checking behaviour on different systems.

I guess we can't really make this in portable way, so closing.

**Comment by RaimoNiskanen** [comment]
On Thu, May 24, 2018 at 10:06:26AM +0200, Raimo Niskanen wrote:
> On Thu, May 24, 2018 at 12:26:27AM -0700, Jan Pazdziora wrote:
> > Using `basename` would just replace forking `sed` with different binary. My primary goal was to avoid the fork. I will have to figure out if there is reasonable way to fall back to the external process. Perhaps something like
> > 
> > ```
> > PROGNAME=${0##*/} 2> /dev/null
> > if ! [ "$?" = "0" ] ; then PROGNAME=`echo $0 | sed 's/.*\///'` ; fi
> > ```
> 
> Testing on Solaris 10:
> $ uname -a
> SunOS carcharoth 5.10 Generic_125100-10 sun4u sparc SUNW,Netra-240
> $
> 
> 
> Seems to not quite cut it:
> $ PROGNAME="${0##*/}" 1>/dev/null 2>&1
> bad substitution
> $ PROGNAME="${0##*/}" : 1>/dev/null 2>&1
> bad substitution
> $ eval PROGNAME="${0##*/}" 1>/dev/null 2>&1
> bad substitution
> $
> 
> The text "bad substitution" must be printed by the current shell so the
> redirecion has no effect.  The current shell fails to parse a command.
> 
> 
> 
> $ if ! [ "$?" = "0" ] ; then PROGNAME=`echo $0 | sed 's/.*\///'` ; fi
> !: not found
> 
> Sorry, the ! negation is not Bourne shell.
> 
> 
> 
> This works apart from the "bad substitution" printout:
> 
> $ PROGNAME="${0##*/}"
> bad substitution
> $ [ $? = 0 ] || PROGNAME="`echo $0 | sed 's/.*\///'`"
> $ echo $PROGNAME
> sh

This seems to work on Bourne shell, Solaris 10
(storing fd 2 for current shell in fd 3, temporarily)

$ exec 3>&2 2>/dev/null
PROGNAME="${0##*/}"
[ $? = 0 ] || PROGNAME="`echo $0 | sed 's/.*\///'`"
exec 2>&3
$ echo $PROGNAME
sh


-- 

/ Raimo Niskanen, Erlang/OTP, Ericsson AB

**Pull request closed without merging**
