### PR TITLE
Consider ANSI escape codes on cp_pos_to_col

### PR DESCRIPTION
**Pull request by ggcampinho**
This fixes the issue with the function `move_cursor` described in #1536 and that causes the bug described in elixir-lang/elixir#6504, and also fixes wide chars handling.

The function `cp_pos_to_col` maps the current position in the buffer to the correct column on the screen, but it didn't handle ANSI escape codes. Since the ANSI escape codes aren't visible, the `cp_pos_to_col` now skips them when executing the calculations using `ansi_escape_width`. This new function only considers color escape codes, but also handles invalid codes.

The function `del_chars` used to first delete the buffer and than write down the new buffer cleaning the line and moving the cursor back, the problem in that is that when you clean the buffer you lose the size of the old characters and, if you have wide chars, it will move the cursor back to the wrong position. Now the function writes and clear the line, for then to remove the chars from the buffer.

### CODE REVIEW

**Comment by ggcampinho** [comment]
I'm not sure if this is the best approach, but I tried to focus the parsing issues in the `insert_buf` function and let the other functions as light as possible.

The bug with the cursor is easily reproduced changing the prompt and adding some colors. On the [group file](https://github.com/erlang/otp/blob/master/lib/kernel/src/group.erl#L858), you can substitute `Prompt` for `"\e[34;3mdevelopment\e[0m " ++ Prompt`.

Then, if you type a very long line, press enter, then up (back in history), then use the left arrow to walk back, in some point the cursor will jump.
```
Erlang/OTP 20 [erts-9.0.4] [source-66a623f71] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0.4  (abort with ^G)
development 1> [a,                                                                                                                                             b].
[a,b]
development 2> [a,                                                                                                                                     [a,b]   b].
development 3> 
```

I did some testing to check also what happens on the terminal with wrong escape codes:
```
1> io:format("\emfoo~n").   
foo
ok
2> io:format("\efoo~n"). 
oo
ok
3> io:format("\e[3;mfoo~n").
foo
ok
4> io:format("\e[[mfoo~n"). 
mfoo
ok
5> io:format("\e[;mfoo~n").
foo
ok
```

As we can see if there is a strange character the escape code swallows it and then it prints normally again.

**Comment by dgud** [comment]
My recent changes in the ttsl_drv had the idea that cp_pos_to_col() should calculate (CodePoint) array index to column position.  This was done to handle graphemes i.e. multi codepoints to one column character.

So if that is a good idea I believe that the compensation should be there, and I wanted `cp_pos_to_col()` to be `wcswidth(lbuf, cp_pos)` which should handle Korean better for instance, but that doesn't handle ANSI escape codes.

So maybe a loop of wcswidth() while ignoring escape codes?

**Comment by ggcampinho** [comment]
I think it makes sense, I will try to change things and make `cp_pos_to_col` responsible for this. I only didn't understand the `wcswidth` part of the things, should I change the `wcwidth` use?

**Comment by dgud** [comment]
Yes change wcwidth use to wcswidth usage on the non ANSI parts of the buffer.

**Comment by ggcampinho** [comment]
I pushed some changes, it's working but it's a little bit slow and it makes visible the erasing and rewriting of the buffer when moving up in the history. I'll try to improve that.

**Comment by ggcampinho** [comment]
I realized that the debug was making it slow, but I tried to make the function as short as possible, but still simple.

Unfortunately, I couldn't find a case which `wcwidth` behaves strangely, I did found that when Korean is used the function `del_chars` doesn't behave properly and I can address that in another PR. I think the problem is that we delete the wide chars and when we try to move the cursor we miss the information about how many columns we deleted, moving less them expected.

**Comment by dgud** [comment]
I'm on vacation will take a look at it when I return.

**Comment by ggcampinho** [comment]
Okay 👍

I added here the bug with wide chars that I described. If I add Korean chars to the prompt and try to move in the history, or delete something, the cursor would go to the wrong position. I don't know if I should split this in 2 PRs or should I keep it here.

**Comment by dgud** [comment]
If you have a fix for the second problem you can add it as a separate
commit in this PR.

**Comment by dgud** [comment]
I have problems with last commit.

Make a long line that have more chars than what fits on the line then delete chars so that the cursor should go back to the previous line, the cursor jumps to the wrong position (neither forward or backward delete works).

```
1> "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa....
aaa"  BSP BSP BSP BSP
```

**Comment by ggcampinho** [comment]
I'll check that, maybe I did something wrong when I was cleaning the commit

**Comment by ggcampinho** [comment]
I think now it's okay, my fix created a problem with the function `write_buf` that considers the full buffer to decide if it should fix the cursor when `xn` is true, then I realized that the fix was actually much simpler.

**Comment by dgud** [comment]
The idea was that input to move_cursor are array index positions not grapheme indexes or a mix thereof.
So your solution doesn't work when testing with graphemes and multicolumn characters.
ANSI prompt or not doesn't seem to matter.

But I can see the problem with my earlier commit.

And I found another problem (which have been there before my commit) in `move cursor`.
`dc = COL(to_col) - COL(from_col);`  doesn't work when we move a multi-column char beyond line limit,
when it doesn't fit it will move to the next line leaving a blank as last char on previous line and thus 
first line will be only "cols" -1 wide which breaks the cursor position calculation, and everything after
that breaks.

`del_chars` works with multi-column chars as long we are on a single line right? 
(without your last 2 commits)

So I believe the problem is in `move_cursor` as I tried to describe above, your ANSI stuff looks good
from what I can see and test.

I didn't find an easy solution and I will not be able to work on it until next week.

The PR is marked as based on eralng:master (top of this page), tough it should be on erlang:maint?
The branch seems to be based 'maint' on from what I can see.

**Comment by ggcampinho** [comment]
Without the last 2 commits this happens if you use the history and wide chars:
```
Erlang/OTP 20 [erts-9.0.4] [source-1e57f7471] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0.4  (abort with ^G)
한국어/조선말 1> [1,2].
[1,2]
      한국어/조선말 2> [1,2].
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C%   
```

If you try to delete a wide char also it doesn't work properly (there are small spaces in the string, the cursor also moves strangely):
```
Erlang/OTP 20 [erts-9.0.4] [source-1e57f7471] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0.4  (abort with ^G)
1> "한국어조선".
[54620,44397,50612,51312,49440]
2> "한국조선".  
[54620,44397,51312,49440]
3> "한 선".   
[54620,49440]
4> "한선".
```

The reason why these fix works is that anything that is outside the buffer size will be considered as width 1, I had to add an `if` in the beginning of the `move_cursor` to guarantee that the behaviour would continue after the changes.  I don't know how is better to follow up in this one, should I remove my last 2 commits? I can also help trying to find a way to improve `move_cursor` if you need help, but I don't think the issue is super urgent since it wasn't the main goal of this PR

**Comment by dgud** [comment]
Hmm I don't see those problems, on what are you testing this? 
Is xn=1 on your terminal? 
It is 1 in my gnome-terminal and on xterm.

**Comment by ggcampinho** [comment]
You can add `한국어/조선말` to the prompt [here](https://github.com/erlang/otp/blob/master/lib/kernel/src/group.erl#L858)

```erlang
prompt_bytes(Prompt, Encoding) ->
    lists:flatten(io_lib:format_prompt("한국어/조선말 " ++ Prompt, Encoding)).
```

Then type anything hit enter and navigate through history using up. I also have xn=1 on my terminal, but here this isn't an issue, only in my 2nd commit.

To describe the error with more details, when you move up in the history, it will send an `{del_chars,size}` to the driver with `size` being the number of items from the beginning of the buffer up to the current position `lpos`.

In this example, I have 9 elements inside the buffer (3 korean chars, slash, other 3 korean chars, space, 1 and `>`). So, `del_chars` will be called with `n = -9`, `lpos = 9` and `llen = 9`, and we will calculate `pos = 0` using the `else` portion of the code. Then `l = 9`, `r = 0` and `gcs = 16` (because the korean chars use 2 columns each) we don't write anything, print 16 blank spaces, them we move the cursor 9 columns to the left. In this point we are in the wrong position, because we are in the 5th column, not in the 1st. Them the next step is a `write_buf` with the same content from prompt and this is written in the wrong place.

**Comment by dgud** [comment]
Oh I have been tearing my hair here, found out what I got wrong:
Since we are testing ANSI escapes I have color coded the prompt, and then everything
works..sigh..

Thanks, will dig deeper.

Also you can change prompt with:
`shell:prompt_func({shell_default, prompt}).`

With: shell_default.erl
```
prompt(L) ->
    N = proplists:get_value(history, L, 0),
    Prefix = "\e[94m",
    Post = "\e[0m",
    %% Prefix = "",
    %% Post = "",
    case is_alive() of
        true  -> [Prefix, io_lib:format(<<"~s ~w> ">>, [node(), N]), Post];
        false -> [Prefix, io_lib:format(<<"~ts ~w> ">>, [[54620,44397,50612,47,51312,49440,47568],N]), Post]
    end.

```

**Comment by dgud** [comment]
Finally understood what you are doing and why it's ok, thanks for patience.
Added some additional corner case fixes, can you merge the 3 middle commits to one.

I can only see more problems when using multi-column chars on multi lines, which I agree is an other problem and another patch.

**Comment by ggcampinho** [comment]
No problem, and thanks for the help and the tip about the prompt.
I merged the commits, don't know if the message is clear

**Pull request merged**
