### PR TITLE
kernel: gen_tcp_dist refactoring to apply consistent coding style

### PR DESCRIPTION
**Pull request by JeromeDeBretagne**
Apply a consistent coding style throughout gen_tcp_dist, in particular by:
- using commas followed by a blank space
- removing trailing spaces
Not totally straightforward to me if OTP is enforcing specific guidelines. Thanks

### CODE REVIEW

**Comment by llelf** [comment]
I can’t speak for the OTP team, but these kind of things make history / `git blame` unusable for no reason.

**Comment by JeromeDeBretagne** [comment]
This PR is just a proposal at this stage, and indeed there are some potential trade-offs.

With this PR, I've only tried to bring consistency throughout a single file, which was following a common style overall but not totally. I understand the impact this creates when using git blame, but in this particular case, the modified file has a total history of 4 commits so this could be seen as acceptable.

About the "for no reason" part, I feel that there is a lack of global coding style consistency within the code base and it shouldn't be underestimated as it makes it harder 1/ to read & discover existing code and 2/ to make contributions. At least that's how I personally perceive it.

**Comment by essen** [comment]
They generally accept style changes only in the parts of the code that also receive fixes/enhancements.

**Comment by rickard-green** [comment]
As mentioned above, we do not want changes that only change formatting.

**Pull request closed without merging**
