### PR TITLE
Improve observer nodes list menu

### PR DESCRIPTION
**Pull request by gomoripeti**
- Also include connected, hidden nodes ([Observer User Guide](https://www.erlang.org/doc/apps/observer/observer_ug.html#getting-started) uses a hidden node as example)
- Always include current node. If dist_listen is false it won't show up
in epdm names
- If the default epmd module `erl_epmd` is used and `erl_epmd_port` is set
to `DistPort` then it is only possible to connect to the node listening
on `DistPort` (if any), so exclude other nodes registered in EPMD

The last change is controversial, maybe it should be implemented elsewhere (in net_adm or erl_epmd?) and it's not the responsibility of observer to know about this detail. Or the exclusion should not happen at all (Observer shows a nice error dialogue when connection fails and maybe that's good enough)

### CODE REVIEW

**Comment by dgud** [comment]
> Could there be some check only for connected nodes if they support observer functionality and only list those that do?
I don't know how to test that.

> Do c/java nodes show up in epmd names? (If yes, they would also be listed without being connected)
They can do that but then they expose themselves to maybe get rpc:call's so I think that is ok.

**Comment by gomoripeti** [comment]
A connected node is listed among `nodes(hidden)` if either the local node or the remote node is hidden. Would it be an acceptable heuristic that if the current node is hidden then entries from `nodes(hidden)` are listed? (There is an edge case when a c/java node is connected to a hidden node - but I dont know how likely that is)

**Comment by dgud** [comment]
After (not) sleeping on this for a couple of nights, I I think I like your last suggestion :-)

**Comment by gomoripeti** [comment]
happy to hear that, I will update the PR accordingly
wish you some sleep-full nights :)

**Comment by gomoripeti** [comment]
there are some recent changes in net_kernel around hidden type which I made use of. Naming is bit inconsistent with `connection_type` and `publish_type` having the same values (but bit different use)

**Comment by gomoripeti** [comment]
ok, I will add the warning text
(had to try to know it was a bad idea)

**Pull request merged**
