### PR TITLE
public_key: PKCS8 encoded private key support

### PR DESCRIPTION
**Pull request by max-au**
public_key: PKCS8 (Private-Key Information Syntax Standard) encoded private key support

This patch adds support for RSA, DSA and EC private keys encoded using PKCS8 format.

Test *.pem files are made with converting existing *.pem files using openssl:

openssl pkcs8 -in ... -out ... -topk8 -nocrypt

### CODE REVIEW

**Comment by IngelaAndin** [comment]
PKCS-8 is supported in the way that the  "top" PKCS-8 ASN-1 type PrivateKeyInfo can be encoded and decode and encode from the PEM-file.I was also surprised that there seemed to be no test cases for PKCS-8. I vaugly remember  working on this a long time ago. Maybe it was a case of procrastinating (low priority) that got forgotten about.

However I  see the reason that you would like to further decode the key types, something similar
is done for  'SubjectPublicKeyInfo'. But like in the case of 'SubjectPublicKeyInfo' there should be a
way to encode back from the types returned. 

There is also the issue of backwards compatibility.  This would alter the return value, but it might work out. The ssl application will handle this. Otherwise we would need some kind of option. 

I think the conversion code should look more like this:

```
private_key(#'PrivateKeyInfo'{privateKeyAlgorithm =
				 #'PrivateKeyInfo_privateKeyAlgorithm'{algorithm = ?'rsaEncryption'},
			     privateKey = Key}) ->
    public_key:der_decode('RSAPrivateKey', iolist_to_binary(Key));

private_key(#'PrivateKeyInfo'{privateKeyAlgorithm =
				 #'PrivateKeyInfo_privateKeyAlgorithm'{algorithm = ?'id-dsa'},
			     privateKey = Key}) ->
    public_key:der_decode('DSAPrivateKey', iolist_to_binary(Key));

```
Snipped is form ssl and I see EC-key handling is missing so I will fix that for ssl.

**Comment by max-au** [comment]
Agree with both points.
Adding PKCS8 encoder (as for 'SubjectPublicKeyInfo') will alter API. I'm thinking of something like this:

pem_entry_encode('PrivateKeyInfo', ...) ->

Also agree with suggested conversion code change. Will update shortly.

As for changing return value - I believe main user of public_key is ssl application, and it surely benefits from changing the return value format (in fact, it was the main reason for me to make the change).

**Comment by max-au** [comment]
Should be good to go now.

**Comment by IngelaAndin** [comment]
Looks good we will test it shortly. We have some other code in the cooking that we like to test separately 
from this. Could you also please use the macro ?DER_NULL instead of <<5,0>>

**Comment by IngelaAndin** [comment]
Looks good we will test it shortly. We have some other code in the cooking that we like to test separately 
from this. Could you also please use the macro ?DER_NULL instead of <<5,0>>

**Comment by IngelaAndin** [comment]
Your changes works fine with ssl however it fails public_key:  (similar fault for pbes1 test case)

`=== Test case: pbe_SUITE:pbes2/1 (click for source code)

=== Config value:

    [{watchdog,<0.243.0>},
     {tc_logfile,"/ldisk/daily_build/21_master-opu_o.2018-05-16_20/test/test_server/ct_run.test_server@jubilee.2018-05-17_03.26.06/test.public_key_test.logs/run.2018-05-17_03.26.06/pbe_suite.pbes2.html"},
     {tc_group_properties,[]},
     {tc_group_path,[]},
     {data_dir,"/ldisk/daily_build/21_master-opu_o.2018-05-16_20/test/public_key_test/pbe_SUITE_data/"},
     {priv_dir,"/ldisk/daily_build/21_master-opu_o.2018-05-16_20/test/test_server/ct_run.test_server@jubilee.2018-05-17_03.26.06/test.public_key_test.logs/run.2018-05-17_03.26.06/log_private/"}]

=== Current directory is "/ldisk/daily_build/21_master-opu_o.2018-05-16_20/test/test_server/ct_run.test_server@jubilee.2018-05-17_03.26.06"

=== Started at 2018-05-17 03:26:54

*** CT Error Notification 2018-05-17 03:26:54.233 ***
public_key:der_encode failed on line 301
Reason: {badmatch,{error,{asn1,{{badmatch,{'RSAPrivateKey','two-prim...}

Full error description and stacktrace

=== Ended at 2018-05-17 03:26:54
=== Location: [{public_key,der_encode,301},
              {public_key,do_pem_entry_encode,1135},
              {pbe_SUITE,decode_encode_key_file,242},
              {pbe_SUITE,pbes2,220},
              {test_server,ts_tc,1545},
              {test_server,run_test_case_eval1,1063},
              {test_server,run_test_case_eval,995}]
=== Reason: no match of right hand side value 
                 {error,
                     {asn1,
                         {{badmatch,
                              {'RSAPrivateKey','two-prime',
                                  11665542719696244100137339755020444133673093365001689143482571411250320007146892483401023309301930157431430484937672112391042881285657732356933622259725371,
                                  65537,
                                  2386437146084922176030964403246396608025316428041833564958280588227002156580488648651752575887780386814617700003342230461650746543157419947059931076737185,
                                  115698339460408532307549750372762914706181723052382347192752859368032128473067,
                                  100827226856511125596113262500236745197618758897862539650343033743206079926513,
                                  104036175637293974661888922886572338168515420620412043615303092229084354838431,
                                  68640730479425368564264298330875118234538635381342372538256325335106618581889,
                                  19891303127723350731677051070636929556232843370385667409404739292562232517511,
                                  asn1_NOVALUE}},
                          [{'PKCS-FRAME',enc_PrivateKeyInfo,2,
                               [{file,"PKCS-FRAME.erl"},{line,1675}]},
                           {'PKCS-FRAME',encode,2,
                               [{file,"PKCS-FRAME.erl"},{line,139}]},
                           {public_key,der_encode,2,
                               [{file,"public_key.erl"},{line,297}]},
                           {public_key,do_pem_entry_encode,4,
                               [{file,"public_key.erl"},{line,1135}]},
                           {pbe_SUITE,decode_encode_key_file,4,
                               [{file,"pbe_SUITE.erl"},{line,242}]},
                           {pbe_SUITE,pbes2,1,
                               [{file,"pbe_SUITE.erl"},{line,220}]},
                           {test_server,ts_tc,3,
                               [{file,"test_server.erl"},{line,1545}]},
                           {test_server,run_test_case_eval1,6,
                               [{file,"test_server.erl"},{line,1063}]}]}}}
  in function  public_key:der_encode/2 (public_key.erl, line 301)
  in call from public_key:do_pem_entry_encode/4 (public_key.erl, line 1135)
  in call from pbe_SUITE:decode_encode_key_file/4 (pbe_SUITE.erl, line 242)
  in call from pbe_SUITE:pbes2/1 (pbe_SUITE.erl, line 220)
  in call from test_server:ts_tc/3 (test_server.erl, line 1545)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1063)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 995)

`

**Comment by max-au** [comment]
Good catch!
Now the asymmetry between der_decode/der_encode is fixed, should be good to go.

**Pull request merged**
