### PR TITLE
Included config files relative to sys.config dir

### PR DESCRIPTION
**Pull request by crownedgrouse**
This permit same result when using a sys.config file in a release or starting manually a node with -config ... .
For backward compatibility, if file is not found relative to sys.config, it is searched from working directory like before.

### CODE REVIEW

**Comment by crownedgrouse** [comment]
working on adding a test. application_SUITE.erl is quite huge, need to see where it can go.

**Comment by crownedgrouse** [comment]
Hello Siri,
I red application_SUITE.erl file, but I'm not sure how I can add a usefull test. My concern is that some test are simulating config change , but are calling application_controller:change_application_data/2 with term containing included config file (that are located in test datadir, like t2.config etc..) but in such case cwd is explicitely set to this datadir and cannot be changed, as sys.config directory not known.  My PR need to set a path to top sys.config file. I can see nodes started with -config  is the tests, but I need your though if a can add another node start to test my PR. It is maybe time consuming for test durations, or maybe I can use one for that, but I suppose that a test must not be done to test two things. Your opinion would be much appreciated, and maybe a tip . I maybe not embrace the all logic of that. Thanks

**Comment by sirihansen** [comment]
I have added a test case to your branch and will run it in your nightly tests.
Please remove all whitespace changes on lines that are not otherwise changed, and squash all commits into one. Thanks!

**Comment by crownedgrouse** [comment]
well thanks. I did not wanted to let you do it, but this will be probably quicker from an OTP guy. I will do what you requested . BTW I know now how to add a node start test...

**Comment by sirihansen** [comment]
I'm really sorry to just commit to your branch without discussing with you first. The reason is that I had forgotten to follow up on this PR, and then realized that I needed to include it in our tests today to have a chance to get it into OTP-21 (already a bit over due on the code stop).

**Comment by crownedgrouse** [comment]
No problem Siri, you are welcome. I think I reverse the blank removing. I'm not sure I reached to squash like you want. tell me if this is not ok. I agree this PR should go to R21 as it is a new behavior for a new major release.

**Comment by sirihansen** [comment]
Unfortunately, there are still a log of whitespace changes in your commit :(

And for some reason there are also a few changes that do not belong to this PR, e.g. line 1274 in application_controller.erl, and some lines in application_SUITE.erl. I think these might disappear if you rebase your branch on the latest master.

**Comment by crownedgrouse** [comment]
I probably did a mess by merging upstream. if I cannot fix I should probably create another clean branch and do another PR. I will let you know.

**Comment by crownedgrouse** [comment]
too much mess as looks like i worked on a maint branch. Closing for a new PR .

**Comment by crownedgrouse** [comment]
See PR #1838

**Pull request closed without merging**
