### PR TITLE
add binary string uri encode/decode functions

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by IngelaAndin** [comment]
We think that the functionality is desirable. Although we have a concern about how the API should be
designed. In the purposed API  the input type affects the output type. This is for instance avoided by the base64 module that takes multiple inputs but always returns the same output type. And has a separate function to decode/encode_to_string.  In this case we would have to go the other way (encode/decode_to_binary) as string is the current implementation. The docs also only promises that it will work for ASCII strings.  It is an old API, and not in line with newer built in data-types for dialyzer. In the re module and also in other places output type can be changed by an option. The purposed "str" module in PR 1330 sort of have some functions that lets the input decide the output, but it is still chardata all of it. And the functions are specified to return chardata but depending on subtype used as input the subtype can be preserved.

**Comment by IngelaAndin** [comment]
We had many discussions about this.  There is no clear consensus but the conclusion is that
we think that all things considered we will take the pragmatic stand that URI in the context of this
module should be redefined to be uri() = assci_string() | binary()  and that the function can return the subtype that it took as input. The parse function should then also accept a binary as input.

**Comment by tsloughter** [comment]
Sorry, I missed your first comment 29 days ago! I actually had originaly done this was `encode/decode_binary` but found it kinda sloppy/confusing.

So great! I can add binary support to `parse` today.

**Comment by tsloughter** [comment]
I was finally implementing this and realized I'm going to be duplicating a number of things from #1330 ... Like needing a `to_lower` or `lowercase` function that works on a binary string. And needing a length and substr that works on both a list string and binary string. 

Would it be better to base this on #1330 ?

**Comment by IngelaAndin** [comment]
Yes it would be better to base it on  #1330  as long as you only use "to_lower" in the same way as already done in http_uri.

**Comment by IngelaAndin** [comment]
We discussed this some more and  maybe it will be better to wait for  #1330  to be merged as we want to be able to for instance squash commits on this branch.

**Comment by IngelaAndin** [comment]
PR #1330 has now been merged

**Comment by tsloughter** [comment]
Great! I'll look at using those changes for this.

**Comment by IngelaAndin** [comment]
ping

**Comment by tsloughter** [comment]
Sorry about that. Pushed an update. I'll still need to update the docs though.

**Comment by tsloughter** [comment]
Hm, should the docs be changing all `string()` to `unicode:chardata()` or to `string() | binary()`?

**Comment by IngelaAndin** [comment]
Hum ... unicode:chardata() can be deep lists so that I think  that will not work. However it can not be any binary it has to be a utf8-encoded binary.  So maybe we need  a string_binary()

**Comment by IngelaAndin** [comment]
You can use unicode:unicode_binary()

**Comment by tsloughter** [comment]
Great, I've updated the docs to include `unicode_binary()`

**Pull request merged**
