### PR TITLE
Fix typos and grammar

### PR DESCRIPTION
**Pull request by derek121**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Deleting dummy branches failed:

    c/com/ericsson/otp/erlang'
     JAVAC	/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/priv/com/ericsson/otp/erlang/OtpAuthException.class
    OtpAuthException.java:29: error while writing com.ericsson.otp.erlang.OtpAuthException: could not create parent directories
    public class OtpAuthException extends OtpException {
           ^
    1 error
    make[4]: *** [/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/priv/com/ericsson/otp/erlang/OtpAuthException.class] Error 1
    make[4]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/java_src/com/ericsson/otp/erlang'
    make[3]: *** [opt] Error 2
    make[3]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/java_src'
    make[2]: *** [opt] Error 2
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface'
    make[1]: *** [opt] Error 2
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib'
    make: *** [tertiary_bootstrap_build] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
Looks good! Thanks for the fixes! Just putting it through the build machinery to make sure no new warnings have been added to the docs.

**Comment by psyeugenic** [comment]
Lot's of work was done to the docs during the summer. I've rebased your branch on maint but dropped the time_correction file from your commit. I'll merge once it has traversed the CI system.

**Comment by psyeugenic** [comment]
Merged to maint without time_correction changes due to rewrite.

**Pull request closed without merging**
