### PR TITLE
filename join/split fixed for win32 share

### PR DESCRIPTION
**Pull request by c-bik**
Previously : https://github.com/erlang/otp/pull/901

#### Currently
``` erlang
> filename:join("\\\\", "foo").
"/foo"
> filename:split("\\\\foo").
["/","foo"]
```
#### Fixed by this PR
``` erlang
> filename:join("\\\\", "foo").
"\\\\test"
> filename:split("\\\\foo").
["\\\\","test"]
```

Yes, both join and split accepts (in stead of `function_caluse`) but **correct / valid** path is returned. As demonstrated in test cases below:
```erlang
"\\\\" = filename:join("\\\\", ""),
"\\\\foo" = filename:join("\\\\", "foo"),
"\\\\foo/bar" = filename:join("\\\\", "foo\\\\bar"),
"\\\\foo/bar/baz" = filename:join("\\\\foo", "bar\\\\baz"),
"\\\\bar/baz" = filename:join("\\\\foo", "\\\\bar\\baz"),
...
["\\\\","foo"] = filename:split("\\\\foo"),
["\\\\","foo","bar"] = filename:split("\\\\foo\\\\bar"),
["\\\\","foo","baz"] = filename:split("\\\\foo\\baz"),
```

> We will need test cases before we can consider including this patch in OTP. 

Test cases are also provided

### CODE REVIEW

**Comment by dgud** [comment]
Why "\\\\" instead of "//" ?
We want the path delimiter to be '/' and not '\' even for windows.

Also can you please clean up the branch, one commit on top of latest maint.

**Comment by c-bik** [comment]
Closed accidentally while trying to cleanup extra commits on branch! Will reopen soon!

**Comment by c-bik** [comment]
@dgud Thanks 👍 

> Why "\\" instead of "//" ?
We want the path delimiter to be '/' and not '' even for windows.

Done

> Also can you please clean up the branch, one commit on top of latest maint.

Done

**Comment by dgud** [comment]
Ok looking at your maint branch I can see your commit (and here via the web interface together with some ssh commits).

But fetching this pull-request I see another commit 73f84b3df40f which doesn't contain the above.

So from a quick glance the the code looks ok but the branch/PR is still a mess.

I would recommend creating a new PR and closing this PR and do 
(assuming you have named erlang/otp repository 'upstream'):

git fetch upstream
git checkout -b cbik/stdlib/fix-network-path-win32 upstream/maint
git cherry-pick 0cf7f53120
git push origin cbik/stdlib/fix-network-path-win32

And make a new PR.  (the commands are from my head, i.e. untested beware :-)

**Comment by c-bik** [comment]
@dgud sorry for the commit mess.
Tanks for your help with commit cleanup in PR 👍 
New PR commit soon!

**Comment by c-bik** [comment]
@dgud New PR is https://github.com/erlang/otp/pull/1604

**Pull request closed without merging**
