### PR TITLE
Fix supervisor:get_childspec/2 for simple_one_for_one

### PR DESCRIPTION
**Pull request by nybek**
This branch has two commits:

    320cfc8 Fix supervisor:get_childspec/2 for simple_one_for_one
    100d713 Refactor stray code in supervisor.erl left over from previous fix

The first is the important one. Its commit message is:

    A bug in supervisor:get_childspec/2 results in
    {error, simple_one_for_one} being returned on every call when the
    supervisor strategy is simple_one_for_one.

A trivial fix to this problem would have been to just move the handle_call/3
code for the 'get_childspec' msg above:

    %%% The requests delete_child and restart_child are invalid for
    %%% simple_one_for_one supervisors.
    handle_call({_Req, _Data}, _From, State) when ?is_simple(State) ->
        {reply, {error, simple_one_for_one}, State};
  
However, doing so would probably lead to a similar bug the next time someone adds
new functionality to this module. This code itself is actually the problem: it
assumes that someone will read all the clauses in the function before adding a
new one. There were already 10 clauses below it.

I replaced this code. Hope that's what you would have wanted.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Refactor stray code in supervisor.erl left over from previous fix


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
This one I think you can squeeze into one and commit and mention the refactoring in the commit message, saying it is to make the code easier to follow.  We will accept this patch.

**Comment by nybek** [comment]
That's great! I've pushed the updated version. Thanks.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
