### PR TITLE
Fix build failure on MacOSX 10.11 using XCode 8

### PR DESCRIPTION
**Pull request by rickard-green**
Proposed fix for ERL-256 <https://bugs.erlang.org/browse/ERL-256>

### CODE REVIEW

**Comment by bjorng** [comment]
Building with Xcode 7 on El Capitan (macOS 10.11) works.

Building with Xcode 8 on El Capitan now also works, provided I do:

     export MACOSX_DEPLOYMENT_TARGET=10.11

**Comment by bjorng** [comment]
👍 

On El Capitan with Xcode 8 I get the warning message that I must set `MACOSX_DEPLOYMENT_TARGET`. The build succeeds if I set it to either `10.11` or `10.11.6`.

El Captain with Xcode 7 builds fine (without setting `MACOSX_DEPLOYMENT_TARGET`), as does Sierra with Xcode 8.

**Comment by rickard-green** [comment]
👍

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
