### PR TITLE
hipe: Fix compiler crashes when inlining FP operations

### PR DESCRIPTION
**Pull request by kostis**
The HiPE compiler crashed, during compilation, in some cases that involved inlining of FP operations on complicated control flow graphs. (Though one could bypass the problem by supplying the option `no_inline_fp`.) Both cases were reported on the erlang-bugs mailing list -- one of them long ago and the other towards the end of 2015.  Thanks to @margnus1 for the fix!

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by sverker** [comment]
Merged to master.

**Comment by kostis** [comment]
I would have thought this would be merged to **maint** as it fixes a compiler crash and does not introdude any incompatibilities, but most likely you had good reasons to not do that.  Still, it's good that it's finally merged!

**Comment by sverker** [comment]
It was a bit late, but planned for 18.3 anyway from start.
Then we got problems with a bug in the beam compiler triggered by this PR
just before release. So we removed it to reduce risk. The bug turned out to
only exist in master, but then it was too late.

**Pull request closed without merging**
