### PR TITLE
ssl: Handle legacy scheme names

### LINKED ISSUE #7774: TLS handshake failure with OTP 26, succeeds with OTP 25
Repository with code to reproduce this issue:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU

I know that OTP 26 has "tightened things up" when it comes to TLS, and the following issue may actually be how TLS _should_ work in Erlang, but I thought this deserved a report.

**Describe the bug**

When a SSL listener is configured with `{versions, ['tlsv1.2','tlsv1.3']}`, and a connection attempt is made using a .NET application on Windows Server 2016, a handshake failure occurs using OTP 26. This failure does not occur using OTP 25.

The original reporter also provides a Python script that crafts the same client hello message that causes the issue. The script is located here:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/py/repro.py

There are some important notes here about which signature algorithms are necessary for OTP 26 to work:

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/py/notes.txt#L5-L10

**To Reproduce**

https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/README.md

**Expected behavior**

TLS connection succeeds.

**Affected versions**

Failure tested with OTP 26.1.2, succeeds with OTP 25.3.2.7

**Additional context**

* Note that because the client application is running on Windows and uses .NET, it is using Windows' TLS implementation and not OpenSSL. Running `openssl s_client` works just fine using OTP 26 and `{versions, ['tlsv1.2','tlsv1.3']}`.
* Original report - https://groups.google.com/g/rabbitmq-users/c/X9VRDGdn5HU
* Packet capture when using OTP 26, showing failure - https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/failure-otp-26.pcapng
* Packet capture using OTP 25, showing success - https://github.com/lukebakken/rabbitmq-users-X9VRDGdn5HU/blob/main/success-otp-25.pcapng

### PR DESCRIPTION
**Pull request by IngelaAndin**
closes #7774

### CODE REVIEW

**Comment by dgud** [comment]
This seems to need a testcase

**Comment by IngelaAndin** [comment]
@dgud  I agree, I will try to make one before merge. But I want @lukebakken to be able to test the solution.

**Comment by lukebakken** [comment]
I get the following compilation errors:

```
C:\Users\lbakken\development\erlang\otp\lib\ssl\src [ingela/ssl/legacy-schemes/OTP-18817 ≡]
> erlc +debug .\ssl_cipher.erl
ssl_cipher.erl:573:1: function is_supported_sign/2 already defined
%  573| is_supported_sign(SignAlgo, HashSigns) ->
%     | ^

ssl_cipher.erl:575:26: function supported_signalgo/1 undefined
%  575|               [SignAlgo, supported_signalgo(SignAlgo)]).
%     |
```

The first one is easy to address, but this PR branch doesn't appear to have `supported_signalgo/1`

**Review by lukebakken — CHANGES_REQUESTED** [review]
I get the following compilation errors:

```
C:\Users\lbakken\development\erlang\otp\lib\ssl\src [ingela/ssl/legacy-schemes/OTP-18817 ≡]
> erlc +debug .\ssl_cipher.erl
ssl_cipher.erl:573:1: function is_supported_sign/2 already defined
%  573| is_supported_sign(SignAlgo, HashSigns) ->
%     | ^

ssl_cipher.erl:575:26: function supported_signalgo/1 undefined
%  575|               [SignAlgo, supported_signalgo(SignAlgo)]).
%     |
```

**Comment by lukebakken** [comment]
@IngelaAndin I opened a PR for your PR!

https://github.com/IngelaAndin/otp/pull/1

**Pull request merged**
