### PR TITLE
Tracing Framework Update

### PR DESCRIPTION
**Pull request by garazdawi**
This PR is a combination of a lot of changes related to the upcoming tracing changes in OTP 19.0. The major changes are:

* Removed need for trace messages to go via the sys msg dispatcher. This decreases impact of tracing by as much as a factor 10. This is a very large change that effects the order in which trace messages are delivered. It does not change the guarantees that have always been there, but it does take advantage of some of the flexibility in the guarantees which the previous implementation does not. For instance when tracing using timestamps it is now possible to receive messages seemingly out of order. Trace messages from the same process will of course still be ordered correctly, but trace messages from different processes may come in any order. 
* Added Tracer Modules, a callback interface for trace consumers where formatting and filtering of trace events can be done much closer to the generation of the event thus decreasing the overhead.
* Added a new process trace event called 'spawned' which is enabled through the 'procs' trace flag. This event is generated by a process when it is created.
* Added 'send', 'receive' and 'ports' tracing flags to work for ports. Any communication coming to or from ports can now be traced using the normal tracing interface.
* Made the previously undocumented function erlang:match_spec_test/3 documented. The match_spec_test function can be used to compile match specifications and get human readable error messages.
* Update the dbg documentation to contain more examples and hopefully be clearer to beginners.
* Extend enif_send api to use the senders environment when sending messages. This is an optimization for when the majority of the data being sent is given as an argument to the nif.

### CODE REVIEW

**Comment by andytill** [comment]
Great work!

Since the documentation for match specs is updated could you also document how to return a stack trace from a function trace, as featured in redbug?

Does the new spawn event apply to seq_trace, or could it be in the future?  At the moment seq_trace does not apply a trace token to newly spawned processes.

**Comment by garazdawi** [comment]
> Since the documentation for match specs is updated could you also document how to return a stack trace from a function trace, as featured in redbug?

I believe that redbug uses the process_dump to get that information which is already documented.

> Does the new spawn event apply to seq_trace, or could it be in the future? At the moment seq_trace does not apply a trace token to newly spawned processes.

No, the 'spawned' event does not interact with seq_trace in any way. In order to make seq_trace track across spawn calls I think a new seq_trace token called 'spawn' would have to be introduced that sets that token. Such a feature is out of scope of this particular PR, but I'll make a note of it for future reference. Ideally of course someone else will make a separate PR for this.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
merged

**Comment by OTP-Maintainer** [comment]
test message

----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
test

----------------

I am a script, I am not human 

----------------

**Pull request closed without merging**
