### PR TITLE
Sharing-preserving copying of terms

### PR DESCRIPTION
**Pull request by nickie**
This set of commits implements the sharing-preserving copying of terms between process heaps, e.g. when sending messages and when spawning new processes.  Until now, terms are flattened when copied, e.g. the term `[L, L]` where `L = [1,2,3]` is expanded to `[[1,2,3], [1,2,3]]` when copied.  This is a safe but incomplete implementation of sharing-preserving copying: off-heap pointers in terms (e.g. constants) are copied verbatim.  A new BIF is also added, `erts_debug:size_shared/1`, which computes the (non flat) size of a term, i.e. the space that the term occupies in the process's memory.

Kostis Sagonas and I have been discussing this pull request with Kenneth Lundin for a long time.  The main idea is described in a paper presented at the Erlang Workshop in 2012 ([DOI 10.1145/2364489.2364493](http://dx.doi.org/10.1145/2364489.2364493)).  Several of the commits are there for debugging and testing purposes.

As agreed, this sharing-preserving behavior is by default disabled, unless the configure flag `--enable-sharing-preserving` is specified.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lpgauth** [comment]
very cool work :+1:

**Comment by nickie** [comment]
Hi Louis-Philippe,

> On Jun 30, 2015, at 15:36, Louis-Philippe Gauthier <notifications@github.com> wrote:
> very cool work 
> 

Thank you for your kind words.  I am not sure whether you are familiar with the issues that have been identified for this pull request.  In brief, it seems that dangling pointers to constants are created when modules are purged. The immediate way to circumvent this is by copying (and perhaps also flattening) all constants, regardless of sharing, but we are not convinced that this is the right way to proceed.

Unfortunately, Kostis (cc:) and I have not yet found the time to solve these issues, or more precisely, we have not found the time to conclude what is the best way to solve them.  We intend to do so in the near future. Until then, we do not recommend using this version in applications that require code reloading and/or purging.

I’m forwarding a previous e-mail by Rickard Green, explaining the issues.

Best regards,
Nikos Papaspyrou.


> Begin forwarded message:
> 
> From: Rickard Green <rickard.s.green@ericsson.com>
> Subject: Re: Sharing preserving copying implementation
> Date: October 28, 2014 at 19:12:01 GMT+2
> To: Kostis Sagonas <kostis@it.uu.se>, "Kenneth Lundin (AS/EAB)" <kenneth.lundin@ericsson.com>, Sverker Eriksson <sverker.eriksson@ericsson.com>, Bjorn Gustavsson <bgustavsson@gmail.com>, Björn-Egil Dahlberg <bjorn-egil.xb.dahlberg@ericsson.com>, <andreas.schumacher@ericsson.com>
> Cc: "Nikolaos S. Papaspyrou" <nickie@softlab.ntua.gr>
> 
> On 2014-10-26 13:39, Kostis Sagonas wrote:
>> On 10/07/2014 12:16 PM, Kostis Sagonas wrote:
>>> Dear all,
>>> 
>>> Yesterday, Nikos Papaspyrou (cc:), has submitted a pull request with
>>> the changes for the sharing preserving implementation.  It is based on
>>> the master branch ...
>>> 
>>> Compared with what we did about two years ago, the current
>>> implementation has been extended to handle maps properly.  As
>>> mentioned in the pull request comment, off-heap pointers in terms
>>> (e.g. constants) are copied verbatim. So the implementation is still
>>> not safe w.r.t. code unloading/replacement. We will submit another one
>>> pull request towards the end of this week or the beginning of the next
>>> one, so that it can be added separately. The reason is that ideally,
>>> constants should not be copied and the runtime system should be able
>>> to copy them on demand on module reloading or purging. So it's better
>>> if this pull request is separate so that it can be taken out one fine
>>> day.
>>> 
>>> As discussed/agreed with Kenneth, the sharing-preserving behavior is
>>> by default disabled, .... and we are depending on you guys for the
>>> remaining testing.
>>> 
>>> ...
>>> 
>>> Feedback and comments are welcome.
>>> 
>>> Kostis (and Nikos)
>> 
>> Hi all,
>> 
>> It has been about three weeks since the pull request for the sharing
>> preserving implementation (#494) was submitted and I was wondering
>> whether you had the chance to review it and/or test it more extensively.
>> 
>> Two weeks ago, Nikos has also submitted another pull request (#507),
>> which this time contains only tests, not any code changes. This pull
>> request appears here:
>> 
>>   https://github.com/erlang/otp/pull/507
>> 
>> The tests in them check if the use of constants creates dangling
>> pointers after a module is unloaded. Unless we are missing something,
>> these tests verify that the sharing-preserving implementation (when the
>> flag is enabled) handles constants properly. So, unlike what was
>> mentioned in my previous mail which is quoted above, the current
>> sharing-preserving implementation seems to be safe w.r.t. code
>> unloading/upgrade because the runtime system actually does traverse the
>> heaps and copies constants when the constant area of a module is
>> unloaded/purged.  So, unless you can come up with a test that shows that
>> the current sharing-preserving implementation is unsafe, we are
>> considering the implementation complete.
>> 
>> It would be nice to get some confirmation that it works or some reaction.
>> 
>> Cheers,
>> Kostis
> 
> There is a risk of creating dangling pointers after a module is unloaded when only passing constants by reference. That is, we cannot accept this pull request as is.
> 
> As part of code:purge() (and code:soft_purge()) the code_server will call erlang:check_process_code() for all processes currently alive before actually purging the module. The check_process_code() call will ensure that all references to the module from the process is gone (or fail in the soft_purge case). Each process is checked separately and this while the system continues executing.
> 
> The problem occurs when a process that has not yet been checked sends a message containing a constant to a process that already has been checked. Another scenario is that a process is spawned with a reference to a constant while the check process code operations are ongoing from a process that not yet has been checked. In these cases you *will* get dangling pointers to constant-pools that have been removed.
> 
> In the tests you have written, constants are passed before the purge operations have begun which is expected to work. The problem only occurs when a not yet checked process passes constants to processes that are expected to be clean while the code:purge/code:soft_purge operation is ongoing.
> 
> We also got a bit surprised that the following lines were commented out in the tests, and we didn't find any other purges:
>  %true = code:delete(module_with_constants),
>  %true = code:soft_purge(module_with_constants),
> 
> When removing the comments two of the testcases failed.
> 
> These are the branches we've looked at:
>  https://github.com/nickie/otp/commits/refactor
>  https://github.com/nickie/otp/commits/mod_const_tests
> 
> Regards,
> Rickard



-- 
Nikolaos S. Papaspyrou, Associate Professor | Tel:  +30-210-7723393, fax: 2519
National Technical University of Athens     | Home: +30-210-7524801
School of Electrical & Computer Engineering |----------------------------------
Software Engineering Laboratory             | E-mail: nickie@softlab.ntua.gr
15780 Zografou, Athens, Greece              | URL: www.softlab.ntua.gr/~nickie/

**Comment by psyeugenic** [comment]
Merged to master with several changes, ticket OTP-12590.

**Pull request closed without merging**
