### PR TITLE
ssl: Improve active emulation

### PR DESCRIPTION
**Pull request by IngelaAndin**
If using active once sockets and the socket is closed and all data is already
delivered it is desirable that ssl:setopts(S, [{active, once}] shall succeed
and an active close message be sent instead of ssl:setopts returning {error, closed}
This how gen_tcp/inet behaves.

Example of client side:

> {ok, S} = ssl:connect("localhost", 9999, [{active, false}]).
{ok,{sslsocket,{gen_tcp,#Port<0.10>,tls_connection,
                        undefined},
               [<0.120.0>,<0.119.0>]}}
> ssl:setopts(S, [{active, once}]).
ok
> flush().
Shell got {ssl,{sslsocket,{gen_tcp,#Port<0.10>,tls_connection,undefined},
                          [<0.120.0>,<0.119.0>]},
               "foo"}
ok
> ssl:setopts(S, [{active, once}]).
ok
> flush().
Shell got {ssl_closed,
              {sslsocket,
                  {gen_tcp,#Port<0.10>,tls_connection,undefined},
                  [<0.120.0>,<0.119.0>]}}
ok
> ssl:setopts(S, [{active, once}]).
{error,closed}
> flush().
ok

### CODE REVIEW

**Comment by IngelaAndin** [comment]
Updated implementation to avoid busy loop waiting.

**Comment by bmk** [comment]
Is it necessarily a good idea to be "compatible" with gen_tcp?
What if you want to start using 'socket' directly?

**Comment by IngelaAndin** [comment]
We would still want to have the active option even if we start using socket directly. However the user can should not count on that ssl:setopts will always return ok, neither does inet:setopts.  But as we anyway need the mechanism for the connection process to linger after the internal socket is closed by the peer, as there might be more data to deliver, we might as well linger so that we can send a close message to the processes doing ssl:setopts(S, [{active, once}]).  I think it is the least surprising thing to do.

**Comment by bmk** [comment]
I was only talking about the gen_tcp behaviour "emulation" in this case.
Having an active feature is fine, since its conventent.
I think my point was that ok does not mean ok in that case. The actual result may instead come at "some" later time.

**Comment by IngelaAndin** [comment]
I would find it more surprising if setopts returns {error, closed}  and then you get a closed message too.

**Comment by bmk** [comment]
Ok. I thought we where discussing *either* alt A or alt B not both.

**Review by peterdmv — APPROVED** [review]

**Review by bmk — APPROVED** [review]

**Pull request merged**
