### PR TITLE
Make events of gen_statem enter calls

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
Due to the recent mail list thread about [changing states in state enter call](http://erlang.org/pipermail/erlang-questions/2018-June/095628.html) I have for evaluation created an alternative implementation where state enter calls are instead regular events.

The events are still restricted in that they may not be postponed nor inserted, to avoid the confusion those possibilities might induce.  These are the only restrictions, so it has become possible to change states from the state enter event callback, and also to insert events.

The `gen_statem` code is a bit simplified, and also the description of this feature, I think, so this might be a better feature model.

[Reference Manual](http://erlang.org/~raimo/gen_statem-enter-event/lib/stdlib-3.5/doc/html/gen_statem.html)
[User's Guide](http://erlang.org/~raimo/gen_statem-enter-event/doc/design_principles/statem.html)

The reason we can not _just do this_ is that the change is at least theoretically backwards incompatible.  The cases I have managed to identify are:
- When using `{repeat_state,...}` from a state enter event callback the repeated call will have `OldState` as _this_ state instead of with state enter calls where it is the original old state
- When using `{timeout,0,_}` from a state enter event callback multiple times thanks to _also_ using `{repeat_state,...}` the _first_ one will be delivered instead of with state enter calls where the _last_ one is
- When using other timeout 0 timeouts i.e `state_timeout` and generic timeout in the same way as in the previous point all will be delivered instead of only the last

All points both boil down to the change that with state enter events a `{repeat_state,...}` return tuple causes a state change, but with state enter calls the state change consists of all calls repeated this way that collects to one set of state transition options where the last wins.

So the backwards incompatibilities are only detectable in rather odd cases but still possible to encounter.

Do you like this model for handling state entry code, or the old one.  I think this one is maybe neater, but the question is if the change is worth the small backwards incompatibility danger.

Opinions?!

### CODE REVIEW

**Comment by ferd** [comment]
I have a question for:

>   When using `{repeat_state,...}` from a state enter event callback the repeated call will have `OldState` as _this_ state instead of with state enter calls where it is the original old state

So let's say I moved from `off` to `on` state, and in the `enter` event of `on`, I repeat the state. On the first call I had `OldState` as `off`. On the new call it should be what exactly?

I decided to dive in the docs to see if I could find the answer. First:

> The gen_statem keeps the current state, or does a state transition to the current state if you like, sets NewData, and executes all Actions. If the gen_statem runs with state enter events, the state enter event is inserted again, see type transition_option(), otherwise repeat_state is the same as keep_state. 

I go to `transition_option()` which further down has a paragraph saying:

> If state enter events are used, and either: the state changes, it is the initial state, or one of the callback results repeat_state or repeat_state_and_data is used; the gen_statem inserts an event of type enter with content OldState before all other enqueued events. 

So that's not super clear either. But let's see the two cases possible anyway:

- _the call repeats with the same `off` as `OldState`_: there is no way to move out of where we were without tracking some information in Data instead of on the state itself.
- _the call repeats with `on` as `OldState`_: we lose the ability to know when we first start the worker unless you avoid using `repeat_state` but even then, that's not safe because of `enter_loop` anyway

The second point is the current state of affairs as the current doc on erlang.org states:

> Note that a state enter event will be generated right before **entering the initial state even though this formally is not a state change. In this case OldState will be the same as State, which can not happen for a subsequent state change, but will happen when repeating the state entry**.  

I assume the only interpretation that makes sense is that `State =:= OldState` without risking some major breakage.

----

Other comment on your other points:

> When using {timeout,0,_} from a state enter event callback multiple times thanks to also using {repeat_state,...} the first one will be delivered instead of with state enter calls where the last one is

If state entering is now an event, I expect 100% that this event unsets the `timeout` that was in place as if the event was already in the mailbox. There's no scenario where it makes sense that I handle an event, set a timeout to receive once no events come in, then after that receive the timeout I set before handling the event that let me set the new timeout!

If the timeout is not unset by the `enter` event, it's not an event, or the timeout is broken.

> When using other timeout 0 timeouts i.e state_timeout and generic timeout in the same way as in the previous point all will be delivered instead of only the last

How? I mean if I'm using `enter` as an event, I expect a transition to happen.
Here's the current docs:

> Any event cancels an event_timeout() so a zero time event time-out is only generated if the event queue is empty.
>
> A state change cancels a state_timeout() and any new transition option of this type belongs to the new state. 

Since the `enter` event _should_ change the state transition pair (`(off, on) -> (on, on)`) then it wouldn't make sense that this is _not_ considered a state change and that it wouldn't reset the timers.

----

On a more personal note, I've been reviewing the design of gen_statem since the initial ones in a giant github thread some time in prior years, and even as someone who is familiar with the thought process, objectives, current implementation, documentation, and other mechanisms of gen_statem, along with generally being perceived as an Erlang expert, _I personally find gen_statem to be critically confusing_.

The only way people survive with gen_statem is to pick a subset of the features, and stick to them. Here's a snippet of text from a book on human errors from the early 90s (_Behind Human Error_ by Woods):

> Designers frequently fail to appreciate the cognitive and operational cost of more and more complex modes. Often, there are pressures and other constraints on designers that encourage mode proliferation. But in particular cases, the benefits of increased functionality may be more than counterbalanced by the costs of learning about all the available functions, the cost of learning how to coordinate these capabilities in context, and the cost of mode errors. Users frequently cope with the complexity of modes by "re-designing" the system through patterns of use, e.g., few users may actually use more than a small subset of the resident options or capabilities

I believe this is exactly what we're getting with gen_statem. We've got many types of timeouts (state, inactivity, and just general timers as well), with many types of queues (postponed events, injected events, those in the mailbox), with some half-matching events (enter events that are but also are not events).

Those all ended up working together to really muddy the waters on the following concepts:

- what is an event
- what is the event order
- what is a state transition

Considering we're working on a finite state machine abstraction, not knowing for sure what is or is not an event and not being really sure what constitutes a state transition is one hell of a dreadful position to be in. Sure there is a selective receive emulation, but it's now hard to figure out how it can even make sense to be used. It's even harder with special actions like 'repeat_state' which aim to be equivalent to 'next_state' but is not really because it reenqueues events and I can't remember all of the things. Does `repeat_state` cancel state_timeouts or it's not really repeating the state and it just cheats enter calls? That appears to be undocumented, and I might have to go read the source to know, or devise an experiment to figure it out.

I personally cannot keep a mental model of gen_statem. When I teach it, I teach a subset only. That's the only way we can make things reliable on a larger team. Ignore a bunch of features to avoid confusion. This is the C++ approach to things.

I would probably advise to either:

-  make `enter` a real event, which means it works like any other event in the stack. You can postpone it, you can insert it with `next_event`, it can reset timers, and do all of that stuff.  It just happens to be a special event that gets created with `next_event` implicitly by the gen_statem implementation. It is likely going to be stuck keeping its current format to avoid exploding stuff (an `internal` event with the content `{enter, OldState, NewState}` would make most sense under this model), but that's what we have to live with. This breaks backwards compatibility. 

- keep `enter` a distinct non-event. It is a special form of callback. It does not reset or impact pre-registered timers by simply existing, it cannot be created by the user, replayed (other that by reentering the state), or postponed by the user willingly. Its return values are limited and a subset of what actual events can do.

The first recommendation basically removes cognitive load from the developer by removing a mechanism (enter calls) and only keeping events. As a user, I can make a simpler mental model of things.

The second recommendation removes cognitive load by segmenting enter calls away from events. They do not impact each other. Hell, the best way to drive that further would have been to give them a dedicated callback (`handle_enter(...)`) to make it clear that they are not on the same playing field. This lets the user reason about them in distinct bounded contexts, and prevents them from thinking they _are_ events when they are not.

The current implementation does neither. It half-and-halfs the whole thing: state enter calls are now events, but not full blown events. They impact timers and state transitions in ways nothing else does. I think it's not moving in the right direction. It's a patch that seemingly simplifies things by allowing more return values in their respective callbacks, but in practice keeps all the underlying conceptual complexity in place. The user still has to keep in mind that even if they mostly act like events, enter events are not actual events. I think this does not address the actual source of the problem.

**Comment by RaimoNiskanen** [comment]
Hello @ferd, as usual I really value your opinions.  It is good somebody cares!

I am actually happy with the current implementation of handling state enter code, that is; state enter calls. But after having to explain that they are not events and having to motivate their restrictions for a number of times I thought it was time to take a thorough look at the as far as I can see best alternative, so I implemented it and created this pull request to find out how good the idea is.

This pull request aims to be adhering to your first recommendation, and not accepting it is your second recommendation.  With the exception that I still fancy restricting `enter` events from being inserted and postponed.  It is a bit arbitrary restrictions, but I think they are good to have because the `enter` event is the only one automatically inserted by a state change, so both postponing it to a later state, and inserting it, would be really weird things to do...  This restriction would be easy to remove, anyway, so this is an orthogonal detail.

Regarding the `{timeout,0,Msg}` not being cancelled by an `enter` event; I messed up!  It is inserted in the wrong place in the code so it is not detected by the timeout logic.  As you point out the timeout is broken. Of course it should be cancelled by the `enter` event!  I will get back with corrected code!

I am sorry you find `gen_statem` "critically confusing".  I hope the documentation can be reworked to remedy that.  I agree that there should be no more new features.

Regarding your other comments I think they circle around "what is a state change?"  and here the documentation has become, as you say, muddy.  There is both the view from established state machine theory where a state change occurs regardless of which state you change to (even if it is the same), and the special treatment a state change gets in `gen_statem` when the new state =/= the current state, that is: postponed events are retried and a state enter event is inserted.  We need to improve the terminology in the documentation here!

Suggestion: we can talk about "state transition" where the new state is any state including the old state, and "state change" where `NewState =/= OldState`.  Does this sound good?

To answer your direct questions:
* If you change from state `off` to `on`, in the `enter` event `OldState =:= off`, and if you repeat the state the new `enter` event has got `OldState =:= on` since this second state transition is from state `on` to state `on`. 
* The `{repeat_state, ...}` return value is the same as `{keep_state, ...}` which is the same as `{next_state, ...}` with `NewState =:= State`, _except_ that it inserts an `enter` event (with `OldState =:= State`).
* State timeouts are cancelled and postponed events are retried only due to a state change (state transition with `OldState =/= State`. (The pull request cancels state timeouts due to `{repeat_state, ...}` but I now realize that it is a misfeature).

I hope we can clear up the questions so this proposition can be judged on its technical merits, and that we can make the documentation more comprehensible (with or without accepting this pull request) as well.

**Comment by ferd** [comment]
Good to hear about the timeout thing being a bug. This was a bit confusing to me.

I think the suggestion differentiating between _state transition_ and _state change_ is probably good under the current implementation, but again, I would expect a state transition to therefore happen every time `{next_state, ...}` is returned instead of just `{repeat_state, ...}` -- As you said,  a state change occurs regardless of which state you change to.

So if we have state transitions and state changes as two distinct concepts, currently the state enter calls mostly respect the idea that it only happens on a _change_, with the exception of `repeat_state`, which I guess you could see as a way to trigger a _change_ to the current state. If that is so, I would expect state timeouts to be reset by a `repeat_state` as well, otherwise you get an inconsistent behaviour: `repeat_state` is not used as a way to manipulate the FSM state and transitions, but as a fancy GOTO to jump around calls.

In the current PR, I believe the same point from the previous paragraph still applies: there's currently an inconsistency between a definition of state change and of state enter calls when comparing them to state timeouts. I also _understand_ why it would be weird to postpone the enter calls, so for me that points to them _not being events_.

This does not mean that the changes from this PR are all wrong. The question becomes whether the restriction on enqueueing or changing events from that call is valid or not. I think the original design still makes sense, but the confusion strictly comes from overlap in callbacks.

If instead of:

```erlang
handle_event(enter, OldState, NewState, Data) ->
    ReturnEnter;
handle_event(cast, Event, State, Data) ->
    ReturnEvent.
```

We had:

```erlang
handle_enter(OldState, NewState, Data) ->
    ReturnEnter.

handle_event(cast, Event, State, Data) ->
    ReturnEvent.
```
I suspect that we wouldn't have as much confusion. People are not surprised in `gen_server` that you cannot return a `{noreply, ...}` in `code_change/3` since it's a distinct callback. But if `code_change` was handled as `handle_call(code_change, {OldVsn,NewVsn}, State) -> {ok, NewState}` you can bet that people would rightfully be wondering why it can or cannot reply.

It would feel more natural, at the very least, to have distinct capabilities to return value. Again, we could still decide it makes sense for `ReturnEnter` to force a state transition again, but the type signature and expectations would probably be clearer.

The problem of this proposal is figuring out how to go there. There's backwards compatible ways to do it, but they are certainly not going to make for clean docs, and may just make things worse if we look at the whole situation holistically. It's an interesting thought experiment though. 

In any case, I think my position is that if enter calls are to become enter events, they should be able to do all the things an event would, even when it's a bit odd. For a comparison, we never really asked if it would be weird to postpone internal events, but it hasn't been a problem so far even if there should be no reason to ever do it (why are you sending it there?!). If we want to expand their capabilities but not give them all, then that's fine, but I would not call them enter events. We remain in the situation we're in today, just with fewer things being denied.

**Comment by RaimoNiskanen** [comment]
I'd say that a _state transition_ occurs whenever the event handler returns to the `gen_statem` engine with _any_ of the `next_state`, `keep_state*` and `repeat_state*` values (i.e any value except any of the `stop*` values), and that a _state change_ is a _state transition_ where the state before and after the transition is not equal (`=/=`), so it has to be a `next_state` with `NewState =/= State`.

A _state change_ is the same as a _state transition_ with 3 more things that happen:
* Postponed events are retried (the event queue pointer is moved to the oldest postponed event)
* The state timeout is cancelled
* A state enter event is inserted

Of these 3 things I would like `repeat_state*` to only insert a state enter event, since then `repeat_state*` will be the same as `keep_state*` if the machine runs a callback mode without `state_enter`.  If it `repeat_state*` also canceled the state timeout that would be a subtle difference which I do not like and that is awkward to explain.  And I don not want `repeat_state*` to also retry postponed events since the state is the same hence event handler does not change so there is only inefficiency in this.  I prefer `repeat_state*` to do only 1 thing, not 2 out of 3 things.

You have a good point in that if `handle_enter/3` would be a callback of its own there would be no surprise if the set of allowed return values was different from that of `handle_event/4`.  Unfortunately this conflicts with my pet peeve and biggest reason I had to create `gen_statem`; that the callback mode `state_functions` must facilitate gathered state code.  Therefore event entry must be implemented by the normal event handler for the state.

You are also right in that some event types are weird to postpone and insert.  But `internal` events are actually  intended to be possible to use in the same way as external events so you can for example  pre-process external events into inserting an `internal` event and still decide to postpone it in some state.  For `timeout` and `state_timeout` events, on the other hand, I think that they would always be weird to postpone and insert.  In hindsight maybe that should not have been allowed.

Restrictions on events can be a good thing.  When you debug especially someone else's code it is good to know that an `enter` event was not accidentally postponed somewhere else with a completely weird `OldState`, nor can it have been deliberately inserted so I do not have to search for that.  The same would have been good to know about timeout events...

But if we have no restrictions on any other events...
Bummer! I should have restricted timeout events!

**Comment by IngelaAndin** [comment]
I have found one use of repeat_state in the  DTLS state machine and it is to re-run the enter code
that will reset the state timeout that is used as retransmission timer for DTLS over UDP handshake flights. But when receiving a change cipher spec there will be a flight change without changing states, hence the use of repeat_state.

I was thinking maybe we could refer to enter notifications instead of enter events. That is how I perceive them, as a chance for me to for instance start a timer or do some other initiation before event handling in the state starts.

**Comment by IngelaAndin** [comment]
An other thought about the documentation could be to split it into one state driven and one  handle_event driven part. Where you try to avoid too much comparison. Maybe have a special comparison section last if needed. Then most users can concentrate on the state driven documentation and do not have to worry about the event driven one. I know the event driven one has greater flexibility but I also think it adds to the complexity and  makes the code less readable.  The last part may be be subjective but that is how I feel.

**Comment by RaimoNiskanen** [comment]
I have corrected the event timeout 0 bug pointed out by @ferd, and improved the documentation also starting with what he deemed hard to find.

**Comment by RaimoNiskanen** [comment]
@IngelaAndin: I do not think "enter notifications" is a good idea. Up to OTP-21.0 they are called "enter calls" to distinguish them from events, and I think that is a good name.  This pull request wants to make them into events, albeit I suggest events with two small restrictions, but the pull request's intention is that they shall behave like events, so calling them something else would be a failed pull request.

Regarding splitting the documentation:

I think splitting the Reference Manual would be confusing.  It should describe all aspects in one manual.  If it should describe only callback mode `state_functions` and then at the end or in a separate manual describe the difference for `handle_event_function` it would be very confusing since for example the allowed type of the state changes from `atom()` to `term()` and all function signatures reflect this possibility, so the reference manual that only wants to describe `state_functions` still has to explain why the state can be any term.  And I bet there are other oddities if you try to ignore `handle_event_function` in the reference manual.

For the User's Guide it is already focusing on `state_functions` since most examples are with this mode.  But to sweep `handle_event_function` under the rug into some final section would not be good, I think.  Both modes have their use cases and followers and need to be equally visible, although I am myself also mostly in the `state_functions` camp (at least defending its look-and-feel).

**Comment by IngelaAndin** [comment]
@RaimoNiskanen  We can stick with enter calls, I am trying to argue against them being events. Not
necessarily how you implement it but what the semantics should be. In some ways I think it is an event, but it is a special event and maybe it is less confusing to call it something else then explaining all restrictions.

About the documentation I was thinking mainly about the UG. And I do not think you should hide the
handle_event mode I just meant they are describe separately maybe it is easier for people with  no prior knowledge to grasp. If you know nothing about gen_statem and very little about automata theory
it might be hard to have to think about both concepts at once. But maybe last version is like that, have to read it again! And I think that the handle_event-mode is more complex and although someone might find it useful, I think not all users will.

**Comment by ferd** [comment]
> Of these 3 things I would like `repeat_state*` to only insert a state enter event, since then `repeat_state*` will be the same as `keep_state*` if the machine runs a callback mode without state_enter. If it `repeat_state*` also canceled the state timeout that would be a subtle difference which I do not like and that is awkward to explain. And I don not want `repeat_state*` to also retry postponed events since the state is the same hence event handler does not change so there is only inefficiency in this. I prefer `repeat_state*` to do only 1 thing, not 2 out of 3 things.

The way I see it is in trying to re-frame `repeat_state` in terms of how it impacts the state machine: it forces to re-enter the state. What I'm understanding now is that I interpreted it as "repeat the FSM state" whereas you meant "repeat the state enter call", which are _wildly different things_.

Effectively what you have here (particularly if enter calls are events) is almost the action `{next_event, enter, CurrentState}` rather than a full return value -- with the caveat of checking if enter events are allowed in the first place. It has never been obvious to me before that `repeat_state` should have been parsed as `maybe_repeat_state_enter_call` -- if I were to repeat the state, I would have expected regular state transition mechanisms to kick in, not just one of them.

This is a very specific instruction that is wrapped under a more generic sounding name.

> Restrictions on events can be a good thing. When you debug especially someone else's code it is good to know that an enter event was not accidentally postponed somewhere else with a completely weird OldState, nor can it have been deliberately inserted so I do not have to search for that. The same would have been good to know about timeout events...

They can be a good thing when users expect their behavior. When their behavior is unexpected, they have the opposite effect from what you intended. 

I agree that enter events being postponed would be weird, but for me, again, this just means that enter calls should not be events. How weird is it to have one event that is also a "special non-postponable events of which no other kind exist except that one". 

Just don't call it an event or pretend it is one? They're pretty much the only event type to need exceptions. Just don't make them events.

This does not mean that enter calls callbacks cannot or should not be allowed to impact FSM state, this is purely a terminology problem vs. the impact it has in the programmer's mind when they are learning and using the behaviour. I believe I am agreeing with @IngelaAndin on this front.

**Comment by RaimoNiskanen** [comment]
I just rebased the branch into one commit with improvements and optimizations that got into the code during the rewrite, and one that contains the change from state enter calls to state enter events.

**Comment by RaimoNiskanen** [comment]
Rebased to get rid of merge conflict prediction

**Comment by RaimoNiskanen** [comment]
The PR is rejected.

The first two commits are merged to 'master', though (latest first):
4d636ebe55ddd557f62885b724076c1c146f62dd Improve user's guide on time-outs
61935c77915a8e206a82cba1c9c9f64be462905d Clean up and optimize code and doc
since they are just code cleanup and documentation improvements, and not the key point of this PR.

**Pull request closed without merging**
