### PR TITLE
Extra -mode flags are ignored with a warning

### PR DESCRIPTION
**Pull request by Kuroneer**
Prior to this change, providing multiple `-mode` flags to erl would start the code server as 'interactive', regardless of their value:
`erl -mode embedded -mode embedded` would start in interactive mode (vm.args included).
With this change, the last `-mode` flag overrides the previous ones.

A couple of notes:
* I haven't found in the documentation how `erl` would behave if multiple `-mode` flags are feed to erl. I believe that this is the correct behaviour, but, since it changes the current one, if you think it's better just to clarify the documentation I'm good with that too.
* I've commited init.beam as I'd rather have the whole commit buildable, but I'm not sure I've done it as the release mandates (I just `erlc init.erl`). I think it's rather dangerous to have init.beam bytecode from a non-maintainer running around, but I'm not sure how to proceed in this case.
* Should this be mentioned in the mailing list? The contribution guidelines state that ```Major changes or new features in ERTS, Kernel, or STDLIB will need an EEP or at least a discussion on the mailing list.```, and I think it merits a mention there, but I'm not so sure.

### CODE REVIEW

**Comment by josevalim** [comment]
For what is worth, we had a similar issue with the -sname and -name flags and the choice was to use the first one but log that. In Erlang/OTP 22 we do this:

```
$ erl -sname foo -sname bar
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

=WARNING REPORT==== 17-May-2019::21:22:52.769667 ===
Multiple -sname given to erl, using the first, "foo"
Eshell V10.4  (abort with ^G)
(foo@josemac)1>
```

So maybe it is better to stay consistent and keep the first one with a log?

**Comment by Kuroneer** [comment]
In that case, I'll update the PR with that behaviour, thanks!

**Comment by Kuroneer** [comment]
I've updated the PR with the changes discussed above and I've rebased and squashed the commits so that init.beam is no longer modified.

**Comment by garazdawi** [comment]
> I haven't found in the documentation how erl would behave if multiple -mode flags are feed to erl.
Yeah, there is none, though there should be. As José mentioned, we recently merged a PR where the first argument was the chosen one. I'm starting to doubt that I made the right decision there, but maybe we'll have to live with that now. I need to think some more about this.

> I've commited init.beam as I'd rather have the whole commit buildable, but I'm not sure I've done it as the release mandates (I just erlc init.erl). I think it's rather dangerous to have init.beam bytecode from a non-maintainer running around, but I'm not sure how to proceed in this case.

Yes, please remove the beam file from the PR. We'll push a commit to this PR with a beam file that we have built.

> Should this be mentioned in the mailing list?

No need.

**Pull request merged**
