### PR TITLE
Increased left-nav width for readability

### PR DESCRIPTION
**Pull request by emacstheviking**
It just makes it easier to read stuff. For example, gen_server functions are now totally visible, no more guessing.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Hi

Did you get the email regarding the license change?

**Comment by emacstheviking** [comment]
If I said "What email?" would that answer your question.

If it means accepting new T&C-s then I am more than happy to do so.

Thanks,
Sean.

**Comment by zhird** [comment]
Hi Sean, 

Sorry for taking so long, I didn't see this until now! What you need to do is sending the below to license-change@erlang.org. We'll merge this as soon as we have your email. 

Cheers, 
Zandra

Subject: 
Confirmation of license for contribution to Erlang/OTP 
Body: 
I hereby confirm that I am the copyright holder or authorized by the copyright holder of this contribution. As such I hereby confirm that all contributions made to Erlang by me or on behalf of me, hereby is licensed under the Apache 2.0 License [http://www.apache.org/licenses/LICENSE-2.0].

I am aware that any future submissions from myself also will be considered to be
licensed under Apache 2.0 unless I expressly state otherwise.

**Comment by emacstheviking** [comment]
I have sent the email.

:)

Hopefully you till get it soon.

All the best,
Sean.

**Comment by zhird** [comment]
Merged to master.

**Pull request closed without merging**
