### PR TITLE
Fix regression in how ssh handles private keys containing CRLF

### PR DESCRIPTION
**Pull request by lexmag**
Happened in 65b2e2f81559c8f467e89037d316d217a4017c31.

### CODE REVIEW

**Comment by lexmag** [comment]
Note, I updated `lib/ssh/test/ssh_pubkey_SUITE_data/old_format/id_rsa` to contain CRLF.

**Comment by lexmag** [comment]
Done.

**Comment by HansN** [comment]
ssh_file.erl  is updated in the github repository.  I included the handling of \r\n line ends but the space fixes are not there.  Please rebase this branch on maint and change it as needed so it could be tested for the next maint release.

**Comment by HansN** [comment]
Closed due to inactivity.

**Pull request closed without merging**
