### PR TITLE
[RFC] DTLS for R19

### PR DESCRIPTION
**Pull request by RoadRunnr**
This is my current state of DTLS. It is not a 100% production ready version, but I believe that it still is a somewhat large step toward a fully working DTLS stack.

I won't have much time the next months to continue working on this, so I hope that someone else can use these changes as a starting basis to finish the DTLS support.

The changes are broken down into smallish, topic oriented pieces for simple reviewing. Not all changes are perfectly ordered. Sometimes an earlier change might reference a function that is introduced much later.

# What is working:
* DTLS over UDP (with limitations, see next section)
* basic tests (yeah)

# What is missing:
* Documentation
* tests for
  * OpenSSL interoperability
  * packet loss during handshake
  * packet reordering during handshake

# TODO

## Refactoring

There are some code parts that should be unified and/or deduplicated, things that come to mind:
* SNI handling
* (d)tls_connection:handle_handshake
* payload data handling (the only difference is that DTLS does not support HTTP decoding)
* alert handling

The logic of handing the version from the (D)TLS modules to the generic SSL modules needs to be reviewed. There are multiple methods in the generic SSL modules that have to explicitly test for the DTLS version in order to handle them correct. Normally that should be handled by passing dtls_v1:corresponding_tls_version into them, but the call sequence prevent this (i.e. the same version argument is encoded into a handshake and then used for version dependent data handling).

## Packet reordering and loss

This is conceptually working but untested. Also I doubt that every conceivable situation is handled correctly. This also goes hand-in-hand with packet loss detection and flight resending.

Resending is completely left out and the integration with reordering and the connection state handling needs to be validated.

The biggest problem here is that old connection state needs to be kept around to decode incoming resent flights and to be able to resent flights our selfs.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: dtls: adjust API constrains on SSL app to permit UDP socket demuxer
dtls: sync dtls_record DTLS version and crypto handling with TLS
ssl: disable SSLv2 compatibility handling in handshake history


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I hope that I can. Thank you very much for the contribution.  Actually I am currently working with testing
ssl on a new state machine behaviour that we are working on, that I think will make DTLS implementation easier. We did not forget about DTLS it just has been hard to prioritize it highest :(

**Comment by maxlapshin** [comment]
Ingela, is it possible to do something to make this patch appear in erlang?

**Comment by achowdhury918** [comment]
Hi IngelaAndin,
Do you have any ETA when we can get usable DTLS in Erlang? Please, let me know.
Thanks.

**Comment by IngelaAndin** [comment]
Hard to say, but it is the plan to move it forward for 19 and take some of the work from this PR.

**Comment by hachreak** [comment]
:+1: 
I hope it will be released soon on OTP because [gen_coap](https://github.com/gotthardp/gen_coap/issues/1) need it to implement CoAP on DTLS. :)

**Comment by IngelaAndin** [comment]
Some of the commits here addressing event handling will be solved by ssl moving from gen_fsm to gen_statem once this transition is made I will start looking into including other parts of this PR. I can not promise it will be finished for 19.0 but finally DTLS will be moving forward again :)

**Comment by RoadRunnr** [comment]
@IngelaAndin could you share a draft the gen_statem rewrite? I might be able to begin porting some of the DTLS changes already.

**Comment by IngelaAndin** [comment]
There is now a branch in my git repo ingela/ssl-gen-statem/OTP-13464
Note that it is not finished. There are some small improvements to remove all code not needed by the new implementation, and all dialyzer specs are commented out and not updated.  The real version will be in release candidate 1 for 19 coming soon.

**Comment by RoadRunnr** [comment]
rebased to master, TODO still remain

**Comment by RoadRunnr** [comment]
@IngelaAndin 

> There is now a branch in my git repo ingela/ssl-gen-statem/OTP-13464

Do you have a newer version somewhere? There are some important changes in master (signature algorithm selection) that are not your gen_statem conversion, yet.

**Comment by IngelaAndin** [comment]
I force pushed my  ingela/ssl-gen-statem/OTP-13464 branch. Now it is getting close to a mergable 
state. I made some very basic DTLS adjustments. It has dialyzer specs.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: ssl: disable SSLv2 compatibility handling in handshake history
dtls: forward info messages from transport to protocol handler
dtls: pass corresponding tls version into generic ssl functions
dtls: make hello_verfiy configurable and handle sequence numbers for it


----------------

I am a script, I am not human 

----------------

**Comment by RoadRunnr** [comment]
Note: I'm in the progess of porting the changes from this PR to Ingela's gen_statem work. My working branch is here: https://github.com/RoadRunnr/otp/tree/ssl-gen-statem/DTLS

**Comment by RoadRunnr** [comment]
rebased to master with gen_statem support, yeay!

The status and TODO's from the initial message still apply. This version is passing and failing the same tests that older version was. Only the ssl_basic_SUITE was tested!

**Comment by IngelaAndin** [comment]
Nice :) Will look closer on Monday, we have a public holiday now.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: dtls: adjust API constrains on SSL app to permit UDP socket demuxer
dtls: sync dtls_record DTLS version and crypto handling with TLS
dtls: implement handle_common_event and dtls_handshake_events
ssl: disable SSLv2 compatibility handling in handshake history


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Thank you very much for your efforts to bring DTLS implementation forward. Soon some of your commits will start showing up in master. I am cherry picking and also making some other commits.
So the PR on this form will not be included.

**Comment by erszcz** [comment]
@IngelaAndin 
Sorry for digging up and old issue, but I think it's the most convenient place to ask the question:
there's support for RFC 5489: ECDHE_PSK Cipher Suites for Transport Layer Security (TLS) cipher suites in @RoadRunnr's work at https://github.com/RoadRunnr/otp/commit/b163024d82cbae444e21f4ea37d1b25c4e375e0e, but I can't find the same suites in erlang/otp/maint-20.
Is adding support for these ciphers anywhere in the OTP roadmap (given there's some prior work available)?

**Comment by RoadRunnr** [comment]
----- On Jul 21, 2017, at 1:10 PM, Radosław Szymczyszyn <notifications@github.com> wrote: 

> [ https://github.com/ingelaandin | @IngelaAndin ]
> Sorry for digging up and old issue, but I think it's the most convenient place
> to ask the question:
> there's support for RFC 5489: ECDHE_PSK Cipher Suites for Transport Layer
> Security (TLS) cipher suites in @roadrunnr's work at [
> https://github.com/RoadRunnr/otp/commit/b163024d82cbae444e21f4ea37d1b25c4e375e0e
> | RoadRunnr/otp@b163024 ] , but I can't find the same suites in
> erlang/otp/maint-20.
> Is adding support for these ciphers anywhere in the OTP roadmap (given there's
> some prior work available)?

Very strange. I though I had them in some them in some pull request. Took me quite some searching to find them again. 

They are part of this branch: https://github.com/RoadRunnr/otp/commits/ssl_anon_certs. 
It seems that I never included them in a PR. 

From a *very* quick code review, I would think that both changes in that branch are still valid and needed (although they need to be ported to the new SSL stack).

**Pull request closed without merging**
