### PR TITLE
digraph: Document a bad_edge error

### PR DESCRIPTION
**Pull request by jabarszcz**

### CODE REVIEW

**Comment by uabboli** [comment]
Looks good, except that "and" should be "an".

And the diff will be smaller if you keep the newline before "If either of".

**Comment by jabarszcz** [comment]
Good catch, fixed!

**Comment by uabboli** [comment]
Thanks. We'd prefer just one commit. Could you squash them, please?

**Comment by jabarszcz** [comment]
Of course.
This is my first "real" PR and I don't know why but I was under the impression that it was possible to squash when merging. TIL. Thank you for your patience.

**Comment by uabboli** [comment]
The fix will be included in 20.3.

**Pull request merged**
