### PR TITLE
Optimise size calculation for binary construction

### PR DESCRIPTION
**Pull request by michalmuskala**
It turns out it was extremely common to have a following sequence:

    move 0 D1
    byte_size _ D2
    bs_add D1 D2 D

Which is equivalent to just:

    byte_size _ D

Similarly another sequence:

    move S D1
    byte_size _ D2
    bs_add D1 D2 D

Can be optimised into:

    byte_size _ D2
    bs_add S D2 D

Both of those optimisations work with byte_size and bit_size instructions.

### CODE REVIEW

**Comment by bjorng** [comment]
This optimization is not safe if post optimizations are turned off (`no_postopt`). Here is the first compilation failure when running the compiler test suites:

```
Recompile: bs_construct_no_opt_SUITE
bs_construct_no_opt_SUITE: function l/4+112:
  Internal consistency check failed - please report this bug.
  Instruction: {gc_bif,byte_size,{f,0},3,[{y,8}],{x,2}}
  Error:       {{x,2},not_live}:
```

**Comment by michalmuskala** [comment]
Is this caused by the fact that we eliminated a use of a register by omitting the `move` instruction? If so, I can see two paths:
* change the code generation even more so that it doesn't generate such code in the first place 
* do the optimisation somewhere else (e.g. `beam_peep`)

**Comment by bjorng** [comment]
> Is this caused by the fact that we eliminated a use of a register by omitting the move instruction?

Yes.

I am not sure that doing the optmization in `beam_peep` would solve the problem.

A third solution would be to adjust the number of live registers when doing the optimization. That is, change the instruction to:

    {gc_bif,byte_size,{f,0},2,[{y,8}],{x,2}}

**Comment by michalmuskala** [comment]
@bjorng I went with your suggestion of adjusting the live registers. I also restructured the algorithm a little bit which allowed caching and optimizing even more patterns.

**Comment by bjorng** [comment]
Looks good! I have added it to our daily builds.

**Comment by bjorng** [comment]
The test case `exception_SUITE:line_numbers/1` in the emulator tests fails. Otherwise it looks good.

**Comment by michalmuskala** [comment]
Ah, I didn't run the emulator tests, I will see what's wrong.

**Comment by bjorng** [comment]
> The test case exception_SUITE:line_numbers/1 in the emulator tests fails. Otherwise it looks good.

I have looked closer at this. It is not your fault. The problem is that some instructions (for example, some bit syntax instructions) decrements the instruction pointer (I). When an error occurs the instruction pointer may point to the range of the previous line.

This is already a bug in OTP 20 (and earlier). For example for this code:

```
t() ->
    Res = id(x),  %Line number for this line in stack trace.
    Res + 1.

id(I) ->
    I.

```

The loaded code looks like this:

```
00007FD651C967E0: i_func_info_IaaI 0 t t 0 
00007FD651C96808: allocate_tt 0 0 
00007FD651C96818: i_move_call_cf x t:id/1 
00007FD651C96830: i_increment_rIId r(0) 1 1 x(0) 
00007FD651C96850: deallocate_return_Q 0 

```

The increment instruction decrements the instruction pointer so that it will point into the preceding `i_move_call` instruction. If an exception occurs the line for the call instruction will be pointed out.

I will have to think about how to fix this, and come back when I have fixed it.

**Comment by bjorng** [comment]
I have fixed the problem in #1589.

I have added this PR to our daily builds again.

**Pull request merged**
