### PR TITLE
In ssl_tls_dist_proxy, use nodelay for all sockets

### PR DESCRIPTION
**Pull request by legoscia**
On Linux, not using this option leads to occasional latency of 40 ms,
the default delay for Nagle's algorithm.  Let's ensure packets flow
without delays by disabling that.

To reproduce this, first create a certificate and a private key:

```
openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/CN=foo" \
    -keyout erldist.key \
    -out erldist.cert
```

Set ERL_FLAGS to enable distribution over TLS:

```
export ERL_FLAGS="-pa $ERL_TOP/lib/ssl/ebin/ -proto_dist inet_tls \
      -ssl_dist_opt server_certfile erldist.cert server_keyfile erldist.key"
```

Start two nodes:

```
erl -sname foo@localhost
erl -sname bar@localhost
```

Make a sequence of RPC calls from one node to the other:

```
Node = foo@localhost.
[element(1, timer:tc(rpc, call, [Node, erlang, self, []]))
 || _ <- lists:seq(1,5)].
```

(Try this in both directions, as the settings for the "client" and the
"server" can be different.)

Without this change, most of the calls will take around 40 milliseconds:

```
[156164,40342,39854,39993,39958]
```

With this change, the latency drops to less than a millisecond:

```
[47541,275,247,244,245]
```

(The first call takes longer, to set up the connection and do the TLS
handshake.)

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I agree the we need nodaly,  although I think it should be configurable as in  PR #755
We are willing to accept that PR once there is a test case, if you would be willing to look into that it
could speed things up.

**Comment by legoscia** [comment]
I used @tombriden's

**Comment by legoscia** [comment]
I replaced my branch with @tombriden 's, and added a simple test on top of it.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
