### PR TITLE
Remove OSE

### PR DESCRIPTION
**Pull request by garazdawi**
The OSE port is no longer supported and this commit removes it and any changes related to it. The things that were general improvements have been left in the code.

### CODE REVIEW

**Comment by tuncer** [comment]
That was short-lived. May I ask how, why, and if there are OSE installs of Erlang?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by okeuday** [comment]
@garazdawi I am also wondering why.  Isn't OSE usage a good thing?  Is there a reason to not pursue it, like seL4 is a better pursuit due to being open sourced?

**Comment by kqqsysu** [comment]
@garazdawi I want to know  why remove OSE.

**Comment by garazdawi** [comment]
The OSE port was developed for a very specific use case and it was decided that Erlang would not be used there. Since the port was not completed and we have no daily regression running for it, it quickly deteriorated as new features were added to erts and the OSE part was not updated.

If you want to have a working OSE port of Erlang you will have to use 17.4, or better yet you can use the latest branch in my github repo: https://github.com/garazdawi/otp/tree/lukas/ose/master-18.

If someone wants to continue to support it in a fork of their own I'd be happy to answer any questions you might have.

**Comment by garazdawi** [comment]
merged

**Pull request closed without merging**
