### PR TITLE
Remove erlang:display/1 calls

### PR DESCRIPTION
**Pull request by MSch**
I think those are debugging leftovers.

### CODE REVIEW

**Comment by okeuday** [comment]
I agree.

**Comment by psyeugenic** [comment]
LGTM

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by MSch** [comment]
fyi I've (re)licensed my changes under the Apache 2.0 License

**Pull request merged**
