### PR TITLE
compiler: Remove dead code from private-append optimization

### PR DESCRIPTION
**Pull request by frej**
With the decision to not introduce a private append variant of `bs_create_bin` which gracefully tolerates non-binary string arguments, we can remove many code paths in `beam_ssa_private_append.erl` which are never reached as we will never try to track and patch the tail field of a cons.

### CODE REVIEW

**Review by bjorng — APPROVED** [review]

**Comment by frej** [comment]
It turns out that this patch depends on #6855 and maybe #6862, will rebase when it has been merged.

**Comment by bjorng** [comment]
I have merged your other three pull requests. You can rebase now.

**Comment by frej** [comment]
Rebased.

**Comment by bjorng** [comment]
Thanks!

**Pull request merged**
