### PR TITLE
Add a new SSL option; client_cert_verify_fun

### PR DESCRIPTION
**Pull request by Vagabond**
TLS client certificates work by, once the client key exchange in the TLS
handshake completes, the client can send proof it has access to the key
described by the client certificate. It does this by signing a hash of
all the handshake messages sent up to that point on the TLS session. See
RFC 5246 Section 7.4.8 for more details.

This patch allows the user to specify a function to do the signing,
rather than requiring the user to supply the key directly. This is
useful when using a hardware security module, where a key is stored in
such a way that it can not be read out directly, data must be fed into
the HSM to be signed, and the resulting signature is the output.

This is just a WIP to see if people think this feature is useful and implemented correctly. I am happy to write documentation and tests if the basic idea seems valuable.

### CODE REVIEW

**Comment by IngelaAndin** [comment]
We are currently looking into such functionality but it is very much on the drawing table. As far as I understand OpenSSL cryptolib  sign if accessed through the EVP API can take a so called  tokens as input instead of the actual key, if  it has an appropriate engine compiled with the OpenSSL cryptolib. So then the plan is to update crypto to use the EVP API for sign and verify (I think they are the only functions now not using EVP API).  Maybe there would be some other crypto function needed to "load" the engine I am not sure yet how that works.  And then we could have an key option like {token,  Token} or maybe {token, {rsa|ecdsa , Token}} as the application might need to know the type of the key and maybe not all interested applications can find it elsewhere (SSL/TLS can get it from the cert)
and then just pass it along to the openssl cryptolib that takes care of the rest.  Maybe a fun would be desirable also or as part of this solution.

**Comment by Vagabond** [comment]
Do you have any links to what you mentioned? I can't seem to find anything.

I don't have straightforward access to the HSM, which is why I need a callback function like this. I'd love to understand the alternatives and possibly contribute something.

**Comment by IngelaAndin** [comment]
This one I can share
https://www.nlnetlabs.nl/downloads/publications/hsm/hsm.pdf

**Comment by Vagabond** [comment]
Ah yeah, that approach wouldn't be very convenient for me. I would definitely recommend exposing something like the callback interface I propose here in addition to what that document proposes.

**Comment by IngelaAndin** [comment]
Looking at your code again I see that you are purposing a sign fun rather than a key fun. It would probably be interesting to provide that flexibility, I do not think there is enough time to make 20.0 but 
lets keep investigation this.

**Comment by IngelaAndin** [comment]
We have now add support for using OpenSSL engines for HSM support purposes, it is pushed to maint and master. Take a look and maybe make a new PR if there is a need.

**Pull request closed without merging**
