### PR TITLE
Adding <binary>.env file support

### PR DESCRIPTION
**Pull request by dominicletz**
Hey there,

this is an effort to replace the current different behaviors on windows and linux of getting the `BINDIR` variable with a new coherent approach. Reference: https://github.com/erlang/otp/pull/5852#issuecomment-1087202366 by @garazdawi 

This PR doesn't remove `erl.ini` support yet, but instead just adds additional cross-platform support for `<binary>.env` 

The env file follows these rules:
1. It's location is the same as that of the current running binary (`GetModuleFileNameA(NULL, ...);` and `readlink("/proc/self/exe", ...)` 
2. There are three new three new helping environment variables defined before the file is read:
    - `SELF` the name of the binary as found by 1.
    - `SELFBASE` the base directory of the binary as found by 1.
    - `PID` the process id of the running OS process
3. It then constructs the env file search path as "${SELF}.env" and if that file exists opens it and imports all defined environment variables, applying `${}` environment variable substitution.

This allows defining the `BINDIR` and other variables relative to the binary location. For example a `erl.exe.env` file for a windows release inside `App/erts-xxxxx/bin/erl.exe.env` could look like this:

```env
ROOT_DIR=${SELFBASE}/../..
BINDIR=${SELFBASE}
HEART_COMMAND=${SELF}
ERL_EPMD_ADDRESS=127.0.0.1
ERL_AFLAGS=-kernel inet_dist_use_interface {127,0,0,1} -mode interactive -config "${ROOT_DIR}/releases/1.9.1/sys" -boot "${ROOT_DIR}/releases/1.9.1/start" -boot_var RELEASE_LIB "${ROOT_DIR}/lib" -cookie 12345ABCD -heart -name app_${PID}@127.0.0.1
ERL_ZFLAGS=-detached
```

This will launch the release just by running erl.exe directly, with no bash or batch script needed to massage environments. Since after the .env file is processed the `initial_argv_massage` is happening the existing `ERL_*FLAGS` params can be used to define nearly everything.

On linux the corresponding file would often be the `erlexec.env` since on linux usually `erlexec` is the process identity running the beam.

# Benefits

- Unified linux / windows approach to define `BINDIR`
- Less specific `BINDIR` only approach that can be applied to any environment variable and used for `ERL_*FLAGS configuration` (compared to `erl.ini` which is limited to very few variables)
- Windows specific benefit: The starting process can be `erl.exe` directly instead of a batch script, allowing for better platform integration. E.g. right click pin the release process to the taskbar in a way it can be started again by windows os mechanics. (This is a non-problem on linux and macos platforms who allow bash script processes to be replaced by the beam process using `exec` - but this mechanic does fundamentally not exist on windows)

# Request for comments

- Any feedback on this approach, or alternatives? 
- I've added the new lines with tab indention, is tab or spaces the preferred way for new code?
- If valid so far, I would like to add some documentation for this feature as well with both linux and windows examples - where would be the right place / file for that?

Cheers!

### CODE REVIEW

**Comment by garazdawi** [comment]
My initial reaction is that this seems to try to solve a lot more than only the `BINDIR` problem. There is a lot of overlap with the functionality provided by `erl -args_file`, except that it is implicit and allows for environment variable expansion.

So I think we should focus this PR on solving one problem, instead of many. Is the goal to unify BINDIR resolution? or is it to provide environment variable expansion to user provided arguments?

**Comment by dominicletz** [comment]
Good point @garazdawi,

to unravel a bit - the motivation / goal to create this PR was to enable Windows releases that after being started can be pinned to the Windows taskbar. With a default Erlang release this is currently not possible. The process of pinning a running process to the taskbar on Windows will always reference the running .exe file not considering any scripts or batch files that were used to launch the .exe file. As a result release critical parameters such as `-boot` and environment variables such as `BINDIR` are missing and not the release is starting up, but a pure Erlang shell. 

Initially I've tried to use the existing .ini file to solve this but had to realize that it is not capable enough. Also disliked the fact that it would then be a Windows specific solution. Instead the existing `initial_argv_massage` function inspired me to apply this approach.

I'm attaching a screen recording of showing the "problem" on windows with a release based on the default empty app from `rebar3 new release` && `rebar3 release`

output

This is a problem when creating applications using Erlang and wanting them to behave "natively".

Cheers!

**Comment by dominicletz** [comment]
I've been curious to check "what have others been doing to solve this?" myself and tried with Wings3d which is the other erlang windows app that I'm aware of. And the answer seems to be it just isn't solved by anyone. Here is a recording with wings3d

output2

That said I'm happy to reduce scope of this PR if there is a more minimal version solving the pin-to-taskbar problem.

**Comment by garazdawi** [comment]
Without incorporating all of the functionality of the relx batch script inside erl.exe, I'm unsure what we can do? Is it somehow possible to manipulate Windows into thinking that the batch script is the main GUI app?

**Comment by garazdawi** [comment]
I think that we should focus on trying to solve the pinning problem, not create a new way to configure Erlang systems. So to that end I need to know a bit more about how pinning works on Windows. You wouldn't happen to know if there is any documentation around this that I can read?

I assume that it can only be done with applications running a GUI (console or Window)?

When you pin, does the pinning also include any arguments used to start the running program? what about environment variables?

**Comment by dominicletz** [comment]
I couldn't find anything specific to the taskbar as documentation. But it's being mentioned a bit here:

https://learn.microsoft.com/en-us/windows/win32/shell/appids?redirectedfrom=MSDN

Referenced from here on java programs having the same issue: https://stackoverflow.com/questions/1834599/pinning-a-java-application-to-the-windows-7-taskbar

My reading from the Microsoft article is that while the default pinning does not preserve arguments nor environment variables it seems to be possible to create a .lnk file that points to the .exe including arguments. Then pinning might work:

> However, if the process was launched through a shortcut that contains launch arguments (usually the target content to host as the "application"), the system can determine identity and the application can be pinned and relaunched.

It's not very specific on whether just the link can be pinned or the running program, but I can give this a spin and report my findings.

**Comment by dominicletz** [comment]
Thought this would be easier, haven't found a way yet to modify the "Property Table" of a windows shortcut so to be able to set the `AppUserModelID` - Will have to spend more time later on digging into this.

**Comment by garazdawi** [comment]
I'm closing this PR for now. If you get any new ideas on how to make this work we can re-open this or talk elsewhere.

**Pull request closed without merging**
