### PR TITLE
Accept 'ECPrivateKey' as a ssl key option

### PR DESCRIPTION
**Pull request by mururu**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
This is obviously a bug fix. For quicker inclusion it would be great if you could add a test case too, otherwise we will when it gets prioritized.

**Comment by essen** [comment]
What kind of test do you expect and where should it be put? Perhaps there's a similar one somewhere?

**Comment by IngelaAndin** [comment]
There needs to be a test that uses the option to specify a 'ECPrivateKey' and gets a sucessfull connection.

**Comment by mururu** [comment]
Sorry, I found your reply now. I will add a  test this evening.



—
Mailbox から送信

**Comment by IngelaAndin** [comment]
How is it going with the test case?

**Comment by mururu** [comment]
Sorry for the late reply. I have pushed the test case. But I could not find a best place where it should exist. Please tell me if there is a better place.

**Comment by IngelaAndin** [comment]
Well I think this place is good enough for now anyway. There is a der_input case in the ssl_basic_SUITE  that is actually not a good enough test as it does not test all types of keys as DER. Also ECC was added in a later stage then this test was written. At some point we may need to review the test structure of ssl as it is growing all the time, but that is another problem.

**Comment by mururu** [comment]
It is good new. I have supposed something like that. Thanks!

**Comment by OTP-Maintainer** [comment]
Fetching pull requests from github failed:

    Host key verification failed.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.



----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Merged to maint for 18.1

**Comment by mururu** [comment]
Thank you!

**Pull request closed without merging**
