### PR TITLE
[nif] Add support for UTF-8 in atom and string NIF functions.

### PR DESCRIPTION
**Pull request by potatosalad**
This PR adds support for UTF-8 atoms and strings in `erl_nif.h`.

This implements the remaining UTF-8 support missing from the original #2502.

## Summary of Changes

* A new enum value `ERL_NIF_UTF8` for `ErlNifCharEncoding`.
* The following functions have been added to `erl_nif.h`:
    * Adds `enif_get_string_length`
    * Adds `enif_make_new_atom`
    * Adds `enif_make_new_atom_len`
* The following functions have been modified in `erl_nif.h` to support both LATIN1 and UTF-8 encoding:
    * Changes `enif_get_atom`
    * Changes `enif_get_atom_length`
    * Changes `enif_get_string`
    * Changes `enif_get_string_length`
    * Changes `enif_make_existing_atom`
    * Changes `enif_make_existing_atom_len`
    * Changes `enif_make_string`
    * Changes `enif_make_string_len`
* The function `erts_unicode_list_to_buf` in `global.h` has been modified to support a `capacity` parameter as described below.
* Tests for all of the above have been added to `nif_SUITE.erl` and `nif_SUITE.c`.
* Documentation for all of the above has been updated.

The function signature of `erts_unicode_list_to_buf` has been changed from:

```c
int erts_unicode_list_to_buf(Eterm list, byte *buf, Sint len, Sint* written);
```

To the following, which adds a new `Sint capacity` parameter:

```c
int erts_unicode_list_to_buf(Eterm list, byte *buf, Sint capacity, Sint len, Sint* written);
```

`Sint capacity` is used to distinguish between the actual `byte *buf` capacity and the number of UTF-8 characters `Sint len`.

## Test Plan

```bash
make emulator_test ARGS="-suite nif_SUITE -case get_atom"
make emulator_test ARGS="-suite nif_SUITE -case get_atom_length"
make emulator_test ARGS="-suite nif_SUITE -case get_string"
make emulator_test ARGS="-suite nif_SUITE -case get_string_length"
make emulator_test ARGS="-suite nif_SUITE -case make_existing_atoms"
make emulator_test ARGS="-suite nif_SUITE -case make_new_atoms"
```

### CODE REVIEW

**Review by sverker — COMMENTED** [review]
@potatosalad Thanks you for a high quality PR.

I only had some minor comments about the documentation.

But I found preexisting bugs in `erts_unicode_list_to_buf`[`_len`] when passed negative code points. I will push tests and fixes.

**Comment by sverker** [comment]
I did a separate PR #6471 for the negative code points bug. Keeping the fix here for now also and clean it up later.

**Comment by potatosalad** [comment]
@sverker Awesome, thank you for the review!  I will get the fixes you mentioned to the docs, etc integrated later today.

**Comment by sverker** [comment]
I just changed my mind and reverted my negative-code-point stuff, to avoid merge conflict with #6471 in our testing.

**Comment by sverker** [comment]
> @sverker Awesome, thank you for the review! I will get the fixes you mentioned to the docs, etc integrated later today.

Good! I prefer if you do fixes as new commits and don't force push. I can clean it up before merge when we both are happy.

**Comment by sverker** [comment]
I pushed some more commits.
- Refactored the test code (pass enum integers instead of atoms `latin1` and `utf8`) 
- Fixed a bug where `enif_make_new_atom` truncated long utf8 strings
- Some more documentation changes

**Comment by potatosalad** [comment]
@sverker Anything else you'd like me to do on this PR?  Would you like me to fix the conflict in `utils.c`?

**Comment by sverker** [comment]
@potatosalad  It's ok, I can squash all my commits and rebase on master to solve the conflict.

**Comment by sverker** [comment]
Squashed and rebased. Waiting for API approval from technical board before merge.

**Comment by sverker** [comment]
Approved and merged to master.
@potatosalad Thanks for contribution and collaboration.

**Pull request merged**
