### PR TITLE
INCOMPATIBLE? sys:log of gen_* in terminate report

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
This PR begs for community feedback since it modifies (ancient and undocumented | incorrectly documented | incorrectly implemented) code in `sys`.

The purpose is to be able to set `sys:log(Server, {true,N})` and if the Server terminates get the last N system events in the terminate report.

To accomplish this I have changed the return value from `sys:log(Server, get)` to something like it was documented to return, changed(improved) and augmented the documented `sys:system_event()` type, unified the system event values generated by gen_*, and poked around.

I have also added the possibility to `gen_statem` to generate custom system debug events, for fun, and because it seems like a useful feature to be able to notify important happenings in the sys:log that the behaviour engine can not know about.  Is this a good feature, and does it look right(tm)?

So, does this break your code; please let me know so!

Otherwise this is intended for OTP-22.0 since it may break application's code that has gone beyond what is documented...

### CODE REVIEW

**Comment by ferd** [comment]
I think I disagree with the ability to create custom log events in gen_statem:

First of all, I keep opposing stuffing more stuff into the already complex API of gen_statem, but that in itself isn't a strong argument :)

When I use the `sys` module, I expect to use the OTP toolchain to access information a layer _below_ what the application and custom code of a user is doing. I'm using it to debug or observe potential stuff going on in the application itself. The debug messages that belong at the application layer are already supposed to be handled by logging, which already cares for the `{Format, Term}` exact support for debugging.

I'm not too sure what the rationale should be when taking app-level concerns and putting them into framework-level debugging facilities. It has been added "for fun", but I'm a bit concerned that this is not sufficient :)

In any case it should be a feature that is easy to ignore, unless it ends up in `install` debug calls as well?

---- 

That being said, should I expect the format of events sent to functions handled by `sys:install/2-3` to also change? Are they being unified with these or with what `sys:trace/2-3` should display? I feel like uniformity would be very useful there.

While playing with the types, I think I recall noticing at some point that `gen_server:start_link` functions document `{debug, [{install, ...}]}` in their types (they refer to what the `sys` module provides), but `install` is flat out disregarded there.

**Comment by jlouis** [comment]
My initial hunch would be there are rather few users of that API for production uses.

In the Go world, they have tools to read every source file on the planet and then scan for occurrence of a given construct[0]. I know @essen did something similar for his Cowboy project and erlang.mk, but I don't remember the details.

[0] All import statements in Go are self-referential, so you can follow public imports around.

**Comment by essen** [comment]
What Erlang.mk does is just download and build all projects in its package index. Takes a couple hours for around 500 projects. https://github.com/ninenines/erlang.mk/blob/master/test/Makefile#L137

A download + build|parse|inspect loop is not terribly hard to script.

**Comment by RaimoNiskanen** [comment]
@ferd: You are right, not extending `gen_statem` is in this particular case a weak argument...  The funny thing is that is is only possible to implement in `gen_statem` thanks to the return tuple actions list. :-)

Other than that, good point. Is it a good idea to allow the application to insert information the layer below?
The general idea (not only "fun") is that since a state machine's "job" is often the side effects, and that only the application knows e.g if it bangs something to another process, commits a data base record or whatnot, and that these important events could be handy to have in the System Event log.

But as you say we have `logger` for that.
I think you are right.  Application debug logging is a bad idea.

And yes, these refurbished System Events will be visible for `sys:dbg_fun()`s, which is maybe the greatest incompatibility, and also _not_ since a `sys:system_event()` has got a `term()` fallback at the end (cowardly).  This opens for any custom event and the `{debug,...}` event would also fit in here.

Any custom server using `proc_lib` and `sys` could produce any term System Events.  Annoying, at the least.

I have tried to draw a line and unify them to what content should be part of the event and what is passed on the side to the `sys:format_fun()`. These events are the same for all `sys` features.

All `gen_*` passes the start option `{debug,Opts}` as `sys:debug_options(Opts)`.  Their declared types for the start functions may be incomplete...

**Comment by RaimoNiskanen** [comment]
I have removed the `gen_statem` action `{debug,...}`.

**Comment by ferd** [comment]
I'm good with the changes now. I think that normalizing and reupdating these events will be a good cleanup since I (like @jlouis ) don't believe too many people have built literal tooling on these.

I think we might have one or two tests that use the `install` function to expose state transitions that will start failing, but this should be an easy fix.

**Pull request merged**
