### PR TITLE
Union, intersection and subtraction of character classes

### PR DESCRIPTION
**Pull request by rustkas**
Character classes have ability to use union, intersection and subtraction.

This functionality expands the possibilities for describing the required data.

### CODE REVIEW

**Comment by rickard-green** [comment]
Sorry I don't get your examples to work. Equally important I cannot find any PCRE documentation indicating that union, intersection and subtraction are supported. If we are to document an `re` feature, it needs to be supported and documented in PCRE.

**Comment by rustkas** [comment]
@rickard-green you're right. All the same it is. I think we need to contact the developers of the PCRE documentation to make the appropriate adjustments (so that they check the operation of this functionality in the PCRE library).  I can do it (I will send messages to @pelegri, @seanpaultaylor (They are contributors to the project [PCRE](https://github.com/blackberry/PCRE) ) and ask for help. If you know who to contact for help in this matter, please let me know. 

I will write on my own behalf and I will inform you of the results of our negotiations. Therefore, I ask you not to rush to conclusions and do not take any decisions yet.

I am researching how regular expressions work in Erlang (researching this issue). I use experience in other programming languages, research published books about Regular Expressions and examples given by their authors. I also studied the documentation for the program [RegexBuddy](https://www.regexbuddy.com/manual.html).

I share the intermediate results of my research on the [forum pages](https://forum.devtalk.com/t/using-regular-expressions-in-erlang/).

Here are my finished works:

   1.  [Introducing Regular Expressions in Erlang](https://github.com/rustkas/Introducing-Regular-Expressions-by-Erlang)
   2. [Regular Expressions in 10 minutes in Erlang](https://github.com/rustkas/Regular-Expressions-in-10-minutes-in-Erlang)
   3. [RegexBuddy Regular Expression Tutorial](https://github.com/rustkas/RegexBuddy-Regular-Expression-Tutorial)

And these are still unfinished projects:

   - [Regular Expression Pocket Reference](https://github.com/rustkas/Regular-Expression-Pocket-Reference)
   - [Regular Expressions Cookbook](https://github.com/rustkas/Regular-Expressions-Cookbook)


Examples of the discussed functionality (union, intersection and subtraction in character classes) can be found in my works. Code examples are [here](https://github.com/rustkas/Regular-Expressions-Cookbook/blob/main/code/ch02/basic/lib/recipe_03/src/recipe_03.erl). Positive results were obtained in an experimental study - I checked what worked and what did not.

**Comment by rickard-green** [comment]
Ok! We have not had any contact with PCRE maintainers (that I know of), so we do not know any specific people to contact. Note that the `re` module is implemented using PCRE (not the new PCRE2).

**Comment by rustkas** [comment]
I far as I know [PCRE2](https://www.pcre.org/current/doc/html/pcre2.html#SEC4) library package written by Philip Hazel, and copyright by the University of Cambridge, England. 

I wrote him an e-mail with a request to help clarify this issue, as well as to supplement the documentation of the PCRE2 library. 

I will report on the results of the discussion on this issue.

**Comment by KennethL** [comment]
If we in OTP should change from the old PCRE. It is not for sure we will
choose PCRE2, it could just as well be some other regexp library, for
example re2.
We have not investigated at all if and when we have reason to change and to
what, but it is worth pointing out that PCRE2 is not the only choice in
that case.

/Kenneth

**Comment by rustkas** [comment]
@KennethL, we don't need to change anything. I discovered this by researching books on regular expressions and checking what works in Erlang and how. The described functionality exists and works. 
 
I discovered  that like Microsoft Dot Net and Java standard library, the re module provides the ability to use union, intersection and subtraction of character classes.

**Comment by rustkas** [comment]
I received a response from [Philip Hazel](http://quercite.dx.am/) (He is PCRE2 developer) to my request to PCRE2 documentations improvement.

### A main part of my letter text:

> 
> Dear Sir!
>  
> Please, tell me who you can improving the PCRE library documentation. Experimentally, I have discovered undocumented features and would like them to be documented, as this information indirectly affects other projects as well.
>  
> What I found and what I would like to add:
> 
> Character classes have ability to use union, intersection and subtraction.
> 
> The union of the character class allows to match a character from one of the specified ranges i.e. the expression [a-f[A-F[0-9]]] matches a single character which is either a small alphabet set (a-f), a big alphabet set (A-F) or a digit (0-9).
> 
> An intersection relation between ranges is defined using &&. The syntax for it is [class&&[intersect]]. You can use the full character class syntax within the intersected character classes. The expression [\\w&&[a-fA-F0-9\\s]] matches a single character.
> 
> Character class subtraction makes it easy to match a character that is in a certain list, but not in another list. E.g. [a-z-[aeiou]] matches an English consonant. It is particularly handy when working with Unicode properties. E.g. [\p{Thai}-[\P{N}]] matches any Thai numbers.

## [Philip Hazel's](http://quercite.dx.am/) response:

> 
> Hello,
> 
> I am afraid you are mistaken. PCRE does not support set operations on character classes. I know that Perl has introduced features like this with patterns such as    /(?[ \p{Thai} & \p{Digit} ])/    but these features have not (yet) been implemented in PCRE.   I am surprised you found anything that worked. A pattern such as  [a-z-[aeiou]]    will match any letter, a hyphen, an opening square bracket, followed by a closing square bracket. This is an example from pcre2test:
> 
> $ pcre2test /source/pcre2/zz
> PCRE2 version 10.37 2021-05-26
> /([a-z-[aeiou]])+/
> >a]b]-]c-d<
>  0: a]b]-]
>  1: -]
> 
> Notice that it matches the vowel "a".
> 
> Regards,
> Philip

I think that the features I found are just another distinctive features that has already been mentioned in the documentation for [re module](http://erlang.org/doc/man/re.html). I think that the developers of the [re module](http://erlang.org/doc/man/re.html) has surpassed the functionality of the library on the basis of which it was created. The features I have found do not have a negative impact, but only expand the capabilities that Erlang programmers have.

**Comment by rickard-green** [comment]
> I think that the features I found are just another distinctive features that has already been mentioned in the documentation for [re module](http://erlang.org/doc/man/re.html). I think that the developers of the [re module](http://erlang.org/doc/man/re.html) has surpassed the functionality of the library on the basis of which it was created. The features I have found do not have a negative impact, but only expand the capabilities that Erlang programmers have.

I'm not sure I understand what you mean here. I could not get your examples to work and Philip Hazel claim it is not implemented in PCRE.

**Comment by rustkas** [comment]
I am very sorry that you have decided so. 
I have provided working examples. I'm sorry you didn't notice them.
Code examples are [here](https://github.com/rustkas/Regular-Expressions-Cookbook/blob/main/code/ch02/basic/lib/recipe_03/src/recipe_03.erl).

**Comment by rustkas** [comment]
I meant that the module re already has unique options (which are not "support is not compatible with Perl"). If this is the case, then there may be other unique options - the ones that I discovered.

**Comment by rickard-green** [comment]
I tried all of your examples given in the documentation that you want to add except for the thai number one (since I don't know how to produce thai numbers). I expected them all to match the subject "b", but none of them do:
```
$ erl
Erlang/OTP 24 [erts-12.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Eshell V12.0.4  (abort with ^G)
1> re:run("b","[a-f[A-F[0-9]]]").
nomatch
2> re:run("b","[\\w&&[a-fA-F0-9\\s]]").
nomatch
3> re:run("b","[a-z-[aeiou]]").        
nomatch
```
Even if it would have worked, this is not nearly enough. We must know that it works as intended, and not just happens to work. Things that just happens to work might also just happen to stop working at any time. That is, these features would have had to be documented and supported by PCRE in order for us to document and support them. Besides that, Philip Hazel also clearly stated that this is not implemented nor supported by PCRE.

**Comment by rustkas** [comment]
@rickard-green you are right. Thanks a lot for your patience. I understood the essence of my delusion.

**Comment by rickard-green** [comment]
No problem!

**Pull request closed without merging**
