### PR TITLE
Snmp agent vacmViewTreeFamily with non 'null' mask bugfix

### PR DESCRIPTION
**Pull request by davidqo**
It fixes
http://erlang.org/pipermail/erlang-bugs/2015-April/004891.html
And includes
http://erlang.org/pipermail/erlang-patches/2015-April/004766.html

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Checkout the maintenance branch failed:

    erence.erl "/ldisk/jenkins/jobs/pullrequests/workspace/otp/release/tests/emulator_test"
    /usr/bin/install -c -m 644 bs_bincomp_no_opt_SUITE.erl bs_bit_binaries_no_opt_SUITE.erl bs_construct_no_opt_SUITE.erl bs_match_bin_no_opt_SUITE.erl bs_match_int_no_opt_SUITE.erl bs_match_tail_no_opt_SUITE.erl bs_match_misc_no_opt_SUITE.erl bs_utf_no_opt_SUITE.erl guard_no_opt_SUITE.erl map_no_opt_SUITE.erl "/ldisk/jenkins/jobs/pullrequests/workspace/otp/release/tests/emulator_test"
    /usr/bin/install -c -m 644 hibernate_native_SUITE.erl "/ldisk/jenkins/jobs/pullrequests/workspace/otp/release/tests/emulator_test"
    chmod -R u+w "/ldisk/jenkins/jobs/pullrequests/workspace/otp/release/tests/emulator_test"
    tar cf - *_SUITE_data | (cd "/ldisk/jenkins/jobs/pullrequests/workspace/otp/release/tests/emulator_test"; tar xf -)
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/erts/emulator/test'
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/erts/emulator/test'



----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
hmm ok.
Well, 'maint' has just moved from 17.5.6 -> 18.0 so it would be lovely if you could rebase.

And I will take a look at Mr Jenkins and the weird errors.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
Hi we a questions about the  snmpa_mib_data_tttn.erl change.

You say "This code always return false as OidSoFar is shorter than MibView"

The intent of the code is that if   OidSoFar is a prefix of MibView it should 
be accepted. I have not dug deep into this myself, but our snmp expert says it should be so.

Could you turn on the verbosity of the agent (using the snmp API) setting it to trace and run your example that fails and send us the output ? 

Also there seems to be an error in the documentation saying that the first element in vacmViewTreeFamily  is  ViewIndex (integer()) but it should be  ViewName (string()) according to the standard.

**Comment by IngelaAndin** [comment]
Ping

**Comment by IngelaAndin** [comment]
Ping!  We will cherry-pick all fixes but  lib/snmp/src/agent/snmpa_mib_data_tttn.erl  and include them. If you want the last fix we need some more input see earlier comment.

**Comment by IngelaAndin** [comment]
I have merged the cherry-picked branch. If you can can motivate the not included changes you are welcome to open a new PR.

**Pull request closed without merging**
