### PR TITLE
Add option to bypass SSL PEM cache

### PR DESCRIPTION
**Pull request by ferd**
The current SSL implementation has a PEM cache running through the ssl
manager process, whose primary role is caching CA chains from files on
disk. This is intended as a way to save on disk operation when the
requested certificates are often the same, and those cache values are
both time-bound and reference-counted. The code path also includes
caching the Erlang-formatted certificate as decoded by the public_key
application

The same code path is used for DER-encoded certificates, which are
passed in memory and do not require file access. These certificates are
cached, but not reference-counted and also not shared across
connections.

For heavy usage of DER-encoded certificates, the PEM cache becomes a
central bottleneck for a server, forcing the decoding of every one of
them individually through a single critical process. It is also not
clear if the cache remains useful for disk certificates in all cases.

This commit adds a configuration variable for the ssl application
(`bypass_pem_cache = true | false`) which allows to open files and decode
certificates in the calling connection process rather than the manager.
When this action takes place, the operations to cache and return data
are replaced to strictly return data.

To provide a transparent behaviour, the `CacheDbRef` used to keep track
of the certificates in the cache is replaced by the certificates itself,
and all further lookup functions or folds can be done locally.

This has proven under benchmark to more than triple the performance of
the SSL application under load (once the session cache had also been
disabled) in a full stack system of ours.

----

Do note that I have run the SSL app's tests and they mostly passed successfully
both with and without the option being set.
Exceptions include the current tests dealing with cache clearing counts, since
these cannot apply without change, and one with CRLs in the noncached version
that I'm still chasing after as I'm not quite sure how they're related, but they
apparently are.

I have however not taken the time to write new tests since I'm not quite sure
what form the OTP team wants them to take -- specifically, re-running the
suite a second time to validate all possible paths for CA cert resolution with
a single configuration switch enabled sounds like trouble, but that's what I
have done here on a solo run.

Not sure what form the OTP team would like for long term tests here.

I am also currently working on a minimal benchmark run to show the benefits
of this approach. I'm trying to see how the suites run for that one as I've
seen they are skipped by default.

### CODE REVIEW

**Comment by ferd** [comment]
I've just added a commit to fix CRL issuer checks when bypassing certs. The 3 tests I've seen that failed with the cache dir hash still do so when in cache-bypass mode, but from what I could dig into, the test sets up multiple connections and appears to rely on the fact that the client and server both share the same cache (given they're on the same host) and the CertsDB cache scan does not care for initial Refs and therefore is free to look at issuers from the entire cache of all sessions. 

If my understanding is correct, it feels like the same test would fail the client and server (or various sessions) were to be moved on disjoint nodes and by removing cache, this just gets a simpler similar case. I don't think this one could be fixed easily.

**Comment by ferd** [comment]
Hi, so I just got a standalone benchmark script going -- I didn't get it going within the ssl_bench_SUITE (I saw that it at least did not negatively impact anything there, whether from PEM or files), but I'm willing to move this kind of work in there. I wanted to first show preliminary work and discuss it in here.

So I've got a script at https://gist.githubusercontent.com/ferd/f8525a4b95c2905f7ccfd6912d12c967/raw/182e9cd6b2d2bb2b53abfa90d8ea2de5dc8574f2/ssl_cache_bench.erl  -- it simulates batches of acceptors and clients doing N requests each, with a few milliseconds spent simulating work.

The server uses a self-signed cert at `./cert.pem` and `./key.pem` (loaded in memory as DER files first), whereas the client uses an inline DER bundle of CA certs taken from the `certifi` library (it represents a standard set of root certs for general compatibility). All traffic is done locally, within one node, which may or may not increase the pressure on the cache table.

Here's the results in running it with various parameters:

- 50 acceptors / 50 clients / 50 reqs each / 10ms sleep before responding
 - cache bypass false: 23314ms
 - cache bypass true: 20292ms

- 100/100/50/10
 - bypass false: 53788ms
 - bypass true: 32444ms

- 150/150/50/10
 - bypass false: 88279ms
 - bypass true: 67054ms

- 150/150/50/5
 - bypass false: 89518ms
 - bypass true:  66704ms

- 150/150/50/0
 - bypass false: 82687ms
 - bypass true:  65546ms

Additional nodes at looking at `htop` while running the benchmark on a 4-core linux VPS:
- bypass false tends to peg 1 core at 100% at regular intervals while the rest falls to 0%. For us this was equivalent to latency spikes and availability losses.
- bypass true tends to always do work on at least 3 cores, although 1 is higher, closer to or at 100%. For us this meant the node remained healthy with predictable performance by comparison.

As an explanation, what we've realized after looking at our own private benchmarks more is that what seems to happen for performance degradation in there is that over time, the PEM cache table seems to grow to a size at which the scanning operations in the ETS cache done from within the ssl_manager take enough time to lock it up on a core, and create a large backlog of pending requests in its mailbox.

As the mailbox grows in size, the table operations take longer and longer and the table bloats in size. What we notice then is that the entire node locks up and freezes for multiple seconds while the cache gets cleared or reduced in size enough to free itself up, or, in our cases, to enter a death spiral where everything SSL related becomes unresponsive as long as load from outside the node keeps increasing.

I don't know how we'd want to include this inside the regular test suite, on top of adding the current regular tests in there.

**Comment by IngelaAndin** [comment]
Interesting observation on the CRL tests. I will look into it. We have had some false negative test due to test environment problems, that I feel we have started to get a grip on, but it might be so that there are some missed real test case problems.   We will try to find time to review this PR more in detail hopefully next week, things are starting to get back to normal after summer vacations.

**Comment by ferd** [comment]
I'm adding another post there because I've got some news from the front, posted with permission from my employer.

We deployed a few canary servers using this patched version of the library and the numbers are extremely encouraging.

For the sake of completeness, here's some context:

- The servers are AWS c3.4xlarge instaces (16 cores, 30GB Ram)
- They run routing software doing SNI termination on-instance and returning simple 'hello world' over HTTP
- SNI termination in this case is done with Let's Encrypt DER certificates with their respective CA Chain
- The clients contacting the node that figures are reported for are written in Ruby and use Curl to do their work, but otherwise we have browsers and clients of all kind
- The servers are running a regular production load and these ruby clients are themselves canaries to evaluate the QoS over time. They open connections, make a request then close the connection, so the values reported include the handshake every time
- There is a background of SSL work being done by numerous server requests being handled, and a few client requests on the server itself contacting other APIs. The load is very asymmetric towards serving traffic
- All traffic terminated over SNI is done with DER certs, none of them contain file certificates.
- The network traffic, request count, and packet counts remained similar before and after the deploy
- The results were calibrated against bias introduced in a restart by comparing them with another node (on the old version of the library) that has been restarted at the same time
- Cache has been disabled for sessions in all cases, and the cache implementation we substituted stores nothing at all to avoid work done that way.

We've deployed this version and got the following results:


Reduction of the median, average, perc95 and perc99 times by roughly 4x to 5x on busy servers, 2x on less busy ones. Actual figures point of a reduction from 100ms..120ms in roundtrip time down to 20ms..25ms for SNI requests served on average.



Reduction in GC load is fairly large, going from ~3,000,000 GCs a minute down to ~2,500,000 per minute. The reclaimed words are impacted more significantly: from around 7G words reclaimed down to 4G words reclaimed per minute. Not sure what they are, but the big variable that changed is the `ssl_manager` process not opening files on its own anymore, and instead letting idividual processes handle things and shed the memory when they're done executing*

Other figures:
- ~3-5% reduction in CPU load on a busy node, close to 30% reduction on one of the least active nodes when we tested. Most of
 that appears to be work done regarding garbage collection, interrupts, and scheduling
- the 'runtime' stats have decreased from 430,000 to 365,000 per minute
- run queues remained similar on larger nodes, but went flat rapidly on less busy nodes

But for us, the 4-5x reduction in the overall roundtrip time for handshakes due to this patch makes this entirely worthwhile.

\* I don't know if that will lead to more memory fragmentation over time.

**Comment by IngelaAndin** [comment]
I remember at the time we had a discussion that the PEM-cache should be done by a separate process and not by the manager, that manages session ids which is an unavoidable bottleneck that we want to minimise, alas this step was never implemented. Also in the case of the input being DER I think the code should skip the PEM cache,  however the the intention was that we should only need to decode the cert once.  The lookup of operations should already by local as it is a public ets-table that can be read by the connection processes.  So it seems that the handling of ets-entries in the manager becomes an unacceptable bottleneck.

Our view at the moment is that this PR can be part of the solution, and maybe also used as a workaround until the PEM-cache can be improved. We will start by testing it in our nightly builds.

On the test front we are thinking to add a group pem_cache to
ssl_bench_SUITE which will only be run on our benchmark-computers

Something like:
all() -> [{group, setup}, {group, payload}, {group, pem_cache}].

groups() ->
    [{setup, [{repeat, 3}], [setup_sequential, setup_concurrent]},
     {payload, [{repeat, 3}], [payload_simple]},
     {pem_cache, [{repeat, 3}], [use_pem_cache, bypass_pem_cache]},
    ].

use_pem_cache() ->
 {ok, Result} = bypass(false),
  ct_event:notify(#event{name = benchmark_data,
			   data=[{value, Result},
				 {suite, "ssl"}, {name, "Use PEM cache"}]}).

bypass_pem_cache() ->
 {ok, Result} = bypass(true),
  ct_event:notify(#event{name = benchmark_data,
			   data=[{value, Result},
				 {suite, "ssl"}, {name, "Bypass PEM cache"}]}).

Result should be an integer where bigger is better. You would need to add an init_per_testcase
that skips the test if for older versions of the ssl application.

Maybe there should be a a der_pem_cache and der_bypass_pem_cache so that we could add
file_pem_cache and file_bypass_pem_cache later?!

**Comment by ferd** [comment]
Hi,

I've added the benchmark for the PEM cache bypass. They're not as demonstrative of gains as other benchmark runs I've shown here (nor our production graphs), but that ought to be decent enough?

>  The lookup of operations should already by local as it is a public ets-table that can be read by the connection processes. So it seems that the handling of ets-entries in the manager becomes an unacceptable bottleneck.

One of the costly operations, I believe, is the decoding of a cert to the Erlang format, done within the `ssl_pkix_db` functions, which takes place within the SSL manager. This tends to let the table grow bigger and the cache clean flush operations paralyze the table for even longer. We've in fact discovered the issue by how much time was spent in `select` operations.

> Maybe there should be a a der_pem_cache and der_bypass_pem_cache so that we could add
file_pem_cache and file_bypass_pem_cache later?!

Possibly. Doing so would prevent us from reusing most of the testing infrastructure (which mostly uses file-based certs) rather than DER certificates, but may not be that difficult to implement otherwise.

**Comment by IngelaAndin** [comment]
I have put it into our nightly builds.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by IngelaAndin** [comment]
I have made an issue to improve the PEM cache and merged my branch featuring this PR and with a small edition to skip bench-marks tests in the ordinary test run. Also added some documention. Usually you would get to write the doc, but I wanted it to make 19.1.

**Comment by edmorley** [comment]
Thank you for the interesting write-up on the [Heroku blog](https://engineering.heroku.com/blogs/2016-12-22-how-we-sped-up-sni-tls-handshakes-by-5x/).

For anyone curious to see the commits as manually merged, they are https://github.com/erlang/otp/commit/59ec0761d69608a6d4be2db1967e71efdb9f535d, https://github.com/erlang/otp/commit/911ab85688b21832c13d686d44c6b9064e9604a5 and https://github.com/erlang/otp/commit/dba6a3165e4cc8c2555c161510fd4caa82a1a96a - and the release notes are [here](http://erlang.org/doc/apps/ssl/notes.html#id57332).

> I have made an issue to improve the PEM cache

I couldn't find this issue on https://bugs.erlang.org/ -- I presume it's on your internal tracker instead?

**Pull request closed without merging**
