### PR TITLE
asn1: Fix feature interaction with +undec_rest and +asn1config

### PR DESCRIPTION
**Pull request by vances**
Compiling an ASN.1 specification Module using the `+undec_rest` option causes the result of `Module:decode/2` to be `{ok, Value, Rest}`, however when combined with `+asn1config` option to create exclusive decode functions those are not effected by the `+undec_rest` option.

This commit fixes this so exclusive decode functions return the expected result when the `+undec_rest` option is provided.

### CODE REVIEW

**Comment by bjorng** [comment]
Thanks for the pull request.

Could you write a test case to ensure that it works and keeps working?

**Comment by vances** [comment]
Added test case `exclusive_decode_rest` which mirrors our use case by concatenating two binary CDRs, created with the existing `SwCDR` ASN.1 module, running exclusive decode and checking that `Rest` is the second CDR.

**Comment by bjorng** [comment]
Thanks! Added to our daily builds.

**Review by vkatsuba — APPROVED** [review]

**Comment by bjorng** [comment]
Thanks for your pull request.

**Pull request merged**
