### PR TITLE
Rand plugin for cached strong crypto bytes

### PR DESCRIPTION
**Pull request by RaimoNiskanen**
This pull request adds functions `rand_seed_alg(Alg)` and `rand_seed_alg_s(Alg)` to the `crypto` module.

The new functions take an algorithm name where the name `crypto` names the previously existing algorithm implemented in `rand_seed()` and `rand_seed_s()`, and the new algorithm name `crypto_cache` implements an algorithm that fetches bytes from the same source as `strong_rand_bytes(N)` but caches them for speed and returns a random 56 bit (also for speed) word at the time.

This algorithm gives a decent speed for generating cryptographically secure random numbers.  The test case `rand_SUITE:measure/1` indicates (amortized) only about 60% to 100% slower than the default PRNG in the `rand` module, while the previous `crypto` algorithm (in `rand_seed()`) is about 4 to 15 _times_ slower than the default PRNG.

### CODE REVIEW

**Comment by okeuday** [comment]
@RaimoNiskanen It is best if the `crypto_cache` algorithm allowed specifying the size of the cache in bytes because different use-cases may benefit from more memory consumption.  Not sure if there is a way to specify the rand configuration in app env settings, though that would be beneficial to ensure a single setting is used by default.

**Comment by RaimoNiskanen** [comment]
@okeuday It would be nice to avoid a knob that is not necessary.  I did not see significantly better speed from larger cache, and thought this cache size was small enough for almost every application.

But give me a convincing counter example then I am all for a knob!

**Comment by okeuday** [comment]
@RaimoNiskanen The size of the cache is a reflection of the speed of the openssl/libressl library, the hardware, and ERTS, though these are a moving target.  The other problem is the request rate is very important and you may not have been testing with a high request rate, or you may have been limiting from testing a high request rate because of your environment (openssl/libressl library and hardware).  In the future, ideally ERTS will become faster with things with JIT which will also impact the buffer size necessary.  So, it should be impossible for you to select the proper cache size that all people will need in the future.

**Comment by RaimoNiskanen** [comment]
@okeuday True, but that knob will be no problem to add later on.  Either as an application crypto environment variable, or as an argument `{crypto_cache,CacheSize}` to `crypto:rand_seed_alg/1` and `crypto:rand_seed_alg_s/1`.

If anyone can show a machine today on which the cache size 16*56 bytes is not sensible, then we should add the knob today.

**Comment by okeuday** [comment]
@RaimoNiskanen You may consider the latency in your testing to be acceptable, while others do not, and are able to achieve lower latency with more memory on faster hardware.  This is my perspective for making sure this functionality is as widely applicable as possible, but I do have my own code (https://github.com/okeuday/quickrand/blob/master/src/quickrand_cache.erl) to help me avoid this implementation being a bottleneck, because the size there is configurable.

Your testing was likely on a slower machine with a specific request rate.  Other faster machines are capable of higher request rates.  It would be better to add a configurable size now, rather than tolerate complaints for a year or more, waiting for an Erlang release to get it fixed.

**Comment by RaimoNiskanen** [comment]
@okeuday I have added the knob.

**Comment by okeuday** [comment]
@RaimoNiskanen This is good and will avoid the cache size being a bottleneck anywhere.  Thanks!

**Pull request merged**
