### PR TITLE
stdlib: Fix proc_lib:stop when exit reason is expected reason

### PR DESCRIPTION
**Pull request by garazdawi**
When working with peer in #8537 I got a lot of errors where gen_server:stop would crash with reason `normal` as the peer process terminated with that reason just as gen_server:stop was called. I'm opening this PR to start a discussion to see if we want to make it so that if a process exits with the expected reason, though not was a result of the stop call, we should still consider it a successful shutdown?

### CODE REVIEW

**Comment by IngelaAndin** [comment]
I think it sounds reasonable, as the processes are parallel things that may stop execution by themselves or be shutdown by an other process and of course this can happen in the same time and there can be a race which one happens first, but they both end up with the wanted end result.  I think it sound strange that we get a crash because something terminated normally!

**Comment by max-au** [comment]
Makes sense to me too (although changes existing behaviour). 
If behaviour change isn't desirable, there could be a way to fix it specifically for `peer`.

**Comment by IngelaAndin** [comment]
I think it comes down to if we consider the current behaviour to be a bug or not. If it is a bug I think it is ok to change it, we never promised to be bug-compatible.

**Comment by essen** [comment]
This has bit me before so I 100% support the change. It's hard to imagine that this change will result in incompatibilities but I'm sure someone somewhere expects a `normal` crash.

**Comment by garazdawi** [comment]
I'll merge it into 28 and mark it as a potential incompatability. I too have a hard time seeing someone relying on this.

**Review by IngelaAndin — APPROVED** [review]

**Pull request merged**
