### PR TITLE
reltool: Add option for selective beam stripping

### PR DESCRIPTION
**Pull request by attah**
The debug_info option can now take a list of chunk ids to keep.
Chunk ids are as per beam_lib:chunkid().

For example, {debug_info, ["Attr"]} will keep only the attributes
in the beam files and strip the rest.

---
Why?
We have some code that introspects itself for some declarative use-cases (mainly "wild" attributes), and recently we started needing to be able to deliver stripped binaries.

### CODE REVIEW

**Comment by attah** [comment]
Hmm... neither exporting the type in beam_lib, nor adding it to DIA_PLT_APPS in reltool Makefile fixes the dialyzer warning.
(Unknown types: beam_lib:chunkid/0 (reltool.hrl:31:45))
BTW, since it is a type in a public API, shouldn't it have been exported already?
Or should i just put in a local type which also resolves to nonepty_string() and only refer to it in text?

**Comment by garazdawi** [comment]
> exporting the type in beam_lib

Are you sure this did not work? I tried it locally and it worked for me.

> BTW, since it is a type in a public API, shouldn't it have been exported already?

Not all documented types are public. Some are just in the docs for documentation purposes.

**Comment by attah** [comment]
Thanks for looking into it. I must have done something wrong (rebuild those two apps and run-dialyzer). I read you as the Makefile change not being needed, so i omitted that.

**Comment by tsloughter** [comment]
Note also that `Attr` needs to remain for the release to work with `release_handler`. In relx the default for stripping a release is now to keep the attributes: https://github.com/erlware/relx/pull/906

**Comment by garazdawi** [comment]
Thanks!

**Pull request merged**
