### PR TITLE
erts: Remove old unused functions

### PR DESCRIPTION
**Pull request by garazdawi**
The functions have been found using: https://github.com/caolanm/callcatcher

### CODE REVIEW

**Comment by sverker** [comment]
`erts_gc_after_bif_call` is called by `erts/emulator/hipe/hipe_*_glue.S`

**Comment by kostis** [comment]
I think that `grep` is a far superior tool than `callcatcher` ...

**Comment by garazdawi** [comment]
@sverker yes I noticed just as I pressed create pr, will fix.

**Comment by kostis** [comment]
I think it's very easy.  For each function you are about to remove (let's say `erts_gc_after_bif_call`) you issue a `grep` call first:
<pre>
~/HiPE/otp/erts$ grep -r "erts_gc_after_bif_call" .
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/smp/beam_emu.o matches
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/smp/erl_gc.o matches
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/smp/hipe_amd64_glue.o matches
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/plain/beam_emu.o matches
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/plain/erl_gc.o matches
Binary file ./emulator/obj/x86_64-unknown-linux-gnu/opt/plain/hipe_amd64_glue.o matches
./emulator/hipe/hipe_arm_glue.S:        bl      erts_gc_after_bif_call
./emulator/hipe/hipe_ppc_glue.S:        bl      CSYM(erts_gc_after_bif_call)
./emulator/hipe/hipe_x86_glue.S:        call    CSYM(erts_gc_after_bif_call)
./emulator/hipe/hipe_sparc_glue.S:      call    erts_gc_after_bif_call
./emulator/hipe/hipe_amd64_glue.S:      call    CSYM(erts_gc_after_bif_call)
./emulator/beam/erl_gc.h:Eterm erts_gc_after_bif_call_lhf(struct process* p, ErlHeapFragment *live_hf_end,
./emulator/beam/erl_gc.h:Eterm erts_gc_after_bif_call(struct process* p, Eterm result, Eterm* regs, Uint arity);
./emulator/beam/erl_gc.c:erts_gc_after_bif_call_lhf(Process* p, ErlHeapFragment *live_hf_end,
./emulator/beam/erl_gc.c:erts_gc_after_bif_call(Process* p, Eterm result, Eterm* regs, Uint arity)
./emulator/beam/erl_gc.c:    return erts_gc_after_bif_call_lhf(p, ERTS_INVALID_HFRAG_PTR,
./emulator/beam/beam_emu.c:         result = erts_gc_after_bif_call_lhf(c_p, live_hf_end, result, reg, arity);
./emulator/beam/beam_emu.c:             nif_bif_result = erts_gc_after_bif_call_lhf(c_p, live_hf_end,
</pre>

**Comment by garazdawi** [comment]
@kostis sigh, I missed a "not". I meant to say: how do I go about getting to know which non static c functions are not called elsewhere in the code using grep?

Anyways, this error is not a fault of the tool I used, but of my own sloppyness. Btw if you do have a way to find "dead" code using grep (or any other tool), please do share. I want to find a analysis tool for C that can detect dead defines, types, functions etc.

**Comment by kostis** [comment]
> Btw if you do have a way to find "dead" code using grep (or any other tool), please do share. I want to find a analysis tool for C that can detect dead defines, types, functions etc.

@garazdawi I find this surprising coming from you. It's essentially the same process as what a tracing garbage collector needs to do. Think about it ;)

**Pull request merged**
