### PR TITLE
Dialyzer minor improvements / refactoring

### PR DESCRIPTION
**Pull request by lucafavatella**
Each commit is an independent small Dialyzer improvement / refactoring. I created only one PR as I think this is the most clean way to get the changes reviewed but please let me know if you prefer I split in separate PRs / remove some commits / etc.

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: Clarify function return value and side-effect code in Dialyzer
Delete a couple of leftover chars in type spec and Dialyzer doc


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by lucafavatella** [comment]
I removed the last commit (5325c1d "Better reflect side-effect code in Dialyzer. Change similar to 49ccc5d.") because it was breaking typer (it was a debatable change anyway).

BTW Sadly typer has no tests.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
"Prefer fun clauses to case-in-fun in dialyzer_utils"
I suggest this commit is left out since it's a matter of taste if one
considers this an improvement.

"Split race_data server out of dialyzer_callgraph"
I've nothing against this commit, per se, but I wonder if it's worth
it. Maybe Stavros or Kostis has something to say about the future of
the race detection in Dialyzer. Will it be removed completely
eventually?

The rest of the commits are OK, I think (but I haven't checked the
"Clarify..." in detail).

**Comment by aronisstav** [comment]
I agree with @uabboli about ed5b6a75bd7247eeb72dffcb06f8dcc0169e1bf6.
Regarding the race detection, I do not have an opinion about its future. The refactoring makes sense, anyway (I remember wondering what to do about it while developing the parallel version).

**Comment by lucafavatella** [comment]
Thanks for your feedback. I understand action is on me - I hope to come back to this in a month or so.

**Comment by uabboli** [comment]
I'll create a ticket for this pull request. All commits except ed5b6a7 will be included in the 'master' branch (OTP 19.0) with a few minor modifications.

**Comment by lucafavatella** [comment]
I see this was merged in d5b4f05.
@uabboli Thanks for taking care of this.

**Pull request closed without merging**
