### PR TITLE
Add helper function to reduce code duplication

### PR DESCRIPTION
**Pull request by rokob**
I was going through application_controller.erl looking for why
something was behaving a certain way, saw a comment about removing
this duplicated code one day, and decided to move that a step forward.

### CODE REVIEW

**Comment by sirihansen** [comment]
The change is probably ok, but please back out the whitespace changes so it is easier to see the real change.

**Comment by zhird** [comment]
@rokob, any updates on when you can get to backing out the whitespace changes for this?

**Comment by rokob** [comment]
Sorry, took a little longer to get back to this. I backed out the whitespace changes.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
Hi. It would be appreciated if you merge the 2 commits into one ;)

**Comment by rokob** [comment]
Oops, let me fix that

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
