### PR TITLE
Report arguments in the order given

### LINKED ISSUE #7934: argparse help shows arguments in the wrong order
**Describe the bug**
In experimenting with argparse -- https://www.erlang.org/doc/man/argparse.html, it seems that the help text displays positional arguments for nested commands in the wrong order.

**To Reproduce**

```
main(Args) ->
    argparse:run(
        Args,
        #{
            arguments => [#{name => global}],
            commands => #{
                "list" => #{
                    arguments => [#{name => what}],
                    handler => fun(A) -> io:format("~p~n", [A]) end
                }
            }
        },
        #{progname => ?MODULE}
    ).
```

Here we have an example that takes a "list" command, taking two arguments: "global" (common to all commands) and "what" (specific to the "list" command).

The help text shows the following:

```
% ./example list
error: example list: required argument missing: global
Usage:
  example list <what> <global>

Arguments:
  what   what
  global global
```

You can see that it claims to expect "what" and then "global".

However, the parser expects "global" and then "what" as seen here:

```
./example list global what
#{global => "global",what => "what"}
```

**Expected behavior**

The help text should display the positional arguments in the correct order.

**Affected versions**

OTP-26.1.2

**Additional context**

I guess you could argue that it's kinda weird to use positional arguments in the face of sub-commands, but argparse allows it, so it should do it correctly.

### PR DESCRIPTION
**Pull request by rlipscombe**
Fixes #7934

### CODE REVIEW

**Comment by max-au** [comment]
Code looks good to me. I'd also suggest to update documentation (here: https://github.com/erlang/otp/blob/master/lib/stdlib/doc/src/argparse.xml#L691 ) to make this sort order official. The original implementation did not make any promises about usage argument order, and I'd like to hear from the OTP team if they're OK with changing that.

**Comment by jhogberg** [comment]
Thanks for the PR!

I think it's reasonable to expect that the usage printout reflects the actual argument order. If I've understood things correctly, the problem is that users may be confused into writing the following?

```
% ./example list
error: example list: required argument missing: global
Usage:
  example list <what> <global>

Arguments:
  what   what
  global global

% ./example list what global
#{global => "what",what => "global"} # Instead of #{global => "global",what => "what"}
```

**Comment by jhogberg** [comment]
Great! I agree that the order should be defined in the documentation. If nothing else it will give everyone a stable foundation, I don't think anyone would like their argument order to change from one OTP version to another.

**Comment by max-au** [comment]
Should this be based off `maint`? If we agree to qualify this oversight as a bug, I'd suggest so.

**Comment by jhogberg** [comment]
Sure, `maint` sounds good. :)

**Comment by rlipscombe** [comment]
> to make this sort order official

Any suggested wording? I mean: these are positional arguments, so they're kinda _defined_ by their position...

> Sure, `maint` sounds good. :)

Because rebasing breaks the PR conversation, I'll reopen this against `maint` once we've resolved the above.

**Comment by jhogberg** [comment]
> Because rebasing breaks the PR conversation, I'll reopen this against maint once we've resolved the above.

You can keep the conversation alive by force-pushing the rebased branch, then select `Edit` near the PR's title, and changing the base to `maint`.

**Comment by rlipscombe** [comment]
> changing the base to maint

Done. TIL about `git rebase --onto`

**Comment by jhogberg** [comment]
> I took a stab at this in [4cbac1e](https://github.com/erlang/otp/commit/4cbac1e88ec74efa1fc6985a337112d6d75ee84e).

I'm happy with that, it's short and to the point. Feel free to squash the commits, I'll merge it by Friday or early next week :-)

**Comment by rlipscombe** [comment]
> Feel free to squash the commits, I'll merge it by Friday or early next week :-)

I've rebased on the current state of maint, squashed the commits, and added a (hopefully) useful commit comment.

**Review by max-au — APPROVED** [review]

**Comment by jhogberg** [comment]
Merged, thanks again for the PR! :)

**Pull request merged**
