### PR TITLE
Add uptime() shell command

### PR DESCRIPTION
**Pull request by richcarl**
Inspired by http://erlang.org/pipermail/erlang-questions/2010-March/050078.html

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by uabboli** [comment]
Looks good. However, there is no spec, no test case (shell_SUITE or c_SUITE), and
no documentation in c(3).

Best regards,

Hans Bolinder, Erlang/OTP team, Ericsson

**Comment by richcarl** [comment]
Added spec and xml docs, but none of the other info-printing shell functions have testcases, so I don't quite know how you'd like such a test to work. And the output is always different depending on the time when you run it, so you can only really test that the function prints a nonempty string.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Pull request merged**
