### PR TITLE
Reimplement efile_drv as a NIF

### PR DESCRIPTION
**Pull request by jhogberg**
This PR reimplements efile_drv as a NIF and cleans up a lot of old cruft in the process. I've tried to keep functional changes to a minimum but there are two points I've decided to break;

* The `use_threads` option for `file:sendfile/5` no longer has any effect; we either use non-blocking `sendfile(2)` or fall back to `file:read` + `gen_tcp:send`. The gist of it is that there's an awful race at play and we have to choose between `use_threads` and the ability to cancel sendfile operations with `gen_tcp:close`. :(
* The file-specific DTrace probes have been removed. The same effect can be achieved with normal tracing together with the `nif__entry`/`nif__return` probes to track scheduling.

Performance has been improved a bit as the new implementation hands blocking operations to dirty IO schedulers instead of async threads, which lowers latency as they're more eager to run new jobs. Their shared global queue also eliminates the risk of an operation stalling behind a long-running job on the same async thread while other threads sit idle.

I'm particularly interested in hearing about regressions, as well as feedback on the NIF API extension in the first commit (A dependency from a different branch).

### CODE REVIEW

**Comment by jhogberg** [comment]
To give you an idea of how much the performance has improved, I've recorded the microbenchmarks (21563f2) over the past week. The blue line is this branch, the green line is the maint branch, and "stones" are IOPS.

tiny_reads
tiny_reads_ahead
large_writes
large_writes_delayed
tiny_writes
tiny_writes_delayed
(This last one may be a bit unfair as it hits a performance bug in the old driver, but hey, it's faster!)

**Comment by tuncer** [comment]
Excellent work!

@jhogberg, does this mean `file:sendfile` is now as generally useful as [sendfile_drv](https://github.com/tuncer/sendfile_drv) and [yaws_sendfile_drv](https://github.com/klacke/yaws/blob/master/c_src/yaws_sendfile_drv.c)? The desire of `efile_drv` and `inet_drv` to both own the same handle at different times had been problematic and prevnted the expected benefit in all use cases. Hence, sometimes it was preferable to use the external linked-in drivers instead.

/cc @vinoski

**Comment by tuncer** [comment]
Excellent work!

@jhogberg, does this mean `file:sendfile` is now as generally useful as [yaws_sendfile_drv](https://github.com/klacke/yaws/blob/master/c_src/yaws_sendfile_drv.c) and [sendfile_drv](https://github.com/tuncer/sendfile)? In some use cases `file:sendfile` had been under-performing, but I don't recall the details. Hence, sometimes it was preferable to use the external, linked-in driver(s) instead.

/cc @vinoski

**Comment by jhogberg** [comment]
Thanks!

`file:sendfile/5` does a bit less work when setting up, and `file:sendfile/2` benefits from `file:open/2` being slightly faster, but I can't say for sure as we lack benchmarks at the moment.

What areas were the old implementation weak in?

**Comment by tuncer** [comment]
> What areas were the old implementation weak in?

I don't recall the details, but IIRC @vinoski and @essen did have performance remarks back when Patrik and I implemented `file:sendfile`. @garazdawi might remember as well. The gist was that for some cases the external, linked-in driver(s) performed better.

**Comment by tuncer** [comment]
One problem when we were implementing `file:sendfile` was that `efile_drv` and `inet_drv` both wanted to exclusively own one of the sendfile(2) handles, though that just lead to hack'ish code and not a performance drop.

**Comment by tuncer** [comment]
`tiny_writes_delayed`'s estones used to be stable, and the new code is much better but has a lot more variance. It doesn't seem like an issue, though I'm curious if there's an interesting explanation.

**Comment by tuncer** [comment]
I didn't do this myself, but I know some developers use the file api in `raw` mode, and there are even projects that use `prim_file` to circumvent the server. Did the optimizations shrink the overhead? I wouldn't think so.

**Comment by jhogberg** [comment]
> One problem when we were implementing file:sendfile was that efile_drv and inet_drv both wanted to exclusively own one of the sendfile(2) handles, though that just lead to hack'ish code and not a performance drop. **IIRC @garazdawi, implemented (explicit) cooperative sharing of the handle.**

The new implementation does something similar.

> tiny_writes_delayed's estones used to be stable, and the new code is much better but has a lot more variance. It doesn't seem like an issue, though I'm curious if there's an interesting explanation.

The old code has a bug that sometimes causes `delayed_write` to block until writes _time out_ for no good reason, giving it bad performance with very little variance. The benchmark triggers it consistently but you can hide its effects by setting the timeout to 1ms, in which case it lands somewhere around half the speed of the new implementation with similar variance.

> I didn't do this myself, but I know some developers use the file api in raw mode, and there are even projects that use prim_file to circumvent the server. Did the optimizations shrink the overhead? I wouldn't think so.

That's correct, the PR doesn't touch "ordinary files" and all the improvements are to `raw` mode. They'll be faster as a consequence of `raw` mode being faster, but it's not a drastic improvement.

FWIW, there's nothing wrong with using `raw` and it has negligible overhead over using `prim_file` directly, it's just one `apply/3` away.

**Comment by jhogberg** [comment]
Merged into master.

**Pull request closed without merging**
