### PR TITLE
crypto: Make ed25519/x25519 available without ed448/x448

### PR DESCRIPTION
**Pull request by VlkrS**
This is an attempt to resolve https://github.com/erlang/otp/issues/9000

### CODE REVIEW

**Comment by sverker** [comment]
@VlkrS This looks good. Have you tested it yourself with LibreSSL that it solves the problem?

**Review by sverker — DISMISSED** [review]

**Comment by VlkrS** [comment]
> @VlkrS This looks good. Have you tested it yourself with LibreSSL that it solves the problem?

Yes, I tested with the OpenBSD port of OTP 27. I didn't test on other platforms than that, however.

**Comment by sverker** [comment]
I squashed it into one commit and rebased on `maint` branch to be released in OTP 27.3.

**Review by sverker — APPROVED** [review]

**Comment by VlkrS** [comment]
> @VlkrS Does this sound ok as release note:
> 
> > Allow for ED25519 and X25519 being available without ED448 and X448, which is the case in LibreSSL. This is necessary for supporting TLS1.3 using LibreSSL.

lgtm, thanks!

**Pull request merged**
