### PR TITLE
Fix formatting of depth option

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Checkout the maintenance branch failed:

    c/com/ericsson/otp/erlang'
     JAVAC	/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/priv/com/ericsson/otp/erlang/OtpAuthException.class
    OtpAuthException.java:29: error while writing com.ericsson.otp.erlang.OtpAuthException: could not create parent directories
    public class OtpAuthException extends OtpException {
           ^
    1 error
    make[4]: *** [/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/priv/com/ericsson/otp/erlang/OtpAuthException.class] Error 1
    make[4]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/java_src/com/ericsson/otp/erlang'
    make[3]: *** [opt] Error 2
    make[3]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface/java_src'
    make[2]: *** [opt] Error 2
    make[2]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib/jinterface'
    make[1]: *** [opt] Error 2
    make[1]: Leaving directory `/ldisk/jenkins/jobs/pullrequests/workspace/otp/lib'
    make: *** [tertiary_bootstrap_build] Error 2



----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by zhird** [comment]
Hi, did you get the email about license confirmation?

**Comment by ericmj** [comment]
Yes, just replied to it.

**Pull request merged**
