### PR TITLE
Add OTP versions in docs for "new" functions and modules

### PR DESCRIPTION
**Pull request by sverker**
The reference documentation will tell in which OTP version a function or module was first introduced.

For entire new modules, a "Since" headline is added at the top. Example:
http://erlang.org/~sverker/since/lib/stdlib-3.6/doc/html/rand.html

For functions, an OTP version is shown in the right margin. Example:
http://erlang.org/~sverker/since/erts-10.1.3/doc/html/erlang.html
(search for "OTP" a couple of times)

OTP versions older than R13B04 will not be shown.

You can browse all modules here:
http://erlang.org/~sverker/since/doc/man_index.html

### CODE REVIEW

**Comment by essen** [comment]
Nice! That's useful. Orange though?

**Comment by sverker** [comment]
@essen
For functions I thought the versions should have something that makes them stand out from the surrounding text, a possibly long function spec.

Maybe green is nicer, same color as the "Note" boxes.

**Comment by essen** [comment]
> For functions I thought the versions should have something that makes them stand out from the surrounding text, a possibly long function spec.

It does! Perhaps a bit too much.

> Maybe green is nicer, same color as the "Note" boxes.

I'm sure @marianoguerra will want to pitch in. :-)

**Comment by michalmuskala** [comment]
That's a great addition overall. It will make it simpler when working on libraries that need to support older versions.

For reference this is how similar information is displayed in the Elixir docs: https://hexdocs.pm/elixir/Date.html#add/2

**Comment by marianoguerra** [comment]
Looks good! 

Maybe for recent releases (2?) it has a more prominent color, since you should consider the compatibility implications of using it

for older releases it gets a softer color like grey, since it should be OK to use them, and someone who has to support older versions knows where to look.

**Comment by KennethL** [comment]
The actual layout in the generated html is not in place yet. And is open for comments. A modified version is under construction.

**Comment by crownedgrouse** [comment]
Orange color should be used for deprecated functions and modules, maybe?

**Comment by sverker** [comment]
Now a more discreet look.

**Comment by essen** [comment]
Looks good!

**Pull request merged**
