### PR TITLE
docs: fix simple typos

### PR DESCRIPTION
**Pull request by siiky**

### CODE REVIEW

**Review by kikofernandez — APPROVED** [review]
Thanks for fixing the typos, greatly appreciated.

**Comment by kikofernandez** [comment]
I will run some tests tonight that check that all works as expected and merge on Wed (Tuesday June 6 is the Swedish national day, i.e., we have a free day to eat lots of strawberries,  😆 )

**Comment by kikofernandez** [comment]
Would it be possible to squash all commits into a single one? If you can do this before Tuesday (June 6) at 18:00 CEST, I can check our internal tests and merge on Wed morning :) 

Thanks for your contribution!

**Comment by siiky** [comment]
Squashed and rebased against the latest master.

BTW I tried running `make xmllint` but there was an about some `.erl` file missing; do you know what could be the cause?

**Comment by kikofernandez** [comment]
I will check, but your typos fix should not affect that.

Could you rebase on top of `maint`, so that your changes are included in the first patch of OTP 26? :)

I believe that for this to work, you may need to close this PR and open a new one against `maint`, but maybe there are other ways?

**Comment by kikofernandez** [comment]
@siiky changing the base branch won't work because it now includes changes from `master` into `maint`, and those changes are things we have merged for `master`.

**Comment by kikofernandez** [comment]
For my understanding, so that I can do the same thing in the future.
Did you change the base branch, rebase / cherry pick your commits on top of `maint`, and force push to the same branch?

**Comment by siiky** [comment]
Exactly, after hitting the "edit" button it let me change the base. Locally I just rebased and force-pushed, as you said.

**Pull request merged**
