### PR TITLE
Introduce `erpc:call_opt/3,5`

### LINKED ISSUE #8641: `erpc:call` behavior is different on local and remote nodes
**Describe the bug**
`erpc:call` usually runs the given function in a spawned process. However, if the given `Node` is the local node and if the given `Timeout` is `infinity` (implicit in `erpc:call/2` and `/4`), an optimization is used that instead uses `erlang:apply`:

https://github.com/erlang/otp/blob/d05de4c400200fabf3b22edd8cd7f75a02d44602/lib/kernel/src/erpc.erl#L255-L260

https://github.com/erlang/otp/blob/d05de4c400200fabf3b22edd8cd7f75a02d44602/lib/kernel/src/erpc.erl#L1267-L1270

Using `apply` means that the given function is executed in the context of the process calling `erpc:call`, which can have a row of unintended consequences:

* The function could accidentially corrupt the state or interfere with the workings of the calling process, eg by modifying the process dictionary or private/protected ets tables, closing files or sockets, stealing messages, changing the `trap_exit` flag, linking/monitoring (or unlinking/demonitoring) other processes, etc. All of this can not happen if the function executes in a separate process.
* The function could cause memory leaks by opening but not closing files or sockets, creating ets tables, etc. If the function executes in a separate process, it can create quite a mess which would all be neatly cleaned up when it finishes. When executed in the calling process, the mess remains.
* When the calling process exits (eg via a link, explicit exit/kill, etc) while executing the function, the function is basically interrupted at whatever it is doing. When executed in a separate process, it runs through to the end, no matter what happens to the calling process.

**To Reproduce**
Exemplified by creating an `private` `ets` table. The distinction between executing the function in the calling process (1> and 2>) vs a separate one (3> and 4>) is forced by the timeout.
```erlang
1> erpc:call(node(), fun() -> ets:new(foo, [named_table, private]) end, infinity).
foo
2> ets:tab2list(foo).
[]
3> erpc:call(node(), fun() -> ets:new(bar, [named_table, private]) end, 1000).
bar
4> ets:tab2list(bar).
** exception error: bad argument
     in function  ets:match_object/2
        called as ets:match_object(bar,'_')
        *** argument 1: the table identifier does not refer to an existing ETS table
     in call from ets:tab2list/1 (ets.erl, line 2266)
```
As can be seen at 2>, the `ets` table created in the call at 1> still exists, and is also accessible by the calling process. Conversely at 4>, the `ets` table created in the call at 3> is gone.

Exemplifying the interruption of the function when the calling process crashes. A function sets a timer to kill itself after 1s, then uses `erpc:call` to execute a function which waits 2s before sending `done` back to the shell.
```erlang
1> Self = self().                                                                                        
<0.81.0>
2> spawn(fun() -> timer:kill_after(1000, self()), erpc:call(node(), fun() -> timer:sleep(2000), Self ! done end, infinity) end).
<0.108.0>
3> receive done -> ok after 5000 -> error end.                                                                                  
error
4> spawn(fun() -> timer:kill_after(1000, self()), erpc:call(node(), fun() -> timer:sleep(2000), Self ! done end, 5000) end).
<0.104.0>
5> receive done -> done after 5000 -> error end.
done
```
As can be seen at 3>, the `done` message never arrives when the calling process exits in the wait period of the function that was started at 2>. Conversely, at 5> we get the `done` message even though the calling process exited.

**Expected behavior**
`erpc` call should behave the same, no matter the node or timeout. Specifically, it should _always_ execute the given function in a separate process.

**Affected versions**
OTP 27, but probably going back all the way to OTP 23 when `erpc` was introduced.

**Additional context**
The optimization seems pointless to me. When the function is executed at the local node, it already _is_ fast, no need to try to shave off a few microseconds. Also, it only takes place when the given `Timeout` is `infinity`, which indicates that the caller is prepared to wait for however long it takes, not in a hurry.

### PR DESCRIPTION
**Pull request by juhlig**
Fixes #8641.

### CODE REVIEW

**Comment by juhlig** [comment]
After much discussion in #8641, and with help from @Maria-12648430, the last commit provides a solution that enables users to force `erpc:call`s to be executed in a freshly spawned process while not breaking any existing code.

**Comment by Maria-12648430** [comment]
Final answers are still out in #8641, but it may be a good time to remove the "..., by a server, ..." passages from the notes on executing process assumptions. These only seem to apply to the legacy `rpc` module, not `erpc`.

Also, the specs for the functions that take a `fun` use `function()` and mention in the doc text that it must be a 0-arity fun. It might be better to change those specs to `fun(() -> Result)`, WDYT?

**Comment by josevalim** [comment]
One nitpick on the name: the original issue was about reusing the caller process. The new option, however, would require a new process to always be spawned. However, if in the future `erpc` decides to reuses processes on the remote node (as `rpc` did in the past), then I would expect the option to also start fresh processes there, which may not be desired? In that case, it may be better for the option name to be more specific and be called `reuse_caller`, which can be set to false. This will make it clear that it is exclusively about reusing the caller process.

I am fine either way but I wanted to make sure this aspect is not overlooked.

**Comment by josevalim** [comment]
@juhlig good points! I guess the words we want here is "local" (we are talking about the current node) and "spawn", so maybe `spawn_local` or `always_spawn_local` or something along those lines. But overall `always_spawn` is also fine, it just has to be respected in the future. :)

**Comment by juhlig** [comment]
@josevalim I'll leave it at `always_spawn` for now and wait for more opinions then.

**Comment by juhlig** [comment]
There are two failing tests, namely `call_against_old_node` and `call_from_old_node failed`. They are skipped on my local machine, I don't know how to make them run :man_shrugging:

The failing tests go as far as minutely testing the stack trace produced by a failing call. I wonder why this is necessary
When called on a node running a release with the changes in this PR, the function causing the exception is `erpc:do_call/6`. When an older node is involved, the failing function is `erpc:call/5` instead. This seems to me hard to resolve, I could use some pointers how to address this.

**Comment by rickard-green** [comment]
We have had mixed opinions about this at OTP. One point being: why not spawn processes yourself if you want a spawned process.. Besides the `call` operation we also got the `send_request`, `multicall`,  `cast`, and `multicast` operations...  We'll have some more discussions about this and get back to you.

**Comment by rickard-green** [comment]
We've decided on the following. Extend `call/3`, `call/5`, `multicall/3`, `multicall/5`, so that they also can take an option map on the following format instead of the timeout argument:
```
#{
   timeout => timeout_time(), %% default: infinity
   always_spawn => boolean() %% default: false
  }

Also remove the documentation about that the process applying the function might a server from all functions.
```

**Comment by juhlig** [comment]
@rickard-green thanks, I'll see to it next week.

**Comment by juhlig** [comment]
@rickard-green I extended `call/3,5` and `multicall/3,5` as requested, please have a look. Documentation changes and tests are still out, I'll have to get back to that later.

**Comment by juhlig** [comment]
@rickard-green the last two commits add the documentation changes and tests. IMO this is ready for review now.

**Comment by Maria-12648430** [comment]
@rickard-green on another note...
https://github.com/erlang/otp/blob/ee9628e7ed09ef02e767994a6da5b7a225316aaa/lib/kernel/src/erpc.erl#L107-L127

The restriction to `4294967295` stems from `receive... after` accepting only values up to `4294967295`, and could be lifted the same way that `timer:sleep/1` was made to accept values greater than `4294967295`.

Now, I am of course aware that nobody in his right mind would want to wait longer than ~49 days (vs `infinity`) for a response, so this would only be for the kinda aesthetic reason of removing this limitation from the docs. WDYT?

**Comment by rickard-green** [comment]
Sorry for the long delay. Got swamped with other work that I needed to prioritize. I'll try to bring this PR forward now. It still may take some time for me to respond, but not as long as this delay.

**Comment by rickard-green** [comment]
> @rickard-green I think the following paragraph should be removed from the documentation of `erpc:multicall/5`:

> IMO it adds little value, the opening sentence "Performs multiple call operations in parallel on multiple nodes." explains all what `multicall` does. There is little value in having a long paragraph explaining an equivalent but more complex (14 lines!) and less performant solution.
> 
> If you agree, we could remove it in this PR, or should we open another for it?

I don't agree. I think it serves two purposes. It points out that you'll get the selective receive optimization by using it which you wont if you implement it yourself using the `send_request/receive_response` primitives. I also think it serves the purpose of showing what a multicall actually is even though it is obvious for a lot of people.

**Comment by rickard-green** [comment]
> The restriction to `4294967295` stems from `receive... after` accepting only values up to `4294967295`, and could be lifted the same way that `timer:sleep/1` was made to accept values greater than `4294967295`.
> 
> Now, I am of course aware that nobody in his right mind would want to wait longer than ~49 days (vs `infinity`) for a response, so this would only be for the kinda aesthetic reason of removing this limitation from the docs. WDYT?

I have nothing against lifting this restriction, but I don't see it as especially important. If you want to do it, make a separate PR for it, though.

**Comment by juhlig** [comment]
@rickard-green I still have problems with the tests that involve older versions. Would be grateful for any pointers =^^=

**Comment by rickard-green** [comment]
@juhlig I cannot see any such failures in our internal daily builds. I suspect that it was an issue unrelated to this PR that has been fixed in master now.

**Comment by juhlig** [comment]
@rickard-green ok then, then I would say this is ready for review :+1:

**Comment by rickard-green** [comment]
Merged now, thanks for PR!

**Pull request merged**
