### PR TITLE
public_key:generate_key/1 RSA key generation inconsistency

### PR DESCRIPTION
**Pull request by angelhof**
This pull request "fixes" the following inconsistency.

It is stated in the documentation that the record 'RSAPrivateKey' has the following form:
```
#'RSAPrivateKey'{        
         version,         % two-prime | multi
	  modulus,         % integer()
	  publicExponent,  % integer()
	  privateExponent, % integer()
	  prime1,          % integer() 
	  prime2,          % integer()
	  exponent1,       % integer()
	  exponent2,       % integer()
	  coefficient,     % integer()
	  otherPrimeInfos  % [#OtherPrimeInfo{}] | asn1_NOVALUE
	 }
```
and public_key:generate_key/1 creates an 'RSAPrivateKey' record with version = 0.

I chose to change the generate_key implementation and not the docs because in my opinion version = 'two-prime' seems more natural, and favors comprehension.

### CODE REVIEW

**Comment by RaimoNiskanen** [comment]
We would have preferred your branch name being something describing the topic of the change, but let's roll with this for now...

**Comment by angelhof** [comment]
I am sorry for that. Should I open a new pull request with a better branch name and close this one?

**Comment by RaimoNiskanen** [comment]
Nah.  I just will have to remember to fix the merge commit message to not say "Merge from branch 'maint'", which would become confusing (note to self).

**Comment by RoadRunnr** [comment]
Might not be relevant, but ssl/test/ssl_test_lib.erl is setting the version to 0 as well. It's not using the record declaration, that might explain why you missed it. Should this also be changed?

**Comment by angelhof** [comment]
Yes @RoadRunnr you are right, I missed this. I suppose that I have to change this too.

**Comment by IngelaAndin** [comment]
Hum .. maybe it should be reformatted to the record in ssl_test_lib, I just ran public_key:generate_key and pasted the result to the test files. There are several reasons to want to hard code the tests data, one being that not all platforms will support key generating another that some key generations may occasionally take a very long time.  

I think the PR is a sane change, I will let it run in test for a couple of more days as we had some test disturbing  the last couple of days.

**Comment by IngelaAndin** [comment]
Ok it this looks good in the tests. But as I consider this a bug I would rather this be based on maint than on master and then you get the opportunity to call your branch something more describing!

**Pull request closed without merging**
