### PR TITLE
ERL-980: Fixed map size check for ipv4 and ipv6 socket:setopt add_membership

### PR DESCRIPTION
**Pull request by srstrong**

### CODE REVIEW

**Comment by bmk** [comment]
Hi,

First, I have already a fix for this. It will be released in the next patch (I hope).
In testing now.
Second; The white space explosion makes it hard to find what it is you have done
(and see if you have found something I have missed).

Regards,
     /BMK

**Comment by bmk** [comment]
I have merge my branch into maint and master. Patch coming.
But it would still be useful if you could "cleanup" your branch (white space's)
and resubmit, so that I could check if you have found something else.

Regards,
    /BMK

**Comment by bmk** [comment]
A colleague showed me how its possible to view the diff without white space changes
('hide white space changes') .
Magic stuff!
Anyway, you have the same fix as me, so we are done.

Regards,
    /BMK

**Comment by IngelaAndin** [comment]
As the issue is resolved I will close this PR now.

**Pull request closed without merging**
