### PR TITLE
Optimize and increase stability of open_port({spawn, ""},...)

### PR DESCRIPTION
**Pull request by garazdawi**
Instead of forking from the beam process, we create a separate
process in which all forks are done. This has several advantages:

1) performance:
  * don't have to close all fd's in the world
  * fork only has to copy stuff from a small process
  * work is done in a completely seperate process
  * a 3x performance increase has been measured,
    can be made even greater (10x) if we cache the
    environment in child setup

2) stability
  * the exec is done in another process than beam, which means that
    if the file that we exec to is on an nfs that is not available
    right now we will not block a scheduler (or the vm in the case of vfork) until the nfs returns.

3) simplicity
  * don't have to deal with SIGCHLD in the erts

Unfortunately, this solution also implies some badness.

1) There will always be a seperate process running together with
   beam on unix. This could be confusing and undesirable.
2) We have to transfer the entire environment to child_setup
   for each command.

This pull request also adds two new driver API's that are needed for this feature, erl_drv_set_pid and asynchronous open_port, and various refactorings.

### CODE REVIEW

**Comment by sverker** [comment]
Valgrind complains about memory leak at 
erts_internal_open_port_2:83 [erl_bif_port.c].

I added 

    if (prt->async_open_port)
	    erts_free(ERTS_ALC_T_PRTSD, prt->async_open_port);

in erts_port_free() which seems to fix it.
But is it also a leak in the ERTS_PROC_PENDING_EXIT case?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
@sverker It should be enough with just that fix, as erts_port_release will call erts_port_free if it is the last reference to the port.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
merged

**Pull request closed without merging**
