### PR TITLE
Support expirable gen calls

### PR DESCRIPTION
**Pull request by g-andrade**
This PR proposes an implementation of expirable `gen` calls, following a recent mailing list [thread](http://erlang.org/pipermail/erlang-questions/2018-January/094667.html) where this idea was first mentioned by @jlouis and then further discussed.

The rationale behind it is to minimize the impact of common overload patterns of singleton `gen` processes, where work delivered to a slow consumer risks piling up until either work production slows down or resource exhaustion is reached in a feedback loop, as [succinctly exposed](http://erlang.org/pipermail/erlang-questions/2018-January/094662.html) by @maxlapshin on the same thread.

The core of the presented solution lies on optionally attaching an `Expiration` value to the call message, in native units of monotonic time. When the consumer (`gen_server`, `gen_statem`, ...) receives the call message it will compare the current monotonic timestamp against the expiration value and, if it's equal or greater, the call will be ignored.

Because monotonic timestamps originating on different nodes are not comparable, for this to work when calling a remote `gen_server` a temporary process is spawned remotely that's responsible for determining the expiration timestamp, attaching it to the call message and dispatching the call to the process.

In order to avoid the overhead of performing all of the above unless strictly necessary, un-expirable calls are still sent and processed in the same way. For the same reason, local expirable calls don't make use of temporary processes as remote ones do. There's no interface breakage other than for `gen` consumer behaviours that desire to support expirable calls.

### CODE REVIEW

**Comment by g-andrade** [comment]
For now, only `gen_server` has been extended in order to support expirable calls, and no test cases were yet written - I would first like to know what does the OTP team think about it, and whether it's a route that can be followed.

**Comment by deadtrickster** [comment]
I've been using this technique for a while. Would be cool to have it included in OTP itself. Each call has to be marked expirable explicitly? Can we have process-wide default setting? probably passed to start?

**Comment by g-andrade** [comment]
I considered a general per-process setting (controlled using `process_flag/2`) that would determine whether inbound messages would get a monotonic timestamp attached at the moment of insertion into the message queue. When such a setting were to be active, one could then filter out any old message when using `receive` clauses, perhaps in the following fashion:

```erlang
receive
    Message:Age when Age < 5000 ->
        do_work(),
        loop()
    _Message ->
        % discard
        loop()
end
```
But it would require far-reaching changes to ERTS and the way messages are delivered, as well as the language syntax itself. It would likely consume significantly more memory as well. All in all, it sounded like something appropriate for a five year plan, but definitely not something that we might see around soon (assuming it's both acceptable and accepted.)

**Comment by g-andrade** [comment]
> Each call has to be marked expirable explicitly?

Under this solution that only touches `gen` calls, that's a yes.

**Comment by maxlapshin** [comment]
This approach still will block calling process even if we know for sure that server is not responsible.

If there is a storm of web requests that make calls from different processes, message queue is not protected from endless overfilling.

Maybe it should be better to add a concept of watchdog to a message queue? If process do not reset a watchdog, then sending message to it will fail. This will require change in vm.

----
Max Lapshin
+7 (906) 711-11-14

**Comment by lpgauth** [comment]
@maxlapshin to protect against endless overfilling you can use an ETS counter. When you want to send a message you increment the counter. If the counter is lower than X you send the message if it's equal to X you drop early. When the server is done processing the message it decrements the counter.

https://github.com/lpgauth/shackle/blob/master/src/shackle_backlog.erl

**Comment by okeuday** [comment]
@maxlapshin @lpgauth We also have `erlang:process_flag(max_heap_size, MaxHeapSize)` to enforce a total limit on the process memory size.  However that could be a problem with `erlang:process_flag(message_queue_data, off_heap)` usage (default is `on_heap`) because the message queue data wouldn't be included in the size.  I prefer the approach with an additional process and a queue data structure using timers for the timeout, which is what happens in [CloudI](http://cloudi.org) services, and that doesn't depend on global data use in `ets`.  By using timers with a queue no extra process is required for calls from remote nodes to get the correct monotonic time, though the time spent in the Erlang process message queue isn't included then.  The use of timers for this would add memory consumption in the ERTS timer wheel which can be more significant for larger timeout values (i.e., if the processing takes longer).  However, I wouldn't expect that approach to be allowed within the `gen_server` behaviour.

**Comment by deadtrickster** [comment]
I think this PR tries to solve well-definable problem. For me it sounds like "if client doesn't care we not doing this".

My feature list:

1. Expirable per-call (implemented);
2. Expirable by default (could be set via worker options in supervisor config);
3. Do not even call `handle_call` if `From` is dead in `handle_msg` (this can be controlled by another option, have no preference here).

This of course manages gen's load and saves resources managed by it.
Calling processes can be guarded in many ways. Perhaps even with fuse (melted when expired call discarded) - slightly more complex than @lpgauth's simple counters idea but ready to use.
I would suggest leave clients for the moment.

**Comment by g-andrade** [comment]
@maxlapshin @okeuday and @lpgauth, many of the solutions you all mentioned are valid approaches to solving overload, and I myself have used fuse and other suchlike tools extensively. But, in general, they're not mechanisms I would expect to be bundled with OTP - at least not short term. Besides, I don't think _anything_ that would break the current `gen` architecture would have a real chance of being accepted.

**Comment by g-andrade** [comment]
@deadtrickster 

> 2. Expirable by default

This would be tricky under the current architecture, as you'd need to find an elegant way to share that default with callers - most of the answers that come first to my head either constitute performance bottlenecks on the VM, or they could exhaust resources, or they're simply not adequate for working with distribution (ETS? process dictionary? a specially formatted registered name?)

> 3. Do not even call handle_call if From is dead

This could be done for local callers by using `is_process_alive/1` (assuming the performance hit would be negligible, which might not be true.) But it wouldn't cover remote callers.

**Comment by deadtrickster** [comment]
What you mean 'share with callers'? 
Say I wrote a gen_server, I don't want to bother with passing expiration on each call. I just start _my_ gen_server with expiration option which goes to the State which in turn accessible in handle_msg. What you think?

**Comment by g-andrade** [comment]
> What you mean 'share with callers'?

How would a process executing a `gen_server:call` know that it must attach an expiration timestamp when calling a particular server, but not others?

**Comment by g-andrade** [comment]
The only good option would be to _always_ attach the timestamp to the call messages, and leave to the receiver to act upon it depending on policy. This would add overhead to all calls, and would break interface as well.

**Comment by g-andrade** [comment]
> I don't want to bother with passing expiration on each call.

I don't think it would be _that_ bad. You can always wrap it:
```
expirable_call(ServerRef, Call, Timeout) ->
    gen_server:call(ServerRef, Call, [{timeout, Timeout}, expirable]).
```
Which is good in the sense that makes it explicit. It also makes it very natural to distinguish between expirable calls and regular ones, which depending on your business logic might be exactly what you want.

**Comment by deadtrickster** [comment]
> This would add overhead to all calls, and would break interface as well.

If overhead is small maybe it can be acceptable, too lazy to write tests though:-)
What interface it would break?

**Comment by g-andrade** [comment]
The compatibility of call messages between different OTP releases; say, when you have node A and node B running different OTP versions.

**Comment by deadtrickster** [comment]
but this sort of incompatibility still applies to this whole idea and your patches in particular, doesn't it? I mean you've added new handle_msg clause and what if remote node doesn't have it?

**Comment by g-andrade** [comment]
Well, not quite. This is more of an _extension_ of the interface; there's this new call format now, but the old one is still there and nothing has changed about it. And so here's what can happen:
- If you don't use expirable calls, nothing changes between releases and life goes on as it always has.
- If you start using them, then you'll be very self aware that they've appeared upon a particular new release of OTP, and that very clearly it won't work backwards. You would then upgrade rollout accordingly.

> what if remote node doesn't have it

The extended call message would end up in the remote gen_server's `:handle_info` clause... :). I'm waiting on feedback from OTP team on that particular point.

**Comment by deadtrickster** [comment]
> would end up in the remote gen_server's :handle_info clause

sounds like breaking to me :-)

**Comment by g-andrade** [comment]
> The extended call message would end up in the remote gen_server's :handle_info clause... :). I'm waiting on feedback from OTP team on that particular point.

Actually, no, that's not what would happen. Because remote expirable calls depend on a new, exported function that was added to the `gen` module, the remote sender process would simply crash and the call wouldn't get through.

**Comment by g-andrade** [comment]
> sounds like breaking to me :-)
But one would have to break it explicitly, right? It would be upon the developer to shoot themselves in the foot; free will and all of that. If we choose to change the format of all `gen` calls instead, we'd be giving users this rigged shotgun that could blow up at the slightest misstep in upgrade rollouts.

**Comment by deadtrickster** [comment]
Dunno, I don't have a problem with breaking changes personally when they documented properly (maybe it's just my workflow though). Moreover, I expect them actually when major version bumps. Still, gen_* are too important, so yeah, let's wait for feedback from OTP team.

**Comment by maxlapshin** [comment]
I think that adding timestamp is better if you add not current time, but a deadline time. It will help with proper breaking deep nested calls.

**Comment by Pouriya-Jahanbakhsh** [comment]
Hi. I found this issue interesting. I think it's good if every call/cast has some metadata (for example a map, it can be `{'$gen_call', From, Metadata::map(), Msg::any()}` or `{'$gen_cast', Metadata::map(), Msg::any()}`. Sometimes metadata can contains timestamp, send options that sender defined them and other possible values which may add in future for calls/casts. In this solution we can have some fixed size of options and handle them in generic part of code (in code of generic behaviours).
My Second solution is that OTP's generic behaviours need to know and handle every message which is a list with length size equal or greater than 2 that has `$gen_call` tag as its first element as call request and a list whith length size equal or greater than 1 that has `$gen_cast` tag as its first element as cast. for example:
```erlang

loop(..., Mod, State, ...) ->
    receive
        ['$gen_call', From|Opts] ->
                try Mod:handle_call(Opts, From, State) of
                ...
         ['$gen_cast'|Opts] ->
                try Mod:handle_cast(Opts, State) of
                ...
```
In above solution we can handle those options in specific part of code (callbacks).
I'm so sorry if you found my solutions ineffective. I did not read all otp behavior's code compeletly. I just wrote some special process in erlang.

**Comment by josevalim** [comment]
> Expirable by default (could be set via worker options in supervisor config);

I am strongly against this behaviour. It is unlikely all calls can be "expirable" because you most likely want to handle the call/cast and change the server state, even if the initial request has expired. Skipping a request can leave the state inconsistent and I would prefer if this behaviour to be explicitly opted-in on every call.

> Do not even call handle_call if From is dead in handle_msg 

This wouldn't work for remote calls. I would also say that when `From` is dead, it is usually because it reached the timeout, so the current functionality seems to cover most common scenarios.

**Comment by deadtrickster** [comment]
> I am against this option.
You against giving people choice? or you just saying _you_ won't use it?

>  it is usually because it reached the timeout
So what? If gen_server is busy, client queued its call, and then times out, gen_server will still execute it, right? And I'm not sure this always perfectly reflects intention behind call. Example: call to access remote resource, client died, no one interested in result. why bother?

**Comment by okeuday** [comment]
@deadtrickster @josevalim Avoiding adding extra latency with a call to `erlang:is_process_alive/1` in all call paths is a good thing.  `gen_server` shouldn't become slower with its default usage.

**Comment by josevalim** [comment]
> You against giving people choice? or you just saying you won't use it?

Nobody's choice is being removed, you can still achieve the same behaviour without it. It can be as simple as:

    call(Name, Value, Opts) ->
      gen_server:call(Name, Value, [expirable | Opts]).

And now you do all calls for that module via this private function.

I would like potentially dangerous behaviour to be explicit and not located in a separate file when the process is started in a supervision tree.

**Comment by ferd** [comment]
I'm also a +1 on only making the expirable calls manual.

I'm curious how the feature would compose with the internal timeout option, which triggers a timeout iff no message is received. Is an expired message going to cancel or trigger the timeout?

There's the interesting case where an overloaded process with only expirable calls, if they're silently dropped, can be having a queue with hundreds of thousands of messages in it, and since it's in a death spiral of lag, will send an internal timeout as if it were inactive.

I don't know that this is going to be a problem, but I'd rather have these kinds of edge cases figured out before changing one of the main building blocks of all OTP systems out there.

**Comment by deadtrickster** [comment]
Ok, so no technical arguments against having defaults. Still, I understand that community
can be against it for other reasons. (kinda sad that this reason is 'dangerous', though).
Thanks for the feedback.

@okeuday, for local gen_server is_process_alive needed only when it's enabled, not all paths.
And this can be dispatched by matching. Which is fast. Is it fast enough for this case? I don't know.

@fred, what you mean by 'send an internal timeout...'? completely agree about edge cases!

**Comment by g-andrade** [comment]
> @fred what you mean by 'send an internal timeout...'? completely agree about edge cases!

[These](http://erlang.org/doc/man/gen_server.html#Module:handle_info-2) timeouts (e.g. as in the `{noreply,NewState,Timeout}` return value.) 

I hadn't thought of those - good catch. At the moment, I believe it will cancel the timeout (will have to check though.) We probably want to handle this better.

**Comment by josevalim** [comment]
I would say "cancelling" the timeout is a reasonable expectation, since all messages that arrive to the server, even system messages, would "cancel" it. 

We may discuss though what is the definition of "cancellation" here. Does it mean the timeout is lost and we wait for infinity next (currently implemented) or should we re-use the same timeout the next time we call `receive` (as we do for system messages)? I would expect the latter but I don't have a strong argument for it.

**Comment by IngelaAndin** [comment]
As stated before changing defaults is difficult. I would very much like to change the default of gen:call so that it does not have a 5 second time out that kills the client, that is seldom what you want.  But it is very unlikely that we ever get to change that, it would potentially break a lot of existing code. In my experience calls have always been done with an infinity time out to gen and perhaps a time out argument sent to the server that will answer with {error, timeout} if it takes to long to generate some more interesting result. For example a server might send a query to an external database and if the answer does not arrive in reasonable time answer {error, timeout} will be sent to the client and possible answer from the database will discarded.  gen_behaviours (server side) does not have to be blocking on calls just because the client is, see gen_*:reply/2  and return no_reply from handle_call.
This does not really address flow control, but I does give you a sever-side time out that believe will avoid the problem described.

**Comment by Pouriya-Jahanbakhsh** [comment]
For example in Ejabberd when they are interacting with external database and they want expirable calls, in [here](https://github.com/processone/ejabberd/blob/18.01/src/ejabberd_sql.erl#L162) they send current time with query to the server and [here](https://github.com/processone/ejabberd/blob/18.01/src/ejabberd_sql.erl#L430) server calculates send time and receive time difference and does its work and sends reply based this difference.

**Comment by IngelaAndin** [comment]
I think this looks like they implemented a server side timeout and also set the gen:call timeout to some value that hopefully is larger than the server side timeout to work best.

**Comment by g-andrade** [comment]
Hi; any news on this?

**Pull request closed without merging**
