### PR TITLE
zlib: support extraction of inflation dictionary

### PR DESCRIPTION
**Pull request by g-andrade**
zlib already exposes a stream method for this - `inflateGetDictionary` - only the final glue was missing.

### CODE REVIEW

**Comment by garazdawi** [comment]
patch looks good, could you please add a testcase to lib/kernel/test/zlib_SUITE.erl.

**Comment by g-andrade** [comment]
Done. There's still the matter of the preloaded zlib module not including the new method; I recompiled it locally in order to check the testcase but I'm not sure what's the proper procedure for regenerating preloaded modules, so I've left it as is.

**Comment by garazdawi** [comment]
thanks.

I'll take care of the preloaded update.

**Comment by garazdawi** [comment]
@g-andrade Only the latest version of zlib (vsn 1.2.8) has inflateGetDictionary, so there has to be a configure check added that looks to see if the symbol exists or maybe a version check from the zlib header?

i.e. something like this

    #if ZLIB_VER_MAJOR > 4 && ZLIB_VER_MINOR > 1 && ZLIB_VER_REVISION > 7
    #define HAVE_INFLATEGETFICTIONARY 1
    #endif

and return `enotsup` if the version is not correct.

**Comment by g-andrade** [comment]
Fix pushed; but how about the new test case? Should it assume zlib >= 1.2.8 is always being tested?

**Comment by garazdawi** [comment]
No, the test case cannot make that assumption, so it also has to be updated. good catch.

**Comment by OTP-Maintainer** [comment]
The summary line of the commit message is too long and/or ends with a "."
Make sure the whole message follows the guidelines here: https://github.com/erlang/otp/wiki/Writing-good-commit-messages.

Bad message: zlib: Add min. zlib version note to inflateGetDictionary documentation
zlib: Skip inflateGetDictionary test case if operation is unsupported


----------------

I am a script, I am not human 

----------------

**Comment by garazdawi** [comment]
thanks, I've put it into testing again.

We have a 50 character limit on the title of commits which the bot enforces, so if you could update the commit titles to be smaller than that and put any extra info you think it necessary in the body of the commit messages that would be great.

**Pull request merged**
