### PR TITLE
Drop remnants of elib_malloc (removed in R15)

### PR DESCRIPTION
**Pull request by richcarl**
While working on https://github.com/erlang/otp/pull/2627, I found that this elib_malloc stuff was still in there even though the docs said it was to be removed in R15. See https://github.com/erlang/otp/blob/master/erts/doc/src/notes.xml#L16543

### CODE REVIEW

**Comment by michalmuskala** [comment]
Is this related to `ERL_MALLOC_LIB` and `+MYm` emulator option that only support `libc`? If so, processing of that could probably be also removed.

https://github.com/erlang/otp/blob/9cab4f6d7b373babdfeedc9913a63162ba280d44/erts/etc/common/erlexec.c#L491-L505

**Comment by garazdawi** [comment]
You also need to update the clause_i numbers for all the system_info clauses in erlang.xml

**Comment by richcarl** [comment]
> You also need to update the clause_i numbers for all the system_info clauses in erlang.xml

Oh joy!

**Comment by richcarl** [comment]
> Is this related to `ERL_MALLOC_LIB` and `+MYm` emulator option that only support `libc`? If so, processing of that could probably be also removed.

Yes, it's related, but the question is whether OTP want to keep the `+MYm` option around in case they want to try using it again. @garazdawi ?

**Comment by garazdawi** [comment]
> Yes, it's related, but the question is whether OTP want to keep the +MYm option around in case they want to try using it again. @garazdawi ?

Please remove that as well.

**Comment by garazdawi** [comment]
thanks!

**Pull request merged**
