### PR TITLE
Slave specs

### PR DESCRIPTION
**Pull request by wmalik**
Fix types for Host and Name in start/1,2,3 and start_link/1,2,3
Remove commented out code

### CODE REVIEW

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
This could be a reasonable change, but could you explain in the commit message what you are fixing and why?

**Comment by wmalik** [comment]
Done

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Thanks!

One more thing: there is a type called hostname() in inet.erl. Instead of creating your own type, it would better to use inet:hostname() in slave.erl.

**Comment by wmalik** [comment]
I forgot to mention in the commit message that the fix is for the types of `Host` and `Name`. Should we use inet:hostname() for both the `Host` and the `Name`? I think inet:hostname() only makes sense for `Host`. What do you think?

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by bjorng** [comment]
Yes, I agree. inet:hostname() only makes sense for Host.

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by OTP-Maintainer** [comment]
Patch has passed first testings and has been assigned to be reviewed


----------------

I am a script, I am not human 

----------------

**Comment by proxyles** [comment]
merged

**Pull request closed without merging**
