### PR TITLE
Remove query keyword residues

### PR DESCRIPTION
**Pull request by bitnitdit**
There are still some query residues used as a keyword. Remove them.
query was no longer a keyword since the commit 0dc3a29744bed0b7f483ad72e19773dc0982ea50 2012-11-19.

### CODE REVIEW

**Comment by RaimoNiskanen** [comment]
The concerned application maintainers will have to take a look at this after they vacations to see if there still are missed occurrences, or if some of those you removed have some backwards compatibility reason to still exist, or something...

**Comment by uabboli** [comment]
Nitpicking: the quotes in
./lib/kernel/doc/src/inet_res.xml
./lib/compiler/test/compilation_SUITE_data/opt_crash.erl
can be removed.

**Comment by bitnitdit** [comment]
Hi, @uabboli 
IMHO, the 'query' in those two files were not used as keyword, so no need to remove them. 
I'm just Erlang beginner, if I'm wrong, please correct me.
Thanks!

**Comment by uabboli** [comment]
I didn't mean to remove the words, just the quotes. The quotes are a `query` keyword residue.

That is, substitute `query` for `'query'` in those two files.

**Comment by bitnitdit** [comment]
@uabboli 
Got it. Yes, You are right. Thanks!

**Pull request merged**
